Proton: AdProviderIOS_ChartBoost.h File Reference
AdProviderIOS_ChartBoost.h File Reference
Functions
void ChartBoostIOS_ShowInterstitial (string location)
void ChartBoostIOS_CacheShowInterstitial (string location)
void ChartBoostIOS_StartSession (string appID, string appSignature)
void ChartBoostIOS_ShowMoreApps ()
void ChartBoostIOS_CacheShowMoreApps ()
Function Documentation
void ChartBoostIOS_CacheShowInterstitial (string location)
Referenced by AdProviderChartBoost::CacheShowInterstitial().
void ChartBoostIOS_CacheShowMoreApps ()
Referenced by AdProviderChartBoost::CacheShowMoreApps().
void ChartBoostIOS_ShowInterstitial (string location)
Referenced by AdProviderChartBoost::ShowInterstitial().
void ChartBoostIOS_ShowMoreApps ()
Referenced by AdProviderChartBoost::ShowMoreApps().
void ChartBoostIOS_StartSession (string appID, string appSignature)
Referenced by AdProviderChartBoost::OnAddToManager().