Proton: AndroidApp.cpp File Reference
AndroidApp.cpp File Reference
Functions
JNIEXPORT void JNICALL Java_com_rtsoft_shared_SharedActivity_nativeOnKey (JNIEnv *env, jobject thiz, jint type, jint keycode, jint c)
JNIEXPORT void JNICALL Java_com_rtsoft_shared_SharedActivity_nativeSendGUIEx (JNIEnv *env, jobject thiz, jint messageType, jint parm1, jint parm2, jint finger)
JNIEXPORT void JNICALL Java_com_rtsoft_shared_SharedActivity_nativeSendGUIStringEx (JNIEnv *env, jobject thiz, jint messageType, jint parm1, jint parm2, jint finger, jstring s)
JNIEXPORT void JNICALL Java_com_rtsoft_shared_SharedActivity_nativeOnAccelerometerUpdate (JNIEnv *env, jobject thiz, jfloat x, jfloat y, jfloat z)
JNIEXPORT void JNICALL Java_com_rtsoft_shared_SharedActivity_nativeOnTrackball (JNIEnv *env, jobject thiz, jfloat x, jfloat y)
JNIEXPORT void JNICALL Java_com_rtsoft_shared_SharedActivity_nativeOnJoyPadButtons (JNIEnv *env, jobject thiz, jint key, jint value)
JNIEXPORT void JNICALL Java_com_rtsoft_shared_SharedActivity_nativeOnJoyPad (JNIEnv *env, jobject thiz, jfloat xL, jfloat yL, jfloat xR, jfloat yR)
JNIEXPORT void JNICALL Java_com_rtsoft_shared_AppGLSurfaceView_nativePause (JNIEnv *env)
JNIEXPORT void JNICALL Java_com_rtsoft_shared_AppGLSurfaceView_nativeResume (JNIEnv *env)
JNIEXPORT void JNICALL Java_com_rtsoft_shared_AppGLSurfaceView_nativeOnTouch (JNIEnv *env, jobject thiz, jint action, jfloat x, jfloat y, jint finger)
JNIEXPORT int Java_com_rtsoft_shared_AppRenderer_nativeOSMessageGet (JNIEnv *env)
JNIEXPORT float Java_com_rtsoft_shared_AppRenderer_nativeGetLastOSMessageX (JNIEnv *env)
JNIEXPORT int Java_com_rtsoft_shared_AppRenderer_nativeGetLastOSMessageParm1 (JNIEnv *env)
JNIEXPORT void JNICALL Java_com_rtsoft_shared_AppRenderer_nativeInit (JNIEnv *env)
JNIEXPORT void JNICALL Java_com_rtsoft_shared_AppRenderer_nativeResize (JNIEnv *env, jobject thiz, jint w, jint h)
JNIEXPORT void JNICALL Java_com_rtsoft_shared_AppRenderer_nativeDone (JNIEnv *env)
JNIEXPORT void JNICALL Java_com_rtsoft_shared_AppRenderer_nativeUpdate (JNIEnv *env)
JNIEXPORT void JNICALL Java_com_rtsoft_shared_AppRenderer_nativeRender (JNIEnv *env)
Function Documentation
JNIEXPORT void JNICALL Java_com_rtsoft_shared_AppGLSurfaceView_nativeOnTouch (JNIEnv * env, jobject thiz, jint action, jfloat x, jfloat y, jint finger)
Definition at line 47 of file AndroidApp.cpp.
References AppOnTouch().
JNIEXPORT void JNICALL Java_com_rtsoft_shared_AppGLSurfaceView_nativePause (JNIEnv * env)
Definition at line 39 of file AndroidApp.cpp.
References AppPause().
JNIEXPORT void JNICALL Java_com_rtsoft_shared_AppGLSurfaceView_nativeResume (JNIEnv * env)
Definition at line 43 of file AndroidApp.cpp.
References AppResume().
JNIEXPORT void JNICALL Java_com_rtsoft_shared_AppRenderer_nativeDone (JNIEnv * env)
Definition at line 76 of file AndroidApp.cpp.
References AppDone().
JNIEXPORT int Java_com_rtsoft_shared_AppRenderer_nativeGetLastOSMessageParm1 (JNIEnv * env)
Definition at line 60 of file AndroidApp.cpp.
References AppGetLastOSMessageParm1().
JNIEXPORT float Java_com_rtsoft_shared_AppRenderer_nativeGetLastOSMessageX (JNIEnv * env)
Definition at line 56 of file AndroidApp.cpp.
References AppGetLastOSMessageX().
JNIEXPORT void JNICALL Java_com_rtsoft_shared_AppRenderer_nativeInit (JNIEnv * env)
Definition at line 65 of file AndroidApp.cpp.
References AppInit().
JNIEXPORT int Java_com_rtsoft_shared_AppRenderer_nativeOSMessageGet (JNIEnv * env)
Definition at line 52 of file AndroidApp.cpp.
References AppOSMessageGet().
JNIEXPORT void JNICALL Java_com_rtsoft_shared_AppRenderer_nativeRender (JNIEnv * env)
Definition at line 85 of file AndroidApp.cpp.
References AppRender().
JNIEXPORT void JNICALL Java_com_rtsoft_shared_AppRenderer_nativeResize (JNIEnv * env, jobject thiz, jint w, jint h)
Definition at line 70 of file AndroidApp.cpp.
References AppResize().
JNIEXPORT void JNICALL Java_com_rtsoft_shared_AppRenderer_nativeUpdate (JNIEnv * env)
Definition at line 81 of file AndroidApp.cpp.
References AppUpdate().
JNIEXPORT void JNICALL Java_com_rtsoft_shared_SharedActivity_nativeOnAccelerometerUpdate (JNIEnv * env, jobject thiz, jfloat x, jfloat y, jfloat z)
Definition at line 21 of file AndroidApp.cpp.
References AppOnAccelerometerUpdate().
JNIEXPORT void JNICALL Java_com_rtsoft_shared_SharedActivity_nativeOnJoyPad (JNIEnv * env, jobject thiz, jfloat xL, jfloat yL, jfloat xR, jfloat yR)
Definition at line 34 of file AndroidApp.cpp.
References AppOnJoypad().
JNIEXPORT void JNICALL Java_com_rtsoft_shared_SharedActivity_nativeOnJoyPadButtons (JNIEnv * env, jobject thiz, jint key, jint value)
Definition at line 30 of file AndroidApp.cpp.
References AppOnJoypadButtons().
JNIEXPORT void JNICALL Java_com_rtsoft_shared_SharedActivity_nativeOnKey (JNIEnv * env, jobject thiz, jint type, jint keycode, jint c)
Definition at line 9 of file AndroidApp.cpp.
References AppOnKey().
JNIEXPORT void JNICALL Java_com_rtsoft_shared_SharedActivity_nativeOnTrackball (JNIEnv * env, jobject thiz, jfloat x, jfloat y)
Definition at line 25 of file AndroidApp.cpp.
References AppOnTrackball().
JNIEXPORT void JNICALL Java_com_rtsoft_shared_SharedActivity_nativeSendGUIEx (JNIEnv * env, jobject thiz, jint messageType, jint parm1, jint parm2, jint finger)
Definition at line 13 of file AndroidApp.cpp.
References AppOnSendGUIEx().
JNIEXPORT void JNICALL Java_com_rtsoft_shared_SharedActivity_nativeSendGUIStringEx (JNIEnv * env, jobject thiz, jint messageType, jint parm1, jint parm2, jint finger, jstring s)
Definition at line 17 of file AndroidApp.cpp.
References AppOnSendGUIStringEx().