Proton: AndroidUtils.h File Reference
AndroidUtils.h File Reference
Functions
std::string GetAPKFile ()
JNIEnv * GetJavaEnv ()
char * GetAndroidMainClassName ()
void AppResize (JNIEnv *env, jobject thiz, jint w, jint h)
void AppUpdate (JNIEnv *env)
void AppRender (JNIEnv *env)
void AppDone (JNIEnv *env)
void AppPause (JNIEnv *env)
void AppInit (JNIEnv *env)
void AppResume (JNIEnv *env)
void AppOnTouch (JNIEnv *env, jobject jobj, jint action, jfloat x, jfloat y, jint finger)
void AppOnKey (JNIEnv *env, jobject jobj, jint type, jint keycode, jint c)
int AppOSMessageGet (JNIEnv *env)
float AppGetLastOSMessageX (JNIEnv *env)
float AppGetLastOSMessageY (JNIEnv *env)
void AppOnAccelerometerUpdate (JNIEnv *env, jobject jobj, jfloat x, jfloat y, jfloat z)
void AppOnTrackball (JNIEnv *env, jobject jobj, jfloat x, jfloat y)
void AppOnJoypad (JNIEnv *env, jobject jobj, jfloat xL, jfloat yL, jfloat xR, jfloat yR)
void AppOnJoypadButtons (JNIEnv *env, jobject jobj, jint key, jint value)
void AppOnJoypadConnection (JNIEnv *env, jobject jobj, jint connect)
void AppOnSendGUIEx (JNIEnv *env, jobject thiz, jint messageType, jint parm1, jint parm2, jint finger)
jstring AppGetLastOSMessageString (JNIEnv *env)
jstring AppGetLastOSMessageString2 (JNIEnv *env)
jstring AppGetLastOSMessageString3 (JNIEnv *env)
void AppOnSendGUIStringEx (JNIEnv *env, jobject thiz, jint messageType, jint parm1, jint parm2, jint finger, jstring s)
float AppGetLastOSMessageParm1 (JNIEnv *env)
Function Documentation
void AppDone (JNIEnv * env)
Definition at line 857 of file AndroidUtils.cpp.
References GetBaseApp(), IsBaseAppInitted(), BaseApp::Kill(), and LogMsg().
Referenced by Java_com_rtsoft_shared_AppRenderer_nativeDone().
float AppGetLastOSMessageParm1 (JNIEnv * env)
Definition at line 1156 of file AndroidUtils.cpp.
References OSMessage::m_parm1.
Referenced by Java_com_rtsoft_shared_AppRenderer_nativeGetLastOSMessageParm1().
jstring AppGetLastOSMessageString (JNIEnv * env)
Definition at line 1131 of file AndroidUtils.cpp.
References OSMessage::m_string.
jstring AppGetLastOSMessageString2 (JNIEnv * env)
Definition at line 1136 of file AndroidUtils.cpp.
References OSMessage::m_string2.
jstring AppGetLastOSMessageString3 (JNIEnv * env)
Definition at line 1141 of file AndroidUtils.cpp.
References OSMessage::m_string3.
float AppGetLastOSMessageX (JNIEnv * env)
Definition at line 1146 of file AndroidUtils.cpp.
References OSMessage::m_x.
Referenced by Java_com_rtsoft_shared_AppRenderer_nativeGetLastOSMessageX().
float AppGetLastOSMessageY (JNIEnv * env)
Definition at line 1151 of file AndroidUtils.cpp.
References OSMessage::m_y.
void AppInit (JNIEnv * env)
Definition at line 917 of file AndroidUtils.cpp.
References g_bSurfacesUnloaded, GetBaseApp(), BaseApp::InitializeGLDefaults(), LogMsg(), BaseApp::m_sig_loadSurfaces, and BaseApp::OnScreenSizeChange().
Referenced by AppUpdate(), and Java_com_rtsoft_shared_AppRenderer_nativeInit().
void AppOnAccelerometerUpdate (JNIEnv * env, jobject jobj, jfloat x, jfloat y, jfloat z)
Definition at line 1213 of file AndroidUtils.cpp.
References GetMessageManager(), MESSAGE_TYPE_GUI_ACCELEROMETER, and MessageManager::SendGUI().
Referenced by Java_com_rtsoft_shared_SharedActivity_nativeOnAccelerometerUpdate().
void AppOnJoypad (JNIEnv * env, jobject jobj, jfloat xL, jfloat yL, jfloat xR, jfloat yR)
Definition at line 1177 of file AndroidUtils.cpp.
References GetBaseApp(), GetMessageManager(), LogMsg(), BaseApp::m_sig_joypad_events, MESSAGE_TYPE_GUI_JOYPAD, and MessageManager::SendGUI().
Referenced by Java_com_rtsoft_shared_SharedActivity_nativeOnJoyPad().
void AppOnJoypadButtons (JNIEnv * env, jobject jobj, jint key, jint value)
Definition at line 1162 of file AndroidUtils.cpp.
References GetBaseApp(), GetMessageManager(), BaseApp::m_sig_joypad_events, MESSAGE_TYPE_GUI_JOYPAD_BUTTONS, and MessageManager::SendGUI().
Referenced by Java_com_rtsoft_shared_SharedActivity_nativeOnJoyPadButtons().
void AppOnJoypadConnection (JNIEnv * env, jobject jobj, jint connect)
Definition at line 1192 of file AndroidUtils.cpp.
References GetBaseApp(), GetMessageManager(), BaseApp::m_sig_joypad_events, MESSAGE_TYPE_GUI_JOYPAD_CONNECT, and MessageManager::SendGUI().
void AppOnKey (JNIEnv * env, jobject jobj, jint type, jint keycode, jint c)
Definition at line 1004 of file AndroidUtils.cpp.
References GetIsUsingNativeUI(), GetMessageManager(), LogMsg(), MESSAGE_TYPE_GUI_CHAR, MESSAGE_TYPE_GUI_CHAR_RAW, MessageManager::SendGUI(), SetIsUsingNativeUI(), VIRTUAL_DPAD_BUTTON_LEFT, VIRTUAL_DPAD_BUTTON_RIGHT, VIRTUAL_DPAD_BUTTON_UP, VIRTUAL_DPAD_LBUTTON, VIRTUAL_DPAD_RBUTTON, VIRTUAL_DPAD_SELECT, VIRTUAL_DPAD_START, and VIRTUAL_KEY_BACK.
Referenced by Java_com_rtsoft_shared_SharedActivity_nativeOnKey().
void AppOnSendGUIEx (JNIEnv * env, jobject thiz, jint messageType, jint parm1, jint parm2, jint finger)
Definition at line 988 of file AndroidUtils.cpp.
References GetMessageManager(), and MessageManager::SendGUIEx().
Referenced by Java_com_rtsoft_shared_SharedActivity_nativeSendGUIEx().
void AppOnSendGUIStringEx (JNIEnv * env, jobject thiz, jint messageType, jint parm1, jint parm2, jint finger, jstring s)
Definition at line 994 of file AndroidUtils.cpp.
References GetMessageManager(), and MessageManager::SendGUIStringEx().
Referenced by Java_com_rtsoft_shared_SharedActivity_nativeSendGUIStringEx().
void AppOnTouch (JNIEnv * env, jobject jobj, jint action, jfloat x, jfloat y, jint finger)
Definition at line 946 of file AndroidUtils.cpp.
References ACTION_DOWN, ACTION_MOVE, ACTION_UP, g_messageCache, LogMsg(), MESSAGE_TYPE_GUI_CLICK_END, MESSAGE_TYPE_GUI_CLICK_MOVE, MESSAGE_TYPE_GUI_CLICK_START, and MESSAGE_TYPE_UNKNOWN.
Referenced by Java_com_rtsoft_shared_AppGLSurfaceView_nativeOnTouch().
void AppOnTrackball (JNIEnv * env, jobject jobj, jfloat x, jfloat y)
Definition at line 1207 of file AndroidUtils.cpp.
References GetMessageManager(), MESSAGE_TYPE_GUI_TRACKBALL, and MessageManager::SendGUI().
Referenced by Java_com_rtsoft_shared_SharedActivity_nativeOnTrackball().
int AppOSMessageGet (JNIEnv * env)
Definition at line 1088 of file AndroidUtils.cpp.
References ConvertCoordinatesIfRequired(), g_messageCache, GetBaseApp(), GetMessageManager(), BaseApp::GetOSMessages(), IsBaseAppInitted(), OSMessage::m_type, OSMessage::MESSAGE_CHECK_CONNECTION, OSMessage::MESSAGE_NONE, MESSAGE_TYPE_OS_CONNECTION_CHECKED, RT_kCFStreamEventOpenCompleted, MessageManager::SendGUI(), and MessageManager::SendGUIEx().
Referenced by Java_com_rtsoft_shared_AppRenderer_nativeOSMessageGet().
void AppPause (JNIEnv * env)
Definition at line 864 of file AndroidUtils.cpp.
References g_musicPos, g_musicToPlay, g_pauseASAP, GetAudioManager(), GetBaseApp(), AudioManager::GetLastMusicFileName(), AudioManager::GetPos(), AudioManager::Kill(), LogMsg(), and BaseApp::m_sig_pre_enterbackground.
Referenced by Java_com_rtsoft_shared_AppGLSurfaceView_nativePause().
void AppRender (JNIEnv * env)
Definition at line 798 of file AndroidUtils.cpp.
References BaseApp::Draw(), g_pauseASAP, GetBaseApp(), GetPrimaryGLX(), GetPrimaryGLY(), and glViewport().
Referenced by Java_com_rtsoft_shared_AppRenderer_nativeRender().
void AppResize (JNIEnv * env, jobject thiz, jint w, jint h)
Definition at line 743 of file AndroidUtils.cpp.
References CreateDirectoryRecursively(), g_winVideoScreenX, g_winVideoScreenY, GetAPKFile(), GetAppCachePath(), GetBaseApp(), GetFileManager(), GetPrimaryGLX(), GetPrimaryGLY(), FileSystemZip::Init(), LogMsg(), FileManager::MountFileSystem(), BaseApp::OnScreenSizeChange(), ORIENTATION_PORTRAIT, FileSystemZip::SetRootDirectory(), and SetupScreenInfo().
Referenced by Java_com_rtsoft_shared_AppRenderer_nativeResize().
void AppResume (JNIEnv * env)
Definition at line 908 of file AndroidUtils.cpp.
References g_callAppResumeASAPTimer, GetSystemTimeTick(), GetTick(), LogMsg(), and TIMER_SYSTEM.
Referenced by Java_com_rtsoft_shared_AppGLSurfaceView_nativeResume().
void AppUpdate (JNIEnv * env)
Definition at line 807 of file AndroidUtils.cpp.
References AppInit(), g_bSurfacesUnloaded, g_callAppResumeASAPTimer, g_musicPos, g_musicToPlay, g_pauseASAP, GetAudioManager(), GetBaseApp(), GetSystemTimeTick(), AudioManager::Init(), AudioManager::Kill(), LogMsg(), BaseApp::m_sig_unloadSurfaces, BaseApp::OnEnterBackground(), BaseApp::OnEnterForeground(), AudioManager::Play(), AudioManager::SetPos(), and BaseApp::Update().
Referenced by Java_com_rtsoft_shared_AppRenderer_nativeUpdate().
char* GetAndroidMainClassName ()
Definition at line 133 of file AndroidUtils.cpp.
References StringReplace().
Referenced by CreateDirectoryRecursively(), AudioManagerAndroid::FadeOutMusic(), FireAchievement(), GetAPKFile(), GetAppCachePath(), GetClipboardText(), GetDeviceID(), AudioManagerAndroid::GetPos(), GetRegionString(), GetSavePathBasic(), IsAppInstalled(), AudioManagerAndroid::IsPlaying(), LaunchURL(), AudioManagerAndroid::Play(), AudioManagerAndroid::Preload(), AudioManagerAndroid::SetFrequency(), AudioManagerAndroid::SetMusicVol(), AudioManagerAndroid::SetPan(), AudioManagerAndroid::SetPos(), AudioManagerAndroid::SetVol(), AudioManagerAndroid::Stop(), AudioManagerAndroid::StopMusic(), AudioManagerAndroid::Vibrate(), and SoundObject::~SoundObject().
std::string GetAPKFile ()
Definition at line 196 of file AndroidUtils.cpp.
References GetAndroidMainClassName(), GetJavaEnv(), and LogMsg().
Referenced by AppResize().
JNIEnv* GetJavaEnv ()
Definition at line 119 of file AndroidUtils.cpp.
References g_pJavaVM, and LogError().
Referenced by CreateDirectoryRecursively(), AudioManagerAndroid::FadeOutMusic(), FireAchievement(), GetAPKFile(), GetAppCachePath(), GetClipboardText(), GetDeviceID(), AudioManagerAndroid::GetPos(), GetRegionString(), GetSavePathBasic(), IsAppInstalled(), AudioManagerAndroid::IsPlaying(), LaunchURL(), AudioManagerAndroid::Play(), AudioManagerAndroid::Preload(), AudioManagerAndroid::SetFrequency(), AudioManagerAndroid::SetMusicVol(), AudioManagerAndroid::SetPan(), AudioManagerAndroid::SetPos(), AudioManagerAndroid::SetVol(), AudioManagerAndroid::Stop(), AudioManagerAndroid::StopMusic(), AudioManagerAndroid::Vibrate(), and SoundObject::~SoundObject().