Proton: AndroidUtils.cpp File Reference
AndroidUtils.cpp File Reference
Enumerations
enum eAndroidActions {
ACTION_DOWN, ACTION_UP, ACTION_MOVE, ACTION_CANCEL,
ACTION_OUTSIDE
}
Functions
const char * GetAppName ()
const char * GetBundlePrefix ()
const char * GetBundleName ()
void StringReplace (const std::string &what, const std::string &with, std::string &in)
vector< string > StringTokenize (const string &theString, const string &theDelimiter)
JNIEXPORT jint JNICALL JNI_OnLoad (JavaVM *vm, void *reserved)
int GetPrimaryGLX ()
int GetPrimaryGLY ()
void LogMsg (const char *traceStr,...)
string GetBaseAppPath ()
JNIEnv * GetJavaEnv ()
char * GetAndroidMainClassName ()
string GetSavePathBasic ()
void SetPreferSDCardForStorage (bool bNew)
string GetSavePath ()
string GetAPKFile ()
string GetAppCachePath ()
void LaunchEmail (string subject, string content)
void FireAchievement (string achievement)
void LaunchURL (string url)
string GetClipboardText ()
bool IsIPhone3GS ()
bool IsDesktop ()
Checks if the currently emulated platform is a desktop platform.
ePlatformID GetPlatformID ()
Gets the platform id of the real running environment.
bool IsIphoneOriPad ()
bool IsIphone ()
bool IsIphone4 ()
string GetDeviceID ()
string GetMacAddress ()
bool IsIPAD ()
float GetDeviceOSVersion ()
eDeviceMemoryClass GetDeviceMemoryClass ()
bool CheckDay (const int year, const int month, const int day)
bool LaterThanNow (const int year, const int month, const int day)
unsigned int GetSystemTimeTick ()
double GetSystemTimeAccurate ()
unsigned int GetFreeMemory ()
void SetLastStringInput (string s)
std::string GetLastStringInput ()
eNetworkType IsNetReachable (string url)
int GetSystemData ()
void RemoveFile (string fileName, bool bAddSavePath)
string GetRegionString ()
bool IsAppInstalled (string packageName)
int GetDaysSinceDate (int month, int day, int year)
bool RTCreateDirectory (const std::string &dir_name)
void CreateDirectoryRecursively (string basePath, string path)
vector< string > GetDirectoriesAtPath (string path)
vector< string > GetFilesAtPath (string path)
bool RemoveDirectoryRecursively (string path)
bool CheckIfOtherAudioIsPlaying ()
void CreateAppCacheDirIfNeeded ()
void NotifyOSOfOrientationPreference (eOrientationMode orientation)
bool HasVibration ()
void AppResize (JNIEnv *env, jobject thiz, jint w, jint h)
void AppRender (JNIEnv *env)
void AppUpdate (JNIEnv *env)
void AppDone (JNIEnv *env)
void AppPause (JNIEnv *env)
void AppResume (JNIEnv *env)
void AppInit (JNIEnv *env)
void AppOnTouch (JNIEnv *env, jobject jobj, jint action, jfloat x, jfloat y, jint finger)
void AppOnSendGUIEx (JNIEnv *env, jobject thiz, jint messageType, jint parm1, jint parm2, jint finger)
void AppOnSendGUIStringEx (JNIEnv *env, jobject thiz, jint messageType, jint parm1, jint parm2, jint finger, jstring s)
void AppOnKey (JNIEnv *env, jobject jobj, jint type, jint keycode, jint c)
int AppOSMessageGet (JNIEnv *env)
jstring AppGetLastOSMessageString (JNIEnv *env)
jstring AppGetLastOSMessageString2 (JNIEnv *env)
jstring AppGetLastOSMessageString3 (JNIEnv *env)
float AppGetLastOSMessageX (JNIEnv *env)
float AppGetLastOSMessageY (JNIEnv *env)
float AppGetLastOSMessageParm1 (JNIEnv *env)
void AppOnJoypadButtons (JNIEnv *env, jobject jobj, jint key, jint value)
void AppOnJoypad (JNIEnv *env, jobject jobj, jfloat xL, jfloat yL, jfloat xR, jfloat yR)
void AppOnJoypadConnection (JNIEnv *env, jobject jobj, jint connect)
void AppOnTrackball (JNIEnv *env, jobject jobj, jfloat x, jfloat y)
void AppOnAccelerometerUpdate (JNIEnv *env, jobject jobj, jfloat x, jfloat y, jfloat z)
void ForceVideoUpdate ()
bool IsDirectoryDateNewerThan (string dir, int day, int month, int year)
Variables
JavaVM * g_pJavaVM = NULL
bool g_preferSDCardForUserStorage = false
uint32 g_callAppResumeASAPTimer = 0
bool g_pauseASAP = false
string g_musicToPlay
int g_musicPos = 0
bool g_bSurfacesUnloaded = false
OSMessage g_lastOSMessage
list< AndroidMessageCache > g_messageCache
int g_winVideoScreenX = 0
int g_winVideoScreenY = 0
string g_string
Enumeration Type Documentation
enum eAndroidActions
Enumerator:
ACTION_DOWN
ACTION_UP
ACTION_MOVE
ACTION_CANCEL
ACTION_OUTSIDE
Definition at line 937 of file AndroidUtils.cpp.
Function Documentation
void AppDone (JNIEnv * env)
Definition at line 857 of file AndroidUtils.cpp.
References GetBaseApp(), IsBaseAppInitted(), BaseApp::Kill(), and LogMsg().
Referenced by Java_com_rtsoft_shared_AppRenderer_nativeDone().
float AppGetLastOSMessageParm1 (JNIEnv * env)
Definition at line 1156 of file AndroidUtils.cpp.
References OSMessage::m_parm1.
Referenced by Java_com_rtsoft_shared_AppRenderer_nativeGetLastOSMessageParm1().
jstring AppGetLastOSMessageString (JNIEnv * env)
Definition at line 1131 of file AndroidUtils.cpp.
References OSMessage::m_string.
jstring AppGetLastOSMessageString2 (JNIEnv * env)
Definition at line 1136 of file AndroidUtils.cpp.
References OSMessage::m_string2.
jstring AppGetLastOSMessageString3 (JNIEnv * env)
Definition at line 1141 of file AndroidUtils.cpp.
References OSMessage::m_string3.
float AppGetLastOSMessageX (JNIEnv * env)
Definition at line 1146 of file AndroidUtils.cpp.
References OSMessage::m_x.
Referenced by Java_com_rtsoft_shared_AppRenderer_nativeGetLastOSMessageX().
float AppGetLastOSMessageY (JNIEnv * env)
Definition at line 1151 of file AndroidUtils.cpp.
References OSMessage::m_y.
void AppInit (JNIEnv * env)
Definition at line 917 of file AndroidUtils.cpp.
References g_bSurfacesUnloaded, GetBaseApp(), BaseApp::InitializeGLDefaults(), LogMsg(), BaseApp::m_sig_loadSurfaces, and BaseApp::OnScreenSizeChange().
Referenced by AppUpdate(), and Java_com_rtsoft_shared_AppRenderer_nativeInit().
void AppOnAccelerometerUpdate (JNIEnv * env, jobject jobj, jfloat x, jfloat y, jfloat z)
Definition at line 1213 of file AndroidUtils.cpp.
References GetMessageManager(), MESSAGE_TYPE_GUI_ACCELEROMETER, and MessageManager::SendGUI().
Referenced by Java_com_rtsoft_shared_SharedActivity_nativeOnAccelerometerUpdate().
void AppOnJoypad (JNIEnv * env, jobject jobj, jfloat xL, jfloat yL, jfloat xR, jfloat yR)
Definition at line 1177 of file AndroidUtils.cpp.
References GetBaseApp(), GetMessageManager(), LogMsg(), BaseApp::m_sig_joypad_events, MESSAGE_TYPE_GUI_JOYPAD, and MessageManager::SendGUI().
Referenced by Java_com_rtsoft_shared_SharedActivity_nativeOnJoyPad().
void AppOnJoypadButtons (JNIEnv * env, jobject jobj, jint key, jint value)
Definition at line 1162 of file AndroidUtils.cpp.
References GetBaseApp(), GetMessageManager(), BaseApp::m_sig_joypad_events, MESSAGE_TYPE_GUI_JOYPAD_BUTTONS, and MessageManager::SendGUI().
Referenced by Java_com_rtsoft_shared_SharedActivity_nativeOnJoyPadButtons().
void AppOnJoypadConnection (JNIEnv * env, jobject jobj, jint connect)
Definition at line 1192 of file AndroidUtils.cpp.
References GetBaseApp(), GetMessageManager(), BaseApp::m_sig_joypad_events, MESSAGE_TYPE_GUI_JOYPAD_CONNECT, and MessageManager::SendGUI().
void AppOnKey (JNIEnv * env, jobject jobj, jint type, jint keycode, jint c)
Definition at line 1004 of file AndroidUtils.cpp.
References GetIsUsingNativeUI(), GetMessageManager(), LogMsg(), MESSAGE_TYPE_GUI_CHAR, MESSAGE_TYPE_GUI_CHAR_RAW, MessageManager::SendGUI(), SetIsUsingNativeUI(), VIRTUAL_DPAD_BUTTON_LEFT, VIRTUAL_DPAD_BUTTON_RIGHT, VIRTUAL_DPAD_BUTTON_UP, VIRTUAL_DPAD_LBUTTON, VIRTUAL_DPAD_RBUTTON, VIRTUAL_DPAD_SELECT, VIRTUAL_DPAD_START, and VIRTUAL_KEY_BACK.
Referenced by Java_com_rtsoft_shared_SharedActivity_nativeOnKey().
void AppOnSendGUIEx (JNIEnv * env, jobject thiz, jint messageType, jint parm1, jint parm2, jint finger)
Definition at line 988 of file AndroidUtils.cpp.
References GetMessageManager(), and MessageManager::SendGUIEx().
Referenced by Java_com_rtsoft_shared_SharedActivity_nativeSendGUIEx().
void AppOnSendGUIStringEx (JNIEnv * env, jobject thiz, jint messageType, jint parm1, jint parm2, jint finger, jstring s)
Definition at line 994 of file AndroidUtils.cpp.
References GetMessageManager(), and MessageManager::SendGUIStringEx().
Referenced by Java_com_rtsoft_shared_SharedActivity_nativeSendGUIStringEx().
void AppOnTouch (JNIEnv * env, jobject jobj, jint action, jfloat x, jfloat y, jint finger)
Definition at line 946 of file AndroidUtils.cpp.
References ACTION_DOWN, ACTION_MOVE, ACTION_UP, g_messageCache, LogMsg(), MESSAGE_TYPE_GUI_CLICK_END, MESSAGE_TYPE_GUI_CLICK_MOVE, MESSAGE_TYPE_GUI_CLICK_START, and MESSAGE_TYPE_UNKNOWN.
Referenced by Java_com_rtsoft_shared_AppGLSurfaceView_nativeOnTouch().
void AppOnTrackball (JNIEnv * env, jobject jobj, jfloat x, jfloat y)
Definition at line 1207 of file AndroidUtils.cpp.
References GetMessageManager(), MESSAGE_TYPE_GUI_TRACKBALL, and MessageManager::SendGUI().
Referenced by Java_com_rtsoft_shared_SharedActivity_nativeOnTrackball().
int AppOSMessageGet (JNIEnv * env)
Definition at line 1088 of file AndroidUtils.cpp.
References ConvertCoordinatesIfRequired(), g_messageCache, GetBaseApp(), GetMessageManager(), BaseApp::GetOSMessages(), IsBaseAppInitted(), OSMessage::m_type, OSMessage::MESSAGE_CHECK_CONNECTION, OSMessage::MESSAGE_NONE, MESSAGE_TYPE_OS_CONNECTION_CHECKED, RT_kCFStreamEventOpenCompleted, MessageManager::SendGUI(), and MessageManager::SendGUIEx().
Referenced by Java_com_rtsoft_shared_AppRenderer_nativeOSMessageGet().
void AppPause (JNIEnv * env)
Definition at line 864 of file AndroidUtils.cpp.
References g_musicPos, g_musicToPlay, g_pauseASAP, GetAudioManager(), GetBaseApp(), AudioManager::GetLastMusicFileName(), AudioManager::GetPos(), AudioManager::Kill(), LogMsg(), and BaseApp::m_sig_pre_enterbackground.
Referenced by Java_com_rtsoft_shared_AppGLSurfaceView_nativePause().
void AppRender (JNIEnv * env)
Definition at line 798 of file AndroidUtils.cpp.
References BaseApp::Draw(), g_pauseASAP, GetBaseApp(), GetPrimaryGLX(), GetPrimaryGLY(), and glViewport().
Referenced by Java_com_rtsoft_shared_AppRenderer_nativeRender().
void AppResize (JNIEnv * env, jobject thiz, jint w, jint h)
Definition at line 743 of file AndroidUtils.cpp.
References CreateDirectoryRecursively(), g_winVideoScreenX, g_winVideoScreenY, GetAPKFile(), GetAppCachePath(), GetBaseApp(), GetFileManager(), GetPrimaryGLX(), GetPrimaryGLY(), FileSystemZip::Init(), LogMsg(), FileManager::MountFileSystem(), BaseApp::OnScreenSizeChange(), ORIENTATION_PORTRAIT, FileSystemZip::SetRootDirectory(), and SetupScreenInfo().
Referenced by Java_com_rtsoft_shared_AppRenderer_nativeResize().
void AppResume (JNIEnv * env)
Definition at line 908 of file AndroidUtils.cpp.
References g_callAppResumeASAPTimer, GetSystemTimeTick(), GetTick(), LogMsg(), and TIMER_SYSTEM.
Referenced by Java_com_rtsoft_shared_AppGLSurfaceView_nativeResume().
void AppUpdate (JNIEnv * env)
Definition at line 807 of file AndroidUtils.cpp.
References AppInit(), g_bSurfacesUnloaded, g_callAppResumeASAPTimer, g_musicPos, g_musicToPlay, g_pauseASAP, GetAudioManager(), GetBaseApp(), GetSystemTimeTick(), AudioManager::Init(), AudioManager::Kill(), LogMsg(), BaseApp::m_sig_unloadSurfaces, BaseApp::OnEnterBackground(), BaseApp::OnEnterForeground(), AudioManager::Play(), AudioManager::SetPos(), and BaseApp::Update().
Referenced by Java_com_rtsoft_shared_AppRenderer_nativeUpdate().
bool CheckDay (const int year, const int month, const int day)
Definition at line 381 of file AndroidUtils.cpp.
References LogMsg().
bool CheckIfOtherAudioIsPlaying ()
Definition at line 724 of file AndroidUtils.cpp.
void CreateAppCacheDirIfNeeded ()
Definition at line 729 of file AndroidUtils.cpp.
void CreateDirectoryRecursively (string basePath, string path)
Definition at line 584 of file AndroidUtils.cpp.
References GetAndroidMainClassName(), and GetJavaEnv().
Referenced by AppResize(), and RTCreateDirectory().
void FireAchievement (string achievement)
Definition at line 267 of file AndroidUtils.cpp.
References GetAndroidMainClassName(), GetJavaEnv(), and LogMsg().
void ForceVideoUpdate ()
Definition at line 1225 of file AndroidUtils.cpp.
References RenderBatcher::Flush(), and g_globalBatcher.
char* GetAndroidMainClassName ()
Definition at line 133 of file AndroidUtils.cpp.
References StringReplace().
Referenced by CreateDirectoryRecursively(), AudioManagerAndroid::FadeOutMusic(), FireAchievement(), GetAPKFile(), GetAppCachePath(), GetClipboardText(), GetDeviceID(), AudioManagerAndroid::GetPos(), GetRegionString(), GetSavePathBasic(), IsAppInstalled(), AudioManagerAndroid::IsPlaying(), LaunchURL(), AudioManagerAndroid::Play(), AudioManagerAndroid::Preload(), AudioManagerAndroid::SetFrequency(), AudioManagerAndroid::SetMusicVol(), AudioManagerAndroid::SetPan(), AudioManagerAndroid::SetPos(), AudioManagerAndroid::SetVol(), AudioManagerAndroid::Stop(), AudioManagerAndroid::StopMusic(), AudioManagerAndroid::Vibrate(), and SoundObject::~SoundObject().
string GetAPKFile ()
Definition at line 196 of file AndroidUtils.cpp.
References GetAndroidMainClassName(), GetJavaEnv(), and LogMsg().
Referenced by AppResize().
string GetAppCachePath ()
Definition at line 221 of file AndroidUtils.cpp.
Referenced by AppResize(), and GetSavePath().
const char* GetAppName ()
Referenced by initSDL_GLES(), and LogMsg().
string GetBaseAppPath ()
Definition at line 114 of file AndroidUtils.cpp.
Referenced by TextScanner::AppendToFile(), FileManager::Copy(), FileManager::FileExists(), FileManager::Get(), FileManager::GetFileSize(), FileManager::GetStreaming(), IrrlichtManager::GetTexture(), LoadFileIntoMemoryBasic(), LogMsg(), AudioManagerSDL::Play(), AudioManagerAndroid::Play(), AudioManagerBBX::Play(), AudioManagerSDL::Preload(), AudioManagerFlash::Preload(), AudioManagerFMOD::Preload(), AudioManagerAndroid::Preload(), AudioManagerAudiere::Preload(), and AudioManagerBBX::Preload().
const char* GetBundleName ()
Referenced by GetAppCachePath().
const char* GetBundlePrefix ()
Referenced by GetAppCachePath().
string GetClipboardText ()
Definition at line 294 of file AndroidUtils.cpp.
int GetDaysSinceDate (int month, int day, int year)
Definition at line 566 of file AndroidUtils.cpp.
string GetDeviceID ()
Definition at line 342 of file AndroidUtils.cpp.
eDeviceMemoryClass GetDeviceMemoryClass ()
Definition at line 376 of file AndroidUtils.cpp.
float GetDeviceOSVersion ()
Definition at line 370 of file AndroidUtils.cpp.
vector<string> GetDirectoriesAtPath (string path)
Definition at line 603 of file AndroidUtils.cpp.
References LogError().
vector<string> GetFilesAtPath (string path)
Definition at line 640 of file AndroidUtils.cpp.
References LogError().
unsigned int GetFreeMemory ()
Definition at line 477 of file AndroidUtils.cpp.
Referenced by BaseApp::Draw().
JNIEnv* GetJavaEnv ()
Definition at line 119 of file AndroidUtils.cpp.
References g_pJavaVM, and LogError().
Referenced by CreateDirectoryRecursively(), AudioManagerAndroid::FadeOutMusic(), FireAchievement(), GetAPKFile(), GetAppCachePath(), GetClipboardText(), GetDeviceID(), AudioManagerAndroid::GetPos(), GetRegionString(), GetSavePathBasic(), IsAppInstalled(), AudioManagerAndroid::IsPlaying(), LaunchURL(), AudioManagerAndroid::Play(), AudioManagerAndroid::Preload(), AudioManagerAndroid::SetFrequency(), AudioManagerAndroid::SetMusicVol(), AudioManagerAndroid::SetPan(), AudioManagerAndroid::SetPos(), AudioManagerAndroid::SetVol(), AudioManagerAndroid::Stop(), AudioManagerAndroid::StopMusic(), AudioManagerAndroid::Vibrate(), and SoundObject::~SoundObject().
std::string GetLastStringInput ()
Definition at line 489 of file AndroidUtils.cpp.
string GetMacAddress ()
Definition at line 359 of file AndroidUtils.cpp.
ePlatformID GetPlatformID ()
Gets the platform id of the real running environment.
The emulated platform can be different from this one.
Definition at line 322 of file AndroidUtils.cpp.
Referenced by AppendStringToFile(), TextScanner::AppendToFile(), GetEmulatedPlatformID(), and BaseApp::OnEnterBackground().
int GetPrimaryGLX ()
Definition at line 83 of file AndroidUtils.cpp.
Referenced by AppRender(), AppResize(), ConvertFakeScreenRectToReal(), Surface::CopyFromScreen(), RenderScissorComponent::FilterOnRender(), GetOGLPos(), IrrlichtManager::Init(), InitBaseScreenSizeFromPrimary(), initSDL_GLES(), main(), NeedToUseFakeScreenSize(), BaseApp::OnFullscreenToggleRequest(), SDLEventLoop(), SetLockedLandscape(), and SetupScreenInfo().
int GetPrimaryGLY ()
Definition at line 88 of file AndroidUtils.cpp.
Referenced by AppRender(), AppResize(), ConvertFakeScreenRectToReal(), Surface::CopyFromScreen(), RenderScissorComponent::FilterOnRender(), GetOGLPos(), IrrlichtManager::Init(), InitBaseScreenSizeFromPrimary(), initSDL_GLES(), main(), NeedToUseFakeScreenSize(), BaseApp::OnFullscreenToggleRequest(), SDLEventLoop(), SetLockedLandscape(), and SetupScreenInfo().
string GetRegionString ()
Definition at line 536 of file AndroidUtils.cpp.
Referenced by GetCountryCode().
string GetSavePath ()
Definition at line 175 of file AndroidUtils.cpp.
Referenced by VariantDB::Load(), LoadFileIntoMemoryBasic(), RemoveFile(), VariantDB::Save(), and TextScanner::SaveFile().
string GetSavePathBasic ()
Definition at line 150 of file AndroidUtils.cpp.
References GetAndroidMainClassName(), and GetJavaEnv().
Referenced by GetAppCachePath(), and GetSavePath().
int GetSystemData ()
Definition at line 499 of file AndroidUtils.cpp.
double GetSystemTimeAccurate ()
Definition at line 472 of file AndroidUtils.cpp.
Referenced by GameTimer::Reset(), and GameTimer::Update().
unsigned int GetSystemTimeTick ()
Definition at line 442 of file AndroidUtils.cpp.
Referenced by AppResume(), AppUpdate(), NetSocket::GetIdleTimeMS(), GetSystemTimeAccurate(), NetSocket::Init(), profile_begin(), profile_end(), profile_init(), profile_tally(), CRandom::Randomize(), NetSocket::SetSocket(), NetSocket::UpdateRead(), and NetSocket::UpdateWrite().
bool HasVibration ()
Definition at line 738 of file AndroidUtils.cpp.
bool IsAppInstalled (string packageName)
Definition at line 553 of file AndroidUtils.cpp.
References GetAndroidMainClassName(), and GetJavaEnv().
bool IsDesktop ()
Checks if the currently emulated platform is a desktop platform.
Definition at line 316 of file AndroidUtils.cpp.
Referenced by main().
bool IsDirectoryDateNewerThan (string dir, int day, int month, int year)
Definition at line 1231 of file AndroidUtils.cpp.
References LogMsg().
bool IsIPAD ()
Definition at line 365 of file AndroidUtils.cpp.
Referenced by SetProtonPixelScaleFactor().
bool IsIphone ()
Definition at line 332 of file AndroidUtils.cpp.
bool IsIPhone3GS ()
Definition at line 311 of file AndroidUtils.cpp.
bool IsIphone4 ()
Definition at line 337 of file AndroidUtils.cpp.
bool IsIphoneOriPad ()
Definition at line 327 of file AndroidUtils.cpp.
eNetworkType IsNetReachable (string url)
Definition at line 494 of file AndroidUtils.cpp.
References C_NETWORK_WIFI.
JNIEXPORT jint JNICALL JNI_OnLoad (JavaVM * vm, void * reserved)
Definition at line 67 of file AndroidUtils.cpp.
References g_pJavaVM, and LogMsg().
bool LaterThanNow (const int year, const int month, const int day)
Definition at line 400 of file AndroidUtils.cpp.
References LogMsg().
void LaunchEmail (string subject, string content)
Definition at line 263 of file AndroidUtils.cpp.
void LaunchURL (string url)
Definition at line 281 of file AndroidUtils.cpp.
References GetAndroidMainClassName(), GetJavaEnv(), and LogMsg().
void LogMsg (const char * traceStr, ...)
Definition at line 93 of file AndroidUtils.cpp.
Referenced by L_ParticleEffect::add(), GamepadManager::AddGamepad(), AdManager::AddProvider(), GamepadManager::AddProvider(), MySQLManager::AddSelectResults(), AppDone(), AppInit(), AppOnJoypad(), AppOnKey(), AppOnTouch(), AppPause(), AppResize(), AppResume(), AppUpdate(), IAPManager::BuyItem(), AdProvider::CacheShowInterstitial(), AdProviderChartBoost::CacheShowInterstitial(), AdProvider::CacheShowMoreApps(), ChangeEmulationOrientationIfPossible(), CheckDay(), CompressFile(), Gamepad::ConnectToArcadeComponent(), FileManager::Copy(), RTFont::CountCharsThatFitX(), L_ParticleEffect::create_particle(), DestroyUnusedTextures(), MessageManager::DumpMessages(), TextScanner::DumpToLog(), FireAchievement(), RenderBatcher::Flush(), FMOD_ERROR_CHECK(), GenerateSmartBuffer(), GetAPKFile(), GetAppCachePath(), GetDaysSinceDate(), GetDirectoriesAtPath(), GetFileSize(), GetFilterSetting(), AudioManagerAndroid::GetPos(), GetSavePath(), ResourceManager::GetSpriteAnimationSet(), FileSystemZip::GetStreaming(), ResourceManager::GetSurfaceResource(), AdManager::GetTapPointsFromServer(), glActiveTexture(), glClientActiveTexture(), glClipPlanef(), glColorMask(), glCopyTexSubImage2D(), glDeleteTextures(), glDrawArraysEx(), glEnableClientStateEx(), glEnableEx(), GLFlashAdaptor_Initialize(), GLFlashAdaptor_Kill(), glGetBooleanv(), glGetFloatv(), glGetIntegerv(), glLightf(), glLightfv(), glLightModelf(), glLightModelfv(), glPopMatrix(), glReadPixels(), glTexEnvi(), glTexImage2D(), glTexParameteri(), glTexSubImage2D(), IAPManager::HandleIAPBuyResult(), IAPManager::HandleItemUpdateState(), IAPManager::HandlePurchaseListReply(), MySQLManager::Init(), GamepadProvideriCade::Init(), AudioManagerSDL::Init(), GamepadProviderMoga::Init(), FileSystemZip::Init(), IrrlichtManager::Init(), AudioManagerFlash::Init(), GamepadProviderDirectX::Init(), AdManager::Init(), AudioManagerBBX::Init(), FileCopier::Init(), BaseApp::Init(), FileCopier::InitAndCopy(), Surface::InitBlankSurface(), RTGLESExt::InitExtensions(), Surface::InitFromSoftSurface(), NetSocket::InitHost(), InitSDL(), initSDL_GLES(), AdManager::InitTapjoy(), IsDirectoryDateNewerThan(), JNI_OnLoad(), AudioManagerAndroid::Kill(), AudioManagerSDL::KillCachedSounds(), AudioManagerFlash::KillCachedSounds(), AudioManagerFMOD::KillCachedSounds(), AudioManagerAndroid::KillCachedSounds(), AudioManagerAudiere::KillCachedSounds(), AudioManagerBBX::KillCachedSounds(), LaterThanNow(), LaunchURL(), RTFont::Load(), VariantDB::Load(), Surface::LoadFile(), Surface::LoadFileFromMemory(), LogError(), main(), RTFont::MeasureText(), Native_Update(), DPadComponent::OnAdd(), AdProviderFlurry::OnAddToManager(), AdProviderChartBoost::OnAddToManager(), Gamepad::OnButton(), BaseApp::OnEnterBackground(), BaseApp::OnEnterForeground(), Gamepad::OnHat(), GamepadMoga::OnJoypadEvent(), IrrlichtManager::OnLoadSurfaces(), Surface::OnLoadSurfaces(), GamepadProvideriCade::OnLostiCadeConnection(), BaseApp::OnMemoryWarning(), AdManager::OnMessage(), IrrlichtManager::OnUnloadSurfaces(), Surface::OnUnloadSurfaces(), TyperComponent::OnUpdate(), StreamingInstanceFile::Open(), AdManager::OpenTapjoyOfferWall(), AudioManagerSDL::Play(), AudioManagerFlash::Play(), AudioManagerFMOD::Play(), AudioManagerBBX::Play(), AudioManagerSDL::Preload(), AudioManagerFlash::Preload(), AudioManagerFMOD::Preload(), AudioManagerAndroid::Preload(), AudioManagerAudiere::Preload(), AudioManagerBBX::Preload(), VariantDB::Print(), BaseApp::PrintGLString(), Entity::PrintTreeAsText(), StreamingInstanceFile::Read(), StreamingInstance::ReadLineOfText(), RemoveFile(), GamepadManager::RemoveProviderByName(), BaseApp::ResetTouches(), RTCreateDirectory(), ProtonTester::runAllTests(), Variant::Save(), SDLEventLoop(), Gamepad::SendArcadeDirectionByDegrees(), Gamepad::SendArcadeDirectionByKey(), IAPManager::SendUnexpectedPurchaseSignal(), SeparateStringSTL(), VariantList::SerializeFromMem(), Gamepad::SetAxis(), SetFilterSetting(), BaseApp::SetManualRotationMode(), AudioManagerFlash::SetMusicVol(), AudioManagerBBX::SetMusicVol(), AudioManagerAndroid::SetPos(), AdManager::SetTapjoyFeatureAppVisible(), SetupScreenInfo(), AdProvider::ShowInterstitial(), AdProviderChartBoost::ShowInterstitial(), AdProvider::ShowMoreApps(), AudioManagerBBX::StopMusic(), IAPManager::SyncPurchases(), AudioManagerFlash::Testy(), IAPManager::Update(), NetSocket::UpdateRead(), AudioManager::Vibrate(), Gamepad::~Gamepad(), and InputTextRenderComponent::~InputTextRenderComponent().
void NotifyOSOfOrientationPreference (eOrientationMode orientation)
Definition at line 734 of file AndroidUtils.cpp.
Referenced by SetupScreenInfo().
bool RemoveDirectoryRecursively (string path)
Definition at line 675 of file AndroidUtils.cpp.
References LogError().
Referenced by RemoveDirectoryRecursively().
void RemoveFile (string fileName, bool bAddSavePath)
Definition at line 504 of file AndroidUtils.cpp.
References GetSavePath(), LogError(), and LogMsg().
Referenced by VariantDB::Load(), main(), UnpackArchiveComponent::OnRemove(), NetHTTP::Reset(), FileCopier::~FileCopier(), and NetHTTP::~NetHTTP().
bool RTCreateDirectory (const std::string & dir_name)
Definition at line 573 of file AndroidUtils.cpp.
References CreateDirectoryRecursively(), and LogMsg().
Referenced by CreateDirectoryRecursively().
void SetLastStringInput (string s)
Definition at line 484 of file AndroidUtils.cpp.
Referenced by PreloadKeyboard().
void SetPreferSDCardForStorage (bool bNew)
Definition at line 170 of file AndroidUtils.cpp.
References g_preferSDCardForUserStorage.
void StringReplace (const std::string & what, const std::string & with, std::string & in)
Definition at line 426 of file ResourceUtils.cpp.
Referenced by BreakDownURLIntoPieces(), CreateDirectoryRecursively(), TextScanner::DumpToLog(), GetAndroidMainClassName(), AudioManagerFlash::Play(), AudioManagerAndroid::Play(), AudioManagerFlash::Preload(), AudioManagerAndroid::Preload(), TextScanner::Replace(), ReplaceMP3(), ReplaceWithDeviceNameInFileName(), ReplaceWithLargeInFileName(), ReplaceWithLargeInFileNameAndOSSpecific(), and TextScanner::SetupFromMemoryAddress().
vector<string> StringTokenize (const string & theString, const string & theDelimiter)
Definition at line 337 of file MiscUtils.cpp.
Referenced by CreateDirectoryRecursively(), TextScanner::GetMultipleLineStrings(), TextScanner::GetParmString(), PeekFirstParmString(), PopFirstParmString(), TextScanner::SetupFromMemoryAddress(), and TextScanner::TokenizeLine().
Variable Documentation
bool g_bSurfacesUnloaded = false
Definition at line 30 of file AndroidUtils.cpp.
Referenced by AppInit(), and AppUpdate().
uint32 g_callAppResumeASAPTimer = 0
Definition at line 25 of file AndroidUtils.cpp.
Referenced by AppResume(), and AppUpdate().
OSMessage g_lastOSMessage
Definition at line 36 of file AndroidUtils.cpp.
list<AndroidMessageCache> g_messageCache
Definition at line 51 of file AndroidUtils.cpp.
Referenced by AppOnTouch(), and AppOSMessageGet().
int g_musicPos = 0
Definition at line 28 of file AndroidUtils.cpp.
Referenced by AppPause(), and AppUpdate().
string g_musicToPlay
Definition at line 27 of file AndroidUtils.cpp.
Referenced by AppPause(), and AppUpdate().
bool g_pauseASAP = false
Definition at line 26 of file AndroidUtils.cpp.
Referenced by AppPause(), AppRender(), and AppUpdate().
JavaVM * g_pJavaVM = NULL
Definition at line 53 of file AndroidUtils.cpp.
Referenced by GetJavaEnv(), and JNI_OnLoad().
bool g_preferSDCardForUserStorage = false
Definition at line 23 of file AndroidUtils.cpp.
Referenced by GetSavePath(), and SetPreferSDCardForStorage().
string g_string
Definition at line 482 of file AndroidUtils.cpp.
Referenced by GetLastStringInput(), and SetLastStringInput().
int g_winVideoScreenX = 0
Definition at line 55 of file AndroidUtils.cpp.
Referenced by AppResize(), GetPrimaryGLX(), and main().
int g_winVideoScreenY = 0
Definition at line 56 of file AndroidUtils.cpp.
Referenced by AppResize(), GetPrimaryGLY(), and main().