Proton: AudioManagerFMOD.h File Reference
AudioManagerFMOD.h File Reference
Classes
class SoundObject
class AudioManagerFMOD
Functions
void FMOD_ERROR_CHECK (FMOD_RESULT result)
Function Documentation
void FMOD_ERROR_CHECK (FMOD_RESULT result)
Definition at line 8 of file AudioManagerFMOD.cpp.
References LogMsg().
Referenced by AudioManagerFMOD::Init(), AudioManagerFMOD::Kill(), AudioManagerFMOD::Play(), and AudioManagerFMOD::Preload().