Proton: BaseApp.h File Reference
BaseApp.h File Reference
Classes
struct OSMessage
class TouchTrackInfo
class BaseApp
Enumerations
enum eFont { FONT_SMALL, FONT_LARGE, FONT_FIXED, FONT_BASE_COUNT }
enum eInputMode { INPUT_MODE_NORMAL, INPUT_MODE_SEPARATE_MOVE_TOUCHES }
Functions
BaseApp * GetBaseApp ()
bool IsBaseAppInitted ()
MessageManager * GetMessageManager ()
FileManager * GetFileManager ()
AudioManager * GetAudioManager ()
Entity * GetEntityRoot ()
GamepadManager * GetGamepadManager ()
ResourceManager * GetResourceManager ()
unsigned int GetTick (eTimingSystem timingSystem=GetBaseApp()->GetActiveTimingSystem())
eTimingSystem GetTiming ()
Variables
RenderBatcher g_globalBatcher
Enumeration Type Documentation
enum eFont
Enumerator:
FONT_SMALL
FONT_LARGE
FONT_FIXED
FONT_BASE_COUNT
Definition at line 40 of file BaseApp.h.
enum eInputMode
Enumerator:
INPUT_MODE_NORMAL
INPUT_MODE_SEPARATE_MOVE_TOUCHES
Definition at line 140 of file BaseApp.h.
Function Documentation
AudioManager* GetAudioManager ()
Referenced by AppPause(), AppUpdate(), BaseApp::Draw(), LoopingSound::Init(), BaseApp::Init(), BaseApp::OnEnterBackground(), BaseApp::OnEnterForeground(), BaseApp::OnMessage(), LoopingSound::SetMoving(), LoopingSound::Update(), and BaseApp::Update().
BaseApp* GetBaseApp ()
Referenced by AppDone(), AppInit(), AppOnJoypad(), AppOnJoypadButtons(), AppOnJoypadConnection(), AppOSMessageGet(), AppPause(), AppRender(), AppResize(), AppUpdate(), IrrlichtManager::BeginScene(), Surface::Blit(), RenderBatcher::BlitEx(), Surface::BlitEx(), SoftSurface::BlitFromScreen(), IAPManager::BuyItem(), AdProviderChartBoost::CacheShowInterstitial(), AdProviderChartBoost::CacheShowMoreApps(), AdManager::CacheTapjoyAd(), AdManager::CacheTapjoyFeaturedApp(), ProtonPainter::CalculateTextDrawSize(), ConvertCoordinatesIfRequired(), ConvertFakeScreenRectToReal(), CreateCheckbox(), CreateInputTextEntity(), CreateSlider(), DestroyUnusedTextures(), ProtonPainter::DrawText(), EnforceMinimumFontLineToScreenRatio(), RenderScissorComponent::FilterOnRender(), GamepadMoga::GamepadMoga(), GenerateFillRect(), GenerateSetPerspectiveFOV(), GetEntityRoot(), GetFontAndScaleToFitThisLinesPerScreenY(), GetFontAndScaleToFitThisPixelHeight(), GetFontAndScaleToFitThisStringInWidthPixels(), ProtonPainter::GetFontHeight(), GetOGLPos(), GetResourceManager(), AdManager::GetTapPointsFromServer(), GetTick(), GetTiming(), TouchDeviceEmulatorPointerEventHandler::handlePointerDownEvent(), TouchDeviceEmulatorPointerEventHandler::handlePointerMoveEvent(), TouchDeviceEmulatorPointerEventHandler::handlePointerUpEvent(), IrrlichtManager::Init(), GamepadiCade::Init(), Surface::InitBlankSurface(), AdManager::InitTapjoy(), SoftSurface::Kill(), Surface::Kill(), FocusInputComponent::LinkMoveMessages(), FocusInputComponent::LinkRawMessages(), RTFont::Load(), Surface::LoadFileFromMemory(), LogError(), LogMsg(), main(), AdManager::ModifyTapPoints(), Native_OnGotFocus(), Native_OnLostFocus(), Native_Update(), SelectButtonWithCustomInputComponent::OnAdd(), HTTPComponent::OnAdd(), FocusUpdateComponent::OnAdd(), FocusRenderComponent::OnAdd(), InterpolateComponent::OnAdd(), TyperComponent::OnAdd(), TrailRenderComponent::OnAdd(), TextBoxRenderComponent::OnAdd(), LogDisplayComponent::OnAdd(), FocusInputComponent::OnAdd(), InputTextRenderComponent::OnAdd(), ArcadeInputComponent::OnAdd(), AdProviderFlurry::OnAddToManager(), AdProviderChartBoost::OnAddToManager(), InterpolateComponent::OnDurationChanged(), BaseApp::OnEnterForeground(), BaseApp::OnFullscreenToggleRequest(), TouchHandlerArcadeComponent::OnInput(), TouchDragComponent::OnInput(), MoveButtonState::OnPress(), MoveButtonState::OnPressToggle(), InterpolateComponent::OnUpdate(), TyperComponent::OnUpdate(), AdManager::OpenTapjoyOfferWall(), PreloadKeyboard(), MoveButtonState::ReleaseIfNeeded(), IrrlichtManager::Render2D(), RenderSpinningTriangle(), RenderTexturedGLTriangle(), RenderTexturedGLTriangleWithDrawElements(), TouchDragComponent::ResetLastPos(), VariantTuner::resetTunableVariant(), RotateGLIfNeeded(), SoftSurface::Scale(), SDLEventLoop(), SendFakeInputMessageToEntity(), IAPManager::sendPurchaseMessage(), BaseApp::SetAccelerometerUpdateHz(), BaseApp::SetAllowScreenDimming(), Message::SetDeliveryTime(), BaseApp::SetFPSLimit(), SetIsUsingNativeUI(), SetLockedLandscape(), AdManager::SetTapjoyAdVisible(), AdManager::SetTapjoyFeatureAppVisible(), VariantTuner::setTunableVariant(), AdManager::SetupBanner(), SetupScreenInfo(), BaseApp::SetVideoMode(), AdProviderChartBoost::ShowInterstitial(), AdProviderChartBoost::ShowMoreApps(), SinGamePulseByMS(), SinPulseByMS(), IAPManager::SyncPurchases(), AdProviderFlurry::TrackingLog(), AdProviderFlurry::TrackingOnPageView(), NetHTTP::Update(), MessageManager::Update(), ScrollComponent::~ScrollComponent(), TouchDragComponent::~TouchDragComponent(), and TouchStripComponent::~TouchStripComponent().
Entity* GetEntityRoot ()
Definition at line 9 of file BaseApp.cpp.
References GetBaseApp(), BaseApp::GetEntityRoot(), and IsBaseAppInitted().
Referenced by DestroyUnusedTextures(), SetConsole(), and ToggleConsole().
FileManager* GetFileManager ()
Referenced by AppResize(), FileManager::Copy(), FileExists(), GetHashOfFile(), FileCopier::Init(), FileInstance::Load(), DPadComponent::OnAdd(), and AudioManagerFlash::Preload().
GamepadManager* GetGamepadManager ()
Referenced by GamepadProvideriCade::Init(), and GamepadProviderMoga::Init().
MessageManager* GetMessageManager ()
Referenced by AddFocusIfNeeded(), AnimateEntity(), AnimateStopEntity(), AnimateStopEntityAndSetFrame(), AppOnAccelerometerUpdate(), AppOnJoypad(), AppOnJoypadButtons(), AppOnJoypadConnection(), AppOnKey(), AppOnSendGUIEx(), AppOnSendGUIStringEx(), AppOnTrackball(), AppOSMessageGet(), CreateScrollingTextBoxEntity(), DisableComponentByName(), EnableAllButtonsEntity(), EnableComponentByName(), PassThroughPointerEventHandler::handlePointerDownEvent(), TouchDeviceEmulatorPointerEventHandler::handlePointerDownEvent(), PassThroughPointerEventHandler::handlePointerMoveEvent(), TouchDeviceEmulatorPointerEventHandler::handlePointerMoveEvent(), PassThroughPointerEventHandler::handlePointerUpEvent(), TouchDeviceEmulatorPointerEventHandler::handlePointerUpEvent(), KillEntity(), main(), Native_SendGUIEx(), Native_Update(), DPADButton::OnButtonChange(), OnShowTextMessage(), AudioManagerAndroid::Play(), BaseApp::ResetTouches(), SDLEventLoop(), SendFakeButtonPushToEntity(), SendFakeInputMessageToEntity(), SetFilterSetting(), SetOverlayImageEntity(), Entity::SetTaggedForDeletion(), SetupInterpolateComponent(), ShowTextMessage(), SpriteAnimationUtils::StartAnimationEntity(), IAPManager::TestDelayedIAP(), TypeTextLabelEntity(), IAPManager::Update(), and BaseApp::Update().
ResourceManager* GetResourceManager ()
Definition at line 485 of file BaseApp.cpp.
References GetBaseApp(), and BaseApp::GetResourceManager().
Referenced by CreateCheckbox().
unsigned int GetTick (eTimingSystem timingSystem = GetBaseApp()->GetActiveTimingSystem())
Definition at line 480 of file BaseApp.cpp.
References GetBaseApp(), and BaseApp::GetTickTimingSystem().
Referenced by AppResume(), DPadComponent::OnAdd(), MoveButtonState::OnPress(), MoveButtonState::OnPressToggle(), TyperComponent::OnUpdate(), IAPManager::sendPurchaseMessage(), LoopingSound::SetMoving(), MySQLManager::Update(), LoopingSound::Update(), AdManager::Update(), IAPManager::Update(), NetHTTP::Update(), and MoveButtonState::Update().
eTimingSystem GetTiming ()
Definition at line 57 of file BaseApp.cpp.
bool IsBaseAppInitted ()
Definition at line 19 of file BaseApp.cpp.
References g_isBaseAppInitted.
Referenced by BaseApp::AddOSMessage(), AppDone(), AppOSMessageGet(), GetEntityRoot(), SoftSurface::Kill(), LogMsg(), and SetupScreenInfo().
Variable Documentation
RenderBatcher g_globalBatcher
Definition at line 15 of file BaseApp.cpp.
Referenced by L_ParticleEffect::draw(), L_Particle::draw(), RTFont::DrawScaled(), RTFont::DrawScaledSolidColor(), RTFont::DrawWrapped(), RenderScissorComponent::FilterOnRender(), ForceVideoUpdate(), RenderScissorComponent::PostOnRender(), RenderClipComponent::PostOnRender(), PrepareForGL(), RemoveOrthoRenderSize(), Surface::SetupForRender(), and SetupOrtho().