Proton: BaseApp.cpp File Reference
BaseApp.cpp File Reference
Functions
Entity * GetEntityRoot ()
bool IsBaseAppInitted ()
eTimingSystem GetTiming ()
void DrawConsole ()
void LogError (const char *traceStr,...)
unsigned int GetTick (eTimingSystem timingSystem)
ResourceManager * GetResourceManager ()
Variables
RenderBatcher g_globalBatcher
bool g_isLoggerInitted = false
bool g_isBaseAppInitted = false
bool g_bIsFullScreen
Function Documentation
void DrawConsole ()
Definition at line 126 of file BaseApp.cpp.
Referenced by BaseApp::Draw().
Entity* GetEntityRoot ()
Definition at line 9 of file BaseApp.cpp.
References GetBaseApp(), BaseApp::GetEntityRoot(), and IsBaseAppInitted().
Referenced by DestroyUnusedTextures(), SetConsole(), and ToggleConsole().
ResourceManager* GetResourceManager ()
Definition at line 485 of file BaseApp.cpp.
References GetBaseApp(), and BaseApp::GetResourceManager().
Referenced by CreateCheckbox().
unsigned int GetTick (eTimingSystem timingSystem)
Definition at line 480 of file BaseApp.cpp.
References GetBaseApp(), and BaseApp::GetTickTimingSystem().
Referenced by AppResume(), DPadComponent::OnAdd(), MoveButtonState::OnPress(), MoveButtonState::OnPressToggle(), TyperComponent::OnUpdate(), IAPManager::sendPurchaseMessage(), LoopingSound::SetMoving(), MySQLManager::Update(), LoopingSound::Update(), AdManager::Update(), IAPManager::Update(), NetHTTP::Update(), and MoveButtonState::Update().
eTimingSystem GetTiming ()
Definition at line 57 of file BaseApp.cpp.
References BaseApp::GetActiveTimingSystem(), and GetBaseApp().
bool IsBaseAppInitted ()
Definition at line 19 of file BaseApp.cpp.
References g_isBaseAppInitted.
Referenced by BaseApp::AddOSMessage(), AppDone(), AppOSMessageGet(), GetEntityRoot(), SoftSurface::Kill(), LogMsg(), and SetupScreenInfo().
void LogError (const char * traceStr, ...)
Definition at line 460 of file BaseApp.cpp.
Referenced by AdManager::AddProvider(), GamepadManager::AddProvider(), MySQLManager::AddSelectResults(), Entity::CallFunctionRecursivelyWithUpdatedVar(), StreamingInstanceZip::Close(), FileManager::Copy(), CreateCheckbox(), CreateOverlayEntity(), MySQLManager::DoesTableExist(), MySQLManager::DoResultsExist(), FilterInputComponent::FilterOnInput(), FileSystemZip::Get(), FileManager::Get(), RTFont::GetColorFromString(), FileSystemZip::GetContents(), GetDirectoriesAtPath(), GetFilesAtPath(), FileSystemZip::GetFileSize(), GetJavaEnv(), TextScanner::GetParmString(), MySQLManager::GetTableRecordCount(), glDrawArraysEx(), glMatrixMode(), glTexImage2D(), glVertexPointerEx(), GamepadDirectX::Init(), FileSystemZip::Init(), IrrlichtManager::Init(), GamepadProviderDirectX::Init(), FileCopier::Init(), NetSocket::InitHost(), Variant::Interpolate(), RTFont::Load(), SpriteAnimationSet::LoadFile(), SoftSurface::LoadFileFromMemory(), Surface::LoadFileFromMemory(), main(), RTFont::MeasureTextAndAddByLinesIntoDeque(), Entity::MoveComponentToBottomByAddress(), Entity::MoveComponentToTopByAddress(), Entity::MoveEntityToBottomByAddress(), Entity::MoveEntityToTopByAddress(), AdProviderFlurry::OnAddToManager(), AdProviderChartBoost::OnAddToManager(), InterpolateComponent::OnDurationChanged(), InterpolateComponent::OnUpdate(), InterpolateComponent::OnVarNameChanged(), JPGSurfaceLoader::output_message(), AudioManagerSDL::Play(), AudioManagerFlash::Play(), AudioManagerFMOD::Play(), AudioManagerAndroid::Play(), AudioManagerBBX::Play(), AudioManagerAudiere::Play(), MySQLManager::Query(), StreamingInstanceZip::Read(), RemoveDirectoryRecursively(), RemoveFile(), RenderClipComponent::RenderClipComponent(), ResizeScrollBounds(), VariantDB::Save(), TextScanner::SaveFile(), rtRectf::Scale(), SpriteAnimationUtils::SetAnimationName(), MySQLManager::ShowError(), SpriteAnimationUtils::StartAnimationEntity(), UpdateBlendModes(), SoftSurface::WriteBMPOut(), and SoftSurface::WriteRawDataOut().
Variable Documentation
bool g_bIsFullScreen
Referenced by BaseApp::OnFullscreenToggleRequest().
RenderBatcher g_globalBatcher
Definition at line 15 of file BaseApp.cpp.
Referenced by L_ParticleEffect::draw(), L_Particle::draw(), RTFont::DrawScaled(), RTFont::DrawScaledSolidColor(), RTFont::DrawWrapped(), RenderScissorComponent::FilterOnRender(), ForceVideoUpdate(), RenderScissorComponent::PostOnRender(), RenderClipComponent::PostOnRender(), PrepareForGL(), RemoveOrthoRenderSize(), Surface::SetupForRender(), and SetupOrtho().
bool g_isBaseAppInitted = false
Definition at line 17 of file BaseApp.cpp.
Referenced by BaseApp::BaseApp(), IsBaseAppInitted(), and BaseApp::Kill().
bool g_isLoggerInitted = false
Definition at line 16 of file BaseApp.cpp.
Referenced by BaseApp::BaseApp(), and BaseApp::~BaseApp().