Proton: GamepadProviderDirectX Class Reference
GamepadProviderDirectX Class Reference
#include <GamepadProviderDirectX.h>
Public Member Functions
GamepadProviderDirectX ()
virtual ~GamepadProviderDirectX ()
virtual string GetName ()
virtual bool Init ()
virtual void Kill ()
virtual void Update ()
HWND GetHWND ()
LPDIRECTINPUT8 GetDInput ()
Detailed Description
Definition at line 47 of file GamepadProviderDirectX.h.
Constructor & Destructor Documentation
GamepadProviderDirectX::GamepadProviderDirectX ()
Definition at line 23 of file GamepadProviderDirectX.cpp.
GamepadProviderDirectX::~GamepadProviderDirectX () [virtual]
Definition at line 28 of file GamepadProviderDirectX.cpp.
Member Function Documentation
LPDIRECTINPUT8 GamepadProviderDirectX::GetDInput () [inline]
Definition at line 60 of file GamepadProviderDirectX.h.
HWND GamepadProviderDirectX::GetHWND ()
Definition at line 89 of file GamepadProviderDirectX.cpp.
References hwndMain.
virtual string GamepadProviderDirectX::GetName () [inline, virtual]
Implements GamepadProvider.
Definition at line 53 of file GamepadProviderDirectX.h.
bool GamepadProviderDirectX::Init () [virtual]
Implements GamepadProvider.
Definition at line 32 of file GamepadProviderDirectX.cpp.
References EnumWindowProc(), hwndMain, LogError(), and LogMsg().
void GamepadProviderDirectX::Kill () [virtual]
Implements GamepadProvider.
Definition at line 61 of file GamepadProviderDirectX.cpp.
void GamepadProviderDirectX::Update () [virtual]
Implements GamepadProvider.
Definition at line 84 of file GamepadProviderDirectX.cpp.
The documentation for this class was generated from the following files:
GamepadProviderDirectX.h
GamepadProviderDirectX.cpp