Proton: RenderBatcher Class Reference
RenderBatcher Class Reference
#include <RenderBatcher.h>
Public Types
enum eFlushMode { FLUSH_SETUP_RENDER_UNSETUP, FLUSH_SETUP, FLUSH_RENDER, FLUSH_UNSETUP }
Public Member Functions
RenderBatcher ()
virtual ~RenderBatcher ()
void BlitEx (Surface *pSurf, rtRectf dst, rtRectf src, unsigned int rgba=MAKE_RGBA(255, 255, 255, 255))
void Flush (eFlushMode mode=FLUSH_SETUP_RENDER_UNSETUP)
void BlitRawImage (int dstX, int dstY, byte *pRaw, int width, int height, bool bNeedsAlpha)
void BlitRawImage (int x, int y, SoftSurface &soft)
void glDrawArrays (const CL_Vec3f *pVerts, const CL_Vec3f *vNormals, const CL_Vec2f *TexCords, glColorBytes glColorByte, CL_Mat4f *pMatrix, int glDrawMode, int primCount)
void Flush3D (bool bUseNormals, bool bUseTextures, bool bUseColorByte)
void BuildVert (BatchVert *pVert, const CL_Vec3f *pVerts, const CL_Vec3f *vNormals, const CL_Vec2f *TexCords, glColorBytes glColorByte, CL_Mat4f *pMatrix, int srcVertIndex)
Protected Attributes
Surface * m_pSurf
vector< BatchVert > m_verts
deque< RenderBatchEvent > m_batchEvents
Detailed Description
Definition at line 39 of file RenderBatcher.h.
Member Enumeration Documentation
enum RenderBatcher::eFlushMode
Enumerator:
FLUSH_SETUP_RENDER_UNSETUP
FLUSH_SETUP
FLUSH_RENDER
FLUSH_UNSETUP
Definition at line 43 of file RenderBatcher.h.
Constructor & Destructor Documentation
RenderBatcher::RenderBatcher ()
Definition at line 13 of file RenderBatcher.cpp.
RenderBatcher::~RenderBatcher () [virtual]
Definition at line 17 of file RenderBatcher.cpp.
Member Function Documentation
void RenderBatcher::BlitEx (Surface * pSurf, rtRectf dst, rtRectf src, unsigned int rgba = MAKE_RGBA(255,255,255,255))
Definition at line 21 of file RenderBatcher.cpp.
References glColorBytes::a, glColorBytes::b, Surface::BLENDING_PREMULTIPLIED_ALPHA, rtRectf::bottom, BatchVert::color, glColorBytes::g, GetBaseApp(), Surface::GetBlendingMode(), Surface::GetHeight(), GetOrthoRenderSizeYf(), Surface::GetRawTextureHeight(), Surface::GetRawTextureWidth(), Surface::GetWidth(), Surface::IsLoaded(), rtRectf::left, m_batchEvents, m_pSurf, m_verts, glColorBytes::r, rtRectf::right, rtRectf::top, RenderBatchEvent::TYPE_2D_BLIT, BatchVert::vPos, and BatchVert::vUv.
Referenced by SurfaceAnim::BlitScaledAnim(), Surface::BlitScaledWithRotatePoint(), RTFont::DrawScaled(), and RTFont::DrawScaledSolidColor().
void RenderBatcher::BlitRawImage (int dstX, int dstY, byte * pRaw, int width, int height, bool bNeedsAlpha)
Definition at line 215 of file RenderBatcher.cpp.
References glColorPointer(), glDisable(), glDisableClientState(), glDrawArrays(), glEnable(), glEnableClientState(), glPopMatrix(), glPushMatrix(), glVertexPointer(), and SetupOrtho().
Referenced by BlitRawImage().
void RenderBatcher::BlitRawImage (int x, int y, SoftSurface & soft)
Definition at line 199 of file RenderBatcher.cpp.
References SoftSurface::Blit(), BlitRawImage(), SoftSurface::GetHeight(), SoftSurface::GetPixelData(), SoftSurface::GetSurfaceType(), SoftSurface::GetUsesAlpha(), SoftSurface::GetWidth(), SoftSurface::Init(), and SoftSurface::SURFACE_RGBA.
void RenderBatcher::BuildVert (BatchVert * pVert, const CL_Vec3f * pVerts, const CL_Vec3f * vNormals, const CL_Vec2f * TexCords, glColorBytes glColorByte, CL_Mat4f * pMatrix, int srcVertIndex)
Definition at line 267 of file RenderBatcher.cpp.
References BatchVert::color, BatchVert::vNormal, and BatchVert::vPos.
Referenced by glDrawArrays().
void RenderBatcher::Flush (eFlushMode mode = FLUSH_SETUP_RENDER_UNSETUP)
Definition at line 126 of file RenderBatcher.cpp.
References FLUSH_RENDER, FLUSH_SETUP, FLUSH_SETUP_RENDER_UNSETUP, FLUSH_UNSETUP, glColor4x(), glColorPointer(), glDisable(), glDisableClientState(), glDrawArrays(), glEnable(), glEnableClientState(), glTexCoordPointer(), glVertexPointer(), LogMsg(), m_batchEvents, RenderBatchEvent::m_pSurf, RenderBatchEvent::m_vertCount, and m_verts.
Referenced by L_ParticleEffect::draw(), BaseApp::Draw(), RTFont::DrawScaled(), RTFont::DrawScaledSolidColor(), RenderScissorComponent::FilterOnRender(), ForceVideoUpdate(), RenderScissorComponent::PostOnRender(), RenderClipComponent::PostOnRender(), PrepareForGL(), RemoveOrthoRenderSize(), Surface::SetupForRender(), and SetupOrtho().
void RenderBatcher::Flush3D (bool bUseNormals, bool bUseTextures, bool bUseColorByte)
Definition at line 322 of file RenderBatcher.cpp.
References Surface::Bind(), glColor4x(), glColorPointer(), glDisable(), glDisableClientState(), glDrawArrays(), glEnableClientState(), glNormalPointer(), glTexCoordPointer(), glVertexPointer(), m_pSurf, and m_verts.
void RenderBatcher::glDrawArrays (const CL_Vec3f * pVerts, const CL_Vec3f * vNormals, const CL_Vec2f * TexCords, glColorBytes glColorByte, CL_Mat4f * pMatrix, int glDrawMode, int primCount)
Definition at line 276 of file RenderBatcher.cpp.
References BuildVert(), and m_verts.
Referenced by BlitRawImage(), Flush(), and Flush3D().
Member Data Documentation
deque<RenderBatchEvent> RenderBatcher::m_batchEvents [protected]
Definition at line 69 of file RenderBatcher.h.
Referenced by BlitEx(), and Flush().
Surface* RenderBatcher::m_pSurf [protected]
Definition at line 66 of file RenderBatcher.h.
Referenced by BlitEx(), and Flush3D().
vector<BatchVert> RenderBatcher::m_verts [protected]
Definition at line 67 of file RenderBatcher.h.
Referenced by BlitEx(), Flush(), Flush3D(), and glDrawArrays().
The documentation for this class was generated from the following files:
RenderBatcher.h
RenderBatcher.cpp