Proton: SoftSurface Class Reference
SoftSurface Class Reference
#include <SoftSurface.h>
Public Types
enum eSurfaceType { SURFACE_NONE, SURFACE_PALETTE_8BIT, SURFACE_RGBA, SURFACE_RGB }
enum eColorKeyType { COLOR_KEY_NONE, COLOR_KEY_BLACK, COLOR_KEY_WHITE, COLOR_KEY_MAGENTA }
Public Member Functions
SoftSurface ()
virtual ~SoftSurface ()
eSurfaceType GetSurfaceType ()
int GetWidth ()
int GetHeight ()
int GetOriginalWidth ()
int GetOriginalHeight ()
int GetBytesPerPixel ()
bool IsActive ()
bool Init (int sizex, int sizey, eSurfaceType type)
void Kill ()
void FillColor (glColorBytes color)
byte * GetPixelData ()
bool LoadFile (string fName, eColorKeyType colorKey, bool addBasePath=true)
bool LoadFileFromMemory (byte *pMem, eColorKeyType colorKey, int inputSize=0, bool bAddAlphaChannelIfNotPowerOfTwo=false)
void Blit (int dstX, int dstY, SoftSurface *pSrc, int srcX=0, int srcY=0, int srcWidth=0, int srcHeight=0)
Surface * CreateGLTexture ()
unsigned int GetSizeInBytes ()
void SetAutoPremultiplyAlpha (bool bYes)
bool GetAutoPremultiplyAlpha ()
void SetHasPremultipliedAlpha (bool bYes)
bool GetHasPremultipliedAlpha ()
void SetPixel (int x, int y, glColorBytes color)
void SetPixel (int x, int y, byte color)
glColorBytes GetPixel (int x, int y)
bool GetUsesAlpha ()
void SetUsesAlpha (bool bNew)
int GetPitch ()
bool SetPaletteFromBMP (const string fName, eColorKeyType colorKey)
void SetColorKeyType (eColorKeyType colorKey)
eColorKeyType GetColorKeyType ()
glColorBytes GetColorKeyColor ()
int GetColorKeyPaletteIndex ()
glColorBytes * GetPalette ()
int GetPaletteColorCount ()
bool IsPaletteTheSame (glColorBytes *palette, int colorCount)
bool GetModified ()
void SetModified (bool bNew)
void FlipY ()
void Rotate90Degrees (bool bRotateLeft)
void BlitFromScreen (int dstX, int dstY, int srcX, int srcY, int srcWidth, int srcHeight)
void WriteRawDataOut (string fileName)
void WriteBMPOut (string fileName)
void FillAlphaBit (unsigned char alpha)
void Scale (int newX, int newY)
Detailed Description
Definition at line 20 of file SoftSurface.h.
Member Enumeration Documentation
enum SoftSurface::eColorKeyType
Enumerator:
COLOR_KEY_NONE
COLOR_KEY_BLACK
COLOR_KEY_WHITE
COLOR_KEY_MAGENTA
Definition at line 36 of file SoftSurface.h.
enum SoftSurface::eSurfaceType
Enumerator:
SURFACE_NONE
SURFACE_PALETTE_8BIT
SURFACE_RGBA
SURFACE_RGB
Definition at line 28 of file SoftSurface.h.
Constructor & Destructor Documentation
SoftSurface::SoftSurface ()
Definition at line 8 of file SoftSurface.cpp.
References SURFACE_NONE.
SoftSurface::~SoftSurface () [virtual]
Definition at line 20 of file SoftSurface.cpp.
References Kill().
Member Function Documentation
void SoftSurface::Blit (int dstX, int dstY, SoftSurface * pSrc, int srcX = 0, int srcY = 0, int srcWidth = 0, int srcHeight = 0)
Definition at line 1006 of file SoftSurface.cpp.
References GetHeight(), GetSurfaceType(), GetWidth(), SetModified(), SURFACE_PALETTE_8BIT, SURFACE_RGB, and SURFACE_RGBA.
Referenced by BlitFromScreen(), RenderBatcher::BlitRawImage(), CreateGLTexture(), and Surface::InitFromSoftSurface().
void SoftSurface::BlitFromScreen (int dstX, int dstY, int srcX, int srcY, int srcWidth, int srcHeight)
Definition at line 979 of file SoftSurface.cpp.
References Blit(), GetBaseApp(), GetHeight(), GetPixelData(), glReadPixels(), Init(), InLandscapeGUIMode(), SetUsesAlpha(), and SURFACE_RGBA.
Surface * SoftSurface::CreateGLTexture ()
Definition at line 1078 of file SoftSurface.cpp.
References Surface::BLENDING_PREMULTIPLIED_ALPHA, Blit(), FlipY(), GetHasPremultipliedAlpha(), GetHeight(), GetPixelData(), GetSurfaceType(), GetUsesAlpha(), GetWidth(), Init(), Surface::InitBlankSurface(), Surface::SetBlendingMode(), Surface::SetTextureType(), Surface::SetUsesAlpha(), SURFACE_PALETTE_8BIT, SURFACE_RGBA, Surface::TYPE_GUI, and Surface::UpdateSurfaceRect().
void SoftSurface::FillAlphaBit (unsigned char alpha)
Definition at line 1263 of file SoftSurface.cpp.
References GetHeight(), GetSurfaceType(), GetWidth(), and SURFACE_RGBA.
void SoftSurface::FillColor (glColorBytes color)
Definition at line 80 of file SoftSurface.cpp.
References GetHeight(), GetPitch(), glColorBytes::r, SURFACE_PALETTE_8BIT, SURFACE_RGB, and SURFACE_RGBA.
Referenced by JPGSurfaceLoader::LoadFromMem().
void SoftSurface::FlipY ()
Definition at line 960 of file SoftSurface.cpp.
References GetHeight(), GetPitch(), and GetPixelData().
Referenced by CreateGLTexture(), and JPGSurfaceLoader::LoadFromMem().
bool SoftSurface::GetAutoPremultiplyAlpha () [inline]
Definition at line 63 of file SoftSurface.h.
int SoftSurface::GetBytesPerPixel () [inline]
Definition at line 49 of file SoftSurface.h.
Referenced by JPGSurfaceLoader::LoadFromMem().
glColorBytes SoftSurface::GetColorKeyColor ()
Definition at line 158 of file SoftSurface.cpp.
References COLOR_KEY_BLACK, COLOR_KEY_MAGENTA, COLOR_KEY_WHITE, and GetColorKeyType().
int SoftSurface::GetColorKeyPaletteIndex () [inline]
Definition at line 113 of file SoftSurface.h.
eColorKeyType SoftSurface::GetColorKeyType () [inline]
Definition at line 111 of file SoftSurface.h.
Referenced by GetColorKeyColor().
bool SoftSurface::GetHasPremultipliedAlpha () [inline]
Definition at line 65 of file SoftSurface.h.
Referenced by CreateGLTexture().
int SoftSurface::GetHeight () [inline]
Definition at line 46 of file SoftSurface.h.
Referenced by Blit(), BlitFromScreen(), RenderBatcher::BlitRawImage(), CreateGLTexture(), FillAlphaBit(), FillColor(), FlipY(), and Surface::InitFromSoftSurface().
bool SoftSurface::GetModified () [inline]
Definition at line 117 of file SoftSurface.h.
int SoftSurface::GetOriginalHeight () [inline]
Definition at line 48 of file SoftSurface.h.
Referenced by Surface::InitFromSoftSurface().
int SoftSurface::GetOriginalWidth () [inline]
Definition at line 47 of file SoftSurface.h.
Referenced by Surface::InitFromSoftSurface().
glColorBytes* SoftSurface::GetPalette () [inline]
Definition at line 114 of file SoftSurface.h.
int SoftSurface::GetPaletteColorCount () [inline]
Definition at line 115 of file SoftSurface.h.
int SoftSurface::GetPitch () [inline]
Definition at line 108 of file SoftSurface.h.
Referenced by FillColor(), and FlipY().
glColorBytes SoftSurface::GetPixel (int x, int y) [inline]
Definition at line 82 of file SoftSurface.h.
References SURFACE_PALETTE_8BIT, SURFACE_RGB, and SURFACE_RGBA.
byte* SoftSurface::GetPixelData () [inline]
Definition at line 56 of file SoftSurface.h.
Referenced by BlitFromScreen(), RenderBatcher::BlitRawImage(), CreateGLTexture(), FlipY(), glTexImage2D(), Surface::InitFromSoftSurface(), JPGSurfaceLoader::LoadFromMem(), and WriteRawDataOut().
unsigned int SoftSurface::GetSizeInBytes () [inline]
Definition at line 61 of file SoftSurface.h.
eSurfaceType SoftSurface::GetSurfaceType () [inline]
Definition at line 44 of file SoftSurface.h.
Referenced by Blit(), RenderBatcher::BlitRawImage(), CreateGLTexture(), FillAlphaBit(), Surface::InitFromSoftSurface(), SetPaletteFromBMP(), and WriteBMPOut().
bool SoftSurface::GetUsesAlpha () [inline]
Definition at line 105 of file SoftSurface.h.
Referenced by RenderBatcher::BlitRawImage(), and CreateGLTexture().
int SoftSurface::GetWidth () [inline]
Definition at line 45 of file SoftSurface.h.
Referenced by Blit(), RenderBatcher::BlitRawImage(), CreateGLTexture(), FillAlphaBit(), and Surface::InitFromSoftSurface().
bool SoftSurface::Init (int sizex, int sizey, eSurfaceType type)
Definition at line 40 of file SoftSurface.cpp.
References Kill(), SURFACE_PALETTE_8BIT, SURFACE_RGB, and SURFACE_RGBA.
Referenced by BlitFromScreen(), RenderBatcher::BlitRawImage(), CreateGLTexture(), glTexImage2D(), Surface::InitFromSoftSurface(), and JPGSurfaceLoader::LoadFromMem().
bool SoftSurface::IsActive () [inline]
Definition at line 51 of file SoftSurface.h.
References SURFACE_NONE.
bool SoftSurface::IsPaletteTheSame (glColorBytes * palette, int colorCount)
Definition at line 1117 of file SoftSurface.cpp.
void SoftSurface::Kill ()
Definition at line 25 of file SoftSurface.cpp.
References COLOR_KEY_NONE, GetBaseApp(), IsBaseAppInitted(), BaseApp::ModMemUsed(), SetColorKeyType(), SetUsesAlpha(), and SURFACE_NONE.
Referenced by Init(), LoadFileFromMemory(), and ~SoftSurface().
bool SoftSurface::LoadFile (string fName, eColorKeyType colorKey, bool addBasePath = true)
Definition at line 116 of file SoftSurface.cpp.
References FileInstance::GetAsBytes(), FileInstance::IsLoaded(), and LoadFileFromMemory().
bool SoftSurface::LoadFileFromMemory (byte * pMem, eColorKeyType colorKey, int inputSize = 0, bool bAddAlphaChannelIfNotPowerOfTwo = false)
Definition at line 536 of file SoftSurface.cpp.
References C_JPG_HEADER_MARKER, Kill(), JPGSurfaceLoader::LoadFromMem(), LogError(), and SetColorKeyType().
Referenced by LoadFile(), and Surface::LoadFileFromMemory().
void SoftSurface::Rotate90Degrees (bool bRotateLeft)
Definition at line 1141 of file SoftSurface.cpp.
void SoftSurface::Scale (int newX, int newY)
Definition at line 1284 of file SoftSurface.cpp.
References GetBaseApp(), and BaseApp::ModMemUsed().
void SoftSurface::SetAutoPremultiplyAlpha (bool bYes) [inline]
Definition at line 62 of file SoftSurface.h.
void SoftSurface::SetColorKeyType (eColorKeyType colorKey) [inline]
Definition at line 110 of file SoftSurface.h.
Referenced by Kill(), and LoadFileFromMemory().
void SoftSurface::SetHasPremultipliedAlpha (bool bYes) [inline]
Definition at line 64 of file SoftSurface.h.
void SoftSurface::SetModified (bool bNew) [inline]
Definition at line 118 of file SoftSurface.h.
Referenced by Blit().
bool SoftSurface::SetPaletteFromBMP (const string fName, eColorKeyType colorKey)
Definition at line 125 of file SoftSurface.cpp.
References BMPImageHeader::ColorsUsed, FileInstance::GetAsBytes(), GetSurfaceType(), FileInstance::IsLoaded(), FileInstance::Load(), and SURFACE_PALETTE_8BIT.
void SoftSurface::SetPixel (int x, int y, glColorBytes color) [inline]
Definition at line 67 of file SoftSurface.h.
References glColorBytes::r, and SURFACE_RGBA.
void SoftSurface::SetPixel (int x, int y, byte color) [inline]
Definition at line 75 of file SoftSurface.h.
References SURFACE_PALETTE_8BIT.
void SoftSurface::SetUsesAlpha (bool bNew) [inline]
Definition at line 106 of file SoftSurface.h.
Referenced by BlitFromScreen(), and Kill().
void SoftSurface::WriteBMPOut (string fileName)
Definition at line 1183 of file SoftSurface.cpp.
References BMPImageHeader::BitCount, BMP_COMPRESSION_NONE, BMPImageHeader::Compression, GetSurfaceType(), BMPImageHeader::Height, LogError(), BMPImageHeader::Size, SURFACE_RGB, SURFACE_RGBA, and BMPImageHeader::Width.
void SoftSurface::WriteRawDataOut (string fileName)
Definition at line 1128 of file SoftSurface.cpp.
References GetPixelData(), and LogError().
The documentation for this class was generated from the following files:
SoftSurface.h
SoftSurface.cpp