Proton: NamedTickIterator Class Reference
NamedTickIterator Class Reference
#include <pplot.h>
Public Member Functions
NamedTickIterator ()
void SetStringList (const vector< string > &inStringList)
virtual bool GetNextTick (float &outTick, bool &outIsMajorTick, string &outFormatString)
bool InitFromRanges (float inParRange, float inOrthoScreenRange, float inDivGuess, TickInfo &outTickInfo) const
Protected Attributes
vector< string > mStringList
Detailed Description
Definition at line 439 of file pplot.h.
Constructor & Destructor Documentation
NamedTickIterator::NamedTickIterator () [inline]
Definition at line 441 of file pplot.h.
Member Function Documentation
bool NamedTickIterator::GetNextTick (float & outTick, bool & outIsMajorTick, string & outFormatString) [virtual]
Reimplemented from LinTickIterator.
Definition at line 864 of file PPlot.cpp.
References LinTickIterator::GetNextTick(), and PPlot::Round().
bool NamedTickIterator::InitFromRanges (float inParRange, float inOrthoScreenRange, float inDivGuess, TickInfo & outTickInfo) const [virtual]
Reimplemented from LinTickIterator.
Definition at line 875 of file PPlot.cpp.
References LinTickIterator::InitFromRanges(), and TickInfo::mTickDivision.
void NamedTickIterator::SetStringList (const vector< string > & inStringList) [inline]
Definition at line 443 of file pplot.h.
References mStringList.
Referenced by PPlot::ConfigureSelf().
Member Data Documentation
vector<string> NamedTickIterator::mStringList [protected]
Definition at line 450 of file pplot.h.
Referenced by SetStringList().
The documentation for this class was generated from the following files:
pplot.h
PPlot.cpp