Proton: Button2DComponent Class Reference
Button2DComponent Class Reference
A component that adds button behaviour to an Entity.
#include <Button2DComponent.h>
Public Types
enum eVisualStyle { STYLE_NONE, STYLE_FADE_ALPHA_ON_HOVER, STYLE_SCALE_DOWN_ON_HOVER, STYLE_INVISIBLE_UNTIL_CLICKED }
Visual behaviour styles.
enum eButtonStyle { BUTTON_STYLE_CLICK_ON_TOUCH_RELEASE, BUTTON_STYLE_CLICK_ON_TOUCH, BUTTON_STYLE_CLICK_ON_TOUCH_PRESS_RELEASE, BUTTON_STYLE_CLICK_ON_TOUCH_IGNORE_DRAGGING }
Button behaviour styles.
Public Member Functions
Button2DComponent ()
virtual ~Button2DComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
Detailed Description
A component that adds button behaviour to an Entity.
The name of the component is initially set to "Button2D".
This component works nicely together with TouchHandlerComponent which calls appropriate functions on the parent Entity. This component listens calls to those functions and behaves like a button.
The following named variants are used inside the component itself:
"onClickAudioFile" (string): the name of the audio file that is played when the button is clicked. By default is whatever is the current global default click sound. See SetDefaultAudioClickSound().
"disabled" (uint32): used to disable the button. 0 (the default) means the button is enabled, any other values disables it.
"visualStyle" (uint32): determines the button's visual style, i.e. what the button looks like when it's pressed. This needs to be one of the values of eVisualStyle. The default value is STYLE_FADE_ALPHA_ON_HOVER.
"buttonStyle" (uint32): determines the button's behaviour style. This needs to be one of the values of eButtonStyle. By default is whatever is the current global default button style. See SetDefaultButtonStyle().
"repeatDelayMS" (uint32): a delay in milliseconds during which a button is non-clickable after it has been clicked. Default is 250 milliseconds.
When the button is clicked the "OnButtonSelected" function of the parent Entity gets called. This function gets a VariantList that contains three members:
0: the touch point of type Vector2
1: a pointer to the Entity that was touched
2: the id of the finger, type is uint32
Definition at line 55 of file Button2DComponent.h.
Member Enumeration Documentation
enum Button2DComponent::eButtonStyle
Button behaviour styles.
Enumerator:
BUTTON_STYLE_CLICK_ON_TOUCH_RELEASE
The button is clicked when it's released.
BUTTON_STYLE_CLICK_ON_TOUCH
The button is clicked immeditely when it's pressed.
BUTTON_STYLE_CLICK_ON_TOUCH_PRESS_RELEASE
The button is clicked after it has been pressed and subsequently released.
BUTTON_STYLE_CLICK_ON_TOUCH_IGNORE_DRAGGING
No idea what this is.
Seems to be exactly what BUTTON_STYLE_CLICK_ON_TOUCH is too.
Deprecated:
This is badly named and almost the same as BUTTON_STYLE_CLICK_ON_TOUCH so use that instead.
Definition at line 86 of file Button2DComponent.h.
enum Button2DComponent::eVisualStyle
Visual behaviour styles.
Enumerator:
STYLE_NONE
No visual change.
STYLE_FADE_ALPHA_ON_HOVER
The alpha value of the visuals is set to half of the original value.
STYLE_SCALE_DOWN_ON_HOVER
The visuals is scaled down slightly.
STYLE_INVISIBLE_UNTIL_CLICKED
The button is invisible until it is clicked.
After a click it stays visible for a while and then disappears again. The duration of the visibility period is the value of the repeatDelayMS variant of the component.
Definition at line 67 of file Button2DComponent.h.
Constructor & Destructor Documentation
Button2DComponent::Button2DComponent ()
Definition at line 44 of file Button2DComponent.cpp.
References EntityComponent::SetName().
Button2DComponent::~Button2DComponent () [virtual]
Definition at line 50 of file Button2DComponent.cpp.
Member Function Documentation
void Button2DComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 54 of file Button2DComponent.cpp.
References g_defaultButtonClickSound, g_defaultButtonStyle, Variant::GetFloat(), Entity::GetFunction(), EntityComponent::GetParent(), Variant::GetRect(), Variant::GetSigOnChanged, Variant::GetString(), Variant::GetUINT32(), EntityComponent::GetVar(), Entity::GetVar(), EntityComponent::GetVarWithDefault(), Entity::GetVarWithDefault(), Variant::GetVector2(), FunctionObject::sig_function, and STYLE_FADE_ALPHA_ON_HOVER.
void Button2DComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 91 of file Button2DComponent.cpp.
The documentation for this class was generated from the following files:
Button2DComponent.h
Button2DComponent.cpp