Proton: PDeleteInteraction Class Reference
PDeleteInteraction Class Reference
#include <PPlotInteraction.h>
Public Member Functions
PDeleteInteraction (PPlot &inPPlot)
virtual bool Impl_HandleKeyEvent (const PKeyEvent &inEvent)
virtual bool Impl_Calculate (Painter &inPainter, PPlot &inPPlot)
Protected Member Functions
void HandleDeleteKey (PlotDataBase *inXData, PlotDataBase *inYData, PlotDataSelection *inPlotDataSelection)
Detailed Description
Definition at line 277 of file PPlotInteraction.h.
Constructor & Destructor Documentation
PDeleteInteraction::PDeleteInteraction (PPlot & inPPlot)
Definition at line 562 of file PPlotInteraction.cpp.
Member Function Documentation
void PDeleteInteraction::HandleDeleteKey (PlotDataBase * inXData, PlotDataBase * inYData, PlotDataSelection * inPlotDataSelection) [protected]
Definition at line 612 of file PPlotInteraction.cpp.
References Erase(), PlotDataSelection::GetSelectedCount(), PlotDataBase::GetSize(), and PlotDataSelection::IsSelected().
Referenced by Impl_Calculate().
bool PDeleteInteraction::Impl_Calculate (Painter & inPainter, PPlot & inPPlot) [virtual]
Implements PEditInteraction.
Definition at line 575 of file PPlotInteraction.cpp.
References PlotDataContainer::GetDataDrawer(), PlotDataContainer::GetPlotCount(), PlotDataContainer::GetPlotDataSelection(), PlotDataContainer::GetXData(), PlotDataContainer::GetYData(), HandleDeleteKey(), PKeyEvent::IsDelete(), PEditInteraction::mKeyEvent, and PPlot::mPlotDataContainer.
bool PDeleteInteraction::Impl_HandleKeyEvent (const PKeyEvent & inEvent) [virtual]
Implements PEditInteraction.
Definition at line 567 of file PPlotInteraction.cpp.
References PKeyEvent::IsDelete().
The documentation for this class was generated from the following files:
PPlotInteraction.h
PPlotInteraction.cpp