Proton: AudioManagerAudiere Class Reference
AudioManagerAudiere Class Reference
#include <AudioManagerAudiere.h>
Public Member Functions
AudioManagerAudiere ()
virtual ~AudioManagerAudiere ()
virtual bool Init ()
virtual void Kill ()
virtual AudioHandle Play (std::string fName, bool bLooping=false, bool bIsMusic=false, bool bAddBasePath=true, bool bForceStreaming=false)
virtual void Preload (std::string fName, bool bLooping=false, bool bIsMusic=false, bool bAddBasePath=true, bool bForceStreaming=false)
SoundObject * GetSoundObjectByFileName (std::string fName)
virtual void KillCachedSounds (bool bKillMusic, bool bKillLooping, int ignoreSoundsUsedInLastMS, int killSoundsLowerPriorityThanThis, bool bKillSoundsPlaying)
virtual void Update ()
This method must be called periodically, e.g once every frame.
virtual void Stop (AudioHandle soundID)
virtual AudioHandle GetMusicChannel ()
virtual bool IsPlaying (AudioHandle soundID)
virtual void SetMusicEnabled (bool bNew)
Enables or disables the playing of music.
virtual void StopMusic ()
Stops the currently playing music immediately.
virtual int GetMemoryUsed ()
bool DeleteSoundObjectByFileName (std::string fName)
virtual void SetFrequency (AudioHandle soundID, int freq)
virtual void SetPan (AudioHandle soundID, float pan)
virtual void SetVol (AudioHandle soundID, float vol)
virtual void SetPriority (AudioHandle soundID, int priority)
virtual uint32 GetPos (AudioHandle soundID)
virtual void SetPos (AudioHandle soundID, uint32 posMS)
virtual void SetMusicVol (float vol)
SoundObject * GetSoundObjectByPointer (void *p)
Detailed Description
Definition at line 60 of file AudioManagerAudiere.h.
Constructor & Destructor Documentation
AudioManagerAudiere::AudioManagerAudiere ()
Definition at line 8 of file AudioManagerAudiere.cpp.
AudioManagerAudiere::~AudioManagerAudiere () [virtual]
Definition at line 14 of file AudioManagerAudiere.cpp.
References Kill().
Member Function Documentation
bool AudioManagerAudiere::DeleteSoundObjectByFileName (std::string fName)
Definition at line 75 of file AudioManagerAudiere.cpp.
int AudioManagerAudiere::GetMemoryUsed () [virtual]
Reimplemented from AudioManager.
Definition at line 320 of file AudioManagerAudiere.cpp.
AudioHandle AudioManagerAudiere::GetMusicChannel () [virtual]
Definition at line 274 of file AudioManagerAudiere.cpp.
uint32 AudioManagerAudiere::GetPos (AudioHandle soundID) [virtual]
Reimplemented from AudioManager.
Definition at line 336 of file AudioManagerAudiere.cpp.
SoundObject * AudioManagerAudiere::GetSoundObjectByFileName (std::string fName)
Definition at line 93 of file AudioManagerAudiere.cpp.
Referenced by Play(), and Preload().
SoundObject * AudioManagerAudiere::GetSoundObjectByPointer (void * p)
Definition at line 109 of file AudioManagerAudiere.cpp.
Referenced by SetVol(), and Stop().
bool AudioManagerAudiere::Init () [virtual]
Reimplemented from AudioManager.
Definition at line 19 of file AudioManagerAudiere.cpp.
bool AudioManagerAudiere::IsPlaying (AudioHandle soundID) [virtual]
Reimplemented from AudioManager.
Definition at line 281 of file AudioManagerAudiere.cpp.
void AudioManagerAudiere::Kill () [virtual]
Reimplemented from AudioManager.
Definition at line 65 of file AudioManagerAudiere.cpp.
References KillCachedSounds().
Referenced by ~AudioManagerAudiere().
void AudioManagerAudiere::KillCachedSounds (bool bKillMusic, bool bKillLooping, int ignoreSoundsUsedInLastMS, int killSoundsLowerPriorityThanThis, bool bKillSoundsPlaying) [virtual]
Reimplemented from AudioManager.
Definition at line 26 of file AudioManagerAudiere.cpp.
References LogMsg(), and AudioManager::m_lastMusicFileName.
Referenced by Kill().
AudioHandle AudioManagerAudiere::Play (std::string fName, bool bLooping = false, bool bIsMusic = false, bool bAddBasePath = true, bool bForceStreaming = false) [virtual]
Definition at line 177 of file AudioManagerAudiere.cpp.
References AudioManager::GetMusicEnabled(), AudioManager::GetSoundEnabled(), GetSoundObjectByFileName(), LogError(), AudioManager::m_bLastMusicLooping, AudioManager::m_lastMusicFileName, AudioManager::m_musicVol, SoundObject::m_pSound, Preload(), SetMusicVol(), SetVol(), and StopMusic().
Referenced by SetMusicEnabled().
void AudioManagerAudiere::Preload (std::string fName, bool bLooping = false, bool bIsMusic = false, bool bAddBasePath = true, bool bForceStreaming = false) [virtual]
Definition at line 125 of file AudioManagerAudiere.cpp.
References GetBaseAppPath(), AudioManager::GetMusicEnabled(), GetSoundObjectByFileName(), LogMsg(), SoundObject::m_bIsLooping, SoundObject::m_bIsMusic, SoundObject::m_fileName, AudioManager::m_lastMusicFileName, and SoundObject::m_pSound.
Referenced by Play().
void AudioManagerAudiere::SetFrequency (AudioHandle soundID, int freq) [virtual]
Reimplemented from AudioManager.
Definition at line 326 of file AudioManagerAudiere.cpp.
void AudioManagerAudiere::SetMusicEnabled (bool bNew) [virtual]
Enables or disables the playing of music.
When the music system is disabled any currently playing music is stopped. When the music system is later enabled again the music file that was left playing is resumed from the location where it stopped.
Reimplemented from AudioManager.
Definition at line 288 of file AudioManagerAudiere.cpp.
References AudioManager::m_bLastMusicLooping, AudioManager::m_bMusicEnabled, AudioManager::m_lastMusicFileName, Play(), and StopMusic().
void AudioManagerAudiere::SetMusicVol (float vol) [virtual]
Reimplemented from AudioManager.
Definition at line 365 of file AudioManagerAudiere.cpp.
References AudioManager::m_musicVol.
Referenced by Play().
void AudioManagerAudiere::SetPan (AudioHandle soundID, float pan) [virtual]
Reimplemented from AudioManager.
Definition at line 331 of file AudioManagerAudiere.cpp.
void AudioManagerAudiere::SetPos (AudioHandle soundID, uint32 posMS) [virtual]
Reimplemented from AudioManager.
Definition at line 342 of file AudioManagerAudiere.cpp.
void AudioManagerAudiere::SetPriority (AudioHandle soundID, int priority) [virtual]
Reimplemented from AudioManager.
Definition at line 385 of file AudioManagerAudiere.cpp.
void AudioManagerAudiere::SetVol (AudioHandle soundID, float vol) [virtual]
Reimplemented from AudioManager.
Definition at line 348 of file AudioManagerAudiere.cpp.
References GetSoundObjectByPointer(), and SoundObject::m_pSound.
Referenced by Play().
void AudioManagerAudiere::Stop (AudioHandle soundID) [virtual]
Reimplemented from AudioManager.
Definition at line 262 of file AudioManagerAudiere.cpp.
References GetSoundObjectByPointer(), and SoundObject::m_pSound.
void AudioManagerAudiere::StopMusic () [virtual]
Stops the currently playing music immediately.
Reimplemented from AudioManager.
Definition at line 302 of file AudioManagerAudiere.cpp.
References AudioManager::m_lastMusicFileName.
Referenced by Play(), and SetMusicEnabled().
void AudioManagerAudiere::Update () [virtual]
This method must be called periodically, e.g once every frame.
Reimplemented from AudioManager.
Definition at line 257 of file AudioManagerAudiere.cpp.
The documentation for this class was generated from the following files:
AudioManagerAudiere.h
AudioManagerAudiere.cpp