Proton: FilterInputComponent Class Reference
FilterInputComponent Class Reference
#include <FilterInputComponent.h>
Public Types
enum eMode {
MODE_CLIP_INPUT_TO_ABSOLUTE_CLIP_RECT, MODE_CLIP_INPUT_TO_SIZE, MODE_DISABLE_INPUT_ALL, MODE_DISABLE_INPUT_CHILDREN,
MODE_IDLE, MODE_CLIP_INPUT_TO_ABSOLUTE_CLIP_RECT_AND_DISABLE_INPUT_CHILDREN, MODE_IGNORE_ABSOLUTE_CLIP_RECT, MODE_CLIP_INPUT_TO_SIZE_STRICT,
MODE_CLIP_INPUT_TO_CLIP_RECT
}
Public Member Functions
FilterInputComponent ()
virtual ~FilterInputComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
void FilterOnInput (VariantList *pVList)
Detailed Description
Definition at line 17 of file FilterInputComponent.h.
Member Enumeration Documentation
enum FilterInputComponent::eMode
Enumerator:
MODE_CLIP_INPUT_TO_ABSOLUTE_CLIP_RECT
MODE_CLIP_INPUT_TO_SIZE
MODE_DISABLE_INPUT_ALL
MODE_DISABLE_INPUT_CHILDREN
MODE_IDLE
MODE_CLIP_INPUT_TO_ABSOLUTE_CLIP_RECT_AND_DISABLE_INPUT_CHILDREN
MODE_IGNORE_ABSOLUTE_CLIP_RECT
MODE_CLIP_INPUT_TO_SIZE_STRICT
MODE_CLIP_INPUT_TO_CLIP_RECT
Definition at line 26 of file FilterInputComponent.h.
Constructor & Destructor Documentation
FilterInputComponent::FilterInputComponent ()
Definition at line 6 of file FilterInputComponent.cpp.
References EntityComponent::SetName().
FilterInputComponent::~FilterInputComponent () [virtual]
Definition at line 11 of file FilterInputComponent.cpp.
Member Function Documentation
void FilterInputComponent::FilterOnInput (VariantList * pVList)
Definition at line 40 of file FilterInputComponent.cpp.
References Entity::FILTER_INDEX, Entity::FILTER_REFUSE_ALL, Entity::FILTER_REFUSE_CHILDREN, VariantList::Get(), GetAlignmentOffset(), Variant::GetFloat(), Variant::GetUINT32(), Variant::GetVector2(), LogError(), VariantList::m_variant, MESSAGE_TYPE_GUI_CLICK_END, MESSAGE_TYPE_GUI_CLICK_MOVE, MESSAGE_TYPE_GUI_CLICK_START, MODE_CLIP_INPUT_TO_ABSOLUTE_CLIP_RECT, MODE_CLIP_INPUT_TO_ABSOLUTE_CLIP_RECT_AND_DISABLE_INPUT_CHILDREN, MODE_CLIP_INPUT_TO_CLIP_RECT, MODE_CLIP_INPUT_TO_SIZE, MODE_CLIP_INPUT_TO_SIZE_STRICT, MODE_DISABLE_INPUT_ALL, MODE_DISABLE_INPUT_CHILDREN, MODE_IDLE, MODE_IGNORE_ABSOLUTE_CLIP_RECT, and Variant::Set().
Referenced by OnAdd().
void FilterInputComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 15 of file FilterInputComponent.cpp.
References FilterOnInput(), Entity::GetFunction(), EntityComponent::GetParent(), Variant::GetRect(), Variant::GetUINT32(), EntityComponent::GetVar(), Entity::GetVar(), EntityComponent::GetVarWithDefault(), Variant::GetVector2(), MODE_CLIP_INPUT_TO_SIZE, Entity::OnFilterAdd(), and FunctionObject::sig_function.
void FilterInputComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 34 of file FilterInputComponent.cpp.
References EntityComponent::GetParent(), and Entity::OnFilterRemove().
The documentation for this class was generated from the following files:
FilterInputComponent.h
FilterInputComponent.cpp