Proton: ArcadeInputComponent Class Reference
ArcadeInputComponent Class Reference
#include <ArcadeInputComponent.h>
Public Types
enum TrackballMode { TRACKBALL_MODE_WALKING, TRACKBALL_MODE_MENU_SELECTION }
Public Member Functions
ArcadeInputComponent ()
virtual ~ArcadeInputComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
bool GetDirectionKeysAsVector (CL_Vec2f *pVecOut)
bool GetDirectionKeys (bool &bLeftOut, bool &bRightOut, bool &bUpOut, bool &bDownOut)
void SetDirectionKey (eMoveButtonDir moveDir, bool bPressed, bool bBroadcastKeyIfChanged=true)
void ResetDirectionKeys (bool bBroadcastKeyIfChanged)
void OnRawKeyboard (VariantList *pVList)
Detailed Description
Definition at line 122 of file ArcadeInputComponent.h.
Member Enumeration Documentation
enum ArcadeInputComponent::TrackballMode
Enumerator:
TRACKBALL_MODE_WALKING
TRACKBALL_MODE_MENU_SELECTION
Definition at line 139 of file ArcadeInputComponent.h.
Constructor & Destructor Documentation
ArcadeInputComponent::ArcadeInputComponent ()
Definition at line 99 of file ArcadeInputComponent.cpp.
References MOVE_BUTTON_DIR_DOWN, MOVE_BUTTON_DIR_LEFT, MOVE_BUTTON_DIR_RIGHT, MOVE_BUTTON_DIR_UP, MoveButtonState::SetKeyType(), EntityComponent::SetName(), VIRTUAL_KEY_DIR_DOWN, VIRTUAL_KEY_DIR_LEFT, VIRTUAL_KEY_DIR_RIGHT, and VIRTUAL_KEY_DIR_UP.
ArcadeInputComponent::~ArcadeInputComponent () [virtual]
Definition at line 109 of file ArcadeInputComponent.cpp.
Member Function Documentation
bool ArcadeInputComponent::GetDirectionKeys (bool & bLeftOut, bool & bRightOut, bool & bUpOut, bool & bDownOut)
Definition at line 399 of file ArcadeInputComponent.cpp.
References MoveButtonState::m_bIsDown, MOVE_BUTTON_DIR_DOWN, MOVE_BUTTON_DIR_LEFT, MOVE_BUTTON_DIR_RIGHT, and MOVE_BUTTON_DIR_UP.
bool ArcadeInputComponent::GetDirectionKeysAsVector (CL_Vec2f * pVecOut)
Definition at line 392 of file ArcadeInputComponent.cpp.
References ConvertKeysToDirectionVector(), MOVE_BUTTON_DIR_DOWN, MOVE_BUTTON_DIR_LEFT, MOVE_BUTTON_DIR_RIGHT, and MOVE_BUTTON_DIR_UP.
void ArcadeInputComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 113 of file ArcadeInputComponent.cpp.
References GetBaseApp(), EntityComponent::GetFunction(), EntityComponent::GetParent(), Variant::GetSigOnChanged, Variant::GetUINT32(), EntityComponent::GetVar(), Entity::GetVar(), EntityComponent::GetVarWithDefault(), Variant::GetVector2(), BaseApp::m_sig_raw_keyboard, BaseApp::m_sig_trackball, BaseApp::m_sig_update, OnRawKeyboard(), FunctionObject::sig_function, and TRACKBALL_MODE_WALKING.
void ArcadeInputComponent::OnRawKeyboard (VariantList * pVList)
Definition at line 264 of file ArcadeInputComponent.cpp.
References VariantList::Get(), and Variant::GetUINT32().
Referenced by Gamepad::ConnectToArcadeComponent(), and OnAdd().
void ArcadeInputComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 137 of file ArcadeInputComponent.cpp.
void ArcadeInputComponent::ResetDirectionKeys (bool bBroadcastKeyIfChanged)
Definition at line 414 of file ArcadeInputComponent.cpp.
References MOVE_BUTTON_DIR_COUNT, and MoveButtonState::OnPressToggle().
void ArcadeInputComponent::SetDirectionKey (eMoveButtonDir moveDir, bool bPressed, bool bBroadcastKeyIfChanged = true)
Definition at line 409 of file ArcadeInputComponent.cpp.
References MoveButtonState::OnPressToggle().
Referenced by Gamepad::SendArcadeDirectionByDegrees(), Gamepad::SendArcadeDirectionByKey(), and Gamepad::SendArcadeDirectionRelease().
The documentation for this class was generated from the following files:
ArcadeInputComponent.h
ArcadeInputComponent.cpp