Proton: StreamingInstance Class Reference
StreamingInstance Class Reference
#include <StreamingInstance.h>
Public Member Functions
StreamingInstance ()
virtual ~StreamingInstance ()
virtual bool Open (string fName)=0
virtual bool ReadLineOfText (string &textOut)
virtual bool ReadLineOfText (char *pBuffer, int bufferSize)
virtual bool IsFinished ()=0
virtual int Read (byte *pBufferOut, int maxBytesToRead)=0
virtual void SeekFromStart (int byteCount)
int32 ReadInt32 ()
float ReadFloat32 ()
Detailed Description
Definition at line 13 of file StreamingInstance.h.
Constructor & Destructor Documentation
StreamingInstance::StreamingInstance ()
Definition at line 4 of file StreamingInstance.cpp.
StreamingInstance::~StreamingInstance () [virtual]
Definition at line 8 of file StreamingInstance.cpp.
Member Function Documentation
virtual bool StreamingInstance::IsFinished () [pure virtual]
Implemented in StreamingInstanceZip, and StreamingInstanceFile.
Referenced by FileManager::Copy(), and ReadLineOfText().
virtual bool StreamingInstance::Open (string fName) [pure virtual]
Implemented in StreamingInstanceZip, and StreamingInstanceFile.
virtual int StreamingInstance::Read (byte * pBufferOut, int maxBytesToRead) [pure virtual]
Implemented in StreamingInstanceZip, and StreamingInstanceFile.
Referenced by FileManager::Copy(), ReadFloat32(), ReadInt32(), ReadLineOfText(), and FileCopier::Update().
float StreamingInstance::ReadFloat32 ()
Definition at line 111 of file StreamingInstance.cpp.
References Read().
int32 StreamingInstance::ReadInt32 ()
Definition at line 104 of file StreamingInstance.cpp.
References Read().
bool StreamingInstance::ReadLineOfText (string & textOut) [virtual]
Definition at line 12 of file StreamingInstance.cpp.
References IsFinished(), and Read().
bool StreamingInstance::ReadLineOfText (char * pBuffer, int bufferSize) [virtual]
Definition at line 54 of file StreamingInstance.cpp.
References IsFinished(), LogMsg(), and Read().
void StreamingInstance::SeekFromStart (int byteCount) [virtual]
Reimplemented in StreamingInstanceZip, and StreamingInstanceFile.
Definition at line 98 of file StreamingInstance.cpp.
The documentation for this class was generated from the following files:
StreamingInstance.h
StreamingInstance.cpp