Proton: PrimeSearch Class Reference
PrimeSearch Class Reference
#include <PrimeSearch.h>
Public Member Functions
PrimeSearch (int elements)
PrimeSearch ()
int GetNext (bool restart=false)
bool Done ()
void Restart ()
void Init (int elements)
Public Attributes
int skip
int currentPosition
int maxElements
int * currentPrime
int searches
CRandom r
Static Public Attributes
static int prime_array []
Detailed Description
Definition at line 20 of file PrimeSearch.h.
Constructor & Destructor Documentation
PrimeSearch::PrimeSearch (int elements)
Definition at line 79 of file PrimeSearch.cpp.
References Init().
PrimeSearch::PrimeSearch ()
Definition at line 74 of file PrimeSearch.cpp.
References maxElements.
Member Function Documentation
bool PrimeSearch::Done () [inline]
Definition at line 28 of file PrimeSearch.h.
References currentPrime, and searches.
Referenced by GetNext().
int PrimeSearch::GetNext (bool restart = false)
Definition at line 84 of file PrimeSearch.cpp.
References currentPosition, currentPrime, Done(), maxElements, Restart(), searches, and skip.
void PrimeSearch::Init (int elements)
Definition at line 39 of file PrimeSearch.cpp.
References currentPrime, maxElements, prime_array, Restart(), and skip.
Referenced by PrimeSearch().
void PrimeSearch::Restart () [inline]
Definition at line 29 of file PrimeSearch.h.
References currentPosition, and searches.
Referenced by GetNext(), and Init().
Member Data Documentation
int PrimeSearch::currentPosition
Definition at line 35 of file PrimeSearch.h.
Referenced by GetNext(), and Restart().
int* PrimeSearch::currentPrime
Definition at line 37 of file PrimeSearch.h.
Referenced by Done(), GetNext(), and Init().
int PrimeSearch::maxElements
Definition at line 36 of file PrimeSearch.h.
Referenced by GetNext(), Init(), and PrimeSearch().
int PrimeSearch::prime_array [static]
Initial value:
{
        2, 3, 5, 7,
        11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47,
        53, 59, 61, 67, 71, 73, 79, 83, 89, 97,
        101, 103, 107, 109, 113, 127, 131, 137, 139, 149,
        151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199,
        211, 223, 227, 229, 233, 239, 241,
        5003, 5101, 5209, 5303, 5407, 5501, 5623, 5701, 5801, 5903,
        6007, 6101, 6211, 6301, 6421, 6521, 6607, 6701, 6803, 6907,
        7001, 7103, 7207, 7307, 7411, 7507, 7603, 7703, 7817, 7901,
        8009, 8101, 8209, 8311, 8419, 8501, 8609, 8707, 8803, 8923, 9001,
        9103, 9203, 9311, 9403, 9511, 9601, 9719, 9803, 9901,
        10007, 10501, 11003, 11503, 12007, 12503, 13001, 13513, 14009, 14503,
        15013, 15511, 16033, 16519, 17011, 17509, 18013, 18503, 19001, 19501,
        20011, 20507, 21001, 21503, 22003, 22501, 23003, 23509, 24001, 24509
}
Definition at line 32 of file PrimeSearch.h.
Referenced by Init().
CRandom PrimeSearch::r
Definition at line 40 of file PrimeSearch.h.
int PrimeSearch::searches
Definition at line 38 of file PrimeSearch.h.
Referenced by Done(), GetNext(), and Restart().
int PrimeSearch::skip
Definition at line 34 of file PrimeSearch.h.
Referenced by GetNext(), and Init().
The documentation for this class was generated from the following files:
PrimeSearch.h
PrimeSearch.cpp