Proton: PCrosshairInteraction Class Reference
PCrosshairInteraction Class Reference
#include <PPlotInteraction.h>
Public Member Functions
PCrosshairInteraction (PPlot &inPPlot)
void SetListener (PCrosshairInteractionListener *inListener)
Protected Member Functions
virtual bool HandleMouseEvent (const PMouseEvent &inEvent)
virtual bool Draw (Painter &inPainter)
bool GetCrossPoint (const PlotDataBase *inXData, const PlotDataBase *inYData, float &outY)
Protected Attributes
bool mActive
int mX
PCrosshairInteractionListener * mListener
Detailed Description
Definition at line 294 of file PPlotInteraction.h.
Constructor & Destructor Documentation
PCrosshairInteraction::PCrosshairInteraction (PPlot & inPPlot)
Definition at line 634 of file PPlotInteraction.cpp.
References PPlot::mPostDrawerList.
Member Function Documentation
bool PCrosshairInteraction::Draw (Painter & inPainter) [protected, virtual]
Implements PDrawer.
Definition at line 666 of file PPlotInteraction.cpp.
References Painter::DrawLine(), GetCrossPoint(), Painter::GetHeight(), PlotDataContainer::GetLegendData(), PlotDataContainer::GetPlotCount(), Painter::GetWidth(), PlotDataContainer::GetXData(), PlotDataContainer::GetYData(), PCrosshairInteractionListener::HandleCrosshair(), mActive, PColor::mB, PMargins::mBottom, LegendData::mColor, PColor::mG, PMargins::mLeft, mListener, PPlot::mMargins, PPlot::mPlotDataContainer, PPlotInteraction::mPPlot, PColor::mR, PMargins::mTop, mX, PPlot::mXTrafo, PPlot::mYTrafo, Painter::SetLineColor(), and Trafo::TransformBack().
bool PCrosshairInteraction::GetCrossPoint (const PlotDataBase * inXData, const PlotDataBase * inYData, float & outY) [protected]
Definition at line 703 of file PPlotInteraction.cpp.
References PlotDataBase::GetSize(), PlotDataBase::GetValue(), PPlotInteraction::mPPlot, mX, PPlot::mXTrafo, PPlot::mYTrafo, Trafo::Transform(), and Trafo::TransformBack().
Referenced by Draw().
bool PCrosshairInteraction::HandleMouseEvent (const PMouseEvent & inEvent) [protected, virtual]
Implements PPlotInteraction.
Definition at line 643 of file PPlotInteraction.cpp.
References PModifierKeys::IsControlKeyDown(), PMouseEvent::IsMouseDown(), PMouseEvent::IsMouseMove(), PMouseEvent::IsMouseUp(), PModifierKeys::IsShiftKeyDown(), mActive, PMouseEvent::mX, and mX.
void PCrosshairInteraction::SetListener (PCrosshairInteractionListener * inListener) [inline]
Definition at line 298 of file PPlotInteraction.h.
References mListener.
Member Data Documentation
bool PCrosshairInteraction::mActive [protected]
Definition at line 304 of file PPlotInteraction.h.
Referenced by Draw(), and HandleMouseEvent().
PCrosshairInteractionListener* PCrosshairInteraction::mListener [protected]
Definition at line 306 of file PPlotInteraction.h.
Referenced by Draw(), and SetListener().
int PCrosshairInteraction::mX [protected]
Definition at line 305 of file PPlotInteraction.h.
Referenced by Draw(), GetCrossPoint(), and HandleMouseEvent().
The documentation for this class was generated from the following files:
PPlotInteraction.h
PPlotInteraction.cpp