Proton: AudioManagerBBX Class Reference
AudioManagerBBX Class Reference
#include <AudioManagerBBX.h>
Public Member Functions
AudioManagerBBX ()
virtual ~AudioManagerBBX ()
virtual bool Init ()
virtual void Kill ()
virtual AudioHandle Play (string fName, bool bLooping=false, bool bIsMusic=false, bool bAddBasePath=true, bool bForceStreaming=false)
Plays an audio specified by a file name.
virtual void Preload (string fName, bool bLooping=false, bool bIsMusic=false, bool bAddBasePath=true, bool bForceStreaming=false)
SoundObject * GetSoundObjectByFileName (string fName)
virtual void KillCachedSounds (bool bKillMusic, bool bKillLooping, int ignoreSoundsUsedInLastMS, int killSoundsLowerPriorityThanThis, bool bKillSoundsPlaying)
virtual void Update ()
This method must be called periodically, e.g once every frame.
virtual void Stop (AudioHandle soundID)
virtual AudioHandle GetMusicChannel ()
virtual bool IsPlaying (AudioHandle soundID)
virtual void SetMusicEnabled (bool bNew)
Enables or disables the playing of music.
virtual void StopMusic ()
Stops the currently playing music immediately.
virtual int GetMemoryUsed ()
bool DeleteSoundObjectByFileName (string fName)
virtual void SetFrequency (AudioHandle soundID, int freq)
virtual void SetPan (AudioHandle soundID, float pan)
virtual void SetVol (AudioHandle soundID, float vol)
virtual void SetPriority (AudioHandle soundID, int priority)
virtual uint32 GetPos (AudioHandle soundID)
virtual void SetPos (AudioHandle soundID, uint32 posMS)
virtual void SetMusicVol (float vol)
virtual void Suspend ()
virtual void Resume ()
SoundObject * GetSoundObjectByPointer (void *p)
Detailed Description
Definition at line 59 of file AudioManagerBBX.h.
Constructor & Destructor Documentation
AudioManagerBBX::AudioManagerBBX ()
Definition at line 9 of file AudioManagerBBX.cpp.
AudioManagerBBX::~AudioManagerBBX () [virtual]
Definition at line 23 of file AudioManagerBBX.cpp.
References Kill().
Member Function Documentation
bool AudioManagerBBX::DeleteSoundObjectByFileName (string fName)
Definition at line 98 of file AudioManagerBBX.cpp.
int AudioManagerBBX::GetMemoryUsed () [virtual]
Reimplemented from AudioManager.
Definition at line 445 of file AudioManagerBBX.cpp.
AudioHandle AudioManagerBBX::GetMusicChannel () [virtual]
Definition at line 365 of file AudioManagerBBX.cpp.
uint32 AudioManagerBBX::GetPos (AudioHandle soundID) [virtual]
Reimplemented from AudioManager.
Definition at line 461 of file AudioManagerBBX.cpp.
SoundObject * AudioManagerBBX::GetSoundObjectByFileName (string fName)
Definition at line 116 of file AudioManagerBBX.cpp.
Referenced by Play(), and Preload().
SoundObject * AudioManagerBBX::GetSoundObjectByPointer (void * p)
Definition at line 132 of file AudioManagerBBX.cpp.
Referenced by IsPlaying(), SetVol(), and Stop().
bool AudioManagerBBX::Init () [virtual]
Reimplemented from AudioManager.
Definition at line 44 of file AudioManagerBBX.cpp.
References LogMsg().
bool AudioManagerBBX::IsPlaying (AudioHandle soundID) [virtual]
Reimplemented from AudioManager.
Definition at line 371 of file AudioManagerBBX.cpp.
References GetSoundObjectByPointer(), AudioManager::m_bLastMusicLooping, AudioManager::m_bMusicEnabled, AudioManager::m_lastMusicID, and SoundObject::source.
Referenced by KillCachedSounds().
void AudioManagerBBX::Kill () [virtual]
Reimplemented from AudioManager.
Definition at line 89 of file AudioManagerBBX.cpp.
References KillCachedSounds().
Referenced by ~AudioManagerBBX().
void AudioManagerBBX::KillCachedSounds (bool bKillMusic, bool bKillLooping, int ignoreSoundsUsedInLastMS, int killSoundsLowerPriorityThanThis, bool bKillSoundsPlaying) [virtual]
Reimplemented from AudioManager.
Definition at line 50 of file AudioManagerBBX.cpp.
References IsPlaying(), LogMsg(), and AudioManager::m_lastMusicFileName.
Referenced by Kill().
AudioHandle AudioManagerBBX::Play (string fName, bool bLooping = false, bool bIsMusic = false, bool bAddBasePath = true, bool bForceStreaming = false) [virtual]
Plays an audio specified by a file name.
Returns the audio handle for the playing sound if the playing started successfully. Returns AUDIO_HANDLE_BLANK if the playing of the audio didn't start successfully. Also returns AUDIO_HANDLE_BLANK if requesting to play a sound file and sound is currently disabled or requesting to play music and music is currently disabled.
Parameters:
fName the file name of the audio to play.
bLooping whether the sound should start again when it ends, i.e. loop.
bIsMusic specifies if this sound is the music track.
bAddBasePath adds the base path to the file name. See GetBaseAppPath().
bForceStreaming streams the audio directly from the file and doesn't load it into memory. This flag might not be supported by all audio backends.
Returns:
The audio handle for the playing sound if the playing started successfully. Returns AUDIO_HANDLE_BLANK if the playing of the audio didn't start.
Reimplemented from AudioManager.
Definition at line 206 of file AudioManagerBBX.cpp.
References GetBaseAppPath(), AudioManager::GetMusicEnabled(), AudioManager::GetSoundEnabled(), GetSoundObjectByFileName(), LogError(), LogMsg(), SoundObject::m_bIsLooping, AudioManager::m_bLastMusicLooping, AudioManager::m_lastMusicFileName, AudioManager::m_lastMusicID, AudioManager::m_musicVol, SoundObject::m_volume, Preload(), SetMusicVol(), SoundObject::source, and StopMusic().
Referenced by SetMusicEnabled().
void AudioManagerBBX::Preload (string fName, bool bLooping = false, bool bIsMusic = false, bool bAddBasePath = true, bool bForceStreaming = false) [virtual]
Reimplemented from AudioManager.
Definition at line 148 of file AudioManagerBBX.cpp.
References SoundObject::buffer, GetBaseAppPath(), AudioManager::GetMusicEnabled(), GetSoundObjectByFileName(), LogMsg(), SoundObject::m_bIsLooping, SoundObject::m_bIsMusic, SoundObject::m_fileName, AudioManager::m_lastMusicFileName, and SoundObject::source.
Referenced by Play().
void AudioManagerBBX::Resume () [virtual]
Reimplemented from AudioManager.
Definition at line 543 of file AudioManagerBBX.cpp.
void AudioManagerBBX::SetFrequency (AudioHandle soundID, int freq) [virtual]
Reimplemented from AudioManager.
Definition at line 451 of file AudioManagerBBX.cpp.
void AudioManagerBBX::SetMusicEnabled (bool bNew) [virtual]
Enables or disables the playing of music.
When the music system is disabled any currently playing music is stopped. When the music system is later enabled again the music file that was left playing is resumed from the location where it stopped.
Reimplemented from AudioManager.
Definition at line 396 of file AudioManagerBBX.cpp.
References AudioManager::m_bLastMusicLooping, AudioManager::m_bMusicEnabled, AudioManager::m_lastMusicFileName, Play(), and StopMusic().
void AudioManagerBBX::SetMusicVol (float vol) [virtual]
Reimplemented from AudioManager.
Definition at line 490 of file AudioManagerBBX.cpp.
References LogMsg(), and AudioManager::m_musicVol.
Referenced by Play(), and SetVol().
void AudioManagerBBX::SetPan (AudioHandle soundID, float pan) [virtual]
Reimplemented from AudioManager.
Definition at line 456 of file AudioManagerBBX.cpp.
void AudioManagerBBX::SetPos (AudioHandle soundID, uint32 posMS) [virtual]
Reimplemented from AudioManager.
Definition at line 466 of file AudioManagerBBX.cpp.
void AudioManagerBBX::SetPriority (AudioHandle soundID, int priority) [virtual]
Reimplemented from AudioManager.
Definition at line 517 of file AudioManagerBBX.cpp.
void AudioManagerBBX::SetVol (AudioHandle soundID, float vol) [virtual]
Reimplemented from AudioManager.
Definition at line 470 of file AudioManagerBBX.cpp.
References GetSoundObjectByPointer(), AudioManager::m_musicVol, SoundObject::m_volume, SetMusicVol(), and SoundObject::source.
void AudioManagerBBX::Stop (AudioHandle soundID) [virtual]
Reimplemented from AudioManager.
Definition at line 347 of file AudioManagerBBX.cpp.
References GetSoundObjectByPointer(), SoundObject::source, and StopMusic().
void AudioManagerBBX::StopMusic () [virtual]
Stops the currently playing music immediately.
Reimplemented from AudioManager.
Definition at line 415 of file AudioManagerBBX.cpp.
References LogMsg(), and AudioManager::m_lastMusicID.
Referenced by Play(), SetMusicEnabled(), and Stop().
void AudioManagerBBX::Suspend () [virtual]
Reimplemented from AudioManager.
Definition at line 522 of file AudioManagerBBX.cpp.
void AudioManagerBBX::Update () [virtual]
This method must be called periodically, e.g once every frame.
Reimplemented from AudioManager.
Definition at line 342 of file AudioManagerBBX.cpp.
The documentation for this class was generated from the following files:
AudioManagerBBX.h
AudioManagerBBX.cpp