Proton: SpriteFrame Class Reference
SpriteFrame Class Reference
A sprite presentation.
#include <SpriteAnimation.h>
Public Member Functions
SpriteFrame (unsigned int duration)
Constructs a new SpriteFrame.
unsigned int GetDuration () const
Returns the duration of this SpriteFrame.
void AddCell (const SpriteCell &spriteCell)
Adds a new cell to the end of the list of cells in this frame.
unsigned int GetCellCount () const
Gets the number of SpriteCells in this frame.
const SpriteCell * GetCell (unsigned int cellIndex) const
Gets the requested SpriteCell of this frame.
const CL_Rectf & GetBoundingBox () const
Gets the bounding box inside which this frame fits.
Detailed Description
A sprite presentation.
Consists of 0 or more SpriteCells that form the complete picture.
Definition at line 55 of file SpriteAnimation.h.
Constructor & Destructor Documentation
SpriteFrame::SpriteFrame (unsigned int duration)
Constructs a new SpriteFrame.
Parameters:
duration specifies the duration of this frame.
Definition at line 35 of file SpriteAnimation.cpp.
Member Function Documentation
void SpriteFrame::AddCell (const SpriteCell & spriteCell)
Adds a new cell to the end of the list of cells in this frame.
Definition at line 45 of file SpriteAnimation.cpp.
References SpriteCell::GetBoundingBox(), and SpriteCell::GetZLayer().
const CL_Rectf & SpriteFrame::GetBoundingBox () const
Gets the bounding box inside which this frame fits.
Definition at line 84 of file SpriteAnimation.cpp.
Referenced by SpriteAnimation::AddFrame().
const SpriteCell * SpriteFrame::GetCell (unsigned int cellIndex) const
Gets the requested SpriteCell of this frame.
If cellIndex is out of bounds then returns NULL.
The cells are ordered according to their z-layer values. All cells on layers <n have smaller indices than cells on layer n for any z-layer value n.
Definition at line 74 of file SpriteAnimation.cpp.
unsigned int SpriteFrame::GetCellCount () const
Gets the number of SpriteCells in this frame.
Definition at line 69 of file SpriteAnimation.cpp.
unsigned int SpriteFrame::GetDuration () const
Returns the duration of this SpriteFrame.
Definition at line 40 of file SpriteAnimation.cpp.
Referenced by SpriteAnimation::AddFrame().
The documentation for this class was generated from the following files:
SpriteAnimation.h
SpriteAnimation.cpp