Proton: RectRenderComponent Class Reference
RectRenderComponent Class Reference
#include <RectRenderComponent.h>
Public Types
enum eVisualStyle { STYLE_NORMAL, STYLE_3D, STYLE_BORDER_ONLY }
Public Member Functions
RectRenderComponent ()
virtual ~RectRenderComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
Detailed Description
Definition at line 19 of file RectRenderComponent.h.
Member Enumeration Documentation
enum RectRenderComponent::eVisualStyle
Enumerator:
STYLE_NORMAL
STYLE_3D
STYLE_BORDER_ONLY
Definition at line 28 of file RectRenderComponent.h.
Constructor & Destructor Documentation
RectRenderComponent::RectRenderComponent ()
Definition at line 7 of file RectRenderComponent.cpp.
References EntityComponent::SetName().
RectRenderComponent::~RectRenderComponent () [virtual]
Definition at line 13 of file RectRenderComponent.cpp.
Member Function Documentation
void RectRenderComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 18 of file RectRenderComponent.cpp.
References Variant::GetFloat(), Entity::GetFunction(), EntityComponent::GetParent(), Variant::GetSigOnChanged, Variant::GetString(), Variant::GetUINT32(), EntityComponent::GetVar(), Entity::GetVar(), EntityComponent::GetVarWithDefault(), Entity::GetVarWithDefault(), Variant::GetVector2(), FunctionObject::sig_function, and STYLE_NORMAL.
void RectRenderComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 63 of file RectRenderComponent.cpp.
The documentation for this class was generated from the following files:
RectRenderComponent.h
RectRenderComponent.cpp