Proton: VideoMode Class Reference
VideoMode Class Reference
Representation of a video mode.
#include <VideoModeSelector.h>
Public Member Functions
VideoMode ()
Initializes a video mode that doesn't represent a valid video mode.
VideoMode (std::string name, int x, int y, ePlatformID platformID, eOrientationMode orientationMode=ORIENTATION_DONT_CARE)
std::string getName () const
The human readable name of the mode.
int getX () const
The horizontal resolution.
int getY () const
The vertical resolution.
ePlatformID getPlatformID () const
The id of the platform.
eOrientationMode getOrientationMode () const
How to interpret this modes orientation.
Detailed Description
Representation of a video mode.
Definition at line 11 of file VideoModeSelector.h.
Constructor & Destructor Documentation
VideoMode::VideoMode ()
Initializes a video mode that doesn't represent a valid video mode.
The name will be empty, size will be zero and platform will be unknown.
Definition at line 7 of file VideoModeSelector.cpp.
VideoMode::VideoMode (std::string name, int x, int y, ePlatformID platformID, eOrientationMode orientationMode = ORIENTATION_DONT_CARE)
Member Function Documentation
string VideoMode::getName () const
The human readable name of the mode.
Definition at line 25 of file VideoModeSelector.cpp.
eOrientationMode VideoMode::getOrientationMode () const
How to interpret this modes orientation.
Definition at line 45 of file VideoModeSelector.cpp.
Referenced by main(), and VideoModeSelector::modesAsString().
ePlatformID VideoMode::getPlatformID () const
The id of the platform.
Definition at line 40 of file VideoModeSelector.cpp.
Referenced by main(), and VideoModeSelector::modesAsString().
int VideoMode::getX () const
The horizontal resolution.
Definition at line 30 of file VideoModeSelector.cpp.
Referenced by main(), and VideoModeSelector::modesAsString().
int VideoMode::getY () const
The vertical resolution.
Definition at line 35 of file VideoModeSelector.cpp.
Referenced by main(), and VideoModeSelector::modesAsString().
The documentation for this class was generated from the following files:
VideoModeSelector.h
VideoModeSelector.cpp