Proton: GameTimer Class Reference
GameTimer Class Reference
#include <GameTimer.h>
Public Member Functions
void Update ()
unsigned int GetTick ()
unsigned int GetGameTick ()
void SetGameTick (unsigned int tick)
int GetFPS ()
GameTimer ()
virtual ~GameTimer ()
float GetDelta ()
float GetGameDelta ()
int GetDeltaTick ()
int GetDeltaGameTick ()
void SetGameTickPause (bool bNew)
bool GetGameTickPause ()
void Reset ()
Detailed Description
Definition at line 13 of file GameTimer.h.
Constructor & Destructor Documentation
GameTimer::GameTimer ()
Definition at line 10 of file GameTimer.cpp.
GameTimer::~GameTimer () [virtual]
Definition at line 20 of file GameTimer.cpp.
Member Function Documentation
float GameTimer::GetDelta () [inline]
Definition at line 25 of file GameTimer.h.
int GameTimer::GetDeltaGameTick () [inline]
Definition at line 28 of file GameTimer.h.
int GameTimer::GetDeltaTick () [inline]
Definition at line 27 of file GameTimer.h.
int GameTimer::GetFPS () [inline]
Definition at line 22 of file GameTimer.h.
Referenced by BaseApp::Draw().
float GameTimer::GetGameDelta () [inline]
Definition at line 26 of file GameTimer.h.
unsigned int GameTimer::GetGameTick () [inline]
Definition at line 20 of file GameTimer.h.
Referenced by BaseApp::GetTickTimingSystem().
bool GameTimer::GetGameTickPause () [inline]
Definition at line 30 of file GameTimer.h.
unsigned int GameTimer::GetTick () [inline]
Definition at line 19 of file GameTimer.h.
Referenced by BaseApp::GetTickTimingSystem().
void GameTimer::Reset ()
Definition at line 80 of file GameTimer.cpp.
References GetSystemTimeAccurate().
Referenced by BaseApp::Init().
void GameTimer::SetGameTick (unsigned int tick) [inline]
Definition at line 21 of file GameTimer.h.
void GameTimer::SetGameTickPause (bool bNew)
Definition at line 89 of file GameTimer.cpp.
void GameTimer::Update ()
Definition at line 24 of file GameTimer.cpp.
References GetSystemTimeAccurate().
Referenced by BaseApp::Update().
The documentation for this class was generated from the following files:
GameTimer.h
GameTimer.cpp