Proton: TouchDeviceEmulatorPointerEventHandler Class Reference
TouchDeviceEmulatorPointerEventHandler Class Reference
Emulates a multitouch device with a single pointer device (such as a mouse on a desktop computer).
#include <TouchDeviceEmulatorPointerEventHandler.h>
Public Member Functions
TouchDeviceEmulatorPointerEventHandler (unsigned int primaryPointerId, unsigned int secondaryPointerId)
virtual ~TouchDeviceEmulatorPointerEventHandler ()
virtual void handlePointerDownEvent (float x, float y, unsigned int pointerId)
virtual void handlePointerMoveEvent (float x, float y, unsigned int pointerId)
virtual void handlePointerUpEvent (float x, float y, unsigned int pointerId)
Detailed Description
Emulates a multitouch device with a single pointer device (such as a mouse on a desktop computer).
Handles two pointer ids specially (set in the constructor). When the secondary pointer is pressed down the position of the pointer becomes a center position for a future multitouch gesture. Afterwards when the primary pointer is pressed down (and the secondary pointer is still down) a two-touchpoint gesture is started. The second touch point is on the opposite side of the gesture center point. Pinch-zoom and two-finger rotate gestures can be performed with this system.
This class also draws a small marker on the place of the emulated touch point.
Definition at line 20 of file TouchDeviceEmulatorPointerEventHandler.h.
Constructor & Destructor Documentation
TouchDeviceEmulatorPointerEventHandler::TouchDeviceEmulatorPointerEventHandler (unsigned int primaryPointerId, unsigned int secondaryPointerId)
Parameters:
primaryPointerId sets a value that is used for the primary pointer.
secondaryPointerId sets a value that is used for the secondary pointer.
Definition at line 7 of file TouchDeviceEmulatorPointerEventHandler.cpp.
TouchDeviceEmulatorPointerEventHandler::~TouchDeviceEmulatorPointerEventHandler () [virtual]
Definition at line 15 of file TouchDeviceEmulatorPointerEventHandler.cpp.
Member Function Documentation
void TouchDeviceEmulatorPointerEventHandler::handlePointerDownEvent (float x, float y, unsigned int pointerId) [virtual]
Implements PointerEventHandler.
Definition at line 19 of file TouchDeviceEmulatorPointerEventHandler.cpp.
References Entity::AddComponent(), Entity::AddEntity(), GetBaseApp(), BaseApp::GetEntityRoot(), GetMessageManager(), Entity::GetVar(), MESSAGE_TYPE_GUI_CLICK_START, MessageManager::SendGUIEx(), and Variant::Set().
void TouchDeviceEmulatorPointerEventHandler::handlePointerMoveEvent (float x, float y, unsigned int pointerId) [virtual]
Implements PointerEventHandler.
Definition at line 60 of file TouchDeviceEmulatorPointerEventHandler.cpp.
References GetBaseApp(), Entity::GetEntityByName(), BaseApp::GetEntityRoot(), GetMessageManager(), Entity::GetVar(), MESSAGE_TYPE_GUI_CLICK_MOVE, MessageManager::SendGUIEx(), and Variant::Set().
void TouchDeviceEmulatorPointerEventHandler::handlePointerUpEvent (float x, float y, unsigned int pointerId) [virtual]
Implements PointerEventHandler.
Definition at line 75 of file TouchDeviceEmulatorPointerEventHandler.cpp.
References GetBaseApp(), BaseApp::GetEntityRoot(), GetMessageManager(), MESSAGE_TYPE_GUI_CLICK_END, Entity::RemoveEntityByName(), and MessageManager::SendGUIEx().
The documentation for this class was generated from the following files:
TouchDeviceEmulatorPointerEventHandler.h
TouchDeviceEmulatorPointerEventHandler.cpp