Proton: Trafo Class Reference
Trafo Class Reference
#include <pplot.h>
Public Member Functions
virtual ~Trafo ()
virtual float Transform (float inValue) const =0
virtual float TransformBack (float inValue) const =0
Detailed Description
Definition at line 364 of file pplot.h.
Constructor & Destructor Documentation
virtual Trafo::~Trafo () [inline, virtual]
Definition at line 366 of file pplot.h.
Member Function Documentation
virtual float Trafo::Transform (float inValue) const [pure virtual]
Implemented in LogTrafo, and LinTrafo.
Referenced by PSelectionInteraction::CalculateDistanceToPlot(), LineDataDrawer::DrawData(), BarDataDrawer::DrawData(), PPlot::DrawGridXAxis(), PPlot::DrawGridYAxis(), BarDataDrawer::DrawOnlyLastPoint(), PPlot::DrawXAxis(), PPlot::DrawXTick(), PPlot::DrawYAxis(), PPlot::DrawYTick(), PCrosshairInteraction::GetCrossPoint(), and PVerticalCursorInteraction::HandleVerticalCursorKey().
virtual float Trafo::TransformBack (float inValue) const [pure virtual]
Implemented in LogTrafo, and LinTrafo.
Referenced by PZoomInteraction::DoZoomIn(), PCrosshairInteraction::Draw(), PCrosshairInteraction::GetCrossPoint(), and PVerticalCursorInteraction::HandleVerticalCursorKey().
The documentation for this class was generated from the following file:
pplot.h