Proton: ResourceManager Class Reference
ResourceManager Class Reference
A manager for resources.
#include <ResourceManager.h>
Classes
class Resource
Public Member Functions
ResourceManager ()
virtual ~ResourceManager ()
SurfaceAnim * GetSurfaceAnim (const string &fileName, bool bAddBasePath=true)
Gets a SurfaceAnim resource.
template<class T >
T * GetSurfaceResource (const string &fileName, Surface::eTextureType textureType=Surface::TYPE_DEFAULT, bool bAddBasePath=true)
Gets a resource of any class that is or is inherited from Surface.
bool IsResourceLoaded (string fName)
SpriteAnimationSet * GetSpriteAnimationSet (const string &fileName)
Gets a SpriteAnimationSet resource loaded from file fileName.
void KillAllResources ()
Removes and destroys all the resources currently in this resource manager.
void RemoveTexturesNotInExclusionList (const vector< string > &exclusionList)
Detailed Description
A manager for resources.
A resource is something that can be loaded from a file, such as an image.
The ResourceManager is useful in preventing the reading of the same file over and over again. The file reading only needs to happen once and thereafter the data is accessible through this class.
The resources are identified by their filenames from which they are loaded.
Definition at line 31 of file ResourceManager.h.
Constructor & Destructor Documentation
ResourceManager::ResourceManager ()
Definition at line 9 of file ResourceManager.cpp.
ResourceManager::~ResourceManager () [virtual]
Definition at line 13 of file ResourceManager.cpp.
References KillAllResources().
Member Function Documentation
SpriteAnimationSet * ResourceManager::GetSpriteAnimationSet (const string & fileName)
Gets a SpriteAnimationSet resource loaded from file fileName.
Returns NULL if the resource is not found or can't be loaded for any reason.
Definition at line 36 of file ResourceManager.cpp.
References SpriteAnimationSet::LoadFile(), and LogMsg().
SurfaceAnim * ResourceManager::GetSurfaceAnim (const string & fileName, bool bAddBasePath = true)
Gets a SurfaceAnim resource.
This is identical to calling:
 GetSurfaceResource<SurfaceAnim>(fileName, Surface::TYPE_GUI);
See also:
GetSurfaceResource()
Definition at line 30 of file ResourceManager.cpp.
References Surface::TYPE_GUI.
Referenced by CreateCheckbox().
template<class T > T* ResourceManager::GetSurfaceResource (const string & fileName, Surface::eTextureType textureType = Surface::TYPE_DEFAULT, bool bAddBasePath = true) [inline]
Gets a resource of any class that is or is inherited from Surface.
Returns NULL if the resource is not found or it has been previously loaded into a different type of Surface (that can't be dynamically cast to the requested type).
The textureType argument sets the texture type for the Surface. This argument however only has effect if the Surface has not been previously loaded.
Definition at line 60 of file ResourceManager.h.
References Surface::LoadFile(), LogMsg(), and Surface::SetTextureType().
bool ResourceManager::IsResourceLoaded (string fName)
Definition at line 123 of file ResourceManager.cpp.
void ResourceManager::KillAllResources ()
Removes and destroys all the resources currently in this resource manager.
Definition at line 76 of file ResourceManager.cpp.
Referenced by BaseApp::~BaseApp(), and ~ResourceManager().
void ResourceManager::RemoveTexturesNotInExclusionList (const vector< string > & exclusionList)
Definition at line 88 of file ResourceManager.cpp.
Referenced by DestroyUnusedTextures().
The documentation for this class was generated from the following files:
ResourceManager.h
ResourceManager.cpp