Proton: MySQLManager Class Reference
MySQLManager Class Reference
#include <MySQLManager.h>
Public Member Functions
MySQLManager ()
virtual ~MySQLManager ()
bool Init (string name, string password)
void Kill ()
int ShowError ()
bool Query (string query, bool bShowError=true)
bool DoesTableExist (string tableName, bool bShowErrors)
int GetLastAutoIncrementInsertID ()
int AddSelectResults (vector< VariantDB > &vdb)
void Update ()
bool DoResultsExist ()
bool LostServerConnection ()
string EscapeString (const string &input)
MYSQL * GetConnection ()
int GetTableRecordCount (string tableName)
unsigned int GetOpsDone ()
Detailed Description
Definition at line 22 of file MySQLManager.h.
Constructor & Destructor Documentation
MySQLManager::MySQLManager ()
Definition at line 18 of file MySQLManager.cpp.
MySQLManager::~MySQLManager () [virtual]
Definition at line 26 of file MySQLManager.cpp.
References Kill().
Member Function Documentation
int MySQLManager::AddSelectResults (vector< VariantDB > & vdb)
Definition at line 94 of file MySQLManager.cpp.
References Variant::GetString(), VariantDB::GetVar(), LogError(), LogMsg(), and Variant::Set().
Referenced by GetTableRecordCount().
bool MySQLManager::DoesTableExist (string tableName, bool bShowErrors)
Definition at line 50 of file MySQLManager.cpp.
References LogError(), and Query().
Referenced by Update().
bool MySQLManager::DoResultsExist ()
Definition at line 71 of file MySQLManager.cpp.
References LogError().
std::string MySQLManager::EscapeString (const string & input)
Definition at line 355 of file MySQLManager.cpp.
MYSQL* MySQLManager::GetConnection () [inline]
Definition at line 38 of file MySQLManager.h.
int MySQLManager::GetLastAutoIncrementInsertID ()
Definition at line 338 of file MySQLManager.cpp.
unsigned int MySQLManager::GetOpsDone () [inline]
Definition at line 40 of file MySQLManager.h.
int MySQLManager::GetTableRecordCount (string tableName)
Definition at line 367 of file MySQLManager.cpp.
References AddSelectResults(), LogError(), and Query().
bool MySQLManager::Init (string name, string password)
Definition at line 276 of file MySQLManager.cpp.
References Kill(), LogMsg(), and ShowError().
void MySQLManager::Kill ()
Definition at line 31 of file MySQLManager.cpp.
Referenced by Init(), and ~MySQLManager().
bool MySQLManager::LostServerConnection () [inline]
Definition at line 36 of file MySQLManager.h.
bool MySQLManager::Query (string query, bool bShowError = true)
Definition at line 305 of file MySQLManager.cpp.
References LogError(), and ShowError().
Referenced by DoesTableExist(), and GetTableRecordCount().
int MySQLManager::ShowError ()
Definition at line 40 of file MySQLManager.cpp.
References LogError().
Referenced by Init(), and Query().
void MySQLManager::Update ()
Definition at line 343 of file MySQLManager.cpp.
References DoesTableExist(), and GetTick().
The documentation for this class was generated from the following files:
MySQLManager.h
MySQLManager.cpp