Proton: FileManager Class Reference
FileManager Class Reference
#include <FileManager.h>
Public Member Functions
FileManager ()
virtual ~FileManager ()
byte * Get (std::string fileName, int *pSizeOut, bool bAddBasePath=true, bool bAutoDecompress=true)
Loads a file from the file system and returns the contents of it as an array of bytes.
StreamingInstance * GetStreaming (std::string fileName, int *pSizeOut, bool bAddBasePath=true)
void MountFileSystem (FileSystem *pFileSystem)
bool FileExists (std::string fileName, bool bAddBasePath=true)
int GetFileSize (std::string fileName, bool bAddBasePath=true)
FileSystem * GetFileSystem (int index)
bool Copy (std::string srcFile, std::string dstFile, bool bAddBasePath=true)
Detailed Description
Definition at line 48 of file FileManager.h.
Constructor & Destructor Documentation
FileManager::FileManager ()
Definition at line 45 of file FileManager.cpp.
FileManager::~FileManager () [virtual]
Definition at line 50 of file FileManager.cpp.
Member Function Documentation
bool FileManager::Copy (std::string srcFile, std::string dstFile, bool bAddBasePath = true)
Definition at line 237 of file FileManager.cpp.
References GetBaseAppPath(), GetFileManager(), GetStreaming(), StreamingInstance::IsFinished(), LogError(), LogMsg(), and StreamingInstance::Read().
bool FileManager::FileExists (std::string fileName, bool bAddBasePath = true)
Definition at line 165 of file FileManager.cpp.
References GetBaseAppPath().
Referenced by FileExists().
byte * FileManager::Get (std::string fileName, int * pSizeOut, bool bAddBasePath = true, bool bAutoDecompress = true)
Loads a file from the file system and returns the contents of it as an array of bytes.
If the file is compressed (an RTPack file), this also decompresses the file. The size of the (decompressed) data is written to pSizeOut.
Returns NULL if anything goes wrong in the reading.
A zero byte is added to the end of the file contents. This makes it easier to use the contents of the file as a string.
The caller is responsible for freeing the returned memory later.
Definition at line 94 of file FileManager.cpp.
References DecompressRTPackToMemory(), GetBaseAppPath(), IsAPackedFile(), and LogError().
Referenced by GetHashOfFile(), FileInstance::Load(), and AudioManagerFlash::Preload().
int FileManager::GetFileSize (std::string fileName, bool bAddBasePath = true)
Definition at line 195 of file FileManager.cpp.
References GetBaseAppPath().
FileSystem * FileManager::GetFileSystem (int index)
Definition at line 219 of file FileManager.cpp.
StreamingInstance * FileManager::GetStreaming (std::string fileName, int * pSizeOut, bool bAddBasePath = true)
Definition at line 63 of file FileManager.cpp.
References GetBaseAppPath(), and StreamingInstanceFile::Open().
Referenced by Copy(), and FileCopier::Init().
void FileManager::MountFileSystem (FileSystem * pFileSystem)
Definition at line 160 of file FileManager.cpp.
Referenced by AppResize().
The documentation for this class was generated from the following files:
FileManager.h
FileManager.cpp