Proton: PSelectionInteraction Class Reference
PSelectionInteraction Class Reference
#include <PPlotInteraction.h>
Public Types
enum ECommand { kNone, kPointwiseSelection, kGlobalSelection, kSelectAll }
Public Member Functions
PSelectionInteraction (PPlot &inPPlot)
virtual bool HandleKeyEvent (const PKeyEvent &inEvent)
virtual bool HandleMouseEvent (const PMouseEvent &inEvent)
virtual bool Calculate (Painter &inPainter, PPlot &inPPlot)
void SetCommand (ECommand inCommand, const PKeyEvent &inKeyEvent, const PMouseEvent &inMouseEvent)
void SetListener (PSelectionInteractionListener *inListener)
Protected Member Functions
void HandleGlobalInteraction (bool inHit, long inNearestPointIndex, DataDrawerBase *inDataDrawer, PlotDataSelection *inPlotDataSelection)
void HandlePointwiseInteraction (bool inHit, long inNearestPointIndex, DataDrawerBase *inDataDrawer, PlotDataSelection *inPlotDataSelection)
float CalculateDistanceToPlot (const PlotDataBase *inXData, const PlotDataBase *inYData, long &outNearestPointIndex)
void SelectAll (PlotDataBase *inYData, PlotDataSelection *inPlotDataSelection)
Protected Attributes
PSelectionInteractionListener * mListener
ECommand mCommand
PMouseEvent mMouseEvent
PKeyEvent mKeyEvent
Detailed Description
Definition at line 196 of file PPlotInteraction.h.
Member Enumeration Documentation
enum PSelectionInteraction::ECommand
Enumerator:
kNone
kPointwiseSelection
kGlobalSelection
kSelectAll
Definition at line 199 of file PPlotInteraction.h.
Constructor & Destructor Documentation
PSelectionInteraction::PSelectionInteraction (PPlot & inPPlot)
Definition at line 251 of file PPlotInteraction.cpp.
References PPlot::mPostCalculatorList.
Member Function Documentation
bool PSelectionInteraction::Calculate (Painter & inPainter, PPlot & inPPlot) [virtual]
Reimplemented from PCalculator.
Definition at line 299 of file PPlotInteraction.cpp.
References CalculateDistanceToPlot(), PlotDataContainer::GetDataDrawer(), PlotDataContainer::GetPlotCount(), PlotDataContainer::GetPlotDataSelection(), PlotDataContainer::GetXData(), PlotDataContainer::GetYData(), HandleGlobalInteraction(), HandlePointwiseInteraction(), PSelectionInteractionListener::HandlePSelectionInteraction(), kGlobalSelection, kHitDistance, kNone, kPointwiseSelection, kSelectAll, mCommand, mListener, PPlot::mPlotDataContainer, and SelectAll().
float PSelectionInteraction::CalculateDistanceToPlot (const PlotDataBase * inXData, const PlotDataBase * inYData, long & outNearestPointIndex) [protected]
Definition at line 378 of file PPlotInteraction.cpp.
References PlotDataBase::GetSize(), PlotDataBase::GetValue(), mMouseEvent, PPlotInteraction::mPPlot, PMouseEvent::mX, PPlot::mXTrafo, PMouseEvent::mY, PPlot::mYTrafo, and Trafo::Transform().
Referenced by Calculate().
void PSelectionInteraction::HandleGlobalInteraction (bool inHit, long inNearestPointIndex, DataDrawerBase * inDataDrawer, PlotDataSelection * inPlotDataSelection) [protected]
Definition at line 347 of file PPlotInteraction.cpp.
Referenced by Calculate().
bool PSelectionInteraction::HandleKeyEvent (const PKeyEvent & inEvent) [virtual]
Reimplemented from PPlotInteraction.
Definition at line 260 of file PPlotInteraction.cpp.
References PKeyEvent::GetChar(), PKeyEvent::IsChar(), PModifierKeys::IsOnlyControlKeyDown(), kNone, kSelectAll, mCommand, and mKeyEvent.
bool PSelectionInteraction::HandleMouseEvent (const PMouseEvent & inEvent) [virtual]
Implements PPlotInteraction.
Definition at line 278 of file PPlotInteraction.cpp.
References PMouseEvent::IsMouseDown(), PModifierKeys::IsOnlyControlKeyDown(), PModifierKeys::IsOnlyShiftKeyDown(), kGlobalSelection, kNone, kPointwiseSelection, mCommand, and mMouseEvent.
void PSelectionInteraction::HandlePointwiseInteraction (bool inHit, long inNearestPointIndex, DataDrawerBase * inDataDrawer, PlotDataSelection * inPlotDataSelection) [protected]
Definition at line 359 of file PPlotInteraction.cpp.
Referenced by Calculate().
void PSelectionInteraction::SelectAll (PlotDataBase * inYData, PlotDataSelection * inPlotDataSelection) [protected]
Definition at line 271 of file PPlotInteraction.cpp.
Referenced by Calculate().
void PSelectionInteraction::SetCommand (ECommand inCommand, const PKeyEvent & inKeyEvent, const PMouseEvent & inMouseEvent)
void PSelectionInteraction::SetListener (PSelectionInteractionListener * inListener) [inline]
Definition at line 213 of file PPlotInteraction.h.
References mListener.
Member Data Documentation
ECommand PSelectionInteraction::mCommand [protected]
Definition at line 223 of file PPlotInteraction.h.
Referenced by Calculate(), HandleKeyEvent(), and HandleMouseEvent().
PKeyEvent PSelectionInteraction::mKeyEvent [protected]
Definition at line 225 of file PPlotInteraction.h.
Referenced by HandleKeyEvent().
PSelectionInteractionListener* PSelectionInteraction::mListener [protected]
Definition at line 213 of file PPlotInteraction.h.
Referenced by Calculate(), and SetListener().
PMouseEvent PSelectionInteraction::mMouseEvent [protected]
Definition at line 224 of file PPlotInteraction.h.
Referenced by CalculateDistanceToPlot(), and HandleMouseEvent().
The documentation for this class was generated from the following files:
PPlotInteraction.h
PPlotInteraction.cpp