Proton: TemplateComponent Class Reference
TemplateComponent Class Reference
#include <TemplateComponent.h>
Public Member Functions
TemplateComponent ()
virtual ~TemplateComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
Detailed Description
Definition at line 17 of file TemplateComponent.h.
Constructor & Destructor Documentation
TemplateComponent::TemplateComponent ()
Definition at line 6 of file TemplateComponent.cpp.
References EntityComponent::SetName().
TemplateComponent::~TemplateComponent () [virtual]
Definition at line 11 of file TemplateComponent.cpp.
Member Function Documentation
void TemplateComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 17 of file TemplateComponent.cpp.
References Entity::GetFunction(), EntityComponent::GetParent(), Entity::GetVar(), Variant::GetVector2(), and FunctionObject::sig_function.
void TemplateComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 39 of file TemplateComponent.cpp.
The documentation for this class was generated from the following files:
TemplateComponent.h
TemplateComponent.cpp