Proton: ProtonPainter Class Reference
ProtonPainter Class Reference
#include <ProtonPainter.h>
Public Member Functions
ProtonPainter ()
virtual ~ProtonPainter ()
void SetSize (int x, int y)
void SetPos (int x, int y)
virtual void DrawLine (float inX1, float inY1, float inX2, float inY2)
virtual void FillRect (int inX, int inY, int inW, int inH)
virtual void InvertRect (int inX, int inY, int inW, int inH)
virtual void SetClipRect (int inX, int inY, int inW, int inH)
virtual long GetWidth () const
virtual long GetHeight () const
virtual void SetLineColor (int inR, int inG, int inB)
virtual void SetFillColor (int inR, int inG, int inB)
virtual long CalculateTextDrawSize (const char *inString)
virtual long GetFontHeight () const
virtual void DrawText (int inX, int inY, const char *inString)
virtual void DrawRotatedText (int inX, int inY, float inDegrees, const char *inString)
Detailed Description
Definition at line 17 of file ProtonPainter.h.
Constructor & Destructor Documentation
ProtonPainter::ProtonPainter ()
Definition at line 4 of file ProtonPainter.cpp.
References FONT_SMALL.
ProtonPainter::~ProtonPainter () [virtual]
Definition at line 18 of file ProtonPainter.cpp.
Member Function Documentation
long ProtonPainter::CalculateTextDrawSize (const char * inString) [virtual]
Implements Painter.
Definition at line 67 of file ProtonPainter.cpp.
References GetBaseApp(), BaseApp::GetFont(), and RTFont::MeasureText().
void ProtonPainter::DrawLine (float inX1, float inY1, float inX2, float inY2) [virtual]
Implements Painter.
Definition at line 28 of file ProtonPainter.cpp.
virtual void ProtonPainter::DrawRotatedText (int inX, int inY, float inDegrees, const char * inString) [inline, virtual]
Implements Painter.
Definition at line 37 of file ProtonPainter.h.
void ProtonPainter::DrawText (int inX, int inY, const char * inString) [virtual]
Implements Painter.
Definition at line 57 of file ProtonPainter.cpp.
References RTFont::DrawScaled(), GetBaseApp(), and BaseApp::GetFont().
void ProtonPainter::FillRect (int inX, int inY, int inW, int inH) [virtual]
Implements Painter.
Definition at line 23 of file ProtonPainter.cpp.
References DrawFilledRect().
long ProtonPainter::GetFontHeight () const [virtual]
Implements Painter.
Definition at line 62 of file ProtonPainter.cpp.
References GetBaseApp(), BaseApp::GetFont(), and RTFont::GetLineHeight().
virtual long ProtonPainter::GetHeight () const [inline, virtual]
Implements Painter.
Definition at line 31 of file ProtonPainter.h.
virtual long ProtonPainter::GetWidth () const [inline, virtual]
Implements Painter.
Definition at line 30 of file ProtonPainter.h.
void ProtonPainter::InvertRect (int inX, int inY, int inW, int inH) [virtual]
Implements Painter.
Definition at line 72 of file ProtonPainter.cpp.
References DrawFilledRect().
virtual void ProtonPainter::SetClipRect (int inX, int inY, int inW, int inH) [inline, virtual]
Implements Painter.
Definition at line 29 of file ProtonPainter.h.
void ProtonPainter::SetFillColor (int inR, int inG, int inB) [virtual]
Implements Painter.
Definition at line 52 of file ProtonPainter.cpp.
void ProtonPainter::SetLineColor (int inR, int inG, int inB) [virtual]
Implements Painter.
Definition at line 46 of file ProtonPainter.cpp.
void ProtonPainter::SetPos (int x, int y)
Definition at line 40 of file ProtonPainter.cpp.
void ProtonPainter::SetSize (int x, int y)
Definition at line 34 of file ProtonPainter.cpp.
The documentation for this class was generated from the following files:
ProtonPainter.h
ProtonPainter.cpp