Proton: P3DPlot Class Reference
P3DPlot Class Reference
#include <P3DPlot.h>
Public Member Functions
P3DPlot ()
virtual ~P3DPlot ()
virtual bool MakeModel (Carpenter &inCarpenter)
void SetData (PlotData *inData, long inXCount=0, long inYCount=0)
Protected Member Functions
void MakeBar (float inX, float inY, float inZ, float inSize)
void MakePolygonWithOffset (const vector< PVertex > &inVertices, const PVertex &inOffset)
Protected Attributes
Carpenter * mCarpenter
PlotData * mData
long mXCount
long mYCount
Detailed Description
Definition at line 39 of file P3DPlot.h.
Constructor & Destructor Documentation
P3DPlot::P3DPlot ()
Definition at line 14 of file P3DPlot.cpp.
P3DPlot::~P3DPlot () [virtual]
Definition at line 16 of file P3DPlot.cpp.
References mData.
Member Function Documentation
void P3DPlot::MakeBar (float inX, float inY, float inZ, float inSize) [protected]
Definition at line 85 of file P3DPlot.cpp.
References Carpenter::MakePolygon(), MakePolygonWithOffset(), mCarpenter, and Carpenter::SetSurfaceNormal().
Referenced by MakeModel().
bool P3DPlot::MakeModel (Carpenter & inCarpenter) [virtual]
Definition at line 36 of file P3DPlot.cpp.
References Carpenter::Finish(), MakeBar(), Carpenter::MakeLine(), mCarpenter, mData, mXCount, mYCount, Carpenter::SetColor(), and Carpenter::SetSurfaceNormal().
void P3DPlot::MakePolygonWithOffset (const vector< PVertex > & inVertices, const PVertex & inOffset) [protected]
Definition at line 123 of file P3DPlot.cpp.
References Carpenter::MakePolygon(), mCarpenter, PVertex::mX, PVertex::mY, and PVertex::mZ.
Referenced by MakeBar().
void P3DPlot::SetData (PlotData * inData, long inXCount = 0, long inYCount = 0)
Definition at line 20 of file P3DPlot.cpp.
References mData, mXCount, and mYCount.
Referenced by MakeExamplePlot1(), and MakeExamplePlot2().
Member Data Documentation
Carpenter* P3DPlot::mCarpenter [protected]
Definition at line 50 of file P3DPlot.h.
Referenced by MakeBar(), MakeModel(), and MakePolygonWithOffset().
PlotData* P3DPlot::mData [protected]
Definition at line 52 of file P3DPlot.h.
Referenced by MakeModel(), SetData(), and ~P3DPlot().
long P3DPlot::mXCount [protected]
Definition at line 53 of file P3DPlot.h.
Referenced by MakeModel(), and SetData().
long P3DPlot::mYCount [protected]
Definition at line 54 of file P3DPlot.h.
Referenced by MakeModel(), and SetData().
The documentation for this class was generated from the following files:
P3DPlot.h
P3DPlot.cpp