Proton: VariantDB Class Reference
VariantDB Class Reference
#include <VariantDB.h>
Public Member Functions
VariantDB ()
virtual ~VariantDB ()
FunctionObject * GetFunction (const string &keyName)
FunctionObject * GetFunctionIfExists (const string &keyName)
void CallFunctionIfExists (const string &keyName, VariantList *pVList)
Variant * GetVar (const string &keyName)
Variant * GetVarIfExists (const string &keyName)
Variant * GetVarWithDefault (const string &keyName, const Variant &vDefault)
int DeleteVarsStartingWith (string deleteStr)
int DeleteVar (string keyName)
bool Save (const string &fileName, bool bAddBasePath=true)
bool Load (const string &fileName, bool *pFileExistedOut=NULL, bool bAddBasePath=true)
string DumpAsString ()
void Print ()
void DeleteAll ()
void ResetNext ()
Variant * GetNext (string &keyOut)
int AddVarPointersToVector (vector< pair< const string *, Variant * > > *varListOut, const string keyMustStartWithThisText="")
VariantDB & operator= (const VariantDB &rhs)
VariantDB (const VariantDB &ref)
Detailed Description
Definition at line 94 of file VariantDB.h.
Constructor & Destructor Documentation
VariantDB::VariantDB ()
Definition at line 6 of file VariantDB.cpp.
References ResetNext().
VariantDB::~VariantDB () [virtual]
Definition at line 11 of file VariantDB.cpp.
References DeleteAll().
VariantDB::VariantDB (const VariantDB & ref) [inline]
Definition at line 137 of file VariantDB.h.
Member Function Documentation
int VariantDB::AddVarPointersToVector (vector< pair< const string *, Variant * > > * varListOut, const string keyMustStartWithThisText = "")
Definition at line 413 of file VariantDB.cpp.
References StringFromStartMatches().
void VariantDB::CallFunctionIfExists (const string & keyName, VariantList * pVList)
Definition at line 135 of file VariantDB.cpp.
References GetFunctionIfExists(), and FunctionObject::sig_function.
Referenced by Entity::CallFunctionRecursively(), Entity::CallFunctionRecursivelyWithUpdatedVar(), and SetEntityWithNativeUIFocus().
void VariantDB::DeleteAll ()
Definition at line 16 of file VariantDB.cpp.
Referenced by ~VariantDB().
int VariantDB::DeleteVar (string keyName)
Definition at line 38 of file VariantDB.cpp.
int VariantDB::DeleteVarsStartingWith (string deleteStr)
Definition at line 347 of file VariantDB.cpp.
std::string VariantDB::DumpAsString ()
Definition at line 372 of file VariantDB.cpp.
References Variant::Print().
FunctionObject * VariantDB::GetFunction (const string & keyName)
Definition at line 121 of file VariantDB.cpp.
References GetFunctionIfExists().
Referenced by EntityComponent::GetFunction(), and Entity::GetFunction().
FunctionObject * VariantDB::GetFunctionIfExists (const string & keyName)
Definition at line 108 of file VariantDB.cpp.
Referenced by CallFunctionIfExists(), Entity::CallFunctionRecursivelyWithUpdatedVar(), GetFunction(), and EntityComponent::OnRemove().
Variant * VariantDB::GetNext (string & keyOut)
Definition at line 396 of file VariantDB.cpp.
References ResetNext().
Variant * VariantDB::GetVar (const string & keyName)
Definition at line 93 of file VariantDB.cpp.
References GetVarIfExists().
Referenced by MySQLManager::AddSelectResults(), EntityComponent::GetVar(), Entity::GetVar(), Load(), and InterpolateComponent::OnAdd().
Variant * VariantDB::GetVarIfExists (const string & keyName)
Definition at line 63 of file VariantDB.cpp.
Referenced by Entity::CallFunctionRecursivelyWithUpdatedVar(), GetVar(), GetVarWithDefault(), Load(), and SetupInterpolateComponent().
Variant * VariantDB::GetVarWithDefault (const string & keyName, const Variant & vDefault)
Definition at line 78 of file VariantDB.cpp.
References GetVarIfExists().
Referenced by EntityComponent::GetVarWithDefault(), and Entity::GetVarWithDefault().
bool VariantDB::Load (const string & fileName, bool * pFileExistedOut = NULL, bool bAddBasePath = true)
Definition at line 191 of file VariantDB.cpp.
References GetSavePath(), GetVar(), GetVarIfExists(), LoadFromFile(), LogMsg(), RemoveFile(), Variant::Set(), Variant::TYPE_FLOAT, Variant::TYPE_INT32, Variant::TYPE_RECT, Variant::TYPE_STRING, Variant::TYPE_UINT32, Variant::TYPE_UNUSED, Variant::TYPE_VECTOR2, and Variant::TYPE_VECTOR3.
VariantDB& VariantDB::operator= (const VariantDB & rhs) [inline]
Definition at line 124 of file VariantDB.h.
void VariantDB::Print ()
Definition at line 330 of file VariantDB.cpp.
References LogMsg(), and Variant::Print().
void VariantDB::ResetNext ()
Definition at line 391 of file VariantDB.cpp.
Referenced by GetNext(), and VariantDB().
bool VariantDB::Save (const string & fileName, bool bAddBasePath = true)
Definition at line 144 of file VariantDB.cpp.
References GetSavePath(), LogError(), Variant::Save(), and Variant::TYPE_UNUSED.
The documentation for this class was generated from the following files:
VariantDB.h
VariantDB.cpp