Proton: AdProviderFlurry Class Reference
AdProviderFlurry Class Reference
#include <AdProviderFlurry.h>
Public Member Functions
AdProviderFlurry ()
virtual ~AdProviderFlurry ()
virtual bool OnAddToManager (AdManager *pAdManager)
virtual string GetName ()
virtual void Update ()
virtual bool OnMessage (Message &m)
virtual void TrackingOnPageView ()
virtual void TrackingLog (string eventName, string optionalKey="", string optionalValue="")
void SetupInfo (const string flurryAPIkey)
Detailed Description
Definition at line 15 of file AdProviderFlurry.h.
Constructor & Destructor Documentation
AdProviderFlurry::AdProviderFlurry ()
Definition at line 5 of file AdProviderFlurry.cpp.
References AD_PROVIDER_FLURRY, and AdProvider::m_adProviderType.
AdProviderFlurry::~AdProviderFlurry () [virtual]
Definition at line 10 of file AdProviderFlurry.cpp.
Member Function Documentation
virtual string AdProviderFlurry::GetName () [inline, virtual]
Implements AdProvider.
Definition at line 23 of file AdProviderFlurry.h.
bool AdProviderFlurry::OnAddToManager (AdManager * pAdManager) [virtual]
Implements AdProvider.
Definition at line 19 of file AdProviderFlurry.cpp.
References BaseApp::AddOSMessage(), GetBaseApp(), LogError(), LogMsg(), OSMessage::m_string, OSMessage::m_type, and OSMessage::MESSAGE_FLURRY_SETUP.
bool AdProviderFlurry::OnMessage (Message & m) [virtual]
Reimplemented from AdProvider.
Definition at line 37 of file AdProviderFlurry.cpp.
void AdProviderFlurry::SetupInfo (const string flurryAPIkey)
Definition at line 14 of file AdProviderFlurry.cpp.
void AdProviderFlurry::TrackingLog (string eventName, string optionalKey = "", string optionalValue = "") [virtual]
Reimplemented from AdProvider.
Definition at line 51 of file AdProviderFlurry.cpp.
References BaseApp::AddOSMessage(), GetBaseApp(), OSMessage::m_string, OSMessage::m_string2, OSMessage::m_string3, OSMessage::m_type, and OSMessage::MESSAGE_FLURRY_LOG_EVENT.
void AdProviderFlurry::TrackingOnPageView () [virtual]
Reimplemented from AdProvider.
Definition at line 42 of file AdProviderFlurry.cpp.
References BaseApp::AddOSMessage(), GetBaseApp(), OSMessage::m_type, and OSMessage::MESSAGE_FLURRY_ON_PAGE_VIEW.
virtual void AdProviderFlurry::Update () [inline, virtual]
Implements AdProvider.
Definition at line 24 of file AdProviderFlurry.h.
The documentation for this class was generated from the following files:
AdProviderFlurry.h
AdProviderFlurry.cpp