Proton: SpriteAnimationUtils Class Reference
SpriteAnimationUtils Class Reference
Various utility functions for dealing with sprites and sprite animations.
#include <SpriteAnimationUtils.h>
Static Public Member Functions
static void SetupAnimationEntity (Entity *pEntity, const std::string &fileName, const std::string &animationName=std::string())
Sets up pEntity to be used with a sprite animation.
static void SetAnimationName (Entity *pEntity, const std::string &animationName)
Sets a sprite animation name to animationName.
static void StartAnimationEntity (Entity *pEntity, const std::string &animationName, unsigned int animationDuration, unsigned int delayToStartMS=0, InterpolateComponent::eOnFinish finishType=InterpolateComponent::ON_FINISH_STOP)
Starts a sprite animation called animationName on pEntity.
Detailed Description
Various utility functions for dealing with sprites and sprite animations.
Definition at line 10 of file SpriteAnimationUtils.h.
Member Function Documentation
void SpriteAnimationUtils::SetAnimationName (Entity * pEntity, const std::string & animationName) [static]
Sets a sprite animation name to animationName.
The argument pEntity must already contain a SpriteAnimationRenderComponent. This method does not create one.
Definition at line 18 of file SpriteAnimationUtils.cpp.
References Entity::GetComponentByName(), Entity::GetName(), EntityComponent::GetVar(), LogError(), and Variant::Set().
void SpriteAnimationUtils::SetupAnimationEntity (Entity * pEntity, const std::string & fileName, const std::string & animationName = std::string()) [static]
Sets up pEntity to be used with a sprite animation.
The file from which the animation data is loaded is set by fileName. If an initial animation name should be set it can be given with animationName.
Definition at line 7 of file SpriteAnimationUtils.cpp.
References Entity::AddComponent(), EntityComponent::GetVar(), and Variant::Set().
void SpriteAnimationUtils::StartAnimationEntity (Entity * pEntity, const std::string & animationName, unsigned int animationDuration, unsigned int delayToStartMS = 0, InterpolateComponent::eOnFinish finishType = InterpolateComponent::ON_FINISH_STOP) [static]
Starts a sprite animation called animationName on pEntity.
The duration of the animation is set by animationDuration in milliseconds. It's expected that pEntity has been prepared with SetupSpriteAnimationEntity() before calling this function.
If delayToStartMS is greater than 0 then the animation is only started after this many milliseconds has passed.
When the animation ends by default the animation stops and the last frame of the animation is left visible. This behaviour can be changed by setting the finishType. For example the animation can be set to repeat itself from the start.
Definition at line 36 of file SpriteAnimationUtils.cpp.
References Entity::AddComponent(), Entity::GetComponentByName(), GetMessageManager(), Entity::GetName(), EntityComponent::GetVar(), INTERPOLATE_LINEAR, LogError(), Variant::Set(), MessageManager::SetComponentVariable(), and EntityComponent::SetName().
The documentation for this class was generated from the following files:
SpriteAnimationUtils.h
SpriteAnimationUtils.cpp