Proton: VariantList Class Reference
VariantList Class Reference
#include <Variant.h>
Public Member Functions
VariantList ()
Variant & Get (int parmNum)
VariantList (Variant v0)
VariantList (Variant v0, Variant v1)
VariantList (Variant v0, Variant v1, Variant v2)
VariantList (Variant v0, Variant v1, Variant v2, Variant v3)
VariantList (Variant v0, Variant v1, Variant v2, Variant v3, Variant v4)
VariantList (Variant v0, Variant v1, Variant v2, Variant v3, Variant v4, Variant v5)
void Reset ()
byte * SerializeToMem (uint32 *pSizeOut, byte *pDest)
bool SerializeFromMem (byte *pSrc, int length, int *pBytesReadOut=NULL)
void GetVariantListStartingAt (VariantList *pOut, int startIndex)
std::string GetContentsAsDebugString ()
Public Attributes
Variant m_variant [C_MAX_VARIANT_LIST_PARMS]
Detailed Description
Definition at line 440 of file Variant.h.
Constructor & Destructor Documentation
VariantList::VariantList () [inline]
Definition at line 444 of file Variant.h.
VariantList::VariantList (Variant v0) [inline]
Definition at line 447 of file Variant.h.
References m_variant.
VariantList::VariantList (Variant v0, Variant v1) [inline]
Definition at line 448 of file Variant.h.
References m_variant.
VariantList::VariantList (Variant v0, Variant v1, Variant v2) [inline]
Definition at line 449 of file Variant.h.
References m_variant.
VariantList::VariantList (Variant v0, Variant v1, Variant v2, Variant v3) [inline]
Definition at line 450 of file Variant.h.
References m_variant.
VariantList::VariantList (Variant v0, Variant v1, Variant v2, Variant v3, Variant v4) [inline]
Definition at line 451 of file Variant.h.
References m_variant.
VariantList::VariantList (Variant v0, Variant v1, Variant v2, Variant v3, Variant v4, Variant v5) [inline]
Definition at line 452 of file Variant.h.
References m_variant.
Member Function Documentation
Variant& VariantList::Get (int parmNum) [inline]
Definition at line 446 of file Variant.h.
References m_variant.
Referenced by FilterInputComponent::FilterOnInput(), LightBarOnChange(), MoveEntityToTop(), Gamepad::OnButton(), TouchHandlerArcadeComponent::OnInput(), TouchDragComponent::OnInput(), TouchHandlerComponent::OnInput(), GamepadMoga::OnJoypadEvent(), BaseApp::OnMessage(), MoveButtonState::OnPress(), MoveButtonState::OnPressToggle(), ArcadeInputComponent::OnRawKeyboard(), OnShowTextMessage(), PreloadKeyboard(), MoveButtonState::ReleaseIfNeeded(), ResizeScrollBounds(), ResizeScrollerAfterTextboxChanges(), and SendFakeInputMessageToEntity().
string VariantList::GetContentsAsDebugString ()
Definition at line 623 of file Variant.cpp.
References m_variant, Variant::Print(), toString(), and Variant::TYPE_UNUSED.
void VariantList::GetVariantListStartingAt (VariantList * pOut, int startIndex)
Definition at line 613 of file Variant.cpp.
References m_variant.
void VariantList::Reset () [inline]
Definition at line 454 of file Variant.h.
References m_variant, and Variant::Reset().
Referenced by BaseApp::OnMessage().
bool VariantList::SerializeFromMem (byte * pSrc, int length, int * pBytesReadOut = NULL)
Definition at line 517 of file Variant.cpp.
References LogMsg(), m_variant, Variant::Set(), Variant::TYPE_FLOAT, Variant::TYPE_INT32, Variant::TYPE_RECT, Variant::TYPE_STRING, Variant::TYPE_UINT32, Variant::TYPE_VECTOR2, and Variant::TYPE_VECTOR3.
byte * VariantList::SerializeToMem (uint32 * pSizeOut, byte * pDest)
Definition at line 436 of file Variant.cpp.
References GetSizeOfData(), Variant::GetType(), m_variant, and Variant::TYPE_STRING.
Member Data Documentation
Variant VariantList::m_variant[C_MAX_VARIANT_LIST_PARMS]
Definition at line 464 of file Variant.h.
Referenced by Entity::CallFunctionRecursivelyWithUpdatedVar(), Entity::CallFunctionRecursivelyWithUpdatedVarBackwards(), FilterComponent::FilterOnInput(), FilterInputComponent::FilterOnInput(), RenderClipComponent::FilterOnRender(), RenderScissorComponent::FilterOnRender(), Get(), GetContentsAsDebugString(), GetVariantListStartingAt(), OnCheckboxToggle(), Reset(), SerializeFromMem(), SerializeToMem(), and VariantList().
The documentation for this class was generated from the following files:
Variant.h
Variant.cpp