Proton: PassThroughPointerEventHandler Class Reference
PassThroughPointerEventHandler Class Reference
#include <PassThroughPointerEventHandler.h>
Public Member Functions
PassThroughPointerEventHandler ()
virtual ~PassThroughPointerEventHandler ()
virtual void handlePointerDownEvent (float x, float y, unsigned int pointerId)
virtual void handlePointerMoveEvent (float x, float y, unsigned int pointerId)
virtual void handlePointerUpEvent (float x, float y, unsigned int pointerId)
Detailed Description
Definition at line 6 of file PassThroughPointerEventHandler.h.
Constructor & Destructor Documentation
PassThroughPointerEventHandler::PassThroughPointerEventHandler ()
Definition at line 5 of file PassThroughPointerEventHandler.cpp.
PassThroughPointerEventHandler::~PassThroughPointerEventHandler () [virtual]
Definition at line 9 of file PassThroughPointerEventHandler.cpp.
Member Function Documentation
void PassThroughPointerEventHandler::handlePointerDownEvent (float x, float y, unsigned int pointerId) [virtual]
Implements PointerEventHandler.
Definition at line 13 of file PassThroughPointerEventHandler.cpp.
References GetMessageManager(), MESSAGE_TYPE_GUI_CLICK_START, and MessageManager::SendGUIEx().
void PassThroughPointerEventHandler::handlePointerMoveEvent (float x, float y, unsigned int pointerId) [virtual]
Implements PointerEventHandler.
Definition at line 18 of file PassThroughPointerEventHandler.cpp.
References GetMessageManager(), MESSAGE_TYPE_GUI_CLICK_MOVE, and MessageManager::SendGUIEx().
void PassThroughPointerEventHandler::handlePointerUpEvent (float x, float y, unsigned int pointerId) [virtual]
Implements PointerEventHandler.
Definition at line 23 of file PassThroughPointerEventHandler.cpp.
References GetMessageManager(), MESSAGE_TYPE_GUI_CLICK_END, and MessageManager::SendGUIEx().
The documentation for this class was generated from the following files:
PassThroughPointerEventHandler.h
PassThroughPointerEventHandler.cpp