Proton: PPlot Class Reference
PPlot Class Reference
#include <pplot.h>
Public Member Functions
PPlot ()
virtual ~PPlot ()
virtual bool Draw (Painter &inPainter)
void SetPPlotDrawer (PDrawer *inPDrawer)
void SetPPlotDrawer (PDrawer &inPDrawer)
virtual bool CalculateXTransformation (const PRect &inRect)
virtual bool CalculateYTransformation (const PRect &inRect)
virtual bool DrawGridXAxis (const PRect &inRect, Painter &inPainter) const
virtual bool DrawGridYAxis (const PRect &inRect, Painter &inPainter) const
virtual bool DrawXAxis (const PRect &inRect, Painter &inPainter) const
virtual bool DrawYAxis (const PRect &inRect, Painter &inPainter) const
virtual bool CalculateTickInfo (const PRect &inRect, Painter &inPainter)
Static Public Member Functions
static int Round (float inFloat)
Public Attributes
PlotDataContainer mPlotDataContainer
AxisSetup mXAxisSetup
AxisSetup mYAxisSetup
GridInfo mGridInfo
PMargins mMargins
PlotBackground mPlotBackground
bool mHasAnyModifyingCalculatorBeenActive
PCalculator::tList mModifyingCalculatorList
PCalculator::tList mPostCalculatorList
PDrawer::tList mPreDrawerList
PDrawer::tList mPostDrawerList
TickIterator * mXTickIterator
TickIterator * mYTickIterator
Trafo * mXTrafo
Trafo * mYTrafo
Static Public Attributes
static const float kRangeVerySmall = (float)1.0e-3
Protected Member Functions
PPlot (const PPlot &)
PPlot & operator= (const PPlot &)
virtual bool DrawPlotBackground (const PRect &inRect, Painter &inPainter) const
virtual bool DrawXTick (float inX, int inScreenY, bool inMajor, const string &inFormatString, Painter &inPainter, PRect &outRect) const
virtual bool DrawYTick (float inY, int inScreenX, bool inMajor, const string &inFormatString, Painter &inPainter, PRect &outRect) const
virtual bool DrawLegend (const PRect &inRect, Painter &inPainter) const
virtual bool DrawPlot (int inIndex, const PRect &inRect, Painter &inPainter) const
virtual bool ConfigureSelf ()
virtual bool ValidateData ()
virtual bool CalculateAxisRanges ()
virtual bool CheckRange (const AxisSetup &inAxisSetup) const
void SetTickSizes (int inFontHeight, TickInfo &ioTickInfo)
Static Protected Member Functions
static bool CalculateLogTransformation (int inBegin, int inEnd, const AxisSetup &inAxisSetup, LogTrafo &outTrafo)
static bool CalculateLinTransformation (int inBegin, int inEnd, const AxisSetup &inAxisSetup, LinTrafo &outTrafo)
Protected Attributes
LinTrafo mXLinTrafo
LinTrafo mYLinTrafo
LogTrafo mXLogTrafo
LogTrafo mYLogTrafo
LinTickIterator mXLinTickIterator
LinTickIterator mYLinTickIterator
LogTickIterator mXLogTickIterator
LogTickIterator mYLogTickIterator
NamedTickIterator mXNamedTickIterator
PDrawer * mPPlotDrawer
bool mOwnsPPlotDrawer
Detailed Description
Definition at line 489 of file pplot.h.
Constructor & Destructor Documentation
PPlot::PPlot ()
Definition at line 918 of file PPlot.cpp.
References kDefaultMargins, AxisSetup::mAscending, mMargins, and mYAxisSetup.
PPlot::~PPlot () [virtual]
Definition at line 931 of file PPlot.cpp.
References mOwnsPPlotDrawer, and mPPlotDrawer.
PPlot::PPlot (const PPlot &) [protected]
Member Function Documentation
bool PPlot::CalculateAxisRanges () [protected, virtual]
Definition at line 1685 of file PPlot.cpp.
References TickIterator::AdjustRange(), PlotDataContainer::CalculateXRange(), PlotDataContainer::CalculateYRange(), kLogMinClipValue, AxisSetup::mAutoScaleMax, AxisSetup::mAutoScaleMin, AxisSetup::mLogScale, AxisSetup::mMax, AxisSetup::mMin, mPlotDataContainer, mXAxisSetup, mXTickIterator, mYAxisSetup, and mYTickIterator.
Referenced by Draw().
bool PPlot::CalculateLinTransformation (int inBegin, int inEnd, const AxisSetup & inAxisSetup, LinTrafo & outTrafo) [static, protected]
Definition at line 1823 of file PPlot.cpp.
References kFloatSmall, AxisSetup::mAscending, AxisSetup::mMax, AxisSetup::mMin, LinTrafo::mOffset, and LinTrafo::mSlope.
Referenced by CalculateXTransformation(), and CalculateYTransformation().
bool PPlot::CalculateLogTransformation (int inBegin, int inEnd, const AxisSetup & inAxisSetup, LogTrafo & outTrafo) [static, protected]
Definition at line 1797 of file PPlot.cpp.
References kFloatSmall, AxisSetup::mAscending, LogTrafo::mBase, AxisSetup::mLogBase, AxisSetup::mMax, AxisSetup::mMin, LogTrafo::mOffset, LogTrafo::mSlope, and SafeLog().
Referenced by CalculateXTransformation(), and CalculateYTransformation().
bool PPlot::CalculateTickInfo (const PRect & inRect, Painter & inPainter) [virtual]
Definition at line 1744 of file PPlot.cpp.
References Painter::CalculateTextDrawSize(), Painter::GetFontHeight(), TickIterator::InitFromRanges(), kMajorTickXInitialFac, kMajorTickYInitialFac, kRangeVerySmall, TickInfo::mAutoTick, PRect::mH, AxisSetup::mMax, AxisSetup::mMin, AxisSetup::mTickInfo, PRect::mW, mXAxisSetup, mXTickIterator, mYAxisSetup, mYTickIterator, and SetTickSizes().
Referenced by Draw().
bool PPlot::CalculateXTransformation (const PRect & inRect) [virtual]
Definition at line 1844 of file PPlot.cpp.
References CalculateLinTransformation(), CalculateLogTransformation(), AxisSetup::mLogScale, PRect::mW, PRect::mX, mXAxisSetup, mXLinTrafo, and mXLogTrafo.
Referenced by Draw().
bool PPlot::CalculateYTransformation (const PRect & inRect) [virtual]
Definition at line 1854 of file PPlot.cpp.
References CalculateLinTransformation(), CalculateLogTransformation(), PRect::mH, AxisSetup::mLogScale, PRect::mY, mYAxisSetup, mYLinTrafo, and mYLogTrafo.
Referenced by Draw().
bool PPlot::CheckRange (const AxisSetup & inAxisSetup) const [protected, virtual]
Definition at line 1734 of file PPlot.cpp.
References kLogMinClipValue, AxisSetup::mLogScale, and AxisSetup::mMin.
Referenced by Draw().
bool PPlot::ConfigureSelf () [protected, virtual]
Definition at line 1618 of file PPlot.cpp.
References PlotDataContainer::GetConstXData(), PlotDataContainer::GetDataDrawer(), PlotDataContainer::GetPlotCount(), StringData::GetStringData(), AxisSetup::mCrossOrigin, AxisSetup::mLogScale, mPlotDataContainer, mXAxisSetup, mXLinTickIterator, mXLinTrafo, mXLogTickIterator, mXLogTrafo, mXNamedTickIterator, mXTickIterator, mXTrafo, mYAxisSetup, mYLinTickIterator, mYLinTrafo, mYLogTickIterator, mYLogTrafo, mYTickIterator, mYTrafo, TickIterator::SetAxisSetup(), DataDrawerBase::SetPlotCount(), DataDrawerBase::SetPlotIndex(), NamedTickIterator::SetStringList(), DataDrawerBase::SetXTrafo(), and DataDrawerBase::SetYTrafo().
Referenced by Draw().
bool PPlot::Draw (Painter & inPainter) [virtual]
Implements PDrawer.
Definition at line 938 of file PPlot.cpp.
References PCalculator::Calculate(), CalculateAxisRanges(), CalculateTickInfo(), CalculateXTransformation(), CalculateYTransformation(), CheckRange(), ConfigureSelf(), PDrawer::Draw(), DrawGridXAxis(), DrawGridYAxis(), DrawLegend(), DrawPlot(), DrawPlotBackground(), DrawXAxis(), DrawYAxis(), Painter::GetHeight(), PlotDataContainer::GetPlotCount(), Painter::GetWidth(), PMargins::mBottom, PRect::mH, mHasAnyModifyingCalculatorBeenActive, PMargins::mLeft, mMargins, mModifyingCalculatorList, mPlotDataContainer, mPostCalculatorList, mPostDrawerList, mPPlotDrawer, mPreDrawerList, PMargins::mRight, PMargins::mTop, PRect::mW, PRect::mX, mXAxisSetup, PRect::mY, mYAxisSetup, PDrawer::Prepare(), Painter::SetClipRect(), Painter::SetLineColor(), PCalculator::ShouldCalculate(), and ValidateData().
bool PPlot::DrawGridXAxis (const PRect & inRect, Painter & inPainter) const [virtual]
Definition at line 1106 of file PPlot.cpp.
References Painter::DrawLine(), TickIterator::GetNextTick(), TickIterator::Init(), mGridInfo, PRect::mH, TickInfo::mStyle, AxisSetup::mStyle, AxisSetup::mTickInfo, mXAxisSetup, GridInfo::mXGridOn, mXTickIterator, mXTrafo, PRect::mY, Painter::SetFillColor(), Painter::SetLineColor(), Painter::SetStyle(), and Trafo::Transform().
Referenced by Draw().
bool PPlot::DrawGridYAxis (const PRect & inRect, Painter & inPainter) const [virtual]
Definition at line 1138 of file PPlot.cpp.
References Painter::DrawLine(), TickIterator::GetNextTick(), TickIterator::Init(), mGridInfo, TickInfo::mStyle, AxisSetup::mStyle, AxisSetup::mTickInfo, TickInfo::mTicksOn, PRect::mW, PRect::mX, mYAxisSetup, GridInfo::mYGridOn, mYTickIterator, mYTrafo, Painter::SetFillColor(), Painter::SetLineColor(), Painter::SetStyle(), and Trafo::Transform().
Referenced by Draw().
bool PPlot::DrawLegend (const PRect & inRect, Painter & inPainter) const [protected, virtual]
Definition at line 1339 of file PPlot.cpp.
References Painter::CalculateTextDrawSize(), Painter::DrawText(), PlotDataContainer::GetConstLegendData(), Painter::GetFontHeight(), PlotDataContainer::GetPlotCount(), PColor::mB, LegendData::mColor, PColor::mG, LegendData::mName, mPlotDataContainer, PColor::mR, LegendData::mShow, LegendData::mStyle, PRect::mW, PRect::mX, PRect::mY, Painter::SetLineColor(), and Painter::SetStyle().
Referenced by Draw().
bool PPlot::DrawPlot (int inIndex, const PRect & inRect, Painter & inPainter) const [protected, virtual]
Definition at line 1587 of file PPlot.cpp.
References DataDrawerBase::DrawData(), PlotDataContainer::GetConstDataDrawer(), PlotDataContainer::GetConstLegendData(), PlotDataContainer::GetConstPlotDataSelection(), PlotDataContainer::GetConstXData(), PlotDataContainer::GetConstYData(), PlotDataContainer::GetPlotCount(), PColor::mB, LegendData::mColor, PColor::mG, mPlotDataContainer, PColor::mR, mXAxisSetup, Painter::SetFillColor(), and Painter::SetLineColor().
Referenced by Draw().
bool PPlot::DrawPlotBackground (const PRect & inRect, Painter & inPainter) const [protected, virtual]
Definition at line 1088 of file PPlot.cpp.
References Painter::CalculateTextDrawSize(), Painter::DrawText(), Painter::FillRect(), Painter::GetFontHeight(), PColor::mB, PColor::mG, PRect::mH, mMargins, mPlotBackground, PlotBackground::mPlotRegionBackColor, PColor::mR, PlotBackground::mStyle, PlotBackground::mTitle, PMargins::mTop, PlotBackground::mTransparent, PRect::mW, PRect::mX, PRect::mY, Round(), Painter::SetFillColor(), and Painter::SetStyle().
Referenced by Draw().
bool PPlot::DrawXAxis (const PRect & inRect, Painter & inPainter) const [virtual]
Definition at line 1171 of file PPlot.cpp.
References Painter::CalculateTextDrawSize(), Painter::DrawLine(), Painter::DrawText(), DrawXTick(), Painter::GetFontHeight(), TickIterator::GetNextTick(), TickIterator::Init(), AxisSetup::mAscending, AxisSetup::mCrossOrigin, PRect::mH, AxisSetup::mLabel, AxisSetup::mMax, AxisSetup::mMin, TickInfo::mStyle, AxisSetup::mStyle, AxisSetup::mTickInfo, TickInfo::mTicksOn, PRect::mW, PRect::mX, mXAxisSetup, mXTickIterator, PRect::mY, mYAxisSetup, mYTrafo, Painter::SetStyle(), and Trafo::Transform().
Referenced by Draw().
bool PPlot::DrawXTick (float inX, int inScreenY, bool inMajor, const string & inFormatString, Painter & inPainter, PRect & outRect) const [protected, virtual]
Definition at line 1232 of file PPlot.cpp.
References Painter::DrawLine(), Painter::DrawText(), Painter::GetFontHeight(), PRect::mH, TickInfo::mMajorTickScreenSize, TickInfo::mMinorTickScreenSize, AxisSetup::mTickInfo, PRect::mW, PRect::mX, mXAxisSetup, mXTrafo, PRect::mY, and Trafo::Transform().
Referenced by DrawXAxis().
bool PPlot::DrawYAxis (const PRect & inRect, Painter & inPainter) const [virtual]
Definition at line 1255 of file PPlot.cpp.
References Painter::CalculateTextDrawSize(), Painter::DrawLine(), Painter::DrawRotatedText(), DrawYTick(), TickIterator::GetNextTick(), TickIterator::Init(), AxisSetup::mAscending, AxisSetup::mCrossOrigin, PRect::mH, AxisSetup::mLabel, AxisSetup::mMax, AxisSetup::mMin, TickInfo::mStyle, AxisSetup::mStyle, AxisSetup::mTickInfo, TickInfo::mTicksOn, PRect::mX, mXAxisSetup, mXTrafo, PRect::mY, mYAxisSetup, mYTickIterator, Painter::SetStyle(), and Trafo::Transform().
Referenced by Draw().
bool PPlot::DrawYTick (float inY, int inScreenX, bool inMajor, const string & inFormatString, Painter & inPainter, PRect & outRect) const [protected, virtual]
Definition at line 1313 of file PPlot.cpp.
References Painter::CalculateTextDrawSize(), Painter::DrawLine(), Painter::DrawText(), Painter::GetFontHeight(), PRect::mH, TickInfo::mMajorTickScreenSize, TickInfo::mMinorTickScreenSize, AxisSetup::mTickInfo, PRect::mW, PRect::mX, PRect::mY, mYAxisSetup, mYTrafo, and Trafo::Transform().
Referenced by DrawYAxis().
PPlot& PPlot::operator= (const PPlot &) [protected]
int PPlot::Round (float inFloat) [static]
Definition at line 144 of file PPlot.cpp.
Referenced by DrawPlotBackground(), NamedTickIterator::GetNextTick(), LinTickIterator::InitFromRanges(), LogTickIterator::InitFromRanges(), TickInfo::RoundSpan(), and SetTickSizes().
void PPlot::SetPPlotDrawer (PDrawer * inPDrawer)
Definition at line 1075 of file PPlot.cpp.
References mOwnsPPlotDrawer, and mPPlotDrawer.
Referenced by MakePainterTester().
void PPlot::SetPPlotDrawer (PDrawer & inPDrawer)
Definition at line 1083 of file PPlot.cpp.
References mOwnsPPlotDrawer, and mPPlotDrawer.
void PPlot::SetTickSizes (int inFontHeight, TickInfo & ioTickInfo) [protected]
Definition at line 1785 of file PPlot.cpp.
References kMaxMajorTickSizeInFontHeight, kRelMajorTickSize, kRelMinorTickSize, TickInfo::mAutoTickSize, TickInfo::mMajorTickScreenSize, TickInfo::mMinorTickScreenSize, and Round().
Referenced by CalculateTickInfo().
bool PPlot::ValidateData () [protected, virtual]
Definition at line 1666 of file PPlot.cpp.
References PlotDataContainer::GetConstXData(), PlotDataContainer::GetPlotCount(), and mPlotDataContainer.
Referenced by Draw().
Member Data Documentation
const float PPlot::kRangeVerySmall = (float)1.0e-3 [static]
Definition at line 527 of file pplot.h.
Referenced by CalculateTickInfo(), and PZoomInteraction::DoZoomIn().
GridInfo PPlot::mGridInfo
Definition at line 499 of file pplot.h.
Referenced by DrawGridXAxis(), DrawGridYAxis(), MakeCopy(), MakeExamplePlot4(), and MakeExamplePlot7().
bool PPlot::mHasAnyModifyingCalculatorBeenActive
Definition at line 506 of file pplot.h.
Referenced by Draw().
PMargins PPlot::mMargins
Definition at line 500 of file pplot.h.
Referenced by PZoomInteraction::Draw(), PCrosshairInteraction::Draw(), Draw(), DrawPlotBackground(), MakeCopy(), MakeExamplePlot1(), MakeExamplePlot2(), MakeExamplePlot3(), MakeExamplePlot4(), MakeExamplePlot5(), MakeExamplePlot6(), MakeExamplePlot7(), MakeExamplePlot8(), and PPlot().
PCalculator::tList PPlot::mModifyingCalculatorList
Definition at line 507 of file pplot.h.
Referenced by Draw(), and PEditInteraction::PEditInteraction().
bool PPlot::mOwnsPPlotDrawer [protected]
Definition at line 560 of file pplot.h.
Referenced by SetPPlotDrawer(), and ~PPlot().
PlotBackground PPlot::mPlotBackground
Definition at line 501 of file pplot.h.
Referenced by DrawPlotBackground(), MakeCopy(), MakeExamplePlot1(), MakeExamplePlot2(), MakeExamplePlot3(), MakeExamplePlot6(), and MakeExamplePlot8().
PlotDataContainer PPlot::mPlotDataContainer
Definition at line 496 of file pplot.h.
Referenced by PSelectionInteraction::Calculate(), CalculateAxisRanges(), ConfigureSelf(), PCrosshairInteraction::Draw(), Draw(), DrawLegend(), DrawPlot(), PVerticalCursorInteraction::Impl_Calculate(), PDeleteInteraction::Impl_Calculate(), MakeCopy(), MakeExamplePlot1(), MakeExamplePlot2(), MakeExamplePlot3(), MakeExamplePlot4(), MakeExamplePlot5(), MakeExamplePlot6(), MakeExamplePlot7(), MakeExamplePlot8(), and ValidateData().
PCalculator::tList PPlot::mPostCalculatorList
Definition at line 508 of file pplot.h.
Referenced by Draw(), and PSelectionInteraction::PSelectionInteraction().
PDrawer::tList PPlot::mPostDrawerList
Definition at line 510 of file pplot.h.
Referenced by Draw(), PCrosshairInteraction::PCrosshairInteraction(), and PZoomInteraction::PZoomInteraction().
PDrawer* PPlot::mPPlotDrawer [protected]
Definition at line 559 of file pplot.h.
Referenced by Draw(), SetPPlotDrawer(), and ~PPlot().
PDrawer::tList PPlot::mPreDrawerList
Definition at line 509 of file pplot.h.
Referenced by Draw().
AxisSetup PPlot::mXAxisSetup
Definition at line 497 of file pplot.h.
Referenced by CalculateAxisRanges(), CalculateTickInfo(), CalculateXTransformation(), ConfigureSelf(), PZoomInteraction::DoZoomIn(), PZoomInteraction::DoZoomOut(), Draw(), DrawGridXAxis(), DrawPlot(), DrawXAxis(), DrawXTick(), DrawYAxis(), MakeCopy(), MakeExamplePlot1(), MakeExamplePlot2(), MakeExamplePlot4(), and PZoomInteraction::StoreCurrentAxisSetup().
LinTickIterator PPlot::mXLinTickIterator [protected]
Definition at line 553 of file pplot.h.
Referenced by ConfigureSelf().
LinTrafo PPlot::mXLinTrafo [protected]
Definition at line 548 of file pplot.h.
Referenced by CalculateXTransformation(), and ConfigureSelf().
LogTickIterator PPlot::mXLogTickIterator [protected]
Definition at line 555 of file pplot.h.
Referenced by ConfigureSelf().
LogTrafo PPlot::mXLogTrafo [protected]
Definition at line 550 of file pplot.h.
Referenced by CalculateXTransformation(), and ConfigureSelf().
NamedTickIterator PPlot::mXNamedTickIterator [protected]
Definition at line 557 of file pplot.h.
Referenced by ConfigureSelf().
TickIterator* PPlot::mXTickIterator
Definition at line 512 of file pplot.h.
Referenced by CalculateAxisRanges(), CalculateTickInfo(), ConfigureSelf(), DrawGridXAxis(), and DrawXAxis().
Trafo* PPlot::mXTrafo
Definition at line 523 of file pplot.h.
Referenced by PSelectionInteraction::CalculateDistanceToPlot(), ConfigureSelf(), PZoomInteraction::DoZoomIn(), PCrosshairInteraction::Draw(), DrawGridXAxis(), DrawXTick(), DrawYAxis(), and PCrosshairInteraction::GetCrossPoint().
AxisSetup PPlot::mYAxisSetup
Definition at line 498 of file pplot.h.
Referenced by CalculateAxisRanges(), CalculateTickInfo(), CalculateYTransformation(), ConfigureSelf(), PZoomInteraction::DoZoomIn(), PZoomInteraction::DoZoomOut(), Draw(), DrawGridYAxis(), DrawXAxis(), DrawYAxis(), DrawYTick(), MakeCopy(), MakeExamplePlot1(), MakeExamplePlot2(), MakeExamplePlot4(), MakeExamplePlot7(), PPlot(), and PZoomInteraction::StoreCurrentAxisSetup().
LinTickIterator PPlot::mYLinTickIterator [protected]
Definition at line 554 of file pplot.h.
Referenced by ConfigureSelf().
LinTrafo PPlot::mYLinTrafo [protected]
Definition at line 549 of file pplot.h.
Referenced by CalculateYTransformation(), and ConfigureSelf().
LogTickIterator PPlot::mYLogTickIterator [protected]
Definition at line 556 of file pplot.h.
Referenced by ConfigureSelf().
LogTrafo PPlot::mYLogTrafo [protected]
Definition at line 551 of file pplot.h.
Referenced by CalculateYTransformation(), and ConfigureSelf().
TickIterator* PPlot::mYTickIterator
Definition at line 513 of file pplot.h.
Referenced by CalculateAxisRanges(), CalculateTickInfo(), ConfigureSelf(), DrawGridYAxis(), and DrawYAxis().
Trafo* PPlot::mYTrafo
Definition at line 524 of file pplot.h.
Referenced by PSelectionInteraction::CalculateDistanceToPlot(), ConfigureSelf(), PZoomInteraction::DoZoomIn(), PCrosshairInteraction::Draw(), DrawGridYAxis(), DrawXAxis(), DrawYTick(), PCrosshairInteraction::GetCrossPoint(), and PVerticalCursorInteraction::HandleVerticalCursorKey().
The documentation for this class was generated from the following files:
pplot.h
PPlot.cpp