Proton: EmitVirtualKeyComponent Class Reference
EmitVirtualKeyComponent Class Reference
#include <EmitVirtualKeyComponent.h>
Public Member Functions
EmitVirtualKeyComponent ()
virtual ~EmitVirtualKeyComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
Detailed Description
Definition at line 26 of file EmitVirtualKeyComponent.h.
Constructor & Destructor Documentation
EmitVirtualKeyComponent::EmitVirtualKeyComponent ()
Definition at line 5 of file EmitVirtualKeyComponent.cpp.
References EntityComponent::SetName().
EmitVirtualKeyComponent::~EmitVirtualKeyComponent () [virtual]
Definition at line 10 of file EmitVirtualKeyComponent.cpp.
Member Function Documentation
void EmitVirtualKeyComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 16 of file EmitVirtualKeyComponent.cpp.
References Entity::GetFunction(), EntityComponent::GetParent(), Variant::GetUINT32(), EntityComponent::GetVar(), and FunctionObject::sig_function.
void EmitVirtualKeyComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 26 of file EmitVirtualKeyComponent.cpp.
The documentation for this class was generated from the following files:
EmitVirtualKeyComponent.h
EmitVirtualKeyComponent.cpp