Proton: LinTickIterator Class Reference
LinTickIterator Class Reference
#include <pplot.h>
Public Member Functions
LinTickIterator ()
virtual bool Init ()
virtual bool GetNextTick (float &outTick, bool &outIsMajorTick, string &outFormatString)
bool InitFromRanges (float inParRange, float inOrthoScreenRange, float inDivGuess, TickInfo &outTickInfo) const
Protected Attributes
float mCurrentTick
long mCount
float mDelta
string mFormatString
Detailed Description
Definition at line 409 of file pplot.h.
Constructor & Destructor Documentation
LinTickIterator::LinTickIterator () [inline]
Definition at line 411 of file pplot.h.
Member Function Documentation
bool LinTickIterator::GetNextTick (float & outTick, bool & outIsMajorTick, string & outFormatString) [virtual]
Implements TickIterator.
Reimplemented in NamedTickIterator.
Definition at line 691 of file PPlot.cpp.
References kLittleIncrease.
Referenced by NamedTickIterator::GetNextTick().
bool LinTickIterator::Init () [virtual]
Implements TickIterator.
Definition at line 673 of file PPlot.cpp.
bool LinTickIterator::InitFromRanges (float inParRange, float inOrthoScreenRange, float inDivGuess, TickInfo & outTickInfo) const [virtual]
Implements TickIterator.
Reimplemented in NamedTickIterator.
Definition at line 707 of file PPlot.cpp.
References kFloatSmall, kMinMinorTickScreenSize, kRelMajorTickSize, kRelMinorTickSize, TickInfo::MakeFormatString(), TickInfo::mAutoTickSize, TickInfo::mFormatString, TickInfo::mMajorTickScreenSize, TickInfo::mMajorTickSpan, TickInfo::mMinorTickScreenSize, TickInfo::mTickDivision, PMax(), PPlot::Round(), and TickInfo::RoundSpan().
Referenced by NamedTickIterator::InitFromRanges().
Member Data Documentation
long LinTickIterator::mCount [protected]
Definition at line 418 of file pplot.h.
float LinTickIterator::mCurrentTick [protected]
Definition at line 417 of file pplot.h.
float LinTickIterator::mDelta [protected]
Definition at line 419 of file pplot.h.
string LinTickIterator::mFormatString [protected]
Definition at line 420 of file pplot.h.
The documentation for this class was generated from the following files:
pplot.h
PPlot.cpp