Proton: TickIterator Class Reference
TickIterator Class Reference
#include <pplot.h>
Public Member Functions
TickIterator ()
virtual ~TickIterator ()
virtual bool Init ()=0
virtual bool GetNextTick (float &outTick, bool &outIsMajorTick, string &outFormatString)=0
virtual bool InitFromRanges (float inParRange, float inOrthoScreenRange, float inDivGuess, TickInfo &outTickInfo) const =0
virtual bool AdjustRange (float &ioMin, float &ioMax) const
void SetAxisSetup (const AxisSetup *inAxisSetup)
Protected Attributes
const AxisSetup * mAxisSetup
Detailed Description
Definition at line 393 of file pplot.h.
Constructor & Destructor Documentation
TickIterator::TickIterator () [inline]
Definition at line 395 of file pplot.h.
virtual TickIterator::~TickIterator () [inline, virtual]
Definition at line 396 of file pplot.h.
Member Function Documentation
virtual bool TickIterator::AdjustRange (float & ioMin, float & ioMax) const [inline, virtual]
Reimplemented in LogTickIterator.
Definition at line 402 of file pplot.h.
Referenced by PPlot::CalculateAxisRanges().
virtual bool TickIterator::GetNextTick (float & outTick, bool & outIsMajorTick, string & outFormatString) [pure virtual]
Implemented in NamedTickIterator, LogTickIterator, and LinTickIterator.
Referenced by PPlot::DrawGridXAxis(), PPlot::DrawGridYAxis(), PPlot::DrawXAxis(), and PPlot::DrawYAxis().
virtual bool TickIterator::Init () [pure virtual]
Implemented in LogTickIterator, and LinTickIterator.
Referenced by PPlot::DrawGridXAxis(), PPlot::DrawGridYAxis(), PPlot::DrawXAxis(), and PPlot::DrawYAxis().
virtual bool TickIterator::InitFromRanges (float inParRange, float inOrthoScreenRange, float inDivGuess, TickInfo & outTickInfo) const [pure virtual]
Implemented in NamedTickIterator, LogTickIterator, and LinTickIterator.
Referenced by PPlot::CalculateTickInfo().
void TickIterator::SetAxisSetup (const AxisSetup * inAxisSetup) [inline]
Definition at line 404 of file pplot.h.
References mAxisSetup.
Referenced by PPlot::ConfigureSelf().
Member Data Documentation
const AxisSetup* TickIterator::mAxisSetup [protected]
Definition at line 404 of file pplot.h.
Referenced by SetAxisSetup().
The documentation for this class was generated from the following file:
pplot.h