Proton: PlotDataBase Class Reference
PlotDataBase Class Reference
#include <pplot.h>
Public Member Functions
virtual ~PlotDataBase ()
virtual const RealPlotData * GetRealPlotData () const =0
virtual const CalculatedDataBase * GetCalculatedData () const
long GetSize () const
float GetValue (long inIndex) const
virtual bool CalculateRange (float &outMin, float &outMax)
Detailed Description
Definition at line 41 of file pplot.h.
Constructor & Destructor Documentation
PlotDataBase::~PlotDataBase () [virtual]
Definition at line 274 of file PPlot.cpp.
Member Function Documentation
bool PlotDataBase::CalculateRange (float & outMin, float & outMax) [virtual]
Definition at line 81 of file PPlot.cpp.
References CalculatedDataBase::GetSize(), and CalculatedDataBase::GetValue().
Referenced by PlotDataContainer::CalculateXRange().
virtual const CalculatedDataBase* PlotDataBase::GetCalculatedData () const [inline, virtual]
Reimplemented in CalculatedPlotData, and PlotDataPointer.
Definition at line 45 of file pplot.h.
Referenced by PlotDataContainer::AddXYPlot(), and PlotDataPointer::GetCalculatedData().
virtual const RealPlotData* PlotDataBase::GetRealPlotData () const [pure virtual]
Implemented in StringData, DummyData, CalculatedPlotData, PlotData, and PlotDataPointer.
Referenced by PlotDataContainer::AddXYPlot(), PlotDataPointer::GetRealPlotData(), and PlotDataContainer::SetXYPlot().
long PlotDataBase::GetSize () const
Definition at line 61 of file PPlot.cpp.
Referenced by PlotDataContainer::AddXYPlot(), PSelectionInteraction::CalculateDistanceToPlot(), PlotDataContainer::CalculateXRange(), PlotDataContainer::CalculateYRangePlot(), LineDataDrawer::DrawData(), BarDataDrawer::DrawData(), BarDataDrawer::DrawOnlyLastPoint(), FindRange(), PCrosshairInteraction::GetCrossPoint(), PDeleteInteraction::HandleDeleteKey(), PVerticalCursorInteraction::HandleVerticalCursorKey(), and PlotDataContainer::SetXYPlot().
float PlotDataBase::GetValue (long inIndex) const
Definition at line 71 of file PPlot.cpp.
Referenced by PSelectionInteraction::CalculateDistanceToPlot(), PlotDataContainer::CalculateYRangePlot(), LineDataDrawer::DrawData(), BarDataDrawer::DrawData(), BarDataDrawer::DrawOnlyLastPoint(), FindRange(), PCrosshairInteraction::GetCrossPoint(), and GetMaxFromRange().
The documentation for this class was generated from the following files:
pplot.h
PPlot.cpp