Proton: AudioManagerFlash Class Reference
AudioManagerFlash Class Reference
#include <AudioManagerFlash.h>
Public Member Functions
AudioManagerFlash ()
virtual ~AudioManagerFlash ()
virtual bool Init ()
virtual void Kill ()
virtual AudioHandle Play (string fName, bool bLooping=false, bool bIsMusic=false, bool bAddBasePath=true, bool bForceStreaming=false)
Plays an audio specified by a file name.
virtual void Preload (string fName, bool bLooping=false, bool bIsMusic=false, bool bAddBasePath=true, bool bForceStreaming=false)
SoundObjectFlash * GetSoundObjectByFileName (string fName)
virtual void KillCachedSounds (bool bKillMusic, bool bKillLooping, int ignoreSoundsUsedInLastMS, int killSoundsLowerPriorityThanThis, bool bKillSoundsPlaying)
virtual void Update ()
This method must be called periodically, e.g once every frame.
virtual void Stop (AudioHandle soundID)
virtual AudioHandle GetMusicChannel ()
virtual bool IsPlaying (AudioHandle soundID)
virtual void SetMusicEnabled (bool bNew)
Enables or disables the playing of music.
virtual void StopMusic ()
Stops the currently playing music immediately.
virtual int GetMemoryUsed ()
bool DeleteSoundObjectByFileName (string fName)
virtual void SetFrequency (AudioHandle soundID, int freq)
virtual void SetPan (AudioHandle soundID, float pan)
virtual void SetVol (AudioHandle soundID, float vol)
virtual void SetPriority (AudioHandle soundID, int priority)
virtual uint32 GetPos (AudioHandle soundID)
virtual void SetPos (AudioHandle soundID, uint32 posMS)
virtual void SetMusicVol (float vol)
virtual void Suspend ()
virtual void Resume ()
SoundObjectFlash * GetSoundObjectByPointer (void *p)
void Testy ()
Detailed Description
Definition at line 41 of file AudioManagerFlash.h.
Constructor & Destructor Documentation
AudioManagerFlash::AudioManagerFlash ()
Definition at line 31 of file AudioManagerFlash.cpp.
AudioManagerFlash::~AudioManagerFlash () [virtual]
Definition at line 37 of file AudioManagerFlash.cpp.
References Kill().
Member Function Documentation
bool AudioManagerFlash::DeleteSoundObjectByFileName (string fName)
Definition at line 94 of file AudioManagerFlash.cpp.
int AudioManagerFlash::GetMemoryUsed () [virtual]
Reimplemented from AudioManager.
Definition at line 370 of file AudioManagerFlash.cpp.
AudioHandle AudioManagerFlash::GetMusicChannel () [virtual]
Definition at line 322 of file AudioManagerFlash.cpp.
References AudioManager::m_lastMusicID.
uint32 AudioManagerFlash::GetPos (AudioHandle soundID) [virtual]
Reimplemented from AudioManager.
Definition at line 386 of file AudioManagerFlash.cpp.
SoundObjectFlash * AudioManagerFlash::GetSoundObjectByFileName (string fName)
Definition at line 112 of file AudioManagerFlash.cpp.
Referenced by Play(), and Preload().
SoundObjectFlash * AudioManagerFlash::GetSoundObjectByPointer (void * p)
Definition at line 128 of file AudioManagerFlash.cpp.
Referenced by IsPlaying(), and SetVol().
bool AudioManagerFlash::Init () [virtual]
Reimplemented from AudioManager.
Definition at line 43 of file AudioManagerFlash.cpp.
References LogMsg().
bool AudioManagerFlash::IsPlaying (AudioHandle soundID) [virtual]
Reimplemented from AudioManager.
Definition at line 328 of file AudioManagerFlash.cpp.
References GetSoundObjectByPointer(), AudioManager::m_bLastMusicLooping, AudioManager::m_bMusicEnabled, and AudioManager::m_lastMusicID.
void AudioManagerFlash::Kill () [virtual]
Reimplemented from AudioManager.
Definition at line 89 of file AudioManagerFlash.cpp.
Referenced by ~AudioManagerFlash().
void AudioManagerFlash::KillCachedSounds (bool bKillMusic, bool bKillLooping, int ignoreSoundsUsedInLastMS, int killSoundsLowerPriorityThanThis, bool bKillSoundsPlaying) [virtual]
Reimplemented from AudioManager.
Definition at line 49 of file AudioManagerFlash.cpp.
References LogMsg(), and AudioManager::m_lastMusicFileName.
AudioHandle AudioManagerFlash::Play (string fName, bool bLooping = false, bool bIsMusic = false, bool bAddBasePath = true, bool bForceStreaming = false) [virtual]
Plays an audio specified by a file name.
Returns the audio handle for the playing sound if the playing started successfully. Returns AUDIO_HANDLE_BLANK if the playing of the audio didn't start successfully. Also returns AUDIO_HANDLE_BLANK if requesting to play a sound file and sound is currently disabled or requesting to play music and music is currently disabled.
Parameters:
fName the file name of the audio to play.
bLooping whether the sound should start again when it ends, i.e. loop.
bIsMusic specifies if this sound is the music track.
bAddBasePath adds the base path to the file name. See GetBaseAppPath().
bForceStreaming streams the audio directly from the file and doesn't load it into memory. This flag might not be supported by all audio backends.
Returns:
The audio handle for the playing sound if the playing started successfully. Returns AUDIO_HANDLE_BLANK if the playing of the audio didn't start.
Reimplemented from AudioManager.
Definition at line 218 of file AudioManagerFlash.cpp.
References AudioManager::GetMusicEnabled(), AudioManager::GetSoundEnabled(), GetSoundObjectByFileName(), LogError(), LogMsg(), SoundObjectFlash::m_bIsLooping, AudioManager::m_bLastMusicLooping, AudioManager::m_lastMusicFileName, AudioManager::m_lastMusicID, AudioManager::m_musicVol, SoundObjectFlash::m_sampleID, Preload(), SetMusicVol(), StopMusic(), and StringReplace().
Referenced by SetMusicEnabled().
void AudioManagerFlash::Preload (string fName, bool bLooping = false, bool bIsMusic = false, bool bAddBasePath = true, bool bForceStreaming = false) [virtual]
Reimplemented from AudioManager.
Definition at line 144 of file AudioManagerFlash.cpp.
References FileManager::Get(), GetBaseAppPath(), GetFileManager(), AudioManager::GetMusicEnabled(), GetSoundObjectByFileName(), LogMsg(), SoundObjectFlash::m_bIsLooping, SoundObjectFlash::m_bIsMusic, SoundObjectFlash::m_fileName, SoundObjectFlash::m_sampleID, and StringReplace().
Referenced by Play().
void AudioManagerFlash::Resume () [virtual]
Reimplemented from AudioManager.
Definition at line 442 of file AudioManagerFlash.cpp.
void AudioManagerFlash::SetFrequency (AudioHandle soundID, int freq) [virtual]
Reimplemented from AudioManager.
Definition at line 376 of file AudioManagerFlash.cpp.
void AudioManagerFlash::SetMusicEnabled (bool bNew) [virtual]
Enables or disables the playing of music.
When the music system is disabled any currently playing music is stopped. When the music system is later enabled again the music file that was left playing is resumed from the location where it stopped.
Reimplemented from AudioManager.
Definition at line 346 of file AudioManagerFlash.cpp.
References AudioManager::m_bLastMusicLooping, AudioManager::m_bMusicEnabled, AudioManager::m_lastMusicFileName, Play(), and StopMusic().
void AudioManagerFlash::SetMusicVol (float vol) [virtual]
Reimplemented from AudioManager.
Definition at line 407 of file AudioManagerFlash.cpp.
References LogMsg(), and AudioManager::m_musicVol.
Referenced by Play(), and SetVol().
void AudioManagerFlash::SetPan (AudioHandle soundID, float pan) [virtual]
Reimplemented from AudioManager.
Definition at line 381 of file AudioManagerFlash.cpp.
void AudioManagerFlash::SetPos (AudioHandle soundID, uint32 posMS) [virtual]
Reimplemented from AudioManager.
Definition at line 391 of file AudioManagerFlash.cpp.
void AudioManagerFlash::SetPriority (AudioHandle soundID, int priority) [virtual]
Reimplemented from AudioManager.
Definition at line 419 of file AudioManagerFlash.cpp.
void AudioManagerFlash::SetVol (AudioHandle soundID, float vol) [virtual]
Reimplemented from AudioManager.
Definition at line 395 of file AudioManagerFlash.cpp.
References GetSoundObjectByPointer(), AudioManager::m_musicVol, and SetMusicVol().
void AudioManagerFlash::Stop (AudioHandle soundID) [virtual]
Reimplemented from AudioManager.
Definition at line 303 of file AudioManagerFlash.cpp.
References AudioManager::m_lastMusicID.
Referenced by StopMusic().
void AudioManagerFlash::StopMusic () [virtual]
Stops the currently playing music immediately.
Reimplemented from AudioManager.
Definition at line 365 of file AudioManagerFlash.cpp.
References AudioManager::m_lastMusicID, and Stop().
Referenced by Play(), and SetMusicEnabled().
void AudioManagerFlash::Suspend () [virtual]
Reimplemented from AudioManager.
Definition at line 424 of file AudioManagerFlash.cpp.
void AudioManagerFlash::Testy ()
Definition at line 447 of file AudioManagerFlash.cpp.
References LogMsg().
void AudioManagerFlash::Update () [virtual]
This method must be called periodically, e.g once every frame.
Reimplemented from AudioManager.
Definition at line 298 of file AudioManagerFlash.cpp.
The documentation for this class was generated from the following files:
AudioManagerFlash.h
AudioManagerFlash.cpp