Proton: L_DroppingEffect Class Reference
L_DroppingEffect Class Reference
The simplest among particle effects. It drops a particle on its position each period.
#include <L_DroppingEffect.h>
Public Member Functions
L_DroppingEffect ()
period_t : time(milisec) for next dropping
L_DroppingEffect (int x, int y, int period_t)
L_DroppingEffect (const L_DroppingEffect &cpy)
virtual L_ParticleEffect * new_clone (void)
Create a clone this particle effect.
Protected Member Functions
virtual void howto_emit_particle (void)
Detailed Description
The simplest among particle effects. It drops a particle on its position each period.
Definition at line 34 of file L_DroppingEffect.h.
Constructor & Destructor Documentation
L_DroppingEffect::L_DroppingEffect ()
period_t : time(milisec) for next dropping
Definition at line 39 of file L_DroppingEffect.cpp.
Referenced by new_clone().
L_DroppingEffect::L_DroppingEffect (int x, int y, int period_t)
Definition at line 30 of file L_DroppingEffect.cpp.
L_DroppingEffect::L_DroppingEffect (const L_DroppingEffect & cpy)
Definition at line 35 of file L_DroppingEffect.cpp.
Member Function Documentation
void L_DroppingEffect::howto_emit_particle (void) [protected, virtual]
Implements L_ParticleEffect.
Definition at line 44 of file L_DroppingEffect.cpp.
References L_ParticleEffect::create_particle(), L_ParticleEffect::x_pos, and L_ParticleEffect::y_pos.
L_ParticleEffect * L_DroppingEffect::new_clone (void) [virtual]
Create a clone this particle effect.
Implements L_ParticleEffect.
Definition at line 50 of file L_DroppingEffect.cpp.
References L_DroppingEffect().
The documentation for this class was generated from the following files:
L_DroppingEffect.h
L_DroppingEffect.cpp