Proton: MessageManager Class Reference
MessageManager Class Reference
#include <MessageManager.h>
Public Member Functions
MessageManager ()
virtual ~MessageManager ()
void SendGUI (eMessageType type, float parm1, float parm2=0, int deliverTimeMS=0, eTimingSystem timing=TIMER_SYSTEM)
void SendGUI (eMessageType type, const Variant &v, int deliverTimeMS=0)
void SendGUI (eMessageType type, const VariantList &vList, int deliverTimeMS=0)
void SendGUIEx (eMessageType type, float parm1, float parm2, int finger, int deliverTimeMS=0, eTimingSystem timing=TIMER_SYSTEM)
void SendGUIEx2 (eMessageType type, float parm1, float parm2, int finger, uint32 modifiers, int deliverTimeMS=0, eTimingSystem timing=TIMER_SYSTEM)
void SendGUIStringEx (eMessageType type, float parm1, float parm2, int finger, string s, int deliverTimeMS=0, eTimingSystem timing=TIMER_SYSTEM)
void SendGame (eMessageType type, const string msg, int deliverTimeMS=0, eTimingSystem timing=TIMER_GAME)
void SendGame (eMessageType type, const Variant &v, int deliverTimeMS=0, eTimingSystem timing=TIMER_GAME)
void SetEntityVariable (Entity *pEnt, int timeMS, const string &varName, const Variant &v, eTimingSystem timing=GetTiming())
void SetComponentVariable (EntityComponent *pComp, int timeMS, const string &varName, const Variant &v, eTimingSystem timing=GetTiming())
void RemoveComponentByName (Entity *pEnt, int timeMS, const string &compName, eTimingSystem timing=GetTiming())
void CallEntityFunction (Entity *pEnt, int timeMS, const string &funcName, const VariantList *v=NULL, eTimingSystem timing=GetTiming())
void CallEntityFunctionRecursively (Entity *pEnt, int timeMS, const string &funcName, const VariantList *v=NULL, eTimingSystem timing=GetTiming())
void CallComponentFunction (EntityComponent *pComp, int timeMS, const string &funcName, const VariantList *v=NULL, eTimingSystem timing=GetTiming())
void CallComponentFunction (Entity *pEnt, const string &compName, int timeMS, const string &funcName, const VariantList *v=NULL, eTimingSystem timing=GetTiming())
void AddComponent (Entity *pEnt, int timeMS, EntityComponent *pComp, eTimingSystem timing=GetTiming())
void CallStaticFunction (PtrFuncVarList pFunctionWithVList, int timeMS, const VariantList *v=NULL, eTimingSystem timing=GetTiming())
void DeleteMessagesByFunctionCallName (const string &name, eTimingSystem timing=GetTiming())
void DeleteMessagesToComponent (EntityComponent *pComponent)
void DeleteMessagesToEntity (Entity *pComponent)
void DeleteMessagesByType (eMessageType type, eTimingSystem timing=GetTiming())
void DumpMessages ()
void Update ()
void DeleteAllMessages ()
Detailed Description
Definition at line 269 of file MessageManager.h.
Constructor & Destructor Documentation
MessageManager::MessageManager ()
Definition at line 57 of file MessageManager.cpp.
MessageManager::~MessageManager () [virtual]
Definition at line 61 of file MessageManager.cpp.
References DeleteAllMessages().
Member Function Documentation
void MessageManager::AddComponent (Entity * pEnt, int timeMS, EntityComponent * pComp, eTimingSystem timing = GetTiming())
Definition at line 444 of file MessageManager.cpp.
References MESSAGE_CLASS_ENTITY, MESSAGE_TYPE_REMOVE_COMPONENT, Message::SetComponentToAdd(), Message::SetDeliveryTime(), and Message::SetTargetEntity().
Referenced by AddFocusIfNeeded().
void MessageManager::CallComponentFunction (EntityComponent * pComp, int timeMS, const string & funcName, const VariantList * v = NULL, eTimingSystem timing = GetTiming())
Definition at line 411 of file MessageManager.cpp.
References MESSAGE_CLASS_ENTITY, MESSAGE_TYPE_CALL_ENTITY_FUNCTION, Message::Set(), Message::SetDeliveryTime(), Message::SetTargetComponent(), and Message::SetVarName().
Referenced by AddFocusIfNeeded().
void MessageManager::CallComponentFunction (Entity * pEnt, const string & compName, int timeMS, const string & funcName, const VariantList * v = NULL, eTimingSystem timing = GetTiming())
Definition at line 422 of file MessageManager.cpp.
References MESSAGE_CLASS_ENTITY, MESSAGE_TYPE_CALL_COMPONENT_FUNCTION_BY_NAME, Message::Set(), Message::SetDeliveryTime(), Message::SetStringParm(), Message::SetTargetEntity(), and Message::SetVarName().
void MessageManager::CallEntityFunction (Entity * pEnt, int timeMS, const string & funcName, const VariantList * v = NULL, eTimingSystem timing = GetTiming())
Definition at line 382 of file MessageManager.cpp.
References MESSAGE_CLASS_ENTITY, MESSAGE_TYPE_CALL_ENTITY_FUNCTION, Message::Set(), Message::SetDeliveryTime(), Message::SetTargetEntity(), and Message::SetVarName().
Referenced by CreateScrollingTextBoxEntity(), KillEntity(), OnShowTextMessage(), SendFakeButtonPushToEntity(), SendFakeInputMessageToEntity(), Entity::SetTaggedForDeletion(), and IAPManager::TestDelayedIAP().
void MessageManager::CallEntityFunctionRecursively (Entity * pEnt, int timeMS, const string & funcName, const VariantList * v = NULL, eTimingSystem timing = GetTiming())
Definition at line 401 of file MessageManager.cpp.
References MESSAGE_CLASS_ENTITY, MESSAGE_TYPE_CALL_ENTITY_FUNCTION, Message::Set(), Message::SetDeliveryTime(), Message::SetTargetEntity(), and Message::SetVarName().
void MessageManager::CallStaticFunction (PtrFuncVarList pFunctionWithVList, int timeMS, const VariantList * v = NULL, eTimingSystem timing = GetTiming())
Definition at line 392 of file MessageManager.cpp.
References MESSAGE_CLASS_ENTITY, MESSAGE_TYPE_CALL_STATIC_FUNCTION, Message::Set(), Message::SetDeliveryTime(), and Message::SetFunctionPointer().
Referenced by ShowTextMessage().
void MessageManager::DeleteAllMessages ()
Definition at line 345 of file MessageManager.cpp.
Referenced by ~MessageManager().
void MessageManager::DeleteMessagesByFunctionCallName (const string & name, eTimingSystem timing = GetTiming())
Definition at line 455 of file MessageManager.cpp.
References TIMER_SYSTEM.
void MessageManager::DeleteMessagesByType (eMessageType type, eTimingSystem timing = GetTiming())
Definition at line 543 of file MessageManager.cpp.
References TIMER_SYSTEM.
void MessageManager::DeleteMessagesToComponent (EntityComponent * pComponent)
Definition at line 476 of file MessageManager.cpp.
void MessageManager::DeleteMessagesToEntity (Entity * pComponent)
Definition at line 510 of file MessageManager.cpp.
void MessageManager::DumpMessages ()
Definition at line 211 of file MessageManager.cpp.
References LogMsg().
void MessageManager::RemoveComponentByName (Entity * pEnt, int timeMS, const string & compName, eTimingSystem timing = GetTiming())
Definition at line 434 of file MessageManager.cpp.
References MESSAGE_CLASS_ENTITY, MESSAGE_TYPE_REMOVE_COMPONENT, Message::SetDeliveryTime(), Message::SetTargetEntity(), and Message::SetVarName().
void MessageManager::SendGame (eMessageType type, const string msg, int deliverTimeMS = 0, eTimingSystem timing = TIMER_GAME)
Definition at line 68 of file MessageManager.cpp.
References MESSAGE_CLASS_GAME, Message::SetDeliveryTime(), and Message::SetVarName().
Referenced by AudioManagerAndroid::Play().
void MessageManager::SendGame (eMessageType type, const Variant & v, int deliverTimeMS = 0, eTimingSystem timing = TIMER_GAME)
Definition at line 76 of file MessageManager.cpp.
References MESSAGE_CLASS_GAME, Message::Set(), and Message::SetDeliveryTime().
void MessageManager::SendGUI (eMessageType type, float parm1, float parm2 = 0, int deliverTimeMS = 0, eTimingSystem timing = TIMER_SYSTEM)
Definition at line 83 of file MessageManager.cpp.
References MESSAGE_CLASS_GUI, Message::SetDeliveryTime(), Message::SetParm1(), Message::SetParm2(), Message::SetParm3(), and Message::SetParm4().
Referenced by AppOnAccelerometerUpdate(), AppOnJoypad(), AppOnJoypadButtons(), AppOnJoypadConnection(), AppOnKey(), AppOnTrackball(), AppOSMessageGet(), main(), Native_Update(), DPADButton::OnButtonChange(), and SDLEventLoop().
void MessageManager::SendGUI (eMessageType type, const Variant & v, int deliverTimeMS = 0)
Definition at line 125 of file MessageManager.cpp.
References MESSAGE_CLASS_GUI, Message::Set(), Message::SetDeliveryTime(), and TIMER_SYSTEM.
void MessageManager::SendGUI (eMessageType type, const VariantList & vList, int deliverTimeMS = 0)
Definition at line 133 of file MessageManager.cpp.
References MESSAGE_CLASS_GUI, Message::Set(), Message::SetDeliveryTime(), and TIMER_SYSTEM.
void MessageManager::SendGUIEx (eMessageType type, float parm1, float parm2, int finger, int deliverTimeMS = 0, eTimingSystem timing = TIMER_SYSTEM)
Definition at line 94 of file MessageManager.cpp.
References MESSAGE_CLASS_GUI, Message::SetDeliveryTime(), Message::SetParm1(), Message::SetParm2(), and Message::SetParm3().
Referenced by AppOnSendGUIEx(), AppOSMessageGet(), PassThroughPointerEventHandler::handlePointerDownEvent(), TouchDeviceEmulatorPointerEventHandler::handlePointerDownEvent(), PassThroughPointerEventHandler::handlePointerMoveEvent(), TouchDeviceEmulatorPointerEventHandler::handlePointerMoveEvent(), PassThroughPointerEventHandler::handlePointerUpEvent(), TouchDeviceEmulatorPointerEventHandler::handlePointerUpEvent(), Native_SendGUIEx(), and BaseApp::ResetTouches().
void MessageManager::SendGUIEx2 (eMessageType type, float parm1, float parm2, int finger, uint32 modifiers, int deliverTimeMS = 0, eTimingSystem timing = TIMER_SYSTEM)
Definition at line 104 of file MessageManager.cpp.
References MESSAGE_CLASS_GUI, Message::SetDeliveryTime(), Message::SetParm1(), Message::SetParm2(), Message::SetParm3(), and Message::SetParm4().
void MessageManager::SendGUIStringEx (eMessageType type, float parm1, float parm2, int finger, string s, int deliverTimeMS = 0, eTimingSystem timing = TIMER_SYSTEM)
Definition at line 114 of file MessageManager.cpp.
References MESSAGE_CLASS_GUI, Message::SetDeliveryTime(), Message::SetParm1(), Message::SetParm2(), Message::SetParm3(), and Message::SetStringParm().
Referenced by AppOnSendGUIStringEx(), and IAPManager::Update().
void MessageManager::SetComponentVariable (EntityComponent * pComp, int timeMS, const string & varName, const Variant & v, eTimingSystem timing = GetTiming())
Definition at line 372 of file MessageManager.cpp.
References MESSAGE_CLASS_ENTITY, MESSAGE_TYPE_SET_ENTITY_VARIANT, Message::Set(), Message::SetDeliveryTime(), Message::SetTargetComponent(), and Message::SetVarName().
Referenced by AnimateEntity(), AnimateStopEntity(), AnimateStopEntityAndSetFrame(), DisableComponentByName(), EnableAllButtonsEntity(), EnableComponentByName(), SetFilterSetting(), SetOverlayImageEntity(), SetupInterpolateComponent(), SpriteAnimationUtils::StartAnimationEntity(), and TypeTextLabelEntity().
void MessageManager::SetEntityVariable (Entity * pEnt, int timeMS, const string & varName, const Variant & v, eTimingSystem timing = GetTiming())
Definition at line 362 of file MessageManager.cpp.
References MESSAGE_CLASS_ENTITY, MESSAGE_TYPE_SET_ENTITY_VARIANT, Message::Set(), Message::SetDeliveryTime(), Message::SetTargetEntity(), and Message::SetVarName().
void MessageManager::Update ()
Definition at line 324 of file MessageManager.cpp.
References GetBaseApp(), BaseApp::GetGameTick(), and BaseApp::GetTick().
Referenced by BaseApp::Update().
The documentation for this class was generated from the following files:
MessageManager.h
MessageManager.cpp