Proton: FocusInputComponent Class Reference
FocusInputComponent Class Reference
A component that reacts to keyboard input and passes the events to a tree of Entities.
#include <FocusInputComponent.h>
Public Types
enum eMode { MODE_START_NORMAL, MODE_START_NONE }
Public Member Functions
FocusInputComponent ()
virtual ~FocusInputComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
void OnInput (VariantList *pVList)
void OnInputRaw (VariantList *pVList)
void LinkMoveMessages (VariantList *pVList)
Starts listening to the BaseApp::m_sig_input_move signal.
void LinkRawMessages (VariantList *pVList)
Starts listening to the BaseApp::m_sig_raw_keyboard signal.
Detailed Description
A component that reacts to keyboard input and passes the events to a tree of Entities.
The name of the component is initially set to "FocusInput".
This component connects to the BaseApp::m_sig_input signal and calls the "OnInput" function of the parent Entity recursively.
The following named variants are used inside the component itself:
"mode" (uint32): this holds a value from the eMode enum. If mode is MODE_START_NORMAL (the default) then the BaseApp::m_sig_input signal is automatically connected when this component is attached to an Entity. If mode is MODE_START_NONE then the signal is not connected.
FocusInputComponent can also listen to two other signals from BaseApp but neither of these are automatically connected.
BaseApp::m_sig_input_move signal can be connected by calling LinkMoveMessages(). This signal causes the "OnInput" function of the parent Entity to be called recursively.
BaseApp::m_sig_raw_keyboard signal can be connected by calling LinkRawMessages(). This signal causes the "OnRawInput" function of the parent Entity to be called recursively.
For all the functions of the parent Entity that this component calls the same parameters are passed that the original signal from BaseApp sends.
Definition at line 43 of file FocusInputComponent.h.
Member Enumeration Documentation
enum FocusInputComponent::eMode
Enumerator:
MODE_START_NORMAL
MODE_START_NONE
Definition at line 73 of file FocusInputComponent.h.
Constructor & Destructor Documentation
FocusInputComponent::FocusInputComponent ()
Definition at line 6 of file FocusInputComponent.cpp.
References EntityComponent::SetName().
FocusInputComponent::~FocusInputComponent () [virtual]
Definition at line 11 of file FocusInputComponent.cpp.
Member Function Documentation
void FocusInputComponent::LinkMoveMessages (VariantList * pVList)
Starts listening to the BaseApp::m_sig_input_move signal.
Only connects the signal if the input mode is INPUT_MODE_SEPARATE_MOVE_TOUCHES.
This method is also available through a function object called "LinkMoveMessages".
See also:
BaseApp::GetInputMode()
Definition at line 28 of file FocusInputComponent.cpp.
References GetBaseApp(), INPUT_MODE_SEPARATE_MOVE_TOUCHES, BaseApp::m_sig_input_move, and OnInput().
Referenced by OnAdd().
void FocusInputComponent::LinkRawMessages (VariantList * pVList)
Starts listening to the BaseApp::m_sig_raw_keyboard signal.
This method is also available through a function object called "LinkRawMessages".
Definition at line 36 of file FocusInputComponent.cpp.
References GetBaseApp(), BaseApp::m_sig_raw_keyboard, and OnInputRaw().
Referenced by OnAdd().
void FocusInputComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 15 of file FocusInputComponent.cpp.
References GetBaseApp(), EntityComponent::GetFunction(), EntityComponent::GetVar(), LinkMoveMessages(), LinkRawMessages(), BaseApp::m_sig_input, MODE_START_NORMAL, OnInput(), and FunctionObject::sig_function.
void FocusInputComponent::OnInput (VariantList * pVList)
Definition at line 46 of file FocusInputComponent.cpp.
References Entity::CallFunctionRecursivelyWithUpdatedVarBackwards(), EntityComponent::GetParent(), and Entity::RECURSIVE_VAR_OP_SUBTRACTION_PLUS_ALIGNMENT_OFFSET.
Referenced by LinkMoveMessages(), and OnAdd().
void FocusInputComponent::OnInputRaw (VariantList * pVList)
Definition at line 56 of file FocusInputComponent.cpp.
References Entity::CallFunctionRecursively(), and EntityComponent::GetParent().
Referenced by LinkRawMessages().
void FocusInputComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 41 of file FocusInputComponent.cpp.
The documentation for this class was generated from the following files:
FocusInputComponent.h
FocusInputComponent.cpp