Proton: FunctionObject Class Reference
FunctionObject Class Reference
#include <VariantDB.h>
Public Attributes
boost::signal< void(VariantList *) sig_function)
Detailed Description
Definition at line 19 of file VariantDB.h.
Member Data Documentation
boost::signal<void (VariantList*) FunctionObject::sig_function)
Definition at line 23 of file VariantDB.h.
Referenced by ActivateTextInputEntity(), AddFocusIfNeeded(), AddInputMovementFocusIfNeeded(), AddKeyBinding(), VariantDB::CallFunctionIfExists(), Entity::CallFunctionRecursivelyWithUpdatedVar(), Gamepad::ConnectToArcadeComponent(), CreateCheckbox(), CreateScrollingTextBoxEntity(), EnableRawMessageFocusInput(), IAPManager::IAPManager(), SelectButtonWithCustomInputComponent::OnAdd(), SliderComponent::OnAdd(), HTTPComponent::OnAdd(), ProgressBarComponent::OnAdd(), RenderClipComponent::OnAdd(), RenderScissorComponent::OnAdd(), FilterComponent::OnAdd(), FilterInputComponent::OnAdd(), TapSequenceDetectComponent::OnAdd(), TemplateComponent::OnAdd(), TextRenderComponent::OnAdd(), BlinkComponent::OnAdd(), UnpackArchiveComponent::OnAdd(), UnderlineRenderComponent::OnAdd(), InterpolateComponent::OnAdd(), RectRenderComponent::OnAdd(), TouchStripComponent::OnAdd(), TyperComponent::OnAdd(), TouchHandlerArcadeComponent::OnAdd(), EmitVirtualKeyComponentAdvanced::OnAdd(), EmitVirtualKeyComponent::OnAdd(), RandomAudioPlayerComponent::OnAdd(), TouchDragComponent::OnAdd(), TrailRenderComponent::OnAdd(), TextBoxRenderComponent::OnAdd(), DPadComponent::OnAdd(), ScrollBarRenderComponent::OnAdd(), LogDisplayComponent::OnAdd(), FocusInputComponent::OnAdd(), OverlayRenderComponent::OnAdd(), InputTextRenderComponent::OnAdd(), CustomInputComponent::OnAdd(), SpriteAnimationRenderComponent::OnAdd(), TouchHandlerComponent::OnAdd(), Button2DComponent::OnAdd(), SplashComponent::OnAdd(), ScrollComponent::OnAdd(), ArcadeInputComponent::OnAdd(), TouchDragComponent::OnInput(), EntityComponent::OnRemove(), OnShowTextMessage(), InterpolateComponent::OnVarNameChanged(), SetScrollProgressEntity(), Message::SetTargetComponent(), SetupAnimEntity(), SetupLightBarSelect(), and InputTextRenderComponent::~InputTextRenderComponent().
The documentation for this class was generated from the following file:
VariantDB.h