Proton: TyperComponent Class Reference
TyperComponent Class Reference
#include <TyperComponent.h>
Public Types
enum eMode { MODE_ONCE_AND_REMOVE_SELF, MODE_REPEAT }
Public Member Functions
TyperComponent ()
virtual ~TyperComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
void OnUpdate (VariantList *pVList)
Detailed Description
Definition at line 20 of file TyperComponent.h.
Member Enumeration Documentation
enum TyperComponent::eMode
Enumerator:
MODE_ONCE_AND_REMOVE_SELF
MODE_REPEAT
Definition at line 29 of file TyperComponent.h.
Constructor & Destructor Documentation
TyperComponent::TyperComponent ()
Definition at line 7 of file TyperComponent.cpp.
References EntityComponent::SetName().
TyperComponent::~TyperComponent () [virtual]
Definition at line 13 of file TyperComponent.cpp.
Member Function Documentation
void TyperComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 17 of file TyperComponent.cpp.
References GetBaseApp(), Entity::GetFunction(), EntityComponent::GetParent(), Variant::GetString(), BaseApp::GetTick(), Variant::GetUINT32(), EntityComponent::GetVarWithDefault(), MODE_REPEAT, OnUpdate(), and FunctionObject::sig_function.
void TyperComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 34 of file TyperComponent.cpp.
void TyperComponent::OnUpdate (VariantList * pVList)
Definition at line 60 of file TyperComponent.cpp.
References GetBaseApp(), Entity::GetComponentByName(), EntityComponent::GetParent(), Variant::GetString(), BaseApp::GetTick(), GetTick(), EntityComponent::GetVar(), LogMsg(), MODE_ONCE_AND_REMOVE_SELF, MODE_REPEAT, Entity::RemoveComponentByAddress(), and Variant::Set().
Referenced by OnAdd().
The documentation for this class was generated from the following files:
TyperComponent.h
TyperComponent.cpp