Proton: NetSocket Class Reference
NetSocket Class Reference
#include <NetSocket.h>
Public Member Functions
NetSocket ()
virtual ~NetSocket ()
bool Init (std::string url, int port)
bool InitHost (int port, int connections)
void Update ()
void Write (char *pBuff, int len)
void Write (const std::string &msg)
int GetSocket ()
std::vector< char > & GetBuffer ()
int GetIdleTimeMS ()
void Kill ()
void SetSocket (int socket)
bool WasDisconnected ()
std::string GetClientIPAsString ()
Protected Member Functions
void UpdateRead ()
void UpdateWrite ()
Protected Attributes
int m_socket
std::vector< char > m_readBuffer
std::vector< char > m_writeBuffer
unsigned int m_idleTimer
bool m_bWasDisconnected
Detailed Description
Definition at line 17 of file NetSocket.h.
Constructor & Destructor Documentation
NetSocket::NetSocket ()
Definition at line 54 of file NetSocket.cpp.
References m_bWasDisconnected, and m_socket.
NetSocket::~NetSocket () [virtual]
Definition at line 60 of file NetSocket.cpp.
References Kill().
Member Function Documentation
std::vector<char>& NetSocket::GetBuffer () [inline]
Definition at line 28 of file NetSocket.h.
References m_readBuffer.
Referenced by NetHTTP::Update().
string NetSocket::GetClientIPAsString ()
Definition at line 215 of file NetSocket.cpp.
References m_socket.
int NetSocket::GetIdleTimeMS ()
Definition at line 328 of file NetSocket.cpp.
References GetSystemTimeTick(), and m_idleTimer.
Referenced by NetHTTP::Update().
int NetSocket::GetSocket () [inline]
Definition at line 27 of file NetSocket.h.
References m_socket.
bool NetSocket::Init (std::string url, int port)
Definition at line 84 of file NetSocket.cpp.
References GetSystemTimeTick(), Kill(), m_idleTimer, and m_socket.
Referenced by NetHTTP::Start().
bool NetSocket::InitHost (int port, int connections)
Definition at line 137 of file NetSocket.cpp.
References Kill(), LogError(), LogMsg(), and m_socket.
void NetSocket::Kill ()
Definition at line 67 of file NetSocket.cpp.
References m_bWasDisconnected, m_readBuffer, m_socket, and m_writeBuffer.
Referenced by Init(), InitHost(), SetSocket(), and ~NetSocket().
void NetSocket::SetSocket (int socket)
Definition at line 204 of file NetSocket.cpp.
References GetSystemTimeTick(), Kill(), m_idleTimer, and m_socket.
void NetSocket::Update ()
Definition at line 236 of file NetSocket.cpp.
References UpdateRead(), and UpdateWrite().
Referenced by NetHTTP::Update().
void NetSocket::UpdateRead () [protected]
Definition at line 242 of file NetSocket.cpp.
References GetSystemTimeTick(), LogMsg(), m_bWasDisconnected, m_idleTimer, m_readBuffer, and m_socket.
Referenced by Update().
void NetSocket::UpdateWrite () [protected]
Definition at line 290 of file NetSocket.cpp.
References GetSystemTimeTick(), m_idleTimer, m_socket, and m_writeBuffer.
Referenced by Update(), and Write().
bool NetSocket::WasDisconnected () [inline]
Definition at line 32 of file NetSocket.h.
References m_bWasDisconnected.
void NetSocket::Write (char * pBuff, int len)
Definition at line 317 of file NetSocket.cpp.
References m_writeBuffer, and UpdateWrite().
Referenced by NetHTTP::Start().
void NetSocket::Write (const std::string & msg)
Member Data Documentation
bool NetSocket::m_bWasDisconnected [protected]
Definition at line 44 of file NetSocket.h.
Referenced by Kill(), NetSocket(), UpdateRead(), and WasDisconnected().
unsigned int NetSocket::m_idleTimer [protected]
Definition at line 43 of file NetSocket.h.
Referenced by GetIdleTimeMS(), Init(), SetSocket(), UpdateRead(), and UpdateWrite().
std::vector<char> NetSocket::m_readBuffer [protected]
Definition at line 41 of file NetSocket.h.
Referenced by GetBuffer(), Kill(), and UpdateRead().
int NetSocket::m_socket [protected]
Definition at line 39 of file NetSocket.h.
Referenced by GetClientIPAsString(), GetSocket(), Init(), InitHost(), Kill(), NetSocket(), SetSocket(), UpdateRead(), and UpdateWrite().
std::vector<char> NetSocket::m_writeBuffer [protected]
Definition at line 42 of file NetSocket.h.
Referenced by Kill(), UpdateWrite(), and Write().
The documentation for this class was generated from the following files:
NetSocket.h
NetSocket.cpp