Proton: TouchHandlerComponent Class Reference
TouchHandlerComponent Class Reference
A component that adds touch event handling behaviour to an Entity.
#include <TouchHandlerComponent.h>
Public Member Functions
TouchHandlerComponent ()
virtual ~TouchHandlerComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
void OnInput (VariantList *pVList)
Detailed Description
A component that adds touch event handling behaviour to an Entity.
The name of the component is initially set to "TouchHandler".
This component is useful if you want to handle touch input events within a given rectangular area. The area is determined by the position and size of the parent Entity.
The following named variants are used from the parent Entity:
"pos2d" (Vector2), "size2d" (Vector2): used to determine the touch area.
"touchPadding" (Rect): padding area for the touch area. This can be used to make the touch area larger than the area of the parent Entity. The default is (left: 20, top: 5, right: 20, bottom: 15).
"ignoreTouchesOutsideRect" (uint32): defines if move events should be ignored when the touch position has moved outside the touch area. 0 (the default) means that move events outside the touch area are not ignored (i.e. they are handled). Any other value means that they are ignored. If this feature is enabled it basically means that the "OnOverEnd" function doesn't get called. As a side effect the "touchOver" variant also gets out of sync so the usability of this feature is questionable.
"touchOver" (uint32): this value keeps track if the touch position is currently inside the area or not. You can read this value but don't write it!
When events happen the following functions of the parent Entity get called:
OnTouchStart - a pointer was pressed inside the area.
OnOverStart - a pressed pointer has entered the area. This can occur when a pointer is pressed down inside the area (i.e. right after "OnTouchStart") or when an already pressed pointer is moved inside the area.
OnOverMove - a pressed pointer moves within the area.
OnOverEnd - a pressed pointer is moved outside the area or the pointer is released.
OnTouchEnd - a pointer was released inside the area.
When these functions get called they get a VariantList that contains four members:
0: the touch point of type CL_Vec2f
1: a pointer to the Entity that was touched
2: the id of the finger, type is uint32
3: a uint32 telling if the touch point (passed in member 0) is within the touch area. 1 means it's inside the area, 0 means it's outside.
Definition at line 55 of file TouchHandlerComponent.h.
Constructor & Destructor Documentation
TouchHandlerComponent::TouchHandlerComponent ()
Definition at line 8 of file TouchHandlerComponent.cpp.
References EntityComponent::SetName().
TouchHandlerComponent::~TouchHandlerComponent () [virtual]
Definition at line 13 of file TouchHandlerComponent.cpp.
Member Function Documentation
void TouchHandlerComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 17 of file TouchHandlerComponent.cpp.
References Entity::GetFunction(), EntityComponent::GetParent(), Variant::GetRect(), Variant::GetSigOnChanged, Variant::GetUINT32(), Entity::GetVar(), Entity::GetVarWithDefault(), Variant::GetVector2(), OnInput(), and FunctionObject::sig_function.
void TouchHandlerComponent::OnInput (VariantList * pVList)
Definition at line 140 of file TouchHandlerComponent.cpp.
References VariantList::Get(), Variant::GetFloat(), Variant::GetType(), Variant::GetUINT32(), Variant::GetVector2(), MESSAGE_TYPE_GUI_CLICK_END, MESSAGE_TYPE_GUI_CLICK_MOVE, MESSAGE_TYPE_GUI_CLICK_START, and Variant::TYPE_UINT32.
Referenced by OnAdd().
void TouchHandlerComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 39 of file TouchHandlerComponent.cpp.
The documentation for this class was generated from the following files:
TouchHandlerComponent.h
TouchHandlerComponent.cpp