Proton: FilterComponent Class Reference
FilterComponent Class Reference
#include <FilterComponent.h>
Public Member Functions
FilterComponent ()
virtual ~FilterComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
void FilterOnInput (VariantList *pVList)
Detailed Description
Definition at line 17 of file FilterComponent.h.
Constructor & Destructor Documentation
FilterComponent::FilterComponent ()
Definition at line 6 of file FilterComponent.cpp.
References EntityComponent::SetName().
FilterComponent::~FilterComponent () [virtual]
Definition at line 11 of file FilterComponent.cpp.
Member Function Documentation
void FilterComponent::FilterOnInput (VariantList * pVList)
Definition at line 41 of file FilterComponent.cpp.
References Entity::FILTER_INDEX, Entity::FILTER_REFUSE_ALL, Variant::GetUINT32(), VariantList::m_variant, and Variant::Set().
Referenced by OnAdd().
void FilterComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 15 of file FilterComponent.cpp.
References Entity::FILTER_ALLOW, FilterOnInput(), Entity::GetFunction(), EntityComponent::GetParent(), Variant::GetString(), Variant::GetUINT32(), EntityComponent::GetVar(), EntityComponent::GetVarWithDefault(), Entity::OnFilterAdd(), EntityComponent::SetName(), and FunctionObject::sig_function.
void FilterComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 35 of file FilterComponent.cpp.
References EntityComponent::GetParent(), and Entity::OnFilterRemove().
The documentation for this class was generated from the following files:
FilterComponent.h
FilterComponent.cpp