Proton: SplashComponent Class Reference
SplashComponent Class Reference
#include <SplashComponent.h>
Public Member Functions
SplashComponent ()
virtual ~SplashComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
void AddSplash (string fileName, int timeOutMS=300, bool bScaleToFitScreen=true, bool bPerserveAspectRatio=false, unsigned int bgColor=MAKE_RGBA(0, 0, 0, 255))
Public Attributes
boost::signal< void(VariantList *) m_sig_on_splash_change)
Detailed Description
Definition at line 63 of file SplashComponent.h.
Constructor & Destructor Documentation
SplashComponent::SplashComponent ()
Definition at line 6 of file SplashComponent.cpp.
References EntityComponent::SetName().
SplashComponent::~SplashComponent () [virtual]
Definition at line 11 of file SplashComponent.cpp.
Member Function Documentation
void SplashComponent::AddSplash (string fileName, int timeOutMS = 300, bool bScaleToFitScreen = true, bool bPerserveAspectRatio = false, unsigned int bgColor = MAKE_RGBA(0,0,0,255))
Definition at line 76 of file SplashComponent.cpp.
References SplashScreenItem::m_bgColor, SplashScreenItem::m_bPerserveAspectRatio, SplashScreenItem::m_bScaleToFitScreen, SplashScreenItem::m_fileName, and SplashScreenItem::m_timeOutMS.
void SplashComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 43 of file SplashComponent.cpp.
References Entity::GetFunction(), EntityComponent::GetParent(), Entity::GetVar(), Variant::GetVector2(), and FunctionObject::sig_function.
void SplashComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 65 of file SplashComponent.cpp.
Member Data Documentation
boost::signal<void (VariantList*) SplashComponent::m_sig_on_splash_change)
Definition at line 74 of file SplashComponent.h.
The documentation for this class was generated from the following files:
SplashComponent.h
SplashComponent.cpp