Proton: GamepadProviderMoga Class Reference
GamepadProviderMoga Class Reference
#include <GamepadProviderMoga.h>
Public Member Functions
GamepadProviderMoga ()
virtual ~GamepadProviderMoga ()
virtual string GetName ()
virtual bool Init ()
virtual void Kill ()
virtual void Update ()
Detailed Description
Definition at line 23 of file GamepadProviderMoga.h.
Constructor & Destructor Documentation
GamepadProviderMoga::GamepadProviderMoga ()
Definition at line 7 of file GamepadProviderMoga.cpp.
References Kill().
GamepadProviderMoga::~GamepadProviderMoga () [virtual]
Definition at line 12 of file GamepadProviderMoga.cpp.
Member Function Documentation
virtual string GamepadProviderMoga::GetName () [inline, virtual]
Implements GamepadProvider.
Definition at line 29 of file GamepadProviderMoga.h.
bool GamepadProviderMoga::Init () [virtual]
Implements GamepadProvider.
Definition at line 16 of file GamepadProviderMoga.cpp.
References GamepadManager::AddGamepad(), GetGamepadManager(), LogMsg(), and GamepadMoga::SetProvider().
void GamepadProviderMoga::Kill () [virtual]
Implements GamepadProvider.
Definition at line 25 of file GamepadProviderMoga.cpp.
Referenced by GamepadProviderMoga().
void GamepadProviderMoga::Update () [virtual]
Implements GamepadProvider.
Definition at line 29 of file GamepadProviderMoga.cpp.
The documentation for this class was generated from the following files:
GamepadProviderMoga.h
GamepadProviderMoga.cpp