Proton: TouchTrackInfo Class Reference
TouchTrackInfo Class Reference
#include <BaseApp.h>
Public Member Functions
TouchTrackInfo ()
bool WasHandled ()
CL_Vec2f GetPos ()
CL_Vec2f GetLastPos ()
bool WasPreHandled ()
Entity * GetEntityThatPreHandledIt ()
void SetWasPreHandled (bool bNew, Entity *pEntity=NULL)
bool IsDown ()
Entity * GetEntityThatHandledIt ()
void SetIsDown (bool bNew)
void SetPos (const CL_Vec2f &vPos)
void SetWasHandled (bool bNew, Entity *pEntity=NULL)
Detailed Description
Definition at line 147 of file BaseApp.h.
Constructor & Destructor Documentation
TouchTrackInfo::TouchTrackInfo () [inline]
Definition at line 151 of file BaseApp.h.
Member Function Documentation
Entity* TouchTrackInfo::GetEntityThatHandledIt () [inline]
Definition at line 170 of file BaseApp.h.
Referenced by TouchHandlerArcadeComponent::OnInput().
Entity* TouchTrackInfo::GetEntityThatPreHandledIt () [inline]
Definition at line 166 of file BaseApp.h.
CL_Vec2f TouchTrackInfo::GetLastPos () [inline]
Definition at line 163 of file BaseApp.h.
CL_Vec2f TouchTrackInfo::GetPos () [inline]
Definition at line 162 of file BaseApp.h.
Referenced by TouchDragComponent::ResetLastPos().
bool TouchTrackInfo::IsDown () [inline]
Definition at line 169 of file BaseApp.h.
void TouchTrackInfo::SetIsDown (bool bNew) [inline]
Definition at line 171 of file BaseApp.h.
Referenced by SendFakeInputMessageToEntity().
void TouchTrackInfo::SetPos (const CL_Vec2f & vPos) [inline]
Definition at line 172 of file BaseApp.h.
Referenced by SendFakeInputMessageToEntity().
void TouchTrackInfo::SetWasHandled (bool bNew, Entity * pEntity = NULL)
Definition at line 705 of file BaseApp.cpp.
Referenced by TouchDragComponent::OnInput(), SendFakeInputMessageToEntity(), ScrollComponent::~ScrollComponent(), TouchDragComponent::~TouchDragComponent(), and TouchStripComponent::~TouchStripComponent().
void TouchTrackInfo::SetWasPreHandled (bool bNew, Entity * pEntity = NULL)
Definition at line 711 of file BaseApp.cpp.
bool TouchTrackInfo::WasHandled () [inline]
Definition at line 161 of file BaseApp.h.
Referenced by TouchHandlerArcadeComponent::OnInput(), and TouchDragComponent::OnInput().
bool TouchTrackInfo::WasPreHandled () [inline]
Definition at line 165 of file BaseApp.h.
Referenced by TouchHandlerArcadeComponent::OnInput().
The documentation for this class was generated from the following files:
BaseApp.h
BaseApp.cpp