Proton: PModifierKeys Class Reference
PModifierKeys Class Reference
#include <PPlotInteraction.h>
Public Types
enum { kShift = 1, kControl = 2, kAlt = 4 }
Public Member Functions
PModifierKeys (int inModifierKeys=0)
bool IsShiftKeyDown () const
bool IsControlKeyDown () const
bool IsAltKeyDown () const
bool IsOnlyShiftKeyDown () const
bool IsOnlyControlKeyDown () const
bool IsOnlyAltKeyDown () const
bool HasModifierKeys () const
void SetModifierKeys (int inModifierKeys)
Detailed Description
Definition at line 24 of file PPlotInteraction.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
kShift
kControl
kAlt
Definition at line 26 of file PPlotInteraction.h.
Constructor & Destructor Documentation
PModifierKeys::PModifierKeys (int inModifierKeys = 0) [inline]
Definition at line 31 of file PPlotInteraction.h.
Member Function Documentation
bool PModifierKeys::HasModifierKeys () const [inline]
Definition at line 41 of file PPlotInteraction.h.
Referenced by PZoomInteraction::HandleMouseEvent().
bool PModifierKeys::IsAltKeyDown () const [inline]
Definition at line 36 of file PPlotInteraction.h.
References kAlt.
bool PModifierKeys::IsControlKeyDown () const [inline]
Definition at line 35 of file PPlotInteraction.h.
References kControl.
Referenced by PCrosshairInteraction::HandleMouseEvent().
bool PModifierKeys::IsOnlyAltKeyDown () const [inline]
Definition at line 39 of file PPlotInteraction.h.
References kAlt.
bool PModifierKeys::IsOnlyControlKeyDown () const [inline]
Definition at line 38 of file PPlotInteraction.h.
References kControl.
Referenced by PZoomInteraction::HandleKeyEvent(), PSelectionInteraction::HandleKeyEvent(), PSelectionInteraction::HandleMouseEvent(), and PVerticalCursorInteraction::HandleVerticalCursorKey().
bool PModifierKeys::IsOnlyShiftKeyDown () const [inline]
Definition at line 37 of file PPlotInteraction.h.
References kShift.
Referenced by PSelectionInteraction::HandleMouseEvent().
bool PModifierKeys::IsShiftKeyDown () const [inline]
Definition at line 34 of file PPlotInteraction.h.
References kShift.
Referenced by PCrosshairInteraction::HandleMouseEvent().
void PModifierKeys::SetModifierKeys (int inModifierKeys) [inline]
Definition at line 43 of file PPlotInteraction.h.
The documentation for this class was generated from the following file:
PPlotInteraction.h