Proton: PlotDataContainer Class Reference
PlotDataContainer Class Reference
#include <pplot.h>
Public Member Functions
PlotDataContainer ()
~PlotDataContainer ()
void RemoveElement (int inIndex)
void ClearData ()
void AddXYPlot (PlotDataBase *inXData, PlotDataBase *inYData, LegendData *inLegendData=0, DataDrawerBase *inDataDrawer=0, PlotDataSelection *inPlotDataSelection=0)
void SetXYPlot (int inIndex, PlotDataBase *inXData, PlotDataBase *inYData, LegendData *inLegendData=0, DataDrawerBase *inDataDrawer=0, PlotDataSelection *inPlotDataSelection=0)
int GetPlotCount () const
PlotDataBase * GetXData (int inIndex)
PlotDataBase * GetYData (int inIndex)
LegendData * GetLegendData (int inIndex)
DataDrawerBase * GetDataDrawer (int inIndex)
PlotDataSelection * GetPlotDataSelection (int inIndex)
bool SetDataDrawer (int inIndex, DataDrawerBase *inDataDrawer)
int GetPlotIndexByName (const string &inName) const
const PlotDataBase * GetConstXData (int inIndex) const
const PlotDataBase * GetConstYData (int inIndex) const
const LegendData * GetConstLegendData (int inIndex) const
const DataDrawerBase * GetConstDataDrawer (int inIndex) const
const PlotDataSelection * GetConstPlotDataSelection (int inIndex) const
bool CalculateXRange (float &outXMin, float &outXMax) const
bool CalculateYRange (float inXMin, float inXMax, float &outYMin, float &outYMax) const
bool CalculateYRangePlot (float inXMin, float inXMax, const PlotDataBase &inXData, const PlotDataBase &inYData, float &outYMin, float &outYMax) const
Protected Member Functions
bool CheckState () const
Protected Attributes
PlotDataList mXDataList
PlotDataList mYDataList
LegendDataList mLegendDataList
DataDrawerList mDataDrawerList
PlotDataSelectionList mPlotDataSelectionList
Detailed Description
Definition at line 265 of file pplot.h.
Constructor & Destructor Documentation
PlotDataContainer::PlotDataContainer ()
Definition at line 278 of file PPlot.cpp.
PlotDataContainer::~PlotDataContainer ()
Definition at line 280 of file PPlot.cpp.
Member Function Documentation
void PlotDataContainer::AddXYPlot (PlotDataBase * inXData, PlotDataBase * inYData, LegendData * inLegendData = 0, DataDrawerBase * inDataDrawer = 0, PlotDataSelection * inPlotDataSelection = 0)
Definition at line 413 of file PPlot.cpp.
References PlotDataBase::GetCalculatedData(), PlotDataBase::GetRealPlotData(), PlotDataBase::GetSize(), and LegendData::SetDefaultValues().
Referenced by MakeCopy(), MakeExamplePlot1(), MakeExamplePlot2(), MakeExamplePlot3(), MakeExamplePlot4(), MakeExamplePlot5(), MakeExamplePlot6(), MakeExamplePlot7(), and MakeExamplePlot8().
bool PlotDataContainer::CalculateXRange (float & outXMin, float & outXMax) const
Definition at line 532 of file PPlot.cpp.
References PlotDataBase::CalculateRange(), and PlotDataBase::GetSize().
Referenced by PPlot::CalculateAxisRanges().
bool PlotDataContainer::CalculateYRange (float inXMin, float inXMax, float & outYMin, float & outYMax) const
Definition at line 570 of file PPlot.cpp.
Referenced by PPlot::CalculateAxisRanges().
bool PlotDataContainer::CalculateYRangePlot (float inXMin, float inXMax, const PlotDataBase & inXData, const PlotDataBase & inYData, float & outYMin, float & outYMax) const
Definition at line 602 of file PPlot.cpp.
References PlotDataBase::GetSize(), and PlotDataBase::GetValue().
bool PlotDataContainer::CheckState () const [protected]
Definition at line 634 of file PPlot.cpp.
void PlotDataContainer::ClearData ()
Definition at line 380 of file PPlot.cpp.
const DataDrawerBase * PlotDataContainer::GetConstDataDrawer (int inIndex) const
Definition at line 340 of file PPlot.cpp.
Referenced by PPlot::DrawPlot(), and MakeCopy().
const LegendData * PlotDataContainer::GetConstLegendData (int inIndex) const
Definition at line 333 of file PPlot.cpp.
Referenced by PPlot::DrawLegend(), PPlot::DrawPlot(), and MakeCopy().
const PlotDataSelection * PlotDataContainer::GetConstPlotDataSelection (int inIndex) const
Definition at line 347 of file PPlot.cpp.
Referenced by PPlot::DrawPlot().
const PlotDataBase * PlotDataContainer::GetConstXData (int inIndex) const
Definition at line 319 of file PPlot.cpp.
Referenced by PPlot::ConfigureSelf(), PPlot::DrawPlot(), MakeCopy(), and PPlot::ValidateData().
const PlotDataBase * PlotDataContainer::GetConstYData (int inIndex) const
Definition at line 326 of file PPlot.cpp.
Referenced by PPlot::DrawPlot(), and MakeCopy().
DataDrawerBase * PlotDataContainer::GetDataDrawer (int inIndex)
Definition at line 305 of file PPlot.cpp.
Referenced by PSelectionInteraction::Calculate(), PPlot::ConfigureSelf(), PVerticalCursorInteraction::Impl_Calculate(), and PDeleteInteraction::Impl_Calculate().
LegendData * PlotDataContainer::GetLegendData (int inIndex)
Definition at line 298 of file PPlot.cpp.
Referenced by PCrosshairInteraction::Draw(), and MakeExamplePlot1().
int PlotDataContainer::GetPlotCount () const [inline]
Definition at line 276 of file pplot.h.
References mYDataList.
Referenced by PSelectionInteraction::Calculate(), PPlot::ConfigureSelf(), PCrosshairInteraction::Draw(), PPlot::Draw(), PPlot::DrawLegend(), PPlot::DrawPlot(), PVerticalCursorInteraction::Impl_Calculate(), PDeleteInteraction::Impl_Calculate(), MakeCopy(), and PPlot::ValidateData().
PlotDataSelection * PlotDataContainer::GetPlotDataSelection (int inIndex)
Definition at line 312 of file PPlot.cpp.
Referenced by PSelectionInteraction::Calculate(), PVerticalCursorInteraction::Impl_Calculate(), and PDeleteInteraction::Impl_Calculate().
int PlotDataContainer::GetPlotIndexByName (const string & inName) const
Definition at line 518 of file PPlot.cpp.
References LegendData::mName.
PlotDataBase * PlotDataContainer::GetXData (int inIndex)
Definition at line 284 of file PPlot.cpp.
Referenced by PSelectionInteraction::Calculate(), PCrosshairInteraction::Draw(), PVerticalCursorInteraction::Impl_Calculate(), and PDeleteInteraction::Impl_Calculate().
PlotDataBase * PlotDataContainer::GetYData (int inIndex)
Definition at line 291 of file PPlot.cpp.
Referenced by PSelectionInteraction::Calculate(), PCrosshairInteraction::Draw(), PVerticalCursorInteraction::Impl_Calculate(), and PDeleteInteraction::Impl_Calculate().
void PlotDataContainer::RemoveElement (int inIndex)
Definition at line 354 of file PPlot.cpp.
bool PlotDataContainer::SetDataDrawer (int inIndex, DataDrawerBase * inDataDrawer)
Definition at line 505 of file PPlot.cpp.
void PlotDataContainer::SetXYPlot (int inIndex, PlotDataBase * inXData, PlotDataBase * inYData, LegendData * inLegendData = 0, DataDrawerBase * inDataDrawer = 0, PlotDataSelection * inPlotDataSelection = 0)
Definition at line 449 of file PPlot.cpp.
References PlotDataBase::GetRealPlotData(), PlotDataBase::GetSize(), and LegendData::SetDefaultValues().
Member Data Documentation
DataDrawerList PlotDataContainer::mDataDrawerList [protected]
Definition at line 302 of file pplot.h.
LegendDataList PlotDataContainer::mLegendDataList [protected]
Definition at line 301 of file pplot.h.
PlotDataSelectionList PlotDataContainer::mPlotDataSelectionList [protected]
Definition at line 303 of file pplot.h.
PlotDataList PlotDataContainer::mXDataList [protected]
Definition at line 299 of file pplot.h.
PlotDataList PlotDataContainer::mYDataList [protected]
Definition at line 300 of file pplot.h.
Referenced by GetPlotCount().
The documentation for this class was generated from the following files:
pplot.h
PPlot.cpp