Proton: RTFont Class Reference
RTFont Class Reference
#include <RTFont.h>
Public Member Functions
RTFont ()
RTFont (string fileName)
virtual ~RTFont ()
void Draw (float x, float y, string text, unsigned int color=MAKE_RGBA(255, 255, 255, 255))
bool Load (string fileName)
void MeasureText (rtRectf *pRectOut, const string &text, float scale=1.0f)
void MeasureText (rtRectf *pRectOut, const char *pText, int len, float scale)
CL_Vec2f MeasureText (const string &text, float scale=1.0f)
void MeasureTextAndAddByLinesIntoDeque (const CL_Vec2f &textBounds, const string &text, deque< string > *pLines, float scale, CL_Vec2f &vEnclosingSizeOut)
int CountCharsThatFitX (float sizeX, const string &text, float scale=1.0f)
void DrawScaled (float x, float y, const string &text, float scale=1.0f, unsigned int color=MAKE_RGBA(255, 255, 255, 255), FontStateStack *pState=NULL, RenderBatcher *pBatcher=NULL)
void DrawScaledSolidColor (float x, float y, const string &text, float scale=1.0f, unsigned int color=MAKE_RGBA(255, 255, 255, 255), FontStateStack *pState=NULL, RenderBatcher *pBatcher=NULL)
CL_Vec2f DrawWrapped (rtRect &r, const string &txt, bool centerX=false, bool centerY=false, unsigned int color=MAKE_RGBA(255, 255, 255, 255), float scale=1.0f, bool bMeasureOnly=false, uint32 bgColor=MAKE_RGBA(0, 0, 0, 0))
void DrawAligned (float x, float y, const string &text, eAlignment alignment=ALIGNMENT_UPPER_LEFT, float scale=1.0f, unsigned int color=MAKE_RGBA(255, 255, 255, 255), FontStateStack *pState=NULL, RenderBatcher *pBatcher=NULL)
void DrawAlignedSolidColor (float x, float y, const string &text, eAlignment alignment=ALIGNMENT_UPPER_LEFT, float scale=1.0f, unsigned int color=MAKE_RGBA(255, 255, 255, 255), FontStateStack *pState=NULL, RenderBatcher *pBatcher=NULL)
void SetSmoothing (bool bSmoothing)
float GetLineHeight (float scale=1.0f)
void DrawScaledFakeToUpdateState (const string &text, unsigned int color, FontStateStack *pState)
bool IsLoaded ()
unsigned int GetColorFromString (const char *pText)
Surface * GetSurface ()
Detailed Description
Definition at line 18 of file RTFont.h.
Constructor & Destructor Documentation
RTFont::RTFont ()
Definition at line 6 of file RTFont.cpp.
RTFont::RTFont (string fileName)
Definition at line 17 of file RTFont.cpp.
References Load().
RTFont::~RTFont () [virtual]
Definition at line 23 of file RTFont.cpp.
Member Function Documentation
int RTFont::CountCharsThatFitX (float sizeX, const string & text, float scale = 1.0f)
Definition at line 855 of file RTFont.cpp.
References rtfont_header::blankCharWidth, rtfont_charData::charSizeX, rtfont_header::firstChar, LogMsg(), and rtfont_charData::xadvance.
void RTFont::Draw (float x, float y, string text, unsigned int color = MAKE_RGBA(255,255,255,255))
Definition at line 138 of file RTFont.cpp.
References DrawScaled().
Referenced by IrrlichtManager::Render2D().
void RTFont::DrawAligned (float x, float y, const string & text, eAlignment alignment = ALIGNMENT_UPPER_LEFT, float scale = 1.0f, unsigned int color = MAKE_RGBA(255,255,255,255), FontStateStack * pState = NULL, RenderBatcher * pBatcher = NULL)
Definition at line 543 of file RTFont.cpp.
References ALIGNMENT_UPPER_LEFT, DrawScaled(), GetAlignmentOffset(), and MeasureText().
void RTFont::DrawAlignedSolidColor (float x, float y, const string & text, eAlignment alignment = ALIGNMENT_UPPER_LEFT, float scale = 1.0f, unsigned int color = MAKE_RGBA(255,255,255,255), FontStateStack * pState = NULL, RenderBatcher * pBatcher = NULL)
Definition at line 557 of file RTFont.cpp.
References ALIGNMENT_UPPER_LEFT, DrawScaledSolidColor(), GetAlignmentOffset(), and MeasureText().
void RTFont::DrawScaled (float x, float y, const string & text, float scale = 1.0f, unsigned int color = MAKE_RGBA(255,255,255,255), FontStateStack * pState = NULL, RenderBatcher * pBatcher = NULL)
Definition at line 266 of file RTFont.cpp.
References ALIGNMENT_UPPER_LEFT, rtfont_header::blankCharWidth, RenderBatcher::BlitEx(), rtfont_charData::bmpPosX, rtfont_charData::bmpPosY, rtRectf::bottom, rtfont_charData::charBmpOffsetX, rtfont_charData::charBmpOffsetY, rtfont_charData::charSizeX, rtfont_charData::charSizeY, rtfont_header::firstChar, RenderBatcher::Flush(), g_globalBatcher, GetLineHeight(), Surface::IsLoaded(), rtRectf::left, rtRectf::right, rtRectf::Scale(), SetupOrtho(), rtRectf::top, and rtfont_charData::xadvance.
Referenced by Draw(), BaseApp::Draw(), DrawAligned(), ProtonPainter::DrawText(), and DrawWrapped().
void RTFont::DrawScaledFakeToUpdateState (const string & text, unsigned int color, FontStateStack * pState)
Definition at line 787 of file RTFont.cpp.
void RTFont::DrawScaledSolidColor (float x, float y, const string & text, float scale = 1.0f, unsigned int color = MAKE_RGBA(255,255,255,255), FontStateStack * pState = NULL, RenderBatcher * pBatcher = NULL)
Definition at line 409 of file RTFont.cpp.
References ALIGNMENT_UPPER_LEFT, rtfont_header::blankCharWidth, RenderBatcher::BlitEx(), rtfont_charData::bmpPosX, rtfont_charData::bmpPosY, rtRectf::bottom, rtfont_charData::charBmpOffsetX, rtfont_charData::charBmpOffsetY, rtfont_charData::charSizeX, rtfont_charData::charSizeY, rtfont_header::firstChar, RenderBatcher::Flush(), g_globalBatcher, GetLineHeight(), Surface::IsLoaded(), rtRectf::left, rtRectf::right, rtRectf::Scale(), SetupOrtho(), rtRectf::top, and rtfont_charData::xadvance.
Referenced by DrawAlignedSolidColor().
CL_Vec2f RTFont::DrawWrapped (rtRect & r, const string & txt, bool centerX = false, bool centerY = false, unsigned int color = MAKE_RGBA(255,255,255,255), float scale = 1.0f, bool bMeasureOnly = false, uint32 bgColor = MAKE_RGBA(0,0,0,0))
Definition at line 723 of file RTFont.cpp.
References DrawFilledRect(), DrawScaled(), g_globalBatcher, rtRect::GetHeight(), GetLineHeight(), rtRect::GetWidth(), rtRect::left, MeasureText(), MeasureTextAndAddByLinesIntoDeque(), rtRectf::right, and rtRect::top.
unsigned int RTFont::GetColorFromString (const char * pText)
Definition at line 831 of file RTFont.cpp.
References LogError().
float RTFont::GetLineHeight (float scale = 1.0f)
Definition at line 717 of file RTFont.cpp.
References rtfont_header::lineHeight.
Referenced by CreateInputTextEntity(), CreateSlider(), DrawScaled(), DrawScaledSolidColor(), DrawWrapped(), EnforceMinimumFontLineToScreenRatio(), GetFontAndScaleToFitThisLinesPerScreenY(), GetFontAndScaleToFitThisPixelHeight(), GetFontAndScaleToFitThisStringInWidthPixels(), ProtonPainter::GetFontHeight(), MeasureText(), and MeasureTextAndAddByLinesIntoDeque().
Surface* RTFont::GetSurface () [inline]
Definition at line 44 of file RTFont.h.
bool RTFont::IsLoaded () [inline]
Definition at line 41 of file RTFont.h.
References Surface::IsLoaded().
Referenced by MeasureText().
bool RTFont::Load (string fileName)
Definition at line 60 of file RTFont.cpp.
References KerningPair::amount, FontChar::data, RTFileHeader::fileTypeID, KerningPair::first, rtfont_header::firstChar, rtfont_header::fontStateCount, FileInstance::GetAsBytes(), GetBaseApp(), FileInstance::IsLoaded(), rtfont_header::kerningPairCount, rtfont_header::lastChar, Surface::LoadFileFromMemory(), LogError(), LogMsg(), BaseApp::m_sig_loadSurfaces, BaseApp::m_sig_unloadSurfaces, rtfont_header::rtFileHeader, KerningPair::second, Surface::SetTextureType(), and Surface::TYPE_GUI.
Referenced by RTFont().
void RTFont::MeasureText (rtRectf * pRectOut, const string & text, float scale = 1.0f)
Definition at line 172 of file RTFont.cpp.
Referenced by ProtonPainter::CalculateTextDrawSize(), CreateCheckbox(), DrawAligned(), DrawAlignedSolidColor(), DrawWrapped(), GetFontAndScaleToFitThisStringInWidthPixels(), and MeasureText().
void RTFont::MeasureText (rtRectf * pRectOut, const char * pText, int len, float scale)
Definition at line 185 of file RTFont.cpp.
References rtfont_header::blankCharWidth, rtRectf::bottom, rtfont_charData::charBmpOffsetY, rtfont_charData::charSizeX, rtfont_charData::charSizeY, rtfont_header::firstChar, GetLineHeight(), IsLoaded(), LogMsg(), rtRectf::right, rtRectf::top, and rtfont_charData::xadvance.
CL_Vec2f RTFont::MeasureText (const string & text, float scale = 1.0f)
Definition at line 177 of file RTFont.cpp.
References rtRectf::GetHeight(), rtRectf::GetWidth(), and MeasureText().
void RTFont::MeasureTextAndAddByLinesIntoDeque (const CL_Vec2f & textBounds, const string & text, deque< string > * pLines, float scale, CL_Vec2f & vEnclosingSizeOut)
Definition at line 684 of file RTFont.cpp.
References GetLineHeight(), and LogError().
Referenced by DrawWrapped().
void RTFont::SetSmoothing (bool bSmoothing)
Definition at line 595 of file RTFont.cpp.
References Surface::IsLoaded(), and Surface::SetSmoothing().
The documentation for this class was generated from the following files:
RTFont.h
RTFont.cpp