Proton: LogTickIterator Class Reference
LogTickIterator Class Reference
#include <pplot.h>
Public Member Functions
LogTickIterator ()
virtual bool Init ()
virtual bool GetNextTick (float &outTick, bool &outIsMajorTick, string &outFormatString)
bool InitFromRanges (float inParRange, float inOrthoScreenRange, float inDivGuess, TickInfo &outTickInfo) const
virtual bool AdjustRange (float &ioMin, float &ioMax) const
float RoundUp (float inFloat) const
float RoundDown (float inFloat) const
Protected Attributes
float mCurrentTick
long mCount
float mDelta
Detailed Description
Definition at line 423 of file pplot.h.
Constructor & Destructor Documentation
LogTickIterator::LogTickIterator () [inline]
Definition at line 425 of file pplot.h.
Member Function Documentation
bool LogTickIterator::AdjustRange (float & ioMin, float & ioMax) const [virtual]
Reimplemented from TickIterator.
Definition at line 824 of file PPlot.cpp.
References kLittleDecrease, kLittleIncrease, kLogMinClipValue, and SafeExp().
bool LogTickIterator::GetNextTick (float & outTick, bool & outIsMajorTick, string & outFormatString) [virtual]
Implements TickIterator.
Definition at line 793 of file PPlot.cpp.
References kEps, kLittleIncrease, TickInfo::MakeFormatString(), SafeExp(), and SafeLog().
bool LogTickIterator::Init () [virtual]
Implements TickIterator.
Definition at line 734 of file PPlot.cpp.
References kLittleDecrease, SafeExp(), and SafeLog().
bool LogTickIterator::InitFromRanges (float inParRange, float inOrthoScreenRange, float inDivGuess, TickInfo & outTickInfo) const [virtual]
Implements TickIterator.
Definition at line 768 of file PPlot.cpp.
References kFloatSmall, kMinMinorTickScreenSize, kRelMajorTickSize, kRelMinorTickSize, TickInfo::mFormatString, TickInfo::mMajorTickScreenSize, TickInfo::mMajorTickSpan, TickInfo::mMinorTickScreenSize, TickInfo::mTickDivision, PMax(), and PPlot::Round().
float LogTickIterator::RoundDown (float inFloat) const
Definition at line 857 of file PPlot.cpp.
References SafeLog().
float LogTickIterator::RoundUp (float inFloat) const
Definition at line 850 of file PPlot.cpp.
References SafeLog().
Member Data Documentation
long LogTickIterator::mCount [protected]
Definition at line 435 of file pplot.h.
float LogTickIterator::mCurrentTick [protected]
Definition at line 434 of file pplot.h.
float LogTickIterator::mDelta [protected]
Definition at line 436 of file pplot.h.
The documentation for this class was generated from the following files:
pplot.h
PPlot.cpp