Proton: LineDataDrawer Class Reference
LineDataDrawer Class Reference
#include <pplot.h>
Public Member Functions
LineDataDrawer ()
virtual bool DrawData (const PlotDataBase &inXData, const PlotDataBase &inYData, const PlotDataSelection &inPlotDataSelection, const AxisSetup &inXAxisSetup, const PRect &inRect, Painter &inPainter) const
virtual DataDrawerBase * Clone () const
virtual bool DrawPoint (int inScreenX, int inScreenY, const PRect &inRect, Painter &inPainter) const
virtual bool DrawSelection (int inScreenX, int inScreenY, const PRect &inRect, Painter &inPainter) const
Public Attributes
bool mDrawLine
bool mDrawPoint
PStyle mStyle
Detailed Description
Definition at line 232 of file pplot.h.
Constructor & Destructor Documentation
LineDataDrawer::LineDataDrawer () [inline]
Definition at line 234 of file pplot.h.
Referenced by Clone().
Member Function Documentation
DataDrawerBase * LineDataDrawer::Clone () const [virtual]
Implements DataDrawerBase.
Definition at line 1497 of file PPlot.cpp.
References LineDataDrawer().
bool LineDataDrawer::DrawData (const PlotDataBase & inXData, const PlotDataBase & inYData, const PlotDataSelection & inPlotDataSelection, const AxisSetup & inXAxisSetup, const PRect & inRect, Painter & inPainter) const [virtual]
Implements DataDrawerBase.
Definition at line 1432 of file PPlot.cpp.
References Painter::DrawLine(), DrawPoint(), DrawSelection(), FindRange(), GetMaxFromRange(), PlotDataBase::GetSize(), PlotDataBase::GetValue(), Painter::GetWidth(), PlotDataSelection::IsSelected(), DataDrawerBase::mDrawFast, mDrawLine, mDrawPoint, AxisSetup::mMax, AxisSetup::mMin, mStyle, DataDrawerBase::mXTrafo, DataDrawerBase::mYTrafo, Painter::SetStyle(), and Trafo::Transform().
bool LineDataDrawer::DrawPoint (int inScreenX, int inScreenY, const PRect & inRect, Painter & inPainter) const [virtual]
Reimplemented in DotDataDrawer.
Definition at line 1501 of file PPlot.cpp.
References Painter::DrawLine().
Referenced by DrawData().
bool LineDataDrawer::DrawSelection (int inScreenX, int inScreenY, const PRect & inRect, Painter & inPainter) const [virtual]
Definition at line 1507 of file PPlot.cpp.
References Painter::FillRect().
Referenced by DrawData().
Member Data Documentation
bool LineDataDrawer::mDrawLine
Definition at line 241 of file pplot.h.
Referenced by DotDataDrawer::DotDataDrawer(), DrawData(), and MakeExamplePlot6().
bool LineDataDrawer::mDrawPoint
Definition at line 242 of file pplot.h.
Referenced by DotDataDrawer::DotDataDrawer(), DrawData(), and MakeExamplePlot6().
PStyle LineDataDrawer::mStyle
Definition at line 243 of file pplot.h.
Referenced by DrawData(), MakeExamplePlot1(), and MakeExamplePlot6().
The documentation for this class was generated from the following files:
pplot.h
PPlot.cpp