Proton: AdProvider Class Reference
AdProvider Class Reference
#include <AdProvider.h>
Public Member Functions
AdProvider ()
virtual ~AdProvider ()
virtual bool OnAddToManager (AdManager *pAdManager)=0
virtual string GetName ()=0
virtual void Update ()=0
virtual bool OnMessage (Message &m)
virtual void ShowInterstitial (std::string location="", std::string parm2="", std::string parm3="")
virtual void CacheShowInterstitial (std::string location="", std::string parm2="", std::string parm3="")
virtual void ShowMoreApps (std::string location="", std::string parm2="", std::string parm3="")
virtual void CacheShowMoreApps (std::string location="", std::string parm2="", std::string parm3="")
virtual void TrackingOnPageView ()
virtual void TrackingLog (string eventName, string optionalKey="", string optionalValue="")
eAdProviderType GetType ()
Protected Attributes
eAdProviderType m_adProviderType
Detailed Description
Definition at line 25 of file AdProvider.h.
Constructor & Destructor Documentation
AdProvider::AdProvider ()
Definition at line 4 of file AdProvider.cpp.
References AD_PROVIDER_UNKNOWN, and m_adProviderType.
AdProvider::~AdProvider () [virtual]
Definition at line 9 of file AdProvider.cpp.
Member Function Documentation
virtual void AdProvider::CacheShowInterstitial (std::string location = "", std::string parm2 = "", std::string parm3 = "") [inline, virtual]
Reimplemented in AdProviderChartBoost.
Definition at line 37 of file AdProvider.h.
References GetName(), and LogMsg().
virtual void AdProvider::CacheShowMoreApps (std::string location = "", std::string parm2 = "", std::string parm3 = "") [inline, virtual]
Reimplemented in AdProviderChartBoost.
Definition at line 40 of file AdProvider.h.
References GetName(), and LogMsg().
virtual string AdProvider::GetName () [pure virtual]
Implemented in AdProviderChartBoost, and AdProviderFlurry.
Referenced by AdManager::AddProvider(), CacheShowInterstitial(), CacheShowMoreApps(), ShowInterstitial(), and ShowMoreApps().
eAdProviderType AdProvider::GetType () [inline]
Definition at line 45 of file AdProvider.h.
References m_adProviderType.
virtual bool AdProvider::OnAddToManager (AdManager * pAdManager) [pure virtual]
Implemented in AdProviderChartBoost, and AdProviderFlurry.
Referenced by AdManager::AddProvider().
virtual bool AdProvider::OnMessage (Message & m) [inline, virtual]
Reimplemented in AdProviderChartBoost, and AdProviderFlurry.
Definition at line 34 of file AdProvider.h.
virtual void AdProvider::ShowInterstitial (std::string location = "", std::string parm2 = "", std::string parm3 = "") [inline, virtual]
Reimplemented in AdProviderChartBoost.
Definition at line 36 of file AdProvider.h.
References GetName(), and LogMsg().
virtual void AdProvider::ShowMoreApps (std::string location = "", std::string parm2 = "", std::string parm3 = "") [inline, virtual]
Reimplemented in AdProviderChartBoost.
Definition at line 39 of file AdProvider.h.
References GetName(), and LogMsg().
virtual void AdProvider::TrackingLog (string eventName, string optionalKey = "", string optionalValue = "") [inline, virtual]
Reimplemented in AdProviderFlurry.
Definition at line 43 of file AdProvider.h.
virtual void AdProvider::TrackingOnPageView () [inline, virtual]
Reimplemented in AdProviderFlurry.
Definition at line 42 of file AdProvider.h.
virtual void AdProvider::Update () [pure virtual]
Implemented in AdProviderChartBoost, and AdProviderFlurry.
Member Data Documentation
eAdProviderType AdProvider::m_adProviderType [protected]
Definition at line 49 of file AdProvider.h.
Referenced by AdProvider(), AdProviderChartBoost::AdProviderChartBoost(), AdProviderFlurry::AdProviderFlurry(), and GetType().
The documentation for this class was generated from the following files:
AdProvider.h
AdProvider.cpp