Proton: JPGSurfaceLoader Class Reference
JPGSurfaceLoader Class Reference
#include <JPGSurfaceLoader.h>
Public Member Functions
JPGSurfaceLoader ()
virtual ~JPGSurfaceLoader ()
bool LoadFromMem (byte *pMem, int inputSize, SoftSurface *pSurf, bool bAddAlphaChannelIfPadded)
Static Public Member Functions
static void init_source (j_decompress_ptr cinfo)
static boolean fill_input_buffer (j_decompress_ptr cinfo)
static void skip_input_data (j_decompress_ptr cinfo, long count)
static void term_source (j_decompress_ptr cinfo)
static void output_message (j_common_ptr cinfo)
static void error_exit (j_common_ptr cinfo)
Detailed Description
Definition at line 21 of file JPGSurfaceLoader.h.
Constructor & Destructor Documentation
JPGSurfaceLoader::JPGSurfaceLoader ()
Definition at line 15 of file JPGSurfaceLoader.cpp.
JPGSurfaceLoader::~JPGSurfaceLoader () [virtual]
Definition at line 19 of file JPGSurfaceLoader.cpp.
Member Function Documentation
void JPGSurfaceLoader::error_exit (j_common_ptr cinfo) [static]
Definition at line 23 of file JPGSurfaceLoader.cpp.
Referenced by LoadFromMem().
boolean JPGSurfaceLoader::fill_input_buffer (j_decompress_ptr cinfo) [static]
Definition at line 45 of file JPGSurfaceLoader.cpp.
Referenced by LoadFromMem().
void JPGSurfaceLoader::init_source (j_decompress_ptr cinfo) [static]
Definition at line 38 of file JPGSurfaceLoader.cpp.
Referenced by LoadFromMem().
bool JPGSurfaceLoader::LoadFromMem (byte * pMem, int inputSize, SoftSurface * pSurf, bool bAddAlphaChannelIfPadded)
Definition at line 78 of file JPGSurfaceLoader.cpp.
References error_exit(), fill_input_buffer(), SoftSurface::FillColor(), SoftSurface::FlipY(), SoftSurface::GetBytesPerPixel(), SoftSurface::GetPixelData(), SoftSurface::Init(), init_source(), IsPowerOf2(), output_message(), skip_input_data(), SoftSurface::SURFACE_RGB, SoftSurface::SURFACE_RGBA, and term_source().
Referenced by SoftSurface::LoadFileFromMemory().
void JPGSurfaceLoader::output_message (j_common_ptr cinfo) [static]
Definition at line 70 of file JPGSurfaceLoader.cpp.
References LogError().
Referenced by LoadFromMem().
void JPGSurfaceLoader::skip_input_data (j_decompress_ptr cinfo, long count) [static]
Definition at line 53 of file JPGSurfaceLoader.cpp.
Referenced by LoadFromMem().
void JPGSurfaceLoader::term_source (j_decompress_ptr cinfo) [static]
Definition at line 65 of file JPGSurfaceLoader.cpp.
Referenced by LoadFromMem().
The documentation for this class was generated from the following files:
JPGSurfaceLoader.h
JPGSurfaceLoader.cpp