Proton: CRandom Class Reference
CRandom Class Reference
#include <CRandom.h>
Public Member Functions
CRandom (void)
unsigned int Random (unsigned int n)
int RandomRange (int min, int max)
float RandomRangeFloat (float rangeMin, float rangeMax)
void SetRandomSeed (unsigned int n)
unsigned int GetRandomSeed (void)
void Randomize (void)
unsigned int rand ()
Detailed Description
Definition at line 24 of file CRandom.h.
Constructor & Destructor Documentation
CRandom::CRandom (void)
Definition at line 4 of file CRandom.cpp.
Member Function Documentation
unsigned int CRandom::GetRandomSeed (void)
Definition at line 68 of file CRandom.cpp.
unsigned int CRandom::rand ()
Definition at line 10 of file CRandom.cpp.
References Random().
Referenced by CWeightRand::GetRandom().
unsigned int CRandom::Random (unsigned int n)
Definition at line 16 of file CRandom.cpp.
References SetRandomSeed().
Referenced by rand(), and RandomRange().
void CRandom::Randomize (void)
Definition at line 73 of file CRandom.cpp.
References GetSystemTimeTick(), and SetRandomSeed().
int CRandom::RandomRange (int min, int max)
Definition at line 78 of file CRandom.cpp.
References Random().
Referenced by RandomRangeFloat().
float CRandom::RandomRangeFloat (float rangeMin, float rangeMax) [inline]
Definition at line 37 of file CRandom.h.
References RandomRange().
void CRandom::SetRandomSeed (unsigned int n)
Definition at line 56 of file CRandom.cpp.
Referenced by Random(), and Randomize().
The documentation for this class was generated from the following files:
CRandom.h
CRandom.cpp