Proton: TestResults Class Reference
TestResults Class Reference
#include <ProtonTester-internal.h>
Public Member Functions
TestResults ()
void clear ()
unsigned int GetTotalRun () const
unsigned int GetNumPassed () const
unsigned int GetNumFailed () const
std::string GetResultString () const
Static Public Member Functions
static void add (const CheckResult &result)
Detailed Description
Definition at line 59 of file ProtonTester-internal.h.
Constructor & Destructor Documentation
TestResults::TestResults ()
Definition at line 50 of file ProtonTester.cpp.
References clear().
Member Function Documentation
void TestResults::add (const CheckResult & result) [static]
Definition at line 63 of file ProtonTester.cpp.
References CheckResult::FAIL, CheckResult::GetResult(), CheckResult::GetResultString(), and CheckResult::GetTestName().
Referenced by CmpEq().
void TestResults::clear ()
Definition at line 55 of file ProtonTester.cpp.
Referenced by TestResults().
unsigned int TestResults::GetNumFailed () const
Definition at line 93 of file ProtonTester.cpp.
Referenced by ProtonTester::GetNumFailed(), and GetResultString().
unsigned int TestResults::GetNumPassed () const
Definition at line 88 of file ProtonTester.cpp.
Referenced by ProtonTester::GetNumPassed(), and GetResultString().
std::string TestResults::GetResultString () const
Definition at line 98 of file ProtonTester.cpp.
References GetNumFailed(), GetNumPassed(), GetTotalRun(), and toString().
Referenced by ProtonTester::runAllTests().
unsigned int TestResults::GetTotalRun () const
Definition at line 83 of file ProtonTester.cpp.
Referenced by GetResultString(), and ProtonTester::GetTotalRun().
The documentation for this class was generated from the following files:
ProtonTester-internal.h
ProtonTester.cpp