Proton: Painter Class Reference
Painter Class Reference
#include <pplot.h>
Public Member Functions
virtual void DrawLine (float inX1, float inY1, float inX2, float inY2)=0
virtual void FillRect (int inX, int inY, int inW, int inH)=0
virtual void InvertRect (int inX, int inY, int inW, int inH)=0
virtual void SetClipRect (int inX, int inY, int inW, int inH)=0
virtual long GetWidth () const =0
virtual long GetHeight () const =0
virtual void SetLineColor (int inR, int inG, int inB)=0
virtual void SetFillColor (int inR, int inG, int inB)=0
virtual long CalculateTextDrawSize (const char *inString)=0
virtual long GetFontHeight () const =0
virtual void DrawText (int inX, int inY, const char *inString)=0
virtual void DrawRotatedText (int inX, int inY, float inDegrees, const char *inString)=0
virtual void SetStyle (const PStyle &inStyle)
Detailed Description
Definition at line 171 of file pplot.h.
Member Function Documentation
virtual long Painter::CalculateTextDrawSize (const char * inString) [pure virtual]
Implemented in DummyPainter, and ProtonPainter.
Referenced by PPlot::CalculateTickInfo(), PainterTester::Draw(), PPlot::DrawLegend(), PPlot::DrawPlotBackground(), PPlot::DrawXAxis(), PPlot::DrawYAxis(), and PPlot::DrawYTick().
virtual void Painter::DrawLine (float inX1, float inY1, float inX2, float inY2) [pure virtual]
Implemented in DummyPainter, and ProtonPainter.
Referenced by PZoomInteraction::Draw(), PCrosshairInteraction::Draw(), PainterTester::Draw(), LineDataDrawer::DrawData(), PPlot::DrawGridXAxis(), PPlot::DrawGridYAxis(), LineDataDrawer::DrawPoint(), DotDataDrawer::DrawPoint(), PPlot::DrawXAxis(), PPlot::DrawXTick(), PPlot::DrawYAxis(), and PPlot::DrawYTick().
virtual void Painter::DrawRotatedText (int inX, int inY, float inDegrees, const char * inString) [pure virtual]
Implemented in DummyPainter, and ProtonPainter.
Referenced by PainterTester::Draw(), and PPlot::DrawYAxis().
virtual void Painter::DrawText (int inX, int inY, const char * inString) [pure virtual]
Implemented in DummyPainter, and ProtonPainter.
Referenced by PainterTester::Draw(), PPlot::DrawLegend(), PPlot::DrawPlotBackground(), PPlot::DrawXAxis(), PPlot::DrawXTick(), and PPlot::DrawYTick().
virtual void Painter::FillRect (int inX, int inY, int inW, int inH) [pure virtual]
Implemented in DummyPainter, and ProtonPainter.
Referenced by BarDataDrawer::DrawData(), BarDataDrawer::DrawOnlyLastPoint(), PPlot::DrawPlotBackground(), and LineDataDrawer::DrawSelection().
virtual long Painter::GetFontHeight () const [pure virtual]
Implemented in DummyPainter, and ProtonPainter.
Referenced by PPlot::CalculateTickInfo(), PainterTester::Draw(), PPlot::DrawLegend(), PPlot::DrawPlotBackground(), PPlot::DrawXAxis(), PPlot::DrawXTick(), and PPlot::DrawYTick().
virtual long Painter::GetHeight () const [pure virtual]
Implemented in DummyPainter, and ProtonPainter.
Referenced by PZoomInteraction::Draw(), PCrosshairInteraction::Draw(), and PPlot::Draw().
virtual long Painter::GetWidth () const [pure virtual]
Implemented in DummyPainter, and ProtonPainter.
Referenced by PZoomInteraction::Draw(), PCrosshairInteraction::Draw(), PPlot::Draw(), and LineDataDrawer::DrawData().
virtual void Painter::InvertRect (int inX, int inY, int inW, int inH) [pure virtual]
Implemented in DummyPainter, and ProtonPainter.
Referenced by PZoomInteraction::Draw().
virtual void Painter::SetClipRect (int inX, int inY, int inW, int inH) [pure virtual]
Implemented in DummyPainter, and ProtonPainter.
Referenced by PPlot::Draw().
virtual void Painter::SetFillColor (int inR, int inG, int inB) [pure virtual]
Implemented in DummyPainter, and ProtonPainter.
Referenced by PPlot::DrawGridXAxis(), PPlot::DrawGridYAxis(), PPlot::DrawPlot(), and PPlot::DrawPlotBackground().
virtual void Painter::SetLineColor (int inR, int inG, int inB) [pure virtual]
Implemented in DummyPainter, and ProtonPainter.
Referenced by PZoomInteraction::Draw(), PCrosshairInteraction::Draw(), PPlot::Draw(), PPlot::DrawGridXAxis(), PPlot::DrawGridYAxis(), PPlot::DrawLegend(), and PPlot::DrawPlot().
virtual void Painter::SetStyle (const PStyle & inStyle) [inline, virtual]
Definition at line 186 of file pplot.h.
Referenced by LineDataDrawer::DrawData(), PPlot::DrawGridXAxis(), PPlot::DrawGridYAxis(), PPlot::DrawLegend(), PPlot::DrawPlotBackground(), PPlot::DrawXAxis(), and PPlot::DrawYAxis().
The documentation for this class was generated from the following file:
pplot.h