Proton: ProgressBarComponent Class Reference
ProgressBarComponent Class Reference
#include <ProgressBarComponent.h>
Public Types
enum eType { TYPE_HORIZONTAL, TYPE_VERTICAL }
Public Member Functions
ProgressBarComponent ()
virtual ~ProgressBarComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
Detailed Description
Definition at line 17 of file ProgressBarComponent.h.
Member Enumeration Documentation
enum ProgressBarComponent::eType
Enumerator:
TYPE_HORIZONTAL
TYPE_VERTICAL
Definition at line 26 of file ProgressBarComponent.h.
Constructor & Destructor Documentation
ProgressBarComponent::ProgressBarComponent ()
Definition at line 7 of file ProgressBarComponent.cpp.
References EntityComponent::SetName().
ProgressBarComponent::~ProgressBarComponent () [virtual]
Definition at line 12 of file ProgressBarComponent.cpp.
Member Function Documentation
void ProgressBarComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 56 of file ProgressBarComponent.cpp.
References Variant::GetFloat(), Entity::GetFunction(), EntityComponent::GetParent(), Variant::GetSigOnChanged, Variant::GetString(), Variant::GetUINT32(), EntityComponent::GetVar(), Entity::GetVar(), EntityComponent::GetVarWithDefault(), Entity::GetVarWithDefault(), Variant::GetVector2(), INTERPOLATE_SMOOTHSTEP, FunctionObject::sig_function, and TYPE_HORIZONTAL.
void ProgressBarComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 96 of file ProgressBarComponent.cpp.
The documentation for this class was generated from the following files:
ProgressBarComponent.h
ProgressBarComponent.cpp