Proton: StreamingInstanceFile Class Reference
StreamingInstanceFile Class Reference
#include <StreamingInstanceFile.h>
Public Member Functions
StreamingInstanceFile ()
virtual ~StreamingInstanceFile ()
virtual bool Open (string fName)
virtual bool IsFinished ()
virtual int Read (byte *pBufferOut, int maxBytesToRead)
virtual void Close ()
virtual void SeekFromStart (int byteCount)
Detailed Description
Definition at line 15 of file StreamingInstanceFile.h.
Constructor & Destructor Documentation
StreamingInstanceFile::StreamingInstanceFile ()
Definition at line 4 of file StreamingInstanceFile.cpp.
StreamingInstanceFile::~StreamingInstanceFile () [virtual]
Definition at line 9 of file StreamingInstanceFile.cpp.
References Close().
Member Function Documentation
void StreamingInstanceFile::Close () [virtual]
Definition at line 14 of file StreamingInstanceFile.cpp.
Referenced by Open(), and ~StreamingInstanceFile().
bool StreamingInstanceFile::IsFinished () [virtual]
Implements StreamingInstance.
Definition at line 50 of file StreamingInstanceFile.cpp.
bool StreamingInstanceFile::Open (string fName) [virtual]
Implements StreamingInstance.
Definition at line 23 of file StreamingInstanceFile.cpp.
References Close(), and LogMsg().
Referenced by FileManager::GetStreaming().
int StreamingInstanceFile::Read (byte * pBufferOut, int maxBytesToRead) [virtual]
Implements StreamingInstance.
Definition at line 38 of file StreamingInstanceFile.cpp.
References LogMsg().
void StreamingInstanceFile::SeekFromStart (int byteCount) [virtual]
Reimplemented from StreamingInstance.
Definition at line 57 of file StreamingInstanceFile.cpp.
The documentation for this class was generated from the following files:
StreamingInstanceFile.h
StreamingInstanceFile.cpp