Proton: TapSequenceDetectComponent Class Reference
TapSequenceDetectComponent Class Reference
#include <TapSequenceDetectComponent.h>
Public Member Functions
TapSequenceDetectComponent ()
virtual ~TapSequenceDetectComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
Detailed Description
Definition at line 17 of file TapSequenceDetectComponent.h.
Constructor & Destructor Documentation
TapSequenceDetectComponent::TapSequenceDetectComponent ()
Definition at line 6 of file TapSequenceDetectComponent.cpp.
References EntityComponent::SetName().
TapSequenceDetectComponent::~TapSequenceDetectComponent () [virtual]
Definition at line 11 of file TapSequenceDetectComponent.cpp.
Member Function Documentation
void TapSequenceDetectComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 16 of file TapSequenceDetectComponent.cpp.
References EntityComponent::GetFunction(), Entity::GetFunction(), EntityComponent::GetParent(), Variant::GetUINT32(), Entity::GetVar(), Entity::GetVarWithDefault(), Variant::GetVector2(), and FunctionObject::sig_function.
void TapSequenceDetectComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 35 of file TapSequenceDetectComponent.cpp.
The documentation for this class was generated from the following files:
TapSequenceDetectComponent.h
TapSequenceDetectComponent.cpp