Proton: FocusUpdateComponent Class Reference
FocusUpdateComponent Class Reference
#include <FocusUpdateComponent.h>
Public Member Functions
FocusUpdateComponent ()
virtual ~FocusUpdateComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
void OnUpdate (VariantList *pVList)
Detailed Description
Definition at line 16 of file FocusUpdateComponent.h.
Constructor & Destructor Documentation
FocusUpdateComponent::FocusUpdateComponent ()
Definition at line 7 of file FocusUpdateComponent.cpp.
References EntityComponent::SetName().
FocusUpdateComponent::~FocusUpdateComponent () [virtual]
Definition at line 12 of file FocusUpdateComponent.cpp.
Member Function Documentation
void FocusUpdateComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 16 of file FocusUpdateComponent.cpp.
References GetBaseApp(), BaseApp::m_sig_update, and OnUpdate().
void FocusUpdateComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 25 of file FocusUpdateComponent.cpp.
void FocusUpdateComponent::OnUpdate (VariantList * pVList)
Definition at line 30 of file FocusUpdateComponent.cpp.
References Entity::CallFunctionRecursively(), and EntityComponent::GetParent().
Referenced by OnAdd().
The documentation for this class was generated from the following files:
FocusUpdateComponent.h
FocusUpdateComponent.cpp