Proton: BaseApp Class Reference
BaseApp Class Reference
#include <BaseApp.h>
Public Types
enum eErrorType { ERROR_NONE, ERROR_MEM, ERROR_SPACE }
Public Member Functions
BaseApp ()
virtual ~BaseApp ()
virtual bool Init ()
virtual void Kill ()
virtual bool OnPreInitVideo ()
virtual void Draw ()
virtual void Update ()
virtual void OnEnterBackground ()
virtual void OnEnterForeground ()
virtual void OnScreenSizeChange ()
virtual void OnFullscreenToggleRequest ()
void SetConsoleVisible (bool bNew)
bool GetConsoleVisible ()
bool GetFPSVisible ()
void SetFPSVisible (bool bNew)
unsigned int GetGameTick ()
void SetGameTick (unsigned int tick)
unsigned int GetTick ()
eTimingSystem GetActiveTimingSystem ()
unsigned int GetTickTimingSystem (eTimingSystem timingSystem)
float GetDelta ()
float GetGameDelta ()
int GetDeltaTick ()
int GetGameDeltaTick ()
float GetElapsedTime ()
float GetGameElapsedTime ()
Console * GetConsole ()
void SetGameTickPause (bool bNew)
bool GetGameTickPause ()
GameTimer * GetGameTimer ()
virtual void OnMessage (Message &m)
RTFont * GetFont (eFont font)
void SetInputMode (eInputMode mode)
eInputMode GetInputMode ()
virtual void OnMemoryWarning ()
deque< OSMessage > * GetOSMessages ()
void AddOSMessage (OSMessage &m)
void SetManualRotationMode (bool bRotation)
bool GetManualRotationMode ()
ResourceManager * GetResourceManager ()
void ModMemUsed (int mod)
void ModTexUsed (int mod)
int GetMemUsed ()
int GetTexMemUsed ()
eErrorType GetLastError ()
void ClearError ()
void SetLastError (eErrorType error)
bool IsInBackground ()
bool GetDisableSubPixelBlits ()
void SetDisableSubPixelBlits (bool bNew)
void AddCommandLineParm (string parm)
vector< string > GetCommandLineParms ()
void SetAccelerometerUpdateHz (float hz)
void SetAllowScreenDimming (bool bAllowDimming)
void PrintGLString (const char *name, GLenum s)
bool IsInitted ()
virtual void InitializeGLDefaults ()
CL_Mat4f * GetProjectionMatrix ()
Entity * GetEntityRoot ()
void SetCheatMode (bool bCheatMode)
bool GetCheatMode ()
void SetVideoMode (int width, int height, bool bFullScreen, float aspectRatio=0)
void KillOSMessagesByType (OSMessage::eMessageType type)
void SetFPSLimit (float fps)
Limits the running rate of the main loop.
TouchTrackInfo * GetTouch (int index)
int GetTotalActiveTouches ()
void ResetTouches ()
string GetAppVersion ()
Public Attributes
boost::signal< void(VariantList *) m_sig_input)
Taps, clicks, and basic keyboard input.
boost::signal< void(VariantList *) m_sig_input_move)
"Move" touch messages.
boost::signal< void(VariantList *) m_sig_os)
Messages from the platform itself.
boost::signal< void(VariantList *) m_sig_update)
Update signal for the game logic.
boost::signal< void(VariantList *) m_sig_render)
Signal for doing rendering.
boost::signal< void(VariantList *) m_sig_pre_enterbackground)
Early signal that we are about to enter background.
boost::signal< void(VariantList *) m_sig_enterbackground)
Game lost focus.
boost::signal< void(VariantList *) m_sig_enterforeground)
Game restored focus.
boost::signal< void(VariantList *) m_sig_accel)
Accelerometer data from iphone.
boost::signal< void(VariantList *) m_sig_trackball)
Used for android trackball move data.
boost::signal< void(VariantList *) m_sig_arcade_input)
For arcade movement controls like left/right/up/down.
boost::signal< void(VariantList *) m_sig_raw_keyboard)
For raw data from keyboards that give pressed/released messages.
boost::signal< void(VariantList *) m_sig_hardware)
boost::signal< void(void)> m_sig_unloadSurfaces
Signal to notify that it's time to release surfaces.
boost::signal< void(void)> m_sig_loadSurfaces
Signal to notify that it's time to reload surfaces.
boost::signal< void(VariantList *) m_sig_joypad_events)
boost::signal< void(VariantList *) m_sig_native_input_state_changed)
Protected Attributes
bool m_bConsoleVisible
bool m_bFPSVisible
bool m_bInitted
GameTimer m_gameTimer
Console m_console
RTFont m_fontArray [FONT_BASE_COUNT]
deque< OSMessage > m_OSMessages
bool m_bManualRotation
ResourceManager m_resourceManager
eInputMode m_inputMode
int m_memUsed
int m_texMemUsed
eErrorType m_error
bool m_bIsInBackground
vector< string > m_commandLineParms
CL_Mat4f m_projectionMatrix
Entity m_entityRoot
bool m_bCheatMode
vector< TouchTrackInfo > m_touchTracker
string m_version
bool m_bDisableSubPixelBlits
Detailed Description
Definition at line 189 of file BaseApp.h.
Member Enumeration Documentation
enum BaseApp::eErrorType
Enumerator:
ERROR_NONE
ERROR_MEM
ERROR_SPACE
Definition at line 194 of file BaseApp.h.
Constructor & Destructor Documentation
BaseApp::BaseApp ()
Definition at line 24 of file BaseApp.cpp.
References ClearError(), g_isBaseAppInitted, g_isLoggerInitted, INPUT_MODE_NORMAL, m_bCheatMode, m_bConsoleVisible, m_bDisableSubPixelBlits, m_bInitted, m_bIsInBackground, m_bManualRotation, m_memUsed, m_texMemUsed, m_touchTracker, m_version, SetFPSVisible(), and SetInputMode().
BaseApp::~BaseApp () [virtual]
Definition at line 43 of file BaseApp.cpp.
References g_isLoggerInitted, ResourceManager::KillAllResources(), m_commandLineParms, m_entityRoot, m_resourceManager, and Entity::RemoveAllEntities().
Member Function Documentation
void BaseApp::AddCommandLineParm (string parm)
Definition at line 554 of file BaseApp.cpp.
References m_commandLineParms.
void BaseApp::AddOSMessage (OSMessage & m)
Definition at line 419 of file BaseApp.cpp.
References IsBaseAppInitted(), and m_OSMessages.
Referenced by IAPManager::BuyItem(), AdProviderChartBoost::CacheShowInterstitial(), AdProviderChartBoost::CacheShowMoreApps(), AdManager::CacheTapjoyAd(), AdManager::CacheTapjoyFeaturedApp(), AdManager::GetTapPointsFromServer(), AdManager::InitTapjoy(), AdManager::ModifyTapPoints(), AdProviderFlurry::OnAddToManager(), AdProviderChartBoost::OnAddToManager(), AdManager::OpenTapjoyOfferWall(), PreloadKeyboard(), IAPManager::sendPurchaseMessage(), SetAccelerometerUpdateHz(), SetAllowScreenDimming(), SetFPSLimit(), AdManager::SetTapjoyAdVisible(), AdManager::SetTapjoyFeatureAppVisible(), AdManager::SetupBanner(), SetVideoMode(), AdProviderChartBoost::ShowInterstitial(), AdProviderChartBoost::ShowMoreApps(), IAPManager::SyncPurchases(), AdProviderFlurry::TrackingLog(), and AdProviderFlurry::TrackingOnPageView().
void BaseApp::ClearError () [inline]
Definition at line 354 of file BaseApp.h.
Referenced by BaseApp().
void BaseApp::Draw () [virtual]
Definition at line 131 of file BaseApp.cpp.
References DrawConsole(), RTFont::DrawScaled(), ERROR_MEM, ERROR_NONE, ERROR_SPACE, RenderBatcher::Flush(), FONT_SMALL, GetAudioManager(), GetConsoleVisible(), IrrlichtManager::GetDriver(), GetFont(), GameTimer::GetFPS(), GetFPSVisible(), GetFreeMemory(), GetIrrlichtManager(), GetLastError(), AudioManager::GetMemoryUsed(), GetNativeMemoryUsed(), m_gameTimer, m_memUsed, m_sig_render, m_texMemUsed, and SetupOrtho().
Referenced by AppRender(), and main().
eTimingSystem BaseApp::GetActiveTimingSystem ()
Definition at line 446 of file BaseApp.cpp.
References GetGameTickPause(), TIMER_GAME, and TIMER_SYSTEM.
Referenced by GetTiming(), and TrailRenderComponent::OnAdd().
string BaseApp::GetAppVersion ()
Definition at line 700 of file BaseApp.cpp.
References m_version.
bool BaseApp::GetCheatMode () [inline]
Definition at line 371 of file BaseApp.h.
vector< string > BaseApp::GetCommandLineParms ()
Definition at line 559 of file BaseApp.cpp.
References m_commandLineParms.
Console* BaseApp::GetConsole () [inline]
Definition at line 228 of file BaseApp.h.
Referenced by LogMsg(), and LogDisplayComponent::OnAdd().
bool BaseApp::GetConsoleVisible () [inline]
Definition at line 214 of file BaseApp.h.
Referenced by Draw().
float BaseApp::GetDelta () [inline]
Definition at line 222 of file BaseApp.h.
int BaseApp::GetDeltaTick () [inline]
Definition at line 224 of file BaseApp.h.
bool BaseApp::GetDisableSubPixelBlits () [inline]
Definition at line 357 of file BaseApp.h.
float BaseApp::GetElapsedTime () [inline]
Definition at line 226 of file BaseApp.h.
Entity* BaseApp::GetEntityRoot () [inline]
Definition at line 367 of file BaseApp.h.
Referenced by GetEntityRoot(), TouchDeviceEmulatorPointerEventHandler::handlePointerDownEvent(), TouchDeviceEmulatorPointerEventHandler::handlePointerMoveEvent(), TouchDeviceEmulatorPointerEventHandler::handlePointerUpEvent(), Init(), VariantTuner::resetTunableVariant(), and VariantTuner::setTunableVariant().
RTFont* BaseApp::GetFont (eFont font) [inline]
Definition at line 233 of file BaseApp.h.
Referenced by ProtonPainter::CalculateTextDrawSize(), CreateCheckbox(), CreateInputTextEntity(), CreateSlider(), Draw(), ProtonPainter::DrawText(), EnforceMinimumFontLineToScreenRatio(), GetFontAndScaleToFitThisLinesPerScreenY(), GetFontAndScaleToFitThisPixelHeight(), GetFontAndScaleToFitThisStringInWidthPixels(), ProtonPainter::GetFontHeight(), and IrrlichtManager::Render2D().
bool BaseApp::GetFPSVisible () [inline]
Definition at line 215 of file BaseApp.h.
Referenced by Draw().
float BaseApp::GetGameDelta () [inline]
Definition at line 223 of file BaseApp.h.
int BaseApp::GetGameDeltaTick () [inline]
Definition at line 225 of file BaseApp.h.
float BaseApp::GetGameElapsedTime () [inline]
Definition at line 227 of file BaseApp.h.
unsigned int BaseApp::GetGameTick () [inline]
Definition at line 217 of file BaseApp.h.
Referenced by Message::SetDeliveryTime(), SinGamePulseByMS(), and MessageManager::Update().
bool BaseApp::GetGameTickPause () [inline]
Definition at line 230 of file BaseApp.h.
Referenced by GetActiveTimingSystem().
GameTimer* BaseApp::GetGameTimer () [inline]
Definition at line 231 of file BaseApp.h.
eInputMode BaseApp::GetInputMode () [inline]
Definition at line 235 of file BaseApp.h.
eErrorType BaseApp::GetLastError () [inline]
Definition at line 353 of file BaseApp.h.
Referenced by Draw().
bool BaseApp::GetManualRotationMode () [inline]
Definition at line 344 of file BaseApp.h.
Referenced by ConvertCoordinatesIfRequired(), ConvertFakeScreenRectToReal(), RenderScissorComponent::FilterOnRender(), and GetOGLPos().
int BaseApp::GetMemUsed () [inline]
Definition at line 350 of file BaseApp.h.
deque<OSMessage>* BaseApp::GetOSMessages () [inline]
Definition at line 341 of file BaseApp.h.
Referenced by AppOSMessageGet(), main(), and Native_Update().
CL_Mat4f* BaseApp::GetProjectionMatrix () [inline]
Definition at line 366 of file BaseApp.h.
Referenced by GenerateSetPerspectiveFOV(), and GetOGLPos().
ResourceManager* BaseApp::GetResourceManager () [inline]
Definition at line 345 of file BaseApp.h.
Referenced by DestroyUnusedTextures(), and GetResourceManager().
int BaseApp::GetTexMemUsed () [inline]
Definition at line 351 of file BaseApp.h.
unsigned int BaseApp::GetTick () [inline]
Definition at line 219 of file BaseApp.h.
Referenced by TyperComponent::OnAdd(), TyperComponent::OnUpdate(), Message::SetDeliveryTime(), SinPulseByMS(), NetHTTP::Update(), and MessageManager::Update().
unsigned int BaseApp::GetTickTimingSystem (eTimingSystem timingSystem)
Definition at line 452 of file BaseApp.cpp.
References GameTimer::GetGameTick(), GameTimer::GetTick(), m_gameTimer, TIMER_GAME, and TIMER_SYSTEM.
Referenced by GetTick(), InterpolateComponent::OnDurationChanged(), and InterpolateComponent::OnUpdate().
int BaseApp::GetTotalActiveTouches ()
Definition at line 682 of file BaseApp.cpp.
References m_touchTracker.
TouchTrackInfo * BaseApp::GetTouch (int index)
Definition at line 670 of file BaseApp.cpp.
References m_touchTracker.
Referenced by TouchHandlerArcadeComponent::OnInput(), TouchDragComponent::OnInput(), TouchDragComponent::ResetLastPos(), SendFakeInputMessageToEntity(), ScrollComponent::~ScrollComponent(), TouchDragComponent::~TouchDragComponent(), and TouchStripComponent::~TouchStripComponent().
bool BaseApp::Init () [virtual]
Definition at line 89 of file BaseApp.cpp.
References GetAudioManager(), GetEntityRoot(), glGetIntegerv(), AudioManager::Init(), InitializeGLDefaults(), LogMsg(), m_bInitted, m_gameTimer, PrintGLString(), GameTimer::Reset(), and Entity::SetName().
void BaseApp::InitializeGLDefaults () [virtual]
Definition at line 68 of file BaseApp.cpp.
References glBlendFunc(), glClearColor(), glColor4x(), glCullFace(), glDepthFunc(), glDepthMask(), glDisable(), glDisableClientState(), glEnable(), glEnableClientState(), and glMatrixMode().
Referenced by AppInit(), and Init().
bool BaseApp::IsInBackground () [inline]
Definition at line 356 of file BaseApp.h.
bool BaseApp::IsInitted () [inline]
Definition at line 364 of file BaseApp.h.
void BaseApp::Kill () [virtual]
Definition at line 51 of file BaseApp.cpp.
References g_isBaseAppInitted.
Referenced by AppDone(), and main().
void BaseApp::KillOSMessagesByType (OSMessage::eMessageType type)
Definition at line 426 of file BaseApp.cpp.
References m_OSMessages.
void BaseApp::ModMemUsed (int mod) [inline]
Definition at line 347 of file BaseApp.h.
References mod().
Referenced by SoftSurface::Kill(), and SoftSurface::Scale().
void BaseApp::ModTexUsed (int mod) [inline]
Definition at line 348 of file BaseApp.h.
References mod().
Referenced by Surface::Kill().
void BaseApp::OnEnterBackground () [virtual]
Definition at line 502 of file BaseApp.cpp.
References GetAudioManager(), GetEmulatedPlatformID(), GetPlatformID(), LogMsg(), m_bIsInBackground, m_sig_enterbackground, m_sig_pre_enterbackground, m_sig_unloadSurfaces, PLATFORM_ID_ANDROID, and AudioManager::Suspend().
Referenced by AppUpdate(), Native_OnLostFocus(), and SDLEventLoop().
void BaseApp::OnEnterForeground () [virtual]
Definition at line 531 of file BaseApp.cpp.
References GetAudioManager(), GetBaseApp(), GetEmulatedPlatformID(), LogMsg(), m_bIsInBackground, m_sig_enterforeground, m_sig_loadSurfaces, PLATFORM_ID_ANDROID, and AudioManager::Resume().
Referenced by AppUpdate(), Native_OnGotFocus(), and SDLEventLoop().
void BaseApp::OnFullscreenToggleRequest () [virtual]
Definition at line 633 of file BaseApp.cpp.
References g_bIsFullScreen, GetBaseApp(), GetPrimaryGLX(), GetPrimaryGLY(), and SetVideoMode().
Referenced by OnMessage().
void BaseApp::OnMemoryWarning () [virtual]
Definition at line 497 of file BaseApp.cpp.
References LogMsg().
void BaseApp::OnMessage (Message & m) [virtual]
Definition at line 217 of file BaseApp.cpp.
References Message::Get(), VariantList::Get(), GetAudioManager(), Message::GetClass(), Message::GetParm1(), Message::GetParm2(), Message::GetParm3(), Message::GetParm4(), Message::GetStringParm(), Message::GetType(), Variant::GetUINT32(), Message::GetVarName(), Variant::GetVector2(), Variant::GetVector3(), INPUT_MODE_NORMAL, m_inputMode, m_sig_accel, m_sig_hardware, m_sig_input, m_sig_input_move, m_sig_os, m_sig_raw_keyboard, m_sig_trackball, m_touchTracker, m_version, MESSAGE_CLASS_GAME, MESSAGE_CLASS_GUI, MESSAGE_TYPE_APP_VERSION, MESSAGE_TYPE_GUI_ACCELEROMETER, MESSAGE_TYPE_GUI_CHAR, MESSAGE_TYPE_GUI_CHAR_RAW, MESSAGE_TYPE_GUI_CLICK_END, MESSAGE_TYPE_GUI_CLICK_MOVE, MESSAGE_TYPE_GUI_CLICK_MOVE_RAW, MESSAGE_TYPE_GUI_CLICK_START, MESSAGE_TYPE_GUI_MOUSEWHEEL, MESSAGE_TYPE_GUI_PASTE, MESSAGE_TYPE_GUI_TOGGLE_FULLSCREEN, MESSAGE_TYPE_GUI_TRACKBALL, MESSAGE_TYPE_HW_TOUCH_KEYBOARD_WILL_HIDE, MESSAGE_TYPE_HW_TOUCH_KEYBOARD_WILL_SHOW, MESSAGE_TYPE_OS_CONNECTION_CHECKED, MESSAGE_TYPE_PLAY_MUSIC, MESSAGE_TYPE_PLAY_SOUND, MESSAGE_TYPE_PRELOAD_SOUND, MESSAGE_TYPE_SET_SOUND_ENABLED, MESSAGE_TYPE_VIBRATE, OnFullscreenToggleRequest(), AudioManager::Play(), AudioManager::Preload(), ReplaceMP3(), VariantList::Reset(), Variant::Set(), AudioManager::SetSoundEnabled(), and AudioManager::Vibrate().
bool BaseApp::OnPreInitVideo () [virtual]
Definition at line 618 of file BaseApp.cpp.
Referenced by main().
void BaseApp::OnScreenSizeChange () [virtual]
Definition at line 202 of file BaseApp.cpp.
References GenerateSetPerspectiveFOV(), GetScreenSizeXf(), and GetScreenSizeYf().
Referenced by AppInit(), AppResize(), main(), and SetupScreenInfo().
void BaseApp::PrintGLString (const char * name, GLenum s)
Definition at line 62 of file BaseApp.cpp.
References glGetString(), and LogMsg().
Referenced by Init().
void BaseApp::ResetTouches ()
Definition at line 656 of file BaseApp.cpp.
References GetMessageManager(), LogMsg(), m_touchTracker, MESSAGE_TYPE_GUI_CLICK_END, and MessageManager::SendGUIEx().
void BaseApp::SetAccelerometerUpdateHz (float hz)
Definition at line 564 of file BaseApp.cpp.
References AddOSMessage(), GetBaseApp(), OSMessage::m_type, OSMessage::m_x, and OSMessage::MESSAGE_SET_ACCELEROMETER_UPDATE_HZ.
void BaseApp::SetAllowScreenDimming (bool bAllowDimming)
Definition at line 572 of file BaseApp.cpp.
References AddOSMessage(), GetBaseApp(), OSMessage::m_type, OSMessage::m_x, and OSMessage::MESSAGE_ALLOW_SCREEN_DIMMING.
void BaseApp::SetCheatMode (bool bCheatMode) [inline]
Definition at line 370 of file BaseApp.h.
void BaseApp::SetConsoleVisible (bool bNew)
Definition at line 212 of file BaseApp.cpp.
References m_bConsoleVisible.
Referenced by LogError().
void BaseApp::SetDisableSubPixelBlits (bool bNew) [inline]
Definition at line 358 of file BaseApp.h.
void BaseApp::SetFPSLimit (float fps)
Limits the running rate of the main loop.
The main loop will execute (approximately) at most fps number of times per second.
Setting fps to zero removes the limitation and lets the main loop run as quickly as possible. This is also the default.
Negative values for fps are meaningless and are silently ignored.
Note:
Using this function sets an upper bound for the execution rate of the main loop. It can't be used for example to ensure a given rate of calls to Update().
Definition at line 586 of file BaseApp.cpp.
References AddOSMessage(), GetBaseApp(), OSMessage::m_type, OSMessage::m_x, and OSMessage::MESSAGE_SET_FPS_LIMIT.
void BaseApp::SetFPSVisible (bool bNew) [inline]
Definition at line 216 of file BaseApp.h.
Referenced by BaseApp().
void BaseApp::SetGameTick (unsigned int tick) [inline]
Definition at line 218 of file BaseApp.h.
void BaseApp::SetGameTickPause (bool bNew) [inline]
Definition at line 229 of file BaseApp.h.
void BaseApp::SetInputMode (eInputMode mode) [inline]
Definition at line 234 of file BaseApp.h.
Referenced by BaseApp().
void BaseApp::SetLastError (eErrorType error) [inline]
Definition at line 355 of file BaseApp.h.
void BaseApp::SetManualRotationMode (bool bRotation)
Definition at line 490 of file BaseApp.cpp.
References LogMsg(), and m_bManualRotation.
void BaseApp::SetVideoMode (int width, int height, bool bFullScreen, float aspectRatio = 0)
Definition at line 597 of file BaseApp.cpp.
References AddOSMessage(), GetBaseApp(), OSMessage::m_fontSize, OSMessage::m_fullscreen, OSMessage::m_type, OSMessage::m_x, OSMessage::m_y, and OSMessage::MESSAGE_SET_VIDEO_MODE.
Referenced by OnFullscreenToggleRequest().
void BaseApp::Update () [virtual]
Definition at line 194 of file BaseApp.cpp.
References GetAudioManager(), GetMessageManager(), m_gameTimer, m_sig_update, GameTimer::Update(), AudioManager::Update(), and MessageManager::Update().
Referenced by AppUpdate(), and main().
Member Data Documentation
bool BaseApp::m_bCheatMode [protected]
Definition at line 414 of file BaseApp.h.
Referenced by BaseApp().
bool BaseApp::m_bConsoleVisible [protected]
Definition at line 396 of file BaseApp.h.
Referenced by BaseApp(), and SetConsoleVisible().
bool BaseApp::m_bDisableSubPixelBlits [protected]
Definition at line 417 of file BaseApp.h.
Referenced by BaseApp().
bool BaseApp::m_bFPSVisible [protected]
Definition at line 397 of file BaseApp.h.
bool BaseApp::m_bInitted [protected]
Definition at line 398 of file BaseApp.h.
Referenced by BaseApp(), and Init().
bool BaseApp::m_bIsInBackground [protected]
Definition at line 409 of file BaseApp.h.
Referenced by BaseApp(), OnEnterBackground(), and OnEnterForeground().
bool BaseApp::m_bManualRotation [protected]
Definition at line 403 of file BaseApp.h.
Referenced by BaseApp(), and SetManualRotationMode().
vector<string> BaseApp::m_commandLineParms [protected]
Definition at line 410 of file BaseApp.h.
Referenced by AddCommandLineParm(), GetCommandLineParms(), and ~BaseApp().
Console BaseApp::m_console [protected]
Definition at line 400 of file BaseApp.h.
Entity BaseApp::m_entityRoot [protected]
Definition at line 413 of file BaseApp.h.
Referenced by ~BaseApp().
eErrorType BaseApp::m_error [protected]
Definition at line 408 of file BaseApp.h.
RTFont BaseApp::m_fontArray[FONT_BASE_COUNT] [protected]
Definition at line 401 of file BaseApp.h.
GameTimer BaseApp::m_gameTimer [protected]
Definition at line 399 of file BaseApp.h.
Referenced by Draw(), GetTickTimingSystem(), Init(), and Update().
eInputMode BaseApp::m_inputMode [protected]
Definition at line 405 of file BaseApp.h.
Referenced by OnMessage().
int BaseApp::m_memUsed [protected]
Definition at line 406 of file BaseApp.h.
Referenced by BaseApp(), and Draw().
deque<OSMessage> BaseApp::m_OSMessages [protected]
Definition at line 402 of file BaseApp.h.
Referenced by AddOSMessage(), and KillOSMessagesByType().
CL_Mat4f BaseApp::m_projectionMatrix [protected]
Definition at line 412 of file BaseApp.h.
ResourceManager BaseApp::m_resourceManager [protected]
Definition at line 404 of file BaseApp.h.
Referenced by ~BaseApp().
boost::signal<void (VariantList*) BaseApp::m_sig_accel)
Accelerometer data from iphone.
Definition at line 304 of file BaseApp.h.
Referenced by OnMessage().
boost::signal<void (VariantList*) BaseApp::m_sig_arcade_input)
For arcade movement controls like left/right/up/down.
If MovementInputComponent is used, trackball/wasd are converted to send through this as well.
Definition at line 310 of file BaseApp.h.
Referenced by MoveButtonState::OnPress(), MoveButtonState::OnPressToggle(), and MoveButtonState::ReleaseIfNeeded().
boost::signal<void (VariantList*) BaseApp::m_sig_enterbackground)
Game lost focus.
Definition at line 302 of file BaseApp.h.
Referenced by InputTextRenderComponent::OnAdd(), and OnEnterBackground().
boost::signal<void (VariantList*) BaseApp::m_sig_enterforeground)
Game restored focus.
Definition at line 303 of file BaseApp.h.
Referenced by Surface::InitBlankSurface(), Surface::LoadFileFromMemory(), InputTextRenderComponent::OnAdd(), and OnEnterForeground().
boost::signal<void (VariantList*) BaseApp::m_sig_hardware)
0: the eSystemType, as float. Should be cast to (eMessageType)(int) Signal to notify about hardware messages. Currently there are only two, MESSAGE_TYPE_HW_TOUCH_KEYBOARD_WILL_SHOW and MESSAGE_TYPE_HW_TOUCH_KEYBOARD_WILL_HIDE
Definition at line 327 of file BaseApp.h.
Referenced by GamepadiCade::Init(), OnMessage(), and PreloadKeyboard().
boost::signal<void (VariantList*) BaseApp::m_sig_input)
Taps, clicks, and basic keyboard input.
The parameter variant list contains the following:
0: the type of the event cast to a float. One of:
MESSAGE_TYPE_GUI_CLICK_START
MESSAGE_TYPE_GUI_CLICK_END
MESSAGE_TYPE_GUI_CLICK_MOVE
MESSAGE_TYPE_GUI_CLICK_MOVE_RAW
MESSAGE_TYPE_GUI_CHAR
MESSAGE_TYPE_GUI_PASTE
1: the position of the event as a Vector2 if it makes sense. If the first member (the type) is either MESSAGE_TYPE_GUI_CHAR or MESSAGE_TYPE_GUI_PASTE then this is always (0, 0).
2: this parameter depends on the value of the first member (the type).
For MESSAGE_TYPE_GUI_CLICK_START, MESSAGE_TYPE_GUI_CLICK_END, MESSAGE_TYPE_GUI_CLICK_MOVE, MESSAGE_TYPE_GUI_CLICK_MOVE_RAW this parameter defines the id of the finger used for the touch event as a uint32.
For MESSAGE_TYPE_GUI_CHAR this parameter contains the keycode of the pressed key as a uint32.
For MESSAGE_TYPE_GUI_PASTE this parameter contains the contents of the clipboard as a string.
3: this parameter depends on the value of the first member (the type).
For MESSAGE_TYPE_GUI_CLICK_START, MESSAGE_TYPE_GUI_CLICK_END, MESSAGE_TYPE_GUI_CLICK_MOVE, MESSAGE_TYPE_GUI_CLICK_MOVE_RAW MESSAGE_TYPE_GUI_CHAR this MESSAGE_TYPE_GUI_CHAR_RAW this parameter contains the state of the control/shift/alt keys as a bitfield (uint32). Test against the eVirtualKeyModifiers to determine which keys were down at the time this msg was generated.
For MESSAGE_TYPE_GUI_PASTE this parameter contains the contents of the clipboard as a string.
Definition at line 274 of file BaseApp.h.
Referenced by FocusInputComponent::OnAdd(), and OnMessage().
boost::signal<void (VariantList*) BaseApp::m_sig_input_move)
"Move" touch messages.
Used if eInputMode::INPUT_MODE_SEPARATE_MOVE_TOUCHES was set. Otherwise they are signaled via BaseApp::m_sig_input.
Definition at line 280 of file BaseApp.h.
Referenced by FocusInputComponent::LinkMoveMessages(), and OnMessage().
boost::signal<void (VariantList*) BaseApp::m_sig_joypad_events)
Definition at line 337 of file BaseApp.h.
Referenced by AppOnJoypad(), AppOnJoypadButtons(), AppOnJoypadConnection(), and GamepadMoga::GamepadMoga().
boost::signal<void (void)> BaseApp::m_sig_loadSurfaces
Signal to notify that it's time to reload surfaces.
Definition at line 335 of file BaseApp.h.
Referenced by AppInit(), IrrlichtManager::Init(), Surface::InitBlankSurface(), RTFont::Load(), and OnEnterForeground().
boost::signal<void (VariantList*) BaseApp::m_sig_native_input_state_changed)
Definition at line 339 of file BaseApp.h.
Referenced by SetIsUsingNativeUI().
boost::signal<void (VariantList*) BaseApp::m_sig_os)
Messages from the platform itself.
To get the type of the message use code like this:
 eMessageType mType = (eMessageType)(int)pVList->m_variant[0].GetFloat();
Definition at line 286 of file BaseApp.h.
Referenced by HTTPComponent::OnAdd(), and OnMessage().
boost::signal<void (VariantList*) BaseApp::m_sig_pre_enterbackground)
Early signal that we are about to enter background.
Don't mess with video here. Useful for shutting down audio on android.
Definition at line 301 of file BaseApp.h.
Referenced by AppPause(), and OnEnterBackground().
boost::signal<void (VariantList*) BaseApp::m_sig_raw_keyboard)
For raw data from keyboards that give pressed/released messages.
Generally you would convert them into arcade messages.
The parameter variant list contains two members:
0: the keycode of the pressed or released key as a uint32.
1: VIRTUAL_KEY_PRESS or VIRTUAL_KEY_RELEASE as a uint32 depending on whether the event was a key press or release.
Definition at line 320 of file BaseApp.h.
Referenced by GamepadiCade::Init(), FocusInputComponent::LinkRawMessages(), SelectButtonWithCustomInputComponent::OnAdd(), ArcadeInputComponent::OnAdd(), and OnMessage().
boost::signal<void (VariantList*) BaseApp::m_sig_render)
Signal for doing rendering.
Called once per frame. You should render but not do game logic here.
Definition at line 296 of file BaseApp.h.
Referenced by Draw(), and FocusRenderComponent::OnAdd().
boost::signal<void (VariantList*) BaseApp::m_sig_trackball)
Used for android trackball move data.
Definition at line 305 of file BaseApp.h.
Referenced by ArcadeInputComponent::OnAdd(), and OnMessage().
boost::signal<void (void)> BaseApp::m_sig_unloadSurfaces
Signal to notify that it's time to release surfaces.
Sent for example when the app goes to background.
Definition at line 334 of file BaseApp.h.
Referenced by AppUpdate(), IrrlichtManager::Init(), Surface::InitBlankSurface(), RTFont::Load(), Surface::LoadFileFromMemory(), and OnEnterBackground().
boost::signal<void (VariantList*) BaseApp::m_sig_update)
Update signal for the game logic.
Called once per frame, usually.
Definition at line 291 of file BaseApp.h.
Referenced by FocusUpdateComponent::OnAdd(), ArcadeInputComponent::OnAdd(), and Update().
int BaseApp::m_texMemUsed [protected]
Definition at line 407 of file BaseApp.h.
Referenced by BaseApp(), and Draw().
vector<TouchTrackInfo> BaseApp::m_touchTracker [protected]
Definition at line 415 of file BaseApp.h.
Referenced by BaseApp(), GetTotalActiveTouches(), GetTouch(), OnMessage(), and ResetTouches().
string BaseApp::m_version [protected]
Definition at line 416 of file BaseApp.h.
Referenced by BaseApp(), GetAppVersion(), and OnMessage().
The documentation for this class was generated from the following files:
BaseApp.h
BaseApp.cpp