Proton: GamepadProvideriCade Class Reference
GamepadProvideriCade Class Reference
#include <GamepadProvideriCade.h>
Public Member Functions
GamepadProvideriCade ()
virtual ~GamepadProvideriCade ()
virtual string GetName ()
virtual bool Init ()
virtual void Kill ()
virtual void Update ()
void OnLostiCadeConnection ()
Detailed Description
Definition at line 22 of file GamepadProvideriCade.h.
Constructor & Destructor Documentation
GamepadProvideriCade::GamepadProvideriCade ()
Definition at line 7 of file GamepadProvideriCade.cpp.
References Kill().
GamepadProvideriCade::~GamepadProvideriCade () [virtual]
Definition at line 12 of file GamepadProvideriCade.cpp.
Member Function Documentation
virtual string GamepadProvideriCade::GetName () [inline, virtual]
Implements GamepadProvider.
Definition at line 28 of file GamepadProvideriCade.h.
bool GamepadProvideriCade::Init () [virtual]
Implements GamepadProvider.
Definition at line 16 of file GamepadProvideriCade.cpp.
References GamepadManager::AddGamepad(), GetGamepadManager(), LogMsg(), and Gamepad::SetProvider().
void GamepadProvideriCade::Kill () [virtual]
Implements GamepadProvider.
Definition at line 25 of file GamepadProvideriCade.cpp.
Referenced by GamepadProvideriCade().
void GamepadProvideriCade::OnLostiCadeConnection ()
Definition at line 34 of file GamepadProvideriCade.cpp.
References LogMsg(), and GamepadProvider::m_sig_failed_to_connect.
void GamepadProvideriCade::Update () [virtual]
Implements GamepadProvider.
Definition at line 29 of file GamepadProvideriCade.cpp.
The documentation for this class was generated from the following files:
GamepadProvideriCade.h
GamepadProvideriCade.cpp