Proton: Gamepad Class Reference
Gamepad Class Reference
#include <Gamepad.h>
Public Member Functions
Gamepad ()
virtual ~Gamepad ()
virtual const string & GetName ()
virtual bool Init ()=0
virtual void Kill ()=0
virtual void Update ()
void Reset ()
bool GetIsUsed ()
void SetIsUsed (bool bUsed)
void ConnectToArcadeComponent (ArcadeInputComponent *pComp, bool bSendButtonEvents, bool bSendPadEventsAsFourDirections)
CL_Vec2f GetLeftStick ()
CL_Vec2f GetRightStick ()
GamepadButton * GetButton (int buttonID)
void SetRightStickAxis (int axisX, int axisY)
void SetID (eGamepadID id)
eGamepadID GetID ()
GamepadProvider * GetProvider ()
void SetProvider (GamepadProvider *pProvider)
void SetAxis (int axis, float val)
void OnButton (bool bDown, int buttonID)
void OnHat (int index, float val)
void SendArcadeDirectionByKey (eVirtualKeys key, bool bDown)
Public Attributes
boost::signal< void(VariantList *) m_sig_gamepad_buttons)
boost::signal< void(VariantList *) m_sig_left_stick)
boost::signal< void(VariantList *) m_sig_right_stick)
Protected Member Functions
void SendArcadeDirectionByDegrees (int val)
void OnArcadeCompDestroyed (VariantList *pVList)
void SendArcadeDirectionRelease ()
Protected Attributes
bool m_bJustSentStickRelease
string m_name
GamepadProvider * m_pPadProvider
GamepadAxis m_axis [GAMEPAD_MAX_AXIS]
GamepadButton m_buttons [GAMEPAD_MAX_BUTTONS]
int m_buttonsUsedCount
int m_axisUsedCount
int m_rightStickAxisX
int m_rightStickAxisY
CL_Vec2f m_vLastSentLeftStick
CL_Vec2f m_vLastSentRightStick
eGamepadID m_id
bool m_bIsUsed
MoveButtonState m_dirButtons [MOVE_BUTTON_DIR_COUNT]
ArcadeInputComponent * m_pArcadeComp
Detailed Description
Definition at line 63 of file Gamepad.h.
Constructor & Destructor Documentation
Gamepad::Gamepad ()
Definition at line 11 of file Gamepad.cpp.
References m_axisUsedCount, m_bIsUsed, m_bJustSentStickRelease, m_buttons, m_buttonsUsedCount, m_name, m_pArcadeComp, m_pPadProvider, GamepadButton::m_virtualKey, SetRightStickAxis(), and VIRTUAL_DPAD_BUTTON_LEFT.
Gamepad::~Gamepad () [virtual]
Definition at line 29 of file Gamepad.cpp.
References LogMsg(), and m_name.
Member Function Documentation
void Gamepad::ConnectToArcadeComponent (ArcadeInputComponent * pComp, bool bSendButtonEvents, bool bSendPadEventsAsFourDirections)
Definition at line 220 of file Gamepad.cpp.
References EntityComponent::GetFunction(), GetName(), LogMsg(), m_pArcadeComp, m_sig_gamepad_buttons, OnArcadeCompDestroyed(), ArcadeInputComponent::OnRawKeyboard(), and FunctionObject::sig_function.
GamepadButton * Gamepad::GetButton (int buttonID)
Definition at line 243 of file Gamepad.cpp.
References m_buttons.
Referenced by ArcadeKeyboardControl::Setup().
eGamepadID Gamepad::GetID () [inline]
Definition at line 103 of file Gamepad.h.
References m_id.
Referenced by GamepadManager::AddGamepad(), and GamepadManager::SetDefaultGamepad().
bool Gamepad::GetIsUsed () [inline]
Definition at line 76 of file Gamepad.h.
References m_bIsUsed.
CL_Vec2f Gamepad::GetLeftStick ()
Definition at line 249 of file Gamepad.cpp.
References m_axis.
Referenced by Update().
virtual const string& Gamepad::GetName () [inline, virtual]
Definition at line 70 of file Gamepad.h.
References m_name.
Referenced by GamepadManager::AddGamepad(), and ConnectToArcadeComponent().
GamepadProvider* Gamepad::GetProvider () [inline]
Definition at line 105 of file Gamepad.h.
References m_pPadProvider.
CL_Vec2f Gamepad::GetRightStick ()
Definition at line 254 of file Gamepad.cpp.
References m_axis, m_rightStickAxisX, and m_rightStickAxisY.
Referenced by Update().
virtual bool Gamepad::Init () [pure virtual]
Implemented in GamepadiCade, Gamepad60Beat, GamepadDirectX, and GamepadMoga.
Referenced by GamepadManager::AddGamepad().
virtual void Gamepad::Kill () [pure virtual]
Implemented in GamepadiCade, Gamepad60Beat, GamepadDirectX, and GamepadMoga.
void Gamepad::OnArcadeCompDestroyed (VariantList * pVList) [protected]
Definition at line 213 of file Gamepad.cpp.
References m_pArcadeComp.
Referenced by ConnectToArcadeComponent().
void Gamepad::OnButton (bool bDown, int buttonID)
Definition at line 44 of file Gamepad.cpp.
References VariantList::Get(), LogMsg(), m_buttons, m_id, m_sig_gamepad_buttons, GamepadButton::OnPress(), Variant::Set(), VIRTUAL_KEY_PRESS, and VIRTUAL_KEY_RELEASE.
Referenced by GamepadMoga::OnJoypadEvent(), and GamepadDirectX::Update().
void Gamepad::OnHat (int index, float val)
Definition at line 185 of file Gamepad.cpp.
References LogMsg(), m_pArcadeComp, SendArcadeDirectionByDegrees(), and SendArcadeDirectionRelease().
Referenced by GamepadDirectX::Update().
void Gamepad::Reset () [inline]
Definition at line 75 of file Gamepad.h.
References m_bIsUsed.
void Gamepad::SendArcadeDirectionByDegrees (int val) [protected]
Definition at line 91 of file Gamepad.cpp.
References LogMsg(), m_pArcadeComp, MOVE_BUTTON_DIR_DOWN, MOVE_BUTTON_DIR_LEFT, MOVE_BUTTON_DIR_RIGHT, MOVE_BUTTON_DIR_UP, and ArcadeInputComponent::SetDirectionKey().
Referenced by OnHat(), and Update().
void Gamepad::SendArcadeDirectionByKey (eVirtualKeys key, bool bDown)
Definition at line 66 of file Gamepad.cpp.
References LogMsg(), m_pArcadeComp, MOVE_BUTTON_DIR_DOWN, MOVE_BUTTON_DIR_LEFT, MOVE_BUTTON_DIR_RIGHT, MOVE_BUTTON_DIR_UP, ArcadeInputComponent::SetDirectionKey(), VIRTUAL_KEY_DIR_DOWN, VIRTUAL_KEY_DIR_LEFT, VIRTUAL_KEY_DIR_RIGHT, and VIRTUAL_KEY_DIR_UP.
void Gamepad::SendArcadeDirectionRelease () [protected]
Definition at line 176 of file Gamepad.cpp.
References m_pArcadeComp, MOVE_BUTTON_DIR_DOWN, MOVE_BUTTON_DIR_LEFT, MOVE_BUTTON_DIR_RIGHT, MOVE_BUTTON_DIR_UP, and ArcadeInputComponent::SetDirectionKey().
Referenced by OnHat(), and Update().
void Gamepad::SetAxis (int axis, float val)
Definition at line 34 of file Gamepad.cpp.
References LogMsg(), GamepadAxis::m_axis, and m_axis.
Referenced by GamepadMoga::OnJoypadEvent(), GamepadDirectX::Update(), and GamepadiCade::Update().
void Gamepad::SetID (eGamepadID id) [inline]
Definition at line 102 of file Gamepad.h.
References m_id.
Referenced by GamepadManager::AddGamepad().
void Gamepad::SetIsUsed (bool bUsed) [inline]
Definition at line 77 of file Gamepad.h.
References m_bIsUsed.
Referenced by GamepadManager::GetUnusedGamepad().
void Gamepad::SetProvider (GamepadProvider * pProvider) [inline]
Definition at line 106 of file Gamepad.h.
References m_pPadProvider.
Referenced by GamepadProvideriCade::Init().
void Gamepad::SetRightStickAxis (int axisX, int axisY)
Definition at line 206 of file Gamepad.cpp.
References m_rightStickAxisX, and m_rightStickAxisY.
Referenced by Gamepad(), GamepadMoga::Init(), and GamepadDirectX::Init().
void Gamepad::Update () [virtual]
Reimplemented in GamepadiCade, Gamepad60Beat, GamepadDirectX, and GamepadMoga.
Definition at line 259 of file Gamepad.cpp.
References GetLeftStick(), GetRightStick(), m_bJustSentStickRelease, m_id, m_pArcadeComp, m_sig_left_stick, m_sig_right_stick, m_vLastSentLeftStick, m_vLastSentRightStick, mod(), SendArcadeDirectionByDegrees(), and SendArcadeDirectionRelease().
Member Data Documentation
GamepadAxis Gamepad::m_axis[GAMEPAD_MAX_AXIS] [protected]
Definition at line 124 of file Gamepad.h.
Referenced by GetLeftStick(), GetRightStick(), and SetAxis().
int Gamepad::m_axisUsedCount [protected]
Definition at line 128 of file Gamepad.h.
Referenced by Gamepad(), GamepadMoga::Init(), GamepadDirectX::Init(), and GamepadiCade::Init().
bool Gamepad::m_bIsUsed [protected]
Definition at line 138 of file Gamepad.h.
Referenced by Gamepad(), GetIsUsed(), Reset(), and SetIsUsed().
bool Gamepad::m_bJustSentStickRelease [protected]
Definition at line 120 of file Gamepad.h.
Referenced by Gamepad(), and Update().
GamepadButton Gamepad::m_buttons[GAMEPAD_MAX_BUTTONS] [protected]
Definition at line 125 of file Gamepad.h.
Referenced by Gamepad(), GetButton(), GamepadDirectX::Init(), GamepadMoga::Init(), and OnButton().
int Gamepad::m_buttonsUsedCount [protected]
Definition at line 127 of file Gamepad.h.
Referenced by Gamepad(), GamepadDirectX::Init(), and GamepadiCade::Init().
MoveButtonState Gamepad::m_dirButtons[MOVE_BUTTON_DIR_COUNT] [protected]
Definition at line 142 of file Gamepad.h.
eGamepadID Gamepad::m_id [protected]
Definition at line 136 of file Gamepad.h.
Referenced by GetID(), OnButton(), SetID(), and Update().
string Gamepad::m_name [protected]
Definition at line 121 of file Gamepad.h.
Referenced by Gamepad(), GetName(), GamepadDirectX::Init(), GamepadMoga::Init(), GamepadiCade::Init(), and ~Gamepad().
ArcadeInputComponent* Gamepad::m_pArcadeComp [protected]
Definition at line 143 of file Gamepad.h.
Referenced by ConnectToArcadeComponent(), Gamepad(), OnArcadeCompDestroyed(), OnHat(), SendArcadeDirectionByDegrees(), SendArcadeDirectionByKey(), SendArcadeDirectionRelease(), and Update().
GamepadProvider* Gamepad::m_pPadProvider [protected]
Definition at line 122 of file Gamepad.h.
Referenced by Gamepad(), GetProvider(), GamepadDirectX::Init(), and SetProvider().
int Gamepad::m_rightStickAxisX [protected]
Definition at line 129 of file Gamepad.h.
Referenced by GetRightStick(), and SetRightStickAxis().
int Gamepad::m_rightStickAxisY [protected]
Definition at line 130 of file Gamepad.h.
Referenced by GetRightStick(), and SetRightStickAxis().
boost::signal<void (VariantList*) Gamepad::m_sig_gamepad_buttons)
Definition at line 95 of file Gamepad.h.
Referenced by ConnectToArcadeComponent(), and OnButton().
boost::signal<void (VariantList*) Gamepad::m_sig_left_stick)
Definition at line 99 of file Gamepad.h.
Referenced by Update().
boost::signal<void (VariantList*) Gamepad::m_sig_right_stick)
Definition at line 100 of file Gamepad.h.
Referenced by Update().
CL_Vec2f Gamepad::m_vLastSentLeftStick [protected]
Definition at line 133 of file Gamepad.h.
Referenced by Update().
CL_Vec2f Gamepad::m_vLastSentRightStick [protected]
Definition at line 134 of file Gamepad.h.
Referenced by Update().
The documentation for this class was generated from the following files:
Gamepad.h
Gamepad.cpp