Proton: TouchStripComponent Class Reference
TouchStripComponent Class Reference
#include <TouchStripComponent.h>
Public Types
enum eVisualStyle { STYLE_NONE }
Public Member Functions
TouchStripComponent ()
virtual ~TouchStripComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
Detailed Description
Definition at line 20 of file TouchStripComponent.h.
Member Enumeration Documentation
enum TouchStripComponent::eVisualStyle
Enumerator:
STYLE_NONE
Definition at line 29 of file TouchStripComponent.h.
Constructor & Destructor Documentation
TouchStripComponent::TouchStripComponent ()
Definition at line 5 of file TouchStripComponent.cpp.
References EntityComponent::SetName().
TouchStripComponent::~TouchStripComponent () [virtual]
Definition at line 11 of file TouchStripComponent.cpp.
References GetBaseApp(), BaseApp::GetTouch(), and TouchTrackInfo::SetWasHandled().
Member Function Documentation
void TouchStripComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 25 of file TouchStripComponent.cpp.
References Entity::GetFunction(), EntityComponent::GetParent(), Variant::GetRect(), Variant::GetUINT32(), EntityComponent::GetVar(), Entity::GetVar(), EntityComponent::GetVarWithDefault(), Entity::GetVarWithDefault(), Variant::GetVector2(), FunctionObject::sig_function, and STYLE_NONE.
void TouchStripComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 53 of file TouchStripComponent.cpp.
The documentation for this class was generated from the following files:
TouchStripComponent.h
TouchStripComponent.cpp