Proton: PZoomInteraction Class Reference
PZoomInteraction Class Reference
#include <PPlotInteraction.h>
Public Types
enum EZoomMode { kZoom_Region, kZoom_X, kZoom_Y }
Public Member Functions
PZoomInteraction (PPlot &inPPlot)
virtual bool HandleMouseEvent (const PMouseEvent &inEvent)
virtual bool HandleKeyEvent (const PKeyEvent &inEvent)
void DoZoomIn (float inX1, float inX2, float inY1, float inY2)
void DoZoomOut (float inY1=-1, float inY2=-1)
bool CanZoomOut ()
int GetZoomStackSize ()
bool IsZoomRegion () const
bool IsZoomX () const
bool IsZoomY () const
Public Attributes
stack< PAxisInfo > mZoomHistory
EZoomMode mZoomMode
Protected Member Functions
void StoreCurrentAxisSetup ()
virtual bool Draw (Painter &inPainter)
bool CheckRange (float inFloat1, float inFloat2)
void DoZoomIn ()
Protected Attributes
bool mDragging
int mX1
int mY1
int mX2
int mY2
Detailed Description
Definition at line 129 of file PPlotInteraction.h.
Member Enumeration Documentation
enum PZoomInteraction::EZoomMode
Enumerator:
kZoom_Region
kZoom_X
kZoom_Y
Definition at line 132 of file PPlotInteraction.h.
Constructor & Destructor Documentation
PZoomInteraction::PZoomInteraction (PPlot & inPPlot)
Definition at line 55 of file PPlotInteraction.cpp.
References PPlot::mPostDrawerList.
Member Function Documentation
bool PZoomInteraction::CanZoomOut () [inline]
Definition at line 145 of file PPlotInteraction.h.
References mZoomHistory.
bool PZoomInteraction::CheckRange (float inFloat1, float inFloat2) [protected]
Definition at line 167 of file PPlotInteraction.cpp.
Referenced by DoZoomIn().
void PZoomInteraction::DoZoomIn (float inX1, float inX2, float inY1, float inY2)
Definition at line 185 of file PPlotInteraction.cpp.
References CheckRange(), IsZoomRegion(), IsZoomX(), IsZoomY(), PPlot::kRangeVerySmall, AxisSetup::mMax, AxisSetup::mMin, PPlotInteraction::mPPlot, PPlot::mXAxisSetup, PPlot::mYAxisSetup, pmax(), pmin(), AxisSetup::SetAutoScale(), and StoreCurrentAxisSetup().
void PZoomInteraction::DoZoomIn () [protected]
Definition at line 225 of file PPlotInteraction.cpp.
References PPlotInteraction::mPPlot, mX1, mX2, PPlot::mXTrafo, mY1, mY2, PPlot::mYTrafo, and Trafo::TransformBack().
Referenced by HandleMouseEvent().
void PZoomInteraction::DoZoomOut (float inY1 = -1, float inY2 = -1)
Definition at line 235 of file PPlotInteraction.cpp.
References AxisSetup::mMax, AxisSetup::mMin, PPlotInteraction::mPPlot, PAxisInfo::mXAxisSetup, PPlot::mXAxisSetup, PAxisInfo::mYAxisSetup, PPlot::mYAxisSetup, mZoomHistory, pmax(), and pmin().
Referenced by HandleMouseEvent().
bool PZoomInteraction::Draw (Painter & inPainter) [protected, virtual]
Implements PDrawer.
Definition at line 124 of file PPlotInteraction.cpp.
References Painter::DrawLine(), Painter::GetHeight(), Painter::GetWidth(), Painter::InvertRect(), kZoom_Region, kZoom_X, kZoom_Y, PMargins::mBottom, mDragging, PMargins::mLeft, PPlot::mMargins, PPlotInteraction::mPPlot, PMargins::mRight, PMargins::mTop, mX1, mX2, mY1, mY2, mZoomMode, pmin(), and Painter::SetLineColor().
int PZoomInteraction::GetZoomStackSize () [inline]
Definition at line 146 of file PPlotInteraction.h.
bool PZoomInteraction::HandleKeyEvent (const PKeyEvent & inEvent) [virtual]
Reimplemented from PPlotInteraction.
Definition at line 103 of file PPlotInteraction.cpp.
References PKeyEvent::GetChar(), PKeyEvent::IsChar(), PModifierKeys::IsOnlyControlKeyDown(), kZoom_Region, kZoom_X, kZoom_Y, and mZoomMode.
bool PZoomInteraction::HandleMouseEvent (const PMouseEvent & inEvent) [virtual]
Implements PPlotInteraction.
Definition at line 63 of file PPlotInteraction.cpp.
References DoZoomIn(), DoZoomOut(), PModifierKeys::HasModifierKeys(), PMouseEvent::IsMouseDown(), PMouseEvent::IsMouseMove(), PMouseEvent::IsMouseUp(), mDragging, PMouseEvent::mX, mX1, mX2, PMouseEvent::mY, mY1, and mY2.
bool PZoomInteraction::IsZoomRegion () const [inline]
Definition at line 151 of file PPlotInteraction.h.
References kZoom_Region, and mZoomMode.
Referenced by DoZoomIn().
bool PZoomInteraction::IsZoomX () const [inline]
Definition at line 152 of file PPlotInteraction.h.
References kZoom_X, and mZoomMode.
Referenced by DoZoomIn().
bool PZoomInteraction::IsZoomY () const [inline]
Definition at line 153 of file PPlotInteraction.h.
References kZoom_Y, and mZoomMode.
Referenced by DoZoomIn().
void PZoomInteraction::StoreCurrentAxisSetup () [protected]
Definition at line 216 of file PPlotInteraction.cpp.
References PPlotInteraction::mPPlot, PAxisInfo::mXAxisSetup, PPlot::mXAxisSetup, PAxisInfo::mYAxisSetup, PPlot::mYAxisSetup, and mZoomHistory.
Referenced by DoZoomIn().
Member Data Documentation
bool PZoomInteraction::mDragging [protected]
Definition at line 161 of file PPlotInteraction.h.
Referenced by Draw(), and HandleMouseEvent().
int PZoomInteraction::mX1 [protected]
Definition at line 162 of file PPlotInteraction.h.
Referenced by DoZoomIn(), Draw(), and HandleMouseEvent().
int PZoomInteraction::mX2 [protected]
Definition at line 164 of file PPlotInteraction.h.
Referenced by DoZoomIn(), Draw(), and HandleMouseEvent().
int PZoomInteraction::mY1 [protected]
Definition at line 163 of file PPlotInteraction.h.
Referenced by DoZoomIn(), Draw(), and HandleMouseEvent().
int PZoomInteraction::mY2 [protected]
Definition at line 165 of file PPlotInteraction.h.
Referenced by DoZoomIn(), Draw(), and HandleMouseEvent().
stack<PAxisInfo> PZoomInteraction::mZoomHistory
Definition at line 146 of file PPlotInteraction.h.
Referenced by CanZoomOut(), DoZoomOut(), and StoreCurrentAxisSetup().
EZoomMode PZoomInteraction::mZoomMode
Definition at line 149 of file PPlotInteraction.h.
Referenced by Draw(), HandleKeyEvent(), IsZoomRegion(), IsZoomX(), and IsZoomY().
The documentation for this class was generated from the following files:
PPlotInteraction.h
PPlotInteraction.cpp