Proton: UnpackArchiveComponent Class Reference
UnpackArchiveComponent Class Reference
#include <UnpackArchiveComponent.h>
Public Member Functions
UnpackArchiveComponent ()
virtual ~UnpackArchiveComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
Detailed Description
Definition at line 17 of file UnpackArchiveComponent.h.
Constructor & Destructor Documentation
UnpackArchiveComponent::UnpackArchiveComponent ()
Definition at line 7 of file UnpackArchiveComponent.cpp.
References EntityComponent::SetName().
UnpackArchiveComponent::~UnpackArchiveComponent () [virtual]
Definition at line 12 of file UnpackArchiveComponent.cpp.
Member Function Documentation
void UnpackArchiveComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 16 of file UnpackArchiveComponent.cpp.
References Entity::GetFunction(), EntityComponent::GetParent(), Variant::GetString(), Variant::GetUINT32(), EntityComponent::GetVar(), Entity::GetVar(), Variant::GetVector2(), and FunctionObject::sig_function.
void UnpackArchiveComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 40 of file UnpackArchiveComponent.cpp.
References RemoveFile().
The documentation for this class was generated from the following files:
UnpackArchiveComponent.h
UnpackArchiveComponent.cpp