Proton: BlinkComponent Class Reference
BlinkComponent Class Reference
#include <BlinkComponent.h>
Public Member Functions
BlinkComponent ()
virtual ~BlinkComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
Detailed Description
Definition at line 17 of file BlinkComponent.h.
Constructor & Destructor Documentation
BlinkComponent::BlinkComponent ()
Definition at line 6 of file BlinkComponent.cpp.
References EntityComponent::SetName().
BlinkComponent::~BlinkComponent () [virtual]
Definition at line 12 of file BlinkComponent.cpp.
Member Function Documentation
void BlinkComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 17 of file BlinkComponent.cpp.
References Entity::GetFunction(), EntityComponent::GetParent(), Variant::GetUINT32(), Entity::GetVarWithDefault(), and FunctionObject::sig_function.
void BlinkComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 28 of file BlinkComponent.cpp.
The documentation for this class was generated from the following files:
BlinkComponent.h
BlinkComponent.cpp