Proton: PMouseEvent Class Reference
PMouseEvent Class Reference
#include <PPlotInteraction.h>
Public Types
enum EType { kNone, kDown, kUp, kMove }
Public Member Functions
PMouseEvent (int inX=0, int inY=0, EType inType=kNone, int inModifierKeys=0)
bool IsNone () const
bool IsMouseDown () const
bool IsMouseUp () const
bool IsMouseMove () const
Public Attributes
int mX
int mY
EType mType
Detailed Description
Definition at line 48 of file PPlotInteraction.h.
Member Enumeration Documentation
enum PMouseEvent::EType
Enumerator:
kNone
kDown
kUp
kMove
Definition at line 50 of file PPlotInteraction.h.
Constructor & Destructor Documentation
PMouseEvent::PMouseEvent (int inX = 0, int inY = 0, EType inType = kNone, int inModifierKeys = 0)
Definition at line 32 of file PPlotInteraction.cpp.
Member Function Documentation
bool PMouseEvent::IsMouseDown () const [inline]
Definition at line 66 of file PPlotInteraction.h.
References kDown, and mType.
Referenced by PZoomInteraction::HandleMouseEvent(), PSelectionInteraction::HandleMouseEvent(), and PCrosshairInteraction::HandleMouseEvent().
bool PMouseEvent::IsMouseMove () const [inline]
Definition at line 68 of file PPlotInteraction.h.
References kMove, and mType.
Referenced by PZoomInteraction::HandleMouseEvent(), and PCrosshairInteraction::HandleMouseEvent().
bool PMouseEvent::IsMouseUp () const [inline]
Definition at line 67 of file PPlotInteraction.h.
References kUp, and mType.
Referenced by PZoomInteraction::HandleMouseEvent(), and PCrosshairInteraction::HandleMouseEvent().
bool PMouseEvent::IsNone () const [inline]
Definition at line 65 of file PPlotInteraction.h.
References kNone, and mType.
Member Data Documentation
EType PMouseEvent::mType
Definition at line 63 of file PPlotInteraction.h.
Referenced by IsMouseDown(), IsMouseMove(), IsMouseUp(), and IsNone().
int PMouseEvent::mX
Definition at line 59 of file PPlotInteraction.h.
Referenced by PSelectionInteraction::CalculateDistanceToPlot(), PZoomInteraction::HandleMouseEvent(), and PCrosshairInteraction::HandleMouseEvent().
int PMouseEvent::mY
Definition at line 60 of file PPlotInteraction.h.
Referenced by PSelectionInteraction::CalculateDistanceToPlot(), and PZoomInteraction::HandleMouseEvent().
The documentation for this class was generated from the following files:
PPlotInteraction.h
PPlotInteraction.cpp