Proton: DPadComponent Class Reference
DPadComponent Class Reference
#include <DPadComponent.h>
Public Member Functions
DPadComponent ()
virtual ~DPadComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
Detailed Description
Definition at line 38 of file DPadComponent.h.
Constructor & Destructor Documentation
DPadComponent::DPadComponent ()
Definition at line 38 of file DPadComponent.cpp.
References EntityComponent::SetName().
DPadComponent::~DPadComponent () [virtual]
Definition at line 43 of file DPadComponent.cpp.
Member Function Documentation
void DPadComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 47 of file DPadComponent.cpp.
References Entity::AddComponent(), AddInputMovementFocusIfNeeded(), ALIGNMENT_CENTER, CreateOverlayEntity(), FadeEntity(), FileExists(), GetFileManager(), Variant::GetFloat(), Entity::GetFunction(), EntityComponent::GetParent(), Variant::GetRect(), Variant::GetSigOnChanged, Variant::GetString(), GetTick(), Entity::GetVar(), EntityComponent::GetVarWithDefault(), Entity::GetVarWithDefault(), Variant::GetVector2(), LogMsg(), Variant::Set(), SetAlignmentEntity(), SetAlphaEntity(), FunctionObject::sig_function, and TIMER_SYSTEM.
void DPadComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 119 of file DPadComponent.cpp.
The documentation for this class was generated from the following files:
DPadComponent.h
DPadComponent.cpp