Proton: VideoModeSelector Class Reference
VideoModeSelector Class Reference
A class that can be used to select a video mode.
#include <VideoModeSelector.h>
Public Member Functions
VideoModeSelector ()
const VideoMode * getNamedMode (const std::string &name) const
Requests a named video mode and returns it.
const std::vector< std::string > & getModeNames () const
Gets all the video mode names currently available in this selector.
std::string modesAsString () const
Returns a string representation of the video modes currently available in this selector.
Detailed Description
A class that can be used to select a video mode.
Provides a number of video modes that are usable on the platform.
Definition at line 60 of file VideoModeSelector.h.
Constructor & Destructor Documentation
VideoModeSelector::VideoModeSelector ()
Definition at line 125 of file VideoModeSelector.cpp.
Member Function Documentation
const vector< string > & VideoModeSelector::getModeNames () const
Gets all the video mode names currently available in this selector.
Definition at line 141 of file VideoModeSelector.cpp.
Referenced by modesAsString().
const VideoMode * VideoModeSelector::getNamedMode (const std::string & name) const
Requests a named video mode and returns it.
If the requested mode can't be found returns NULL.
Definition at line 130 of file VideoModeSelector.cpp.
Referenced by main(), and modesAsString().
string VideoModeSelector::modesAsString () const
Returns a string representation of the video modes currently available in this selector.
The string representation includes the video mode names as well as details about them. The returned string is suitable for showing to the user.
Definition at line 146 of file VideoModeSelector.cpp.
References getModeNames(), getNamedMode(), VideoMode::getOrientationMode(), VideoMode::getPlatformID(), VideoMode::getX(), VideoMode::getY(), OrientationAsStringDisplay(), PlatformIDAsStringDisplay(), and toString().
Referenced by main().
The documentation for this class was generated from the following files:
VideoModeSelector.h
VideoModeSelector.cpp