Proton: PlotDataSelection Class Reference
PlotDataSelection Class Reference
#include <pplot.h>
Public Member Functions
PlotDataSelection (long inSize=0)
bool IsSelected (long inIndex) const
long GetSelectedCount () const
Detailed Description
Definition at line 161 of file pplot.h.
Constructor & Destructor Documentation
PlotDataSelection::PlotDataSelection (long inSize = 0) [inline]
Definition at line 163 of file pplot.h.
Member Function Documentation
long PlotDataSelection::GetSelectedCount () const
Definition at line 133 of file PPlot.cpp.
Referenced by PDeleteInteraction::HandleDeleteKey(), and PVerticalCursorInteraction::HandleVerticalCursorKey().
bool PlotDataSelection::IsSelected (long inIndex) const
Definition at line 126 of file PPlot.cpp.
Referenced by LineDataDrawer::DrawData(), PDeleteInteraction::HandleDeleteKey(), and PVerticalCursorInteraction::HandleVerticalCursorKey().
The documentation for this class was generated from the following files:
pplot.h
PPlot.cpp