Proton: AdProviderChartBoost Class Reference
AdProviderChartBoost Class Reference
#include <AdProviderChartBoost.h>
Public Member Functions
AdProviderChartBoost ()
virtual ~AdProviderChartBoost ()
virtual bool OnAddToManager (AdManager *pAdManager)
virtual string GetName ()
virtual void Update ()
virtual bool OnMessage (Message &m)
virtual void ShowInterstitial (std::string location="", std::string parm2="", std::string parm3="")
virtual void CacheShowInterstitial (std::string location="", std::string parm2="", std::string parm3="")
virtual void ShowMoreApps (std::string location="", std::string parm2="", std::string parm3="")
virtual void CacheShowMoreApps (std::string location="", std::string parm2="", std::string parm3="")
void SetupInfo (const string appID, const string appSignature)
Protected Attributes
string m_appID
string m_appSignature
Detailed Description
Definition at line 34 of file AdProviderChartBoost.h.
Constructor & Destructor Documentation
AdProviderChartBoost::AdProviderChartBoost ()
Definition at line 9 of file AdProviderChartBoost.cpp.
References AD_PROVIDER_CHARTBOOST, and AdProvider::m_adProviderType.
AdProviderChartBoost::~AdProviderChartBoost () [virtual]
Definition at line 14 of file AdProviderChartBoost.cpp.
Member Function Documentation
void AdProviderChartBoost::CacheShowInterstitial (std::string location = "", std::string parm2 = "", std::string parm3 = "") [virtual]
Reimplemented from AdProvider.
Definition at line 69 of file AdProviderChartBoost.cpp.
References BaseApp::AddOSMessage(), ChartBoostIOS_CacheShowInterstitial(), GetBaseApp(), LogMsg(), OSMessage::m_string, OSMessage::m_type, and OSMessage::MESSAGE_CHARTBOOST_CACHE_INTERSTITIAL.
void AdProviderChartBoost::CacheShowMoreApps (std::string location = "", std::string parm2 = "", std::string parm3 = "") [virtual]
Reimplemented from AdProvider.
Definition at line 98 of file AdProviderChartBoost.cpp.
References BaseApp::AddOSMessage(), ChartBoostIOS_CacheShowMoreApps(), GetBaseApp(), OSMessage::m_string, OSMessage::m_type, and OSMessage::MESSAGE_CHARTBOOST_CACHE_MORE_APPS.
virtual string AdProviderChartBoost::GetName () [inline, virtual]
Implements AdProvider.
Definition at line 42 of file AdProviderChartBoost.h.
bool AdProviderChartBoost::OnAddToManager (AdManager * pAdManager) [virtual]
Implements AdProvider.
Definition at line 18 of file AdProviderChartBoost.cpp.
References BaseApp::AddOSMessage(), ChartBoostIOS_StartSession(), GetBaseApp(), LogError(), LogMsg(), m_appID, m_appSignature, OSMessage::m_string, OSMessage::m_string2, OSMessage::m_type, and OSMessage::MESSAGE_CHARTBOOST_SETUP.
bool AdProviderChartBoost::OnMessage (Message & m) [virtual]
Reimplemented from AdProvider.
Definition at line 112 of file AdProviderChartBoost.cpp.
void AdProviderChartBoost::SetupInfo (const string appID, const string appSignature)
Definition at line 47 of file AdProviderChartBoost.cpp.
References m_appID, and m_appSignature.
void AdProviderChartBoost::ShowInterstitial (std::string location = "", std::string parm2 = "", std::string parm3 = "") [virtual]
Reimplemented from AdProvider.
Definition at line 53 of file AdProviderChartBoost.cpp.
References BaseApp::AddOSMessage(), ChartBoostIOS_ShowInterstitial(), GetBaseApp(), LogMsg(), OSMessage::m_string, OSMessage::m_type, and OSMessage::MESSAGE_CHARTBOOST_SHOW_INTERSTITIAL.
void AdProviderChartBoost::ShowMoreApps (std::string location = "", std::string parm2 = "", std::string parm3 = "") [virtual]
Reimplemented from AdProvider.
Definition at line 85 of file AdProviderChartBoost.cpp.
References BaseApp::AddOSMessage(), ChartBoostIOS_ShowMoreApps(), GetBaseApp(), OSMessage::m_string, OSMessage::m_type, and OSMessage::MESSAGE_CHARTBOOST_SHOW_MORE_APPS.
void AdProviderChartBoost::Update () [virtual]
Implements AdProvider.
Definition at line 43 of file AdProviderChartBoost.cpp.
Member Data Documentation
string AdProviderChartBoost::m_appID [protected]
Definition at line 57 of file AdProviderChartBoost.h.
Referenced by OnAddToManager(), and SetupInfo().
string AdProviderChartBoost::m_appSignature [protected]
Definition at line 58 of file AdProviderChartBoost.h.
Referenced by OnAddToManager(), and SetupInfo().
The documentation for this class was generated from the following files:
AdProviderChartBoost.h
AdProviderChartBoost.cpp