Proton: RandomAudioPlayerComponent Class Reference
RandomAudioPlayerComponent Class Reference
A component that plays audio files randomly.
#include <RandomAudioPlayerComponent.h>
Public Member Functions
RandomAudioPlayerComponent ()
virtual ~RandomAudioPlayerComponent ()
virtual void OnAdd (Entity *pEnt)
Detailed Description
A component that plays audio files randomly.
The name of the component is initially set to "RandomAudioPlayer".
The component is given a list of audio file names where it chooses one at a time randomly and plays it. The interval of the playing can be adjusted with minimum and maximum boundaries. The component doesn't play the same audio file twice in a row (given that there are more than one sound files to be played).
Note:
When the component is destroyed it does not stop any currently playing sounds.
The following named variants are used inside the component itself:
"audioFiles" (string): a list of audio file names separated with colons (:). The format for the file names is the same what AudioManager::Play() accepts. This component doesn't check if the files are found nor whether the audio player manages to play them successfully. By default the list is empty so no sounds are played.
"minDelayBetweenPlays" (uint32): sets the minimum delay between the playing of the sounds in milliseconds. Default is 1000ms (1 second).
"maxDelayBetweenPlays" (uint32): sets the maximum delay between the playing of the sounds in milliseconds. Default is 2000ms (2 seconds).
"disabled" (uint32): if 0, the component is enabled and it plays sounds. All other values disable the component. The default is 0, so the component is enabled.
Definition at line 30 of file RandomAudioPlayerComponent.h.
Constructor & Destructor Documentation
RandomAudioPlayerComponent::RandomAudioPlayerComponent ()
Definition at line 8 of file RandomAudioPlayerComponent.cpp.
References EntityComponent::SetName().
RandomAudioPlayerComponent::~RandomAudioPlayerComponent () [virtual]
Definition at line 12 of file RandomAudioPlayerComponent.cpp.
Member Function Documentation
void RandomAudioPlayerComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 15 of file RandomAudioPlayerComponent.cpp.
References EntityComponent::GetFunction(), Variant::GetSigOnChanged, Variant::GetUINT32(), EntityComponent::GetVar(), EntityComponent::GetVarWithDefault(), and FunctionObject::sig_function.
The documentation for this class was generated from the following files:
RandomAudioPlayerComponent.h
RandomAudioPlayerComponent.cpp