Proton: EntityComponent Class Reference
EntityComponent Class Reference
#include <Component.h>
Public Member Functions
EntityComponent ()
virtual ~EntityComponent ()
EntityComponent (string name)
void SetName (string name)
string GetName ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
Entity * GetParent ()
VariantDB * GetShared ()
Variant * GetVar (string const &varName)
Variant * GetVarWithDefault (const string &varName, const Variant &var)
FunctionObject * GetFunction (const string &funcName)
Detailed Description
Definition at line 24 of file Component.h.
Constructor & Destructor Documentation
EntityComponent::EntityComponent ()
Definition at line 4 of file Component.cpp.
EntityComponent::~EntityComponent () [virtual]
Definition at line 9 of file Component.cpp.
References OnRemove().
EntityComponent::EntityComponent (string name)
Definition at line 16 of file Component.cpp.
References SetName().
Member Function Documentation
FunctionObject* EntityComponent::GetFunction (const string & funcName) [inline]
Definition at line 39 of file Component.h.
References VariantDB::GetFunction().
Referenced by ActivateTextInputEntity(), AddFocusIfNeeded(), AddInputMovementFocusIfNeeded(), AddKeyBinding(), Gamepad::ConnectToArcadeComponent(), EnableRawMessageFocusInput(), HTTPComponent::OnAdd(), TapSequenceDetectComponent::OnAdd(), TouchDragComponent::OnAdd(), RandomAudioPlayerComponent::OnAdd(), LogDisplayComponent::OnAdd(), FocusInputComponent::OnAdd(), OverlayRenderComponent::OnAdd(), InputTextRenderComponent::OnAdd(), ScrollComponent::OnAdd(), ArcadeInputComponent::OnAdd(), InterpolateComponent::OnVarNameChanged(), SetScrollProgressEntity(), Message::SetTargetComponent(), SetupAnimEntity(), and InputTextRenderComponent::~InputTextRenderComponent().
string EntityComponent::GetName () [inline]
Definition at line 32 of file Component.h.
Referenced by GetUsedTextures(), MorphToFloatComponent(), MorphToVec2Component(), and InterpolateComponent::OnVarNameChanged().
Entity* EntityComponent::GetParent () [inline]
Definition at line 35 of file Component.h.
Referenced by MorphToFloatComponent(), MorphToVec2Component(), SelectButtonWithCustomInputComponent::OnAdd(), HTTPComponent::OnAdd(), SliderComponent::OnAdd(), BlinkComponent::OnAdd(), TapSequenceDetectComponent::OnAdd(), TemplateComponent::OnAdd(), FilterComponent::OnAdd(), TextRenderComponent::OnAdd(), FilterInputComponent::OnAdd(), ProgressBarComponent::OnAdd(), UnderlineRenderComponent::OnAdd(), UnpackArchiveComponent::OnAdd(), RenderClipComponent::OnAdd(), RenderScissorComponent::OnAdd(), InterpolateComponent::OnAdd(), RectRenderComponent::OnAdd(), TouchStripComponent::OnAdd(), TyperComponent::OnAdd(), TouchHandlerArcadeComponent::OnAdd(), EmitVirtualKeyComponent::OnAdd(), EmitVirtualKeyComponentAdvanced::OnAdd(), TouchDragComponent::OnAdd(), TrailRenderComponent::OnAdd(), TextBoxRenderComponent::OnAdd(), DPadComponent::OnAdd(), ScrollBarRenderComponent::OnAdd(), LogDisplayComponent::OnAdd(), InputTextRenderComponent::OnAdd(), OverlayRenderComponent::OnAdd(), CustomInputComponent::OnAdd(), SpriteAnimationRenderComponent::OnAdd(), Button2DComponent::OnAdd(), TouchHandlerComponent::OnAdd(), SplashComponent::OnAdd(), ScrollComponent::OnAdd(), ArcadeInputComponent::OnAdd(), TouchHandlerArcadeComponent::OnInput(), TouchDragComponent::OnInput(), FocusInputComponent::OnInput(), FocusInputComponent::OnInputRaw(), RenderScissorComponent::OnRemove(), FilterInputComponent::OnRemove(), FilterComponent::OnRemove(), RenderClipComponent::OnRemove(), FocusUpdateComponent::OnUpdate(), InterpolateComponent::OnUpdate(), TyperComponent::OnUpdate(), InterpolateComponent::OnVarNameChanged(), Message::SetComponentToAdd(), and InputTextRenderComponent::~InputTextRenderComponent().
VariantDB* EntityComponent::GetShared () [inline]
Definition at line 36 of file Component.h.
Referenced by InterpolateComponent::OnAdd(), and OnRemove().
Variant* EntityComponent::GetVar (string const & varName) [inline]
Definition at line 37 of file Component.h.
References VariantDB::GetVar().
Referenced by AddFilter(), AddHotKeyToButton(), AddInputMovementFocusIfNeeded(), AnimateEntity(), AnimateEntitySetMirrorMode(), AnimateStopEntity(), AnimateStopEntityAndSetFrame(), BobEntity(), CreateButtonHotspot(), CreateInputTextEntity(), CreateLogDisplayEntity(), CreateOverlayEntity(), CreateOverlayRectEntity(), CreateScrollingTextBoxEntity(), CreateSlider(), CreateTextBoxEntity(), CreateTextLabelEntity(), DisableAllButtonsEntity(), DisableComponentByName(), DisableEntityButtonByName(), DisableHorizontalScrolling(), EnableAllButtonsEntity(), EnableComponentByName(), EnableEntityButtonByName(), FlashOnceEntity(), FlashStartEntity(), GetFilterSetting(), GetOverlayImageEntity(), GetScrollProgressEntity(), GetUsedTextures(), IsDisabledEntity(), MakeButtonEmitVirtualGameKey(), MorphToFloatComponent(), MorphToVec2Component(), SelectButtonWithCustomInputComponent::OnAdd(), SliderComponent::OnAdd(), ProgressBarComponent::OnAdd(), TextRenderComponent::OnAdd(), UnpackArchiveComponent::OnAdd(), FilterComponent::OnAdd(), FilterInputComponent::OnAdd(), InterpolateComponent::OnAdd(), RectRenderComponent::OnAdd(), TouchStripComponent::OnAdd(), EmitVirtualKeyComponentAdvanced::OnAdd(), EmitVirtualKeyComponent::OnAdd(), RandomAudioPlayerComponent::OnAdd(), TouchDragComponent::OnAdd(), TextBoxRenderComponent::OnAdd(), ScrollBarRenderComponent::OnAdd(), LogDisplayComponent::OnAdd(), FocusInputComponent::OnAdd(), OverlayRenderComponent::OnAdd(), InputTextRenderComponent::OnAdd(), CustomInputComponent::OnAdd(), SpriteAnimationRenderComponent::OnAdd(), Button2DComponent::OnAdd(), ScrollComponent::OnAdd(), ArcadeInputComponent::OnAdd(), OneTimeBobEntity(), TyperComponent::OnUpdate(), InterpolateComponent::OnVarNameChanged(), ResizeScrollBounds(), SpriteAnimationUtils::SetAnimationName(), SetButtonClickSound(), SetButtonRepeatDelayMS(), SetButtonStyleEntity(), SetButtonVisualStyleEntity(), SetConsole(), SetEntityOverlayToUnloadImageOnKill(), SetFilterSetting(), SetOverlayImageEntity(), SetProgressBarPercent(), SetTextEntity(), SetTextEntityByName(), SetTextShadowColor(), SpriteAnimationUtils::SetupAnimationEntity(), SetupAnimEntity(), SetupInterpolateComponent(), SetupTextEntity(), SpriteAnimationUtils::StartAnimationEntity(), TypeTextLabelEntity(), and OverlayRenderComponent::~OverlayRenderComponent().
Variant* EntityComponent::GetVarWithDefault (const string & varName, const Variant & var) [inline]
Definition at line 38 of file Component.h.
References VariantDB::GetVarWithDefault().
Referenced by SelectButtonWithCustomInputComponent::OnAdd(), SliderComponent::OnAdd(), FilterComponent::OnAdd(), TextRenderComponent::OnAdd(), FilterInputComponent::OnAdd(), ProgressBarComponent::OnAdd(), InterpolateComponent::OnAdd(), RectRenderComponent::OnAdd(), TouchStripComponent::OnAdd(), TyperComponent::OnAdd(), TouchHandlerArcadeComponent::OnAdd(), EmitVirtualKeyComponentAdvanced::OnAdd(), TouchDragComponent::OnAdd(), RandomAudioPlayerComponent::OnAdd(), TrailRenderComponent::OnAdd(), TextBoxRenderComponent::OnAdd(), DPadComponent::OnAdd(), LogDisplayComponent::OnAdd(), OverlayRenderComponent::OnAdd(), InputTextRenderComponent::OnAdd(), CustomInputComponent::OnAdd(), SpriteAnimationRenderComponent::OnAdd(), Button2DComponent::OnAdd(), ScrollComponent::OnAdd(), and ArcadeInputComponent::OnAdd().
void EntityComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented in ArcadeInputComponent, ScrollComponent, SplashComponent, Button2DComponent, TouchHandlerComponent, SpriteAnimationRenderComponent, CustomInputComponent, InputTextRenderComponent, OverlayRenderComponent, FocusInputComponent, LogDisplayComponent, ScrollBarRenderComponent, DPadComponent, TextBoxRenderComponent, TrailRenderComponent, RandomAudioPlayerComponent, TouchDragComponent, EmitVirtualKeyComponent, EmitVirtualKeyComponentAdvanced, TouchHandlerArcadeComponent, TouchStripComponent, TyperComponent, RectRenderComponent, InterpolateComponent, BlinkComponent, FilterComponent, FilterInputComponent, FocusRenderComponent, ProgressBarComponent, RenderClipComponent, RenderScissorComponent, TapSequenceDetectComponent, TemplateComponent, TextRenderComponent, UnderlineRenderComponent, UnpackArchiveComponent, FocusUpdateComponent, HTTPComponent, SliderComponent, and SelectButtonWithCustomInputComponent.
Definition at line 25 of file Component.cpp.
Referenced by Entity::AddComponent().
void EntityComponent::OnRemove () [virtual]
Reimplemented in ArcadeInputComponent, ScrollComponent, SplashComponent, Button2DComponent, TouchHandlerComponent, CustomInputComponent, InputTextRenderComponent, OverlayRenderComponent, FocusInputComponent, LogDisplayComponent, ScrollBarRenderComponent, DPadComponent, TextBoxRenderComponent, TrailRenderComponent, TouchDragComponent, EmitVirtualKeyComponent, EmitVirtualKeyComponentAdvanced, TouchHandlerArcadeComponent, TouchStripComponent, TyperComponent, RectRenderComponent, InterpolateComponent, BlinkComponent, FilterComponent, FilterInputComponent, FocusRenderComponent, ProgressBarComponent, RenderClipComponent, RenderScissorComponent, TapSequenceDetectComponent, TemplateComponent, TextRenderComponent, UnderlineRenderComponent, UnpackArchiveComponent, FocusUpdateComponent, HTTPComponent, SliderComponent, and SelectButtonWithCustomInputComponent.
Definition at line 30 of file Component.cpp.
References VariantDB::GetFunctionIfExists(), GetShared(), and FunctionObject::sig_function.
Referenced by ~EntityComponent().
void EntityComponent::SetName (string name)
Definition at line 20 of file Component.cpp.
Referenced by AnimateEntity(), ArcadeInputComponent::ArcadeInputComponent(), BlinkComponent::BlinkComponent(), Button2DComponent::Button2DComponent(), CustomInputComponent::CustomInputComponent(), DPadComponent::DPadComponent(), EmitVirtualKeyComponent::EmitVirtualKeyComponent(), EmitVirtualKeyComponentAdvanced::EmitVirtualKeyComponentAdvanced(), EntityComponent(), FadeEntity(), FilterComponent::FilterComponent(), FilterInputComponent::FilterInputComponent(), FocusInputComponent::FocusInputComponent(), FocusRenderComponent::FocusRenderComponent(), FocusUpdateComponent::FocusUpdateComponent(), HTTPComponent::HTTPComponent(), InputTextRenderComponent::InputTextRenderComponent(), InterpolateComponent::InterpolateComponent(), LogDisplayComponent::LogDisplayComponent(), MorphToColorEntity(), MorphToVec2EntityMulti(), FilterComponent::OnAdd(), OverlayRenderComponent::OverlayRenderComponent(), ProgressBarComponent::ProgressBarComponent(), RandomAudioPlayerComponent::RandomAudioPlayerComponent(), RectRenderComponent::RectRenderComponent(), RenderClipComponent::RenderClipComponent(), RenderScissorComponent::RenderScissorComponent(), ScaleEntity(), ScrollBarRenderComponent::ScrollBarRenderComponent(), ScrollComponent::ScrollComponent(), SelectButtonWithCustomInputComponent::SelectButtonWithCustomInputComponent(), SetupInterpolateComponent(), SliderComponent::SliderComponent(), SplashComponent::SplashComponent(), SpriteAnimationRenderComponent::SpriteAnimationRenderComponent(), SpriteAnimationUtils::StartAnimationEntity(), TapSequenceDetectComponent::TapSequenceDetectComponent(), TemplateComponent::TemplateComponent(), TextBoxRenderComponent::TextBoxRenderComponent(), TextRenderComponent::TextRenderComponent(), TouchDragComponent::TouchDragComponent(), TouchHandlerArcadeComponent::TouchHandlerArcadeComponent(), TouchHandlerComponent::TouchHandlerComponent(), TouchStripComponent::TouchStripComponent(), TrailRenderComponent::TrailRenderComponent(), TyperComponent::TyperComponent(), UnderlineRenderComponent::UnderlineRenderComponent(), UnpackArchiveComponent::UnpackArchiveComponent(), and ZoomToPositionEntityMulti().
The documentation for this class was generated from the following files:
Component.h
Component.cpp