Proton: CheckResult Class Reference
CheckResult Class Reference
#include <ProtonTester-internal.h>
Public Types
enum Result { PASS, FAIL }
Public Member Functions
template<typename T >
CheckResult (const CheckLocation &testLocation, Result result, const std::string &expectedStr, const T &expected, const std::string &actualStr, const T &actual)
std::string GetTestName () const
Result GetResult () const
std::string GetResultString () const
template<>
std::string valueToString (const bool &value)
Detailed Description
Definition at line 20 of file ProtonTester-internal.h.
Member Enumeration Documentation
enum CheckResult::Result
Enumerator:
PASS
FAIL
Definition at line 23 of file ProtonTester-internal.h.
Constructor & Destructor Documentation
template<typename T > CheckResult::CheckResult (const CheckLocation & testLocation, Result result, const std::string & expectedStr, const T & expected, const std::string & actualStr, const T & actual) [inline]
Definition at line 29 of file ProtonTester-internal.h.
Member Function Documentation
CheckResult::Result CheckResult::GetResult () const
Definition at line 19 of file ProtonTester.cpp.
Referenced by TestResults::add().
std::string CheckResult::GetResultString () const
Definition at line 24 of file ProtonTester.cpp.
Referenced by TestResults::add().
std::string CheckResult::GetTestName () const
Definition at line 14 of file ProtonTester.cpp.
Referenced by TestResults::add().
std::string CheckResult::valueToString (const bool & value)
Definition at line 9 of file ProtonTester.cpp.
The documentation for this class was generated from the following files:
ProtonTester-internal.h
ProtonTester.cpp