Proton: FileCopier Class Reference
FileCopier Class Reference
#include <FileCopier.h>
Public Types
enum eStatus { STATUS_OK, STATUS_FINISHED, STATUS_ERROR_GENERIC, STATUS_ERROR_LOW_SPACE }
Public Member Functions
FileCopier ()
virtual ~FileCopier ()
bool Init (string fileNameSource, string fileNameDest)
bool InitAndCopy (string fileNameSource, string fileNameDest)
bool Update (int maxBytesToWrite)
eStatus GetStatus ()
Protected Attributes
FILE * m_destFP
StreamingInstance * m_pSrcStreamInstance
eStatus m_status
int m_sourceSizeBytes
string m_destFileName
byte m_buffer [FILE_COPY_BUFFER_SIZE]
Detailed Description
Definition at line 55 of file FileCopier.h.
Member Enumeration Documentation
enum FileCopier::eStatus
Enumerator:
STATUS_OK
STATUS_FINISHED
STATUS_ERROR_GENERIC
STATUS_ERROR_LOW_SPACE
Definition at line 61 of file FileCopier.h.
Constructor & Destructor Documentation
FileCopier::FileCopier ()
Definition at line 7 of file FileCopier.cpp.
References m_destFP, m_pSrcStreamInstance, m_status, and STATUS_OK.
FileCopier::~FileCopier () [virtual]
Definition at line 14 of file FileCopier.cpp.
References m_destFileName, m_destFP, m_status, RemoveFile(), and STATUS_FINISHED.
Member Function Documentation
eStatus FileCopier::GetStatus () [inline]
Definition at line 72 of file FileCopier.h.
References m_status.
bool FileCopier::Init (string fileNameSource, string fileNameDest)
Definition at line 27 of file FileCopier.cpp.
References GetFileManager(), FileManager::GetStreaming(), LogError(), LogMsg(), m_destFileName, m_destFP, m_pSrcStreamInstance, m_sourceSizeBytes, m_status, and STATUS_ERROR_GENERIC.
Referenced by InitAndCopy().
bool FileCopier::InitAndCopy (string fileNameSource, string fileNameDest)
Definition at line 93 of file FileCopier.cpp.
References FILE_COPY_BUFFER_SIZE, Init(), LogMsg(), m_status, STATUS_FINISHED, and Update().
bool FileCopier::Update (int maxBytesToWrite)
Definition at line 60 of file FileCopier.cpp.
References FILE_COPY_BUFFER_SIZE, m_buffer, m_destFP, m_pSrcStreamInstance, m_status, StreamingInstance::Read(), STATUS_ERROR_LOW_SPACE, and STATUS_FINISHED.
Referenced by InitAndCopy().
Member Data Documentation
byte FileCopier::m_buffer[FILE_COPY_BUFFER_SIZE] [protected]
Definition at line 84 of file FileCopier.h.
Referenced by Update().
string FileCopier::m_destFileName [protected]
Definition at line 83 of file FileCopier.h.
Referenced by Init(), and ~FileCopier().
FILE* FileCopier::m_destFP [protected]
Definition at line 79 of file FileCopier.h.
Referenced by FileCopier(), Init(), Update(), and ~FileCopier().
StreamingInstance* FileCopier::m_pSrcStreamInstance [protected]
Definition at line 80 of file FileCopier.h.
Referenced by FileCopier(), Init(), and Update().
int FileCopier::m_sourceSizeBytes [protected]
Definition at line 82 of file FileCopier.h.
Referenced by Init().
eStatus FileCopier::m_status [protected]
Definition at line 81 of file FileCopier.h.
Referenced by FileCopier(), GetStatus(), Init(), InitAndCopy(), Update(), and ~FileCopier().
The documentation for this class was generated from the following files:
FileCopier.h
FileCopier.cpp