Proton: TextScanner Class Reference
TextScanner Class Reference
#include <TextScanner.h>
Public Member Functions
TextScanner ()
TextScanner (const char *pCharArray)
TextScanner (const string &fName)
TextScanner (const string &fName, bool bAddBasePath)
~TextScanner ()
void Kill ()
bool LoadFile (const string &fName, bool bAddBasePath=true)
bool SaveFile (const string &fName, bool bAddBasePath=true)
string GetParmString (string label, int index, string token="|")
string GetParmStringFromLine (int lineNum, int index, string token="|")
int GetParmIntFromLine (int lineNum, int index, string token="|")
float GetParmFloatFromLine (int lineNum, int index, string token="|")
string GetMultipleLineStrings (string label, string token="|")
string GetLine (int lineNum)
void Replace (const string &thisStr, const string &thatStr)
bool IsLoaded ()
bool SetupFromMemoryAddress (const char *pCharArray)
void DeleteLine (int lineNum)
void StripLeadingSpaces ()
string GetAll ()
int GetLineCount ()
void DumpToLog ()
vector< string > TokenizeLine (int lineNum, const string &theDelimiter="|")
void AppendToFile (string fileName, bool bAddBasePath=true)
Public Attributes
vector< string > m_lines
Detailed Description
Definition at line 46 of file TextScanner.h.
Constructor & Destructor Documentation
TextScanner::TextScanner ()
Definition at line 7 of file TextScanner.cpp.
TextScanner::TextScanner (const char * pCharArray)
Definition at line 24 of file TextScanner.cpp.
References SetupFromMemoryAddress().
TextScanner::TextScanner (const string & fName)
Definition at line 12 of file TextScanner.cpp.
References LoadFile().
TextScanner::TextScanner (const string & fName, bool bAddBasePath)
Definition at line 18 of file TextScanner.cpp.
References LoadFile().
TextScanner::~TextScanner ()
Definition at line 75 of file TextScanner.cpp.
References Kill().
Member Function Documentation
void TextScanner::AppendToFile (string fileName, bool bAddBasePath = true)
Definition at line 218 of file TextScanner.cpp.
References GetBaseAppPath(), GetPlatformID(), m_lines, and PLATFORM_ID_LINUX.
void TextScanner::DeleteLine (int lineNum)
Definition at line 207 of file TextScanner.cpp.
References m_lines.
void TextScanner::DumpToLog ()
Definition at line 167 of file TextScanner.cpp.
References GetLineCount(), LogMsg(), m_lines, and StringReplace().
string TextScanner::GetAll ()
Definition at line 124 of file TextScanner.cpp.
References m_lines, and StripWhiteSpace().
string TextScanner::GetLine (int lineNum)
Definition at line 113 of file TextScanner.cpp.
References m_lines.
int TextScanner::GetLineCount () [inline]
Definition at line 72 of file TextScanner.h.
References m_lines.
Referenced by DumpToLog().
std::string TextScanner::GetMultipleLineStrings (string label, string token = "|")
Definition at line 86 of file TextScanner.cpp.
References m_lines, and StringTokenize().
float TextScanner::GetParmFloatFromLine (int lineNum, int index, string token = "|")
Definition at line 150 of file TextScanner.cpp.
References m_lines, and SeparateStringSTL().
int TextScanner::GetParmIntFromLine (int lineNum, int index, string token = "|")
Definition at line 143 of file TextScanner.cpp.
References m_lines, and SeparateStringSTL().
std::string TextScanner::GetParmString (string label, int index, string token = "|")
Definition at line 53 of file TextScanner.cpp.
References LogError(), m_lines, and StringTokenize().
std::string TextScanner::GetParmStringFromLine (int lineNum, int index, string token = "|")
Definition at line 136 of file TextScanner.cpp.
References m_lines, and SeparateStringSTL().
bool TextScanner::IsLoaded () [inline]
Definition at line 67 of file TextScanner.h.
References m_lines.
void TextScanner::Kill ()
Definition at line 80 of file TextScanner.cpp.
References m_lines.
Referenced by LoadFile(), and ~TextScanner().
bool TextScanner::LoadFile (const string & fName, bool bAddBasePath = true)
Definition at line 31 of file TextScanner.cpp.
References FileInstance::GetAsChars(), FileInstance::IsLoaded(), Kill(), and SetupFromMemoryAddress().
Referenced by TextScanner().
void TextScanner::Replace (const string & thisStr, const string & thatStr)
Definition at line 158 of file TextScanner.cpp.
References m_lines, and StringReplace().
bool TextScanner::SaveFile (const string & fName, bool bAddBasePath = true)
Definition at line 177 of file TextScanner.cpp.
References GetSavePath(), LogError(), and m_lines.
bool TextScanner::SetupFromMemoryAddress (const char * pCharArray)
Definition at line 41 of file TextScanner.cpp.
References m_lines, StringReplace(), and StringTokenize().
Referenced by LoadFile(), and TextScanner().
void TextScanner::StripLeadingSpaces ()
Definition at line 103 of file TextScanner.cpp.
References m_lines, and StripWhiteSpace().
vector< string > TextScanner::TokenizeLine (int lineNum, const string & theDelimiter = "|")
Definition at line 213 of file TextScanner.cpp.
References m_lines, and StringTokenize().
Member Data Documentation
vector<string> TextScanner::m_lines
Definition at line 76 of file TextScanner.h.
Referenced by AppendToFile(), DeleteLine(), DumpToLog(), GetAll(), GetLine(), GetLineCount(), GetMultipleLineStrings(), GetParmFloatFromLine(), GetParmIntFromLine(), GetParmString(), GetParmStringFromLine(), IsLoaded(), Kill(), Replace(), SaveFile(), SetupFromMemoryAddress(), StripLeadingSpaces(), and TokenizeLine().
The documentation for this class was generated from the following files:
TextScanner.h
TextScanner.cpp