Proton: PEditInteraction Class Reference
PEditInteraction Class Reference
#include <PPlotInteraction.h>
Public Member Functions
PEditInteraction (PPlot &inPPlot)
virtual bool HandleMouseEvent (const PMouseEvent &inEvent)
virtual bool HandleKeyEvent (const PKeyEvent &inEvent)
virtual bool ShouldCalculate () const
virtual bool Calculate (Painter &inPainter, PPlot &inPPlot)
virtual bool Impl_HandleKeyEvent (const PKeyEvent &inEvent)=0
virtual bool Impl_Calculate (Painter &inPainter, PPlot &inPPlot)=0
void SetListener (PEditInteractionListener *inListener)
Protected Attributes
PEditInteractionListener * mListener
PKeyEvent mKeyEvent
Detailed Description
Definition at line 245 of file PPlotInteraction.h.
Constructor & Destructor Documentation
PEditInteraction::PEditInteraction (PPlot & inPPlot)
Definition at line 465 of file PPlotInteraction.cpp.
References PPlot::mModifyingCalculatorList.
Member Function Documentation
bool PEditInteraction::Calculate (Painter & inPainter, PPlot & inPPlot) [virtual]
Reimplemented from PCalculator.
Definition at line 480 of file PPlotInteraction.cpp.
References PEditInteractionListener::HandlePEditInteraction(), Impl_Calculate(), and mListener.
bool PEditInteraction::HandleKeyEvent (const PKeyEvent & inEvent) [virtual]
Reimplemented from PPlotInteraction.
Definition at line 473 of file PPlotInteraction.cpp.
References Impl_HandleKeyEvent(), and mKeyEvent.
virtual bool PEditInteraction::HandleMouseEvent (const PMouseEvent & inEvent) [inline, virtual]
Implements PPlotInteraction.
Definition at line 249 of file PPlotInteraction.h.
virtual bool PEditInteraction::Impl_Calculate (Painter & inPainter, PPlot & inPPlot) [pure virtual]
Implemented in PDeleteInteraction, and PVerticalCursorInteraction.
Referenced by Calculate().
virtual bool PEditInteraction::Impl_HandleKeyEvent (const PKeyEvent & inEvent) [pure virtual]
Implemented in PDeleteInteraction, and PVerticalCursorInteraction.
Referenced by HandleKeyEvent().
void PEditInteraction::SetListener (PEditInteractionListener * inListener) [inline]
Definition at line 256 of file PPlotInteraction.h.
References mListener.
virtual bool PEditInteraction::ShouldCalculate () const [inline, virtual]
Reimplemented from PCalculator.
Definition at line 251 of file PPlotInteraction.h.
Member Data Documentation
PKeyEvent PEditInteraction::mKeyEvent [protected]
Definition at line 259 of file PPlotInteraction.h.
Referenced by HandleKeyEvent(), PVerticalCursorInteraction::HandleVerticalCursorKey(), PVerticalCursorInteraction::Impl_Calculate(), and PDeleteInteraction::Impl_Calculate().
PEditInteractionListener* PEditInteraction::mListener [protected]
Definition at line 256 of file PPlotInteraction.h.
Referenced by Calculate(), and SetListener().
The documentation for this class was generated from the following files:
PPlotInteraction.h
PPlotInteraction.cpp