Proton: GamepadProvider Class Reference
GamepadProvider Class Reference
#include <GamepadProvider.h>
Public Member Functions
GamepadProvider ()
virtual ~GamepadProvider ()
virtual string GetName ()=0
virtual bool Init ()=0
virtual void Kill ()=0
virtual void Update ()=0
Public Attributes
boost::signal< void(GamepadProvider *) m_sig_failed_to_connect)
boost::signal< void(GamepadProvider
*, VariantList *) m_sig_status)
Detailed Description
Definition at line 13 of file GamepadProvider.h.
Constructor & Destructor Documentation
GamepadProvider::GamepadProvider ()
Definition at line 4 of file GamepadProvider.cpp.
GamepadProvider::~GamepadProvider () [virtual]
Definition at line 8 of file GamepadProvider.cpp.
Member Function Documentation
virtual string GamepadProvider::GetName () [pure virtual]
Implemented in GamepadProviderDirectX, GamepadProvider60Beat, GamepadProviderMoga, and GamepadProvideriCade.
Referenced by GamepadManager::AddProvider().
virtual bool GamepadProvider::Init () [pure virtual]
Implemented in GamepadProviderDirectX, GamepadProvider60Beat, GamepadProviderMoga, and GamepadProvideriCade.
Referenced by GamepadManager::AddProvider().
virtual void GamepadProvider::Kill () [pure virtual]
Implemented in GamepadProviderDirectX, GamepadProvider60Beat, GamepadProviderMoga, and GamepadProvideriCade.
virtual void GamepadProvider::Update () [pure virtual]
Implemented in GamepadProviderDirectX, GamepadProvider60Beat, GamepadProviderMoga, and GamepadProvideriCade.
Member Data Documentation
boost::signal<void (GamepadProvider*) GamepadProvider::m_sig_failed_to_connect)
Definition at line 23 of file GamepadProvider.h.
Referenced by GamepadProvideriCade::OnLostiCadeConnection().
boost::signal<void (GamepadProvider*, VariantList*) GamepadProvider::m_sig_status)
Definition at line 24 of file GamepadProvider.h.
The documentation for this class was generated from the following files:
GamepadProvider.h
GamepadProvider.cpp