Proton: IrrlichtManager Class Reference
IrrlichtManager Class Reference
#include <IrrlichtManager.h>
Public Member Functions
IrrlichtManager ()
virtual ~IrrlichtManager ()
bool Init (irr::IEventReceiver *pEventReceiver)
void Kill ()
bool IsRunning ()
void BeginScene ()
void Render ()
void EndScene ()
void ClearScene ()
irr::video::ITexture * GetTexture (const std::string &fileName)
irr::IrrlichtDevice * GetDevice ()
irr::video::IVideoDriver * GetDriver ()
irr::scene::ISceneManager * GetScene ()
void Render2D ()
bool GetLightingEnabled ()
void SetLightingEnabled (bool bNew)
bool GetDebugEnabled ()
void SetDebugEnabled (bool bNew)
void SetBulletPhysicsEnabled (bool bNew)
void OnUnloadSurfaces ()
void OnLoadSurfaces ()
irrBulletWorld * GetBulletWorld ()
Detailed Description
Definition at line 33 of file IrrlichtManager.h.
Constructor & Destructor Documentation
IrrlichtManager::IrrlichtManager ()
Definition at line 20 of file IrrlichtManager.cpp.
IrrlichtManager::~IrrlichtManager () [virtual]
Definition at line 35 of file IrrlichtManager.cpp.
Member Function Documentation
void IrrlichtManager::BeginScene ()
Definition at line 147 of file IrrlichtManager.cpp.
References GetBaseApp(), glEnable(), and PrepareForGL().
void IrrlichtManager::ClearScene ()
Definition at line 123 of file IrrlichtManager.cpp.
void IrrlichtManager::EndScene ()
Definition at line 201 of file IrrlichtManager.cpp.
References g_lastBound, glBlendFunc(), glDisable(), and glEnable().
irrBulletWorld* IrrlichtManager::GetBulletWorld () [inline]
Definition at line 64 of file IrrlichtManager.h.
bool IrrlichtManager::GetDebugEnabled () [inline]
Definition at line 57 of file IrrlichtManager.h.
irr::IrrlichtDevice* IrrlichtManager::GetDevice () [inline]
Definition at line 49 of file IrrlichtManager.h.
irr::video::IVideoDriver* IrrlichtManager::GetDriver () [inline]
Definition at line 50 of file IrrlichtManager.h.
Referenced by BaseApp::Draw().
bool IrrlichtManager::GetLightingEnabled () [inline]
Definition at line 54 of file IrrlichtManager.h.
irr::scene::ISceneManager* IrrlichtManager::GetScene () [inline]
Definition at line 51 of file IrrlichtManager.h.
Referenced by IrrHealthBar::Init().
irr::video::ITexture * IrrlichtManager::GetTexture (const std::string & fileName)
Definition at line 117 of file IrrlichtManager.cpp.
References GetBaseAppPath().
bool IrrlichtManager::Init (irr::IEventReceiver * pEventReceiver)
Definition at line 61 of file IrrlichtManager.cpp.
References GetBaseApp(), GetPrimaryGLX(), GetPrimaryGLY(), LogError(), LogMsg(), BaseApp::m_sig_loadSurfaces, BaseApp::m_sig_unloadSurfaces, OnLoadSurfaces(), and OnUnloadSurfaces().
bool IrrlichtManager::IsRunning ()
Definition at line 229 of file IrrlichtManager.cpp.
void IrrlichtManager::Kill ()
Definition at line 41 of file IrrlichtManager.cpp.
void IrrlichtManager::OnLoadSurfaces ()
Definition at line 290 of file IrrlichtManager.cpp.
References LogMsg().
Referenced by Init().
void IrrlichtManager::OnUnloadSurfaces ()
Definition at line 279 of file IrrlichtManager.cpp.
References LogMsg().
Referenced by Init().
void IrrlichtManager::Render ()
Definition at line 185 of file IrrlichtManager.cpp.
void IrrlichtManager::Render2D ()
Definition at line 173 of file IrrlichtManager.cpp.
References RTFont::Draw(), FONT_SMALL, GetBaseApp(), and BaseApp::GetFont().
void IrrlichtManager::SetBulletPhysicsEnabled (bool bNew) [inline]
Definition at line 59 of file IrrlichtManager.h.
void IrrlichtManager::SetDebugEnabled (bool bNew) [inline]
Definition at line 58 of file IrrlichtManager.h.
void IrrlichtManager::SetLightingEnabled (bool bNew) [inline]
Definition at line 55 of file IrrlichtManager.h.
The documentation for this class was generated from the following files:
IrrlichtManager.h
IrrlichtManager.cpp