Proton: InteractionContainer Class Reference
InteractionContainer Class Reference
#include <PPlotInteraction.h>
Public Member Functions
InteractionContainer ()
virtual ~InteractionContainer ()
bool HandleMouseEvent (const PMouseEvent &inEvent)
bool HandleKeyEvent (const PKeyEvent &inEvent)
void AddInteraction (PPlotInteraction &inInteraction)
Protected Attributes
PPlotInteraction::tList mList
Detailed Description
Definition at line 309 of file PPlotInteraction.h.
Constructor & Destructor Documentation
InteractionContainer::InteractionContainer () [inline]
Definition at line 311 of file PPlotInteraction.h.
virtual InteractionContainer::~InteractionContainer () [inline, virtual]
Definition at line 312 of file PPlotInteraction.h.
Member Function Documentation
void InteractionContainer::AddInteraction (PPlotInteraction & inInteraction) [inline]
Definition at line 317 of file PPlotInteraction.h.
Referenced by DefaultInteractionContainer::DefaultInteractionContainer().
bool InteractionContainer::HandleKeyEvent (const PKeyEvent & inEvent)
Definition at line 733 of file PPlotInteraction.cpp.
References PPlotInteraction::HandleKeyEvent(), PPlotInteraction::IsEnabled(), and mList.
bool InteractionContainer::HandleMouseEvent (const PMouseEvent & inEvent)
Definition at line 723 of file PPlotInteraction.cpp.
References PPlotInteraction::HandleMouseEvent(), PPlotInteraction::IsEnabled(), and mList.
Member Data Documentation
PPlotInteraction::tList InteractionContainer::mList [protected]
Definition at line 317 of file PPlotInteraction.h.
Referenced by HandleKeyEvent(), and HandleMouseEvent().
The documentation for this class was generated from the following files:
PPlotInteraction.h
PPlotInteraction.cpp