Proton: FileInstance Class Reference
FileInstance Class Reference
#include <FileManager.h>
Public Member Functions
FileInstance (const std::string &fileName)
FileInstance (const std::string &fileName, bool bAddBasePath)
FileInstance ()
~FileInstance ()
bool IsLoaded ()
byte * GetAsBytes ()
char * GetAsChars ()
int GetSize ()
bool Load (std::string fileName, bool bAddBasePath=true)
Detailed Description
Definition at line 21 of file FileManager.h.
Constructor & Destructor Documentation
FileInstance::FileInstance (const std::string & fileName)
FileInstance::FileInstance (const std::string & fileName, bool bAddBasePath)
FileInstance::FileInstance () [inline]
Definition at line 27 of file FileManager.h.
FileInstance::~FileInstance ()
Definition at line 32 of file FileManager.cpp.
Member Function Documentation
byte* FileInstance::GetAsBytes () [inline]
Definition at line 32 of file FileManager.h.
Referenced by RTFont::Load(), SoftSurface::LoadFile(), Surface::LoadFile(), and SoftSurface::SetPaletteFromBMP().
char* FileInstance::GetAsChars () [inline]
Definition at line 33 of file FileManager.h.
Referenced by TextScanner::LoadFile(), and SpriteAnimationSet::LoadFile().
int FileInstance::GetSize () [inline]
Definition at line 34 of file FileManager.h.
Referenced by Surface::LoadFile().
bool FileInstance::IsLoaded () [inline]
Definition at line 31 of file FileManager.h.
Referenced by RTFont::Load(), Load(), SoftSurface::LoadFile(), TextScanner::LoadFile(), Surface::LoadFile(), SpriteAnimationSet::LoadFile(), and SoftSurface::SetPaletteFromBMP().
bool FileInstance::Load (std::string fileName, bool bAddBasePath = true)
Definition at line 37 of file FileManager.cpp.
References FileManager::Get(), GetFileManager(), and IsLoaded().
Referenced by SoftSurface::SetPaletteFromBMP().
The documentation for this class was generated from the following files:
FileManager.h
FileManager.cpp