Proton: SpriteAnimationRenderComponent Class Reference
SpriteAnimationRenderComponent Class Reference
A component that renders sprite animations.
#include <SpriteAnimationRenderComponent.h>
Public Member Functions
SpriteAnimationRenderComponent ()
virtual ~SpriteAnimationRenderComponent ()
virtual void OnAdd (Entity *pEnt)
Detailed Description
A component that renders sprite animations.
The name of the component is initially set to "SpriteAnimationRender".
The following named variants are used from the parent Entity:
"pos2d" (Vector2): specifies the position. You can move this component by changing this.
"size2d" (Vector2): stores the size of the drawn surface. This is used internally, don't set this. Use "scale2d" instead.
"scale2d" (Vector2): specifies the scale for the drawn surface. Default is (1.0, 1.0).
"rotation" (float): specifies the rotation of the drawn surface. The value is in degrees.
"color" (uint32), "colorMod" (uint32), "alpha" (float): these values are passed to ColorCombine() function and the result specifies a color tint for the drawn surface. See SurfaceAnim::Blit() for specifics how the tinting works. The defaults are pure opaque white for "color" and "colorMod" and 1.0 for "alpha". The defaults are such that the color tinting has no effect on the resulting image.
"visible" (uint32): sets whether the surface is visible or not. 0 means not visible, all other values mean visible. The default value is visible.
The following named variants are used inside the component itself:
"flipX" (uint32), "flipY" (uint32): sets if the drawn frame should be flipped horizontally or vertically. 0 means no flipping, all other values enable the flipping. The defaults are 0.
"fileName" (string): specifies the name of the sprite animation file that is used. See ResourceManager::GetSpriteAnimationSet().
"animationName" (string): specifies the name of the animation this component should draw.
"phase" (float): specifies the phase or progress of the animation. This must be a value between 0.0 and 1.0, inclusive. When "phase" is 0.0 the first frame of the animation is drawn. When "phase" is 1.0 the last frame of the animation is drawn. The values between 0.0 and 1.0 map evenly to the frame numbers of the currently selected animation. The animation can be played back by progressively changing the value of "phase" (with InterpolateComponent for example).
"frameSize2d" (Vector2): a read only variant that contains the unscaled frame size of the current animation. If there is no current animation then this value is (0.0, 0.0). See SpriteAnimation::GetBoundingBox().
Definition at line 52 of file SpriteAnimationRenderComponent.h.
Constructor & Destructor Documentation
SpriteAnimationRenderComponent::SpriteAnimationRenderComponent ()
Definition at line 6 of file SpriteAnimationRenderComponent.cpp.
References EntityComponent::SetName().
SpriteAnimationRenderComponent::~SpriteAnimationRenderComponent () [virtual]
Definition at line 28 of file SpriteAnimationRenderComponent.cpp.
Member Function Documentation
void SpriteAnimationRenderComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 86 of file SpriteAnimationRenderComponent.cpp.
References Variant::GetFloat(), Entity::GetFunction(), EntityComponent::GetParent(), Variant::GetSigOnChanged, Variant::GetString(), Variant::GetUINT32(), EntityComponent::GetVar(), Entity::GetVar(), EntityComponent::GetVarWithDefault(), Entity::GetVarWithDefault(), Variant::GetVector2(), PURE_WHITE, and FunctionObject::sig_function.
The documentation for this class was generated from the following files:
SpriteAnimationRenderComponent.h
SpriteAnimationRenderComponent.cpp