Proton: VariantTuner Class Reference
VariantTuner Class Reference
A class that can be used to change a Variant's value incrementally with the mouse wheel.
#include <VariantTuner.h>
Static Public Member Functions
static void setTunableVariant (Variant &var, const Variant &step)
Sets the Variant that is modified by this tuner.
static void resetTunableVariant ()
Stops modifiying any Variant that is currently set for modification.
Detailed Description
A class that can be used to change a Variant's value incrementally with the mouse wheel.
This is a development helper class that isn't meant to be included in releases. This class might be helpful for example in fine tuning some physics related constant. Pass some Variant that you are trying to find a suitable value for to this class. Then adjust the value incrementally during run time with the mouse wheel and see the effect of different values immediately on the screen. Off course the Variant that is manipulated needs to be used somewhere in the code base so that changing its value has a visible effect. This can be generally acchieved in two ways:
1. either pass a Variant to this class that is directly used by some other instance:
 VariantTuner::setTunableVariant(*myEntity->GetVar("pos2d"), CL_Vec2f(1, 0));
2. or listen to changes in a Variant if it's not directly used in a suitable place:
 // Define a listener method
 void MyListener(Variant *v) {
     someVariableThatNeedsToBeModified->SetWeirdValue(v->GetFloat());
 }
 // In some other part of the code
 static Variant tunable(0.0f);
 tunable.GetSigOnChanged()->connect(boost::bind(&MyListener, _1));
 VariantTuner::setTunableVariant(tunable, 0.1f);
Definition at line 32 of file VariantTuner.h.
Member Function Documentation
void VariantTuner::resetTunableVariant () [static]
Stops modifiying any Variant that is currently set for modification.
Definition at line 103 of file VariantTuner.cpp.
References GetBaseApp(), Entity::GetComponentByName(), and BaseApp::GetEntityRoot().
void VariantTuner::setTunableVariant (Variant & var, const Variant & step) [static]
Sets the Variant that is modified by this tuner.
step sets the amount by which var is modified at a time. The types of var and step must match.
Definition at line 86 of file VariantTuner.cpp.
References Entity::AddComponent(), GetBaseApp(), Entity::GetComponentByName(), and BaseApp::GetEntityRoot().
The documentation for this class was generated from the following files:
VariantTuner.h
VariantTuner.cpp