Proton: Carpenter Class Reference
Carpenter Class Reference
#include <P3DPlot.h>
Public Member Functions
virtual void MakeLine (const PVertex &inVertex1, const PVertex &inVertex2)=0
virtual void MakePolygon (const vector< PVertex > &inVertices)=0
virtual void SetColor (int inR, int inG, int inB)=0
virtual void SetSurfaceNormal (const PVertex &inVertex)=0
virtual void Finish ()=0
Detailed Description
Definition at line 28 of file P3DPlot.h.
Member Function Documentation
virtual void Carpenter::Finish () [pure virtual]
Referenced by P3DPlot::MakeModel().
virtual void Carpenter::MakeLine (const PVertex & inVertex1, const PVertex & inVertex2) [pure virtual]
Referenced by P3DPlot::MakeModel().
virtual void Carpenter::MakePolygon (const vector< PVertex > & inVertices) [pure virtual]
Referenced by P3DPlot::MakeBar(), and P3DPlot::MakePolygonWithOffset().
virtual void Carpenter::SetColor (int inR, int inG, int inB) [pure virtual]
Referenced by P3DPlot::MakeModel().
virtual void Carpenter::SetSurfaceNormal (const PVertex & inVertex) [pure virtual]
Referenced by P3DPlot::MakeBar(), and P3DPlot::MakeModel().
The documentation for this class was generated from the following file:
P3DPlot.h