Proton: GamepadManager Class Reference
GamepadManager Class Reference
#include <GamepadManager.h>
Public Member Functions
GamepadManager ()
virtual ~GamepadManager ()
Gamepad * GetDefaultGamepad ()
eGamepadID GetDefaultGamepadID ()
void Update ()
void SetDefaultGamepad (Gamepad *pPad)
int GetGamepadCount ()
Gamepad * GetGamepad (eGamepadID id)
GamepadProvider * GetProviderByName (string name)
bool RemoveProviderByName (string name)
GamepadProvider * AddProvider (GamepadProvider *provider)
void AddGamepad (Gamepad *pad)
void ResetGamepads ()
Gamepad * GetUnusedGamepad ()
Protected Member Functions
void RemoveGamepadsByProvider (GamepadProvider *provider)
Protected Attributes
eGamepadID m_defaultGamepadID
list< GamepadProvider * > m_providers
vector< Gamepad * > m_gamepads
Detailed Description
Definition at line 72 of file GamepadManager.h.
Constructor & Destructor Documentation
GamepadManager::GamepadManager ()
Definition at line 4 of file GamepadManager.cpp.
References GAMEPAD_ID_NONE, and m_defaultGamepadID.
GamepadManager::~GamepadManager () [virtual]
Definition at line 9 of file GamepadManager.cpp.
References GAMEPAD_ID_NONE, m_defaultGamepadID, m_gamepads, and m_providers.
Member Function Documentation
void GamepadManager::AddGamepad (Gamepad * pad)
Definition at line 61 of file GamepadManager.cpp.
References GAMEPAD_ID_NONE, Gamepad::GetID(), Gamepad::GetName(), Gamepad::Init(), LogMsg(), m_defaultGamepadID, m_gamepads, and Gamepad::SetID().
Referenced by GamepadProvideriCade::Init(), and GamepadProviderMoga::Init().
GamepadProvider * GamepadManager::AddProvider (GamepadProvider * provider)
Definition at line 30 of file GamepadManager.cpp.
References GamepadProvider::GetName(), GamepadProvider::Init(), LogError(), LogMsg(), and m_providers.
Gamepad * GamepadManager::GetDefaultGamepad ()
Definition at line 80 of file GamepadManager.cpp.
References GAMEPAD_ID_NONE, m_defaultGamepadID, and m_gamepads.
Referenced by GetUnusedGamepad().
eGamepadID GamepadManager::GetDefaultGamepadID ()
Definition at line 86 of file GamepadManager.cpp.
References m_defaultGamepadID.
Gamepad * GamepadManager::GetGamepad (eGamepadID id)
Definition at line 163 of file GamepadManager.cpp.
References m_gamepads.
int GamepadManager::GetGamepadCount () [inline]
Definition at line 83 of file GamepadManager.h.
References m_gamepads.
GamepadProvider * GamepadManager::GetProviderByName (string name)
Definition at line 173 of file GamepadManager.cpp.
References m_providers.
Gamepad * GamepadManager::GetUnusedGamepad ()
Definition at line 99 of file GamepadManager.cpp.
References GAMEPAD_ID_NONE, GetDefaultGamepad(), m_defaultGamepadID, m_gamepads, and Gamepad::SetIsUsed().
void GamepadManager::RemoveGamepadsByProvider (GamepadProvider * provider) [protected]
Definition at line 146 of file GamepadManager.cpp.
References GAMEPAD_ID_NONE, m_defaultGamepadID, and m_gamepads.
Referenced by RemoveProviderByName().
bool GamepadManager::RemoveProviderByName (string name)
Definition at line 126 of file GamepadManager.cpp.
References LogMsg(), m_providers, and RemoveGamepadsByProvider().
void GamepadManager::ResetGamepads ()
Definition at line 91 of file GamepadManager.cpp.
References m_gamepads.
void GamepadManager::SetDefaultGamepad (Gamepad * pPad)
Definition at line 187 of file GamepadManager.cpp.
References Gamepad::GetID(), and m_defaultGamepadID.
void GamepadManager::Update ()
Definition at line 47 of file GamepadManager.cpp.
References m_gamepads, and m_providers.
Member Data Documentation
eGamepadID GamepadManager::m_defaultGamepadID [protected]
Definition at line 102 of file GamepadManager.h.
Referenced by AddGamepad(), GamepadManager(), GetDefaultGamepad(), GetDefaultGamepadID(), GetUnusedGamepad(), RemoveGamepadsByProvider(), SetDefaultGamepad(), and ~GamepadManager().
vector<Gamepad*> GamepadManager::m_gamepads [protected]
Definition at line 105 of file GamepadManager.h.
Referenced by AddGamepad(), GetDefaultGamepad(), GetGamepad(), GetGamepadCount(), GetUnusedGamepad(), RemoveGamepadsByProvider(), ResetGamepads(), Update(), and ~GamepadManager().
list<GamepadProvider*> GamepadManager::m_providers [protected]
Definition at line 104 of file GamepadManager.h.
Referenced by AddProvider(), GetProviderByName(), RemoveProviderByName(), Update(), and ~GamepadManager().
The documentation for this class was generated from the following files:
GamepadManager.h
GamepadManager.cpp