Proton: SurfaceAnim Class Reference
SurfaceAnim Class Reference
#include <SurfaceAnim.h>
Public Member Functions
SurfaceAnim ()
virtual ~SurfaceAnim ()
void SetupAnim (int framesX, int framesY)
void SetupAnimBySize (int frameWid, int frameHei)
void BlitAnim (float x, float y, int frameX=0, int frameY=0, unsigned int rgba=MAKE_RGBA(255, 255, 255, 255), float rotation=0, CL_Vec2f vRotationPtScreenCoords=CL_Vec2f(0, 0))
void BlitScaledAnim (float x, float y, int frameX, int frameY, CL_Vec2f vScale, eAlignment alignment=ALIGNMENT_CENTER, unsigned int rgba=MAKE_RGBA(255, 255, 255, 255), float rotation=0, CL_Vec2f vRotationPtScreenCoords=CL_Vec2f(0, 0), bool flipX=false, bool flipY=false, RenderBatcher *pBatcher=NULL)
void BlitRotatedAnim (float x, float y, int frameX, int frameY, CL_Vec2f vScale, eAlignment alignment=ALIGNMENT_CENTER, unsigned int rgba=MAKE_RGBA(255, 255, 255, 255), float rotation=0, CL_Vec2f vRotationPtLocalCoords=CL_Vec2f(0, 0), bool flipX=false, bool flipY=false, RenderBatcher *pBatcher=NULL)
int GetFramesX ()
int GetFramesY ()
int GetFrameXByInt (int frame)
int GetFrameYByInt (int frame)
int GetFrameNumFromXY (int frameX, int frameY)
float GetFrameWidth ()
float GetFrameHeight ()
CL_Vec2f GetFrameSize ()
virtual bool LoadFileFromMemory (byte *pMem, int inputSize=0)
virtual bool InitBlankSurface (int x, int y)
virtual bool InitFromSoftSurface (SoftSurface *pSurf)
float GetAspectRatio ()
Protected Member Functions
virtual void ReloadImage ()
Detailed Description
Definition at line 15 of file SurfaceAnim.h.
Constructor & Destructor Documentation
SurfaceAnim::SurfaceAnim ()
Definition at line 5 of file SurfaceAnim.cpp.
SurfaceAnim::~SurfaceAnim () [virtual]
Definition at line 13 of file SurfaceAnim.cpp.
Member Function Documentation
void SurfaceAnim::BlitAnim (float x, float y, int frameX = 0, int frameY = 0, unsigned int rgba = MAKE_RGBA(255,255,255,255), float rotation = 0, CL_Vec2f vRotationPtScreenCoords = CL_Vec2f(0,0))
Definition at line 42 of file SurfaceAnim.cpp.
References Surface::Blit(), Surface::BlitEx(), rtRectf::bottom, GetFrameHeight(), GetFrameWidth(), Surface::GetHeight(), Surface::GetWidth(), rtRectf::left, rtRectf::right, and rtRectf::top.
Referenced by DrawFilledBitmapRect().
void SurfaceAnim::BlitRotatedAnim (float x, float y, int frameX, int frameY, CL_Vec2f vScale, eAlignment alignment = ALIGNMENT_CENTER, unsigned int rgba = MAKE_RGBA(255,255,255,255), float rotation = 0, CL_Vec2f vRotationPtLocalCoords = CL_Vec2f(0,0), bool flipX = false, bool flipY = false, RenderBatcher * pBatcher = NULL)
Definition at line 150 of file SurfaceAnim.cpp.
References BlitScaledAnim().
void SurfaceAnim::BlitScaledAnim (float x, float y, int frameX, int frameY, CL_Vec2f vScale, eAlignment alignment = ALIGNMENT_CENTER, unsigned int rgba = MAKE_RGBA(255,255,255,255), float rotation = 0, CL_Vec2f vRotationPtScreenCoords = CL_Vec2f(0,0), bool flipX = false, bool flipY = false, RenderBatcher * pBatcher = NULL)
Definition at line 72 of file SurfaceAnim.cpp.
References rtRectf::AdjustPosition(), ALIGNMENT_UPPER_LEFT, RenderBatcher::BlitEx(), Surface::BlitEx(), Surface::BlitScaledWithRotatePoint(), rtRectf::bottom, GetAlignmentOffset(), GetFrameHeight(), GetFrameWidth(), Surface::GetHeight(), Surface::GetWidth(), rtRectf::left, rtRectf::right, rtRectf::Scale(), and rtRectf::top.
Referenced by BlitRotatedAnim(), and DrawFilledBitmapRect().
float SurfaceAnim::GetAspectRatio ()
Definition at line 158 of file SurfaceAnim.cpp.
float SurfaceAnim::GetFrameHeight () [inline]
Definition at line 38 of file SurfaceAnim.h.
Referenced by BlitAnim(), BlitScaledAnim(), and GetFrameSize().
int SurfaceAnim::GetFrameNumFromXY (int frameX, int frameY) [inline]
Definition at line 35 of file SurfaceAnim.h.
CL_Vec2f SurfaceAnim::GetFrameSize () [inline]
Definition at line 39 of file SurfaceAnim.h.
References GetFrameHeight(), and GetFrameWidth().
int SurfaceAnim::GetFramesX () [inline]
Definition at line 31 of file SurfaceAnim.h.
Referenced by DrawFilledBitmapRect().
int SurfaceAnim::GetFramesY () [inline]
Definition at line 32 of file SurfaceAnim.h.
Referenced by DrawFilledBitmapRect().
float SurfaceAnim::GetFrameWidth () [inline]
Definition at line 37 of file SurfaceAnim.h.
Referenced by BlitAnim(), BlitScaledAnim(), and GetFrameSize().
int SurfaceAnim::GetFrameXByInt (int frame) [inline]
Definition at line 33 of file SurfaceAnim.h.
int SurfaceAnim::GetFrameYByInt (int frame) [inline]
Definition at line 34 of file SurfaceAnim.h.
bool SurfaceAnim::InitBlankSurface (int x, int y) [virtual]
Reimplemented from Surface.
Definition at line 132 of file SurfaceAnim.cpp.
References Surface::GetHeight(), Surface::GetWidth(), and Surface::InitBlankSurface().
bool SurfaceAnim::InitFromSoftSurface (SoftSurface * pSurf) [virtual]
Definition at line 141 of file SurfaceAnim.cpp.
References Surface::GetHeight(), Surface::GetWidth(), and Surface::InitFromSoftSurface().
bool SurfaceAnim::LoadFileFromMemory (byte * pMem, int inputSize = 0) [virtual]
Reimplemented from Surface.
Definition at line 62 of file SurfaceAnim.cpp.
References Surface::GetHeight(), Surface::GetWidth(), and Surface::LoadFileFromMemory().
void SurfaceAnim::ReloadImage () [protected, virtual]
Reimplemented from Surface.
Definition at line 118 of file SurfaceAnim.cpp.
void SurfaceAnim::SetupAnim (int framesX, int framesY)
Definition at line 17 of file SurfaceAnim.cpp.
References Surface::GetHeight(), Surface::GetWidth(), and Surface::IsLoaded().
void SurfaceAnim::SetupAnimBySize (int frameWid, int frameHei)
Definition at line 31 of file SurfaceAnim.cpp.
References Surface::GetWidth(), and Surface::IsLoaded().
The documentation for this class was generated from the following files:
SurfaceAnim.h
SurfaceAnim.cpp