Proton: TouchDragComponent Class Reference
TouchDragComponent Class Reference
#include <TouchDragComponent.h>
Public Types
enum eVisualStyle { STYLE_NONE }
Public Member Functions
TouchDragComponent ()
virtual ~TouchDragComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
void OnInput (VariantList *pVList)
void ModLastPos (CL_Vec2d vPos)
void SetLastPos (CL_Vec2d vLastPos)
void ResetLastPos ()
Detailed Description
Definition at line 29 of file TouchDragComponent.h.
Member Enumeration Documentation
enum TouchDragComponent::eVisualStyle
Enumerator:
STYLE_NONE
Definition at line 38 of file TouchDragComponent.h.
Constructor & Destructor Documentation
TouchDragComponent::TouchDragComponent ()
Definition at line 5 of file TouchDragComponent.cpp.
References EntityComponent::SetName().
TouchDragComponent::~TouchDragComponent () [virtual]
Definition at line 12 of file TouchDragComponent.cpp.
References GetBaseApp(), BaseApp::GetTouch(), and TouchTrackInfo::SetWasHandled().
Member Function Documentation
void TouchDragComponent::ModLastPos (CL_Vec2d vPos)
Definition at line 169 of file TouchDragComponent.cpp.
void TouchDragComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 36 of file TouchDragComponent.cpp.
References EntityComponent::GetFunction(), Entity::GetFunction(), EntityComponent::GetParent(), Variant::GetRect(), Variant::GetUINT32(), EntityComponent::GetVar(), Entity::GetVar(), EntityComponent::GetVarWithDefault(), Entity::GetVarWithDefault(), Variant::GetVector2(), OnInput(), FunctionObject::sig_function, and STYLE_NONE.
void TouchDragComponent::OnInput (VariantList * pVList)
Definition at line 94 of file TouchDragComponent.cpp.
References ApplyPadding(), VariantList::Get(), GetBaseApp(), Variant::GetFloat(), Entity::GetFunction(), EntityComponent::GetParent(), BaseApp::GetTouch(), Variant::GetType(), Variant::GetUINT32(), Variant::GetVector2(), MESSAGE_TYPE_GUI_CLICK_END, MESSAGE_TYPE_GUI_CLICK_MOVE, MESSAGE_TYPE_GUI_CLICK_START, TouchTrackInfo::SetWasHandled(), FunctionObject::sig_function, Variant::TYPE_UINT32, and TouchTrackInfo::WasHandled().
Referenced by OnAdd().
void TouchDragComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 59 of file TouchDragComponent.cpp.
void TouchDragComponent::ResetLastPos ()
Definition at line 174 of file TouchDragComponent.cpp.
References GetBaseApp(), TouchTrackInfo::GetPos(), and BaseApp::GetTouch().
void TouchDragComponent::SetLastPos (CL_Vec2d vLastPos)
Definition at line 165 of file TouchDragComponent.cpp.
The documentation for this class was generated from the following files:
TouchDragComponent.h
TouchDragComponent.cpp