Proton: FileSystemZip Class Reference
FileSystemZip Class Reference
#include <FileSystemZip.h>
Public Member Functions
FileSystemZip ()
virtual ~FileSystemZip ()
bool Init (string apkFileName)
vector< string > GetContents ()
void SetRootDirectory (string rootDir)
virtual byte * Get (string fileName, int *pSizeOut)
virtual StreamingInstance * GetStreaming (string fileName, int *pSizeOut)
virtual bool FileExists (string fileName)
virtual int GetFileSize (string fileName)
Detailed Description
Definition at line 26 of file FileSystemZip.h.
Constructor & Destructor Documentation
FileSystemZip::FileSystemZip ()
Definition at line 7 of file FileSystemZip.cpp.
FileSystemZip::~FileSystemZip () [virtual]
Definition at line 12 of file FileSystemZip.cpp.
Member Function Documentation
bool FileSystemZip::FileExists (string fileName) [virtual]
Definition at line 268 of file FileSystemZip.cpp.
byte * FileSystemZip::Get (string fileName, int * pSizeOut) [virtual]
Definition at line 135 of file FileSystemZip.cpp.
References LogError().
vector< string > FileSystemZip::GetContents ()
Definition at line 89 of file FileSystemZip.cpp.
References LogError().
int FileSystemZip::GetFileSize (string fileName) [virtual]
Definition at line 280 of file FileSystemZip.cpp.
References LogError().
StreamingInstance * FileSystemZip::GetStreaming (string fileName, int * pSizeOut) [virtual]
Definition at line 224 of file FileSystemZip.cpp.
References StreamingInstanceZip::Init(), LogMsg(), StreamingInstanceZip::OpenWithCacheEntry(), and StreamingInstanceZip::SetRootDirectory().
bool FileSystemZip::Init (string apkFileName)
Definition at line 18 of file FileSystemZip.cpp.
References LogError(), and LogMsg().
Referenced by AppResize().
void FileSystemZip::SetRootDirectory (string rootDir)
Definition at line 219 of file FileSystemZip.cpp.
Referenced by AppResize().
The documentation for this class was generated from the following files:
FileSystemZip.h
FileSystemZip.cpp