Proton: L_ParticleEffect Class Reference
L_ParticleEffect Class Reference
Particle effect interface.
#include <L_ParticleEffect.h>
Public Member Functions
L_ParticleEffect ()
L_ParticleEffect (int period_t, int x, int y)
period : time(milisec) interval between two emissions, 1 <= period < infinity
v_t : velocity for this effect
L_ParticleEffect (const L_ParticleEffect &cpy)
Copy contructor.
virtual ~L_ParticleEffect ()
Destructor.
int add (L_Particle *fl_p, L_REAL prob=-1)
Add a particle type for the effect and probability for the particle to be chosen for every emission.
void set_velocity (const CL_Vec2f &v_t)
Copy effect's velocity from "v_t".
void set_velocity (L_REAL x_length, L_REAL y_length)
Set effect's velocity(vector) using X length and Y length.
void set_position (L_REAL x, L_REAL y)
Set position.
void set_offset (L_REAL x, L_REAL y)
Set offset.
void set_par_random_rotation (bool par_rand_rot=true)
Apply randomization for particles' initial rotation.
void set_size_distortion (L_REAL size_dis)
Apply distortion on particle's size.
void set_life_distortion (int life_dis)
Apply distortion on particle's life.
void set_life (int effect_life)
Set effect's life, L_INFINITE_LIFE for infinite life.
void set_follow_shooting (bool flag=true)
Set the particle facing to the direction of emission.
void set_addit_vector (const CL_Vec2f &v_t)
Add additional vector for emitted particle, can be used for inertia effect.
void set_period (int millisecond)
Set period for emission in milli second.
L_REAL get_x_pos (void)
L_REAL get_y_pos (void)
int get_particle_num (void)
int get_life (void)
int get_period (void)
void trigger (bool bActive=true)
Trigger particle emission.
void initialize (void)
Initialization, must be called (once) before calling run(int).
void clear ()
void run (int time_elapesed_t)
void draw (int x_shift=0, int y_shift=0, float x_size_mod=1, float y_size_mod=1)
virtual L_ParticleEffect * new_clone (void)=0
Create a clone this particle effect.
virtual void activate_particle (int time_elapesed_t)
Run all particles in the list(by calling run(int) function of particles) with certain time.
void Setup (int period_t, int x, int y)
void RenderPointSprites (SurfaceAnim *pSurf, int start, int count)
Public Attributes
std::list< L_Particle * > particle_list
L_REAL x_pos
L_REAL y_pos
L_REAL x_pos_offset
L_REAL y_pos_offset
Protected Member Functions
int choose_particle (void)
L_REAL rand_size (void)
void create_particle (L_REAL in_x, L_REAL in_y, CL_Vec2f *vec_t=NULL)
void motion_process (L_REAL time_elapesed)
void creating_process (void)
virtual void howto_emit_particle (void)=0
Protected Attributes
L_Particle * fl_particle [L_PARTICLE_TYPE_LIMIT]
L_REAL particle_prob [L_PARTICLE_TYPE_LIMIT]
int num_particle_type
CL_Vec2f velocity
bool par_randrot_on
L_REAL size_distortion
int life_distortion
bool follow_shooting
int time_elapesed
bool istriggered
int period
int counter
int life
bool addit_vector_enabled
CL_Vec2f addit_vector
Detailed Description
Particle effect interface.
Definition at line 35 of file L_ParticleEffect.h.
Constructor & Destructor Documentation
L_ParticleEffect::L_ParticleEffect () [inline]
Definition at line 95 of file L_ParticleEffect.h.
L_ParticleEffect::L_ParticleEffect (int period_t, int x, int y)
period : time(milisec) interval between two emissions, 1 <= period < infinity
v_t : velocity for this effect
Definition at line 68 of file L_ParticleEffect.cpp.
References Setup().
L_ParticleEffect::L_ParticleEffect (const L_ParticleEffect & cpy)
Copy contructor.
Note : this does not copy particle list.
Definition at line 74 of file L_ParticleEffect.cpp.
References addit_vector, addit_vector_enabled, counter, fl_particle, follow_shooting, istriggered, life, life_distortion, num_particle_type, par_randrot_on, particle_prob, period, size_distortion, velocity, x_pos, and y_pos.
L_ParticleEffect::~L_ParticleEffect () [virtual]
Destructor.
Definition at line 109 of file L_ParticleEffect.cpp.
References clear().
Member Function Documentation
void L_ParticleEffect::activate_particle (int time_elapesed_t) [virtual]
Run all particles in the list(by calling run(int) function of particles) with certain time.
Basically this is used to resolve the inaccuracy of particle emission and movement when the frame rate is low, normal users should not use this function unless there is intention to write custom ParticleEffect.
Definition at line 585 of file L_ParticleEffect.cpp.
References life, and particle_list.
Referenced by creating_process().
int L_ParticleEffect::add (L_Particle * fl_p, L_REAL prob = -1)
Add a particle type for the effect and probability for the particle to be chosen for every emission.
Note : If no probability is specified, the particle will get the remaining probability to 1 (if more than 1 probability non-specified particle, remaining probability to 1 will be equally divided for each. Maximum number of particle types is limited to 10.
Definition at line 127 of file L_ParticleEffect.cpp.
References fl_particle, LogMsg(), num_particle_type, and particle_prob.
int L_ParticleEffect::choose_particle (void) [inline, protected]
Definition at line 261 of file L_ParticleEffect.cpp.
References num_particle_type, and particle_prob.
Referenced by create_particle().
void L_ParticleEffect::clear ()
Definition at line 122 of file L_ParticleEffect.cpp.
References particle_list.
Referenced by ~L_ParticleEffect().
void L_ParticleEffect::create_particle (L_REAL in_x, L_REAL in_y, CL_Vec2f * vec_t = NULL) [protected]
Definition at line 278 of file L_ParticleEffect.cpp.
References addit_vector, addit_vector_enabled, choose_particle(), fl_particle, follow_shooting, L_Particle::get_ref_size(), L_Particle::get_remaininig_life(), L_Particle::initialize(), life_distortion, linear_get_radian(), LogMsg(), par_randrot_on, particle_list, rand_size(), L_Particle::set_life(), L_Particle::set_rotation(), L_Particle::set_rotation2(), L_Particle::set_size(), L_Particle::set_velocity(), size_distortion, L_Particle::x_pos, and L_Particle::y_pos.
Referenced by L_DroppingEffect::howto_emit_particle(), L_ExplosionEffect::howto_emit_particle(), and L_ShootingEffect::howto_emit_particle().
void L_ParticleEffect::creating_process (void) [protected]
Definition at line 352 of file L_ParticleEffect.cpp.
References activate_particle(), counter, howto_emit_particle(), istriggered, life, motion_process(), period, and time_elapesed.
Referenced by run().
void L_ParticleEffect::draw (int x_shift = 0, int y_shift = 0, float x_size_mod = 1, float y_size_mod = 1)
Definition at line 513 of file L_ParticleEffect.cpp.
References RenderBatcher::Flush(), RenderBatcher::FLUSH_RENDER, RenderBatcher::FLUSH_SETUP, RenderBatcher::FLUSH_UNSETUP, g_globalBatcher, Surface::GetRawTextureWidth(), glBlendFunc(), glPopMatrix(), glPushMatrix(), glTranslatef(), particle_list, L_ParticleMem::pointSpriteArray, L_ParticleMem::pointSpriteArraySize, and RenderPointSprites().
int L_ParticleEffect::get_life (void)
Definition at line 423 of file L_ParticleEffect.cpp.
References life.
int L_ParticleEffect::get_particle_num (void)
Definition at line 417 of file L_ParticleEffect.cpp.
References particle_list.
int L_ParticleEffect::get_period (void)
Definition at line 428 of file L_ParticleEffect.cpp.
References period.
L_REAL L_ParticleEffect::get_x_pos (void)
Definition at line 405 of file L_ParticleEffect.cpp.
References x_pos.
L_REAL L_ParticleEffect::get_y_pos (void)
Definition at line 411 of file L_ParticleEffect.cpp.
References y_pos.
virtual void L_ParticleEffect::howto_emit_particle (void) [protected, pure virtual]
Implemented in L_ShootingEffect, L_ExplosionEffect, and L_DroppingEffect.
Referenced by creating_process().
void L_ParticleEffect::initialize (void)
Initialization, must be called (once) before calling run(int).
Definition at line 433 of file L_ParticleEffect.cpp.
References num_particle_type, and particle_prob.
void L_ParticleEffect::motion_process (L_REAL time_elapesed) [protected]
Definition at line 345 of file L_ParticleEffect.cpp.
References time_elapesed, velocity, x_pos, and y_pos.
Referenced by creating_process().
virtual L_ParticleEffect* L_ParticleEffect::new_clone (void) [pure virtual]
Create a clone this particle effect.
Implemented in L_ShootingEffect, L_ExplosionEffect, and L_DroppingEffect.
Referenced by L_EffectEmitter::emit().
L_REAL L_ParticleEffect::rand_size (void) [protected]
Definition at line 238 of file L_ParticleEffect.cpp.
References size_distortion.
Referenced by create_particle().
void L_ParticleEffect::RenderPointSprites (SurfaceAnim * pSurf, int start, int count)
Definition at line 444 of file L_ParticleEffect.cpp.
References Surface::Bind(), glBindBuffer(), glBlendFunc(), glBufferData(), glColorPointer(), glDisable(), glDisableClientState(), glDrawArrays(), glEnable(), glEnableClientState(), glPointSizePointerOES(), glTexEnvi(), glVertexPointer(), L_ParticleMem::pointSpriteArray, and L_ParticleMem::pointSpriteBufferID.
Referenced by draw().
void L_ParticleEffect::run (int time_elapesed_t)
Definition at line 612 of file L_ParticleEffect.cpp.
References creating_process(), and time_elapesed.
void L_ParticleEffect::set_addit_vector (const CL_Vec2f & v_t)
Add additional vector for emitted particle, can be used for inertia effect.
Definition at line 248 of file L_ParticleEffect.cpp.
References addit_vector, and addit_vector_enabled.
void L_ParticleEffect::set_follow_shooting (bool flag = true)
Set the particle facing to the direction of emission.
Note : Degree distortion is disabled, if you need the particle to follow
its velocity direction even after the emission, please use L_Particle::rotating4();
Definition at line 226 of file L_ParticleEffect.cpp.
References follow_shooting.
void L_ParticleEffect::set_life (int effect_life)
Set effect's life, L_INFINITE_LIFE for infinite life.
Definition at line 232 of file L_ParticleEffect.cpp.
References life.
void L_ParticleEffect::set_life_distortion (int life_dis)
Apply distortion on particle's life.
Each particle would have certain degree of different length of life if "life_dis" is greater than 0.
Definition at line 218 of file L_ParticleEffect.cpp.
References life_distortion.
void L_ParticleEffect::set_offset (L_REAL x, L_REAL y)
Set offset.
Definition at line 182 of file L_ParticleEffect.cpp.
References x_pos, x_pos_offset, y_pos, and y_pos_offset.
void L_ParticleEffect::set_par_random_rotation (bool par_rand_rot = true)
Apply randomization for particles' initial rotation.
Definition at line 206 of file L_ParticleEffect.cpp.
References par_randrot_on.
void L_ParticleEffect::set_period (int millisecond)
Set period for emission in milli second.
Definition at line 255 of file L_ParticleEffect.cpp.
References period.
void L_ParticleEffect::set_position (L_REAL x, L_REAL y)
Set position.
Definition at line 177 of file L_ParticleEffect.cpp.
References x_pos, x_pos_offset, y_pos, and y_pos_offset.
void L_ParticleEffect::set_size_distortion (L_REAL size_dis)
Apply distortion on particle's size.
Each particle would have certain degree of different size if "size_dis" is greater than 0.
Definition at line 212 of file L_ParticleEffect.cpp.
References size_distortion.
void L_ParticleEffect::set_velocity (const CL_Vec2f & v_t)
Copy effect's velocity from "v_t".
Definition at line 171 of file L_ParticleEffect.cpp.
References velocity.
void L_ParticleEffect::set_velocity (L_REAL x_length, L_REAL y_length)
Set effect's velocity(vector) using X length and Y length.
Note : Use this function rather than set_position() if possible, internally there is calculation to ensure better
pattern consistency even in jecky framerate environment. If you require to control exact position
with no any accumulated error, call additional set_position() after run().
Definition at line 200 of file L_ParticleEffect.cpp.
References velocity.
void L_ParticleEffect::Setup (int period_t, int x, int y)
Definition at line 38 of file L_ParticleEffect.cpp.
References addit_vector_enabled, fl_particle, follow_shooting, istriggered, life, life_distortion, num_particle_type, par_randrot_on, period, size_distortion, velocity, x_pos, x_pos_offset, y_pos, and y_pos_offset.
Referenced by L_ParticleEffect().
void L_ParticleEffect::trigger (bool bActive = true)
Trigger particle emission.
Definition at line 606 of file L_ParticleEffect.cpp.
References istriggered.
Member Data Documentation
CL_Vec2f L_ParticleEffect::addit_vector [protected]
Definition at line 65 of file L_ParticleEffect.h.
Referenced by create_particle(), L_ParticleEffect(), and set_addit_vector().
bool L_ParticleEffect::addit_vector_enabled [protected]
Definition at line 64 of file L_ParticleEffect.h.
Referenced by create_particle(), L_ParticleEffect(), set_addit_vector(), and Setup().
int L_ParticleEffect::counter [protected]
Definition at line 60 of file L_ParticleEffect.h.
Referenced by creating_process(), and L_ParticleEffect().
L_Particle* L_ParticleEffect::fl_particle[L_PARTICLE_TYPE_LIMIT] [protected]
Definition at line 44 of file L_ParticleEffect.h.
Referenced by add(), create_particle(), L_ParticleEffect(), and Setup().
bool L_ParticleEffect::follow_shooting [protected]
Definition at line 53 of file L_ParticleEffect.h.
Referenced by create_particle(), L_ParticleEffect(), set_follow_shooting(), and Setup().
bool L_ParticleEffect::istriggered [protected]
Definition at line 57 of file L_ParticleEffect.h.
Referenced by creating_process(), L_ParticleEffect(), Setup(), and trigger().
int L_ParticleEffect::life [protected]
Definition at line 62 of file L_ParticleEffect.h.
Referenced by activate_particle(), creating_process(), get_life(), L_ParticleEffect(), set_life(), and Setup().
int L_ParticleEffect::life_distortion [protected]
Definition at line 52 of file L_ParticleEffect.h.
Referenced by create_particle(), L_ParticleEffect(), set_life_distortion(), and Setup().
int L_ParticleEffect::num_particle_type [protected]
Definition at line 46 of file L_ParticleEffect.h.
Referenced by add(), choose_particle(), initialize(), L_ParticleEffect(), and Setup().
bool L_ParticleEffect::par_randrot_on [protected]
Definition at line 50 of file L_ParticleEffect.h.
Referenced by create_particle(), L_ParticleEffect(), set_par_random_rotation(), and Setup().
std::list<L_Particle*> L_ParticleEffect::particle_list
Definition at line 88 of file L_ParticleEffect.h.
Referenced by activate_particle(), clear(), create_particle(), draw(), and get_particle_num().
L_REAL L_ParticleEffect::particle_prob[L_PARTICLE_TYPE_LIMIT] [protected]
Definition at line 45 of file L_ParticleEffect.h.
Referenced by add(), choose_particle(), initialize(), and L_ParticleEffect().
int L_ParticleEffect::period [protected]
Definition at line 59 of file L_ParticleEffect.h.
Referenced by creating_process(), get_period(), L_ParticleEffect(), set_period(), and Setup().
L_REAL L_ParticleEffect::size_distortion [protected]
Definition at line 51 of file L_ParticleEffect.h.
Referenced by create_particle(), L_ParticleEffect(), rand_size(), set_size_distortion(), and Setup().
int L_ParticleEffect::time_elapesed [protected]
Definition at line 55 of file L_ParticleEffect.h.
Referenced by creating_process(), motion_process(), and run().
CL_Vec2f L_ParticleEffect::velocity [protected]
Definition at line 48 of file L_ParticleEffect.h.
Referenced by L_ParticleEffect(), motion_process(), set_velocity(), and Setup().
L_REAL L_ParticleEffect::x_pos
Definition at line 89 of file L_ParticleEffect.h.
Referenced by L_EffectEmitter::emit(), get_x_pos(), L_DroppingEffect::howto_emit_particle(), L_ExplosionEffect::howto_emit_particle(), L_ShootingEffect::howto_emit_particle(), L_ParticleEffect(), motion_process(), set_offset(), set_position(), and Setup().
L_REAL L_ParticleEffect::x_pos_offset
Definition at line 92 of file L_ParticleEffect.h.
Referenced by set_offset(), set_position(), and Setup().
L_REAL L_ParticleEffect::y_pos
Definition at line 90 of file L_ParticleEffect.h.
Referenced by L_EffectEmitter::emit(), get_y_pos(), L_DroppingEffect::howto_emit_particle(), L_ExplosionEffect::howto_emit_particle(), L_ShootingEffect::howto_emit_particle(), L_ParticleEffect(), motion_process(), set_offset(), set_position(), and Setup().
L_REAL L_ParticleEffect::y_pos_offset
Definition at line 93 of file L_ParticleEffect.h.
Referenced by set_offset(), set_position(), and Setup().
The documentation for this class was generated from the following files:
L_ParticleEffect.h
L_ParticleEffect.cpp