Proton: Console Class Reference
Console Class Reference
#include <Console.h>
Public Member Functions
Console ()
virtual ~Console ()
void AddLine (std::string line)
void SetMaxLines (unsigned int num)
string GetAsSingleString ()
void Clear ()
size_t GetTotalLines ()
string GetLine (int index)
Public Attributes
boost::signal< void()> m_sig_on_text_added
Detailed Description
Definition at line 17 of file Console.h.
Constructor & Destructor Documentation
Console::Console ()
Definition at line 4 of file Console.cpp.
References SetMaxLines().
Console::~Console () [virtual]
Definition at line 9 of file Console.cpp.
Member Function Documentation
void Console::AddLine (std::string line)
Definition at line 18 of file Console.cpp.
References m_sig_on_text_added.
Referenced by LogMsg().
void Console::Clear ()
Definition at line 13 of file Console.cpp.
string Console::GetAsSingleString ()
Definition at line 31 of file Console.cpp.
string Console::GetLine (int index) [inline]
Definition at line 28 of file Console.h.
size_t Console::GetTotalLines () [inline]
Definition at line 27 of file Console.h.
void Console::SetMaxLines (unsigned int num) [inline]
Definition at line 24 of file Console.h.
Referenced by Console().
Member Data Documentation
boost::signal<void()> Console::m_sig_on_text_added
Definition at line 30 of file Console.h.
Referenced by AddLine(), LogDisplayComponent::OnAdd(), and LogDisplayComponent::SetConsole().
The documentation for this class was generated from the following files:
Console.h
Console.cpp