Proton: GamepadDirectX Class Reference
GamepadDirectX Class Reference
#include <GamepadDirectX.h>
Public Member Functions
GamepadDirectX ()
virtual ~GamepadDirectX ()
virtual bool Init ()
virtual void Kill ()
virtual void Update ()
void SetDeviceInstance (DIDEVICEINSTANCE instance)
Detailed Description
Definition at line 18 of file GamepadDirectX.h.
Constructor & Destructor Documentation
GamepadDirectX::GamepadDirectX ()
Definition at line 4 of file GamepadDirectX.cpp.
GamepadDirectX::~GamepadDirectX () [virtual]
Definition at line 9 of file GamepadDirectX.cpp.
References Kill().
Member Function Documentation
bool GamepadDirectX::Init () [virtual]
Implements Gamepad.
Definition at line 14 of file GamepadDirectX.cpp.
References LogError(), Gamepad::m_axisUsedCount, Gamepad::m_buttons, Gamepad::m_buttonsUsedCount, Gamepad::m_name, Gamepad::m_pPadProvider, GamepadButton::m_virtualKey, Gamepad::SetRightStickAxis(), VIRTUAL_DPAD_BUTTON_DOWN, VIRTUAL_DPAD_BUTTON_LEFT, VIRTUAL_DPAD_BUTTON_RIGHT, VIRTUAL_DPAD_BUTTON_UP, VIRTUAL_DPAD_LBUTTON, VIRTUAL_DPAD_RBUTTON, VIRTUAL_DPAD_SELECT, and VIRTUAL_DPAD_START.
void GamepadDirectX::Kill () [virtual]
Implements Gamepad.
Definition at line 125 of file GamepadDirectX.cpp.
Referenced by ~GamepadDirectX().
void GamepadDirectX::SetDeviceInstance (DIDEVICEINSTANCE instance) [inline]
Definition at line 27 of file GamepadDirectX.h.
void GamepadDirectX::Update () [virtual]
Reimplemented from Gamepad.
Definition at line 130 of file GamepadDirectX.cpp.
References Gamepad::OnButton(), Gamepad::OnHat(), and Gamepad::SetAxis().
The documentation for this class was generated from the following files:
GamepadDirectX.h
GamepadDirectX.cpp