Proton: PVerticalCursorInteraction Class Reference
PVerticalCursorInteraction Class Reference
#include <PPlotInteraction.h>
Public Member Functions
PVerticalCursorInteraction (PPlot &inPPlot)
virtual bool Impl_HandleKeyEvent (const PKeyEvent &inEvent)
virtual bool Impl_Calculate (Painter &inPainter, PPlot &inPPlot)
Public Attributes
PlotDataIncrementerBounds mGlobalBounds
Protected Member Functions
void HandleVerticalCursorKey (const PlotDataSelection *inPlotDataSelection, PlotDataBase *inYData)
Detailed Description
Definition at line 264 of file PPlotInteraction.h.
Constructor & Destructor Documentation
PVerticalCursorInteraction::PVerticalCursorInteraction (PPlot & inPPlot)
Definition at line 496 of file PPlotInteraction.cpp.
Member Function Documentation
void PVerticalCursorInteraction::HandleVerticalCursorKey (const PlotDataSelection * inPlotDataSelection, PlotDataBase * inYData) [protected]
Definition at line 526 of file PPlotInteraction.cpp.
References PlotDataSelection::GetSelectedCount(), PlotDataBase::GetSize(), PlotDataIncrementer::Increment(), PKeyEvent::IsArrowDown(), PModifierKeys::IsOnlyControlKeyDown(), PlotDataSelection::IsSelected(), mGlobalBounds, PEditInteraction::mKeyEvent, PPlotInteraction::mPPlot, PPlot::mYTrafo, Trafo::Transform(), and Trafo::TransformBack().
Referenced by Impl_Calculate().
bool PVerticalCursorInteraction::Impl_Calculate (Painter & inPainter, PPlot & inPPlot) [virtual]
Implements PEditInteraction.
Definition at line 509 of file PPlotInteraction.cpp.
References PlotDataContainer::GetDataDrawer(), PlotDataContainer::GetPlotCount(), PlotDataContainer::GetPlotDataSelection(), PlotDataContainer::GetXData(), PlotDataContainer::GetYData(), HandleVerticalCursorKey(), PKeyEvent::IsArrowDown(), PKeyEvent::IsArrowUp(), PEditInteraction::mKeyEvent, and PPlot::mPlotDataContainer.
bool PVerticalCursorInteraction::Impl_HandleKeyEvent (const PKeyEvent & inEvent) [virtual]
Implements PEditInteraction.
Definition at line 501 of file PPlotInteraction.cpp.
References PKeyEvent::IsArrowDown(), and PKeyEvent::IsArrowUp().
Member Data Documentation
PlotDataIncrementerBounds PVerticalCursorInteraction::mGlobalBounds
Definition at line 272 of file PPlotInteraction.h.
Referenced by HandleVerticalCursorKey().
The documentation for this class was generated from the following files:
PPlotInteraction.h
PPlotInteraction.cpp