Proton: RenderClipComponent Class Reference
RenderClipComponent Class Reference
#include <RenderClipComponent.h>
Public Types
enum eClipMode { CLIP_MODE_LEFT, CLIP_MODE_RIGHT, CLIP_MODE_TOP, CLIP_MODE_BOTTOM }
enum eClipPosition { CLIP_POSITION_FROM_SIZE, CLIP_POSITION_CUSTOM }
Public Member Functions
RenderClipComponent ()
virtual ~RenderClipComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
void FilterOnRender (VariantList *pVList)
void PostOnRender (VariantList *pVList)
Detailed Description
Definition at line 17 of file RenderClipComponent.h.
Member Enumeration Documentation
enum RenderClipComponent::eClipMode
Enumerator:
CLIP_MODE_LEFT
CLIP_MODE_RIGHT
CLIP_MODE_TOP
CLIP_MODE_BOTTOM
Definition at line 29 of file RenderClipComponent.h.
enum RenderClipComponent::eClipPosition
Enumerator:
CLIP_POSITION_FROM_SIZE
CLIP_POSITION_CUSTOM
Definition at line 38 of file RenderClipComponent.h.
Constructor & Destructor Documentation
RenderClipComponent::RenderClipComponent ()
Definition at line 6 of file RenderClipComponent.cpp.
References GetEmulatedPlatformID(), LogError(), PLATFORM_ID_ANDROID, and EntityComponent::SetName().
RenderClipComponent::~RenderClipComponent () [virtual]
Definition at line 16 of file RenderClipComponent.cpp.
Member Function Documentation
void RenderClipComponent::FilterOnRender (VariantList * pVList)
Definition at line 44 of file RenderClipComponent.cpp.
References CLIP_MODE_BOTTOM, CLIP_MODE_LEFT, CLIP_MODE_RIGHT, CLIP_MODE_TOP, Variant::GetVector2(), glClipPlane(), glEnable(), VariantList::m_variant, and rtPlane::plane.
Referenced by OnAdd().
void RenderClipComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 20 of file RenderClipComponent.cpp.
References CLIP_MODE_BOTTOM, FilterOnRender(), Entity::GetFunction(), EntityComponent::GetParent(), Variant::GetUINT32(), Entity::GetVar(), Entity::GetVarWithDefault(), Variant::GetVector2(), Entity::OnFilterAdd(), PostOnRender(), and FunctionObject::sig_function.
void RenderClipComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 38 of file RenderClipComponent.cpp.
References EntityComponent::GetParent(), and Entity::OnFilterRemove().
void RenderClipComponent::PostOnRender (VariantList * pVList)
Definition at line 77 of file RenderClipComponent.cpp.
References RenderBatcher::Flush(), g_globalBatcher, and glDisable().
Referenced by OnAdd().
The documentation for this class was generated from the following files:
RenderClipComponent.h
RenderClipComponent.cpp