Proton: PKeyEvent Class Reference
PKeyEvent Class Reference
#include <PPlotInteraction.h>
Public Types
enum EKey {
kNone, kArrowUp, kArrowDown, kArrowLeft,
kArrowRight, kDelete, kChar
}
Public Member Functions
PKeyEvent (EKey inKey=kNone, int inRepeatCount=0, int inModifierKeys=0, char inChar=0)
bool IsNone () const
bool IsArrowUp () const
bool IsArrowDown () const
bool IsArrowLeft () const
bool IsArrowRight () const
bool IsDelete () const
bool IsChar () const
int GetRepeatCount () const
char GetChar () const
Protected Attributes
EKey mKey
char mChar
int mRepeatCount
Detailed Description
Definition at line 71 of file PPlotInteraction.h.
Member Enumeration Documentation
enum PKeyEvent::EKey
Enumerator:
kNone
kArrowUp
kArrowDown
kArrowLeft
kArrowRight
kDelete
kChar
Definition at line 74 of file PPlotInteraction.h.
Constructor & Destructor Documentation
PKeyEvent::PKeyEvent (EKey inKey = kNone, int inRepeatCount = 0, int inModifierKeys = 0, char inChar = 0)
Definition at line 40 of file PPlotInteraction.cpp.
Member Function Documentation
char PKeyEvent::GetChar () const [inline]
Definition at line 96 of file PPlotInteraction.h.
Referenced by PZoomInteraction::HandleKeyEvent(), and PSelectionInteraction::HandleKeyEvent().
int PKeyEvent::GetRepeatCount () const [inline]
Definition at line 95 of file PPlotInteraction.h.
References mRepeatCount.
bool PKeyEvent::IsArrowDown () const [inline]
Definition at line 89 of file PPlotInteraction.h.
References kArrowDown, and mKey.
Referenced by PVerticalCursorInteraction::HandleVerticalCursorKey(), PVerticalCursorInteraction::Impl_Calculate(), and PVerticalCursorInteraction::Impl_HandleKeyEvent().
bool PKeyEvent::IsArrowLeft () const [inline]
Definition at line 90 of file PPlotInteraction.h.
References kArrowLeft, and mKey.
bool PKeyEvent::IsArrowRight () const [inline]
Definition at line 91 of file PPlotInteraction.h.
References kArrowRight, and mKey.
bool PKeyEvent::IsArrowUp () const [inline]
Definition at line 88 of file PPlotInteraction.h.
References kArrowUp, and mKey.
Referenced by PVerticalCursorInteraction::Impl_Calculate(), and PVerticalCursorInteraction::Impl_HandleKeyEvent().
bool PKeyEvent::IsChar () const [inline]
Definition at line 93 of file PPlotInteraction.h.
References kChar, and mKey.
Referenced by PZoomInteraction::HandleKeyEvent(), and PSelectionInteraction::HandleKeyEvent().
bool PKeyEvent::IsDelete () const [inline]
Definition at line 92 of file PPlotInteraction.h.
References kDelete, and mKey.
Referenced by PDeleteInteraction::Impl_Calculate(), and PDeleteInteraction::Impl_HandleKeyEvent().
bool PKeyEvent::IsNone () const [inline]
Definition at line 87 of file PPlotInteraction.h.
References kNone, and mKey.
Member Data Documentation
char PKeyEvent::mChar [protected]
Definition at line 99 of file PPlotInteraction.h.
EKey PKeyEvent::mKey [protected]
Definition at line 96 of file PPlotInteraction.h.
Referenced by IsArrowDown(), IsArrowLeft(), IsArrowRight(), IsArrowUp(), IsChar(), IsDelete(), and IsNone().
int PKeyEvent::mRepeatCount [protected]
Definition at line 101 of file PPlotInteraction.h.
Referenced by GetRepeatCount().
The documentation for this class was generated from the following files:
PPlotInteraction.h
PPlotInteraction.cpp