Proton: InputTextRenderComponent Class Reference
InputTextRenderComponent Class Reference
#include <InputTextRenderComponent.h>
Public Types
enum eVisualStyle { STYLE_NORMAL, STYLE_PASSWORD }
enum eInputType {
INPUT_TYPE_ASCII, INPUT_TYPE_NUMBERS, INPUT_TYPE_URL, INPUT_TYPE_ASCII_FULL,
INPUT_TYPE_EMAIL
}
enum eInputFiltering { FILTERING_STRICT, FILTERING_LOOSE }
Public Member Functions
InputTextRenderComponent ()
virtual ~InputTextRenderComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
Detailed Description
Definition at line 48 of file InputTextRenderComponent.h.
Member Enumeration Documentation
enum InputTextRenderComponent::eInputFiltering
Enumerator:
FILTERING_STRICT
FILTERING_LOOSE
Definition at line 72 of file InputTextRenderComponent.h.
enum InputTextRenderComponent::eInputType
Enumerator:
INPUT_TYPE_ASCII
INPUT_TYPE_NUMBERS
INPUT_TYPE_URL
INPUT_TYPE_ASCII_FULL
INPUT_TYPE_EMAIL
Definition at line 63 of file InputTextRenderComponent.h.
enum InputTextRenderComponent::eVisualStyle
Enumerator:
STYLE_NORMAL
STYLE_PASSWORD
Definition at line 57 of file InputTextRenderComponent.h.
Constructor & Destructor Documentation
InputTextRenderComponent::InputTextRenderComponent ()
Definition at line 6 of file InputTextRenderComponent.cpp.
References EntityComponent::SetName().
InputTextRenderComponent::~InputTextRenderComponent () [virtual]
Definition at line 11 of file InputTextRenderComponent.cpp.
References GetEntityWithNativeUIFocus(), EntityComponent::GetFunction(), GetIsUsingNativeUI(), EntityComponent::GetParent(), LogMsg(), and FunctionObject::sig_function.
Member Function Documentation
void InputTextRenderComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 27 of file InputTextRenderComponent.cpp.
References FILTERING_STRICT, FONT_SMALL, GetBaseApp(), Variant::GetFloat(), EntityComponent::GetFunction(), Entity::GetFunction(), EntityComponent::GetParent(), Variant::GetSigOnChanged, Variant::GetString(), Variant::GetUINT32(), EntityComponent::GetVar(), Entity::GetVar(), EntityComponent::GetVarWithDefault(), Entity::GetVarWithDefault(), Variant::GetVector2(), INPUT_TYPE_ASCII, BaseApp::m_sig_enterbackground, BaseApp::m_sig_enterforeground, FunctionObject::sig_function, and STYLE_NORMAL.
void InputTextRenderComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 338 of file InputTextRenderComponent.cpp.
The documentation for this class was generated from the following files:
InputTextRenderComponent.h
InputTextRenderComponent.cpp