Proton: StreamingInstanceZip Class Reference
StreamingInstanceZip Class Reference
#include <StreamingInstanceZip.h>
Public Member Functions
StreamingInstanceZip ()
virtual ~StreamingInstanceZip ()
virtual bool Open (string fName)
virtual bool IsFinished ()
virtual int Read (byte *pBufferOut, int maxBytesToRead)
virtual void Close ()
virtual void SeekFromStart (int byteCount)
bool Init (string zipFileName)
void SetRootDirectory (string rootDir)
bool OpenWithCacheEntry (ZipCacheEntry *pCacheEntry)
Detailed Description
Definition at line 17 of file StreamingInstanceZip.h.
Constructor & Destructor Documentation
StreamingInstanceZip::StreamingInstanceZip ()
Definition at line 7 of file StreamingInstanceZip.cpp.
StreamingInstanceZip::~StreamingInstanceZip () [virtual]
Definition at line 14 of file StreamingInstanceZip.cpp.
References Close().
Member Function Documentation
void StreamingInstanceZip::Close () [virtual]
Definition at line 163 of file StreamingInstanceZip.cpp.
References LogError().
Referenced by Open(), OpenWithCacheEntry(), Read(), and ~StreamingInstanceZip().
bool StreamingInstanceZip::Init (string zipFileName)
Definition at line 22 of file StreamingInstanceZip.cpp.
Referenced by FileSystemZip::GetStreaming().
bool StreamingInstanceZip::IsFinished () [virtual]
Implements StreamingInstance.
Definition at line 90 of file StreamingInstanceZip.cpp.
bool StreamingInstanceZip::Open (string fName) [virtual]
Implements StreamingInstance.
Definition at line 65 of file StreamingInstanceZip.cpp.
References Close().
bool StreamingInstanceZip::OpenWithCacheEntry (ZipCacheEntry * pCacheEntry)
Definition at line 79 of file StreamingInstanceZip.cpp.
References Close(), and ZipCacheEntry::m_filepos.
Referenced by FileSystemZip::GetStreaming().
int StreamingInstanceZip::Read (byte * pBufferOut, int maxBytesToRead) [virtual]
Implements StreamingInstance.
Definition at line 105 of file StreamingInstanceZip.cpp.
References Close(), and LogError().
void StreamingInstanceZip::SeekFromStart (int byteCount) [virtual]
Reimplemented from StreamingInstance.
Definition at line 179 of file StreamingInstanceZip.cpp.
void StreamingInstanceZip::SetRootDirectory (string rootDir)
Definition at line 157 of file StreamingInstanceZip.cpp.
Referenced by FileSystemZip::GetStreaming().
The documentation for this class was generated from the following files:
StreamingInstanceZip.h
StreamingInstanceZip.cpp