Proton: HTTPComponent Class Reference
HTTPComponent Class Reference
#include <HTTPComponent.h>
Public Types
enum eState { STATE_IDLE, STATE_CHECKING_CONNECTION, STATE_CONNECTED, STATE_FINISHED }
Public Member Functions
HTTPComponent ()
virtual ~HTTPComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
Detailed Description
Definition at line 16 of file HTTPComponent.h.
Member Enumeration Documentation
enum HTTPComponent::eState
Enumerator:
STATE_IDLE
STATE_CHECKING_CONNECTION
STATE_CONNECTED
STATE_FINISHED
Definition at line 25 of file HTTPComponent.h.
Constructor & Destructor Documentation
HTTPComponent::HTTPComponent ()
Definition at line 8 of file HTTPComponent.cpp.
References EntityComponent::SetName().
HTTPComponent::~HTTPComponent () [virtual]
Definition at line 13 of file HTTPComponent.cpp.
Member Function Documentation
void HTTPComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 17 of file HTTPComponent.cpp.
References GetBaseApp(), EntityComponent::GetFunction(), Entity::GetFunction(), EntityComponent::GetParent(), BaseApp::m_sig_os, FunctionObject::sig_function, and STATE_IDLE.
void HTTPComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 106 of file HTTPComponent.cpp.
The documentation for this class was generated from the following files:
HTTPComponent.h
HTTPComponent.cpp