Proton: LoopingSound Class Reference
LoopingSound Class Reference
#include <LoopingSound.h>
Public Types
enum eState { STATE_IDLE, STATE_MOVE_START, STATE_MOVING, STATE_MOVE_END }
Public Member Functions
LoopingSound ()
virtual ~LoopingSound ()
void Init (string loopingMove, string moveStart="", string moveEnd="", string loopingIdle="")
void SetMoving (bool bNew)
void SetTransitionTimings (int transitionStartMS, int transitionStopMS)
void Update ()
void SetDisabled (bool bDisabled)
Detailed Description
Definition at line 16 of file LoopingSound.h.
Member Enumeration Documentation
enum LoopingSound::eState
Enumerator:
STATE_IDLE
STATE_MOVE_START
STATE_MOVING
STATE_MOVE_END
Definition at line 20 of file LoopingSound.h.
Constructor & Destructor Documentation
LoopingSound::LoopingSound ()
Definition at line 4 of file LoopingSound.cpp.
References STATE_IDLE.
LoopingSound::~LoopingSound () [virtual]
Definition at line 15 of file LoopingSound.cpp.
Member Function Documentation
void LoopingSound::Init (string loopingMove, string moveStart = "", string moveEnd = "", string loopingIdle = "")
Definition at line 54 of file LoopingSound.cpp.
References GetAudioManager(), and AudioManager::Preload().
void LoopingSound::SetDisabled (bool bDisabled)
Definition at line 186 of file LoopingSound.cpp.
References STATE_IDLE.
void LoopingSound::SetMoving (bool bNew)
Definition at line 84 of file LoopingSound.cpp.
References GetAudioManager(), GetTick(), AudioManager::Play(), STATE_MOVE_END, STATE_MOVE_START, and TIMER_SYSTEM.
void LoopingSound::SetTransitionTimings (int transitionStartMS, int transitionStopMS)
Definition at line 179 of file LoopingSound.cpp.
void LoopingSound::Update ()
Definition at line 127 of file LoopingSound.cpp.
References GetAudioManager(), GetEmulatedPlatformID(), GetTick(), PLATFORM_ID_WEBOS, STATE_IDLE, STATE_MOVE_END, STATE_MOVE_START, AudioManager::Stop(), and TIMER_SYSTEM.
The documentation for this class was generated from the following files:
LoopingSound.h
LoopingSound.cpp