Proton: PointerEventHandler Class Reference
PointerEventHandler Class Reference
#include <PointerEventHandler.h>
Public Member Functions
virtual ~PointerEventHandler ()
virtual void handlePointerDownEvent (float x, float y, unsigned int pointerId)=0
virtual void handlePointerMoveEvent (float x, float y, unsigned int pointerId)=0
virtual void handlePointerUpEvent (float x, float y, unsigned int pointerId)=0
Detailed Description
Definition at line 4 of file PointerEventHandler.h.
Constructor & Destructor Documentation
virtual PointerEventHandler::~PointerEventHandler () [inline, virtual]
Definition at line 7 of file PointerEventHandler.h.
Member Function Documentation
virtual void PointerEventHandler::handlePointerDownEvent (float x, float y, unsigned int pointerId) [pure virtual]
Implemented in TouchDeviceEmulatorPointerEventHandler, and PassThroughPointerEventHandler.
Referenced by SDLEventLoop().
virtual void PointerEventHandler::handlePointerMoveEvent (float x, float y, unsigned int pointerId) [pure virtual]
Implemented in TouchDeviceEmulatorPointerEventHandler, and PassThroughPointerEventHandler.
Referenced by SDLEventLoop().
virtual void PointerEventHandler::handlePointerUpEvent (float x, float y, unsigned int pointerId) [pure virtual]
Implemented in TouchDeviceEmulatorPointerEventHandler, and PassThroughPointerEventHandler.
Referenced by SDLEventLoop().
The documentation for this class was generated from the following file:
PointerEventHandler.h