Proton: L_Particle Class Reference
L_Particle Class Reference
Particle entity for being attached to ParticleEffect.
#include <L_Particle.h>
Public Member Functions
L_Particle ()
L_Particle (const L_Particle &par)
Copy contructor (it does not copy all variables)
L_Particle (SurfaceAnim *surface_t, int life_t)
Contructor
life_t : pass L_INFINITE_LIFE to have infinite life particle.
~L_Particle ()
void copy_from (const L_Particle &par)
void set_size (L_REAL size)
Set the current size and reference size of particle, the sizing effect is relative to reference size.
void set_life (int life_t)
Set life in miliseconds, pass L_INFINITE_LIFE for infinite life.
void set_color (const L_Color &color)
void set_color (const char a, const char r, const char g, const char b)
void set_velocity (const CL_Vec2f &v_t)
void set_position (L_REAL x, L_REAL y)
void set_rotation (L_REAL radian)
void set_rotation2 (L_REAL radian)
Only use this when rotating2() is used.
void set_motion_controller (L_MotionController *motion_ctr)
Assign motion controller for complex motion.
void set_blending_mode (Surface::eBlendingMode mode)
Set blending mode of particle.
void set_prerun_callback (L_PRERUN_USERFUNC *user_func, void *user_data)
Set user call back function.
void set_delete_surface (bool bDelete)
void set_delete_motion_controller (bool bDelete)
void remove (void)
This particle will be removed in run(int) after this function has been called.
void coloring1 (const L_Color &color1_t, L_REAL begin_at=0)
Set coloring effect, particle changes from current color(at "begin_at") to "color1_t"(at the end).
void coloring2 (const L_Color &color1_t, const L_Color &color2_t, L_REAL begin_at=0)
Set coloring effect, color of particle changes from color1(at "begin_at") to "color2"(at the end).
void coloring3 (const L_Color &color1_t, const L_Color &color2_t, unsigned int switch_time_t, L_REAL begin_at=0)
Set coloring effect, particle keeps switching colors with duration of "switch_time_t"(in milisecs).
void sizing1 (L_REAL size_r, L_REAL begin_at=0)
Set sizing effect, particle changes from current size(at "begin_at") to "size_r"(at the end).
void sizing2 (L_REAL size_r1, L_REAL size_r2, L_REAL begin_at=0)
Set sizing effect, the size of particle changes from "size_r1"(at "begin_at") to "size_r2"(at the end).
void sizing3 (L_REAL size_r, L_REAL begin_at=0)
Set sizing effect, the size of particle changes in amount of "size_r" value every milisecs.
void rotating1 (L_REAL radian_t, L_REAL begin_at=0)
Set rotating effect, particle rotates in amount of "radian_t" every cycle.
void rotating2 (L_REAL radian_t, L_REAL begin_at=0)
Set rotating effect, particle rotates in total amount of "radian_t" in its life.
void rotating3 (L_REAL begin_at=0)
Set rotating effect, particle rotates in randomly.
void rotating4 (L_REAL begin_at=0)
Set rotating effect, particle always face to the direction of its velocity.
void disable_coloring (void)
Disable coloring effect.
void disable_sizing (void)
Disable sizing effect.
void disable_rotating (void)
Disable rotating effect.
L_REAL get_size (void)
L_REAL get_ref_size (void)
L_REAL get_radian (void)
CL_Vec2f get_velocity (void)
int get_remaininig_life (void)
bool is_alive (void)
L_MotionController * get_motion_controller ()
void initialize (void)
void run (int time_elapesed_t)
Pass frame time for this function to activate the particle.
void draw (int x_shift=0, int y_shift=0, float x_size_mod=1, float y_size_mod=1)
Draw particle with screen position shift options.
void Setup (SurfaceAnim *surf, int life_t)
Public Attributes
SurfaceAnim * surface
L_REAL x_pos
L_REAL y_pos
L_Color current_color
Detailed Description
Particle entity for being attached to ParticleEffect.
Definition at line 83 of file L_Particle.h.
Constructor & Destructor Documentation
L_Particle::L_Particle ()
Definition at line 31 of file L_Particle.cpp.
L_Particle::L_Particle (const L_Particle & par)
Copy contructor (it does not copy all variables)
Definition at line 43 of file L_Particle.cpp.
References L_Color::a, L_Color::b, current_color, L_Color::g, L_Color::r, set_color(), and surface.
L_Particle::L_Particle (SurfaceAnim * surface_t, int life_t)
Contructor
life_t : pass L_INFINITE_LIFE to have infinite life particle.
Definition at line 136 of file L_Particle.cpp.
References Setup().
L_Particle::~L_Particle ()
Definition at line 145 of file L_Particle.cpp.
References surface.
Member Function Documentation
void L_Particle::coloring1 (const L_Color & color1_t, L_REAL begin_at = 0)
Set coloring effect, particle changes from current color(at "begin_at") to "color1_t"(at the end).
Definition at line 327 of file L_Particle.cpp.
References L_Color::a, L_Color::b, current_color, L_Color::g, and L_Color::r.
void L_Particle::coloring2 (const L_Color & color1_t, const L_Color & color2_t, L_REAL begin_at = 0)
Set coloring effect, color of particle changes from color1(at "begin_at") to "color2"(at the end).
Definition at line 346 of file L_Particle.cpp.
References L_Color::a, L_Color::b, L_Color::g, and L_Color::r.
void L_Particle::coloring3 (const L_Color & color1_t, const L_Color & color2_t, unsigned int switch_time_t, L_REAL begin_at = 0)
Set coloring effect, particle keeps switching colors with duration of "switch_time_t"(in milisecs).
Definition at line 365 of file L_Particle.cpp.
References L_Color::a, L_Color::b, L_Color::g, and L_Color::r.
void L_Particle::copy_from (const L_Particle & par)
Definition at line 153 of file L_Particle.cpp.
References L_Color::a, L_Color::b, current_color, L_Color::g, L_Color::r, set_color(), and surface.
void L_Particle::disable_coloring (void)
Disable coloring effect.
Definition at line 457 of file L_Particle.cpp.
void L_Particle::disable_rotating (void)
Disable rotating effect.
Definition at line 469 of file L_Particle.cpp.
void L_Particle::disable_sizing (void)
Disable sizing effect.
Definition at line 463 of file L_Particle.cpp.
void L_Particle::draw (int x_shift = 0, int y_shift = 0, float x_size_mod = 1, float y_size_mod = 1)
Draw particle with screen position shift options.
Definition at line 684 of file L_Particle.cpp.
References L_Color::a, ALIGNMENT_CENTER, L_Color::b, current_color, L_Color::g, g_globalBatcher, L_Color::r, x_pos, and y_pos.
L_MotionController* L_Particle::get_motion_controller () [inline]
Definition at line 283 of file L_Particle.h.
L_REAL L_Particle::get_radian (void)
Definition at line 487 of file L_Particle.cpp.
L_REAL L_Particle::get_ref_size (void)
Definition at line 481 of file L_Particle.cpp.
Referenced by L_ParticleEffect::create_particle().
int L_Particle::get_remaininig_life (void)
Definition at line 499 of file L_Particle.cpp.
Referenced by L_ParticleEffect::create_particle().
L_REAL L_Particle::get_size (void)
Definition at line 475 of file L_Particle.cpp.
CL_Vec2f L_Particle::get_velocity (void)
Definition at line 493 of file L_Particle.cpp.
void L_Particle::initialize (void)
Definition at line 648 of file L_Particle.cpp.
Referenced by L_ParticleEffect::create_particle().
bool L_Particle::is_alive (void)
Definition at line 505 of file L_Particle.cpp.
void L_Particle::remove (void)
This particle will be removed in run(int) after this function has been called.
Definition at line 303 of file L_Particle.cpp.
void L_Particle::rotating1 (L_REAL radian_t, L_REAL begin_at = 0)
Set rotating effect, particle rotates in amount of "radian_t" every cycle.
Definition at line 418 of file L_Particle.cpp.
void L_Particle::rotating2 (L_REAL radian_t, L_REAL begin_at = 0)
Set rotating effect, particle rotates in total amount of "radian_t" in its life.
Definition at line 428 of file L_Particle.cpp.
void L_Particle::rotating3 (L_REAL begin_at = 0)
Set rotating effect, particle rotates in randomly.
Definition at line 439 of file L_Particle.cpp.
void L_Particle::rotating4 (L_REAL begin_at = 0)
Set rotating effect, particle always face to the direction of its velocity.
Definition at line 448 of file L_Particle.cpp.
void L_Particle::run (int time_elapesed_t)
Pass frame time for this function to activate the particle.
Definition at line 661 of file L_Particle.cpp.
void L_Particle::set_blending_mode (Surface::eBlendingMode mode)
Set blending mode of particle.
Definition at line 289 of file L_Particle.cpp.
void L_Particle::set_color (const L_Color & color)
Definition at line 233 of file L_Particle.cpp.
References L_Color::a, L_Color::b, current_color, L_Color::g, and L_Color::r.
Referenced by copy_from(), and L_Particle().
void L_Particle::set_color (const char a, const char r, const char g, const char b)
Definition at line 242 of file L_Particle.cpp.
References L_Color::a, L_Color::b, current_color, L_Color::g, and L_Color::r.
void L_Particle::set_delete_motion_controller (bool bDelete) [inline]
Definition at line 208 of file L_Particle.h.
void L_Particle::set_delete_surface (bool bDelete) [inline]
Definition at line 203 of file L_Particle.h.
void L_Particle::set_life (int life_t)
Set life in miliseconds, pass L_INFINITE_LIFE for infinite life.
Definition at line 217 of file L_Particle.cpp.
Referenced by L_ParticleEffect::create_particle().
void L_Particle::set_motion_controller (L_MotionController * motion_ctr)
Assign motion controller for complex motion.
Definition at line 284 of file L_Particle.cpp.
void L_Particle::set_position (L_REAL x, L_REAL y)
Definition at line 264 of file L_Particle.cpp.
References x_pos, and y_pos.
void L_Particle::set_prerun_callback (L_PRERUN_USERFUNC * user_func, void * user_data)
Set user call back function.
The user function is called at least once per frame before calling run(int).
L_PRERUN_USERFUNC :
void callback_function(L_Particle& particle, const void* user_data)
Definition at line 296 of file L_Particle.cpp.
void L_Particle::set_rotation (L_REAL radian)
Definition at line 271 of file L_Particle.cpp.
Referenced by L_ParticleEffect::create_particle().
void L_Particle::set_rotation2 (L_REAL radian)
Only use this when rotating2() is used.
This function would reset the initial rotation
set by rotating2().
Definition at line 277 of file L_Particle.cpp.
Referenced by L_ParticleEffect::create_particle().
void L_Particle::set_size (L_REAL size)
Set the current size and reference size of particle, the sizing effect is relative to reference size.
Definition at line 207 of file L_Particle.cpp.
Referenced by L_ParticleEffect::create_particle().
void L_Particle::set_velocity (const CL_Vec2f & v_t)
Definition at line 251 of file L_Particle.cpp.
References L_1D_ACCELERATION, and linear_set_magnitude().
Referenced by L_ParticleEffect::create_particle().
void L_Particle::Setup (SurfaceAnim * surf, int life_t)
Definition at line 96 of file L_Particle.cpp.
References L_Color::a, L_Color::b, Surface::BLENDING_ADDITIVE, current_color, L_Color::g, L_Color::r, Surface::SetBlendingMode(), x_pos, and y_pos.
Referenced by L_Particle().
void L_Particle::sizing1 (L_REAL size_r, L_REAL begin_at = 0)
Set sizing effect, particle changes from current size(at "begin_at") to "size_r"(at the end).
Definition at line 386 of file L_Particle.cpp.
void L_Particle::sizing2 (L_REAL size_r1, L_REAL size_r2, L_REAL begin_at = 0)
Set sizing effect, the size of particle changes from "size_r1"(at "begin_at") to "size_r2"(at the end).
Definition at line 397 of file L_Particle.cpp.
void L_Particle::sizing3 (L_REAL size_r, L_REAL begin_at = 0)
Set sizing effect, the size of particle changes in amount of "size_r" value every milisecs.
No Zero Limit
Definition at line 408 of file L_Particle.cpp.
Member Data Documentation
L_Color L_Particle::current_color
Definition at line 151 of file L_Particle.h.
Referenced by coloring1(), copy_from(), draw(), L_Particle(), set_color(), and Setup().
SurfaceAnim* L_Particle::surface
Definition at line 148 of file L_Particle.h.
Referenced by copy_from(), L_Particle(), and ~L_Particle().
L_REAL L_Particle::x_pos
Definition at line 149 of file L_Particle.h.
Referenced by L_ParticleEffect::create_particle(), draw(), set_position(), and Setup().
L_REAL L_Particle::y_pos
Definition at line 150 of file L_Particle.h.
Referenced by L_ParticleEffect::create_particle(), draw(), set_position(), and Setup().
The documentation for this class was generated from the following files:
L_Particle.h
L_Particle.cpp