Proton: IAPManager Class Reference
IAPManager Class Reference
A class for doing in-app purchases (IAP).
#include <IAPManager.h>
Public Types
enum eReturnState {
RETURN_STATE_NONE, RETURN_STATE_FAILED, RETURN_STATE_PURCHASED, RETURN_STATE_ALREADY_PURCHASED,
RETURN_STATE_REFUNDED
}
The result of a purchase process.
enum eFailureReason { FAILURE_REASON_NONE, FAILURE_REASON_USER_CANCELED }
Explanation reason for a failed purchase.
enum ResponseCode {
RESULT_OK, RESULT_USER_CANCELED, RESULT_SERVICE_UNAVAILABLE, RESULT_BILLING_UNAVAILABLE,
RESULT_ITEM_UNAVAILABLE, RESULT_DEVELOPER_ERROR, RESULT_ERROR, RESULT_OK_ALREADY_PURCHASED
}
enum ItemStateCode {
ITEM_STATE_ERROR = -2, END_OF_LIST = -1, PURCHASED, CANCELED,
REFUNDED
}
Public Member Functions
IAPManager ()
virtual ~IAPManager ()
bool Init ()
void Update ()
void OnMessage (Message &m)
Use this to pass messages for the IAPManager to handle.
eReturnState GetReturnState () const
Gets the state of the last finished purchase process.
eFailureReason GetFailureReason () const
Gets the detailed reason for a failed purchase.
void BuyItem (const std::string &itemName)
Starts a purchasing process for the given itemName.
bool IsItemPurchased (const std::string &item) const
void Reset ()
Resets the state of the IAPManager.
std::string GetExtraData () const
The extra data is platform dependent details about the purchase.
std::string GetItemID () const
Returns the last item name BuyItem() was called with.
void SyncPurchases ()
Refreshes any previous and outstanding purchases and causes IsItemPurchased() to return valid results.
void TestDelayedIAP (string itemID, string receipt, int delayMS, eReturnState returnState=RETURN_STATE_PURCHASED)
For testing only - Mimics behavior of getting a delayed purchase (applicable to android only), m_sig_item_unexpected_purchase_result will get hit with the call after the delayMS has been reached.
Public Attributes
boost::signal< void(VariantList *) m_sig_item_purchase_result)
A signal for reporting changes in the purchasing process, when waiting for a buy request to happen.
boost::signal< void(VariantList *) m_sig_item_unexpected_purchase_result)
A signal for reporting an unexpected purchase or refund (happens on android only so far, and can happen at ANY TIME the app is running)
boost::signal< void(VariantList *) m_sig_purchased_list_updated)
A signal for reporting that the previous purchases are now known and IsItemPurchased() returns correct results.
Protected Types
enum eState { STATE_NONE, STATE_WAITING }
Protected Member Functions
void sendPurchaseMessage ()
void endPurchaseProcessWithResult (eReturnState returnState)
Changes the state of the purchasing process and sends the m_sig_item_purchase_result signal.
void HandlePurchaseListReply (Message &m)
void HandleIAPBuyResult (Message &m)
void HandleItemUpdateState (Message &m)
void SendUnexpectedPurchaseSignal (eReturnState returnState, string itemID, string extra)
Protected Attributes
eState m_state
eReturnState m_returnState
eFailureReason m_failureReason
unsigned int m_timer
std::set< std::string > m_items
std::string m_itemToBuy
std::string m_extraData
bool m_bWaitingForReply
std::string m_lastItemID
bool m_bGettingItemList
Entity m_entity
Detailed Description
A class for doing in-app purchases (IAP).
This manager can be used to make an IAP for a single item at a time. It can also be used to check if some item has already been purchased.
An IAP process is started for an item with BuyItem(). Later on the IAPManager tells how the purchase ended. The end result can be received by listening to the m_sig_item_purchase_result signal or using the various state methods of the class.
Definition at line 28 of file IAPManager.h.
Member Enumeration Documentation
enum IAPManager::eFailureReason
Explanation reason for a failed purchase.
Enumerator:
FAILURE_REASON_NONE
Either there was no failure or the reason is not known.
FAILURE_REASON_USER_CANCELED
The user canceled the purchase.
Definition at line 49 of file IAPManager.h.
enum IAPManager::eReturnState
The result of a purchase process.
Enumerator:
RETURN_STATE_NONE
No result available.
This is used e.g. when no purchases have been initiated yet.
RETURN_STATE_FAILED
The purchase process has failed.
RETURN_STATE_PURCHASED
The purchase process has finished successfully.
RETURN_STATE_ALREADY_PURCHASED
The item has been purchased already previously.
Applicable to managed items.
RETURN_STATE_REFUNDED
The item has been refunded - only applicable to android and if you listen to m_sig_item_unexpected_purchase_result.
Definition at line 37 of file IAPManager.h.
enum IAPManager::eState [protected]
Enumerator:
STATE_NONE
STATE_WAITING
Definition at line 178 of file IAPManager.h.
enum IAPManager::ItemStateCode
Enumerator:
ITEM_STATE_ERROR
END_OF_LIST
PURCHASED
CANCELED
REFUNDED
Definition at line 161 of file IAPManager.h.
enum IAPManager::ResponseCode
Enumerator:
RESULT_OK
RESULT_USER_CANCELED
RESULT_SERVICE_UNAVAILABLE
RESULT_BILLING_UNAVAILABLE
RESULT_ITEM_UNAVAILABLE
RESULT_DEVELOPER_ERROR
RESULT_ERROR
RESULT_OK_ALREADY_PURCHASED
Definition at line 111 of file IAPManager.h.
Constructor & Destructor Documentation
IAPManager::IAPManager ()
Definition at line 21 of file IAPManager.cpp.
References FAILURE_REASON_NONE, Entity::GetFunction(), m_bGettingItemList, m_bWaitingForReply, m_entity, m_failureReason, m_returnState, m_sig_item_unexpected_purchase_result, m_state, m_timer, RETURN_STATE_NONE, FunctionObject::sig_function, and STATE_NONE.
IAPManager::~IAPManager () [virtual]
Definition at line 34 of file IAPManager.cpp.
Member Function Documentation
void IAPManager::BuyItem (const std::string & itemName)
Starts a purchasing process for the given itemName.
Definition at line 274 of file IAPManager.cpp.
References BaseApp::AddOSMessage(), GetBaseApp(), GetEmulatedPlatformID(), LogMsg(), m_items, m_itemToBuy, m_lastItemID, m_state, OSMessage::m_type, OSMessage::MESSAGE_IAP_GET_PURCHASED_LIST, PLATFORM_ID_ANDROID, Reset(), sendPurchaseMessage(), and STATE_WAITING.
void IAPManager::endPurchaseProcessWithResult (eReturnState returnState) [protected]
Changes the state of the purchasing process and sends the m_sig_item_purchase_result signal.
Definition at line 338 of file IAPManager.cpp.
References m_extraData, m_failureReason, m_lastItemID, m_returnState, m_sig_item_purchase_result, m_state, and STATE_NONE.
Referenced by HandleIAPBuyResult(), HandleItemUpdateState(), and HandlePurchaseListReply().
std::string IAPManager::GetExtraData () const [inline]
The extra data is platform dependent details about the purchase.
It can be for example the order# or receipt.
Definition at line 95 of file IAPManager.h.
References m_extraData.
eFailureReason IAPManager::GetFailureReason () const [inline]
Gets the detailed reason for a failed purchase.
The value returned by this method is only interesting when GetReturnState() returns RETURN_STATE_FAILED. If a purchase has not failed then this method returs FAILURE_REASON_NONE.
Definition at line 78 of file IAPManager.h.
References m_failureReason.
std::string IAPManager::GetItemID () const [inline]
Returns the last item name BuyItem() was called with.
Definition at line 100 of file IAPManager.h.
References m_lastItemID.
eReturnState IAPManager::GetReturnState () const [inline]
Gets the state of the last finished purchase process.
If a purchase process is in progress or hasn't been initiated yet then the state is RETURN_STATE_NONE.
Definition at line 69 of file IAPManager.h.
References m_returnState.
void IAPManager::HandleIAPBuyResult (Message & m) [protected]
Definition at line 114 of file IAPManager.cpp.
References endPurchaseProcessWithResult(), FAILURE_REASON_USER_CANCELED, Message::GetParm1(), Message::GetStringParm(), LogMsg(), m_extraData, m_failureReason, m_itemToBuy, RESULT_OK, RESULT_OK_ALREADY_PURCHASED, RESULT_USER_CANCELED, RETURN_STATE_ALREADY_PURCHASED, RETURN_STATE_FAILED, and RETURN_STATE_PURCHASED.
Referenced by OnMessage().
void IAPManager::HandleItemUpdateState (Message & m) [protected]
Definition at line 140 of file IAPManager.cpp.
References CANCELED, END_OF_LIST, endPurchaseProcessWithResult(), Message::GetParm1(), Message::GetStringParm(), LogMsg(), m_state, PURCHASED, REFUNDED, RETURN_STATE_FAILED, RETURN_STATE_PURCHASED, RETURN_STATE_REFUNDED, SendUnexpectedPurchaseSignal(), and STATE_WAITING.
Referenced by OnMessage().
void IAPManager::HandlePurchaseListReply (Message & m) [protected]
Definition at line 43 of file IAPManager.cpp.
References CANCELED, END_OF_LIST, endPurchaseProcessWithResult(), Message::GetParm1(), Message::GetStringParm(), IsItemPurchased(), LogMsg(), m_items, m_itemToBuy, m_sig_purchased_list_updated, PURCHASED, REFUNDED, RETURN_STATE_ALREADY_PURCHASED, and sendPurchaseMessage().
Referenced by OnMessage().
bool IAPManager::Init ()
Definition at line 233 of file IAPManager.cpp.
bool IAPManager::IsItemPurchased (const std::string & item) const
Definition at line 38 of file IAPManager.cpp.
References m_items.
Referenced by HandlePurchaseListReply().
void IAPManager::OnMessage (Message & m)
Use this to pass messages for the IAPManager to handle.
Note:
This needs to be called in order for the system to work at all!
Definition at line 205 of file IAPManager.cpp.
References Message::GetType(), HandleIAPBuyResult(), HandleItemUpdateState(), HandlePurchaseListReply(), MESSAGE_TYPE_IAP_ITEM_STATE, MESSAGE_TYPE_IAP_PURCHASED_LIST_STATE, and MESSAGE_TYPE_IAP_RESULT.
void IAPManager::Reset ()
Resets the state of the IAPManager.
Definition at line 313 of file IAPManager.cpp.
References FAILURE_REASON_NONE, m_extraData, m_failureReason, m_returnState, m_state, m_timer, RETURN_STATE_NONE, and STATE_NONE.
Referenced by BuyItem().
void IAPManager::sendPurchaseMessage () [protected]
Definition at line 322 of file IAPManager.cpp.
References BaseApp::AddOSMessage(), GetBaseApp(), GetTick(), m_bWaitingForReply, m_itemToBuy, m_state, OSMessage::m_string, m_timer, OSMessage::m_type, OSMessage::MESSAGE_IAP_PURCHASE, STATE_WAITING, and TIMER_SYSTEM.
Referenced by BuyItem(), and HandlePurchaseListReply().
void IAPManager::SendUnexpectedPurchaseSignal (eReturnState returnState, string itemID, string extra) [protected]
Definition at line 104 of file IAPManager.cpp.
References LogMsg(), and m_sig_item_unexpected_purchase_result.
Referenced by HandleItemUpdateState().
void IAPManager::SyncPurchases ()
Refreshes any previous and outstanding purchases and causes IsItemPurchased() to return valid results.
The synchronization happens asynchronously. When it's done m_sig_purchased_list_updated gets signaled.
Definition at line 346 of file IAPManager.cpp.
References BaseApp::AddOSMessage(), GetBaseApp(), LogMsg(), m_items, OSMessage::m_type, and OSMessage::MESSAGE_IAP_GET_PURCHASED_LIST.
void IAPManager::TestDelayedIAP (string itemID, string receipt, int delayMS, eReturnState returnState = RETURN_STATE_PURCHASED)
For testing only - Mimics behavior of getting a delayed purchase (applicable to android only), m_sig_item_unexpected_purchase_result will get hit with the call after the delayMS has been reached.
It's ok to schedule multiple items at once.
Definition at line 356 of file IAPManager.cpp.
References MessageManager::CallEntityFunction(), GetMessageManager(), m_entity, and TIMER_SYSTEM.
void IAPManager::Update ()
Definition at line 238 of file IAPManager.cpp.
References GetMessageManager(), GetTick(), LogMsg(), m_bWaitingForReply, m_timer, MESSAGE_TYPE_IAP_RESULT, RESULT_ERROR, RESULT_OK, RESULT_OK_ALREADY_PURCHASED, RESULT_USER_CANCELED, MessageManager::SendGUIStringEx(), and TIMER_SYSTEM.
Member Data Documentation
bool IAPManager::m_bGettingItemList [protected]
Definition at line 206 of file IAPManager.h.
Referenced by IAPManager().
bool IAPManager::m_bWaitingForReply [protected]
Definition at line 203 of file IAPManager.h.
Referenced by IAPManager(), sendPurchaseMessage(), and Update().
Entity IAPManager::m_entity [protected]
Definition at line 208 of file IAPManager.h.
Referenced by IAPManager(), and TestDelayedIAP().
std::string IAPManager::m_extraData [protected]
Definition at line 202 of file IAPManager.h.
Referenced by endPurchaseProcessWithResult(), GetExtraData(), HandleIAPBuyResult(), and Reset().
eFailureReason IAPManager::m_failureReason [protected]
Definition at line 197 of file IAPManager.h.
Referenced by endPurchaseProcessWithResult(), GetFailureReason(), HandleIAPBuyResult(), IAPManager(), and Reset().
std::set<std::string> IAPManager::m_items [protected]
Definition at line 200 of file IAPManager.h.
Referenced by BuyItem(), HandlePurchaseListReply(), IsItemPurchased(), and SyncPurchases().
std::string IAPManager::m_itemToBuy [protected]
Definition at line 201 of file IAPManager.h.
Referenced by BuyItem(), HandleIAPBuyResult(), HandlePurchaseListReply(), and sendPurchaseMessage().
std::string IAPManager::m_lastItemID [protected]
Definition at line 204 of file IAPManager.h.
Referenced by BuyItem(), endPurchaseProcessWithResult(), and GetItemID().
eReturnState IAPManager::m_returnState [protected]
Definition at line 196 of file IAPManager.h.
Referenced by endPurchaseProcessWithResult(), GetReturnState(), IAPManager(), and Reset().
boost::signal<void (VariantList*) IAPManager::m_sig_item_purchase_result)
A signal for reporting changes in the purchasing process, when waiting for a buy request to happen.
The parameter variant list contains the following items:
0: the return code of type eReturnState as a uint. See GetReturnState().
1: a string that gives more information about the result. This might depend on the platform. See GetExtraData().
2: the item id in question (as a string). See GetItemID().
3: if parameter 0 is RETURN_STATE_FAILED then this parameter contains the detailed failure reason if it's known. The type of this parameter is eFailureReason as a uint. See GetFailureReason().
Definition at line 138 of file IAPManager.h.
Referenced by endPurchaseProcessWithResult().
boost::signal<void (VariantList*) IAPManager::m_sig_item_unexpected_purchase_result)
A signal for reporting an unexpected purchase or refund (happens on android only so far, and can happen at ANY TIME the app is running)
The parameter variant list contains the following items:
0: the return code of type eReturnState as a uint. See GetReturnState().
1: a string that gives more information about the result. (currently unused)
2: the item id in question (as a string)
Definition at line 150 of file IAPManager.h.
Referenced by IAPManager(), and SendUnexpectedPurchaseSignal().
boost::signal<void (VariantList*) IAPManager::m_sig_purchased_list_updated)
A signal for reporting that the previous purchases are now known and IsItemPurchased() returns correct results.
The parameter variant list contains no items.
Definition at line 159 of file IAPManager.h.
Referenced by HandlePurchaseListReply().
eState IAPManager::m_state [protected]
Definition at line 195 of file IAPManager.h.
Referenced by BuyItem(), endPurchaseProcessWithResult(), HandleItemUpdateState(), IAPManager(), Reset(), and sendPurchaseMessage().
unsigned int IAPManager::m_timer [protected]
Definition at line 198 of file IAPManager.h.
Referenced by IAPManager(), Reset(), sendPurchaseMessage(), and Update().
The documentation for this class was generated from the following files:
IAPManager.h
IAPManager.cpp