Proton: UnderlineRenderComponent Class Reference
UnderlineRenderComponent Class Reference
#include <UnderlineRenderComponent.h>
Public Member Functions
UnderlineRenderComponent ()
virtual ~UnderlineRenderComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
Detailed Description
Definition at line 17 of file UnderlineRenderComponent.h.
Constructor & Destructor Documentation
UnderlineRenderComponent::UnderlineRenderComponent ()
Definition at line 6 of file UnderlineRenderComponent.cpp.
References EntityComponent::SetName().
UnderlineRenderComponent::~UnderlineRenderComponent () [virtual]
Definition at line 11 of file UnderlineRenderComponent.cpp.
Member Function Documentation
void UnderlineRenderComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 15 of file UnderlineRenderComponent.cpp.
References Variant::GetFloat(), Entity::GetFunction(), EntityComponent::GetParent(), Variant::GetUINT32(), Entity::GetVar(), Entity::GetVarWithDefault(), Variant::GetVector2(), and FunctionObject::sig_function.
void UnderlineRenderComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 34 of file UnderlineRenderComponent.cpp.
The documentation for this class was generated from the following files:
UnderlineRenderComponent.h
UnderlineRenderComponent.cpp