Proton: GamepadiCade Class Reference
GamepadiCade Class Reference
#include <GamepadiCade.h>
Public Member Functions
GamepadiCade ()
virtual ~GamepadiCade ()
virtual bool Init ()
virtual void Kill ()
virtual void Update ()
Detailed Description
Definition at line 58 of file GamepadiCade.h.
Constructor & Destructor Documentation
GamepadiCade::GamepadiCade ()
Definition at line 19 of file GamepadiCade.cpp.
GamepadiCade::~GamepadiCade () [virtual]
Definition at line 26 of file GamepadiCade.cpp.
References Kill().
Member Function Documentation
bool GamepadiCade::Init () [virtual]
Implements Gamepad.
Definition at line 67 of file GamepadiCade.cpp.
References GetBaseApp(), KEY_ARCADE_BUTTON_COUNT, KEY_ARCADE_BUTTON_DOWN, KEY_ARCADE_BUTTON_L, KEY_ARCADE_BUTTON_LEFT, KEY_ARCADE_BUTTON_R, KEY_ARCADE_BUTTON_RIGHT, KEY_ARCADE_BUTTON_UP, KEY_ARCADE_DIR_DOWN, KEY_ARCADE_DIR_LEFT, KEY_ARCADE_DIR_RIGHT, KEY_ARCADE_DIR_UP, KEY_ARCADE_TRIGGER_L, KEY_ARCADE_TRIGGER_R, Gamepad::m_axisUsedCount, Gamepad::m_buttonsUsedCount, Gamepad::m_name, BaseApp::m_sig_hardware, BaseApp::m_sig_raw_keyboard, ArcadeKeyboardControl::Setup(), VIRTUAL_DPAD_BUTTON_DOWN, VIRTUAL_DPAD_BUTTON_LEFT, VIRTUAL_DPAD_BUTTON_RIGHT, VIRTUAL_DPAD_BUTTON_UP, VIRTUAL_DPAD_LBUTTON, VIRTUAL_DPAD_LTRIGGER, VIRTUAL_DPAD_RBUTTON, VIRTUAL_DPAD_RTRIGGER, VIRTUAL_KEY_DIR_DOWN, VIRTUAL_KEY_DIR_LEFT, VIRTUAL_KEY_DIR_RIGHT, and VIRTUAL_KEY_DIR_UP.
void GamepadiCade::Kill () [virtual]
Implements Gamepad.
Definition at line 169 of file GamepadiCade.cpp.
Referenced by ~GamepadiCade().
void GamepadiCade::Update () [virtual]
Reimplemented from Gamepad.
Definition at line 235 of file GamepadiCade.cpp.
References KEY_ARCADE_DIR_DOWN, KEY_ARCADE_DIR_LEFT, KEY_ARCADE_DIR_RIGHT, KEY_ARCADE_DIR_UP, and Gamepad::SetAxis().
The documentation for this class was generated from the following files:
GamepadiCade.h
GamepadiCade.cpp