Proton: Surface Class Reference
Surface Class Reference
#include <Surface.h>
Public Types
enum eTextureType { TYPE_DEFAULT, TYPE_GUI, TYPE_NOT_OWNER, TYPE_NO_SMOOTHING }
Type for the texture that the Surface class uses.
enum eBlendingMode {
BLENDING_NORMAL, BLENDING_ADDITIVE, BLENDING_PREMULTIPLIED_ALPHA, BLENDING_MULTIPLY,
BLENDING_DARKEN
}
Public Member Functions
Surface ()
Surface (string fName)
Surface (string fName, eTextureType type)
virtual ~Surface ()
bool LoadFile (string fName, bool bAddBasePath=true)
virtual bool LoadFileFromMemory (byte *pMem, int inputSize=0)
void Bind ()
bool IsLoaded ()
bool UsesAlpha ()
void SetUsesAlpha (bool bNew)
int GetWidth ()
int GetHeight ()
int GetRawTextureWidth ()
int GetRawTextureHeight ()
void SetTextureType (eTextureType type)
Sets the texture type for this Surface.
virtual void Blit (float x, float y, unsigned int rgba=MAKE_RGBA(255, 255, 255, 255), float rotationDegrees=0, CL_Vec2f vRotatePt=CL_Vec2f(0, 0))
virtual void BlitEx (rtRectf dst, rtRectf src, unsigned int rgba=MAKE_RGBA(255, 255, 255, 255), float rotationDegrees=0, CL_Vec2f vRotatePt=CL_Vec2f(0, 0))
void BlitScaled (float x, float y, CL_Vec2f vScale, eAlignment alignment=ALIGNMENT_CENTER, unsigned int rgba=MAKE_RGBA(255, 255, 255, 255), float rotation=0, RenderBatcher *pRenderBatcher=NULL)
void BlitScaledWithRotatePoint (float x, float y, CL_Vec2f vScale, eAlignment alignment, unsigned int rgba, float rotation, CL_Vec2f vRotationPt, RenderBatcher *pRenderBatcher=NULL)
void BlitRotated (float x, float y, CL_Vec2f vScale, eAlignment alignment=ALIGNMENT_CENTER, unsigned int rgba=MAKE_RGBA(255, 255, 255, 255), float rotation=0, CL_Vec2f vRotationPtLocalCoords=CL_Vec2f(0, 0), RenderBatcher *pRenderBatcher=NULL)
rtRectf GetRectf ()
void SetSmoothing (bool bSmoothing)
void SetBlendingMode (eBlendingMode mode)
eBlendingMode GetBlendingMode ()
int GetMIPMapCount ()
void SetCreateMipMapsIfNeeded (bool bCreateMipMapsIfNeeded)
virtual bool InitBlankSurface (int x, int y)
virtual bool InitFromSoftSurface (SoftSurface *pSurf, bool bCreateSurface=true, int mipLevel=0)
bool IsRenderTarget ()
void CopyFromScreen ()
void UpdateSurfaceRect (rtRect dstRect, byte *pPixelData, bool bUpsideDownMode=true)
void FillColor (glColorBytes color)
virtual void Kill ()
void OnLoadSurfaces ()
void OnUnloadSurfaces ()
void SetupForRender (const float rotationDegrees=0, const CL_Vec2f &vRotatePt=CL_Vec2f(0, 0), const uint32 rgba=MAKE_RGBA(255, 255, 255, 255))
void EndRender (const float rotationDegrees=0, const uint32 rgba=MAKE_RGBA(255, 255, 255, 255))
void ApplyBlendingMode (uint32 rgba)
void RemoveBlendingMode (uint32 rgba)
Protected Types
enum eTextureCreationMethod { TEXTURE_CREATION_NONE, TEXTURE_CREATION_FILE, TEXTURE_CREATION_MEMORY, TEXTURE_CREATION_BLANK }
Protected Member Functions
virtual void ReloadImage ()
Detailed Description
Definition at line 32 of file Surface.h.
Member Enumeration Documentation
enum Surface::eBlendingMode
Enumerator:
BLENDING_NORMAL
BLENDING_ADDITIVE
BLENDING_PREMULTIPLIED_ALPHA
BLENDING_MULTIPLY
BLENDING_DARKEN
Definition at line 50 of file Surface.h.
enum Surface::eTextureCreationMethod [protected]
Enumerator:
TEXTURE_CREATION_NONE
TEXTURE_CREATION_FILE
TEXTURE_CREATION_MEMORY
TEXTURE_CREATION_BLANK
Definition at line 123 of file Surface.h.
enum Surface::eTextureType
Type for the texture that the Surface class uses.
Enumerator:
TYPE_DEFAULT
Linear filtering, wrap mode is repeat, uses mipmaps.
TYPE_GUI
Linear filtering, wrap mode is clamp to edge, no mipmaps.
TYPE_NOT_OWNER
The texture is owned by somebody else and is responsible for setting the appropriate parameters.
TYPE_NO_SMOOTHING
Nearest pixel filtering, wrap mode is clamp to edge, no mipmaps.
Definition at line 38 of file Surface.h.
Constructor & Destructor Documentation
Surface::Surface ()
Definition at line 15 of file Surface.cpp.
Surface::Surface (string fName)
Definition at line 20 of file Surface.cpp.
References LoadFile().
Surface::Surface (string fName, eTextureType type)
Definition at line 26 of file Surface.cpp.
References LoadFile(), and SetTextureType().
Surface::~Surface () [virtual]
Definition at line 52 of file Surface.cpp.
References Kill().
Member Function Documentation
void Surface::ApplyBlendingMode (uint32 rgba)
Definition at line 554 of file Surface.cpp.
References BLENDING_ADDITIVE, BLENDING_DARKEN, BLENDING_MULTIPLY, BLENDING_NORMAL, BLENDING_PREMULTIPLIED_ALPHA, glBlendFunc(), glColor4x(), glEnable(), PURE_WHITE, and UsesAlpha().
Referenced by SetupForRender().
void Surface::Bind ()
Definition at line 488 of file Surface.cpp.
References g_lastBound, glBindTexture(), ReloadImage(), and TYPE_NOT_OWNER.
Referenced by CopyFromScreen(), RenderBatcher::Flush3D(), L_ParticleEffect::RenderPointSprites(), SetSmoothing(), SetupForRender(), and UpdateSurfaceRect().
void Surface::Blit (float x, float y, unsigned int rgba = MAKE_RGBA(255,255,255,255), float rotationDegrees = 0, CL_Vec2f vRotatePt = CL_Vec2f(0,0)) [virtual]
Definition at line 746 of file Surface.cpp.
References EndRender(), GetBaseApp(), glDrawArrays(), glTexCoordPointer(), glVertexPointer(), IsLoaded(), and SetupForRender().
Referenced by SurfaceAnim::BlitAnim().
void Surface::BlitEx (rtRectf dst, rtRectf src, unsigned int rgba = MAKE_RGBA(255,255,255,255), float rotationDegrees = 0, CL_Vec2f vRotatePt = CL_Vec2f(0,0)) [virtual]
Definition at line 633 of file Surface.cpp.
References rtRectf::AdjustPosition(), rtRectf::bottom, C_TEXEL_HACK_AMOUNT, EndRender(), GetBaseApp(), GetOrthoRenderSizeYf(), glDrawArrays(), glTexCoordPointer(), glVertexPointer(), IsLoaded(), rtRectf::left, rtRectf::right, SetupForRender(), and rtRectf::top.
Referenced by SurfaceAnim::BlitAnim(), SpriteSheetSurface::BlitFrame(), SurfaceAnim::BlitScaledAnim(), and BlitScaledWithRotatePoint().
void Surface::BlitRotated (float x, float y, CL_Vec2f vScale, eAlignment alignment = ALIGNMENT_CENTER, unsigned int rgba = MAKE_RGBA(255,255,255,255), float rotation = 0, CL_Vec2f vRotationPtLocalCoords = CL_Vec2f(0,0), RenderBatcher * pRenderBatcher = NULL)
Definition at line 1227 of file Surface.cpp.
References BlitScaledWithRotatePoint().
void Surface::BlitScaled (float x, float y, CL_Vec2f vScale, eAlignment alignment = ALIGNMENT_CENTER, unsigned int rgba = MAKE_RGBA(255,255,255,255), float rotation = 0, RenderBatcher * pRenderBatcher = NULL)
Definition at line 718 of file Surface.cpp.
References BlitScaledWithRotatePoint().
void Surface::BlitScaledWithRotatePoint (float x, float y, CL_Vec2f vScale, eAlignment alignment, unsigned int rgba, float rotation, CL_Vec2f vRotationPt, RenderBatcher * pRenderBatcher = NULL)
Definition at line 723 of file Surface.cpp.
References rtRectf::AdjustPosition(), RenderBatcher::BlitEx(), BlitEx(), GetAlignmentOffset(), and rtRectf::Scale().
Referenced by BlitRotated(), BlitScaled(), and SurfaceAnim::BlitScaledAnim().
void Surface::CopyFromScreen ()
Definition at line 883 of file Surface.cpp.
References Bind(), GetPrimaryGLX(), GetPrimaryGLY(), glReadPixels(), and glTexSubImage2D().
void Surface::EndRender (const float rotationDegrees = 0, const uint32 rgba = MAKE_RGBA(255,255,255,255))
Definition at line 621 of file Surface.cpp.
References PopRotationMatrix(), and RemoveBlendingMode().
Referenced by Blit(), and BlitEx().
void Surface::FillColor (glColorBytes color)
Definition at line 910 of file Surface.cpp.
References GetHeight(), GetWidth(), and UpdateSurfaceRect().
eBlendingMode Surface::GetBlendingMode () [inline]
Definition at line 97 of file Surface.h.
Referenced by RenderBatcher::BlitEx().
int Surface::GetHeight () [inline]
Definition at line 72 of file Surface.h.
Referenced by SurfaceAnim::BlitAnim(), RenderBatcher::BlitEx(), SurfaceAnim::BlitScaledAnim(), FillColor(), SurfaceAnim::InitBlankSurface(), SurfaceAnim::InitFromSoftSurface(), SurfaceAnim::LoadFileFromMemory(), and SurfaceAnim::SetupAnim().
int Surface::GetMIPMapCount () [inline]
Definition at line 98 of file Surface.h.
int Surface::GetRawTextureHeight () [inline]
Definition at line 75 of file Surface.h.
Referenced by RenderBatcher::BlitEx().
int Surface::GetRawTextureWidth () [inline]
Definition at line 74 of file Surface.h.
Referenced by RenderBatcher::BlitEx(), and L_ParticleEffect::draw().
rtRectf Surface::GetRectf () [inline]
Definition at line 94 of file Surface.h.
int Surface::GetWidth () [inline]
Definition at line 71 of file Surface.h.
Referenced by SurfaceAnim::BlitAnim(), RenderBatcher::BlitEx(), SurfaceAnim::BlitScaledAnim(), FillColor(), SurfaceAnim::InitBlankSurface(), SurfaceAnim::InitFromSoftSurface(), SurfaceAnim::LoadFileFromMemory(), SurfaceAnim::SetupAnim(), and SurfaceAnim::SetupAnimBySize().
bool Surface::InitBlankSurface (int x, int y) [virtual]
Reimplemented in SurfaceAnim, and SpriteSheetSurface.
Definition at line 983 of file Surface.cpp.
References GetBaseApp(), glTexImage2D(), Kill(), LogMsg(), BaseApp::m_sig_enterforeground, BaseApp::m_sig_loadSurfaces, BaseApp::m_sig_unloadSurfaces, nextPowerOfTwo(), OnLoadSurfaces(), OnUnloadSurfaces(), and TEXTURE_CREATION_BLANK.
Referenced by SoftSurface::CreateGLTexture(), SurfaceAnim::InitBlankSurface(), and OnLoadSurfaces().
bool Surface::InitFromSoftSurface (SoftSurface * pSurf, bool bCreateSurface = true, int mipLevel = 0) [virtual]
Definition at line 1102 of file Surface.cpp.
References SoftSurface::Blit(), SoftSurface::GetHeight(), SoftSurface::GetOriginalHeight(), SoftSurface::GetOriginalWidth(), SoftSurface::GetPixelData(), SoftSurface::GetSurfaceType(), SoftSurface::GetWidth(), glTexImage2D(), glTexSubImage2D(), SoftSurface::Init(), Kill(), LogMsg(), nextPowerOfTwo(), SoftSurface::SURFACE_RGB, SoftSurface::SURFACE_RGBA, and TEXTURE_CREATION_BLANK.
Referenced by SurfaceAnim::InitFromSoftSurface(), and LoadFileFromMemory().
bool Surface::IsLoaded () [inline]
Definition at line 67 of file Surface.h.
Referenced by Blit(), RenderBatcher::BlitEx(), BlitEx(), RTFont::DrawScaled(), RTFont::DrawScaledSolidColor(), RTFont::IsLoaded(), RTFont::SetSmoothing(), SetSmoothing(), SetTextureType(), SurfaceAnim::SetupAnim(), and SurfaceAnim::SetupAnimBySize().
bool Surface::IsRenderTarget () [inline]
Definition at line 102 of file Surface.h.
void Surface::Kill () [virtual]
Definition at line 57 of file Surface.cpp.
References GetBaseApp(), glDeleteTextures(), and BaseApp::ModTexUsed().
Referenced by InitBlankSurface(), InitFromSoftSurface(), LoadFile(), LoadFileFromMemory(), OnUnloadSurfaces(), OverlayRenderComponent::~OverlayRenderComponent(), and ~Surface().
bool Surface::LoadFile (string fName, bool bAddBasePath = true)
Definition at line 510 of file Surface.cpp.
References FileInstance::GetAsBytes(), FileInstance::GetSize(), FileInstance::IsLoaded(), Kill(), LoadFileFromMemory(), LogMsg(), and TEXTURE_CREATION_FILE.
Referenced by ResourceManager::GetSurfaceResource(), ReloadImage(), and Surface().
bool Surface::LoadFileFromMemory (byte * pMem, int inputSize = 0) [virtual]
Reimplemented in SurfaceAnim.
Definition at line 424 of file Surface.cpp.
References C_JPG_HEADER_MARKER, SoftSurface::COLOR_KEY_NONE, GetBaseApp(), InitFromSoftSurface(), Kill(), SoftSurface::LoadFileFromMemory(), LogError(), LogMsg(), BaseApp::m_sig_enterforeground, BaseApp::m_sig_unloadSurfaces, OnUnloadSurfaces(), SetSmoothing(), TEXTURE_CREATION_MEMORY, and TEXTURE_CREATION_NONE.
Referenced by RTFont::Load(), LoadFile(), and SurfaceAnim::LoadFileFromMemory().
void Surface::OnLoadSurfaces ()
Definition at line 1064 of file Surface.cpp.
References InitBlankSurface(), LogMsg(), ReloadImage(), TEXTURE_CREATION_BLANK, and TEXTURE_CREATION_FILE.
Referenced by InitBlankSurface().
void Surface::OnUnloadSurfaces ()
Definition at line 1090 of file Surface.cpp.
References Kill(), and LogMsg().
Referenced by InitBlankSurface(), and LoadFileFromMemory().
void Surface::ReloadImage () [protected, virtual]
Reimplemented in SurfaceAnim.
Definition at line 1059 of file Surface.cpp.
References LoadFile().
Referenced by Bind(), and OnLoadSurfaces().
void Surface::RemoveBlendingMode (uint32 rgba)
Definition at line 605 of file Surface.cpp.
References BLENDING_NORMAL, glBlendFunc(), glColor4x(), glDisable(), PURE_WHITE, and UsesAlpha().
Referenced by EndRender().
void Surface::SetBlendingMode (eBlendingMode mode) [inline]
Definition at line 96 of file Surface.h.
Referenced by SoftSurface::CreateGLTexture(), and L_Particle::Setup().
void Surface::SetCreateMipMapsIfNeeded (bool bCreateMipMapsIfNeeded) [inline]
Definition at line 99 of file Surface.h.
void Surface::SetSmoothing (bool bSmoothing)
Definition at line 805 of file Surface.cpp.
References Bind(), glTexParameterx(), and IsLoaded().
Referenced by CreateCheckbox(), LoadFileFromMemory(), and RTFont::SetSmoothing().
void Surface::SetTextureType (eTextureType type)
Sets the texture type for this Surface.
The default type is TYPE_DEFAULT .
Note:
You can only call this method before loading the texture.
Definition at line 799 of file Surface.cpp.
References IsLoaded().
Referenced by SoftSurface::CreateGLTexture(), ResourceManager::GetSurfaceResource(), RTFont::Load(), and Surface().
void Surface::SetupForRender (const float rotationDegrees = 0, const CL_Vec2f & vRotatePt = CL_Vec2f(0,0), const uint32 rgba = MAKE_RGBA(255,255,255,255))
Definition at line 590 of file Surface.cpp.
References ApplyBlendingMode(), Bind(), RenderBatcher::Flush(), g_globalBatcher, PushRotationMatrix(), and SetupOrtho().
Referenced by Blit(), and BlitEx().
void Surface::SetUsesAlpha (bool bNew) [inline]
Definition at line 69 of file Surface.h.
Referenced by SoftSurface::CreateGLTexture().
void Surface::UpdateSurfaceRect (rtRect dstRect, byte * pPixelData, bool bUpsideDownMode = true)
Definition at line 929 of file Surface.cpp.
References Bind(), rtRect::GetHeight(), rtRect::GetWidth(), glTexSubImage2D(), rtRect::left, and rtRect::top.
Referenced by SoftSurface::CreateGLTexture(), and FillColor().
bool Surface::UsesAlpha () [inline]
Definition at line 68 of file Surface.h.
Referenced by ApplyBlendingMode(), and RemoveBlendingMode().
The documentation for this class was generated from the following files:
Surface.h
Surface.cpp