Proton: GamepadMoga Class Reference
GamepadMoga Class Reference
#include <GamepadMoga.h>
Public Member Functions
GamepadMoga ()
virtual ~GamepadMoga ()
virtual bool Init ()
virtual void Kill ()
virtual void Update ()
void SetProvider (GamepadProviderMoga *pProvider)
void OnJoypadEvent (VariantList *pVList)
Detailed Description
Definition at line 18 of file GamepadMoga.h.
Constructor & Destructor Documentation
GamepadMoga::GamepadMoga ()
Definition at line 5 of file GamepadMoga.cpp.
References GetBaseApp(), BaseApp::m_sig_joypad_events, and OnJoypadEvent().
GamepadMoga::~GamepadMoga () [virtual]
Definition at line 14 of file GamepadMoga.cpp.
References Kill().
Member Function Documentation
bool GamepadMoga::Init () [virtual]
Implements Gamepad.
Definition at line 19 of file GamepadMoga.cpp.
References Gamepad::m_axisUsedCount, Gamepad::m_buttons, Gamepad::m_name, GamepadButton::m_virtualKey, Gamepad::SetRightStickAxis(), VIRTUAL_DPAD_BUTTON_DOWN, VIRTUAL_DPAD_BUTTON_LEFT, VIRTUAL_DPAD_BUTTON_RIGHT, VIRTUAL_DPAD_BUTTON_UP, VIRTUAL_DPAD_LBUTTON, VIRTUAL_DPAD_RBUTTON, VIRTUAL_DPAD_SELECT, and VIRTUAL_DPAD_START.
void GamepadMoga::Kill () [virtual]
Implements Gamepad.
Definition at line 40 of file GamepadMoga.cpp.
Referenced by ~GamepadMoga().
void GamepadMoga::OnJoypadEvent (VariantList * pVList)
Definition at line 50 of file GamepadMoga.cpp.
References VariantList::Get(), Variant::GetFloat(), Variant::GetUINT32(), LogMsg(), MESSAGE_TYPE_GUI_JOYPAD, MESSAGE_TYPE_GUI_JOYPAD_BUTTONS, MESSAGE_TYPE_GUI_JOYPAD_CONNECT, Gamepad::OnButton(), and Gamepad::SetAxis().
Referenced by GamepadMoga().
void GamepadMoga::SetProvider (GamepadProviderMoga * pProvider) [inline]
Definition at line 27 of file GamepadMoga.h.
Referenced by GamepadProviderMoga::Init().
void GamepadMoga::Update () [virtual]
Reimplemented from Gamepad.
Definition at line 45 of file GamepadMoga.cpp.
The documentation for this class was generated from the following files:
GamepadMoga.h
GamepadMoga.cpp