Proton: AudioManagerSDL Class Reference
AudioManagerSDL Class Reference
#include <AudioManagerSDL.h>
Public Member Functions
AudioManagerSDL ()
virtual ~AudioManagerSDL ()
virtual AudioHandle Play (const string fileName)
virtual bool Init ()
virtual void Kill ()
virtual AudioHandle Play (string fName, bool bLooping=false, bool bIsMusic=false, bool bAddBasePath=true, bool bForceStreaming=false)
Plays an audio specified by a file name.
virtual AudioHandle Play (string fName, int vol, int pan=0)
virtual void Preload (string fName, bool bLooping=false, bool bIsMusic=false, bool bAddBasePath=true, bool bForceStreaming=false)
virtual void KillCachedSounds (bool bKillMusic, bool bKillLooping, int ignoreSoundsUsedInLastMS, int killSoundsLowerPriorityThanThis, bool bKillSoundsPlaying)
virtual void Update ()
This method must be called periodically, e.g once every frame.
virtual void Stop (AudioHandle soundID)
virtual AudioHandle GetMusicChannel ()
virtual bool IsPlaying (AudioHandle soundID)
virtual void SetMusicEnabled (bool bNew)
Enables or disables the playing of music.
virtual void StopMusic ()
Stops the currently playing music immediately.
virtual void FadeOutMusic (unsigned int duration=1000)
Fades out the currently playing music during duration milliseconds.
virtual int GetMemoryUsed ()
virtual void SetFrequency (AudioHandle soundID, int freq)
virtual void SetPan (AudioHandle soundID, float pan)
virtual void SetVol (AudioHandle soundID, float vol)
virtual void SetPriority (AudioHandle soundID, int priority)
virtual uint32 GetPos (AudioHandle soundID)
virtual void SetPos (AudioHandle soundID, uint32 posMS)
virtual void SetMusicVol (float vol)
Detailed Description
Definition at line 21 of file AudioManagerSDL.h.
Constructor & Destructor Documentation
AudioManagerSDL::AudioManagerSDL ()
Definition at line 46 of file AudioManagerSDL.cpp.
AudioManagerSDL::~AudioManagerSDL () [virtual]
Definition at line 52 of file AudioManagerSDL.cpp.
References Kill().
Member Function Documentation
void AudioManagerSDL::FadeOutMusic (unsigned int duration = 1000) [virtual]
Fades out the currently playing music during duration milliseconds.
If no music is playing then this method does nothing.
Reimplemented from AudioManager.
Definition at line 432 of file AudioManagerSDL.cpp.
int AudioManagerSDL::GetMemoryUsed () [virtual]
Reimplemented from AudioManager.
Definition at line 437 of file AudioManagerSDL.cpp.
AudioHandle AudioManagerSDL::GetMusicChannel () [virtual]
Definition at line 383 of file AudioManagerSDL.cpp.
uint32 AudioManagerSDL::GetPos (AudioHandle soundID) [virtual]
Reimplemented from AudioManager.
Definition at line 457 of file AudioManagerSDL.cpp.
bool AudioManagerSDL::Init () [virtual]
Reimplemented from AudioManager.
Definition at line 64 of file AudioManagerSDL.cpp.
References LogMsg(), and musicFinishedCallback().
bool AudioManagerSDL::IsPlaying (AudioHandle soundID) [virtual]
Reimplemented from AudioManager.
Definition at line 389 of file AudioManagerSDL.cpp.
Referenced by KillCachedSounds(), and Play().
void AudioManagerSDL::Kill () [virtual]
Reimplemented from AudioManager.
Definition at line 157 of file AudioManagerSDL.cpp.
Referenced by ~AudioManagerSDL().
void AudioManagerSDL::KillCachedSounds (bool bKillMusic, bool bKillLooping, int ignoreSoundsUsedInLastMS, int killSoundsLowerPriorityThanThis, bool bKillSoundsPlaying) [virtual]
Reimplemented from AudioManager.
Definition at line 116 of file AudioManagerSDL.cpp.
References IsPlaying(), LogMsg(), and AudioManager::m_lastMusicFileName.
AudioHandle AudioManagerSDL::Play (const string fileName) [virtual]
Definition at line 57 of file AudioManagerSDL.cpp.
References LogMsg().
Referenced by SetMusicEnabled().
AudioHandle AudioManagerSDL::Play (string fName, bool bLooping = false, bool bIsMusic = false, bool bAddBasePath = true, bool bForceStreaming = false) [virtual]
Plays an audio specified by a file name.
Returns the audio handle for the playing sound if the playing started successfully. Returns AUDIO_HANDLE_BLANK if the playing of the audio didn't start successfully. Also returns AUDIO_HANDLE_BLANK if requesting to play a sound file and sound is currently disabled or requesting to play music and music is currently disabled.
Parameters:
fName the file name of the audio to play.
bLooping whether the sound should start again when it ends, i.e. loop.
bIsMusic specifies if this sound is the music track.
bAddBasePath adds the base path to the file name. See GetBaseAppPath().
bForceStreaming streams the audio directly from the file and doesn't load it into memory. This flag might not be supported by all audio backends.
Returns:
The audio handle for the playing sound if the playing started successfully. Returns AUDIO_HANDLE_BLANK if the playing of the audio didn't start.
Reimplemented from AudioManager.
Definition at line 248 of file AudioManagerSDL.cpp.
References GetBaseAppPath(), AudioManager::GetMusicEnabled(), AudioManager::GetSoundEnabled(), IsPlaying(), LogError(), AudioManager::m_bLastMusicLooping, AudioManager::m_lastMusicFileName, AudioManager::m_lastMusicID, AudioManager::m_musicVol, SoundObject::m_pLastChannelToUse, SoundObject::m_pSound, Preload(), SetMusicVol(), SetVol(), and StopMusic().
AudioHandle AudioManagerSDL::Play (string fName, int vol, int pan = 0) [virtual]
Definition at line 351 of file AudioManagerSDL.cpp.
void AudioManagerSDL::Preload (string fName, bool bLooping = false, bool bIsMusic = false, bool bAddBasePath = true, bool bForceStreaming = false) [virtual]
Reimplemented from AudioManager.
Definition at line 209 of file AudioManagerSDL.cpp.
References GetBaseAppPath(), GetFileExtension(), LogMsg(), SoundObject::m_bIsLooping, SoundObject::m_fileName, and SoundObject::m_pSound.
Referenced by Play().
void AudioManagerSDL::SetFrequency (AudioHandle soundID, int freq) [virtual]
Reimplemented from AudioManager.
Definition at line 442 of file AudioManagerSDL.cpp.
void AudioManagerSDL::SetMusicEnabled (bool bNew) [virtual]
Enables or disables the playing of music.
When the music system is disabled any currently playing music is stopped. When the music system is later enabled again the music file that was left playing is resumed from the location where it stopped.
Reimplemented from AudioManager.
Definition at line 403 of file AudioManagerSDL.cpp.
References AudioManager::GetLastMusicLooping(), AudioManager::m_bMusicEnabled, AudioManager::m_lastMusicFileName, Play(), and StopMusic().
void AudioManagerSDL::SetMusicVol (float vol) [virtual]
Reimplemented from AudioManager.
Definition at line 488 of file AudioManagerSDL.cpp.
References AudioManager::m_musicVol.
Referenced by Play().
void AudioManagerSDL::SetPan (AudioHandle soundID, float pan) [virtual]
Reimplemented from AudioManager.
Definition at line 449 of file AudioManagerSDL.cpp.
void AudioManagerSDL::SetPos (AudioHandle soundID, uint32 posMS) [virtual]
Reimplemented from AudioManager.
Definition at line 465 of file AudioManagerSDL.cpp.
void AudioManagerSDL::SetPriority (AudioHandle soundID, int priority) [virtual]
Reimplemented from AudioManager.
Definition at line 499 of file AudioManagerSDL.cpp.
void AudioManagerSDL::SetVol (AudioHandle soundID, float vol) [virtual]
Reimplemented from AudioManager.
Definition at line 473 of file AudioManagerSDL.cpp.
Referenced by Play().
void AudioManagerSDL::Stop (AudioHandle soundID) [virtual]
Reimplemented from AudioManager.
Definition at line 367 of file AudioManagerSDL.cpp.
References StopMusic().
void AudioManagerSDL::StopMusic () [virtual]
Stops the currently playing music immediately.
Reimplemented from AudioManager.
Definition at line 423 of file AudioManagerSDL.cpp.
References AudioManager::m_lastMusicFileName, and AudioManager::m_lastMusicID.
Referenced by Play(), SetMusicEnabled(), Stop(), and Update().
void AudioManagerSDL::Update () [virtual]
This method must be called periodically, e.g once every frame.
Reimplemented from AudioManager.
Definition at line 358 of file AudioManagerSDL.cpp.
References g_MusicHasFinished, and StopMusic().
The documentation for this class was generated from the following files:
AudioManagerSDL.h
AudioManagerSDL.cpp