Proton: AdManager Class Reference
AdManager Class Reference
#include <AdManager.h>
Public Types
enum eReturnState { RETURN_STATE_NONE, RETURN_STATE_WAITING, RETURN_STATE_ERROR, RETURN_STATE_SUCCESS }
Public Member Functions
AdManager ()
virtual ~AdManager ()
void Init ()
void Update ()
void OnMessage (Message &m)
string GetLastErrorString ()
void ClearError ()
eReturnState GetReturnState ()
bool IsReadyForTransaction ()
void OnRender ()
void AddProvider (AdProvider *provider)
AdProvider * GetProviderByType (eAdProviderType type)
bool ProviderExistsByType (eAdProviderType type)
void TrackingOnPageView ()
void TrackingLog (string eventName, string optionalKey="", string optionalValue="")
void InitTapjoy (string tapjoyID, string tapjoyAppSecretKey)
void SetTapjoyAdVisible (bool bVisible)
void SetTapjoyFeatureAppVisible (bool bVisible)
void CacheTapjoyAd ()
void CacheTapjoyFeaturedApp ()
bool IsTapJoyAdReady ()
string GetPointsString ()
void OpenTapjoyOfferWall ()
void SetUsingTapPoints (bool bNew)
void ModifyTapPoints (int mod)
void GetTapPointsFromServer ()
void SetupBanner (CL_Vec2f vBannerSize, eAlignment alignment=ALIGNMENT_DOWN_CENTER)
Public Attributes
Variant m_tapPointVariant
boost::signal< void(VariantList *) m_sig_tappoints_awarded)
Detailed Description
Definition at line 37 of file AdManager.h.
Member Enumeration Documentation
enum AdManager::eReturnState
Enumerator:
RETURN_STATE_NONE
RETURN_STATE_WAITING
RETURN_STATE_ERROR
RETURN_STATE_SUCCESS
Definition at line 41 of file AdManager.h.
Constructor & Destructor Documentation
AdManager::AdManager ()
Definition at line 4 of file AdManager.cpp.
References ALIGNMENT_DOWN_CENTER, m_tapPointVariant, RETURN_STATE_NONE, and Variant::Set().
AdManager::~AdManager () [virtual]
Definition at line 23 of file AdManager.cpp.
Member Function Documentation
void AdManager::AddProvider (AdProvider * provider)
Definition at line 33 of file AdManager.cpp.
References AdProvider::GetName(), LogError(), LogMsg(), and AdProvider::OnAddToManager().
void AdManager::CacheTapjoyAd ()
Definition at line 129 of file AdManager.cpp.
References BaseApp::AddOSMessage(), GetBaseApp(), OSMessage::m_type, and OSMessage::MESSAGE_TAPJOY_GET_AD.
Referenced by Update().
void AdManager::CacheTapjoyFeaturedApp ()
Definition at line 138 of file AdManager.cpp.
References BaseApp::AddOSMessage(), GetBaseApp(), OSMessage::m_type, and OSMessage::MESSAGE_TAPJOY_GET_FEATURED_APP.
Referenced by Update().
void AdManager::ClearError ()
Definition at line 344 of file AdManager.cpp.
Referenced by ModifyTapPoints(), and OnMessage().
string AdManager::GetLastErrorString ()
Definition at line 339 of file AdManager.cpp.
std::string AdManager::GetPointsString ()
Definition at line 320 of file AdManager.cpp.
References toString().
AdProvider * AdManager::GetProviderByType (eAdProviderType type)
Definition at line 48 of file AdManager.cpp.
AdManager::eReturnState AdManager::GetReturnState ()
Definition at line 349 of file AdManager.cpp.
void AdManager::GetTapPointsFromServer ()
Definition at line 300 of file AdManager.cpp.
References BaseApp::AddOSMessage(), GetBaseApp(), LogMsg(), OSMessage::m_type, and OSMessage::MESSAGE_TAPJOY_GET_TAP_POINTS.
void AdManager::Init ()
Definition at line 313 of file AdManager.cpp.
References LogMsg().
void AdManager::InitTapjoy (string tapjoyID, string tapjoyAppSecretKey)
Definition at line 455 of file AdManager.cpp.
References BaseApp::AddOSMessage(), GetBaseApp(), LogMsg(), OSMessage::m_string, OSMessage::m_string2, OSMessage::m_type, and OSMessage::MESSAGE_TAPJOY_INIT_MAIN.
bool AdManager::IsReadyForTransaction ()
Definition at line 354 of file AdManager.cpp.
bool AdManager::IsTapJoyAdReady () [inline]
Definition at line 79 of file AdManager.h.
void AdManager::ModifyTapPoints (int mod)
Definition at line 359 of file AdManager.cpp.
References BaseApp::AddOSMessage(), ClearError(), GetBaseApp(), OSMessage::m_parm1, OSMessage::m_type, OSMessage::MESSAGE_TAPJOY_AWARD_TAP_POINTS, OSMessage::MESSAGE_TAPJOY_SPEND_TAP_POINTS, mod(), and RETURN_STATE_WAITING.
void AdManager::OnMessage (Message & m)
Definition at line 146 of file AdManager.cpp.
References ClearError(), Message::GetParm1(), Message::GetParm2(), Message::GetStringParm(), Message::GetType(), LogMsg(), m_sig_tappoints_awarded, m_tapPointVariant, MESSAGE_TYPE_TAPJOY_AD_READY, MESSAGE_TYPE_TAPJOY_EARNED_TAP_POINTS, MESSAGE_TYPE_TAPJOY_FEATURED_APP_READY, MESSAGE_TYPE_TAPJOY_MOVIE_AD_READY, MESSAGE_TYPE_TAPJOY_SPEND_TAP_POINTS_RETURN, MESSAGE_TYPE_TAPJOY_SPEND_TAP_POINTS_RETURN_ERROR, MESSAGE_TYPE_TAPJOY_TAP_POINTS_RETURN, RETURN_STATE_ERROR, RETURN_STATE_SUCCESS, RETURN_STATE_WAITING, Variant::Set(), SetTapjoyAdVisible(), and SetTapjoyFeatureAppVisible().
void AdManager::OnRender ()
Definition at line 379 of file AdManager.cpp.
References rtRect::AdjustPosition(), DrawFilledRect(), GetFakePrimaryScreenSizeX(), rtRect::GetHeight(), GetOriginalScreenSizeX(), GetOriginalScreenSizeY(), GetScreenSizeX(), GetScreenSizeXf(), GetScreenSizeY(), GetScreenSizeYf(), and rtRect::GetWidth().
void AdManager::OpenTapjoyOfferWall ()
Definition at line 118 of file AdManager.cpp.
References BaseApp::AddOSMessage(), GetBaseApp(), LogMsg(), OSMessage::m_type, and OSMessage::MESSAGE_TAPJOY_SHOW_OFFERS.
bool AdManager::ProviderExistsByType (eAdProviderType type)
Definition at line 423 of file AdManager.cpp.
void AdManager::SetTapjoyAdVisible (bool bVisible)
Definition at line 86 of file AdManager.cpp.
References BaseApp::AddOSMessage(), GetBaseApp(), OSMessage::m_type, OSMessage::m_x, and OSMessage::MESSAGE_TAPJOY_SHOW_AD.
Referenced by OnMessage().
void AdManager::SetTapjoyFeatureAppVisible (bool bVisible)
Definition at line 62 of file AdManager.cpp.
References BaseApp::AddOSMessage(), GetBaseApp(), LogMsg(), OSMessage::m_type, OSMessage::m_x, and OSMessage::MESSAGE_TAPJOY_SHOW_FEATURED_APP.
Referenced by OnMessage().
void AdManager::SetupBanner (CL_Vec2f vBannerSize, eAlignment alignment = ALIGNMENT_DOWN_CENTER)
Definition at line 408 of file AdManager.cpp.
References BaseApp::AddOSMessage(), GetBaseApp(), OSMessage::m_parm1, OSMessage::m_type, OSMessage::m_x, OSMessage::m_y, and OSMessage::MESSAGE_REQUEST_AD_SIZE.
void AdManager::SetUsingTapPoints (bool bNew)
Definition at line 330 of file AdManager.cpp.
void AdManager::TrackingLog (string eventName, string optionalKey = "", string optionalValue = "")
Definition at line 437 of file AdManager.cpp.
void AdManager::TrackingOnPageView ()
Definition at line 446 of file AdManager.cpp.
void AdManager::Update ()
Definition at line 274 of file AdManager.cpp.
References CacheTapjoyAd(), CacheTapjoyFeaturedApp(), GetTick(), and TIMER_SYSTEM.
Member Data Documentation
boost::signal<void (VariantList*) AdManager::m_sig_tappoints_awarded)
Definition at line 87 of file AdManager.h.
Referenced by OnMessage().
Variant AdManager::m_tapPointVariant
Definition at line 58 of file AdManager.h.
Referenced by AdManager(), and OnMessage().
The documentation for this class was generated from the following files:
AdManager.h
AdManager.cpp