Proton: TextRenderComponent Class Reference
TextRenderComponent Class Reference
#include <TextRenderComponent.h>
Public Types
enum eVisualStyle { STYLE_NORMAL, STYLE_EFFECT_SIN_WAVE }
Public Member Functions
TextRenderComponent ()
virtual ~TextRenderComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
Detailed Description
Definition at line 17 of file TextRenderComponent.h.
Member Enumeration Documentation
enum TextRenderComponent::eVisualStyle
Enumerator:
STYLE_NORMAL
STYLE_EFFECT_SIN_WAVE
Definition at line 26 of file TextRenderComponent.h.
Constructor & Destructor Documentation
TextRenderComponent::TextRenderComponent ()
Definition at line 6 of file TextRenderComponent.cpp.
References EntityComponent::SetName().
TextRenderComponent::~TextRenderComponent () [virtual]
Definition at line 11 of file TextRenderComponent.cpp.
Member Function Documentation
void TextRenderComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 34 of file TextRenderComponent.cpp.
References FONT_SMALL, Variant::GetFloat(), Entity::GetFunction(), EntityComponent::GetParent(), Variant::GetSigOnChanged, Variant::GetString(), Variant::GetUINT32(), EntityComponent::GetVar(), Entity::GetVar(), EntityComponent::GetVarWithDefault(), Entity::GetVarWithDefault(), Variant::GetVector2(), FunctionObject::sig_function, and STYLE_NORMAL.
void TextRenderComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 70 of file TextRenderComponent.cpp.
The documentation for this class was generated from the following files:
TextRenderComponent.h
TextRenderComponent.cpp