Proton: Variant Class Reference
Variant Class Reference
#include <Variant.h>
Public Types
enum eType {
TYPE_UNUSED, TYPE_FLOAT, TYPE_STRING, TYPE_VECTOR2,
TYPE_VECTOR3, TYPE_UINT32, TYPE_ENTITY, TYPE_COMPONENT,
TYPE_RECT, TYPE_INT32
}
Public Member Functions
Variant (uint32 var)
Variant (int32 var)
Variant (float var)
Variant (const string &var)
Variant (float x, float y)
Variant (float x, float y, float z)
Variant (const CL_Vec2f &v2)
Variant (const CL_Vec3f &v3)
Variant (const CL_Rectf &r)
Variant (Entity *pEnt)
Variant (EntityComponent *pEnt)
Variant ()
~Variant ()
void Reset ()
void Set (const Variant &v)
void SetVariant (Variant *pVar)
void Set (float var)
float & GetFloat ()
const float & GetFloat () const
void Set (const Entity *pEnt)
Entity * GetEntity ()
const Entity * GetEntity () const
void Set (const EntityComponent *pEnt)
EntityComponent * GetComponent ()
const EntityComponent * GetComponent () const
void Set (uint32 var)
uint32 & GetUINT32 ()
const uint32 & GetUINT32 () const
void Set (int32 var)
int32 & GetINT32 ()
const int32 & GetINT32 () const
void Set (string const &var)
string & GetString ()
const string & GetString () const
void Set (CL_Vec2f const &var)
CL_Vec2f & GetVector2 ()
const CL_Vec2f & GetVector2 () const
void Set (float x, float y)
void Set (CL_Vec3f const &var)
CL_Vec3f & GetVector3 ()
const CL_Vec3f & GetVector3 () const
void Set (CL_Rectf const &var)
CL_Rectf & GetRect ()
const CL_Rectf & GetRect () const
void Set (float x, float y, float z)
eType GetType () const
string Print ()
Variant (const Variant &v)
Variant & operator= (const Variant &rhs)
Variant & operator+= (const Variant &rhs)
Add-and-assign operator.
Variant & operator-= (const Variant &rhs)
Subtract-and-assign operator.
bool operator== (const Variant &rhs) const
Equality operator.
bool operator!= (const Variant &rhs) const
Inequality operator.
void Interpolate (Variant *pA, Variant *pB, float curPos, eInterpolateType type)
bool Save (FILE *fp, const string &varName)
void ClearConnections ()
Public Attributes
boost::signal< void(Variant *)> GetSigOnChanged)()
byte m_var [C_VAR_SPACE_BYTES]
float m_as_floats [4]
uint32 m_as_uint32s [4]
int32 m_as_int32s [4]
Friends
class VariantList
Related Functions
(Note that these are not member functions.)
Variant operator+ (Variant lhs, const Variant &rhs)
Variant operator- (Variant lhs, const Variant &rhs)
Detailed Description
Definition at line 48 of file Variant.h.
Member Enumeration Documentation
enum Variant::eType
Enumerator:
TYPE_UNUSED
TYPE_FLOAT
TYPE_STRING
TYPE_VECTOR2
TYPE_VECTOR3
TYPE_UINT32
TYPE_ENTITY
TYPE_COMPONENT
TYPE_RECT
TYPE_INT32
Definition at line 52 of file Variant.h.
Constructor & Destructor Documentation
Variant::Variant (uint32 var) [inline]
Definition at line 66 of file Variant.h.
References Set().
Variant::Variant (int32 var) [inline]
Definition at line 67 of file Variant.h.
References Set().
Variant::Variant (float var) [inline]
Definition at line 69 of file Variant.h.
References Set().
Variant::Variant (const string & var) [inline]
Definition at line 70 of file Variant.h.
References Set().
Variant::Variant (float x, float y) [inline]
Definition at line 71 of file Variant.h.
References Set().
Variant::Variant (float x, float y, float z) [inline]
Definition at line 72 of file Variant.h.
References Set().
Variant::Variant (const CL_Vec2f & v2) [inline]
Definition at line 73 of file Variant.h.
References Set().
Variant::Variant (const CL_Vec3f & v3) [inline]
Definition at line 74 of file Variant.h.
References Set().
Variant::Variant (const CL_Rectf & r) [inline]
Definition at line 75 of file Variant.h.
References Set().
Variant::Variant (Entity * pEnt) [inline]
Definition at line 76 of file Variant.h.
References Set().
Variant::Variant (EntityComponent * pEnt) [inline]
Definition at line 77 of file Variant.h.
References Set().
Variant::Variant () [inline]
Definition at line 79 of file Variant.h.
Variant::~Variant ()
Definition at line 7 of file Variant.cpp.
Variant::Variant (const Variant & v) [inline]
Definition at line 281 of file Variant.h.
Member Function Documentation
void Variant::ClearConnections ()
Definition at line 21 of file Variant.cpp.
EntityComponent* Variant::GetComponent () [inline]
Definition at line 142 of file Variant.h.
References Set(), TYPE_COMPONENT, and TYPE_UNUSED.
Referenced by operator==(), and Set().
const EntityComponent* Variant::GetComponent () const [inline]
Definition at line 148 of file Variant.h.
References TYPE_COMPONENT.
Entity* Variant::GetEntity () [inline]
Definition at line 123 of file Variant.h.
References Set(), TYPE_ENTITY, and TYPE_UNUSED.
Referenced by LightBarOnChange(), MoveEntityToTop(), SliderComponent::OnAdd(), OnCheckboxToggle(), operator==(), ResizeScrollBounds(), ResizeScrollerAfterTextboxChanges(), and Set().
const Entity* Variant::GetEntity () const [inline]
Definition at line 129 of file Variant.h.
References TYPE_ENTITY.
float& Variant::GetFloat () [inline]
Definition at line 104 of file Variant.h.
References m_var, Set(), TYPE_FLOAT, and TYPE_UNUSED.
Referenced by FilterInputComponent::FilterOnInput(), FlashOnceEntity(), FlashStartEntity(), Interpolate(), ManuallySetAlignmentEntity(), SliderComponent::OnAdd(), TextRenderComponent::OnAdd(), ProgressBarComponent::OnAdd(), UnderlineRenderComponent::OnAdd(), RectRenderComponent::OnAdd(), TrailRenderComponent::OnAdd(), TextBoxRenderComponent::OnAdd(), DPadComponent::OnAdd(), ScrollBarRenderComponent::OnAdd(), LogDisplayComponent::OnAdd(), InputTextRenderComponent::OnAdd(), OverlayRenderComponent::OnAdd(), SpriteAnimationRenderComponent::OnAdd(), Button2DComponent::OnAdd(), ScrollComponent::OnAdd(), TouchHandlerArcadeComponent::OnInput(), TouchDragComponent::OnInput(), TouchHandlerComponent::OnInput(), GamepadMoga::OnJoypadEvent(), operator+=(), operator-=(), operator==(), Print(), and Set().
const float& Variant::GetFloat () const [inline]
Definition at line 110 of file Variant.h.
References m_var, and TYPE_FLOAT.
int32& Variant::GetINT32 () [inline]
Definition at line 180 of file Variant.h.
References m_var, Set(), TYPE_INT32, and TYPE_UNUSED.
Referenced by Interpolate(), operator+=(), operator-=(), operator==(), Print(), and Set().
const int32& Variant::GetINT32 () const [inline]
Definition at line 186 of file Variant.h.
References m_var, and TYPE_INT32.
CL_Rectf& Variant::GetRect () [inline]
Definition at line 255 of file Variant.h.
References m_var, Set(), and TYPE_UNUSED.
Referenced by DisableHorizontalScrolling(), FilterInputComponent::OnAdd(), TouchStripComponent::OnAdd(), TouchHandlerArcadeComponent::OnAdd(), TouchDragComponent::OnAdd(), DPadComponent::OnAdd(), ScrollBarRenderComponent::OnAdd(), Button2DComponent::OnAdd(), TouchHandlerComponent::OnAdd(), ScrollComponent::OnAdd(), operator==(), Print(), and Set().
const CL_Rectf& Variant::GetRect () const [inline]
Definition at line 264 of file Variant.h.
References m_var, and TYPE_RECT.
string& Variant::GetString () [inline]
Definition at line 193 of file Variant.h.
Referenced by MySQLManager::AddSelectResults(), GetOverlayImageEntity(), GetUsedTextures(), SelectButtonWithCustomInputComponent::OnAdd(), FilterComponent::OnAdd(), TextRenderComponent::OnAdd(), UnpackArchiveComponent::OnAdd(), ProgressBarComponent::OnAdd(), InterpolateComponent::OnAdd(), RectRenderComponent::OnAdd(), TyperComponent::OnAdd(), TextBoxRenderComponent::OnAdd(), DPadComponent::OnAdd(), ScrollBarRenderComponent::OnAdd(), LogDisplayComponent::OnAdd(), InputTextRenderComponent::OnAdd(), OverlayRenderComponent::OnAdd(), CustomInputComponent::OnAdd(), SpriteAnimationRenderComponent::OnAdd(), Button2DComponent::OnAdd(), OnShowTextMessage(), TyperComponent::OnUpdate(), InterpolateComponent::OnVarNameChanged(), operator+=(), operator==(), Print(), Set(), and TypeTextLabelEntity().
const string& Variant::GetString () const [inline]
Definition at line 197 of file Variant.h.
eType Variant::GetType () const [inline]
Definition at line 277 of file Variant.h.
Referenced by Entity::CallFunctionRecursivelyWithUpdatedVar(), Interpolate(), TouchHandlerArcadeComponent::OnInput(), TouchDragComponent::OnInput(), TouchHandlerComponent::OnInput(), InterpolateComponent::OnUpdate(), operator+=(), operator-=(), operator==(), Print(), Save(), VariantList::SerializeToMem(), and Set().
uint32& Variant::GetUINT32 () [inline]
Definition at line 161 of file Variant.h.
References m_var, Set(), TYPE_UINT32, and TYPE_UNUSED.
Referenced by AnimateEntity(), Entity::CallFunctionRecursivelyWithUpdatedVar(), ConvertEntityClickToScreenCoords(), FilterComponent::FilterOnInput(), FilterInputComponent::FilterOnInput(), GetAlignmentEntity(), GetFilterSetting(), Interpolate(), IsCheckboxChecked(), IsDisabledEntity(), MeasureEntityAndChildren(), SelectButtonWithCustomInputComponent::OnAdd(), SliderComponent::OnAdd(), TapSequenceDetectComponent::OnAdd(), FilterComponent::OnAdd(), TextRenderComponent::OnAdd(), FilterInputComponent::OnAdd(), BlinkComponent::OnAdd(), UnderlineRenderComponent::OnAdd(), UnpackArchiveComponent::OnAdd(), ProgressBarComponent::OnAdd(), RenderClipComponent::OnAdd(), RenderScissorComponent::OnAdd(), InterpolateComponent::OnAdd(), RectRenderComponent::OnAdd(), TouchStripComponent::OnAdd(), TyperComponent::OnAdd(), TouchHandlerArcadeComponent::OnAdd(), EmitVirtualKeyComponentAdvanced::OnAdd(), EmitVirtualKeyComponent::OnAdd(), TouchDragComponent::OnAdd(), RandomAudioPlayerComponent::OnAdd(), TrailRenderComponent::OnAdd(), TextBoxRenderComponent::OnAdd(), ScrollBarRenderComponent::OnAdd(), LogDisplayComponent::OnAdd(), InputTextRenderComponent::OnAdd(), OverlayRenderComponent::OnAdd(), CustomInputComponent::OnAdd(), SpriteAnimationRenderComponent::OnAdd(), TouchHandlerComponent::OnAdd(), Button2DComponent::OnAdd(), ScrollComponent::OnAdd(), ArcadeInputComponent::OnAdd(), TouchHandlerArcadeComponent::OnInput(), TouchDragComponent::OnInput(), TouchHandlerComponent::OnInput(), GamepadMoga::OnJoypadEvent(), BaseApp::OnMessage(), ArcadeInputComponent::OnRawKeyboard(), OnShowTextMessage(), operator+=(), operator-=(), operator==(), Print(), and Set().
const uint32& Variant::GetUINT32 () const [inline]
Definition at line 167 of file Variant.h.
References m_var, and TYPE_UINT32.
CL_Vec2f& Variant::GetVector2 () [inline]
Definition at line 208 of file Variant.h.
References m_var, Set(), and TYPE_UNUSED.
Referenced by AdjustGUIElementForWindowView(), Entity::CallFunctionRecursivelyWithUpdatedVar(), Entity::CallFunctionRecursivelyWithUpdatedVarBackwards(), ConvertEntityClickToScreenCoords(), CreateCheckbox(), CreateSlider(), EntityIsOnScreen(), EntityRetinaRemapIfNeeded(), EntityScaleiPad(), EntitySetScaleBySize(), FakeClickAnEntity(), FilterInputComponent::FilterOnInput(), RenderClipComponent::FilterOnRender(), RenderScissorComponent::FilterOnRender(), GetPos2DEntity(), GetScale2DEntity(), GetScrollProgressEntity(), GetSize2DEntity(), Interpolate(), LightBarOnChange(), ManuallySetAlignmentEntity(), MeasureEntityAndChildren(), SliderComponent::OnAdd(), FilterInputComponent::OnAdd(), ProgressBarComponent::OnAdd(), RenderClipComponent::OnAdd(), UnderlineRenderComponent::OnAdd(), RenderScissorComponent::OnAdd(), TapSequenceDetectComponent::OnAdd(), TemplateComponent::OnAdd(), TextRenderComponent::OnAdd(), UnpackArchiveComponent::OnAdd(), RectRenderComponent::OnAdd(), TouchStripComponent::OnAdd(), TouchHandlerArcadeComponent::OnAdd(), TouchDragComponent::OnAdd(), TrailRenderComponent::OnAdd(), TextBoxRenderComponent::OnAdd(), DPadComponent::OnAdd(), ScrollBarRenderComponent::OnAdd(), LogDisplayComponent::OnAdd(), InputTextRenderComponent::OnAdd(), OverlayRenderComponent::OnAdd(), SpriteAnimationRenderComponent::OnAdd(), Button2DComponent::OnAdd(), TouchHandlerComponent::OnAdd(), SplashComponent::OnAdd(), ScrollComponent::OnAdd(), ArcadeInputComponent::OnAdd(), OneTimeBobEntity(), TouchHandlerArcadeComponent::OnInput(), TouchDragComponent::OnInput(), TouchHandlerComponent::OnInput(), BaseApp::OnMessage(), operator+=(), operator-=(), operator==(), Print(), ResizeScrollBounds(), SendFakeButtonPushToEntity(), Set(), SetupLightBarSelect(), SlideScreen(), SlideScreenVertical(), ZoomFromPositionEntity(), ZoomToPositionFromThisOffsetEntity(), ZoomToPositionOffsetEntity(), and ZoomToPositionOffsetEntityMulti().
const CL_Vec2f& Variant::GetVector2 () const [inline]
Definition at line 217 of file Variant.h.
References m_var, and TYPE_VECTOR2.
CL_Vec3f& Variant::GetVector3 () [inline]
Definition at line 234 of file Variant.h.
References m_var, Set(), and TYPE_UNUSED.
Referenced by BaseApp::OnMessage(), operator+=(), operator-=(), operator==(), Print(), and Set().
const CL_Vec3f& Variant::GetVector3 () const [inline]
Definition at line 243 of file Variant.h.
References m_var, and TYPE_VECTOR3.
void Variant::Interpolate (Variant * pA, Variant * pB, float curPos, eInterpolateType type)
Definition at line 255 of file Variant.cpp.
References ColorCombineMix(), GetFloat(), GetINT32(), GetType(), GetUINT32(), GetVector2(), INTERPOLATE_BOUNCE_TO, INTERPOLATE_EASE_FROM, INTERPOLATE_EASE_FROM_QUARTIC, INTERPOLATE_EASE_TO, INTERPOLATE_EASE_TO_QUARTIC, INTERPOLATE_LINEAR, INTERPOLATE_LINEAR_AS_COLOR, INTERPOLATE_SMOOTHSTEP, INTERPOLATE_SMOOTHSTEP_AS_COLOR, LogError(), Set(), TYPE_FLOAT, TYPE_INT32, TYPE_UINT32, and TYPE_VECTOR2.
Referenced by InterpolateComponent::OnUpdate().
bool Variant::operator!= (const Variant & rhs) const
Inequality operator.
The opposite of operator==().
See also:
operator==() for a thorough explanation.
Definition at line 197 of file Variant.cpp.
References operator==().
Variant & Variant::operator+= (const Variant & rhs)
Add-and-assign operator.
Adds the value of rhs to the value of this Variant and assigns the new value to this. The type of this must match the type of rhs.
The Variant type's specific addition operator is used. For example the CL_Vec2f::operator+() is used when adding two vectors together.
This operator has effect only for Variant types where adding two values makes sense and is supported, such as the float and integer types. Adding for example two pointers together makes no sense so this operator has no effect for the TYPE_ENTITY nor TYPE_COMPONENT types among others.
Note:
this operator is also supported for TYPE_STRING: it performs string catenation as expected.
Returns:
a reference to this.
Definition at line 81 of file Variant.cpp.
References GetFloat(), GetINT32(), GetString(), GetType(), GetUINT32(), GetVector2(), GetVector3(), Set(), TYPE_FLOAT, TYPE_INT32, TYPE_STRING, TYPE_UINT32, TYPE_VECTOR2, and TYPE_VECTOR3.
Variant & Variant::operator-= (const Variant & rhs)
Subtract-and-assign operator.
Subtracts the value of rhs from the value of this Variant and assigns the new value to this. The type of this must match the type of rhs.
The Variant type's specific subtraction operator is used. For example the CL_Vec2f::operator-() is used when subtracting two vectors.
This operator has effect only for Variant types where subtracting two values makes sense and is supported, such as the float and integer types. Subtracting for example two pointers from each other makes no sense so this operator has no effect for the TYPE_ENTITY nor TYPE_COMPONENT types among others.
Returns:
a reference to this.
Definition at line 119 of file Variant.cpp.
References GetFloat(), GetINT32(), GetType(), GetUINT32(), GetVector2(), GetVector3(), Set(), TYPE_FLOAT, TYPE_INT32, TYPE_UINT32, TYPE_VECTOR2, and TYPE_VECTOR3.
Variant& Variant::operator= (const Variant & rhs) [inline]
Definition at line 289 of file Variant.h.
References m_var.
bool Variant::operator== (const Variant & rhs) const
Equality operator.
Variants are considered equal when their types and values are equal.
If the type is TYPE_UNUSED then it doesn't matter what the values are, the Variants are considered equal.
The values are compared for equality using the values' classes' own operator==(). For example if the type is TYPE_VECTOR2 then CL_Vec2f::operator==() is used for comparing the values.
Definition at line 153 of file Variant.cpp.
References GetComponent(), GetEntity(), GetFloat(), GetINT32(), GetRect(), GetString(), GetType(), GetUINT32(), GetVector2(), GetVector3(), TYPE_COMPONENT, TYPE_ENTITY, TYPE_FLOAT, TYPE_INT32, TYPE_RECT, TYPE_STRING, TYPE_UINT32, TYPE_UNUSED, TYPE_VECTOR2, and TYPE_VECTOR3.
Referenced by operator!=().
std::string Variant::Print ()
Definition at line 202 of file Variant.cpp.
References GetFloat(), GetINT32(), GetRect(), GetString(), GetType(), GetUINT32(), GetVector2(), GetVector3(), PrintRect(), PrintVector2(), PrintVector3(), toString(), TYPE_COMPONENT, TYPE_ENTITY, TYPE_FLOAT, TYPE_INT32, TYPE_RECT, TYPE_STRING, TYPE_UINT32, TYPE_UNUSED, TYPE_VECTOR2, and TYPE_VECTOR3.
Referenced by VariantDB::DumpAsString(), VariantList::GetContentsAsDebugString(), and VariantDB::Print().
void Variant::Reset () [inline]
Definition at line 86 of file Variant.h.
References TYPE_UNUSED.
Referenced by VariantList::Reset().
bool Variant::Save (FILE * fp, const string & varName)
Definition at line 357 of file Variant.cpp.
References GetSizeOfData(), GetType(), LogMsg(), m_var, SaveToFile(), and TYPE_STRING.
Referenced by VariantDB::Save().
void Variant::Set (const Variant & v)
Definition at line 39 of file Variant.cpp.
References GetComponent(), GetEntity(), GetFloat(), GetINT32(), GetRect(), GetString(), GetType(), GetUINT32(), GetVector2(), GetVector3(), TYPE_COMPONENT, TYPE_ENTITY, TYPE_FLOAT, TYPE_INT32, TYPE_RECT, TYPE_STRING, TYPE_UINT32, TYPE_VECTOR2, and TYPE_VECTOR3.
Referenced by AddFilter(), AddHotKeyToButton(), AddInputMovementFocusIfNeeded(), MySQLManager::AddSelectResults(), AdjustGUIElementForWindowView(), AdManager::AdManager(), AnimateEntity(), AnimateEntitySetMirrorMode(), AnimateStopEntity(), AnimateStopEntityAndSetFrame(), BobEntity(), Entity::CallFunctionRecursivelyWithUpdatedVar(), Entity::CallFunctionRecursivelyWithUpdatedVarBackwards(), CopyPropertiesToEntity(), CreateButtonHotspot(), CreateCheckbox(), CreateInputTextEntity(), CreateLogDisplayEntity(), CreateOverlayEntity(), CreateOverlayRectEntity(), CreateScrollingTextBoxEntity(), CreateSlider(), CreateTextBoxEntity(), CreateTextLabelEntity(), DisableAllButtonsEntity(), DisableComponentByName(), DisableEntityButtonByName(), EnableAllButtonsEntity(), EnableComponentByName(), EnableEntityButtonByName(), EntityRetinaRemapIfNeeded(), EntityScaleiPad(), EntitySetScaleBySize(), FadeInEntity(), FadeScreen(), FadeScreenUp(), FilterComponent::FilterOnInput(), FilterInputComponent::FilterOnInput(), FlashOnceEntity(), FlashStartEntity(), GetComponent(), GetEntity(), GetFloat(), GetINT32(), GetRect(), GetUINT32(), GetVector2(), GetVector3(), TouchDeviceEmulatorPointerEventHandler::handlePointerDownEvent(), TouchDeviceEmulatorPointerEventHandler::handlePointerMoveEvent(), Interpolate(), VariantDB::Load(), MakeButtonEmitVirtualGameKey(), ManuallySetAlignmentEntity(), MorphToFloatComponent(), MorphToVec2Component(), DPadComponent::OnAdd(), ScrollBarRenderComponent::OnAdd(), Gamepad::OnButton(), OneTimeBobEntity(), AdManager::OnMessage(), BaseApp::OnMessage(), MoveButtonState::OnPress(), MoveButtonState::OnPressToggle(), InterpolateComponent::OnUpdate(), TyperComponent::OnUpdate(), operator+=(), operator-=(), PreloadKeyboard(), MoveButtonState::ReleaseIfNeeded(), ResizeScrollBounds(), ScaleEntity(), SendFakeInputMessageToEntity(), VariantList::SerializeFromMem(), Set(), SetAlignmentEntity(), SetAlphaEntity(), SpriteAnimationUtils::SetAnimationName(), SetButtonClickSound(), SetButtonRepeatDelayMS(), SetButtonStyleEntity(), SetButtonVisualStyleEntity(), SetCheckBoxChecked(), SetConsole(), SetEntityOverlayToUnloadImageOnKill(), SetFilterSetting(), SetOverlayImageEntity(), SetPos2DEntity(), SetProgressBarPercent(), SetScale2DEntity(), SetSize2DEntity(), SetTextEntity(), SetTextEntityByName(), SetTextShadowColor(), SetTouchPaddingEntity(), SpriteAnimationUtils::SetupAnimationEntity(), SetupAnimEntity(), SetupInterpolateComponent(), SetupLightBarSelect(), SetupTextEntity(), SetVariant(), SetVisibleEntity(), ProtonTester::showResultOnScreen(), SlideScreen(), SlideScreenVertical(), SpriteAnimationUtils::StartAnimationEntity(), TypeTextLabelEntity(), Variant(), ZoomFromPositionEntity(), and ZoomToPositionFromThisOffsetEntity().
void Variant::Set (float var) [inline]
Definition at line 97 of file Variant.h.
References m_var, TYPE_FLOAT, and TYPE_UNUSED.
void Variant::Set (const Entity * pEnt) [inline]
Definition at line 116 of file Variant.h.
References TYPE_ENTITY, and TYPE_UNUSED.
void Variant::Set (const EntityComponent * pEnt) [inline]
Definition at line 135 of file Variant.h.
References TYPE_COMPONENT, and TYPE_UNUSED.
void Variant::Set (uint32 var) [inline]
Definition at line 154 of file Variant.h.
References m_var, TYPE_UINT32, and TYPE_UNUSED.
void Variant::Set (int32 var) [inline]
Definition at line 173 of file Variant.h.
References m_var, TYPE_INT32, and TYPE_UNUSED.
void Variant::Set (string const & var)
Definition at line 26 of file Variant.cpp.
References TYPE_STRING, and TYPE_UNUSED.
void Variant::Set (CL_Vec2f const & var) [inline]
Definition at line 202 of file Variant.h.
References m_var, TYPE_UNUSED, and TYPE_VECTOR2.
void Variant::Set (float x, float y) [inline]
Definition at line 223 of file Variant.h.
References Set().
void Variant::Set (CL_Vec3f const & var) [inline]
Definition at line 228 of file Variant.h.
References m_var, TYPE_UNUSED, and TYPE_VECTOR3.
void Variant::Set (CL_Rectf const & var) [inline]
Definition at line 249 of file Variant.h.
References m_var, TYPE_RECT, and TYPE_UNUSED.
void Variant::Set (float x, float y, float z) [inline]
Definition at line 271 of file Variant.h.
References Set().
void Variant::SetVariant (Variant * pVar)
Definition at line 34 of file Variant.cpp.
References Set().
Friends And Related Function Documentation
Variant operator+ (Variant lhs, const Variant & rhs) [related]
Adds two Variants together. Returns a new Variant that contains the result of the operation.
See also:
Variant::operator+=()
Definition at line 395 of file Variant.cpp.
Variant operator- (Variant lhs, const Variant & rhs) [related]
Subtracts rhs from lhs. Returns a new Variant that contains the result of the operation.
See also:
Variant::operator-=()
Definition at line 401 of file Variant.cpp.
friend class VariantList [friend]
Definition at line 373 of file Variant.h.
Member Data Documentation
boost::signal<void (Variant*)> Variant::GetSigOnChanged)()
Definition at line 92 of file Variant.h.
Referenced by SliderComponent::OnAdd(), TextRenderComponent::OnAdd(), ProgressBarComponent::OnAdd(), InterpolateComponent::OnAdd(), RectRenderComponent::OnAdd(), TouchHandlerArcadeComponent::OnAdd(), EmitVirtualKeyComponentAdvanced::OnAdd(), RandomAudioPlayerComponent::OnAdd(), TextBoxRenderComponent::OnAdd(), DPadComponent::OnAdd(), ScrollBarRenderComponent::OnAdd(), LogDisplayComponent::OnAdd(), OverlayRenderComponent::OnAdd(), InputTextRenderComponent::OnAdd(), SpriteAnimationRenderComponent::OnAdd(), Button2DComponent::OnAdd(), TouchHandlerComponent::OnAdd(), and ArcadeInputComponent::OnAdd().
float Variant::m_as_floats[4]
Definition at line 390 of file Variant.h.
int32 Variant::m_as_int32s[4]
Definition at line 392 of file Variant.h.
uint32 Variant::m_as_uint32s[4]
Definition at line 391 of file Variant.h.
byte Variant::m_var[C_VAR_SPACE_BYTES]
Definition at line 387 of file Variant.h.
Referenced by GetFloat(), GetINT32(), GetRect(), GetUINT32(), GetVector2(), GetVector3(), operator=(), Save(), and Set().
The documentation for this class was generated from the following files:
Variant.h
Variant.cpp