Proton: LogDisplayComponent Class Reference
LogDisplayComponent Class Reference
#include <LogDisplayComponent.h>
Public Member Functions
LogDisplayComponent ()
virtual ~LogDisplayComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
Console * GetConsole ()
void SetConsole (Console *pConsole)
Detailed Description
Definition at line 41 of file LogDisplayComponent.h.
Constructor & Destructor Documentation
LogDisplayComponent::LogDisplayComponent ()
Definition at line 10 of file LogDisplayComponent.cpp.
References EntityComponent::SetName().
LogDisplayComponent::~LogDisplayComponent () [virtual]
Definition at line 22 of file LogDisplayComponent.cpp.
Member Function Documentation
Console* LogDisplayComponent::GetConsole () [inline]
Definition at line 51 of file LogDisplayComponent.h.
void LogDisplayComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 27 of file LogDisplayComponent.cpp.
References FONT_SMALL, GetBaseApp(), BaseApp::GetConsole(), Variant::GetFloat(), EntityComponent::GetFunction(), Entity::GetFunction(), EntityComponent::GetParent(), Variant::GetSigOnChanged, Variant::GetString(), Variant::GetUINT32(), EntityComponent::GetVar(), Entity::GetVar(), EntityComponent::GetVarWithDefault(), Entity::GetVarWithDefault(), Variant::GetVector2(), Console::m_sig_on_text_added, and FunctionObject::sig_function.
void LogDisplayComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 77 of file LogDisplayComponent.cpp.
void LogDisplayComponent::SetConsole (Console * pConsole)
Definition at line 309 of file LogDisplayComponent.cpp.
References Console::m_sig_on_text_added.
The documentation for this class was generated from the following files:
LogDisplayComponent.h
LogDisplayComponent.cpp