Proton: SpriteAnimationSet Class Reference
SpriteAnimationSet Class Reference
A collection of SpriteAnimations that use the same sprite sheet.
#include <SpriteAnimation.h>
Public Member Functions
bool LoadFile (const std::string &fileName)
Loads a set of sprite animations from file named fileName.
const std::string & GetSpriteSheetImageName () const
Gets the name of the sprite sheet resource that this set of animations uses.
void AddAnimation (const std::string &animationName, const SpriteAnimation &animation)
Adds a new animation to this set of animations with the given animationName.
const SpriteAnimation * GetAnimation (const std::string &animationName) const
Gets the animation with name animationName.
Detailed Description
A collection of SpriteAnimations that use the same sprite sheet.
See also:
SpriteSheetSurface
Definition at line 156 of file SpriteAnimation.h.
Member Function Documentation
void SpriteAnimationSet::AddAnimation (const std::string & animationName, const SpriteAnimation & animation)
Adds a new animation to this set of animations with the given animationName.
If there already is an animation with the given name in this set the previous animation is overwritten.
Definition at line 192 of file SpriteAnimation.cpp.
const SpriteAnimation * SpriteAnimationSet::GetAnimation (const std::string & animationName) const
Gets the animation with name animationName.
Returns NULL if no such animation exists.
Definition at line 197 of file SpriteAnimation.cpp.
const string & SpriteAnimationSet::GetSpriteSheetImageName () const
Gets the name of the sprite sheet resource that this set of animations uses.
Definition at line 187 of file SpriteAnimation.cpp.
bool SpriteAnimationSet::LoadFile (const std::string & fileName)
Loads a set of sprite animations from file named fileName.
Returns:
true if the loading succeeded, false if anything failed.
Definition at line 163 of file SpriteAnimation.cpp.
References FileInstance::GetAsChars(), FileInstance::IsLoaded(), and LogError().
Referenced by ResourceManager::GetSpriteAnimationSet().
The documentation for this class was generated from the following files:
SpriteAnimation.h
SpriteAnimation.cpp