Proton: NetHTTP Class Reference
NetHTTP Class Reference
#include <NetHTTP.h>
Public Types
enum eState {
STATE_IDLE, STATE_ACTIVE, STATE_FINISHED, STATE_FORWARD,
STATE_ABORT
}
enum eError {
ERROR_NONE, ERROR_CANT_RESOLVE_URL, ERROR_COMMUNICATION_TIMEOUT, ERROR_WRITING_FILE,
ERROR_404_FILE_NOT_FOUND
}
Public Member Functions
NetHTTP ()
virtual ~NetHTTP ()
void Setup (string serverName, int port, string query)
bool AddPostData (const string &name, const byte *pData, int len=-1)
bool SetFileOutput (const string &fName)
bool Start ()
eState GetState ()
eError GetError ()
int GetDownloadedBytes ()
int GetExpectedBytes ()
const byte * GetDownloadedData ()
void Update ()
void Reset (bool bClearPostData=true)
Detailed Description
Definition at line 49 of file NetHTTP.h.
Member Enumeration Documentation
enum NetHTTP::eError
Enumerator:
ERROR_NONE
ERROR_CANT_RESOLVE_URL
ERROR_COMMUNICATION_TIMEOUT
ERROR_WRITING_FILE
ERROR_404_FILE_NOT_FOUND
Definition at line 64 of file NetHTTP.h.
enum NetHTTP::eState
Enumerator:
STATE_IDLE
STATE_ACTIVE
STATE_FINISHED
STATE_FORWARD
STATE_ABORT
Definition at line 55 of file NetHTTP.h.
Constructor & Destructor Documentation
NetHTTP::NetHTTP ()
Definition at line 12 of file NetHTTP.cpp.
References Reset().
NetHTTP::~NetHTTP () [virtual]
Definition at line 18 of file NetHTTP.cpp.
References RemoveFile().
Member Function Documentation
bool NetHTTP::AddPostData (const string & name, const byte * pData, int len = -1)
Definition at line 77 of file NetHTTP.cpp.
References URLEncoder::encodeData().
int NetHTTP::GetDownloadedBytes ()
Definition at line 391 of file NetHTTP.cpp.
const byte * NetHTTP::GetDownloadedData ()
Definition at line 382 of file NetHTTP.cpp.
eError NetHTTP::GetError () [inline]
Definition at line 81 of file NetHTTP.h.
int NetHTTP::GetExpectedBytes () [inline]
Definition at line 84 of file NetHTTP.h.
eState NetHTTP::GetState () [inline]
Definition at line 80 of file NetHTTP.h.
Referenced by Update().
void NetHTTP::Reset (bool bClearPostData = true)
Definition at line 28 of file NetHTTP.cpp.
References ERROR_NONE, RemoveFile(), and STATE_IDLE.
Referenced by NetHTTP().
bool NetHTTP::SetFileOutput (const string & fName)
Definition at line 60 of file NetHTTP.cpp.
References ERROR_WRITING_FILE.
void NetHTTP::Setup (string serverName, int port, string query)
Definition at line 53 of file NetHTTP.cpp.
bool NetHTTP::Start ()
Definition at line 151 of file NetHTTP.cpp.
References ERROR_CANT_RESOLVE_URL, ERROR_NONE, NetSocket::Init(), STATE_ACTIVE, and NetSocket::Write().
void NetHTTP::Update ()
Definition at line 246 of file NetHTTP.cpp.
References CheckCharVectorForString(), ERROR_COMMUNICATION_TIMEOUT, ERROR_WRITING_FILE, GetBaseApp(), NetSocket::GetBuffer(), NetSocket::GetIdleTimeMS(), GetState(), BaseApp::GetTick(), GetTick(), STATE_ABORT, STATE_ACTIVE, and NetSocket::Update().
The documentation for this class was generated from the following files:
NetHTTP.h
NetHTTP.cpp