Proton: Message Class Reference
Message Class Reference
#include <MessageManager.h>
Public Member Functions
Message (eMessageClass messageClass, eTimingSystem timer, eMessageType type)
void SetParm1 (float parm1)
float GetParm1 ()
void SetParm2 (float parm2)
float GetParm2 ()
void SetParm3 (int parm3)
int GetParm3 ()
void SetParm4 (int parm4)
uint32 GetParm4 ()
eTimingSystem GetTimingMethod ()
unsigned int GetDeliveryTime ()
eMessageType GetType ()
eMessageClass GetClass ()
void SetDeliveryTime (int deliveryTimeMS)
Variant & Get ()
VariantList & GetVariantList ()
void Set (const Variant &v)
void Set (const VariantList *v)
void SetTargetEntity (Entity *pEnt)
Entity * GetTargetEntity ()
void SetFunctionPointer (PtrFuncVarList pFunctionWithVList)
PtrFuncVarList GetFunctionPointer ()
void SetTargetComponent (EntityComponent *pComp)
void SetComponentToAdd (EntityComponent *pComp)
void ClearComponent ()
EntityComponent * GetTargetComponent ()
void OnEntityDestroyed (Entity *pEnt)
void OnComponentDestroyed (VariantList *pVList)
void SetVarName (string const &varName)
string const & GetVarName ()
void SetStringParm (string const &msg)
string const & GetStringParm ()
Detailed Description
Definition at line 199 of file MessageManager.h.
Constructor & Destructor Documentation
Message::Message (eMessageClass messageClass, eTimingSystem timer, eMessageType type) [inline]
Definition at line 204 of file MessageManager.h.
Member Function Documentation
void Message::ClearComponent () [inline]
Definition at line 237 of file MessageManager.h.
Variant& Message::Get () [inline]
Definition at line 225 of file MessageManager.h.
Referenced by BaseApp::OnMessage().
eMessageClass Message::GetClass () [inline]
Definition at line 223 of file MessageManager.h.
Referenced by BaseApp::OnMessage().
unsigned int Message::GetDeliveryTime () [inline]
Definition at line 221 of file MessageManager.h.
PtrFuncVarList Message::GetFunctionPointer () [inline]
Definition at line 233 of file MessageManager.h.
float Message::GetParm1 () [inline]
Definition at line 213 of file MessageManager.h.
Referenced by IAPManager::HandleIAPBuyResult(), IAPManager::HandleItemUpdateState(), IAPManager::HandlePurchaseListReply(), AdManager::OnMessage(), and BaseApp::OnMessage().
float Message::GetParm2 () [inline]
Definition at line 215 of file MessageManager.h.
Referenced by AdManager::OnMessage(), and BaseApp::OnMessage().
int Message::GetParm3 () [inline]
Definition at line 217 of file MessageManager.h.
Referenced by BaseApp::OnMessage().
uint32 Message::GetParm4 () [inline]
Definition at line 219 of file MessageManager.h.
Referenced by BaseApp::OnMessage().
string const& Message::GetStringParm () [inline]
Definition at line 245 of file MessageManager.h.
Referenced by IAPManager::HandleIAPBuyResult(), IAPManager::HandleItemUpdateState(), IAPManager::HandlePurchaseListReply(), AdManager::OnMessage(), and BaseApp::OnMessage().
EntityComponent* Message::GetTargetComponent () [inline]
Definition at line 238 of file MessageManager.h.
Entity* Message::GetTargetEntity () [inline]
Definition at line 230 of file MessageManager.h.
eTimingSystem Message::GetTimingMethod () [inline]
Definition at line 220 of file MessageManager.h.
eMessageType Message::GetType () [inline]
Definition at line 222 of file MessageManager.h.
Referenced by OnEntityDestroyed(), AdManager::OnMessage(), IAPManager::OnMessage(), and BaseApp::OnMessage().
VariantList& Message::GetVariantList () [inline]
Definition at line 226 of file MessageManager.h.
string const& Message::GetVarName () [inline]
Definition at line 243 of file MessageManager.h.
Referenced by BaseApp::OnMessage().
void Message::OnComponentDestroyed (VariantList * pVList)
Definition at line 35 of file MessageManager.cpp.
Referenced by SetTargetComponent().
void Message::OnEntityDestroyed (Entity * pEnt)
Definition at line 21 of file MessageManager.cpp.
References GetType(), and MESSAGE_TYPE_ADD_COMPONENT.
Referenced by SetComponentToAdd(), and SetTargetEntity().
void Message::Set (const Variant & v) [inline]
Definition at line 227 of file MessageManager.h.
Referenced by MessageManager::CallComponentFunction(), MessageManager::CallEntityFunction(), MessageManager::CallEntityFunctionRecursively(), MessageManager::CallStaticFunction(), MessageManager::SendGame(), MessageManager::SendGUI(), MessageManager::SetComponentVariable(), and MessageManager::SetEntityVariable().
void Message::Set (const VariantList * v) [inline]
Definition at line 228 of file MessageManager.h.
void Message::SetComponentToAdd (EntityComponent * pComp)
Definition at line 49 of file MessageManager.cpp.
References EntityComponent::GetParent(), OnEntityDestroyed(), and Entity::sig_onRemoved.
Referenced by MessageManager::AddComponent().
void Message::SetDeliveryTime (int deliveryTimeMS)
Definition at line 6 of file MessageManager.cpp.
References GetBaseApp(), BaseApp::GetGameTick(), BaseApp::GetTick(), and TIMER_GAME.
Referenced by MessageManager::AddComponent(), MessageManager::CallComponentFunction(), MessageManager::CallEntityFunction(), MessageManager::CallEntityFunctionRecursively(), MessageManager::CallStaticFunction(), MessageManager::RemoveComponentByName(), MessageManager::SendGame(), MessageManager::SendGUI(), MessageManager::SendGUIEx(), MessageManager::SendGUIEx2(), MessageManager::SendGUIStringEx(), MessageManager::SetComponentVariable(), and MessageManager::SetEntityVariable().
void Message::SetFunctionPointer (PtrFuncVarList pFunctionWithVList) [inline]
Definition at line 232 of file MessageManager.h.
Referenced by MessageManager::CallStaticFunction().
void Message::SetParm1 (float parm1) [inline]
Definition at line 212 of file MessageManager.h.
Referenced by MessageManager::SendGUI(), MessageManager::SendGUIEx(), MessageManager::SendGUIEx2(), and MessageManager::SendGUIStringEx().
void Message::SetParm2 (float parm2) [inline]
Definition at line 214 of file MessageManager.h.
Referenced by MessageManager::SendGUI(), MessageManager::SendGUIEx(), MessageManager::SendGUIEx2(), and MessageManager::SendGUIStringEx().
void Message::SetParm3 (int parm3) [inline]
Definition at line 216 of file MessageManager.h.
Referenced by MessageManager::SendGUI(), MessageManager::SendGUIEx(), MessageManager::SendGUIEx2(), and MessageManager::SendGUIStringEx().
void Message::SetParm4 (int parm4) [inline]
Definition at line 218 of file MessageManager.h.
Referenced by MessageManager::SendGUI(), and MessageManager::SendGUIEx2().
void Message::SetStringParm (string const & msg) [inline]
Definition at line 244 of file MessageManager.h.
Referenced by MessageManager::CallComponentFunction(), and MessageManager::SendGUIStringEx().
void Message::SetTargetComponent (EntityComponent * pComp)
Definition at line 41 of file MessageManager.cpp.
References EntityComponent::GetFunction(), OnComponentDestroyed(), and FunctionObject::sig_function.
Referenced by MessageManager::CallComponentFunction(), and MessageManager::SetComponentVariable().
void Message::SetTargetEntity (Entity * pEnt)
Definition at line 14 of file MessageManager.cpp.
References OnEntityDestroyed(), and Entity::sig_onRemoved.
Referenced by MessageManager::AddComponent(), MessageManager::CallComponentFunction(), MessageManager::CallEntityFunction(), MessageManager::CallEntityFunctionRecursively(), MessageManager::RemoveComponentByName(), and MessageManager::SetEntityVariable().
void Message::SetVarName (string const & varName) [inline]
Definition at line 242 of file MessageManager.h.
Referenced by MessageManager::CallComponentFunction(), MessageManager::CallEntityFunction(), MessageManager::CallEntityFunctionRecursively(), MessageManager::RemoveComponentByName(), MessageManager::SendGame(), MessageManager::SetComponentVariable(), and MessageManager::SetEntityVariable().
The documentation for this class was generated from the following files:
MessageManager.h
MessageManager.cpp