Proton: Entity Class Reference
Entity Class Reference
#include <Entity.h>
Public Types
enum eRecursiveVarOp { RECURSIVE_VAR_OP_ADDITION, RECURSIVE_VAR_OP_SUBTRACTION, RECURSIVE_VAR_OP_ADDITION_PLUS_ALIGNMENT_OFFSET, RECURSIVE_VAR_OP_SUBTRACTION_PLUS_ALIGNMENT_OFFSET }
enum eFilterSlotInfo { FILTER_INDEX = 3 }
enum eFilterCommunication { FILTER_ALLOW, FILTER_REFUSE_ALL, FILTER_REFUSE_CHILDREN }
Public Member Functions
Entity (string name)
Entity (EntityComponent *pComponent)
Entity (string name, EntityComponent *pComponent)
Entity ()
~Entity ()
void SetName (string name)
string GetName ()
Entity * AddEntity (Entity *pEntity)
Entity * GetEntityByName (const string &name)
Searches for an Entity with the given name.
bool RemoveEntityByName (const string &name, bool bRecursive=false)
bool RemoveEntityByNameSafe (const string &name, bool bRecursive)
bool RemoveEntityByAddress (Entity *pEntToDelete, bool DeleteAlso=true)
void MoveEntityToTopByAddress (Entity *pEnt)
void MoveEntityToBottomByAddress (Entity *pEnt)
void RemoveAllEntities ()
bool RemoveEntitiesByNameThatStartWith (const string &name, bool bRecursive=false)
EntityComponent * AddComponent (EntityComponent *pComp)
EntityComponent * GetComponentByName (string const &name, bool bAlsoCheckParents=false)
Searches for an EntityComponent with the given name and returns it.
bool RemoveComponentByAddress (EntityComponent *pCompToDelete, bool bDeleteAlso=true)
bool RemoveComponentByName (const string &name)
void MoveComponentToTopByAddress (EntityComponent *pComp)
void MoveComponentToBottomByAddress (EntityComponent *pComp)
void RemoveAllComponents ()
void PrintTreeAsText (int indent=0)
VariantDB * GetShared ()
Variant * GetVar (const string &varName)
Gets a named Variant from this Entity's variant DB.
Variant * GetVarWithDefault (const string &varName, const Variant &var)
Gets a named Variant from this Entity's variant DB.
FunctionObject * GetFunction (const string &funcName)
Entity * GetParent ()
void SetParent (Entity *pEntity)
bool GetTaggedForDeletion ()
void SetTaggedForDeletion ()
void CallFunctionRecursively (string funcName, VariantList *pVList)
void CallFunctionRecursivelyWithUpdatedVar (const string funcName, VariantList *pVList, const string &varName, int varIndex, eRecursiveVarOp op, vector< EntityCall > *pEntList=NULL)
void CallFunctionRecursivelyWithUpdatedVarBackwards (const string funcName, VariantList *pVList, const string &varName, int varIndex, eRecursiveVarOp op)
EntityList * GetChildren ()
ComponentList * GetComponents ()
void OnFilterAdd ()
void OnFilterRemove ()
void AddEntitiesToVectorRescursively (vector< Entity * > *pEntVec)
Public Attributes
boost::signal< void(Entity *) sig_onRemoved)
Detailed Description
Definition at line 29 of file Entity.h.
Member Enumeration Documentation
enum Entity::eFilterCommunication
Enumerator:
FILTER_ALLOW
FILTER_REFUSE_ALL
FILTER_REFUSE_CHILDREN
Definition at line 52 of file Entity.h.
enum Entity::eFilterSlotInfo
Enumerator:
FILTER_INDEX
Definition at line 46 of file Entity.h.
enum Entity::eRecursiveVarOp
Enumerator:
RECURSIVE_VAR_OP_ADDITION
RECURSIVE_VAR_OP_SUBTRACTION
RECURSIVE_VAR_OP_ADDITION_PLUS_ALIGNMENT_OFFSET
RECURSIVE_VAR_OP_SUBTRACTION_PLUS_ALIGNMENT_OFFSET
Definition at line 38 of file Entity.h.
Constructor & Destructor Documentation
Entity::Entity (string name)
Definition at line 6 of file Entity.cpp.
Entity::Entity (EntityComponent * pComponent)
Definition at line 11 of file Entity.cpp.
References AddComponent().
Entity::Entity (string name, EntityComponent * pComponent)
Definition at line 17 of file Entity.cpp.
References AddComponent().
Entity::Entity ()
Definition at line 23 of file Entity.cpp.
Entity::~Entity ()
Definition at line 40 of file Entity.cpp.
References RemoveAllComponents(), RemoveAllEntities(), and sig_onRemoved.
Member Function Documentation
EntityComponent * Entity::AddComponent (EntityComponent * pComp)
Definition at line 90 of file Entity.cpp.
References EntityComponent::OnAdd().
Referenced by AddFilter(), AddFocusIfNeeded(), AddHotKeyToButton(), AddInputMovementFocusIfNeeded(), AnimateEntity(), CreateButtonHotspot(), CreateInputTextEntity(), CreateLogDisplayEntity(), CreateOverlayButtonEntity(), CreateOverlayEntity(), CreateOverlayRectEntity(), CreateScrollingTextBoxEntity(), CreateSlider(), CreateTextBoxEntity(), CreateTextButtonEntity(), CreateTextLabelEntity(), Entity(), FadeScreen(), FadeScreenUp(), TouchDeviceEmulatorPointerEventHandler::handlePointerDownEvent(), MakeButtonEmitVirtualGameKey(), DPadComponent::OnAdd(), SetConsole(), VariantTuner::setTunableVariant(), SpriteAnimationUtils::SetupAnimationEntity(), SetupEntityToEatInput(), SetupInterpolateComponent(), SpriteAnimationUtils::StartAnimationEntity(), and TypeTextLabelEntity().
void Entity::AddEntitiesToVectorRescursively (vector< Entity * > * pEntVec)
Definition at line 602 of file Entity.cpp.
Entity * Entity::AddEntity (Entity * pEntity)
Definition at line 78 of file Entity.cpp.
References SetParent().
Referenced by CreateInputTextEntity(), CreateLogDisplayEntity(), CreateOverlayEntity(), CreateOverlayRectEntity(), CreateScrollingTextBoxEntity(), CreateSlider(), CreateTextBoxEntity(), CreateTextLabelEntity(), FadeScreen(), FadeScreenUp(), TouchDeviceEmulatorPointerEventHandler::handlePointerDownEvent(), OnShowTextMessage(), and SetConsole().
void Entity::CallFunctionRecursively (string funcName, VariantList * pVList)
Definition at line 170 of file Entity.cpp.
References VariantDB::CallFunctionIfExists(), and GetShared().
Referenced by FocusInputComponent::OnInputRaw(), FocusUpdateComponent::OnUpdate(), and SendFakeInputMessageToEntity().
void Entity::CallFunctionRecursivelyWithUpdatedVar (const string funcName, VariantList * pVList, const string & varName, int varIndex, eRecursiveVarOp op, vector< EntityCall > * pEntList = NULL)
Definition at line 209 of file Entity.cpp.
References ALIGNMENT_UPPER_LEFT, VariantDB::CallFunctionIfExists(), FILTER_ALLOW, FILTER_INDEX, FILTER_REFUSE_ALL, FILTER_REFUSE_CHILDREN, GetAlignmentOffset(), VariantDB::GetFunctionIfExists(), GetShared(), Variant::GetType(), Variant::GetUINT32(), VariantDB::GetVarIfExists(), GetVarWithDefault(), Variant::GetVector2(), LogError(), VariantList::m_variant, EntityCall::pEnt, RECURSIVE_VAR_OP_ADDITION, RECURSIVE_VAR_OP_ADDITION_PLUS_ALIGNMENT_OFFSET, RECURSIVE_VAR_OP_SUBTRACTION, RECURSIVE_VAR_OP_SUBTRACTION_PLUS_ALIGNMENT_OFFSET, Variant::Set(), FunctionObject::sig_function, Variant::TYPE_VECTOR2, and EntityCall::vUpdatedVar.
Referenced by CallFunctionRecursivelyWithUpdatedVarBackwards().
void Entity::CallFunctionRecursivelyWithUpdatedVarBackwards (const string funcName, VariantList * pVList, const string & varName, int varIndex, eRecursiveVarOp op)
Definition at line 188 of file Entity.cpp.
References CallFunctionRecursivelyWithUpdatedVar(), Variant::GetVector2(), VariantList::m_variant, and Variant::Set().
Referenced by FocusInputComponent::OnInput().
EntityList* Entity::GetChildren () [inline]
Definition at line 134 of file Entity.h.
Referenced by DisableAllButtonsEntity(), EnableAllButtonsEntity(), FadeEntity(), FadeInEntity(), FadeOutAndKillChildrenEntities(), FadeOutEntity(), GetUsedTextures(), MeasureEntityAndChildren(), MorphToColorEntity(), PulsateColorEntity(), and SetDisabledOnAllComponentsRecursively().
EntityComponent * Entity::GetComponentByName (string const & name, bool bAlsoCheckParents = false)
Searches for an EntityComponent with the given name and returns it.
The EntityComponent is searched from this Entity's components.
If bAlsoCheckParents is true and the named EntityComponent is not found from this Entity then the parent Entity is searched also. The search continues up the Entity tree until the named EntityComponent is found or the top of the tree is reached.
If no such EntityComponent is found NULL is returned.
Definition at line 361 of file Entity.cpp.
References GetComponentByName(), and GetParent().
Referenced by ActivateTextInputEntity(), AddFocusIfNeeded(), AddInputMovementFocusIfNeeded(), AnimateEntity(), AnimateEntitySetMirrorMode(), AnimateStopEntity(), AnimateStopEntityAndSetFrame(), CreateSlider(), DisableAllButtonsEntity(), DisableComponentByName(), DisableEntityButtonByName(), DisableHorizontalScrolling(), EnableAllButtonsEntity(), EnableComponentByName(), EnableEntityButtonByName(), EnableRawMessageFocusInput(), EntityHasInputFocus(), GetComponentByName(), GetFilterSetting(), GetOverlayImageEntity(), GetScrollProgressEntity(), IsDisabledEntity(), IsEntityBobbing(), ScrollBarRenderComponent::OnAdd(), OneTimeBobEntity(), TyperComponent::OnUpdate(), InterpolateComponent::OnVarNameChanged(), VariantTuner::resetTunableVariant(), ResizeScrollBounds(), SpriteAnimationUtils::SetAnimationName(), SetButtonClickSound(), SetButtonRepeatDelayMS(), SetButtonStyleEntity(), SetButtonVisualStyleEntity(), SetEntityOverlayToUnloadImageOnKill(), SetFilterSetting(), SetOverlayImageEntity(), SetProgressBarPercent(), SetScrollProgressEntity(), SetTextEntity(), SetTextEntityByName(), SetTextShadowColor(), VariantTuner::setTunableVariant(), SetupAnimEntity(), SetupEntityToEatInput(), SetupInterpolateComponent(), SetupTextEntity(), SpriteAnimationUtils::StartAnimationEntity(), and TypeTextLabelEntity().
ComponentList* Entity::GetComponents () [inline]
Definition at line 135 of file Entity.h.
Referenced by GetUsedTextures(), and SetDisabledOnAllComponentsRecursively().
Entity * Entity::GetEntityByName (const string & name)
Searches for an Entity with the given name.
If the name of this Entity is name then returns the object itself. Otherwise the search descends recursively to the children Entities. If no Entity with the given name is found then NULL is returned.
Definition at line 100 of file Entity.cpp.
References GetEntityByName().
Referenced by DisableEntityButtonByName(), DisableHorizontalScrolling(), EnableEntityButtonByName(), FadeScreen(), FadeScreenUp(), FakeClickAnEntityByName(), GetEntityByName(), TouchDeviceEmulatorPointerEventHandler::handlePointerMoveEvent(), LightBarOnChange(), ResizeScrollBounds(), SetConsole(), SetTextEntityByName(), SetupLightBarSelect(), and ToggleConsole().
FunctionObject* Entity::GetFunction (const string & funcName) [inline]
Definition at line 115 of file Entity.h.
References VariantDB::GetFunction().
Referenced by CreateCheckbox(), CreateScrollingTextBoxEntity(), IAPManager::IAPManager(), SelectButtonWithCustomInputComponent::OnAdd(), SliderComponent::OnAdd(), HTTPComponent::OnAdd(), UnpackArchiveComponent::OnAdd(), ProgressBarComponent::OnAdd(), TextRenderComponent::OnAdd(), FilterComponent::OnAdd(), RenderClipComponent::OnAdd(), UnderlineRenderComponent::OnAdd(), RenderScissorComponent::OnAdd(), BlinkComponent::OnAdd(), FilterInputComponent::OnAdd(), TapSequenceDetectComponent::OnAdd(), TemplateComponent::OnAdd(), InterpolateComponent::OnAdd(), RectRenderComponent::OnAdd(), TouchStripComponent::OnAdd(), TyperComponent::OnAdd(), TouchHandlerArcadeComponent::OnAdd(), EmitVirtualKeyComponent::OnAdd(), EmitVirtualKeyComponentAdvanced::OnAdd(), TouchDragComponent::OnAdd(), TrailRenderComponent::OnAdd(), TextBoxRenderComponent::OnAdd(), DPadComponent::OnAdd(), ScrollBarRenderComponent::OnAdd(), LogDisplayComponent::OnAdd(), InputTextRenderComponent::OnAdd(), OverlayRenderComponent::OnAdd(), CustomInputComponent::OnAdd(), SpriteAnimationRenderComponent::OnAdd(), Button2DComponent::OnAdd(), TouchHandlerComponent::OnAdd(), SplashComponent::OnAdd(), ScrollComponent::OnAdd(), TouchDragComponent::OnInput(), OnShowTextMessage(), and SetupLightBarSelect().
string Entity::GetName () [inline]
Definition at line 61 of file Entity.h.
Referenced by LightBarOnChange(), SpriteAnimationUtils::SetAnimationName(), and SpriteAnimationUtils::StartAnimationEntity().
Entity* Entity::GetParent () [inline]
Definition at line 117 of file Entity.h.
Referenced by GetComponentByName(), GetScreenPos2DEntity(), LightBarOnChange(), and ResizeScrollerAfterTextboxChanges().
VariantDB* Entity::GetShared () [inline]
Definition at line 100 of file Entity.h.
Referenced by CallFunctionRecursively(), CallFunctionRecursivelyWithUpdatedVar(), SetEntityWithNativeUIFocus(), and SetupInterpolateComponent().
bool Entity::GetTaggedForDeletion () [inline]
Definition at line 119 of file Entity.h.
Variant* Entity::GetVar (const string & varName) [inline]
Gets a named Variant from this Entity's variant DB.
If the named variant doesn't exist in the database a default variant is constructed and inserted to the database. This new variant can then be set to any value and type.
Definition at line 107 of file Entity.h.
References VariantDB::GetVar().
Referenced by AdjustGUIElementForWindowView(), ConvertEntityClickToScreenCoords(), CopyPropertiesToEntity(), CreateButtonHotspot(), CreateCheckbox(), CreateInputTextEntity(), CreateLogDisplayEntity(), CreateOverlayEntity(), CreateOverlayRectEntity(), CreateScrollingTextBoxEntity(), CreateSlider(), CreateTextBoxEntity(), CreateTextLabelEntity(), EntityIsOnScreen(), EntityRetinaRemapIfNeeded(), EntityScaleiPad(), EntitySetScaleBySize(), FadeInEntity(), FadeScreen(), FadeScreenUp(), FakeClickAnEntity(), FlashOnceEntity(), FlashStartEntity(), GetAlignmentEntity(), GetPos2DEntity(), GetScale2DEntity(), GetSize2DEntity(), TouchDeviceEmulatorPointerEventHandler::handlePointerDownEvent(), TouchDeviceEmulatorPointerEventHandler::handlePointerMoveEvent(), IsCheckboxChecked(), LightBarOnChange(), ManuallySetAlignmentEntity(), MeasureEntityAndChildren(), SliderComponent::OnAdd(), RenderClipComponent::OnAdd(), RenderScissorComponent::OnAdd(), TextRenderComponent::OnAdd(), TapSequenceDetectComponent::OnAdd(), TemplateComponent::OnAdd(), UnpackArchiveComponent::OnAdd(), FilterInputComponent::OnAdd(), UnderlineRenderComponent::OnAdd(), ProgressBarComponent::OnAdd(), RectRenderComponent::OnAdd(), TouchStripComponent::OnAdd(), TouchHandlerArcadeComponent::OnAdd(), TouchDragComponent::OnAdd(), TrailRenderComponent::OnAdd(), TextBoxRenderComponent::OnAdd(), DPadComponent::OnAdd(), ScrollBarRenderComponent::OnAdd(), LogDisplayComponent::OnAdd(), InputTextRenderComponent::OnAdd(), OverlayRenderComponent::OnAdd(), SpriteAnimationRenderComponent::OnAdd(), Button2DComponent::OnAdd(), TouchHandlerComponent::OnAdd(), SplashComponent::OnAdd(), ScrollComponent::OnAdd(), ArcadeInputComponent::OnAdd(), OneTimeBobEntity(), InterpolateComponent::OnVarNameChanged(), ResizeScrollBounds(), ScaleEntity(), SendFakeButtonPushToEntity(), SetAlignmentEntity(), SetAlphaEntity(), SetCheckBoxChecked(), SetConsole(), SetPos2DEntity(), SetScale2DEntity(), SetSize2DEntity(), SetTouchPaddingEntity(), SetupLightBarSelect(), SetupTextEntity(), SetVisibleEntity(), ProtonTester::showResultOnScreen(), SlideScreen(), SlideScreenVertical(), ZoomFromPositionEntity(), ZoomToPositionFromThisOffsetEntity(), ZoomToPositionOffsetEntity(), and ZoomToPositionOffsetEntityMulti().
Variant* Entity::GetVarWithDefault (const string & varName, const Variant & var) [inline]
Gets a named Variant from this Entity's variant DB.
If the named variant doesn't exist in the database a new variant is constructed from the supplied default value and inserted to the database.
Definition at line 114 of file Entity.h.
References VariantDB::GetVarWithDefault().
Referenced by CallFunctionRecursivelyWithUpdatedVar(), SliderComponent::OnAdd(), BlinkComponent::OnAdd(), ProgressBarComponent::OnAdd(), TextRenderComponent::OnAdd(), RenderClipComponent::OnAdd(), RenderScissorComponent::OnAdd(), UnderlineRenderComponent::OnAdd(), TapSequenceDetectComponent::OnAdd(), RectRenderComponent::OnAdd(), TouchStripComponent::OnAdd(), TouchHandlerArcadeComponent::OnAdd(), TouchDragComponent::OnAdd(), TrailRenderComponent::OnAdd(), TextBoxRenderComponent::OnAdd(), DPadComponent::OnAdd(), ScrollBarRenderComponent::OnAdd(), LogDisplayComponent::OnAdd(), InputTextRenderComponent::OnAdd(), OverlayRenderComponent::OnAdd(), SpriteAnimationRenderComponent::OnAdd(), Button2DComponent::OnAdd(), and TouchHandlerComponent::OnAdd().
void Entity::MoveComponentToBottomByAddress (EntityComponent * pComp)
Definition at line 588 of file Entity.cpp.
References LogError(), and RemoveComponentByAddress().
void Entity::MoveComponentToTopByAddress (EntityComponent * pComp)
Definition at line 573 of file Entity.cpp.
References LogError(), and RemoveComponentByAddress().
void Entity::MoveEntityToBottomByAddress (Entity * pEnt)
Definition at line 504 of file Entity.cpp.
References LogError(), and RemoveEntityByAddress().
Referenced by SetupLightBarSelect().
void Entity::MoveEntityToTopByAddress (Entity * pEnt)
Definition at line 515 of file Entity.cpp.
References LogError(), and RemoveEntityByAddress().
void Entity::OnFilterAdd () [inline]
Definition at line 137 of file Entity.h.
Referenced by FilterComponent::OnAdd(), RenderScissorComponent::OnAdd(), RenderClipComponent::OnAdd(), and FilterInputComponent::OnAdd().
void Entity::OnFilterRemove () [inline]
Definition at line 138 of file Entity.h.
Referenced by FilterComponent::OnRemove(), RenderScissorComponent::OnRemove(), RenderClipComponent::OnRemove(), and FilterInputComponent::OnRemove().
void Entity::PrintTreeAsText (int indent = 0)
Definition at line 119 of file Entity.cpp.
References LogMsg().
void Entity::RemoveAllComponents ()
Definition at line 66 of file Entity.cpp.
Referenced by ~Entity().
void Entity::RemoveAllEntities ()
Definition at line 48 of file Entity.cpp.
Referenced by BaseApp::~BaseApp(), and ~Entity().
bool Entity::RemoveComponentByAddress (EntityComponent * pCompToDelete, bool bDeleteAlso = true)
Definition at line 526 of file Entity.cpp.
Referenced by MoveComponentToBottomByAddress(), MoveComponentToTopByAddress(), InterpolateComponent::OnUpdate(), TyperComponent::OnUpdate(), and TypeTextLabelEntity().
bool Entity::RemoveComponentByName (const string & name)
Definition at line 554 of file Entity.cpp.
Referenced by BobEntityStop(), FadeEntity(), FlashOnceEntity(), FlashStopEntity(), RemoveFocusIfNeeded(), RemoveInputFocusIfNeeded(), and ScaleEntity().
bool Entity::RemoveEntitiesByNameThatStartWith (const string & name, bool bRecursive = false)
Definition at line 411 of file Entity.cpp.
References StringFromStartMatches().
bool Entity::RemoveEntityByAddress (Entity * pEntToDelete, bool DeleteAlso = true)
Definition at line 482 of file Entity.cpp.
Referenced by MoveEntityToBottomByAddress(), and MoveEntityToTopByAddress().
bool Entity::RemoveEntityByName (const string & name, bool bRecursive = false)
Definition at line 377 of file Entity.cpp.
Referenced by TouchDeviceEmulatorPointerEventHandler::handlePointerUpEvent().
bool Entity::RemoveEntityByNameSafe (const string & name, bool bRecursive)
Definition at line 443 of file Entity.cpp.
void Entity::SetName (string name)
Definition at line 85 of file Entity.cpp.
Referenced by CreateButtonHotspot(), FadeScreen(), BaseApp::Init(), and SetupLightBarSelect().
void Entity::SetParent (Entity * pEntity) [inline]
Definition at line 118 of file Entity.h.
Referenced by AddEntity().
void Entity::SetTaggedForDeletion ()
Definition at line 473 of file Entity.cpp.
References MessageManager::CallEntityFunction(), and GetMessageManager().
Referenced by KillEntity().
Member Data Documentation
boost::signal<void (Entity*) Entity::sig_onRemoved)
Definition at line 132 of file Entity.h.
Referenced by Message::SetComponentToAdd(), Message::SetTargetEntity(), and ~Entity().
The documentation for this class was generated from the following files:
Entity.h
Entity.cpp