Proton: AudioManagerFMOD Class Reference
AudioManagerFMOD Class Reference
#include <AudioManagerFMOD.h>
Public Member Functions
AudioManagerFMOD ()
virtual ~AudioManagerFMOD ()
virtual bool Init ()
virtual void Kill ()
virtual AudioHandle Play (string fName, bool bLooping=false, bool bIsMusic=false, bool bAddBasePath=true, bool bForceStreaming=false)
Plays an audio specified by a file name.
virtual AudioHandle Play (string fName, int vol, int pan=0)
virtual void Preload (string fName, bool bLooping=false, bool bIsMusic=false, bool bAddBasePath=true, bool bForceStreaming=false)
SoundObject * GetSoundObjectByFileName (string fName)
virtual void KillCachedSounds (bool bKillMusic, bool bKillLooping, int ignoreSoundsUsedInLastMS, int killSoundsLowerPriorityThanThis, bool bKillSoundsPlaying)
virtual void Update ()
This method must be called periodically, e.g once every frame.
virtual void Stop (AudioHandle soundID)
virtual AudioHandle GetMusicChannel ()
virtual bool IsPlaying (AudioHandle soundID)
virtual void SetMusicEnabled (bool bNew)
Enables or disables the playing of music.
virtual void StopMusic ()
Stops the currently playing music immediately.
virtual int GetMemoryUsed ()
bool DeleteSoundObjectByFileName (string fName)
virtual void SetFrequency (AudioHandle soundID, int freq)
virtual void SetPan (AudioHandle soundID, float pan)
virtual void SetVol (AudioHandle soundID, float vol)
virtual void SetPriority (AudioHandle soundID, int priority)
virtual uint32 GetPos (AudioHandle soundID)
virtual void SetPos (AudioHandle soundID, uint32 posMS)
virtual void SetMusicVol (float vol)
virtual void Suspend ()
virtual void Resume ()
FMOD::System * GetSystem ()
Detailed Description
Definition at line 46 of file AudioManagerFMOD.h.
Constructor & Destructor Documentation
AudioManagerFMOD::AudioManagerFMOD ()
Definition at line 17 of file AudioManagerFMOD.cpp.
AudioManagerFMOD::~AudioManagerFMOD () [virtual]
Definition at line 23 of file AudioManagerFMOD.cpp.
References Kill().
Member Function Documentation
bool AudioManagerFMOD::DeleteSoundObjectByFileName (string fName)
Definition at line 167 of file AudioManagerFMOD.cpp.
Referenced by StopMusic().
int AudioManagerFMOD::GetMemoryUsed () [virtual]
Reimplemented from AudioManager.
Definition at line 440 of file AudioManagerFMOD.cpp.
AudioHandle AudioManagerFMOD::GetMusicChannel () [virtual]
Definition at line 394 of file AudioManagerFMOD.cpp.
Referenced by SetMusicEnabled(), and StopMusic().
uint32 AudioManagerFMOD::GetPos (AudioHandle soundID) [virtual]
Reimplemented from AudioManager.
Definition at line 505 of file AudioManagerFMOD.cpp.
SoundObject * AudioManagerFMOD::GetSoundObjectByFileName (string fName)
Definition at line 185 of file AudioManagerFMOD.cpp.
Referenced by Play(), and Preload().
FMOD::System* AudioManagerFMOD::GetSystem () [inline]
Definition at line 80 of file AudioManagerFMOD.h.
bool AudioManagerFMOD::Init () [virtual]
Reimplemented from AudioManager.
Definition at line 29 of file AudioManagerFMOD.cpp.
References FMOD_ERROR_CHECK().
bool AudioManagerFMOD::IsPlaying (AudioHandle soundID) [virtual]
Reimplemented from AudioManager.
Definition at line 400 of file AudioManagerFMOD.cpp.
Referenced by KillCachedSounds().
void AudioManagerFMOD::Kill () [virtual]
Reimplemented from AudioManager.
Definition at line 153 of file AudioManagerFMOD.cpp.
References FMOD_ERROR_CHECK(), and KillCachedSounds().
Referenced by ~AudioManagerFMOD().
void AudioManagerFMOD::KillCachedSounds (bool bKillMusic, bool bKillLooping, int ignoreSoundsUsedInLastMS, int killSoundsLowerPriorityThanThis, bool bKillSoundsPlaying) [virtual]
Reimplemented from AudioManager.
Definition at line 106 of file AudioManagerFMOD.cpp.
References IsPlaying(), LogMsg(), and AudioManager::m_lastMusicFileName.
Referenced by Kill().
AudioHandle AudioManagerFMOD::Play (string fName, bool bLooping = false, bool bIsMusic = false, bool bAddBasePath = true, bool bForceStreaming = false) [virtual]
Plays an audio specified by a file name.
Returns the audio handle for the playing sound if the playing started successfully. Returns AUDIO_HANDLE_BLANK if the playing of the audio didn't start successfully. Also returns AUDIO_HANDLE_BLANK if requesting to play a sound file and sound is currently disabled or requesting to play music and music is currently disabled.
Parameters:
fName the file name of the audio to play.
bLooping whether the sound should start again when it ends, i.e. loop.
bIsMusic specifies if this sound is the music track.
bAddBasePath adds the base path to the file name. See GetBaseAppPath().
bForceStreaming streams the audio directly from the file and doesn't load it into memory. This flag might not be supported by all audio backends.
Returns:
The audio handle for the playing sound if the playing started successfully. Returns AUDIO_HANDLE_BLANK if the playing of the audio didn't start.
Reimplemented from AudioManager.
Definition at line 274 of file AudioManagerFMOD.cpp.
References FMOD_ERROR_CHECK(), AudioManager::GetMusicEnabled(), AudioManager::GetSoundEnabled(), GetSoundObjectByFileName(), LogError(), AudioManager::m_bLastMusicLooping, AudioManager::m_lastMusicFileName, AudioManager::m_lastMusicID, AudioManager::m_musicVol, SoundObject::m_pLastChannelToUse, SoundObject::m_pSound, Preload(), SetMusicVol(), and StopMusic().
Referenced by Play(), and SetMusicEnabled().
AudioHandle AudioManagerFMOD::Play (string fName, int vol, int pan = 0) [virtual]
Definition at line 352 of file AudioManagerFMOD.cpp.
References AudioManager::GetSoundEnabled(), LogMsg(), and Play().
void AudioManagerFMOD::Preload (string fName, bool bLooping = false, bool bIsMusic = false, bool bAddBasePath = true, bool bForceStreaming = false) [virtual]
Reimplemented from AudioManager.
Definition at line 201 of file AudioManagerFMOD.cpp.
References FMOD_ERROR_CHECK(), GetBaseAppPath(), GetFileExtension(), AudioManager::GetMusicEnabled(), GetSoundObjectByFileName(), LogMsg(), SoundObject::m_bIsLooping, SoundObject::m_fileName, AudioManager::m_lastMusicFileName, AudioManager::m_midiSoundBankFile, SoundObject::m_pSound, and ToLowerCaseString().
Referenced by Play().
void AudioManagerFMOD::Resume () [virtual]
Reimplemented from AudioManager.
Definition at line 557 of file AudioManagerFMOD.cpp.
void AudioManagerFMOD::SetFrequency (AudioHandle soundID, int freq) [virtual]
Reimplemented from AudioManager.
Definition at line 489 of file AudioManagerFMOD.cpp.
void AudioManagerFMOD::SetMusicEnabled (bool bNew) [virtual]
Enables or disables the playing of music.
When the music system is disabled any currently playing music is stopped. When the music system is later enabled again the music file that was left playing is resumed from the location where it stopped.
Reimplemented from AudioManager.
Definition at line 412 of file AudioManagerFMOD.cpp.
References AudioManager::GetLastMusicLooping(), GetMusicChannel(), AudioManager::m_bMusicEnabled, AudioManager::m_lastMusicFileName, Play(), and Stop().
void AudioManagerFMOD::SetMusicVol (float vol) [virtual]
Reimplemented from AudioManager.
Definition at line 532 of file AudioManagerFMOD.cpp.
References AudioManager::m_musicVol.
Referenced by Play().
void AudioManagerFMOD::SetPan (AudioHandle soundID, float pan) [virtual]
Reimplemented from AudioManager.
Definition at line 498 of file AudioManagerFMOD.cpp.
void AudioManagerFMOD::SetPos (AudioHandle soundID, uint32 posMS) [virtual]
Reimplemented from AudioManager.
Definition at line 514 of file AudioManagerFMOD.cpp.
void AudioManagerFMOD::SetPriority (AudioHandle soundID, int priority) [virtual]
Reimplemented from AudioManager.
Definition at line 544 of file AudioManagerFMOD.cpp.
void AudioManagerFMOD::SetVol (AudioHandle soundID, float vol) [virtual]
Reimplemented from AudioManager.
Definition at line 524 of file AudioManagerFMOD.cpp.
void AudioManagerFMOD::Stop (AudioHandle soundID) [virtual]
Reimplemented from AudioManager.
Definition at line 379 of file AudioManagerFMOD.cpp.
Referenced by SetMusicEnabled(), and StopMusic().
void AudioManagerFMOD::StopMusic () [virtual]
Stops the currently playing music immediately.
Reimplemented from AudioManager.
Definition at line 434 of file AudioManagerFMOD.cpp.
References DeleteSoundObjectByFileName(), GetMusicChannel(), AudioManager::m_lastMusicFileName, and Stop().
Referenced by Play().
void AudioManagerFMOD::Suspend () [virtual]
Reimplemented from AudioManager.
Definition at line 549 of file AudioManagerFMOD.cpp.
void AudioManagerFMOD::Update () [virtual]
This method must be called periodically, e.g once every frame.
Reimplemented from AudioManager.
Definition at line 371 of file AudioManagerFMOD.cpp.
The documentation for this class was generated from the following files:
AudioManagerFMOD.h
AudioManagerFMOD.cpp