Proton: AudioManagerAndroid Class Reference
AudioManagerAndroid Class Reference
#include <AudioManagerAndroid.h>
Public Member Functions
AudioManagerAndroid ()
virtual ~AudioManagerAndroid ()
virtual bool Init ()
virtual void Kill ()
virtual AudioHandle Play (string fName, bool bLooping=false, bool bIsMusic=false, bool bAddBasePath=true, bool bForceStreaming=false)
Plays an audio specified by a file name.
virtual void Preload (string fName, bool bLooping=false, bool bIsMusic=false, bool bAddBasePath=true, bool bForceStreaming=false)
SoundObject * GetSoundObjectByFileName (string fName)
virtual void KillCachedSounds (bool bKillMusic, bool bKillLooping, int ignoreSoundsUsedInLastMS, int killSoundsLowerPriorityThanThis, bool bKillSoundsPlaying)
virtual void Update ()
This method must be called periodically, e.g once every frame.
virtual void Stop (AudioHandle soundID)
virtual AudioHandle GetMusicChannel ()
virtual bool IsPlaying (AudioHandle soundID)
virtual void SetMusicEnabled (bool bNew)
Enables or disables the playing of music.
virtual void StopMusic ()
Stops the currently playing music immediately.
virtual void FadeOutMusic (unsigned int duration=1000)
Fades out the currently playing music during duration milliseconds.
virtual int GetMemoryUsed ()
bool DeleteSoundObjectByFileName (string fName)
virtual void SetFrequency (AudioHandle soundID, int freq)
virtual void SetPan (AudioHandle soundID, float pan)
virtual void SetVol (AudioHandle soundID, float vol)
virtual void SetPriority (AudioHandle soundID, int priority)
virtual uint32 GetPos (AudioHandle soundID)
virtual void SetPos (AudioHandle soundID, uint32 posMS)
virtual void SetMusicVol (float vol)
virtual void Vibrate (int duration=300)
Protected Attributes
float m_globalVol
Detailed Description
Definition at line 55 of file AudioManagerAndroid.h.
Constructor & Destructor Documentation
AudioManagerAndroid::AudioManagerAndroid ()
Definition at line 10 of file AudioManagerAndroid.cpp.
References m_globalVol, and AudioManager::m_lastMusicID.
AudioManagerAndroid::~AudioManagerAndroid () [virtual]
Definition at line 16 of file AudioManagerAndroid.cpp.
References Kill().
Member Function Documentation
bool AudioManagerAndroid::DeleteSoundObjectByFileName (string fName)
Definition at line 92 of file AudioManagerAndroid.cpp.
void AudioManagerAndroid::FadeOutMusic (unsigned int duration = 1000) [virtual]
Fades out the currently playing music during duration milliseconds.
If no music is playing then this method does nothing.
Reimplemented from AudioManager.
Definition at line 405 of file AudioManagerAndroid.cpp.
References GetAndroidMainClassName(), and GetJavaEnv().
int AudioManagerAndroid::GetMemoryUsed () [virtual]
Reimplemented from AudioManager.
Definition at line 416 of file AudioManagerAndroid.cpp.
AudioHandle AudioManagerAndroid::GetMusicChannel () [virtual]
Definition at line 339 of file AudioManagerAndroid.cpp.
References AudioManager::m_lastMusicID.
uint32 AudioManagerAndroid::GetPos (AudioHandle soundID) [virtual]
Reimplemented from AudioManager.
Definition at line 491 of file AudioManagerAndroid.cpp.
References GetAndroidMainClassName(), GetJavaEnv(), LogMsg(), and AudioManager::m_lastMusicID.
SoundObject * AudioManagerAndroid::GetSoundObjectByFileName (string fName)
Definition at line 110 of file AudioManagerAndroid.cpp.
Referenced by Play(), and Preload().
bool AudioManagerAndroid::Init () [virtual]
Reimplemented from AudioManager.
Definition at line 21 of file AudioManagerAndroid.cpp.
bool AudioManagerAndroid::IsPlaying (AudioHandle soundID) [virtual]
Reimplemented from AudioManager.
Definition at line 345 of file AudioManagerAndroid.cpp.
References GetAndroidMainClassName(), GetJavaEnv(), and AudioManager::m_lastMusicID.
Referenced by Play().
void AudioManagerAndroid::Kill () [virtual]
Reimplemented from AudioManager.
Definition at line 73 of file AudioManagerAndroid.cpp.
References KillCachedSounds(), LogMsg(), and StopMusic().
Referenced by ~AudioManagerAndroid().
void AudioManagerAndroid::KillCachedSounds (bool bKillMusic, bool bKillLooping, int ignoreSoundsUsedInLastMS, int killSoundsLowerPriorityThanThis, bool bKillSoundsPlaying) [virtual]
Reimplemented from AudioManager.
Definition at line 27 of file AudioManagerAndroid.cpp.
References LogMsg(), AudioManager::m_lastMusicFileName, and StopMusic().
Referenced by Kill().
AudioHandle AudioManagerAndroid::Play (string fName, bool bLooping = false, bool bIsMusic = false, bool bAddBasePath = true, bool bForceStreaming = false) [virtual]
Plays an audio specified by a file name.
Returns the audio handle for the playing sound if the playing started successfully. Returns AUDIO_HANDLE_BLANK if the playing of the audio didn't start successfully. Also returns AUDIO_HANDLE_BLANK if requesting to play a sound file and sound is currently disabled or requesting to play music and music is currently disabled.
Parameters:
fName the file name of the audio to play.
bLooping whether the sound should start again when it ends, i.e. loop.
bIsMusic specifies if this sound is the music track.
bAddBasePath adds the base path to the file name. See GetBaseAppPath().
bForceStreaming streams the audio directly from the file and doesn't load it into memory. This flag might not be supported by all audio backends.
Returns:
The audio handle for the playing sound if the playing started successfully. Returns AUDIO_HANDLE_BLANK if the playing of the audio didn't start.
Reimplemented from AudioManager.
Definition at line 197 of file AudioManagerAndroid.cpp.
References FileExists(), GetAndroidMainClassName(), GetBaseAppPath(), GetFileExtension(), GetJavaEnv(), GetMessageManager(), AudioManager::GetMusicEnabled(), AudioManager::GetSoundEnabled(), GetSoundObjectByFileName(), IsPlaying(), LogError(), AudioManager::m_bLastMusicLooping, m_globalVol, AudioManager::m_lastMusicFileName, AudioManager::m_lastMusicID, AudioManager::m_musicVol, SoundObject::m_soundID, MESSAGE_TYPE_PLAY_SOUND, ModifyFileExtension(), Preload(), MessageManager::SendGame(), SetMusicVol(), StopMusic(), StringReplace(), and TIMER_SYSTEM.
Referenced by SetMusicEnabled().
void AudioManagerAndroid::Preload (string fName, bool bLooping = false, bool bIsMusic = false, bool bAddBasePath = true, bool bForceStreaming = false) [virtual]
Reimplemented from AudioManager.
Definition at line 126 of file AudioManagerAndroid.cpp.
References FileExists(), GetAndroidMainClassName(), GetBaseAppPath(), GetFileExtension(), GetJavaEnv(), GetSoundObjectByFileName(), LogMsg(), SoundObject::m_bIsLooping, SoundObject::m_fileName, SoundObject::m_soundID, ModifyFileExtension(), and StringReplace().
Referenced by Play().
void AudioManagerAndroid::SetFrequency (AudioHandle soundID, int freq) [virtual]
Reimplemented from AudioManager.
Definition at line 422 of file AudioManagerAndroid.cpp.
References GetAndroidMainClassName(), and GetJavaEnv().
void AudioManagerAndroid::SetMusicEnabled (bool bNew) [virtual]
Enables or disables the playing of music.
When the music system is disabled any currently playing music is stopped. When the music system is later enabled again the music file that was left playing is resumed from the location where it stopped.
Reimplemented from AudioManager.
Definition at line 368 of file AudioManagerAndroid.cpp.
References AudioManager::GetLastMusicLooping(), AudioManager::m_bMusicEnabled, AudioManager::m_lastMusicFileName, Play(), and StopMusic().
void AudioManagerAndroid::SetMusicVol (float vol) [virtual]
Reimplemented from AudioManager.
Definition at line 544 of file AudioManagerAndroid.cpp.
References GetAndroidMainClassName(), GetJavaEnv(), m_globalVol, and AudioManager::m_musicVol.
Referenced by Play(), and SetVol().
void AudioManagerAndroid::SetPan (AudioHandle soundID, float pan) [virtual]
Reimplemented from AudioManager.
Definition at line 450 of file AudioManagerAndroid.cpp.
References GetAndroidMainClassName(), GetJavaEnv(), and m_globalVol.
void AudioManagerAndroid::SetPos (AudioHandle soundID, uint32 posMS) [virtual]
Reimplemented from AudioManager.
Definition at line 471 of file AudioManagerAndroid.cpp.
References GetAndroidMainClassName(), GetJavaEnv(), LogMsg(), and AudioManager::m_lastMusicID.
void AudioManagerAndroid::SetPriority (AudioHandle soundID, int priority) [virtual]
Reimplemented from AudioManager.
Definition at line 562 of file AudioManagerAndroid.cpp.
void AudioManagerAndroid::SetVol (AudioHandle soundID, float vol) [virtual]
Reimplemented from AudioManager.
Definition at line 510 of file AudioManagerAndroid.cpp.
References GetAndroidMainClassName(), GetJavaEnv(), m_globalVol, AudioManager::m_lastMusicID, AudioManager::m_musicVol, and SetMusicVol().
void AudioManagerAndroid::Stop (AudioHandle soundID) [virtual]
Reimplemented from AudioManager.
Definition at line 313 of file AudioManagerAndroid.cpp.
References GetAndroidMainClassName(), GetJavaEnv(), AudioManager::m_lastMusicID, and StopMusic().
void AudioManagerAndroid::StopMusic () [virtual]
Stops the currently playing music immediately.
Reimplemented from AudioManager.
Definition at line 390 of file AudioManagerAndroid.cpp.
References GetAndroidMainClassName(), and GetJavaEnv().
Referenced by Kill(), KillCachedSounds(), Play(), SetMusicEnabled(), and Stop().
void AudioManagerAndroid::Update () [virtual]
This method must be called periodically, e.g once every frame.
Reimplemented from AudioManager.
Definition at line 308 of file AudioManagerAndroid.cpp.
void AudioManagerAndroid::Vibrate (int duration = 300) [virtual]
Reimplemented from AudioManager.
Definition at line 567 of file AudioManagerAndroid.cpp.
References GetAndroidMainClassName(), GetJavaEnv(), and AudioManager::m_bVibrationDisabled.
Member Data Documentation
float AudioManagerAndroid::m_globalVol [protected]
Definition at line 93 of file AudioManagerAndroid.h.
Referenced by AudioManagerAndroid(), Play(), SetMusicVol(), SetPan(), and SetVol().
The documentation for this class was generated from the following files:
AudioManagerAndroid.h
AudioManagerAndroid.cpp