Proton: ScrollBarRenderComponent Class Reference
ScrollBarRenderComponent Class Reference
#include <ScrollBarRenderComponent.h>
Public Member Functions
ScrollBarRenderComponent ()
virtual ~ScrollBarRenderComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
Detailed Description
Definition at line 39 of file ScrollBarRenderComponent.h.
Constructor & Destructor Documentation
ScrollBarRenderComponent::ScrollBarRenderComponent ()
Definition at line 8 of file ScrollBarRenderComponent.cpp.
References EntityComponent::SetName().
ScrollBarRenderComponent::~ScrollBarRenderComponent () [virtual]
Definition at line 15 of file ScrollBarRenderComponent.cpp.
Member Function Documentation
void ScrollBarRenderComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 19 of file ScrollBarRenderComponent.cpp.
References Entity::GetComponentByName(), Variant::GetFloat(), Entity::GetFunction(), EntityComponent::GetParent(), Variant::GetRect(), Variant::GetSigOnChanged, Variant::GetString(), Variant::GetUINT32(), EntityComponent::GetVar(), Entity::GetVar(), Entity::GetVarWithDefault(), Variant::GetVector2(), Variant::Set(), and FunctionObject::sig_function.
void ScrollBarRenderComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 82 of file ScrollBarRenderComponent.cpp.
The documentation for this class was generated from the following files:
ScrollBarRenderComponent.h
ScrollBarRenderComponent.cpp