Proton: MoveButtonState Class Reference
MoveButtonState Class Reference
#include <ArcadeInputComponent.h>
Public Member Functions
MoveButtonState ()
void SetKeyType (eVirtualKeys type)
void ReleaseIfNeeded (boost::signal< void(VariantList *)> *pCustomSignal, bool bSendChange=true)
void OnPress (int releaseTime, boost::signal< void(VariantList *)> *pCustomSignal, bool bSendChange=true)
void Update (boost::signal< void(VariantList *)> *pCustomSignal)
void OnPressToggle (bool bDown, boost::signal< void(VariantList *)> *pCustomSignal, bool bSendChange=true)
Public Attributes
bool m_bIsDown
unsigned int m_releaseTimer
eVirtualKeys m_keyType
Detailed Description
Definition at line 72 of file ArcadeInputComponent.h.
Constructor & Destructor Documentation
MoveButtonState::MoveButtonState () [inline]
Definition at line 76 of file ArcadeInputComponent.h.
References m_bIsDown, and m_releaseTimer.
Member Function Documentation
void MoveButtonState::OnPress (int releaseTime, boost::signal< void(VariantList *)> * pCustomSignal, bool bSendChange = true)
Definition at line 7 of file ArcadeInputComponent.cpp.
References VariantList::Get(), GetBaseApp(), GetTick(), m_bIsDown, m_keyType, m_releaseTimer, BaseApp::m_sig_arcade_input, Variant::Set(), TIMER_SYSTEM, and VIRTUAL_KEY_PRESS.
void MoveButtonState::OnPressToggle (bool bDown, boost::signal< void(VariantList *)> * pCustomSignal, bool bSendChange = true)
Definition at line 34 of file ArcadeInputComponent.cpp.
References VariantList::Get(), GetBaseApp(), GetTick(), m_bIsDown, m_keyType, m_releaseTimer, BaseApp::m_sig_arcade_input, ReleaseIfNeeded(), Variant::Set(), TIMER_SYSTEM, and VIRTUAL_KEY_PRESS.
Referenced by ArcadeInputComponent::ResetDirectionKeys(), and ArcadeInputComponent::SetDirectionKey().
void MoveButtonState::ReleaseIfNeeded (boost::signal< void(VariantList *)> * pCustomSignal, bool bSendChange = true)
Definition at line 76 of file ArcadeInputComponent.cpp.
References VariantList::Get(), GetBaseApp(), m_bIsDown, m_keyType, BaseApp::m_sig_arcade_input, Variant::Set(), and VIRTUAL_KEY_RELEASE.
Referenced by OnPressToggle(), and Update().
void MoveButtonState::SetKeyType (eVirtualKeys type) [inline]
Definition at line 82 of file ArcadeInputComponent.h.
References m_keyType.
Referenced by ArcadeInputComponent::ArcadeInputComponent().
void MoveButtonState::Update (boost::signal< void(VariantList *)> * pCustomSignal)
Definition at line 67 of file ArcadeInputComponent.cpp.
References GetTick(), m_bIsDown, m_releaseTimer, ReleaseIfNeeded(), and TIMER_SYSTEM.
Member Data Documentation
bool MoveButtonState::m_bIsDown
Definition at line 92 of file ArcadeInputComponent.h.
Referenced by ArcadeInputComponent::GetDirectionKeys(), MoveButtonState(), OnPress(), OnPressToggle(), ReleaseIfNeeded(), and Update().
eVirtualKeys MoveButtonState::m_keyType
Definition at line 94 of file ArcadeInputComponent.h.
Referenced by OnPress(), OnPressToggle(), ReleaseIfNeeded(), and SetKeyType().
unsigned int MoveButtonState::m_releaseTimer
Definition at line 93 of file ArcadeInputComponent.h.
Referenced by MoveButtonState(), OnPress(), OnPressToggle(), and Update().
The documentation for this class was generated from the following files:
ArcadeInputComponent.h
ArcadeInputComponent.cpp