Proton: InterpolateComponent Class Reference
InterpolateComponent Class Reference
#include <InterpolateComponent.h>
Public Types
enum eOnFinish { ON_FINISH_DIE = 0, ON_FINISH_BOUNCE, ON_FINISH_REPEAT, ON_FINISH_STOP }
Public Member Functions
InterpolateComponent ()
virtual ~InterpolateComponent ()
virtual void OnAdd (Entity *pEnt)
virtual void OnRemove ()
void OnUpdate (VariantList *pVList)
void OnVarNameChanged (Variant *pDataObject)
void OnDurationChanged (Variant *pDataObject)
Detailed Description
Definition at line 18 of file InterpolateComponent.h.
Member Enumeration Documentation
enum InterpolateComponent::eOnFinish
Enumerator:
ON_FINISH_DIE
ON_FINISH_BOUNCE
ON_FINISH_REPEAT
ON_FINISH_STOP
Definition at line 32 of file InterpolateComponent.h.
Constructor & Destructor Documentation
InterpolateComponent::InterpolateComponent ()
Definition at line 6 of file InterpolateComponent.cpp.
References EntityComponent::SetName().
InterpolateComponent::~InterpolateComponent () [virtual]
Definition at line 15 of file InterpolateComponent.cpp.
Member Function Documentation
void InterpolateComponent::OnAdd (Entity * pEnt) [virtual]
Reimplemented from EntityComponent.
Definition at line 64 of file InterpolateComponent.cpp.
References GetBaseApp(), Entity::GetFunction(), EntityComponent::GetParent(), EntityComponent::GetShared(), Variant::GetSigOnChanged, Variant::GetString(), Variant::GetUINT32(), EntityComponent::GetVar(), VariantDB::GetVar(), EntityComponent::GetVarWithDefault(), INTERPOLATE_LINEAR, ON_FINISH_DIE, OnDurationChanged(), OnUpdate(), OnVarNameChanged(), and FunctionObject::sig_function.
void InterpolateComponent::OnDurationChanged (Variant * pDataObject)
Definition at line 42 of file InterpolateComponent.cpp.
References GetBaseApp(), BaseApp::GetTickTimingSystem(), and LogError().
Referenced by OnAdd().
void InterpolateComponent::OnRemove () [virtual]
Reimplemented from EntityComponent.
Definition at line 88 of file InterpolateComponent.cpp.
void InterpolateComponent::OnUpdate (VariantList * pVList)
Definition at line 111 of file InterpolateComponent.cpp.
References GetBaseApp(), EntityComponent::GetParent(), BaseApp::GetTickTimingSystem(), Variant::GetType(), Variant::Interpolate(), LogError(), ON_FINISH_BOUNCE, ON_FINISH_DIE, ON_FINISH_REPEAT, ON_FINISH_STOP, Entity::RemoveComponentByAddress(), Variant::Set(), and Variant::TYPE_UNUSED.
Referenced by OnAdd().
void InterpolateComponent::OnVarNameChanged (Variant * pDataObject)
Definition at line 19 of file InterpolateComponent.cpp.
References Entity::GetComponentByName(), EntityComponent::GetFunction(), EntityComponent::GetName(), EntityComponent::GetParent(), Variant::GetString(), EntityComponent::GetVar(), Entity::GetVar(), LogError(), and FunctionObject::sig_function.
Referenced by OnAdd().
The documentation for this class was generated from the following files:
InterpolateComponent.h
InterpolateComponent.cpp