Proton: CWeightRand Class Reference
CWeightRand Class Reference
#include <WeightRand.h>
Public Member Functions
CWeightRand ()
void AddChoice (int i_index, int i_odds)
int GetRandom ()
int GetRandom (CRandom &rng)
void Clear ()
int GetOdds (int i_choice)
void ModChoice (int index, int mod)
bool Save (FILE *fp)
bool Load (FILE *fp)
unsigned int GetCount ()
Detailed Description
Definition at line 32 of file WeightRand.h.
Constructor & Destructor Documentation
CWeightRand::CWeightRand ()
Definition at line 5 of file WeightRand.cpp.
Member Function Documentation
void CWeightRand::AddChoice (int i_index, int i_odds)
Definition at line 64 of file WeightRand.cpp.
Referenced by Load(), and ModChoice().
void CWeightRand::Clear ()
Definition at line 16 of file WeightRand.cpp.
Referenced by Load().
unsigned int CWeightRand::GetCount () [inline]
Definition at line 45 of file WeightRand.h.
int CWeightRand::GetOdds (int i_choice)
Definition at line 10 of file WeightRand.cpp.
Referenced by ModChoice().
int CWeightRand::GetRandom ()
Definition at line 129 of file WeightRand.cpp.
int CWeightRand::GetRandom (CRandom & rng)
Definition at line 119 of file WeightRand.cpp.
References CRandom::rand().
bool CWeightRand::Load (FILE * fp)
Definition at line 39 of file WeightRand.cpp.
References AddChoice(), and Clear().
void CWeightRand::ModChoice (int index, int mod)
Definition at line 59 of file WeightRand.cpp.
References AddChoice(), and GetOdds().
bool CWeightRand::Save (FILE * fp)
Definition at line 24 of file WeightRand.cpp.
The documentation for this class was generated from the following files:
WeightRand.h
WeightRand.cpp