Proton: BarDataDrawer Class Reference
BarDataDrawer Class Reference
#include <pplot.h>
Public Member Functions
BarDataDrawer (bool inDrawOnlyLastPoint=false)
virtual bool DrawData (const PlotDataBase &inXData, const PlotDataBase &inYData, const PlotDataSelection &inPlotDataSelection, const AxisSetup &inXAxisSetup, const PRect &inRect, Painter &inPainter) const
virtual DataDrawerBase * Clone () const
Protected Member Functions
virtual bool DrawOnlyLastPoint (const PlotDataBase &inXData, const PlotDataBase &inYData, const PlotDataSelection &inPlotDataSelection, const AxisSetup &inXAxisSetup, const PRect &inRect, Painter &inPainter) const
Protected Attributes
bool mDrawOnlyLastPoint
Detailed Description
Definition at line 253 of file pplot.h.
Constructor & Destructor Documentation
BarDataDrawer::BarDataDrawer (bool inDrawOnlyLastPoint = false) [inline]
Definition at line 255 of file pplot.h.
Referenced by Clone().
Member Function Documentation
DataDrawerBase * BarDataDrawer::Clone () const [virtual]
Implements DataDrawerBase.
Definition at line 1583 of file PPlot.cpp.
References BarDataDrawer().
bool BarDataDrawer::DrawData (const PlotDataBase & inXData, const PlotDataBase & inYData, const PlotDataSelection & inPlotDataSelection, const AxisSetup & inXAxisSetup, const PRect & inRect, Painter & inPainter) const [virtual]
Implements DataDrawerBase.
Definition at line 1519 of file PPlot.cpp.
References DrawOnlyLastPoint(), Painter::FillRect(), PlotDataBase::GetSize(), PlotDataBase::GetValue(), mDrawOnlyLastPoint, DataDrawerBase::mPlotCount, PRect::mW, DataDrawerBase::mXTrafo, DataDrawerBase::mYTrafo, and Trafo::Transform().
bool BarDataDrawer::DrawOnlyLastPoint (const PlotDataBase & inXData, const PlotDataBase & inYData, const PlotDataSelection & inPlotDataSelection, const AxisSetup & inXAxisSetup, const PRect & inRect, Painter & inPainter) const [protected, virtual]
Definition at line 1554 of file PPlot.cpp.
References Painter::FillRect(), PlotDataBase::GetSize(), PlotDataBase::GetValue(), DataDrawerBase::mPlotCount, DataDrawerBase::mPlotIndex, PRect::mW, PRect::mX, DataDrawerBase::mXTrafo, DataDrawerBase::mYTrafo, and Trafo::Transform().
Referenced by DrawData().
Member Data Documentation
bool BarDataDrawer::mDrawOnlyLastPoint [protected]
Definition at line 260 of file pplot.h.
Referenced by DrawData().
The documentation for this class was generated from the following files:
pplot.h
PPlot.cpp