Proton: EntityUtils.cpp File Reference
EntityUtils.cpp File Reference
Functions
Entity * CreateOverlayEntity (Entity *pParentEnt, string name, string fileName, float x, float y)
Creates a new Entity and adds an OverlayRenderComponent to it.
Entity * CreateOverlayButtonEntity (Entity *pParentEnt, string name, string fileName, float x, float y)
Like CreateOverlayEntity() but additionally adds a TouchHandlerComponent and a Button2DComponent to the created Entity too.
EntityComponent * SetupInterpolateComponent (Entity *pEnt, const string &componentName, const string &varName, const Variant &targetValue, int durationMS, int delayBeforeStartMS, eInterpolateType interpolationType=INTERPOLATE_SMOOTHSTEP, InterpolateComponent::eOnFinish onFinish=InterpolateComponent::ON_FINISH_DIE, eTimingSystem timing=GetTiming())
Sets up an InterpolateComponent in an Entity.
EntityComponent * SlideScreen (Entity *pEnt, bool bIn, int speedMS, int delayToStartMS)
EntityComponent * SlideScreenVertical (Entity *pEnt, bool bIn, int speedMS, int delayToStartMS)
bool IsEntityBobbing (Entity *pEnt)
void BobEntity (Entity *pEnt, float bobAmount, int delayBeforeBob, int durationOfEachBobMS)
void BobEntityStop (Entity *pEnt)
void OneTimeBobEntity (Entity *pEnt, float bobAmount, int delayBeforeBob, int durationMS)
void AnimateStopEntity (Entity *pEnt, int delayToStartMS)
void AnimateStopEntityAndSetFrame (Entity *pEnt, int delayToStartMS, int frameX, int frameY)
EntityComponent * SetupAnimEntity (Entity *pEnt, uint32 frameCountX, uint32 frameCountY, int curFrameX, int curFrameY)
void AnimateEntitySetMirrorMode (Entity *pEnt, bool flipX, bool flipY)
void AnimateEntity (Entity *pEnt, int startFrame, int endFrame, int animSpeedMS, InterpolateComponent::eOnFinish type, int delayToStartMS)
EntityComponent * SetOverlayImageEntity (Entity *pEntWithOverlayComponent, string imageFileName, uint32 delayBeforeActionMS, bool bAddBasePath)
Sets the filename of an OverlayRenderComponent found from pEntWithOverlayComponent.
std::string GetOverlayImageEntity (Entity *pEntWithOverlayComponent)
Gets the filename of an OverlayRenderComponent found from pEntWithOverlayComponent.
void FadeInEntity (Entity *pEnt, bool bRecursive, int timeMS, int delayBeforeFadingMS, float fadeTarget, eTimingSystem timing)
EntityComponent * MorphToVec2Entity (Entity *pEnt, string targetVar, CL_Vec2f vTargetSize, unsigned int speedMS, eInterpolateType interpolateType, int delayBeforeActionMS)
EntityComponent * MorphToVec2EntityMulti (Entity *pEnt, string targetVar, CL_Vec2f vTargetSize, unsigned int speedMS, eInterpolateType interpolateType, int delayBeforeActionMS)
EntityComponent * MorphToFloatEntity (Entity *pEnt, string targetVar, float target, unsigned int speedMS, eInterpolateType interpolateType, int delayBeforeActionMS)
EntityComponent * MorphToSizeEntity (Entity *pEnt, CL_Vec2f vTargetSize, unsigned int speedMS, eInterpolateType interpolateType, int delayBeforeActionMS)
EntityComponent * MorphToFloatComponent (EntityComponent *pTargetComp, string targetVar, float target, unsigned int speedMS, eInterpolateType interpolateType, int delayBeforeActionMS)
EntityComponent * MorphToVec2Component (EntityComponent *pTargetComp, string targetVar, CL_Vec2f vTargetSize, unsigned int speedMS, eInterpolateType interpolateType, int delayBeforeActionMS)
EntityComponent * ZoomToPositionFromThisOffsetEntity (Entity *pEnt, CL_Vec2f offset, unsigned int speedMS, eInterpolateType interpolateType, int delayBeforeActionMS)
Adds a position animation to an Entity.
EntityComponent * ZoomFromPositionEntity (Entity *pEnt, CL_Vec2f vPos, unsigned int speedMS, eInterpolateType interpolateType, int delayBeforeActionMS)
Adds a position animation to an Entity.
EntityComponent * ZoomToPositionEntity (Entity *pEnt, CL_Vec2f vPos, unsigned int speedMS, eInterpolateType interpolateType, int delayBeforeActionMS)
Adds a position animation to an Entity.
EntityComponent * ZoomToPositionOffsetEntity (Entity *pEnt, CL_Vec2f offset, unsigned int speedMS, eInterpolateType interpolateType, int delayBeforeActionMS)
Adds a position animation to an Entity.
EntityComponent * ZoomToPositionOffsetEntityMulti (Entity *pEnt, CL_Vec2f offset, unsigned int speedMS, eInterpolateType interpolateType, int delayBeforeActionMS)
Like ZoomToPositionOffsetEntity() but doesn't remove any animations currently running.
EntityComponent * ZoomToPositionEntityMulti (Entity *pEnt, CL_Vec2f vPos, unsigned int speedMS, eInterpolateType interpolateType, int delayBeforeActionMS)
Like ZoomToPositionEntity() but doesn't remove any animations currently running.
EntityComponent * ZoomToScaleEntity (Entity *pEnt, CL_Vec2f vScale, unsigned int speedMS, eInterpolateType interpolateType, int delayBeforeActionMS)
Adds a scale animation to an Entity.
void MorphToColorEntity (Entity *pEnt, bool bRecursive, int timeMS, unsigned int color, int delayBeforeActionMS, bool bAllowMultipleAtOnce)
EntityComponent * PulsateColorEntity (Entity *pEnt, bool bRecursive, unsigned int color, unsigned int pulsateSpeedMS)
bool IsDisabledEntity (Entity *pEnt)
Entity * DisableEntityButtonByName (const string &entityName, Entity *pRootEntity)
void DisableAllButtonsEntity (Entity *pEnt, bool bRecursive)
Entity * EnableEntityButtonByName (const string &entityName, Entity *pRootEntity)
void EnableAllButtonsEntity (Entity *pEnt, bool bRecursive, int delayBeforeActionMS, eTimingSystem timing)
void FlashStopEntity (Entity *pEnt)
void FlashStartEntity (Entity *pEnt, int flashSpeedMS)
void FlashOnceEntity (Entity *pEnt, int flashSpeedMS)
void FadeEntity (Entity *pEnt, bool bRecursive, float alpha, int timeMS, int delayBeforeFadingMS, bool bAllowMultipleFadesActiveAtOnce)
void FadeOutEntity (Entity *pEnt, bool bRecursive, int timeMS, int delayBeforeFadingMS, eTimingSystem timing)
void FadeOutAndKillEntity (Entity *pEnt, bool bRecursive, int timeMS, int delayBeforeFadingMS, eTimingSystem timing)
void FadeOutAndKillChildrenEntities (Entity *pEnt, int timeMS, int delayBeforeFadingMS, eTimingSystem timing)
void ScaleEntity (Entity *pEnt, float scaleStart, float scaleEnd, int timeMS, int delayBeforeStartingMS, eInterpolateType interpolationType)
void ScaleEntity (Entity *pEnt, CL_Vec2f vScaleStart, CL_Vec2f vScaleEnd, int timeMS, int delayBeforeStartingMS, eInterpolateType interpolationType)
void KillEntity (Entity *pEnt, int timeMS, eTimingSystem timingSystem)
Entity * CreateTextLabelEntity (Entity *pParentEnt, string name, float x, float y, string text)
Entity * CreateInputTextEntity (Entity *pParentEnt, string name, float x, float y, string text, float sizeX, float sizeY)
Entity * CreateOverlayRectEntity (Entity *pParent, CL_Rectf posAndBoundsRect, uint32 color, RectRenderComponent::eVisualStyle style)
Entity * CreateOverlayRectEntity (Entity *pParent, CL_Vec2f vPos, CL_Vec2f vBounds, uint32 color, RectRenderComponent::eVisualStyle style)
Entity * CreateButtonHotspot (Entity *pParentEnt, string name, CL_Vec2f vPos, CL_Vec2f vBounds, Button2DComponent::eButtonStyle buttonStyle)
void SetButtonRepeatDelayMS (Entity *pEnt, uint32 delayMS)
void SetButtonClickSound (Entity *pEnt, string fileName)
Entity * CreateTextButtonEntity (Entity *pParentEnt, string name, float x, float y, string text, bool bUnderline)
void RemoveFocusIfNeeded (Entity *pEnt)
void RemoveInputFocusIfNeeded (Entity *pEnt)
bool EntityHasInputFocus (Entity *pEnt)
void AddFocusIfNeeded (Entity *pEnt, bool bAlsoLinkMoveMessages, int delayInputMS, int updateAndRenderDelay)
Ensures that the given Entity has needed focus EntityComponents .
void AddInputMovementFocusIfNeeded (Entity *pEnt)
void EnableRawMessageFocusInput (Entity *pEnt)
Commands a FocusInputComponent in pEnt to also recognize the raw keyboard input messages.
Entity * FadeScreen (Entity *pParent, float defaultStartAlpha, float targetAlpha, int fadeDurationMS, bool bDeleteWhenDone)
void FadeScreenUp (Entity *pParent, float targetAlpha, int fadeDurationMS, bool bDeleteWhenDone)
CL_Rectf MeasureEntityAndChildren (Entity *pEnt, CL_Vec2f *pVStartingPos, bool bFirst)
void SetupTextEntity (Entity *pEnt, eFont fontID, float scale)
void SetTextShadowColor (Entity *pEnt, uint32 color)
void GetFontAndScaleToFitThisStringInWidthPixels (eFont *pFontIDOut, float *pFontScaleOut, string text, float desiredWidth)
void GetFontAndScaleToFitThisLinesPerScreenY (eFont *pFontIDOut, float *pFontScaleOut, float desiredLinesPerScreenY)
void GetFontAndScaleToFitThisPixelHeight (eFont *pFontIDOut, float *pFontScaleOut, float heightPixels)
float EnforceMinimumFontLineToScreenRatio (eFont fontID, float fontScale, float minLineToScreenRatio)
void SetAlignmentEntity (Entity *pEnt, eAlignment align)
eAlignment GetAlignmentEntity (Entity *pEnt)
Entity * CreateTextBoxEntity (Entity *pParent, string entName, CL_Vec2f vPos, CL_Vec2f vTextAreaSize, string msg, float scale, eAlignment textAlignment)
Creates a new Entity and adds a TextBoxRenderComponent to it.
EntityComponent * SetTextEntity (Entity *pEntWithTextComponent, const string &text)
void ResizeScrollerAfterTextboxChanges (VariantList *vList)
Entity * CreateScrollingTextBoxEntity (Entity *pParent, string entName, CL_Vec2f vPos, CL_Vec2f vTextAreaSize, string msg, float scale, eAlignment textAlignment)
Like above, but puts the TextBoxRender component under a ScrollComponent.
void RemovePaddingEntity (Entity *pEnt)
void SetTouchPaddingEntity (Entity *pEnt, CL_Rectf padding)
EntityComponent * SetButtonVisualStyleEntity (Entity *pEnt, Button2DComponent::eVisualStyle style)
EntityComponent * SetButtonStyleEntity (Entity *pEnt, Button2DComponent::eButtonStyle style)
EntityComponent * TypeTextLabelEntity (Entity *pEnt, int delayBeforeActionMS, uint32 textTypeSpeedMS, TyperComponent::eMode mode, string textToAddByTyping)
void SetAlphaEntity (Entity *pEnt, float alpha)
void PreloadKeyboard (OSMessage::eParmKeyboardType keyboardType)
void SendFakeInputMessageToEntity (Entity *pEnt, eMessageType msg, CL_Vec2f vClickPos, int delayBeforeStartingMS)
void LightBarOnChange (VariantList *pVList)
void SendFakeButtonPushToEntity (Entity *pEntity, int timeMS)
void SetupLightBarSelect (Entity *pBG, string entNamePrefix, int defaultOption, uint32 color)
void ResizeScrollBounds (VariantList *pVList)
void DisableHorizontalScrolling (Entity *pEnt)
void SetScrollProgressEntity (Entity *pEnt, const CL_Vec2f &progress)
Sets the progress (position) of a ScrollComponent.
CL_Vec2f GetScrollProgressEntity (Entity *pEnt)
void SetDisabledOnAllComponentsRecursively (Entity *pEnt, bool bDisabled)
EntityComponent * DisableComponentByName (Entity *pEnt, const string &compName, int delayBeforeActionMS)
EntityComponent * EnableComponentByName (Entity *pEnt, const string &compName, int delayBeforeActionMS)
CL_Vec2f ConvertEntityClickToScreenCoords (CL_Vec2f pt, Entity *pEnt)
void GetUsedTextures (vector< string > &usedTextures, Entity *pEnt)
void DestroyUnusedTextures ()
bool EntityRetinaRemapIfNeeded (Entity *pEnt, bool bAdjustPosition, bool bAdjustScale, bool bApplyToIpadAlso, bool bPerserveAspectRatio)
void EntityAdjustScaleSoPhysicalSizeMatches (Entity *pEnt, int ppiToMatch, float powerMult)
void EntitySetScaleBySize (Entity *pEnt, CL_Vec2f vDestSize, bool bPreserveAspectRatio, bool bPreserveOtherAxis)
Sets the scale of pEnt such that the resulting size of it will be vDestSize.
void EntityScaleiPad (Entity *pEnt, bool bPerserveAspectRatio)
EntityComponent * AddHotKeyToButton (Entity *pEnt, uint32 keycode)
EntityComponent * MakeButtonEmitVirtualGameKey (Entity *pEnt, uint32 keycode)
EntityComponent * CreateSlider (Entity *pBG, float x, float y, float sizeX, string buttonFileName, string left, string middle, string right)
void AdjustGUIElementForWindowView (Entity *pEnt, CL_Rectf r, float rotation)
void ManuallySetAlignmentEntity (Entity *pEnt, eAlignment alignment)
bool FakeClickAnEntityByName (Entity *pEntitySearchRoot, const string name)
void FakeClickAnEntity (Entity *pEnt, int delayBeforeStartingMS)
bool IsCheckboxChecked (Entity *pEnt)
void SetCheckBoxChecked (Entity *pEnt, bool bChecked, bool bShowAnim)
void OnCheckboxToggle (VariantList *pVList)
Entity * CreateCheckbox (Entity *pBG, string name, string text, float x, float y, bool bChecked, eFont fontID, float fontScale)
Entity * SetTextEntityByName (const string &entityName, string text, Entity *pRootEntity)
bool EntityIsOnScreen (Entity *pEnt)
CL_Vec2f GetSize2DEntity (Entity *pEnt)
void SetSize2DEntity (Entity *pEnt, const CL_Vec2f &vSize)
CL_Vec2f GetPos2DEntity (Entity *pEnt)
void SetPos2DEntity (Entity *pEnt, const CL_Vec2f &vPos)
CL_Vec2f GetScale2DEntity (Entity *pEnt)
void SetScale2DEntity (Entity *pEnt, const CL_Vec2f &vScale)
void SetProgressBarPercent (Entity *pEnt, float progressPercent)
void SetVisibleEntity (Entity *pEnt, bool bVisible)
void CopyPropertiesToEntity (Entity *pToEnt, Entity *pFromEnt, const string varName1, const string varName2, const string varName3)
void MoveEntityToTop (VariantList *pVList)
void OnShowTextMessage (VariantList *pVList)
void ShowTextMessage (string msg, int timeMS, int delayBeforeStartingMS)
void SetupEntityToEatInput (Entity *pEnt)
void ActivateTextInputEntity (Entity *pEnt)
CL_Vec2f GetScreenPos2DEntity (Entity *pEnt, CL_Vec2f vRecursivePosToAdd)
void SetEntityOverlayToUnloadImageOnKill (Entity *pImage)
Function Documentation
void ActivateTextInputEntity (Entity * pEnt)
Definition at line 2266 of file EntityUtils.cpp.
References Entity::GetComponentByName(), EntityComponent::GetFunction(), and FunctionObject::sig_function.
void AddFocusIfNeeded (Entity * pEnt, bool bAlsoLinkMoveMessages = false, int delayInputMS = 0, int updateAndRenderDelay = 0)
Ensures that the given Entity has needed focus EntityComponents .
Three components will be added to pEnt, one instance of each of these classes:
FocusUpdateComponent
FocusRenderComponent
FocusInputComponent
If any focus component is already on the Entity they are not added again. Hence it's safe to call this method multiple times for an Entity.
Parameters:
pEnt this is the Entity where the components are added. Mustn't be NULL.
bAlsoLinkMoveMessages if true, calls the LinkMoveMessages() method for the added FocusInputComponent.
delayInputMS specifies a delay in milliseconds after which the FocusInputComponent is added to the Entity.
updateAndRenderDelay specifies a delay in milliseconds after which the FocusUpdateComponent and FocusRenderComponent are added to the Entity.
Definition at line 921 of file EntityUtils.cpp.
References Entity::AddComponent(), MessageManager::AddComponent(), MessageManager::CallComponentFunction(), Entity::GetComponentByName(), EntityComponent::GetFunction(), GetMessageManager(), and FunctionObject::sig_function.
Referenced by MoveEntityToTop(), OnShowTextMessage(), and SetConsole().
EntityComponent* AddHotKeyToButton (Entity * pEnt, uint32 keycode)
Definition at line 1936 of file EntityUtils.cpp.
References Entity::AddComponent(), EntityComponent::GetVar(), and Variant::Set().
void AddInputMovementFocusIfNeeded (Entity * pEnt)
Definition at line 978 of file EntityUtils.cpp.
References Entity::AddComponent(), Entity::GetComponentByName(), EntityComponent::GetFunction(), EntityComponent::GetVar(), FocusInputComponent::MODE_START_NONE, Variant::Set(), and FunctionObject::sig_function.
Referenced by DPadComponent::OnAdd().
void AdjustGUIElementForWindowView (Entity * pEnt, CL_Rectf r, float rotation)
Definition at line 2009 of file EntityUtils.cpp.
References Entity::GetVar(), Variant::GetVector2(), RotateGUIPoint(), and Variant::Set().
void AnimateEntity (Entity * pEnt, int startFrame, int endFrame, int animSpeedMS, InterpolateComponent::eOnFinish type, int delayToStartMS)
Definition at line 272 of file EntityUtils.cpp.
References Entity::AddComponent(), Entity::GetComponentByName(), GetMessageManager(), Variant::GetUINT32(), EntityComponent::GetVar(), INTERPOLATE_LINEAR, InterpolateComponent::ON_FINISH_DIE, Variant::Set(), MessageManager::SetComponentVariable(), and EntityComponent::SetName().
void AnimateEntitySetMirrorMode (Entity * pEnt, bool flipX, bool flipY)
Definition at line 261 of file EntityUtils.cpp.
References Entity::GetComponentByName(), EntityComponent::GetVar(), and Variant::Set().
void AnimateStopEntity (Entity * pEnt, int delayToStartMS)
Definition at line 188 of file EntityUtils.cpp.
References Entity::GetComponentByName(), GetMessageManager(), EntityComponent::GetVar(), Variant::Set(), and MessageManager::SetComponentVariable().
void AnimateStopEntityAndSetFrame (Entity * pEnt, int delayToStartMS, int frameX, int frameY)
Definition at line 203 of file EntityUtils.cpp.
References Entity::GetComponentByName(), GetMessageManager(), EntityComponent::GetVar(), Variant::Set(), and MessageManager::SetComponentVariable().
Referenced by CreateCheckbox(), and SetCheckBoxChecked().
void BobEntity (Entity * pEnt, float bobAmount, int delayBeforeBob, int durationOfEachBobMS)
Definition at line 152 of file EntityUtils.cpp.
References GetPos2DEntity(), EntityComponent::GetVar(), INTERPOLATE_SMOOTHSTEP, InterpolateComponent::ON_FINISH_BOUNCE, Variant::Set(), and SetupInterpolateComponent().
void BobEntityStop (Entity * pEnt)
Definition at line 166 of file EntityUtils.cpp.
References Entity::RemoveComponentByName().
CL_Vec2f ConvertEntityClickToScreenCoords (CL_Vec2f pt, Entity * pEnt)
Definition at line 1706 of file EntityUtils.cpp.
References ALIGNMENT_UPPER_LEFT, GetAlignmentOffset(), Variant::GetUINT32(), Entity::GetVar(), and Variant::GetVector2().
Referenced by GetScreenPos2DEntity().
void CopyPropertiesToEntity (Entity * pToEnt, Entity * pFromEnt, const string varName1, const string varName2, const string varName3)
Definition at line 2195 of file EntityUtils.cpp.
References Entity::GetVar(), and Variant::Set().
Entity* CreateButtonHotspot (Entity * pParentEnt, string name, CL_Vec2f vPos, CL_Vec2f vBounds, Button2DComponent::eButtonStyle buttonStyle)
Definition at line 851 of file EntityUtils.cpp.
References Entity::AddComponent(), CreateOverlayRectEntity(), EntityComponent::GetVar(), Entity::GetVar(), Variant::Set(), Entity::SetName(), and Button2DComponent::STYLE_INVISIBLE_UNTIL_CLICKED.
Entity* CreateCheckbox (Entity * pBG, string name, string text, float x, float y, bool bChecked, eFont fontID, float fontScale)
Definition at line 2095 of file EntityUtils.cpp.
References AnimateStopEntityAndSetFrame(), CreateOverlayButtonEntity(), CreateTextLabelEntity(), EntitySetScaleBySize(), GetBaseApp(), BaseApp::GetFont(), Entity::GetFunction(), GetResourceManager(), ResourceManager::GetSurfaceAnim(), Entity::GetVar(), Variant::GetVector2(), iPhoneMapX(), iPhoneMapY(), LogError(), RTFont::MeasureText(), OnCheckboxToggle(), RemovePaddingEntity(), Variant::Set(), Surface::SetSmoothing(), SetTouchPaddingEntity(), SetupAnimEntity(), SetupTextEntity(), and FunctionObject::sig_function.
Entity* CreateInputTextEntity (Entity * pParentEnt, string name, float x, float y, string text, float sizeX, float sizeY)
Definition at line 796 of file EntityUtils.cpp.
References Entity::AddComponent(), Entity::AddEntity(), FONT_SMALL, GetBaseApp(), BaseApp::GetFont(), RTFont::GetLineHeight(), EntityComponent::GetVar(), Entity::GetVar(), and Variant::Set().
Entity* CreateOverlayButtonEntity (Entity * pParentEnt, string name, string fileName, float x, float y)
Like CreateOverlayEntity() but additionally adds a TouchHandlerComponent and a Button2DComponent to the created Entity too.
See also:
TouchHandlerComponent, Button2DComponent
Definition at line 29 of file EntityUtils.cpp.
References Entity::AddComponent(), and CreateOverlayEntity().
Referenced by CreateCheckbox(), and CreateSlider().
Entity* CreateOverlayEntity (Entity * pParentEnt, string name, string fileName, float x, float y)
Creates a new Entity and adds an OverlayRenderComponent to it.
If pParentEnt is not NULL the new Entity is added as a child to that Entity. If pParentEnt is NULL then the new Entity will have no parent.
The argument name sets the name of the new Entity.
Arguments x and y specify the position of the new Entity. The position of the OverlayRenderComponent follows the position of its parent Entity so these also set the position of that.
See also:
OverlayRenderComponent
Returns:
The newly created Entity or NULL if the creation failed for any reason.
Definition at line 5 of file EntityUtils.cpp.
References Entity::AddComponent(), Entity::AddEntity(), EntityComponent::GetVar(), Entity::GetVar(), LogError(), and Variant::Set().
Referenced by CreateOverlayButtonEntity(), and DPadComponent::OnAdd().
Entity* CreateOverlayRectEntity (Entity * pParent, CL_Rectf posAndBoundsRect, uint32 color, RectRenderComponent::eVisualStyle style)
Definition at line 823 of file EntityUtils.cpp.
References Entity::AddComponent(), Entity::AddEntity(), EntityComponent::GetVar(), Entity::GetVar(), Variant::Set(), and RectRenderComponent::STYLE_NORMAL.
Referenced by CreateButtonHotspot(), CreateOverlayRectEntity(), CreateSlider(), OnShowTextMessage(), and SetupLightBarSelect().
Entity* CreateOverlayRectEntity (Entity * pParent, CL_Vec2f vPos, CL_Vec2f vBounds, uint32 color, RectRenderComponent::eVisualStyle style)
Definition at line 845 of file EntityUtils.cpp.
References CreateOverlayRectEntity().
Entity* CreateScrollingTextBoxEntity (Entity * pParent, string entName, CL_Vec2f vPos, CL_Vec2f vTextAreaSize, string msg, float scale = 1.0f, eAlignment textAlignment = ALIGNMENT_UPPER_LEFT)
Like above, but puts the TextBoxRender component under a ScrollComponent.
It actually creates the structure scroll->scroll_child->entName. Function returns entName, but keep in mind it's inside two other entities.
It will automatically resize the scroll bars when it notices "text" changing in the TextBoxRender component.
Definition at line 1310 of file EntityUtils.cpp.
References Entity::AddComponent(), Entity::AddEntity(), MessageManager::CallEntityFunction(), Entity::GetFunction(), GetMessageManager(), EntityComponent::GetVar(), Entity::GetVar(), iPhoneMap(), ResizeScrollBounds(), ResizeScrollerAfterTextboxChanges(), Variant::Set(), and FunctionObject::sig_function.
EntityComponent* CreateSlider (Entity * pBG, float x, float y, float sizeX, string buttonFileName, string left, string middle, string right)
Definition at line 1960 of file EntityUtils.cpp.
References Entity::AddComponent(), Entity::AddEntity(), ALIGNMENT_CENTER, ALIGNMENT_UPPER_CENTER, ALIGNMENT_UPPER_RIGHT, Button2DComponent::BUTTON_STYLE_CLICK_ON_TOUCH, CreateOverlayButtonEntity(), CreateOverlayRectEntity(), CreateTextLabelEntity(), FONT_SMALL, GetBaseApp(), Entity::GetComponentByName(), BaseApp::GetFont(), RTFont::GetLineHeight(), EntityComponent::GetVar(), Entity::GetVar(), Variant::GetVector2(), iPhoneMapY2X(), IsLargeScreen(), Variant::Set(), SetAlignmentEntity(), SetButtonStyleEntity(), SetButtonVisualStyleEntity(), and Button2DComponent::STYLE_NONE.
Entity* CreateTextBoxEntity (Entity * pParent, string entName, CL_Vec2f vPos, CL_Vec2f vTextAreaSize, string msg, float scale = 1.0f, eAlignment textAlignment = ALIGNMENT_UPPER_LEFT)
Creates a new Entity and adds a TextBoxRenderComponent to it.
The pParent will be the parent Entity for the new Entity. It mustn't be NULL. The name of the new Entity is set to entName.
The new Entity's position ("pos2d") and size ("size2d") are set to vPos and vTextAreaSize respectively.
The following values are set to the created TextBoxRenderComponent:
the text is set to msg
the scale of the text is set to scale
the text alignment in set to textAlignment
See also:
TextBoxRenderComponent
Returns:
The newly created Entity.
Definition at line 1260 of file EntityUtils.cpp.
References Entity::AddComponent(), Entity::AddEntity(), EntityComponent::GetVar(), Entity::GetVar(), and Variant::Set().
Entity* CreateTextButtonEntity (Entity * pParentEnt, string name, float x, float y, string text, bool bUnderline)
Definition at line 890 of file EntityUtils.cpp.
References Entity::AddComponent(), and CreateTextLabelEntity().
Entity* CreateTextLabelEntity (Entity * pParentEnt, string name, float x, float y, string text)
Definition at line 776 of file EntityUtils.cpp.
References Entity::AddComponent(), Entity::AddEntity(), EntityComponent::GetVar(), Entity::GetVar(), and Variant::Set().
Referenced by CreateCheckbox(), CreateSlider(), CreateTextButtonEntity(), OnShowTextMessage(), and ProtonTester::showResultOnScreen().
void DestroyUnusedTextures ()
Definition at line 1762 of file EntityUtils.cpp.
References GetBaseApp(), GetEntityRoot(), BaseApp::GetResourceManager(), GetUsedTextures(), LogMsg(), and ResourceManager::RemoveTexturesNotInExclusionList().
void DisableAllButtonsEntity (Entity * pEnt, bool bRecursive)
Definition at line 554 of file EntityUtils.cpp.
References DisableAllButtonsEntity(), Entity::GetChildren(), Entity::GetComponentByName(), EntityComponent::GetVar(), and Variant::Set().
Referenced by DisableAllButtonsEntity().
EntityComponent* DisableComponentByName (Entity * pEnt, const string & compName, int delayBeforeActionMS)
Definition at line 1664 of file EntityUtils.cpp.
References Entity::GetComponentByName(), GetMessageManager(), EntityComponent::GetVar(), Variant::Set(), and MessageManager::SetComponentVariable().
Entity* DisableEntityButtonByName (const string & entityName, Entity * pRootEntity)
Definition at line 522 of file EntityUtils.cpp.
References Entity::GetComponentByName(), Entity::GetEntityByName(), EntityComponent::GetVar(), and Variant::Set().
void DisableHorizontalScrolling (Entity * pEnt)
Definition at line 1599 of file EntityUtils.cpp.
References Entity::GetComponentByName(), Entity::GetEntityByName(), Variant::GetRect(), and EntityComponent::GetVar().
void EnableAllButtonsEntity (Entity * pEnt, bool bRecursive, int delayBeforeActionMS, eTimingSystem timing)
Definition at line 614 of file EntityUtils.cpp.
References EnableAllButtonsEntity(), Entity::GetChildren(), Entity::GetComponentByName(), GetMessageManager(), EntityComponent::GetVar(), Variant::Set(), and MessageManager::SetComponentVariable().
Referenced by EnableAllButtonsEntity().
EntityComponent* EnableComponentByName (Entity * pEnt, const string & compName, int delayBeforeActionMS)
Definition at line 1685 of file EntityUtils.cpp.
References Entity::GetComponentByName(), GetMessageManager(), EntityComponent::GetVar(), Variant::Set(), and MessageManager::SetComponentVariable().
Entity* EnableEntityButtonByName (const string & entityName, Entity * pRootEntity)
Definition at line 591 of file EntityUtils.cpp.
References Entity::GetComponentByName(), Entity::GetEntityByName(), EntityComponent::GetVar(), and Variant::Set().
void EnableRawMessageFocusInput (Entity * pEnt)
Commands a FocusInputComponent in pEnt to also recognize the raw keyboard input messages.
The FocusInputComponent is searched for in pEnt and its parent Entities. If no FocusInputComponent is found then this method has no effect.
See also:
FocusInputComponent
Definition at line 991 of file EntityUtils.cpp.
References Entity::GetComponentByName(), EntityComponent::GetFunction(), and FunctionObject::sig_function.
float EnforceMinimumFontLineToScreenRatio (eFont fontID, float fontScale, float minLineToScreenRatio)
Definition at line 1236 of file EntityUtils.cpp.
References GetBaseApp(), BaseApp::GetFont(), RTFont::GetLineHeight(), and GetScreenSizeYf().
void EntityAdjustScaleSoPhysicalSizeMatches (Entity * pEnt, int ppiToMatch, float powerMult)
Definition at line 1826 of file EntityUtils.cpp.
References GetDevicePixelsPerInchDiagonal(), GetScale2DEntity(), and SetScale2DEntity().
bool EntityHasInputFocus (Entity * pEnt)
Definition at line 916 of file EntityUtils.cpp.
References Entity::GetComponentByName().
bool EntityIsOnScreen (Entity * pEnt)
Definition at line 2159 of file EntityUtils.cpp.
References GetScreenRect(), Entity::GetVar(), and Variant::GetVector2().
bool EntityRetinaRemapIfNeeded (Entity * pEnt, bool bAdjustPosition, bool bAdjustScale, bool bApplyToIpadAlso, bool bPerserveAspectRatio)
Definition at line 1783 of file EntityUtils.cpp.
References GetScreenSizeXf(), GetScreenSizeYf(), Entity::GetVar(), Variant::GetVector2(), iPhoneMap(), and Variant::Set().
void EntityScaleiPad (Entity * pEnt, bool bPerserveAspectRatio)
Definition at line 1900 of file EntityUtils.cpp.
References GetScreenSizeXf(), GetScreenSizeYf(), Entity::GetVar(), Variant::GetVector2(), and Variant::Set().
void EntitySetScaleBySize (Entity * pEnt, CL_Vec2f vDestSize, bool bPreserveAspectRatio = false, bool bPreserveOtherAxis = false)
Sets the scale of pEnt such that the resulting size of it will be vDestSize.
If the bPreserveAspectRatio is set to true the resulting scale is uniform. This means that pEnt's appearance will preserve its aspect ratio. If pEnt is taller than it's wide vDestSize.y is ignored and the resulting width of pEnt will be vDestSize.x. The height of pEnt will be whatever it needs to be to preserve the aspect ratio. Similarly if pEnt is wider than it's tall or it's square vDestSize.x is ignored and the resulting height of pEnt will be vDestSize.y. The width of pEnt will be whatever it needs to be to preserve the aspect ratio. To respect the the opposite axis, bPreserveOtherAxis can be set to true.
Definition at line 1847 of file EntityUtils.cpp.
References GetScale2DEntity(), Entity::GetVar(), Variant::GetVector2(), and Variant::Set().
Referenced by CreateCheckbox().
void FadeEntity (Entity * pEnt, bool bRecursive, float alpha, int timeMS, int delayBeforeFadingMS, bool bAllowMultipleFadesActiveAtOnce)
Definition at line 684 of file EntityUtils.cpp.
References FadeEntity(), Entity::GetChildren(), Entity::RemoveComponentByName(), EntityComponent::SetName(), and SetupInterpolateComponent().
Referenced by FadeEntity(), FadeScreen(), FadeScreenUp(), and DPadComponent::OnAdd().
void FadeInEntity (Entity * pEnt, bool bRecursive, int timeMS, int delayBeforeFadingMS, float fadeTarget, eTimingSystem timing)
Definition at line 367 of file EntityUtils.cpp.
References FadeInEntity(), Entity::GetChildren(), Entity::GetVar(), INTERPOLATE_SMOOTHSTEP, InterpolateComponent::ON_FINISH_DIE, Variant::Set(), and SetupInterpolateComponent().
Referenced by FadeInEntity().
void FadeOutAndKillChildrenEntities (Entity * pEnt, int timeMS, int delayBeforeFadingMS, eTimingSystem timing)
Definition at line 731 of file EntityUtils.cpp.
References FadeOutAndKillEntity(), and Entity::GetChildren().
void FadeOutAndKillEntity (Entity * pEnt, bool bRecursive, int timeMS, int delayBeforeFadingMS, eTimingSystem timing)
Definition at line 724 of file EntityUtils.cpp.
References FadeOutEntity(), and KillEntity().
Referenced by FadeOutAndKillChildrenEntities(), and OnShowTextMessage().
void FadeOutEntity (Entity * pEnt, bool bRecursive, int timeMS, int delayBeforeFadingMS, eTimingSystem timing)
Definition at line 707 of file EntityUtils.cpp.
References FadeOutEntity(), Entity::GetChildren(), INTERPOLATE_SMOOTHSTEP, InterpolateComponent::ON_FINISH_DIE, and SetupInterpolateComponent().
Referenced by FadeOutAndKillEntity(), and FadeOutEntity().
Entity* FadeScreen (Entity * pParent, float defaultStartAlpha, float targetAlpha, int fadeDurationMS, bool bDeleteWhenDone)
Definition at line 1002 of file EntityUtils.cpp.
References Entity::AddComponent(), Entity::AddEntity(), FadeEntity(), Entity::GetEntityByName(), GetScreenSizeXf(), GetScreenSizeYf(), Entity::GetVar(), KillEntity(), Variant::Set(), and Entity::SetName().
void FadeScreenUp (Entity * pParent, float targetAlpha, int fadeDurationMS, bool bDeleteWhenDone)
Definition at line 1028 of file EntityUtils.cpp.
References Entity::AddComponent(), Entity::AddEntity(), FadeEntity(), Entity::GetEntityByName(), GetScreenSizeXf(), GetScreenSizeYf(), Entity::GetVar(), KillEntity(), and Variant::Set().
void FakeClickAnEntity (Entity * pEnt, int delayBeforeStartingMS)
Definition at line 2050 of file EntityUtils.cpp.
References Entity::GetVar(), Variant::GetVector2(), MESSAGE_TYPE_GUI_CLICK_END, MESSAGE_TYPE_GUI_CLICK_START, and SendFakeInputMessageToEntity().
Referenced by FakeClickAnEntityByName().
bool FakeClickAnEntityByName (Entity * pEntitySearchRoot, const string name)
Definition at line 2038 of file EntityUtils.cpp.
References FakeClickAnEntity(), and Entity::GetEntityByName().
void FlashOnceEntity (Entity * pEnt, int flashSpeedMS)
Definition at line 675 of file EntityUtils.cpp.
References Variant::GetFloat(), EntityComponent::GetVar(), Entity::GetVar(), INTERPOLATE_SMOOTHSTEP, InterpolateComponent::ON_FINISH_BOUNCE, Entity::RemoveComponentByName(), Variant::Set(), and SetupInterpolateComponent().
void FlashStartEntity (Entity * pEnt, int flashSpeedMS)
Definition at line 667 of file EntityUtils.cpp.
References FlashStopEntity(), Variant::GetFloat(), EntityComponent::GetVar(), Entity::GetVar(), INTERPOLATE_SMOOTHSTEP, InterpolateComponent::ON_FINISH_BOUNCE, Variant::Set(), and SetupInterpolateComponent().
void FlashStopEntity (Entity * pEnt)
Definition at line 662 of file EntityUtils.cpp.
References Entity::RemoveComponentByName().
Referenced by FlashStartEntity().
eAlignment GetAlignmentEntity (Entity * pEnt)
Definition at line 1255 of file EntityUtils.cpp.
References Variant::GetUINT32(), and Entity::GetVar().
void GetFontAndScaleToFitThisLinesPerScreenY (eFont * pFontIDOut, float * pFontScaleOut, float desiredLinesPerScreenY)
Definition at line 1199 of file EntityUtils.cpp.
References FONT_LARGE, FONT_SMALL, GetBaseApp(), BaseApp::GetFont(), RTFont::GetLineHeight(), and GetScreenSizeYf().
void GetFontAndScaleToFitThisPixelHeight (eFont * pFontIDOut, float * pFontScaleOut, float heightPixels)
Definition at line 1215 of file EntityUtils.cpp.
References FONT_LARGE, FONT_SMALL, GetBaseApp(), BaseApp::GetFont(), and RTFont::GetLineHeight().
void GetFontAndScaleToFitThisStringInWidthPixels (eFont * pFontIDOut, float * pFontScaleOut, string text, float desiredWidth)
Definition at line 1176 of file EntityUtils.cpp.
References FONT_LARGE, FONT_SMALL, GetBaseApp(), BaseApp::GetFont(), RTFont::GetLineHeight(), and RTFont::MeasureText().
std::string GetOverlayImageEntity (Entity * pEntWithOverlayComponent)
Gets the filename of an OverlayRenderComponent found from pEntWithOverlayComponent.
The entity should contain an OverlayRenderComponent named "OverlayRender" (which is the default name for that component). The returned value is the current value of the "fileName" attribute in that component.
Returns an empty string if:
no component named "OverlayRender" is found in the entity, or
the found component has no attribute named "fileName", or
the attribute really is an empty string
Definition at line 353 of file EntityUtils.cpp.
References Entity::GetComponentByName(), Variant::GetString(), and EntityComponent::GetVar().
CL_Vec2f GetPos2DEntity (Entity * pEnt)
Definition at line 2170 of file EntityUtils.cpp.
References Entity::GetVar(), and Variant::GetVector2().
Referenced by BobEntity(), and GetScreenPos2DEntity().
CL_Vec2f GetScale2DEntity (Entity * pEnt)
Definition at line 2173 of file EntityUtils.cpp.
References Entity::GetVar(), and Variant::GetVector2().
Referenced by EntityAdjustScaleSoPhysicalSizeMatches(), and EntitySetScaleBySize().
CL_Vec2f GetScreenPos2DEntity (Entity * pEnt, CL_Vec2f vRecursivePosToAdd)
Definition at line 2277 of file EntityUtils.cpp.
References ConvertEntityClickToScreenCoords(), Entity::GetParent(), GetPos2DEntity(), and GetScreenPos2DEntity().
Referenced by GetScreenPos2DEntity().
CL_Vec2f GetScrollProgressEntity (Entity * pEnt)
Definition at line 1626 of file EntityUtils.cpp.
References Entity::GetComponentByName(), EntityComponent::GetVar(), and Variant::GetVector2().
CL_Vec2f GetSize2DEntity (Entity * pEnt)
Definition at line 2167 of file EntityUtils.cpp.
References Entity::GetVar(), and Variant::GetVector2().
Referenced by OnShowTextMessage().
void GetUsedTextures (vector< string > & usedTextures, Entity * pEnt)
Definition at line 1722 of file EntityUtils.cpp.
References Entity::GetChildren(), Entity::GetComponents(), EntityComponent::GetName(), Variant::GetString(), GetUsedTextures(), and EntityComponent::GetVar().
Referenced by DestroyUnusedTextures(), and GetUsedTextures().
bool IsCheckboxChecked (Entity * pEnt)
Definition at line 2058 of file EntityUtils.cpp.
References Variant::GetUINT32(), and Entity::GetVar().
Referenced by OnCheckboxToggle().
bool IsDisabledEntity (Entity * pEnt)
Definition at line 509 of file EntityUtils.cpp.
References Entity::GetComponentByName(), Variant::GetUINT32(), and EntityComponent::GetVar().
bool IsEntityBobbing (Entity * pEnt)
Definition at line 144 of file EntityUtils.cpp.
References Entity::GetComponentByName().
void KillEntity (Entity * pEnt, int timeMS, eTimingSystem timingSystem)
Definition at line 762 of file EntityUtils.cpp.
References MessageManager::CallEntityFunction(), GetMessageManager(), and Entity::SetTaggedForDeletion().
Referenced by FadeOutAndKillEntity(), FadeScreen(), FadeScreenUp(), and SetConsole().
void LightBarOnChange (VariantList * pVList)
Definition at line 1501 of file EntityUtils.cpp.
References VariantList::Get(), Variant::GetEntity(), Entity::GetEntityByName(), Entity::GetName(), Entity::GetParent(), Entity::GetVar(), Variant::GetVector2(), MorphToSizeEntity(), and ZoomToPositionEntity().
Referenced by SetupLightBarSelect().
EntityComponent* MakeButtonEmitVirtualGameKey (Entity * pEnt, uint32 keycode)
Definition at line 1948 of file EntityUtils.cpp.
References Entity::AddComponent(), EntityComponent::GetVar(), and Variant::Set().
void ManuallySetAlignmentEntity (Entity * pEnt, eAlignment alignment)
Definition at line 2015 of file EntityUtils.cpp.
References GetAlignmentOffset(), Variant::GetFloat(), Entity::GetVar(), Variant::GetVector2(), RotationToXYMod(), and Variant::Set().
CL_Rectf MeasureEntityAndChildren (Entity * pEnt, CL_Vec2f * pVStartingPos, bool bFirst)
Definition at line 1052 of file EntityUtils.cpp.
References ALIGNMENT_UPPER_LEFT, GetAlignmentOffset(), Entity::GetChildren(), Variant::GetUINT32(), Entity::GetVar(), Variant::GetVector2(), and MeasureEntityAndChildren().
Referenced by MeasureEntityAndChildren(), and ResizeScrollBounds().
void MorphToColorEntity (Entity * pEnt, bool bRecursive, int timeMS, unsigned int color, int delayBeforeActionMS, bool bAllowMultipleAtOnce)
Definition at line 471 of file EntityUtils.cpp.
References Entity::GetChildren(), INTERPOLATE_SMOOTHSTEP_AS_COLOR, MorphToColorEntity(), EntityComponent::SetName(), and SetupInterpolateComponent().
Referenced by MorphToColorEntity().
EntityComponent* MorphToFloatComponent (EntityComponent * pTargetComp, string targetVar, float target, unsigned int speedMS, eInterpolateType interpolateType, int delayBeforeActionMS)
Definition at line 411 of file EntityUtils.cpp.
References EntityComponent::GetName(), EntityComponent::GetParent(), EntityComponent::GetVar(), MorphToFloatEntity(), and Variant::Set().
EntityComponent* MorphToFloatEntity (Entity * pEnt, string targetVar, float target, unsigned int speedMS, eInterpolateType interpolateType, int delayBeforeActionMS)
Definition at line 400 of file EntityUtils.cpp.
References SetupInterpolateComponent().
Referenced by MorphToFloatComponent().
EntityComponent* MorphToSizeEntity (Entity * pEnt, CL_Vec2f vTargetSize, unsigned int speedMS, eInterpolateType interpolateType, int delayBeforeActionMS)
Definition at line 405 of file EntityUtils.cpp.
References MorphToVec2Entity().
Referenced by LightBarOnChange().
EntityComponent* MorphToVec2Component (EntityComponent * pTargetComp, string targetVar, CL_Vec2f vTargetSize, unsigned int speedMS, eInterpolateType interpolateType, int delayBeforeActionMS)
Definition at line 419 of file EntityUtils.cpp.
References EntityComponent::GetName(), EntityComponent::GetParent(), EntityComponent::GetVar(), MorphToVec2Entity(), and Variant::Set().
EntityComponent* MorphToVec2Entity (Entity * pEnt, string targetVar, CL_Vec2f vTargetSize, unsigned int speedMS, eInterpolateType interpolateType, int delayBeforeActionMS)
Definition at line 386 of file EntityUtils.cpp.
References SetupInterpolateComponent().
Referenced by MorphToSizeEntity(), MorphToVec2Component(), ZoomToPositionEntity(), ZoomToPositionOffsetEntity(), and ZoomToScaleEntity().
EntityComponent* MorphToVec2EntityMulti (Entity * pEnt, string targetVar, CL_Vec2f vTargetSize, unsigned int speedMS, eInterpolateType interpolateType, int delayBeforeActionMS)
Definition at line 392 of file EntityUtils.cpp.
References EntityComponent::SetName(), and SetupInterpolateComponent().
Referenced by ZoomToPositionOffsetEntityMulti().
void MoveEntityToTop (VariantList * pVList)
Definition at line 2211 of file EntityUtils.cpp.
References AddFocusIfNeeded(), VariantList::Get(), Variant::GetEntity(), and RemoveFocusIfNeeded().
Referenced by OnShowTextMessage().
void OnCheckboxToggle (VariantList * pVList)
Definition at line 2089 of file EntityUtils.cpp.
References Variant::GetEntity(), IsCheckboxChecked(), VariantList::m_variant, and SetCheckBoxChecked().
Referenced by CreateCheckbox().
void OneTimeBobEntity (Entity * pEnt, float bobAmount, int delayBeforeBob, int durationMS)
Definition at line 173 of file EntityUtils.cpp.
References Entity::GetComponentByName(), EntityComponent::GetVar(), Entity::GetVar(), Variant::GetVector2(), INTERPOLATE_SMOOTHSTEP, InterpolateComponent::ON_FINISH_BOUNCE, Variant::Set(), and SetupInterpolateComponent().
Referenced by SetCheckBoxChecked().
void OnShowTextMessage (VariantList * pVList)
Definition at line 2219 of file EntityUtils.cpp.
References Entity::AddEntity(), AddFocusIfNeeded(), ALIGNMENT_UPPER_CENTER, MessageManager::CallEntityFunction(), CreateOverlayRectEntity(), CreateTextLabelEntity(), FadeOutAndKillEntity(), FONT_LARGE, VariantList::Get(), Entity::GetFunction(), GetMessageManager(), GetScreenSize(), GetScreenSizeXf(), GetScreenSizeYf(), GetSize2DEntity(), Variant::GetString(), Variant::GetUINT32(), MoveEntityToTop(), SetAlignmentEntity(), SetupTextEntity(), FunctionObject::sig_function, TIMER_SYSTEM, and ZoomFromPositionEntity().
Referenced by ShowTextMessage().
void PreloadKeyboard (OSMessage::eParmKeyboardType keyboardType)
Definition at line 1443 of file EntityUtils.cpp.
References BaseApp::AddOSMessage(), VariantList::Get(), GetBaseApp(), GetEmulatedPlatformID(), OSMessage::m_fontSize, OSMessage::m_parm1, OSMessage::m_parm2, BaseApp::m_sig_hardware, OSMessage::m_sizeX, OSMessage::m_sizeY, OSMessage::m_string, OSMessage::m_type, OSMessage::m_x, OSMessage::m_y, OSMessage::MESSAGE_CLOSE_TEXT_BOX, OSMessage::MESSAGE_OPEN_TEXT_BOX, MESSAGE_TYPE_HW_KEYBOARD_INPUT_ENDING, MESSAGE_TYPE_HW_KEYBOARD_INPUT_STARTING, PLATFORM_ID_ANDROID, Variant::Set(), and SetLastStringInput().
EntityComponent* PulsateColorEntity (Entity * pEnt, bool bRecursive, unsigned int color, unsigned int pulsateSpeedMS)
Definition at line 490 of file EntityUtils.cpp.
References Entity::GetChildren(), INTERPOLATE_SMOOTHSTEP_AS_COLOR, InterpolateComponent::ON_FINISH_BOUNCE, PulsateColorEntity(), and SetupInterpolateComponent().
Referenced by PulsateColorEntity().
void RemoveFocusIfNeeded (Entity * pEnt)
Definition at line 904 of file EntityUtils.cpp.
References Entity::RemoveComponentByName().
Referenced by MoveEntityToTop().
void RemoveInputFocusIfNeeded (Entity * pEnt)
Definition at line 911 of file EntityUtils.cpp.
References Entity::RemoveComponentByName().
void RemovePaddingEntity (Entity * pEnt)
Definition at line 1356 of file EntityUtils.cpp.
References SetTouchPaddingEntity().
Referenced by CreateCheckbox().
void ResizeScrollBounds (VariantList * pVList)
Definition at line 1573 of file EntityUtils.cpp.
References VariantList::Get(), Entity::GetComponentByName(), Variant::GetEntity(), Entity::GetEntityByName(), EntityComponent::GetVar(), Entity::GetVar(), Variant::GetVector2(), LogError(), MeasureEntityAndChildren(), and Variant::Set().
Referenced by CreateScrollingTextBoxEntity(), and ResizeScrollerAfterTextboxChanges().
void ResizeScrollerAfterTextboxChanges (VariantList * vList)
Definition at line 1304 of file EntityUtils.cpp.
References VariantList::Get(), Variant::GetEntity(), Entity::GetParent(), and ResizeScrollBounds().
Referenced by CreateScrollingTextBoxEntity().
void ScaleEntity (Entity * pEnt, float scaleStart, float scaleEnd, int timeMS, int delayBeforeStartingMS, eInterpolateType interpolationType)
Definition at line 744 of file EntityUtils.cpp.
References ScaleEntity().
Referenced by ScaleEntity().
void ScaleEntity (Entity * pEnt, CL_Vec2f vScaleStart, CL_Vec2f vScaleEnd, int timeMS, int delayBeforeStartingMS, eInterpolateType interpolationType)
Definition at line 749 of file EntityUtils.cpp.
References Entity::GetVar(), Entity::RemoveComponentByName(), Variant::Set(), EntityComponent::SetName(), and SetupInterpolateComponent().
void SendFakeButtonPushToEntity (Entity * pEntity, int timeMS)
Definition at line 1520 of file EntityUtils.cpp.
References MessageManager::CallEntityFunction(), GetMessageManager(), Entity::GetVar(), and Variant::GetVector2().
void SendFakeInputMessageToEntity (Entity * pEnt, eMessageType msg, CL_Vec2f vClickPos, int delayBeforeStartingMS)
Definition at line 1475 of file EntityUtils.cpp.
References MessageManager::CallEntityFunction(), Entity::CallFunctionRecursively(), VariantList::Get(), GetBaseApp(), GetMessageManager(), BaseApp::GetTouch(), Variant::Set(), TouchTrackInfo::SetIsDown(), TouchTrackInfo::SetPos(), and TouchTrackInfo::SetWasHandled().
Referenced by FakeClickAnEntity().
void SetAlignmentEntity (Entity * pEnt, eAlignment align)
Definition at line 1250 of file EntityUtils.cpp.
References Entity::GetVar(), and Variant::Set().
Referenced by CreateSlider(), DPadComponent::OnAdd(), and OnShowTextMessage().
void SetAlphaEntity (Entity * pEnt, float alpha)
Definition at line 1438 of file EntityUtils.cpp.
References Entity::GetVar(), and Variant::Set().
Referenced by DPadComponent::OnAdd().
void SetButtonClickSound (Entity * pEnt, string fileName)
Definition at line 878 of file EntityUtils.cpp.
References Entity::GetComponentByName(), EntityComponent::GetVar(), and Variant::Set().
Referenced by SetupEntityToEatInput().
void SetButtonRepeatDelayMS (Entity * pEnt, uint32 delayMS)
Definition at line 866 of file EntityUtils.cpp.
References Entity::GetComponentByName(), EntityComponent::GetVar(), and Variant::Set().
EntityComponent* SetButtonStyleEntity (Entity * pEnt, Button2DComponent::eButtonStyle style)
Definition at line 1380 of file EntityUtils.cpp.
References Entity::GetComponentByName(), EntityComponent::GetVar(), and Variant::Set().
Referenced by CreateSlider(), SetupEntityToEatInput(), and SetupLightBarSelect().
EntityComponent* SetButtonVisualStyleEntity (Entity * pEnt, Button2DComponent::eVisualStyle style)
Definition at line 1366 of file EntityUtils.cpp.
References Entity::GetComponentByName(), EntityComponent::GetVar(), and Variant::Set().
Referenced by CreateSlider(), and SetupEntityToEatInput().
void SetCheckBoxChecked (Entity * pEnt, bool bChecked, bool bShowAnim)
Definition at line 2069 of file EntityUtils.cpp.
References AnimateStopEntityAndSetFrame(), Entity::GetVar(), OneTimeBobEntity(), and Variant::Set().
Referenced by OnCheckboxToggle().
void SetDisabledOnAllComponentsRecursively (Entity * pEnt, bool bDisabled)
Definition at line 1639 of file EntityUtils.cpp.
References Entity::GetChildren(), Entity::GetComponents(), and SetDisabledOnAllComponentsRecursively().
Referenced by SetDisabledOnAllComponentsRecursively().
void SetEntityOverlayToUnloadImageOnKill (Entity * pImage)
Definition at line 2292 of file EntityUtils.cpp.
References Entity::GetComponentByName(), EntityComponent::GetVar(), and Variant::Set().
EntityComponent* SetOverlayImageEntity (Entity * pEntWithOverlayComponent, string imageFileName, uint32 delayBeforeActionMS = 0, bool bAddBasePath = true)
Sets the filename of an OverlayRenderComponent found from pEntWithOverlayComponent.
The entity must contain an OverlayRenderComponent named "OverlayRender" (which is the default name for that component). Otherwise an assert occurs.
The "fileName" attribute of the OverlayRenderComponent is set to imageFileName.
If delayBeforeActionMS is greater than 0 then the "fileName" attribute is set only after a delay of delayBeforeActionMS milliseconds.
Returns:
the OverlayRenderComponent that got modified.
Definition at line 326 of file EntityUtils.cpp.
References Entity::GetComponentByName(), GetMessageManager(), EntityComponent::GetVar(), Variant::Set(), and MessageManager::SetComponentVariable().
void SetPos2DEntity (Entity * pEnt, const CL_Vec2f & vPos)
Definition at line 2171 of file EntityUtils.cpp.
References Entity::GetVar(), and Variant::Set().
void SetProgressBarPercent (Entity * pEnt, float progressPercent)
Definition at line 2176 of file EntityUtils.cpp.
References Entity::GetComponentByName(), EntityComponent::GetVar(), and Variant::Set().
void SetScale2DEntity (Entity * pEnt, const CL_Vec2f & vScale)
Definition at line 2174 of file EntityUtils.cpp.
References Entity::GetVar(), and Variant::Set().
Referenced by EntityAdjustScaleSoPhysicalSizeMatches().
void SetScrollProgressEntity (Entity * pEnt, const CL_Vec2f & progress)
Sets the progress (position) of a ScrollComponent.
The component needs to be found from pEnt.
See also:
ScrollComponent for details.
Definition at line 1612 of file EntityUtils.cpp.
References Entity::GetComponentByName(), EntityComponent::GetFunction(), and FunctionObject::sig_function.
void SetSize2DEntity (Entity * pEnt, const CL_Vec2f & vSize)
Definition at line 2168 of file EntityUtils.cpp.
References Entity::GetVar(), and Variant::Set().
EntityComponent* SetTextEntity (Entity * pEntWithTextComponent, const string & text)
Definition at line 1273 of file EntityUtils.cpp.
References Entity::GetComponentByName(), EntityComponent::GetVar(), and Variant::Set().
Entity* SetTextEntityByName (const string & entityName, string text, Entity * pRootEntity)
Definition at line 2135 of file EntityUtils.cpp.
References Entity::GetComponentByName(), Entity::GetEntityByName(), EntityComponent::GetVar(), and Variant::Set().
void SetTextShadowColor (Entity * pEnt, uint32 color)
Definition at line 1147 of file EntityUtils.cpp.
References Entity::GetComponentByName(), EntityComponent::GetVar(), and Variant::Set().
void SetTouchPaddingEntity (Entity * pEnt, CL_Rectf padding)
Definition at line 1361 of file EntityUtils.cpp.
References Entity::GetVar(), and Variant::Set().
Referenced by CreateCheckbox(), and RemovePaddingEntity().
EntityComponent* SetupAnimEntity (Entity * pEnt, uint32 frameCountX, uint32 frameCountY, int curFrameX, int curFrameY)
Definition at line 234 of file EntityUtils.cpp.
References Entity::GetComponentByName(), EntityComponent::GetFunction(), EntityComponent::GetVar(), Variant::Set(), and FunctionObject::sig_function.
Referenced by CreateCheckbox().
void SetupEntityToEatInput (Entity * pEnt)
Definition at line 2250 of file EntityUtils.cpp.
References Entity::AddComponent(), Button2DComponent::BUTTON_STYLE_CLICK_ON_TOUCH, Entity::GetComponentByName(), SetButtonClickSound(), SetButtonStyleEntity(), SetButtonVisualStyleEntity(), and Button2DComponent::STYLE_NONE.
EntityComponent* SetupInterpolateComponent (Entity * pEnt, const string & componentName, const string & varName, const Variant & targetValue, int durationMS, int delayBeforeStartMS, eInterpolateType interpolationType = INTERPOLATE_SMOOTHSTEP, InterpolateComponent::eOnFinish onFinish = InterpolateComponent::ON_FINISH_DIE, eTimingSystem timing = GetTiming())
Sets up an InterpolateComponent in an Entity.
Parameters:
componentName if not empty tries to find a pre-existing InterpolateComponent with the given name from the Entity. If no such component is found, a new InterpolateComponent is created to the Entity and its name is set to this value. If this argument is an empty string it is ignored.
Definition at line 46 of file EntityUtils.cpp.
References Entity::AddComponent(), Entity::GetComponentByName(), GetMessageManager(), Entity::GetShared(), EntityComponent::GetVar(), VariantDB::GetVarIfExists(), Variant::Set(), MessageManager::SetComponentVariable(), and EntityComponent::SetName().
Referenced by BobEntity(), FadeEntity(), FadeInEntity(), FadeOutEntity(), FlashOnceEntity(), FlashStartEntity(), MorphToColorEntity(), MorphToFloatEntity(), MorphToVec2Entity(), MorphToVec2EntityMulti(), OneTimeBobEntity(), PulsateColorEntity(), ScaleEntity(), SlideScreen(), SlideScreenVertical(), ZoomFromPositionEntity(), ZoomToPositionEntityMulti(), and ZoomToPositionFromThisOffsetEntity().
void SetupLightBarSelect (Entity * pBG, string entNamePrefix, int defaultOption, uint32 color)
Definition at line 1525 of file EntityUtils.cpp.
References Button2DComponent::BUTTON_STYLE_CLICK_ON_TOUCH, CreateOverlayRectEntity(), Entity::GetEntityByName(), Entity::GetFunction(), Entity::GetVar(), Variant::GetVector2(), LightBarOnChange(), Entity::MoveEntityToBottomByAddress(), Variant::Set(), SetButtonStyleEntity(), Entity::SetName(), FunctionObject::sig_function, and toString().
void SetupTextEntity (Entity * pEnt, eFont fontID, float scale)
Definition at line 1098 of file EntityUtils.cpp.
References Entity::GetComponentByName(), EntityComponent::GetVar(), Entity::GetVar(), and Variant::Set().
Referenced by CreateCheckbox(), CreateLogDisplayEntity(), and OnShowTextMessage().
void SetVisibleEntity (Entity * pEnt, bool bVisible)
Definition at line 2188 of file EntityUtils.cpp.
References Entity::GetVar(), and Variant::Set().
void ShowTextMessage (string msg, int timeMS, int delayBeforeStartingMS)
Definition at line 2243 of file EntityUtils.cpp.
References MessageManager::CallStaticFunction(), GetMessageManager(), OnShowTextMessage(), and TIMER_SYSTEM.
EntityComponent* SlideScreen (Entity * pEnt, bool bIn, int speedMS, int delayToStartMS)
Definition at line 107 of file EntityUtils.cpp.
References GetScreenSizeX(), GetScreenSizeXf(), Entity::GetVar(), Variant::GetVector2(), Variant::Set(), and SetupInterpolateComponent().
EntityComponent* SlideScreenVertical (Entity * pEnt, bool bIn, int speedMS, int delayToStartMS)
Definition at line 126 of file EntityUtils.cpp.
References GetScreenSizeYf(), Entity::GetVar(), Variant::GetVector2(), Variant::Set(), and SetupInterpolateComponent().
EntityComponent* TypeTextLabelEntity (Entity * pEnt, int delayBeforeActionMS, uint32 textTypeSpeedMS, TyperComponent::eMode mode, string textToAddByTyping)
Definition at line 1393 of file EntityUtils.cpp.
References Entity::AddComponent(), Entity::GetComponentByName(), GetMessageManager(), Variant::GetString(), EntityComponent::GetVar(), Entity::RemoveComponentByAddress(), Variant::Set(), and MessageManager::SetComponentVariable().
EntityComponent* ZoomFromPositionEntity (Entity * pEnt, CL_Vec2f vPos, unsigned int speedMS, eInterpolateType interpolateType = INTERPOLATE_SMOOTHSTEP, int delayBeforeActionMS = 0)
Adds a position animation to an Entity.
If there is a previous position animation running it is removed first.
The animation starts from the position determined by vPos. The animation will end to the current position of the Entity.
Parameters:
pEnt the Entity to animate.
vPos the start position of the animation.
speedMS the duration of the animation in milliseconds.
interpolateType the type of the interpolation.
delayBeforeActionMS delay in milliseconds before the animation is started. If set to 0 the animation is started immediately.
Returns:
the EntityComponent that performs the animation.
Definition at line 436 of file EntityUtils.cpp.
References Entity::GetVar(), Variant::GetVector2(), Variant::Set(), and SetupInterpolateComponent().
Referenced by OnShowTextMessage().
EntityComponent* ZoomToPositionEntity (Entity * pEnt, CL_Vec2f vPos, unsigned int speedMS, eInterpolateType interpolateType = INTERPOLATE_SMOOTHSTEP, int delayBeforeActionMS = 0)
Adds a position animation to an Entity.
If there is a previous position animation running it is removed first.
The animation starts from the current position of the Entity. The end position is determined by vPos.
Parameters:
pEnt the Entity to animate.
vPos the end position of the animation.
speedMS the duration of the animation in milliseconds.
interpolateType the type of the interpolation.
delayBeforeActionMS delay in milliseconds before the animation is started. If set to 0 the animation is started immediately.
Returns:
the EntityComponent that performs the animation.
Definition at line 444 of file EntityUtils.cpp.
References MorphToVec2Entity().
Referenced by LightBarOnChange().
EntityComponent* ZoomToPositionEntityMulti (Entity * pEnt, CL_Vec2f vPos, unsigned int speedMS, eInterpolateType interpolateType, int delayBeforeActionMS)
Like ZoomToPositionEntity() but doesn't remove any animations currently running.
Definition at line 459 of file EntityUtils.cpp.
References EntityComponent::SetName(), and SetupInterpolateComponent().
EntityComponent* ZoomToPositionFromThisOffsetEntity (Entity * pEnt, CL_Vec2f offset, unsigned int speedMS, eInterpolateType interpolateType = INTERPOLATE_SMOOTHSTEP, int delayBeforeActionMS = 0)
Adds a position animation to an Entity.
If there is a previous position animation running it is removed first.
The animation starts from the current position of the Entity offset by offset. The animation will end to the current position of the Entity.
Parameters:
pEnt the Entity to animate.
offset the offset from where the animation starts.
speedMS the duration of the animation in milliseconds.
interpolateType the type of the interpolation.
delayBeforeActionMS delay in milliseconds before the animation is started. If set to 0 the animation is started immediately.
Returns:
the EntityComponent that performs the animation.
Definition at line 426 of file EntityUtils.cpp.
References Entity::GetVar(), Variant::GetVector2(), Variant::Set(), and SetupInterpolateComponent().
EntityComponent* ZoomToPositionOffsetEntity (Entity * pEnt, CL_Vec2f offset, unsigned int speedMS, eInterpolateType interpolateType = INTERPOLATE_SMOOTHSTEP, int delayBeforeActionMS = 0)
Adds a position animation to an Entity.
If there is a previous position animation running it is removed first.
The animation starts from the current position of the Entity. The animation will end to the current position of the Entity offset by offset.
Parameters:
pEnt the Entity to animate.
offset the offset to where the animation ends.
speedMS the duration of the animation in milliseconds.
interpolateType the type of the interpolation.
delayBeforeActionMS delay in milliseconds before the animation is started. If set to 0 the animation is started immediately.
Returns:
the EntityComponent that performs the animation.
Definition at line 449 of file EntityUtils.cpp.
References Entity::GetVar(), Variant::GetVector2(), and MorphToVec2Entity().
EntityComponent* ZoomToPositionOffsetEntityMulti (Entity * pEnt, CL_Vec2f offset, unsigned int speedMS, eInterpolateType interpolateType, int delayBeforeActionMS)
Like ZoomToPositionOffsetEntity() but doesn't remove any animations currently running.
Definition at line 454 of file EntityUtils.cpp.
References Entity::GetVar(), Variant::GetVector2(), and MorphToVec2EntityMulti().
EntityComponent* ZoomToScaleEntity (Entity * pEnt, CL_Vec2f vScale, unsigned int speedMS, eInterpolateType interpolateType = INTERPOLATE_SMOOTHSTEP, int delayBeforeActionMS = 0)
Adds a scale animation to an Entity.
The animation starts from the current scale of the Entity.
Parameters:
pEnt the Entity to animate.
vScale the end scale of the animation.
speedMS the duration of the animation in milliseconds.
interpolateType the type of the interpolation.
delayBeforeActionMS delay in milliseconds before the animation is started. If set to 0 the animation is started immediately.
Returns:
the EntityComponent that performs the animation.
Definition at line 466 of file EntityUtils.cpp.
References MorphToVec2Entity().