Proton: FilterComponent.h File Reference
FilterComponent.h File Reference
Classes
class FilterComponent
Functions
EntityComponent * AddFilter (Entity *pEnt, string functionName, Entity::eFilterCommunication filterSetting=Entity::FILTER_ALLOW)
Entity::eFilterCommunication GetFilterSetting (Entity *pEnt, string functionName)
void SetFilterSetting (Entity *pEnt, string functionName, Entity::eFilterCommunication filterSetting, int timeMS=0)
Function Documentation
EntityComponent* AddFilter (Entity * pEnt, string functionName, Entity::eFilterCommunication filterSetting = Entity::FILTER_ALLOW)
Definition at line 48 of file FilterComponent.cpp.
References Entity::AddComponent(), EntityComponent::GetVar(), and Variant::Set().
Entity::eFilterCommunication GetFilterSetting (Entity * pEnt, string functionName)
Definition at line 58 of file FilterComponent.cpp.
References Entity::FILTER_ALLOW, Entity::GetComponentByName(), Variant::GetUINT32(), EntityComponent::GetVar(), and LogMsg().
void SetFilterSetting (Entity * pEnt, string functionName, Entity::eFilterCommunication filterSetting, int timeMS = 0)
Definition at line 70 of file FilterComponent.cpp.
References Entity::GetComponentByName(), GetMessageManager(), EntityComponent::GetVar(), LogMsg(), Variant::Set(), and MessageManager::SetComponentVariable().