Proton: gl.h File Reference
flash/GLES/gl.h File Reference
Typedefs
typedef void GLvoid
typedef unsigned int GLenum
typedef unsigned char GLboolean
typedef unsigned int GLbitfield
typedef khronos_int8_t GLbyte
typedef short GLshort
typedef int GLint
typedef int GLsizei
typedef khronos_uint8_t GLubyte
typedef unsigned short GLushort
typedef unsigned int GLuint
typedef khronos_float_t GLfloat
typedef khronos_float_t GLclampf
typedef khronos_int32_t GLfixed
typedef khronos_int32_t GLclampx
typedef khronos_intptr_t GLintptr
typedef khronos_ssize_t GLsizeiptr
Functions
GL_API void GL_APIENTRY glAlphaFunc (GLenum func, GLclampf ref)
GL_API void GL_APIENTRY glClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
GL_API void GL_APIENTRY glClearDepthf (GLclampf depth)
GL_API void GL_APIENTRY glClipPlanef (GLenum plane, const GLfloat *equation)
GL_API void GL_APIENTRY glColor4f (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
GL_API void GL_APIENTRY glDepthRangef (GLclampf zNear, GLclampf zFar)
GL_API void GL_APIENTRY glFogf (GLenum pname, GLfloat param)
GL_API void GL_APIENTRY glFogfv (GLenum pname, const GLfloat *params)
GL_API void GL_APIENTRY glFrustumf (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
GL_API void GL_APIENTRY glGetClipPlanef (GLenum pname, GLfloat eqn[4])
GL_API void GL_APIENTRY glGetFloatv (GLenum pname, GLfloat *params)
GL_API void GL_APIENTRY glGetLightfv (GLenum light, GLenum pname, GLfloat *params)
GL_API void GL_APIENTRY glGetMaterialfv (GLenum face, GLenum pname, GLfloat *params)
GL_API void GL_APIENTRY glGetTexEnvfv (GLenum env, GLenum pname, GLfloat *params)
GL_API void GL_APIENTRY glGetTexParameterfv (GLenum target, GLenum pname, GLfloat *params)
GL_API void GL_APIENTRY glLightModelf (GLenum pname, GLfloat param)
GL_API void GL_APIENTRY glLightModelfv (GLenum pname, const GLfloat *params)
GL_API void GL_APIENTRY glLightf (GLenum light, GLenum pname, GLfloat param)
GL_API void GL_APIENTRY glLightfv (GLenum light, GLenum pname, const GLfloat *params)
GL_API void GL_APIENTRY glLineWidth (GLfloat width)
GL_API void GL_APIENTRY glLoadMatrixf (const GLfloat *m)
GL_API void GL_APIENTRY glMaterialf (GLenum face, GLenum pname, GLfloat param)
GL_API void GL_APIENTRY glMaterialfv (GLenum face, GLenum pname, const GLfloat *params)
GL_API void GL_APIENTRY glMultMatrixf (const GLfloat *m)
GL_API void GL_APIENTRY glMultiTexCoord4f (GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q)
GL_API void GL_APIENTRY glNormal3f (GLfloat nx, GLfloat ny, GLfloat nz)
GL_API void GL_APIENTRY glOrthof (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
GL_API void GL_APIENTRY glPointParameterf (GLenum pname, GLfloat param)
GL_API void GL_APIENTRY glPointParameterfv (GLenum pname, const GLfloat *params)
GL_API void GL_APIENTRY glPointSize (GLfloat size)
GL_API void GL_APIENTRY glPolygonOffset (GLfloat factor, GLfloat units)
GL_API void GL_APIENTRY glRotatef (GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
GL_API void GL_APIENTRY glScalef (GLfloat x, GLfloat y, GLfloat z)
GL_API void GL_APIENTRY glTexEnvf (GLenum target, GLenum pname, GLfloat param)
GL_API void GL_APIENTRY glTexEnvfv (GLenum target, GLenum pname, const GLfloat *params)
GL_API void GL_APIENTRY glTexParameterf (GLenum target, GLenum pname, GLfloat param)
GL_API void GL_APIENTRY glTexParameterfv (GLenum target, GLenum pname, const GLfloat *params)
GL_API void GL_APIENTRY glTranslatef (GLfloat x, GLfloat y, GLfloat z)
GL_API void GL_APIENTRY glActiveTexture (GLenum texture)
GL_API void GL_APIENTRY glAlphaFuncx (GLenum func, GLclampx ref)
GL_API void GL_APIENTRY glBindBuffer (GLenum target, GLuint buffer)
GL_API void GL_APIENTRY glBindTexture (GLenum target, GLuint texture)
GL_API void GL_APIENTRY glBlendFunc (GLenum sfactor, GLenum dfactor)
GL_API void GL_APIENTRY glBufferData (GLenum target, GLsizeiptr size, const GLvoid *data, GLenum usage)
GL_API void GL_APIENTRY glBufferSubData (GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid *data)
GL_API void GL_APIENTRY glClear (GLbitfield mask)
GL_API void GL_APIENTRY glClearColorx (GLclampx red, GLclampx green, GLclampx blue, GLclampx alpha)
GL_API void GL_APIENTRY glClearDepthx (GLclampx depth)
GL_API void GL_APIENTRY glClearStencil (GLint s)
GL_API void GL_APIENTRY glClientActiveTexture (GLenum texture)
GL_API void GL_APIENTRY glClipPlanex (GLenum plane, const GLfixed *equation)
GL_API void GL_APIENTRY glColor4ub (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
GL_API void GL_APIENTRY glColor4x (GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha)
GL_API void GL_APIENTRY glColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
GL_API void GL_APIENTRY glColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer)
GL_API void GL_APIENTRY glCompressedTexImage2D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid *data)
GL_API void GL_APIENTRY glCompressedTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid *data)
GL_API void GL_APIENTRY glCopyTexImage2D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
GL_API void GL_APIENTRY glCopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
GL_API void GL_APIENTRY glCullFace (GLenum mode)
GL_API void GL_APIENTRY glDeleteBuffers (GLsizei n, const GLuint *buffers)
GL_API void GL_APIENTRY glDeleteTextures (GLsizei n, const GLuint *textures)
GL_API void GL_APIENTRY glDepthFunc (GLenum func)
GL_API void GL_APIENTRY glDepthMask (GLboolean flag)
GL_API void GL_APIENTRY glDepthRangex (GLclampx zNear, GLclampx zFar)
GL_API void GL_APIENTRY glDisable (GLenum cap)
GL_API void GL_APIENTRY glDisableClientState (GLenum array)
GL_API void GL_APIENTRY glDrawArrays (GLenum mode, GLint first, GLsizei count)
GL_API void GL_APIENTRY glDrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices)
GL_API void GL_APIENTRY glEnable (GLenum cap)
GL_API void GL_APIENTRY glEnableClientState (GLenum array)
GL_API void GL_APIENTRY glFinish (void)
GL_API void GL_APIENTRY glFlush (void)
GL_API void GL_APIENTRY glFogx (GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glFogxv (GLenum pname, const GLfixed *params)
GL_API void GL_APIENTRY glFrontFace (GLenum mode)
GL_API void GL_APIENTRY glFrustumx (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
GL_API void GL_APIENTRY glGetBooleanv (GLenum pname, GLboolean *params)
GL_API void GL_APIENTRY glGetBufferParameteriv (GLenum target, GLenum pname, GLint *params)
GL_API void GL_APIENTRY glGetClipPlanex (GLenum pname, GLfixed eqn[4])
GL_API void GL_APIENTRY glGenBuffers (GLsizei n, GLuint *buffers)
GL_API void GL_APIENTRY glGenTextures (GLsizei n, GLuint *textures)
GL_API GLenum GL_APIENTRY glGetError (void)
GL_API void GL_APIENTRY glGetFixedv (GLenum pname, GLfixed *params)
GL_API void GL_APIENTRY glGetIntegerv (GLenum pname, GLint *params)
GL_API void GL_APIENTRY glGetLightxv (GLenum light, GLenum pname, GLfixed *params)
GL_API void GL_APIENTRY glGetMaterialxv (GLenum face, GLenum pname, GLfixed *params)
GL_API void GL_APIENTRY glGetPointerv (GLenum pname, void **params)
GL_API const GLubyte *GL_APIENTRY glGetString (GLenum name)
GL_API void GL_APIENTRY glGetTexEnviv (GLenum env, GLenum pname, GLint *params)
GL_API void GL_APIENTRY glGetTexEnvxv (GLenum env, GLenum pname, GLfixed *params)
GL_API void GL_APIENTRY glGetTexParameteriv (GLenum target, GLenum pname, GLint *params)
GL_API void GL_APIENTRY glGetTexParameterxv (GLenum target, GLenum pname, GLfixed *params)
GL_API void GL_APIENTRY glHint (GLenum target, GLenum mode)
GL_API GLboolean GL_APIENTRY glIsBuffer (GLuint buffer)
GL_API GLboolean GL_APIENTRY glIsEnabled (GLenum cap)
GL_API GLboolean GL_APIENTRY glIsTexture (GLuint texture)
GL_API void GL_APIENTRY glLightModelx (GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glLightModelxv (GLenum pname, const GLfixed *params)
GL_API void GL_APIENTRY glLightx (GLenum light, GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glLightxv (GLenum light, GLenum pname, const GLfixed *params)
GL_API void GL_APIENTRY glLineWidthx (GLfixed width)
GL_API void GL_APIENTRY glLoadIdentity (void)
GL_API void GL_APIENTRY glLoadMatrixx (const GLfixed *m)
GL_API void GL_APIENTRY glLogicOp (GLenum opcode)
GL_API void GL_APIENTRY glMaterialx (GLenum face, GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glMaterialxv (GLenum face, GLenum pname, const GLfixed *params)
GL_API void GL_APIENTRY glMatrixMode (GLenum mode)
GL_API void GL_APIENTRY glMultMatrixx (const GLfixed *m)
GL_API void GL_APIENTRY glMultiTexCoord4x (GLenum target, GLfixed s, GLfixed t, GLfixed r, GLfixed q)
GL_API void GL_APIENTRY glNormal3x (GLfixed nx, GLfixed ny, GLfixed nz)
GL_API void GL_APIENTRY glNormalPointer (GLenum type, GLsizei stride, const GLvoid *pointer)
GL_API void GL_APIENTRY glOrthox (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
GL_API void GL_APIENTRY glPixelStorei (GLenum pname, GLint param)
GL_API void GL_APIENTRY glPointParameterx (GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glPointParameterxv (GLenum pname, const GLfixed *params)
GL_API void GL_APIENTRY glPointSizex (GLfixed size)
GL_API void GL_APIENTRY glPolygonOffsetx (GLfixed factor, GLfixed units)
GL_API void GL_APIENTRY glPopMatrix (void)
GL_API void GL_APIENTRY glPushMatrix (void)
GL_API void GL_APIENTRY glReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels)
GL_API void GL_APIENTRY glRotatex (GLfixed angle, GLfixed x, GLfixed y, GLfixed z)
GL_API void GL_APIENTRY glSampleCoverage (GLclampf value, GLboolean invert)
GL_API void GL_APIENTRY glSampleCoveragex (GLclampx value, GLboolean invert)
GL_API void GL_APIENTRY glScalex (GLfixed x, GLfixed y, GLfixed z)
GL_API void GL_APIENTRY glScissor (GLint x, GLint y, GLsizei width, GLsizei height)
GL_API void GL_APIENTRY glShadeModel (GLenum mode)
GL_API void GL_APIENTRY glStencilFunc (GLenum func, GLint ref, GLuint mask)
GL_API void GL_APIENTRY glStencilMask (GLuint mask)
GL_API void GL_APIENTRY glStencilOp (GLenum fail, GLenum zfail, GLenum zpass)
GL_API void GL_APIENTRY glTexCoordPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer)
GL_API void GL_APIENTRY glTexEnvi (GLenum target, GLenum pname, GLint param)
GL_API void GL_APIENTRY glTexEnvx (GLenum target, GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glTexEnviv (GLenum target, GLenum pname, const GLint *params)
GL_API void GL_APIENTRY glTexEnvxv (GLenum target, GLenum pname, const GLfixed *params)
GL_API void GL_APIENTRY glTexImage2D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
GL_API void GL_APIENTRY glTexParameteri (GLenum target, GLenum pname, GLint param)
GL_API void GL_APIENTRY glTexParameterx (GLenum target, GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glTexParameteriv (GLenum target, GLenum pname, const GLint *params)
GL_API void GL_APIENTRY glTexParameterxv (GLenum target, GLenum pname, const GLfixed *params)
GL_API void GL_APIENTRY glTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)
GL_API void GL_APIENTRY glTranslatex (GLfixed x, GLfixed y, GLfixed z)
GL_API void GL_APIENTRY glVertexPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer)
GL_API void GL_APIENTRY glViewport (GLint x, GLint y, GLsizei width, GLsizei height)
GL_API void GL_APIENTRY glPointSizePointerOES (GLenum type, GLsizei stride, const GLvoid *pointer)
Typedef Documentation
typedef unsigned int GLbitfield
Definition at line 18 of file flash/GLES/gl.h.
typedef GLboolean
Definition at line 17 of file flash/GLES/gl.h.
typedef khronos_int8_t GLbyte
Definition at line 19 of file flash/GLES/gl.h.
typedef khronos_float_t GLclampf
Definition at line 27 of file flash/GLES/gl.h.
typedef khronos_int32_t GLclampx
Definition at line 29 of file flash/GLES/gl.h.
typedef GLenum
Definition at line 16 of file flash/GLES/gl.h.
typedef khronos_int32_t GLfixed
Definition at line 28 of file flash/GLES/gl.h.
typedef khronos_float_t GLfloat
Definition at line 26 of file flash/GLES/gl.h.
typedef GLint
Definition at line 21 of file flash/GLES/gl.h.
typedef khronos_intptr_t GLintptr
Definition at line 31 of file flash/GLES/gl.h.
typedef short GLshort
Definition at line 20 of file flash/GLES/gl.h.
typedef int GLsizei
Definition at line 22 of file flash/GLES/gl.h.
typedef khronos_ssize_t GLsizeiptr
Definition at line 32 of file flash/GLES/gl.h.
typedef khronos_uint8_t GLubyte
Definition at line 23 of file flash/GLES/gl.h.
typedef GLuint
Definition at line 25 of file flash/GLES/gl.h.
typedef unsigned short GLushort
Definition at line 24 of file flash/GLES/gl.h.
typedef void GLvoid
Definition at line 15 of file flash/GLES/gl.h.
Function Documentation
GL_API void GL_APIENTRY glActiveTexture (GLenum texture)
Definition at line 1621 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glAlphaFunc (GLenum func, GLclampf ref)
Definition at line 1588 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glAlphaFuncx (GLenum func, GLclampx ref)
GL_API void GL_APIENTRY glBindBuffer (GLenum target, GLuint buffer)
Definition at line 521 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glBindTexture (GLenum target, GLuint texture)
Definition at line 708 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glBlendFunc (GLenum sfactor, GLenum dfactor)
Definition at line 747 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glBufferData (GLenum target, GLsizeiptr size, const GLvoid * data, GLenum usage)
Definition at line 894 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glBufferSubData (GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid * data)
GL_API void GL_APIENTRY glClear (GLbitfield mask)
Definition at line 168 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
Definition at line 158 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glClearColorx (GLclampx red, GLclampx green, GLclampx blue, GLclampx alpha)
GL_API void GL_APIENTRY glClearDepthf (GLclampf depth)
GL_API void GL_APIENTRY glClearDepthx (GLclampx depth)
GL_API void GL_APIENTRY glClearStencil (GLint s)
GL_API void GL_APIENTRY glClientActiveTexture (GLenum texture)
Definition at line 1631 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glClipPlanef (GLenum plane, const GLfloat * equation)
Definition at line 1469 of file GLFlashAdaptor.cpp.
References LogMsg().
GL_API void GL_APIENTRY glClipPlanex (GLenum plane, const GLfixed * equation)
GL_API void GL_APIENTRY glColor4f (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
Definition at line 498 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glColor4ub (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
Definition at line 510 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glColor4x (GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha)
Definition at line 516 of file GLFlashAdaptor.cpp.
References glColor4f().
Referenced by Surface::ApplyBlendingMode(), DrawEllipse(), DrawLine(), RenderBatcher::Flush(), RenderBatcher::Flush3D(), GenerateFillRect(), BaseApp::InitializeGLDefaults(), Surface::RemoveBlendingMode(), and RenderGLTriangle().
GL_API void GL_APIENTRY glColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
Definition at line 1614 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer)
Definition at line 656 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glCompressedTexImage2D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid * data)
GL_API void GL_APIENTRY glCompressedTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid * data)
GL_API void GL_APIENTRY glCopyTexImage2D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
GL_API void GL_APIENTRY glCopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
Definition at line 1607 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glCullFace (GLenum mode)
Definition at line 733 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glDeleteBuffers (GLsizei n, const GLuint * buffers)
Definition at line 934 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glDeleteTextures (GLsizei n, const GLuint * textures)
Definition at line 817 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glDepthFunc (GLenum func)
Definition at line 719 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glDepthMask (GLboolean flag)
Definition at line 724 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glDepthRangef (GLclampf zNear, GLclampf zFar)
Definition at line 742 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glDepthRangex (GLclampx zNear, GLclampx zFar)
GL_API void GL_APIENTRY glDisable (GLenum cap)
Definition at line 462 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glDisableClientState (GLenum array)
Definition at line 493 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glDrawArrays (GLenum mode, GLint first, GLsizei count)
Definition at line 1454 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glDrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid * indices)
Definition at line 1449 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glEnable (GLenum cap)
Definition at line 467 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glEnableClientState (GLenum array)
Definition at line 488 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glFinish (void)
Referenced by main().
GL_API void GL_APIENTRY glFlush (void)
Referenced by main().
GL_API void GL_APIENTRY glFogf (GLenum pname, GLfloat param)
GL_API void GL_APIENTRY glFogfv (GLenum pname, const GLfloat * params)
GL_API void GL_APIENTRY glFogx (GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glFogxv (GLenum pname, const GLfixed * params)
GL_API void GL_APIENTRY glFrontFace (GLenum mode)
Definition at line 360 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glFrustumf (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
Definition at line 1595 of file GLFlashAdaptor.cpp.
References g_pActiveStack.
GL_API void GL_APIENTRY glFrustumx (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
GL_API void GL_APIENTRY glGenBuffers (GLsizei n, GLuint * buffers)
Definition at line 915 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glGenTextures (GLsizei n, GLuint * textures)
Definition at line 951 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glGetBooleanv (GLenum pname, GLboolean * params)
Definition at line 1475 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glGetBufferParameteriv (GLenum target, GLenum pname, GLint * params)
GL_API void GL_APIENTRY glGetClipPlanef (GLenum pname, GLfloat eqn[4])
GL_API void GL_APIENTRY glGetClipPlanex (GLenum pname, GLfixed eqn[4])
GL_API GLenum GL_APIENTRY glGetError (void)
Definition at line 213 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glGetFixedv (GLenum pname, GLfixed * params)
GL_API void GL_APIENTRY glGetFloatv (GLenum pname, GLfloat * params)
Definition at line 572 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glGetIntegerv (GLenum pname, GLint * params)
Definition at line 548 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glGetLightfv (GLenum light, GLenum pname, GLfloat * params)
GL_API void GL_APIENTRY glGetLightxv (GLenum light, GLenum pname, GLfixed * params)
GL_API void GL_APIENTRY glGetMaterialfv (GLenum face, GLenum pname, GLfloat * params)
GL_API void GL_APIENTRY glGetMaterialxv (GLenum face, GLenum pname, GLfixed * params)
GL_API void GL_APIENTRY glGetPointerv (GLenum pname, void ** params)
GL_API const GLubyte* GL_APIENTRY glGetString (GLenum name)
Definition at line 589 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glGetTexEnvfv (GLenum env, GLenum pname, GLfloat * params)
GL_API void GL_APIENTRY glGetTexEnviv (GLenum env, GLenum pname, GLint * params)
GL_API void GL_APIENTRY glGetTexEnvxv (GLenum env, GLenum pname, GLfixed * params)
GL_API void GL_APIENTRY glGetTexParameterfv (GLenum target, GLenum pname, GLfloat * params)
GL_API void GL_APIENTRY glGetTexParameteriv (GLenum target, GLenum pname, GLint * params)
GL_API void GL_APIENTRY glGetTexParameterxv (GLenum target, GLenum pname, GLfixed * params)
GL_API void GL_APIENTRY glHint (GLenum target, GLenum mode)
Definition at line 714 of file GLFlashAdaptor.cpp.
GL_API GLboolean GL_APIENTRY glIsBuffer (GLuint buffer)
GL_API GLboolean GL_APIENTRY glIsEnabled (GLenum cap)
GL_API GLboolean GL_APIENTRY glIsTexture (GLuint texture)
GL_API void GL_APIENTRY glLightf (GLenum light, GLenum pname, GLfloat param)
Definition at line 1513 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glLightfv (GLenum light, GLenum pname, const GLfloat * params)
Definition at line 1520 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glLightModelf (GLenum pname, GLfloat param)
Definition at line 1641 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glLightModelfv (GLenum pname, const GLfloat * params)
Definition at line 1647 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glLightModelx (GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glLightModelxv (GLenum pname, const GLfixed * params)
GL_API void GL_APIENTRY glLightx (GLenum light, GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glLightxv (GLenum light, GLenum pname, const GLfixed * params)
GL_API void GL_APIENTRY glLineWidth (GLfloat width)
Definition at line 1041 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glLineWidthx (GLfixed width)
GL_API void GL_APIENTRY glLoadIdentity (void)
Definition at line 677 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glLoadMatrixf (const GLfloat * m)
Definition at line 682 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glLoadMatrixx (const GLfixed * m)
GL_API void GL_APIENTRY glLogicOp (GLenum opcode)
GL_API void GL_APIENTRY glMaterialf (GLenum face, GLenum pname, GLfloat param)
Definition at line 1506 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glMaterialfv (GLenum face, GLenum pname, const GLfloat * params)
Definition at line 1499 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glMaterialx (GLenum face, GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glMaterialxv (GLenum face, GLenum pname, const GLfixed * params)
GL_API void GL_APIENTRY glMatrixMode (GLenum mode)
Definition at line 598 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glMultiTexCoord4f (GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q)
GL_API void GL_APIENTRY glMultiTexCoord4x (GLenum target, GLfixed s, GLfixed t, GLfixed r, GLfixed q)
GL_API void GL_APIENTRY glMultMatrixf (const GLfloat * m)
Definition at line 807 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glMultMatrixx (const GLfixed * m)
GL_API void GL_APIENTRY glNormal3f (GLfloat nx, GLfloat ny, GLfloat nz)
GL_API void GL_APIENTRY glNormal3x (GLfixed nx, GLfixed ny, GLfixed nz)
GL_API void GL_APIENTRY glNormalPointer (GLenum type, GLsizei stride, const GLvoid * pointer)
Definition at line 666 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glOrthof (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
Definition at line 812 of file GLFlashAdaptor.cpp.
References g_pActiveStack.
Referenced by RemoveOrthoRenderSize(), SetOrthoRenderSize(), and SetupOrtho().
GL_API void GL_APIENTRY glOrthox (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
GL_API void GL_APIENTRY glPixelStorei (GLenum pname, GLint param)
GL_API void GL_APIENTRY glPointParameterf (GLenum pname, GLfloat param)
GL_API void GL_APIENTRY glPointParameterfv (GLenum pname, const GLfloat * params)
GL_API void GL_APIENTRY glPointParameterx (GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glPointParameterxv (GLenum pname, const GLfixed * params)
GL_API void GL_APIENTRY glPointSize (GLfloat size)
GL_API void GL_APIENTRY glPointSizePointerOES (GLenum type, GLsizei stride, const GLvoid * pointer)
Referenced by L_ParticleEffect::RenderPointSprites().
GL_API void GL_APIENTRY glPointSizex (GLfixed size)
GL_API void GL_APIENTRY glPolygonOffset (GLfloat factor, GLfloat units)
Definition at line 1600 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glPolygonOffsetx (GLfixed factor, GLfixed units)
GL_API void GL_APIENTRY glPopMatrix (void)
Definition at line 765 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glPushMatrix (void)
Definition at line 687 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels)
Definition at line 702 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glRotatef (GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
Definition at line 692 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glRotatex (GLfixed angle, GLfixed x, GLfixed y, GLfixed z)
GL_API void GL_APIENTRY glSampleCoverage (GLclampf value, GLboolean invert)
GL_API void GL_APIENTRY glSampleCoveragex (GLclampx value, GLboolean invert)
GL_API void GL_APIENTRY glScalef (GLfloat x, GLfloat y, GLfloat z)
Definition at line 697 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glScalex (GLfixed x, GLfixed y, GLfixed z)
GL_API void GL_APIENTRY glScissor (GLint x, GLint y, GLsizei width, GLsizei height)
Definition at line 1460 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glShadeModel (GLenum mode)
Definition at line 1491 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glStencilFunc (GLenum func, GLint ref, GLuint mask)
GL_API void GL_APIENTRY glStencilMask (GLuint mask)
GL_API void GL_APIENTRY glStencilOp (GLenum fail, GLenum zfail, GLenum zpass)
GL_API void GL_APIENTRY glTexCoordPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer)
Definition at line 644 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glTexEnvf (GLenum target, GLenum pname, GLfloat param)
GL_API void GL_APIENTRY glTexEnvfv (GLenum target, GLenum pname, const GLfloat * params)
GL_API void GL_APIENTRY glTexEnvi (GLenum target, GLenum pname, GLint param)
Definition at line 1655 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glTexEnviv (GLenum target, GLenum pname, const GLint * params)
GL_API void GL_APIENTRY glTexEnvx (GLenum target, GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glTexEnvxv (GLenum target, GLenum pname, const GLfixed * params)
GL_API void GL_APIENTRY glTexImage2D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
Definition at line 969 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glTexParameterf (GLenum target, GLenum pname, GLfloat param)
Definition at line 792 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glTexParameterfv (GLenum target, GLenum pname, const GLfloat * params)
Definition at line 800 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glTexParameteri (GLenum target, GLenum pname, GLint param)
Definition at line 776 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glTexParameteriv (GLenum target, GLenum pname, const GLint * params)
GL_API void GL_APIENTRY glTexParameterx (GLenum target, GLenum pname, GLfixed param)
Definition at line 784 of file GLFlashAdaptor.cpp.
Referenced by Surface::SetSmoothing().
GL_API void GL_APIENTRY glTexParameterxv (GLenum target, GLenum pname, const GLfixed * params)
GL_API void GL_APIENTRY glTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels)
Definition at line 1046 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glTranslatef (GLfloat x, GLfloat y, GLfloat z)
Definition at line 593 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glTranslatex (GLfixed x, GLfixed y, GLfixed z)
GL_API void GL_APIENTRY glVertexPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer)
Definition at line 639 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glViewport (GLint x, GLint y, GLsizei width, GLsizei height)
Referenced by AppRender().