Proton: GLESUtils.cpp File Reference
GLESUtils.cpp File Reference
Functions
void GenerateFillRect (GLuint rgba, float x, float y, float w, float h)
void gluLookAt (GLfloat eyex, GLfloat eyey, GLfloat eyez, GLfloat centerx, GLfloat centery, GLfloat centerz, GLfloat upx, GLfloat upy, GLfloat upz)
void SetExtraScreenRotationDegrees (float degrees)
float OrientationToDegrees (int orientation)
void RotateGLIfNeeded ()
void RotateGLIfNeeded (CL_Mat4f &mat)
void GenerateSetPerspectiveFOV (float fovy, float aspect, float zNear, float zFar)
void DrawFilledSquare (float x, float y, float size, uint32 color, bool bCentered)
void DrawFilledRect (const CL_Rectf &r, uint32 color)
void DrawFilledRect (rtRectf &r, uint32 color)
void DrawFilledRect (rtRect &r, uint32 color)
void DrawFilledRect (float x, float y, float sizeX, float sizeY, uint32 color)
void DrawFilledRect (CL_Vec2f vPos, CL_Vec2f vSize, uint32 color)
void DrawRect (const CL_Rectf &r, uint32 color, float lineWidth)
void DrawFilledBitmapRect (rtRect &r, uint32 middleColor, uint32 borderColor, SurfaceAnim *pSurf, bool bFillMiddleCloserToEdges)
void DrawFilledBitmapRect (const CL_Rectf &r, uint32 middleColor, uint32 borderColor, SurfaceAnim *pSurf, bool bFillMiddleCloserToEdges)
void DrawRect (const rtRect &r, uint32 color, float lineWidth)
void DrawRect (const rtRectf &r, uint32 color, float lineWidth)
void DrawRect (float x, float y, float width, float height, uint32 color, float lineWidth)
void DrawEllipse (const int segments, CL_Vec2f vPos, float radianWidth, float radiusHeight, bool vFilled, uint32 color)
void DrawRect (CL_Vec2f &vPos, CL_Vec2f &vSize, uint32 color, float lineWidth)
void DrawLine (GLuint rgba, float ax, float ay, float bx, float by, float lineWidth)
void PushRotationMatrix (float rotationDegrees, CL_Vec2f vRotatePt)
void PopRotationMatrix ()
void SetOrthoRenderSize (float x, float y, int screenOffsetX, int screenOffsetY)
void RemoveOrthoRenderSize ()
void SetupOrtho ()
void PrepareForGL ()
void transform_point (GLfloat out[4], const GLfloat m[16], const GLfloat in[4])
static void matmul (GLfloat *product, const GLfloat *a, const GLfloat *b)
static GLboolean invert_matrix (const GLfloat *m, GLfloat *out)
GLint gluProject (GLfloat objx, GLfloat objy, GLfloat objz, const GLfloat model[16], const GLfloat proj[16], const GLint viewport[4], GLfloat *winx, GLfloat *winy, GLfloat *winz)
GLint gluUnProject (GLfloat winx, GLfloat winy, GLfloat winz, const GLfloat model[16], const GLfloat proj[16], const GLint viewport[4], GLfloat *objx, GLfloat *objy, GLfloat *objz)
GLint gluUnProject4 (GLfloat winx, GLfloat winy, GLfloat winz, GLfloat clipw, const GLfloat modelMatrix[16], const GLfloat projMatrix[16], const GLint viewport[4], GLclampf nearZ, GLclampf farZ, GLfloat *objx, GLfloat *objy, GLfloat *objz, GLfloat *objw)
float GetOrthoRenderSizeXf ()
float GetOrthoRenderSizeYf ()
Variables
float g_renderOrthoRenderSizeX
float g_renderOrthoRenderSizeY
float g_extraScreenRotation = 0
bool g_OrthoRenderSizeActive = false
Function Documentation
void DrawEllipse (const int segments, CL_Vec2f vPos, float radianWidth, float radiusHeight, bool vFilled, uint32 color)
Definition at line 287 of file GLESUtils.cpp.
References glColor4x(), glDisable(), glDisableClientState(), glDrawArrays(), glEnable(), glEnableClientState(), glPopMatrix(), glPushMatrix(), glTranslatef(), glVertexPointer(), and SetupOrtho().
void DrawFilledBitmapRect (rtRect & r, uint32 middleColor, uint32 borderColor, SurfaceAnim * pSurf, bool bFillMiddleCloserToEdges)
Definition at line 229 of file GLESUtils.cpp.
References rtRect::bottom, DrawFilledBitmapRect(), rtRect::left, rtRect::right, and rtRect::top.
Referenced by DrawFilledBitmapRect().
void DrawFilledBitmapRect (const CL_Rectf & r, uint32 middleColor, uint32 borderColor, SurfaceAnim * pSurf, bool bFillMiddleCloserToEdges)
Definition at line 234 of file GLESUtils.cpp.
References ALIGNMENT_UPPER_LEFT, SurfaceAnim::BlitAnim(), SurfaceAnim::BlitScaledAnim(), DrawFilledRect(), SurfaceAnim::GetFramesX(), and SurfaceAnim::GetFramesY().
void DrawFilledRect (const CL_Rectf & r, uint32 color)
Definition at line 199 of file GLESUtils.cpp.
References GenerateFillRect().
Referenced by DrawFilledBitmapRect(), RTFont::DrawWrapped(), ProtonPainter::FillRect(), ProtonPainter::InvertRect(), and AdManager::OnRender().
void DrawFilledRect (rtRectf & r, uint32 color)
Definition at line 204 of file GLESUtils.cpp.
References GenerateFillRect(), rtRectf::GetHeight(), rtRectf::GetWidth(), rtRectf::left, and rtRectf::top.
void DrawFilledRect (rtRect & r, uint32 color)
Definition at line 209 of file GLESUtils.cpp.
References GenerateFillRect(), rtRect::GetHeight(), rtRect::GetWidth(), rtRect::left, and rtRect::top.
void DrawFilledRect (float x, float y, float sizeX, float sizeY, uint32 color)
Definition at line 214 of file GLESUtils.cpp.
References GenerateFillRect().
void DrawFilledRect (CL_Vec2f vPos, CL_Vec2f vSize, uint32 color)
Definition at line 219 of file GLESUtils.cpp.
References GenerateFillRect().
void DrawFilledSquare (float x, float y, float size, uint32 color, bool bCentered)
Definition at line 189 of file GLESUtils.cpp.
References GenerateFillRect().
void DrawLine (GLuint rgba, float ax, float ay, float bx, float by, float lineWidth)
Definition at line 336 of file GLESUtils.cpp.
References glColor4x(), glDisable(), glDisableClientState(), glDrawArrays(), glEnable(), glEnableClientState(), glHint(), glLineWidth(), glVertexPointer(), and SetupOrtho().
void DrawRect (const CL_Rectf & r, uint32 color, float lineWidth)
Definition at line 224 of file GLESUtils.cpp.
References DrawRect().
Referenced by DrawRect().
void DrawRect (const rtRect & r, uint32 color, float lineWidth)
Definition at line 267 of file GLESUtils.cpp.
References DrawRect(), rtRect::GetHeight(), rtRect::GetWidth(), rtRect::left, and rtRect::top.
void DrawRect (const rtRectf & r, uint32 color, float lineWidth)
Definition at line 271 of file GLESUtils.cpp.
References DrawRect(), rtRectf::GetHeight(), rtRectf::GetWidth(), rtRectf::left, and rtRectf::top.
void DrawRect (float x, float y, float width, float height, uint32 color, float lineWidth)
Definition at line 277 of file GLESUtils.cpp.
References GenerateFillRect().
void DrawRect (CL_Vec2f & vPos, CL_Vec2f & vSize, uint32 color, float lineWidth)
Definition at line 328 of file GLESUtils.cpp.
References DrawRect().
void GenerateFillRect (GLuint rgba, float x, float y, float w, float h)
Definition at line 440 of file GLESUtils.cpp.
References GetBaseApp(), glColor4x(), glDisable(), glDisableClientState(), glDrawArrays(), glEnable(), glEnableClientState(), glVertexPointer(), and SetupOrtho().
Referenced by DrawFilledRect(), DrawFilledSquare(), and DrawRect().
void GenerateSetPerspectiveFOV (float fovy, float aspect, float zNear, float zFar)
Definition at line 161 of file GLESUtils.cpp.
References GetBaseApp(), BaseApp::GetProjectionMatrix(), glLoadIdentity(), glLoadMatrixf(), glMatrixMode(), PrepareForGL(), and RotateGLIfNeeded().
Referenced by BaseApp::OnScreenSizeChange().
float GetOrthoRenderSizeXf ()
Definition at line 988 of file GLESUtils.cpp.
References g_renderOrthoRenderSizeX.
float GetOrthoRenderSizeYf ()
Definition at line 993 of file GLESUtils.cpp.
References g_renderOrthoRenderSizeY.
Referenced by RenderBatcher::BlitEx(), and Surface::BlitEx().
void gluLookAt (GLfloat eyex, GLfloat eyey, GLfloat eyez, GLfloat centerx, GLfloat centery, GLfloat centerz, GLfloat upx, GLfloat upy, GLfloat upz)
Definition at line 11 of file GLESUtils.cpp.
References glMultMatrixf(), and glTranslatef().
GLint gluProject (GLfloat objx, GLfloat objy, GLfloat objz, const GLfloat model[16], const GLfloat proj[16], const GLint viewport[4], GLfloat * winx, GLfloat * winy, GLfloat * winz)
Definition at line 884 of file GLESUtils.cpp.
References transform_point().
GLint gluUnProject (GLfloat winx, GLfloat winy, GLfloat winz, const GLfloat model[16], const GLfloat proj[16], const GLint viewport[4], GLfloat * objx, GLfloat * objy, GLfloat * objz)
Definition at line 919 of file GLESUtils.cpp.
References invert_matrix(), matmul(), and transform_point().
Referenced by GetOGLPos().
GLint gluUnProject4 (GLfloat winx, GLfloat winy, GLfloat winz, GLfloat clipw, const GLfloat modelMatrix[16], const GLfloat projMatrix[16], const GLint viewport[4], GLclampf nearZ, GLclampf farZ, GLfloat * objx, GLfloat * objy, GLfloat * objz, GLfloat * objw)
Definition at line 954 of file GLESUtils.cpp.
References invert_matrix(), matmul(), and transform_point().
static GLboolean invert_matrix (const GLfloat * m, GLfloat * out) [static]
Definition at line 708 of file GLESUtils.cpp.
Referenced by gluUnProject(), and gluUnProject4().
static void matmul (GLfloat * product, const GLfloat * a, const GLfloat * b) [static]
Definition at line 664 of file GLESUtils.cpp.
Referenced by gluUnProject(), and gluUnProject4().
float OrientationToDegrees (int orientation)
Definition at line 104 of file GLESUtils.cpp.
References GetOrientation(), ORIENTATION_DONT_CARE, ORIENTATION_LANDSCAPE_LEFT, ORIENTATION_LANDSCAPE_RIGHT, ORIENTATION_PORTRAIT, and ORIENTATION_PORTRAIT_UPSIDE_DOWN.
Referenced by RenderScissorComponent::FilterOnRender(), and RotateGLIfNeeded().
void PopRotationMatrix ()
Definition at line 497 of file GLESUtils.cpp.
References glPopMatrix().
Referenced by Surface::EndRender().
void PrepareForGL ()
Definition at line 616 of file GLESUtils.cpp.
References RenderBatcher::Flush(), g_globalBatcher, glCullFace(), glDepthMask(), glEnable(), glLoadIdentity(), glMatrixMode(), glPopMatrix(), NeedsOrthoSet(), and ResetOrthoFlag().
Referenced by IrrlichtManager::BeginScene(), GenerateSetPerspectiveFOV(), RedoFakeScreenSize(), and UndoFakeScreenSize().
void PushRotationMatrix (float rotationDegrees, CL_Vec2f vRotatePt)
Definition at line 490 of file GLESUtils.cpp.
References glPushMatrix(), glRotatef(), and glTranslatef().
Referenced by Surface::SetupForRender().
void RemoveOrthoRenderSize ()
Definition at line 535 of file GLESUtils.cpp.
References RenderBatcher::Flush(), g_globalBatcher, g_renderOrthoRenderSizeX, g_renderOrthoRenderSizeY, GetScreenSizeXf(), GetScreenSizeYf(), glLoadIdentity(), glMatrixMode(), glOrthof(), glPopMatrix(), glPushMatrix(), NeedsOrthoSet(), and RotateGLIfNeeded().
Referenced by SetOrthoRenderSize().
void RotateGLIfNeeded ()
Definition at line 128 of file GLESUtils.cpp.
References g_extraScreenRotation, GetBaseApp(), GetOrientation(), glRotatef(), and OrientationToDegrees().
Referenced by GenerateSetPerspectiveFOV(), RemoveOrthoRenderSize(), SetOrthoRenderSize(), and SetupOrtho().
void RotateGLIfNeeded (CL_Mat4f & mat)
Definition at line 145 of file GLESUtils.cpp.
References g_extraScreenRotation, GetBaseApp(), GetOrientation(), and OrientationToDegrees().
void SetExtraScreenRotationDegrees (float degrees)
Definition at line 98 of file GLESUtils.cpp.
References g_extraScreenRotation.
void SetOrthoRenderSize (float x, float y, int screenOffsetX, int screenOffsetY)
Definition at line 505 of file GLESUtils.cpp.
References g_renderOrthoRenderSizeX, g_renderOrthoRenderSizeY, glLoadIdentity(), glMatrixMode(), glOrthof(), glPopMatrix(), glPushMatrix(), RemoveOrthoRenderSize(), RotateGLIfNeeded(), and SetupOrtho().
void SetupOrtho ()
Definition at line 559 of file GLESUtils.cpp.
References RenderBatcher::Flush(), g_globalBatcher, g_renderOrthoRenderSizeX, g_renderOrthoRenderSizeY, GetScreenSizeXf(), GetScreenSizeYf(), glCullFace(), glDepthMask(), glDisable(), glDisableClientState(), glEnable(), glEnableClientState(), glFrontFace(), glLoadIdentity(), glMatrixMode(), glOrthof(), glPushMatrix(), NeedsOrthoSet(), RotateGLIfNeeded(), and SetOrthoModeFlag().
Referenced by RenderBatcher::BlitRawImage(), BaseApp::Draw(), DrawEllipse(), DrawLine(), RTFont::DrawScaled(), RTFont::DrawScaledSolidColor(), GenerateFillRect(), SetOrthoRenderSize(), and Surface::SetupForRender().
void transform_point (GLfloat out[4], const GLfloat m[16], const GLfloat in[4])
Definition at line 641 of file GLESUtils.cpp.
Referenced by gluProject(), gluUnProject(), and gluUnProject4().
Variable Documentation
float g_extraScreenRotation = 0
Definition at line 97 of file GLESUtils.cpp.
Referenced by RotateGLIfNeeded(), and SetExtraScreenRotationDegrees().
bool g_OrthoRenderSizeActive = false
Definition at line 503 of file GLESUtils.cpp.
float g_renderOrthoRenderSizeX
Definition at line 6 of file GLESUtils.cpp.
Referenced by GetOrthoRenderSizeXf(), RemoveOrthoRenderSize(), SetOrthoRenderSize(), and SetupOrtho().
float g_renderOrthoRenderSizeY
Definition at line 7 of file GLESUtils.cpp.
Referenced by GetOrthoRenderSizeYf(), RemoveOrthoRenderSize(), SetOrthoRenderSize(), and SetupOrtho().