Proton: GLFlashAdaptor.h File Reference
GLFlashAdaptor.h File Reference
Functions
bool GLFlashAdaptor_Initialize ()
GL_API void GL_APIENTRY glVertexPointerEx (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer, int vertCount)
Function Documentation
bool GLFlashAdaptor_Initialize ()
Definition at line 129 of file GLFlashAdaptor.cpp.
References g_modelStack, g_projectionStack, g_scissorRect, GetScreenSizeXf(), GetScreenSizeYf(), and LogMsg().
Referenced by main().
GL_API void GL_APIENTRY glVertexPointerEx (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer, int vertCount)
Definition at line 618 of file GLFlashAdaptor.cpp.
References C_PD_VERTEX, and LogError().
Referenced by glVertexPointer().