Proton: GLFlashAdaptor.cpp File Reference
GLFlashAdaptor.cpp File Reference
Enumerations
enum ePointerData {
C_PD_VERTEX, C_PD_TEX_UV, C_PD_VERT_COLORS, C_PD_NORMALS,
C_PD_COUNT
}
Functions
bool GLFlashAdaptor_Initialize ()
void GLResetFBOCaches ()
void GLFlashAdaptor_Kill ()
GL_API void GL_APIENTRY glClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
GL_API void GL_APIENTRY glClear (GLbitfield mask)
GL_API GLenum GL_APIENTRY glGetError (void)
void UpdateScissorRect ()
void UpdateDepthTest ()
void UpdateBlendModes ()
void UpdateCullingOptions ()
GL_API void GL_APIENTRY glFrontFace (GLenum mode)
void glEnableEx (GLenum cap, bool bSetting)
GL_API void GL_APIENTRY glDisable (GLenum cap)
GL_API void GL_APIENTRY glEnable (GLenum cap)
void glEnableClientStateEx (GLenum cap, bool bSetting)
GL_API void GL_APIENTRY glEnableClientState (GLenum array)
GL_API void GL_APIENTRY glDisableClientState (GLenum array)
GL_API void GL_APIENTRY glColor4f (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
GL_API void GL_APIENTRY glColor4ub (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
GL_API void GL_APIENTRY glColor4x (GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha)
GL_API void GL_APIENTRY glBindBuffer (GLenum target, GLuint buffer)
void SendTextureToFlash (int texSlot, bool bTextureActive, GLuint texID)
GL_API void GL_APIENTRY glGetIntegerv (GLenum pname, GLint *params)
GL_API void GL_APIENTRY glGetFloatv (GLenum pname, GLfloat *params)
GL_API const GLubyte *GL_APIENTRY glGetString (GLenum name)
GL_API void GL_APIENTRY glTranslatef (GLfloat x, GLfloat y, GLfloat z)
GL_API void GL_APIENTRY glMatrixMode (GLenum mode)
GL_API void GL_APIENTRY glVertexPointerEx (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer, int vertCount)
GL_API void GL_APIENTRY glVertexPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer)
GL_API void GL_APIENTRY glTexCoordPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer)
GL_API void GL_APIENTRY glColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer)
GL_API void GL_APIENTRY glNormalPointer (GLenum type, GLsizei stride, const GLvoid *pointer)
GL_API void GL_APIENTRY glLoadIdentity (void)
GL_API void GL_APIENTRY glLoadMatrixf (const GLfloat *m)
GL_API void GL_APIENTRY glPushMatrix (void)
GL_API void GL_APIENTRY glRotatef (GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
GL_API void GL_APIENTRY glScalef (GLfloat x, GLfloat y, GLfloat z)
GL_API void GL_APIENTRY glReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels)
GL_API void GL_APIENTRY glBindTexture (GLenum target, GLuint texture)
GL_API void GL_APIENTRY glHint (GLenum target, GLenum mode)
GL_API void GL_APIENTRY glDepthFunc (GLenum func)
GL_API void GL_APIENTRY glDepthMask (GLboolean flag)
GL_API void GL_APIENTRY glCullFace (GLenum mode)
GL_API void GL_APIENTRY glDepthRangef (GLclampf zNear, GLclampf zFar)
GL_API void GL_APIENTRY glBlendFunc (GLenum sfactor, GLenum dfactor)
GL_API void GL_APIENTRY glPopMatrix (void)
GL_API void GL_APIENTRY glTexParameteri (GLenum target, GLenum pname, GLint param)
GL_API void GL_APIENTRY glTexParameterx (GLenum target, GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glTexParameterf (GLenum target, GLenum pname, GLfloat param)
GL_API void GL_APIENTRY glTexParameterfv (GLenum target, GLenum pname, const GLfloat *params)
GL_API void GL_APIENTRY glMultMatrixf (const GLfloat *m)
GL_API void GL_APIENTRY glOrthof (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
GL_API void GL_APIENTRY glDeleteTextures (GLsizei n, const GLuint *textures)
void AttachVBONormalsToShader (GLuint vboIndex, int offsetInt)
void AttachVBOVertsToShader (GLuint vboIndex, int offsetInt)
void AttachVBOColorsToShader (GLuint vboIndex, int offsetInt)
void AttachVBOTexUVToShader (GLuint vboIndex, int offsetInt)
GL_API void GL_APIENTRY glBufferDataEx (GLenum target, GLsizeiptr size, const GLvoid *data, GLenum usage, int vertCount, int dataSizePerVertexInts)
GL_API void GL_APIENTRY glBufferData (GLenum target, GLsizeiptr size, const GLvoid *data, GLenum usage)
GL_API void GL_APIENTRY glBufferDataUV (GLenum target, GLsizeiptr size, const GLvoid *data, GLenum usage, int vertCount, int dataSizePerVertexInts)
GL_API void GL_APIENTRY glGenBuffers (GLsizei n, GLuint *buffers)
GL_API void GL_APIENTRY glDeleteBuffers (GLsizei n, const GLuint *buffers)
GL_API void GL_APIENTRY glGenTextures (GLsizei n, GLuint *textures)
GL_API void GL_APIENTRY glTexImage2D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
GL_API void GL_APIENTRY glLineWidth (GLfloat width)
GL_API void GL_APIENTRY glTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)
float * GenerateSmartBuffer (ePointerData pdType, int first, int count)
void CountUsedVertsInIndexBuffer (uint16 *pIndexBuff, int count, int *pLow, int *pHigh, int *pTotal)
GL_API void GL_APIENTRY glDrawArraysEx (GLenum mode, GLint first, GLsizei count, GLenum indexType, const GLvoid *pIndexBuff)
GL_API void GL_APIENTRY glDrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices)
GL_API void GL_APIENTRY glDrawArrays (GLenum mode, GLint first, GLsizei count)
GL_API void GL_APIENTRY glScissor (GLint x, GLint y, GLsizei width, GLsizei height)
GL_API void GL_APIENTRY glClipPlanef (GLenum plane, const GLfloat *equation)
GL_API void GL_APIENTRY glGetBooleanv (GLenum pname, GLboolean *params)
GL_API void GL_APIENTRY glShadeModel (GLenum mode)
GL_API void GL_APIENTRY glMaterialfv (GLenum face, GLenum pname, const GLfloat *params)
GL_API void GL_APIENTRY glMaterialf (GLenum face, GLenum pname, GLfloat param)
GL_API void GL_APIENTRY glLightf (GLenum light, GLenum pname, GLfloat param)
GL_API void GL_APIENTRY glLightfv (GLenum light, GLenum pname, const GLfloat *params)
GL_API void GL_APIENTRY glAlphaFunc (GLenum func, GLclampf ref)
GL_API void GL_APIENTRY glFrustumf (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
GL_API void GL_APIENTRY glPolygonOffset (GLfloat factor, GLfloat units)
GL_API void GL_APIENTRY glCopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
GL_API void GL_APIENTRY glColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
GL_API void GL_APIENTRY glActiveTexture (GLenum texture)
GL_API void GL_APIENTRY glClientActiveTexture (GLenum texture)
GL_API void GL_APIENTRY glLightModelf (GLenum pname, GLfloat param)
GL_API void GL_APIENTRY glLightModelfv (GLenum pname, const GLfloat *params)
GL_API void GL_APIENTRY glTexEnvi (GLenum target, GLenum pname, GLint param)
Variables
GLclampf g_glClearColorR = 0
GLclampf g_glClearColorB = 0
GLclampf g_glClearColorG = 0
GLclampf g_glClearColorA = 1
VertexPointerData g_pointerData [C_PD_COUNT]
GLenum g_matrixMode = GL_MODELVIEW
GLboolean g_depthMask = true
GLenum g_CullFace = GL_BACK
GLenum g_SourceBlend = GL_SRC_ALPHA
GLenum g_DestBlend = GL_ONE_MINUS_SRC_ALPHA
GLboolean g_GL_TEXTURE_2D = true
GLboolean g_GL_DEPTH_TEST = true
GLboolean g_GL_ALPHA_TEST = false
GLboolean g_GL_BLEND = true
GLboolean g_GL_LIGHTING = true
GLboolean g_GL_CULL_FACE = true
GLboolean g_GL_LINE_SMOOTH = false
GLboolean g_GL_SCISSOR_TEST = false
GLboolean g_GL_COLOR_MATERIAL = false
GLboolean g_GL_TEXTURE_COORD_ARRAY = true
GLboolean g_GL_VERTEX_ARRAY = true
GLboolean g_GL_COLOR_ARRAY = false
GLboolean g_GL_NORMAL_ARRAY = false
CL_Rect g_scissorRect
GLenum g_DEPTHFUNC = GL_LEQUAL
GLuint g_lastBoundTexture = -1
GLuint g_lastTextureSentToFlash = -2
GLuint g_lastBoundVBO = -1
bool g_lastBoundVBOIsIndexBuffer = false
vector< CL_Mat4f > g_projectionStack
vector< CL_Mat4f > g_modelStack
vector< CL_Mat4f > * g_pActiveStack = &g_modelStack
vector< uint16 > g_tempIndexBuff
GLenum g_glFrontFace = GL_CCW
const int C_GL_LIGHTCOUNT = 8
GLFlashLight g_lightInfo [C_GL_LIGHTCOUNT]
Enumeration Type Documentation
enum ePointerData
Enumerator:
C_PD_VERTEX
C_PD_TEX_UV
C_PD_VERT_COLORS
C_PD_NORMALS
C_PD_COUNT
Definition at line 67 of file GLFlashAdaptor.cpp.
Function Documentation
void AttachVBOColorsToShader (GLuint vboIndex, int offsetInt)
Definition at line 851 of file GLFlashAdaptor.cpp.
Referenced by GenerateSmartBuffer().
void AttachVBONormalsToShader (GLuint vboIndex, int offsetInt)
Definition at line 832 of file GLFlashAdaptor.cpp.
Referenced by GenerateSmartBuffer().
void AttachVBOTexUVToShader (GLuint vboIndex, int offsetInt)
Definition at line 861 of file GLFlashAdaptor.cpp.
Referenced by GenerateSmartBuffer().
void AttachVBOVertsToShader (GLuint vboIndex, int offsetInt)
Definition at line 842 of file GLFlashAdaptor.cpp.
Referenced by GenerateSmartBuffer().
void CountUsedVertsInIndexBuffer (uint16 * pIndexBuff, int count, int * pLow, int * pHigh, int * pTotal)
Definition at line 1134 of file GLFlashAdaptor.cpp.
Referenced by glDrawArraysEx().
float* GenerateSmartBuffer (ePointerData pdType, int first, int count)
Definition at line 1061 of file GLFlashAdaptor.cpp.
References AttachVBOColorsToShader(), AttachVBONormalsToShader(), AttachVBOTexUVToShader(), AttachVBOVertsToShader(), C_PD_NORMALS, C_PD_TEX_UV, C_PD_VERT_COLORS, C_PD_VERTEX, glBindBuffer(), glBufferDataEx(), glBufferDataUV(), glGenBuffers(), and LogMsg().
Referenced by glDrawArraysEx().
GL_API void GL_APIENTRY glActiveTexture (GLenum texture)
Definition at line 1621 of file GLFlashAdaptor.cpp.
References LogMsg().
GL_API void GL_APIENTRY glAlphaFunc (GLenum func, GLclampf ref)
Definition at line 1588 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glBindBuffer (GLenum target, GLuint buffer)
Definition at line 521 of file GLFlashAdaptor.cpp.
References g_lastBoundVBO, and g_lastBoundVBOIsIndexBuffer.
Referenced by GenerateSmartBuffer(), glDrawArraysEx(), and L_ParticleEffect::RenderPointSprites().
GL_API void GL_APIENTRY glBindTexture (GLenum target, GLuint texture)
Definition at line 708 of file GLFlashAdaptor.cpp.
References g_lastBoundTexture.
Referenced by Surface::Bind().
GL_API void GL_APIENTRY glBlendFunc (GLenum sfactor, GLenum dfactor)
Definition at line 747 of file GLFlashAdaptor.cpp.
References g_DestBlend, g_SourceBlend, and UpdateBlendModes().
Referenced by Surface::ApplyBlendingMode(), L_ParticleEffect::draw(), IrrlichtManager::EndScene(), BaseApp::InitializeGLDefaults(), Surface::RemoveBlendingMode(), and L_ParticleEffect::RenderPointSprites().
GL_API void GL_APIENTRY glBufferData (GLenum target, GLsizeiptr size, const GLvoid * data, GLenum usage)
Definition at line 894 of file GLFlashAdaptor.cpp.
References glBufferDataEx().
Referenced by glDrawArraysEx(), and L_ParticleEffect::RenderPointSprites().
GL_API void GL_APIENTRY glBufferDataEx (GLenum target, GLsizeiptr size, const GLvoid * data, GLenum usage, int vertCount, int dataSizePerVertexInts)
Definition at line 872 of file GLFlashAdaptor.cpp.
References g_lastBoundVBO.
Referenced by GenerateSmartBuffer(), and glBufferData().
GL_API void GL_APIENTRY glBufferDataUV (GLenum target, GLsizeiptr size, const GLvoid * data, GLenum usage, int vertCount, int dataSizePerVertexInts)
Definition at line 904 of file GLFlashAdaptor.cpp.
References g_lastBoundVBO.
Referenced by GenerateSmartBuffer().
GL_API void GL_APIENTRY glClear (GLbitfield mask)
Definition at line 168 of file GLFlashAdaptor.cpp.
References g_glClearColorA, g_glClearColorB, g_glClearColorG, and g_glClearColorR.
Referenced by InitSDL().
GL_API void GL_APIENTRY glClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
Definition at line 158 of file GLFlashAdaptor.cpp.
References g_glClearColorA, g_glClearColorB, g_glClearColorG, and g_glClearColorR.
Referenced by BaseApp::InitializeGLDefaults(), and InitSDL().
GL_API void GL_APIENTRY glClientActiveTexture (GLenum texture)
Definition at line 1631 of file GLFlashAdaptor.cpp.
References LogMsg().
GL_API void GL_APIENTRY glClipPlanef (GLenum plane, const GLfloat * equation)
Definition at line 1469 of file GLFlashAdaptor.cpp.
References LogMsg().
GL_API void GL_APIENTRY glColor4f (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
Definition at line 498 of file GLFlashAdaptor.cpp.
Referenced by glColor4ub(), and glColor4x().
GL_API void GL_APIENTRY glColor4ub (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
Definition at line 510 of file GLFlashAdaptor.cpp.
References glColor4f().
GL_API void GL_APIENTRY glColor4x (GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha)
Definition at line 516 of file GLFlashAdaptor.cpp.
References glColor4f().
Referenced by Surface::ApplyBlendingMode(), DrawEllipse(), DrawLine(), RenderBatcher::Flush(), RenderBatcher::Flush3D(), GenerateFillRect(), BaseApp::InitializeGLDefaults(), Surface::RemoveBlendingMode(), and RenderGLTriangle().
GL_API void GL_APIENTRY glColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
Definition at line 1614 of file GLFlashAdaptor.cpp.
References LogMsg().
Referenced by InitSDL().
GL_API void GL_APIENTRY glColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer)
Definition at line 656 of file GLFlashAdaptor.cpp.
References C_PD_VERT_COLORS.
Referenced by RenderBatcher::BlitRawImage(), RenderBatcher::Flush(), RenderBatcher::Flush3D(), and L_ParticleEffect::RenderPointSprites().
GL_API void GL_APIENTRY glCopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
Definition at line 1607 of file GLFlashAdaptor.cpp.
References LogMsg().
GL_API void GL_APIENTRY glCullFace (GLenum mode)
Definition at line 733 of file GLFlashAdaptor.cpp.
References g_CullFace, and UpdateCullingOptions().
Referenced by BaseApp::InitializeGLDefaults(), PrepareForGL(), and SetupOrtho().
GL_API void GL_APIENTRY glDeleteBuffers (GLsizei n, const GLuint * buffers)
Definition at line 934 of file GLFlashAdaptor.cpp.
Referenced by L_ParticleMem::deinit(), and glDrawArraysEx().
GL_API void GL_APIENTRY glDeleteTextures (GLsizei n, const GLuint * textures)
Definition at line 817 of file GLFlashAdaptor.cpp.
References LogMsg().
Referenced by Surface::Kill().
GL_API void GL_APIENTRY glDepthFunc (GLenum func)
Definition at line 719 of file GLFlashAdaptor.cpp.
References g_DEPTHFUNC.
Referenced by BaseApp::InitializeGLDefaults().
GL_API void GL_APIENTRY glDepthMask (GLboolean flag)
Definition at line 724 of file GLFlashAdaptor.cpp.
References g_depthMask, and UpdateDepthTest().
Referenced by BaseApp::InitializeGLDefaults(), PrepareForGL(), and SetupOrtho().
GL_API void GL_APIENTRY glDepthRangef (GLclampf zNear, GLclampf zFar)
Definition at line 742 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glDisable (GLenum cap)
Definition at line 462 of file GLFlashAdaptor.cpp.
References glEnableEx().
Referenced by RenderBatcher::BlitRawImage(), DrawEllipse(), DrawLine(), IrrlichtManager::EndScene(), RenderBatcher::Flush(), RenderBatcher::Flush3D(), GenerateFillRect(), BaseApp::InitializeGLDefaults(), RenderClipComponent::PostOnRender(), RenderScissorComponent::PostOnRender(), Surface::RemoveBlendingMode(), RenderGLTriangle(), L_ParticleEffect::RenderPointSprites(), RenderSpinningTriangle(), RenderTexturedGLTriangle(), RenderTexturedGLTriangleWithDrawElements(), RenderTexturedRectangle(), and SetupOrtho().
GL_API void GL_APIENTRY glDisableClientState (GLenum array)
Definition at line 493 of file GLFlashAdaptor.cpp.
References glEnableClientStateEx().
Referenced by RenderBatcher::BlitRawImage(), DrawEllipse(), DrawLine(), RenderBatcher::Flush(), RenderBatcher::Flush3D(), GenerateFillRect(), BaseApp::InitializeGLDefaults(), RenderGLTriangle(), L_ParticleEffect::RenderPointSprites(), and SetupOrtho().
GL_API void GL_APIENTRY glDrawArrays (GLenum mode, GLint first, GLsizei count)
Definition at line 1454 of file GLFlashAdaptor.cpp.
References glDrawArraysEx().
Referenced by Surface::Blit(), Surface::BlitEx(), DrawEllipse(), DrawLine(), GenerateFillRect(), RenderGLTriangle(), L_ParticleEffect::RenderPointSprites(), RenderTexturedGLTriangle(), and RenderTexturedRectangle().
GL_API void GL_APIENTRY glDrawArraysEx (GLenum mode, GLint first, GLsizei count, GLenum indexType, const GLvoid * pIndexBuff)
Definition at line 1156 of file GLFlashAdaptor.cpp.
References C_PD_NORMALS, C_PD_TEX_UV, C_PD_VERT_COLORS, C_PD_VERTEX, CountUsedVertsInIndexBuffer(), g_GL_COLOR_ARRAY, g_GL_NORMAL_ARRAY, g_GL_SCISSOR_TEST, g_GL_TEXTURE_COORD_ARRAY, g_lastBoundTexture, g_modelStack, g_projectionStack, g_scissorRect, g_tempIndexBuff, GenerateSmartBuffer(), GetScreenSizeX(), GetScreenSizeY(), glBindBuffer(), glBufferData(), glDeleteBuffers(), glGenBuffers(), GLResetFBOCaches(), LogError(), LogMsg(), PrintGLColor(), PrintRect(), PrintVector3(), and SendTextureToFlash().
Referenced by glDrawArrays(), and glDrawElements().
GL_API void GL_APIENTRY glDrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid * indices)
Definition at line 1449 of file GLFlashAdaptor.cpp.
References glDrawArraysEx().
Referenced by RenderTexturedGLTriangleWithDrawElements().
GL_API void GL_APIENTRY glEnable (GLenum cap)
Definition at line 467 of file GLFlashAdaptor.cpp.
References glEnableEx().
Referenced by Surface::ApplyBlendingMode(), IrrlichtManager::BeginScene(), RenderBatcher::BlitRawImage(), DrawEllipse(), DrawLine(), IrrlichtManager::EndScene(), RenderClipComponent::FilterOnRender(), RenderScissorComponent::FilterOnRender(), RenderBatcher::Flush(), GenerateFillRect(), BaseApp::InitializeGLDefaults(), PrepareForGL(), RenderGLTriangle(), L_ParticleEffect::RenderPointSprites(), RenderSpinningTriangle(), RenderTexturedGLTriangle(), RenderTexturedGLTriangleWithDrawElements(), RenderTexturedRectangle(), and SetupOrtho().
GL_API void GL_APIENTRY glEnableClientState (GLenum array)
Definition at line 488 of file GLFlashAdaptor.cpp.
References glEnableClientStateEx().
Referenced by RenderBatcher::BlitRawImage(), DrawEllipse(), DrawLine(), RenderBatcher::Flush(), RenderBatcher::Flush3D(), GenerateFillRect(), BaseApp::InitializeGLDefaults(), RenderGLTriangle(), L_ParticleEffect::RenderPointSprites(), RenderTexturedGLTriangle(), RenderTexturedGLTriangleWithDrawElements(), RenderTexturedRectangle(), and SetupOrtho().
void glEnableClientStateEx (GLenum cap, bool bSetting)
Definition at line 472 of file GLFlashAdaptor.cpp.
References g_GL_COLOR_ARRAY, g_GL_NORMAL_ARRAY, g_GL_TEXTURE_COORD_ARRAY, g_GL_VERTEX_ARRAY, and LogMsg().
Referenced by glDisableClientState(), and glEnableClientState().
void glEnableEx (GLenum cap, bool bSetting)
Definition at line 372 of file GLFlashAdaptor.cpp.
References g_GL_ALPHA_TEST, g_GL_BLEND, g_GL_COLOR_MATERIAL, g_GL_CULL_FACE, g_GL_DEPTH_TEST, g_GL_LIGHTING, g_GL_LINE_SMOOTH, g_GL_SCISSOR_TEST, g_GL_TEXTURE_2D, LogMsg(), UpdateBlendModes(), UpdateCullingOptions(), UpdateDepthTest(), and UpdateScissorRect().
Referenced by glDisable(), and glEnable().
bool GLFlashAdaptor_Initialize ()
Definition at line 129 of file GLFlashAdaptor.cpp.
References g_modelStack, g_projectionStack, g_scissorRect, GetScreenSizeXf(), GetScreenSizeYf(), and LogMsg().
Referenced by main().
void GLFlashAdaptor_Kill ()
Definition at line 151 of file GLFlashAdaptor.cpp.
References GLResetFBOCaches(), and LogMsg().
GL_API void GL_APIENTRY glFrontFace (GLenum mode)
Definition at line 360 of file GLFlashAdaptor.cpp.
References g_glFrontFace, and UpdateCullingOptions().
Referenced by SetupOrtho().
GL_API void GL_APIENTRY glFrustumf (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
Definition at line 1595 of file GLFlashAdaptor.cpp.
References g_pActiveStack.
GL_API void GL_APIENTRY glGenBuffers (GLsizei n, GLuint * buffers)
Definition at line 915 of file GLFlashAdaptor.cpp.
Referenced by GenerateSmartBuffer(), glDrawArraysEx(), and L_ParticleMem::init().
GL_API void GL_APIENTRY glGenTextures (GLsizei n, GLuint * textures)
Definition at line 951 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glGetBooleanv (GLenum pname, GLboolean * params)
Definition at line 1475 of file GLFlashAdaptor.cpp.
References g_GL_SCISSOR_TEST, and LogMsg().
Referenced by RenderScissorComponent::FilterOnRender().
GL_API GLenum GL_APIENTRY glGetError (void)
Definition at line 213 of file GLFlashAdaptor.cpp.
Referenced by RenderScissorComponent::FilterOnRender().
GL_API void GL_APIENTRY glGetFloatv (GLenum pname, GLfloat * params)
Definition at line 572 of file GLFlashAdaptor.cpp.
References g_modelStack, g_projectionStack, and LogMsg().
Referenced by ScreenToWorld().
GL_API void GL_APIENTRY glGetIntegerv (GLenum pname, GLint * params)
Definition at line 548 of file GLFlashAdaptor.cpp.
References GetScreenSizeX(), GetScreenSizeY(), and LogMsg().
Referenced by RenderScissorComponent::FilterOnRender(), and BaseApp::Init().
GL_API const GLubyte* GL_APIENTRY glGetString (GLenum name)
Definition at line 589 of file GLFlashAdaptor.cpp.
Referenced by initSDL_GLES(), and BaseApp::PrintGLString().
GL_API void GL_APIENTRY glHint (GLenum target, GLenum mode)
Definition at line 714 of file GLFlashAdaptor.cpp.
Referenced by DrawLine().
GL_API void GL_APIENTRY glLightf (GLenum light, GLenum pname, GLfloat param)
Definition at line 1513 of file GLFlashAdaptor.cpp.
References LogMsg().
GL_API void GL_APIENTRY glLightfv (GLenum light, GLenum pname, const GLfloat * params)
Definition at line 1520 of file GLFlashAdaptor.cpp.
References LogMsg(), and PrintVector3().
GL_API void GL_APIENTRY glLightModelf (GLenum pname, GLfloat param)
Definition at line 1641 of file GLFlashAdaptor.cpp.
References LogMsg().
GL_API void GL_APIENTRY glLightModelfv (GLenum pname, const GLfloat * params)
Definition at line 1647 of file GLFlashAdaptor.cpp.
References LogMsg().
GL_API void GL_APIENTRY glLineWidth (GLfloat width)
Definition at line 1041 of file GLFlashAdaptor.cpp.
Referenced by DrawLine().
GL_API void GL_APIENTRY glLoadIdentity (void)
Definition at line 677 of file GLFlashAdaptor.cpp.
References g_pActiveStack.
Referenced by GenerateSetPerspectiveFOV(), PrepareForGL(), RemoveOrthoRenderSize(), RenderSpinningTriangle(), RenderTexturedGLTriangleWithDrawElements(), SetOrthoRenderSize(), and SetupOrtho().
GL_API void GL_APIENTRY glLoadMatrixf (const GLfloat * m)
Definition at line 682 of file GLFlashAdaptor.cpp.
References g_pActiveStack.
Referenced by GenerateSetPerspectiveFOV().
GL_API void GL_APIENTRY glMaterialf (GLenum face, GLenum pname, GLfloat param)
Definition at line 1506 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glMaterialfv (GLenum face, GLenum pname, const GLfloat * params)
Definition at line 1499 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glMatrixMode (GLenum mode)
Definition at line 598 of file GLFlashAdaptor.cpp.
References g_matrixMode, g_modelStack, g_pActiveStack, g_projectionStack, and LogError().
Referenced by GenerateSetPerspectiveFOV(), BaseApp::InitializeGLDefaults(), PrepareForGL(), RemoveOrthoRenderSize(), SetOrthoRenderSize(), and SetupOrtho().
GL_API void GL_APIENTRY glMultMatrixf (const GLfloat * m)
Definition at line 807 of file GLFlashAdaptor.cpp.
References g_pActiveStack.
Referenced by gluLookAt().
GL_API void GL_APIENTRY glNormalPointer (GLenum type, GLsizei stride, const GLvoid * pointer)
Definition at line 666 of file GLFlashAdaptor.cpp.
References C_PD_NORMALS.
Referenced by RenderBatcher::Flush3D().
GL_API void GL_APIENTRY glOrthof (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
Definition at line 812 of file GLFlashAdaptor.cpp.
References g_pActiveStack.
Referenced by RemoveOrthoRenderSize(), SetOrthoRenderSize(), and SetupOrtho().
GL_API void GL_APIENTRY glPolygonOffset (GLfloat factor, GLfloat units)
Definition at line 1600 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glPopMatrix (void)
Definition at line 765 of file GLFlashAdaptor.cpp.
References g_pActiveStack, and LogMsg().
Referenced by RenderBatcher::BlitRawImage(), L_ParticleEffect::draw(), DrawEllipse(), PopRotationMatrix(), PrepareForGL(), RemoveOrthoRenderSize(), RenderSpinningTriangle(), RenderTexturedGLTriangle(), RenderTexturedGLTriangleWithDrawElements(), and SetOrthoRenderSize().
GL_API void GL_APIENTRY glPushMatrix (void)
Definition at line 687 of file GLFlashAdaptor.cpp.
References g_pActiveStack.
Referenced by RenderBatcher::BlitRawImage(), L_ParticleEffect::draw(), DrawEllipse(), PushRotationMatrix(), RemoveOrthoRenderSize(), RenderSpinningTriangle(), RenderTexturedGLTriangle(), RenderTexturedGLTriangleWithDrawElements(), SetOrthoRenderSize(), and SetupOrtho().
GL_API void GL_APIENTRY glReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels)
Definition at line 702 of file GLFlashAdaptor.cpp.
References LogMsg().
Referenced by SoftSurface::BlitFromScreen(), and Surface::CopyFromScreen().
void GLResetFBOCaches ()
Definition at line 142 of file GLFlashAdaptor.cpp.
References C_PD_COUNT.
Referenced by glDrawArraysEx(), and GLFlashAdaptor_Kill().
GL_API void GL_APIENTRY glRotatef (GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
Definition at line 692 of file GLFlashAdaptor.cpp.
References g_pActiveStack.
Referenced by PushRotationMatrix(), RenderSpinningTriangle(), RenderTexturedGLTriangle(), RenderTexturedGLTriangleWithDrawElements(), and RotateGLIfNeeded().
GL_API void GL_APIENTRY glScalef (GLfloat x, GLfloat y, GLfloat z)
Definition at line 697 of file GLFlashAdaptor.cpp.
References g_pActiveStack.
GL_API void GL_APIENTRY glScissor (GLint x, GLint y, GLsizei width, GLsizei height)
Definition at line 1460 of file GLFlashAdaptor.cpp.
References g_scissorRect, GetScreenSizeY(), and UpdateScissorRect().
Referenced by RenderScissorComponent::FilterOnRender(), and RenderScissorComponent::PostOnRender().
GL_API void GL_APIENTRY glShadeModel (GLenum mode)
Definition at line 1491 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glTexCoordPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer)
Definition at line 644 of file GLFlashAdaptor.cpp.
References C_PD_TEX_UV.
Referenced by Surface::Blit(), Surface::BlitEx(), RenderBatcher::Flush(), RenderBatcher::Flush3D(), RenderTexturedGLTriangle(), RenderTexturedGLTriangleWithDrawElements(), and RenderTexturedRectangle().
GL_API void GL_APIENTRY glTexEnvi (GLenum target, GLenum pname, GLint param)
Definition at line 1655 of file GLFlashAdaptor.cpp.
References LogMsg().
Referenced by L_ParticleEffect::RenderPointSprites().
GL_API void GL_APIENTRY glTexImage2D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
Definition at line 969 of file GLFlashAdaptor.cpp.
References g_lastBoundTexture, SoftSurface::GetPixelData(), SoftSurface::Init(), LogError(), LogMsg(), and SoftSurface::SURFACE_RGBA.
Referenced by Surface::InitBlankSurface(), and Surface::InitFromSoftSurface().
GL_API void GL_APIENTRY glTexParameterf (GLenum target, GLenum pname, GLfloat param)
Definition at line 792 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glTexParameterfv (GLenum target, GLenum pname, const GLfloat * params)
Definition at line 800 of file GLFlashAdaptor.cpp.
GL_API void GL_APIENTRY glTexParameteri (GLenum target, GLenum pname, GLint param)
Definition at line 776 of file GLFlashAdaptor.cpp.
References LogMsg().
GL_API void GL_APIENTRY glTexParameterx (GLenum target, GLenum pname, GLfixed param)
Definition at line 784 of file GLFlashAdaptor.cpp.
Referenced by Surface::SetSmoothing().
GL_API void GL_APIENTRY glTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels)
Definition at line 1046 of file GLFlashAdaptor.cpp.
References LogMsg().
Referenced by Surface::CopyFromScreen(), Surface::InitFromSoftSurface(), and Surface::UpdateSurfaceRect().
GL_API void GL_APIENTRY glTranslatef (GLfloat x, GLfloat y, GLfloat z)
Definition at line 593 of file GLFlashAdaptor.cpp.
References g_pActiveStack.
Referenced by L_ParticleEffect::draw(), DrawEllipse(), gluLookAt(), PushRotationMatrix(), RenderSpinningTriangle(), and RenderTexturedGLTriangleWithDrawElements().
GL_API void GL_APIENTRY glVertexPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer)
Definition at line 639 of file GLFlashAdaptor.cpp.
References glVertexPointerEx().
Referenced by Surface::Blit(), Surface::BlitEx(), RenderBatcher::BlitRawImage(), DrawEllipse(), DrawLine(), RenderBatcher::Flush(), RenderBatcher::Flush3D(), GenerateFillRect(), RenderGLTriangle(), L_ParticleEffect::RenderPointSprites(), RenderTexturedGLTriangle(), RenderTexturedGLTriangleWithDrawElements(), and RenderTexturedRectangle().
GL_API void GL_APIENTRY glVertexPointerEx (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer, int vertCount)
Definition at line 618 of file GLFlashAdaptor.cpp.
References C_PD_VERTEX, and LogError().
Referenced by glVertexPointer().
void SendTextureToFlash (int texSlot, bool bTextureActive, GLuint texID)
Definition at line 527 of file GLFlashAdaptor.cpp.
Referenced by glDrawArraysEx().
void UpdateBlendModes ()
Definition at line 286 of file GLFlashAdaptor.cpp.
References g_DestBlend, g_GL_BLEND, g_SourceBlend, and LogError().
Referenced by glBlendFunc(), and glEnableEx().
void UpdateCullingOptions ()
Definition at line 322 of file GLFlashAdaptor.cpp.
References g_CullFace, g_GL_CULL_FACE, and g_glFrontFace.
Referenced by glCullFace(), glEnableEx(), and glFrontFace().
void UpdateDepthTest ()
Definition at line 248 of file GLFlashAdaptor.cpp.
References g_depthMask, and g_GL_DEPTH_TEST.
Referenced by glDepthMask(), and glEnableEx().
void UpdateScissorRect ()
Definition at line 219 of file GLFlashAdaptor.cpp.
References g_GL_SCISSOR_TEST, and g_scissorRect.
Referenced by glEnableEx(), and glScissor().
Variable Documentation
const int C_GL_LIGHTCOUNT = 8
Definition at line 125 of file GLFlashAdaptor.cpp.
GLenum g_CullFace = GL_BACK
Definition at line 83 of file GLFlashAdaptor.cpp.
Referenced by glCullFace(), and UpdateCullingOptions().
GLenum g_DEPTHFUNC = GL_LEQUAL
Definition at line 103 of file GLFlashAdaptor.cpp.
Referenced by glDepthFunc().
GLboolean g_depthMask = true
Definition at line 82 of file GLFlashAdaptor.cpp.
Referenced by glDepthMask(), and UpdateDepthTest().
GLenum g_DestBlend = GL_ONE_MINUS_SRC_ALPHA
Definition at line 85 of file GLFlashAdaptor.cpp.
Referenced by glBlendFunc(), and UpdateBlendModes().
GLboolean g_GL_ALPHA_TEST = false
Definition at line 88 of file GLFlashAdaptor.cpp.
Referenced by glEnableEx().
GLboolean g_GL_BLEND = true
Definition at line 89 of file GLFlashAdaptor.cpp.
Referenced by glEnableEx(), and UpdateBlendModes().
GLboolean g_GL_COLOR_ARRAY = false
Definition at line 98 of file GLFlashAdaptor.cpp.
Referenced by glDrawArraysEx(), and glEnableClientStateEx().
GLboolean g_GL_COLOR_MATERIAL = false
Definition at line 94 of file GLFlashAdaptor.cpp.
Referenced by glEnableEx().
GLboolean g_GL_CULL_FACE = true
Definition at line 91 of file GLFlashAdaptor.cpp.
Referenced by glEnableEx(), and UpdateCullingOptions().
GLboolean g_GL_DEPTH_TEST = true
Definition at line 87 of file GLFlashAdaptor.cpp.
Referenced by glEnableEx(), and UpdateDepthTest().
GLboolean g_GL_LIGHTING = true
Definition at line 90 of file GLFlashAdaptor.cpp.
Referenced by glEnableEx().
GLboolean g_GL_LINE_SMOOTH = false
Definition at line 92 of file GLFlashAdaptor.cpp.
Referenced by glEnableEx().
GLboolean g_GL_NORMAL_ARRAY = false
Definition at line 99 of file GLFlashAdaptor.cpp.
Referenced by glDrawArraysEx(), and glEnableClientStateEx().
GLboolean g_GL_SCISSOR_TEST = false
Definition at line 93 of file GLFlashAdaptor.cpp.
Referenced by glDrawArraysEx(), glEnableEx(), glGetBooleanv(), and UpdateScissorRect().
GLboolean g_GL_TEXTURE_2D = true
Definition at line 86 of file GLFlashAdaptor.cpp.
Referenced by glEnableEx().
GLboolean g_GL_TEXTURE_COORD_ARRAY = true
Definition at line 96 of file GLFlashAdaptor.cpp.
Referenced by glDrawArraysEx(), and glEnableClientStateEx().
GLboolean g_GL_VERTEX_ARRAY = true
Definition at line 97 of file GLFlashAdaptor.cpp.
Referenced by glEnableClientStateEx().
GLclampf g_glClearColorA = 1
Definition at line 20 of file GLFlashAdaptor.cpp.
Referenced by glClear(), and glClearColor().
GLclampf g_glClearColorB = 0
Definition at line 18 of file GLFlashAdaptor.cpp.
Referenced by glClear(), and glClearColor().
GLclampf g_glClearColorG = 0
Definition at line 19 of file GLFlashAdaptor.cpp.
Referenced by glClear(), and glClearColor().
GLclampf g_glClearColorR = 0
Definition at line 17 of file GLFlashAdaptor.cpp.
Referenced by glClear(), and glClearColor().
GLenum g_glFrontFace = GL_CCW
Definition at line 113 of file GLFlashAdaptor.cpp.
Referenced by glFrontFace(), and UpdateCullingOptions().
GLuint g_lastBoundTexture = -1
Definition at line 104 of file GLFlashAdaptor.cpp.
Referenced by glBindTexture(), glDrawArraysEx(), and glTexImage2D().
GLuint g_lastBoundVBO = -1
Definition at line 106 of file GLFlashAdaptor.cpp.
Referenced by glBindBuffer(), glBufferDataEx(), and glBufferDataUV().
bool g_lastBoundVBOIsIndexBuffer = false
Definition at line 107 of file GLFlashAdaptor.cpp.
Referenced by glBindBuffer().
GLuint g_lastTextureSentToFlash = -2
Definition at line 105 of file GLFlashAdaptor.cpp.
GLFlashLight g_lightInfo[C_GL_LIGHTCOUNT]
Definition at line 127 of file GLFlashAdaptor.cpp.
GLenum g_matrixMode = GL_MODELVIEW
Definition at line 81 of file GLFlashAdaptor.cpp.
Referenced by glMatrixMode().
vector<CL_Mat4f> g_modelStack
Definition at line 109 of file GLFlashAdaptor.cpp.
Referenced by glDrawArraysEx(), GLFlashAdaptor_Initialize(), glGetFloatv(), and glMatrixMode().
vector<CL_Mat4f>* g_pActiveStack = &g_modelStack
Definition at line 111 of file GLFlashAdaptor.cpp.
Referenced by glFrustumf(), glLoadIdentity(), glLoadMatrixf(), glMatrixMode(), glMultMatrixf(), glOrthof(), glPopMatrix(), glPushMatrix(), glRotatef(), glScalef(), and glTranslatef().
VertexPointerData g_pointerData[C_PD_COUNT]
Definition at line 78 of file GLFlashAdaptor.cpp.
vector<CL_Mat4f> g_projectionStack
Definition at line 108 of file GLFlashAdaptor.cpp.
Referenced by glDrawArraysEx(), GLFlashAdaptor_Initialize(), glGetFloatv(), and glMatrixMode().
CL_Rect g_scissorRect
Definition at line 101 of file GLFlashAdaptor.cpp.
Referenced by glDrawArraysEx(), GLFlashAdaptor_Initialize(), glScissor(), and UpdateScissorRect().
GLenum g_SourceBlend = GL_SRC_ALPHA
Definition at line 84 of file GLFlashAdaptor.cpp.
Referenced by glBlendFunc(), and UpdateBlendModes().
vector<uint16> g_tempIndexBuff
Definition at line 112 of file GLFlashAdaptor.cpp.
Referenced by glDrawArraysEx().