Proton: IrrlichtManager.h File Reference
IrrlichtManager.h File Reference
Classes
class IrrlichtManager
Functions
IrrlichtManager * GetIrrlichtManager ()
core::rect< s32 > CLRectToIrrlichtRect32 (CL_Rectf clR)
core::vector3df GetVectorHeadingFromNode (scene::ISceneNode *pNode)
core::vector3df RotatePositionByDirectionalVector (core::vector3df vPos, core::vector3df vNormal)
float Vector3DToAngleRadians (core::vector3df v)
std::string PrintVector3 (core::vector3df v)
Function Documentation
core::rect<s32> CLRectToIrrlichtRect32 (CL_Rectf clR)
Definition at line 237 of file IrrlichtManager.cpp.
IrrlichtManager* GetIrrlichtManager ()
Definition at line 15 of file IrrlichtManager.cpp.
References g_irrlichtManager.
Referenced by BaseApp::Draw(), and IrrHealthBar::Init().
core::vector3df GetVectorHeadingFromNode (scene::ISceneNode * pNode)
Definition at line 247 of file IrrlichtManager.cpp.
std::string PrintVector3 (core::vector3df v)
Definition at line 300 of file IrrlichtManager.cpp.
References PrintVector3().
Referenced by glDrawArraysEx(), glLightfv(), Variant::Print(), and PrintVector3().
core::vector3df RotatePositionByDirectionalVector (core::vector3df vPos, core::vector3df vNormal)
Definition at line 257 of file IrrlichtManager.cpp.
float Vector3DToAngleRadians (core::vector3df v)
Definition at line 274 of file IrrlichtManager.cpp.