Proton: L_Defination.cpp File Reference
L_Defination.cpp File Reference
Functions
void linear_set2 (CL_Vec2f &v, L_REAL magnitude, L_REAL radian)
void linear_set_magnitude (CL_Vec2f &v, L_REAL magnitude)
L_REAL linear_get_sqr_magnitude (CL_Vec2f &v)
L_REAL linear_get_radian (CL_Vec2f &v)
Function Documentation
L_REAL linear_get_radian (CL_Vec2f & v)
Definition at line 23 of file L_Defination.cpp.
Referenced by L_ParticleEffect::create_particle(), L_ShootingEffect::howto_emit_particle(), and L_ShootingEffect::set_shooting_vector().
L_REAL linear_get_sqr_magnitude (CL_Vec2f & v)
Definition at line 18 of file L_Defination.cpp.
void linear_set2 (CL_Vec2f & v, L_REAL magnitude, L_REAL radian)
Definition at line 5 of file L_Defination.cpp.
Referenced by L_ExplosionEffect::howto_emit_particle(), L_ShootingEffect::howto_emit_particle(), and L_ShootingEffect::set_shooting_vector().
void linear_set_magnitude (CL_Vec2f & v, L_REAL magnitude)
Definition at line 11 of file L_Defination.cpp.
Referenced by L_Particle::set_velocity().