Proton: LinuxUtils.cpp File Reference
LinuxUtils.cpp File Reference
Functions
void StringReplace (const std::string &what, const std::string &with, std::string &in)
vector< string > StringTokenize (const string &theString, const string &theDelimiter)
string GetDateAndTimeAsString ()
void AppendStringToFile (string filename, string text)
void LogMsg (const char *traceStr,...)
string GetBaseAppPath ()
string GetSavePath ()
string GetAppCachePath ()
void LaunchEmail (string subject, string content)
void LaunchURL (string url)
string GetClipboardText ()
float GetDeviceOSVersion ()
string GetMacAddress ()
bool IsIPhone3GS ()
bool IsDesktop ()
Checks if the currently emulated platform is a desktop platform.
ePlatformID GetPlatformID ()
Gets the platform id of the real running environment.
bool IsIphoneOriPad ()
bool IsIphone ()
bool IsIphone4 ()
bool IsIPAD ()
eDeviceMemoryClass GetDeviceMemoryClass ()
int GetYOffset ()
unsigned int GetSystemTimeTick ()
uint64 GetSystemTimeTickLong ()
void GetDateAndTime (int *monthOut, int *dayOut, int *yearOut, int *hourOut, int *minOut, int *secOut)
double GetSystemTimeAccurate ()
unsigned int GetFreeMemory ()
void SetLastStringInput (string s)
std::string GetLastStringInput ()
eNetworkType IsNetReachable (string url)
int GetSystemData ()
void RemoveFile (string fileName, bool bAddSavePath)
string GetRegionString ()
int GetDaysSinceDate (int month, int day, int year)
bool RTCreateDirectory (const std::string &dir_name)
void CreateDirectoryRecursively (string basePath, string path)
vector< string > GetDirectoriesAtPath (string path)
vector< string > GetFilesAtPath (string path)
bool RemoveDirectoryRecursively (string path)
bool CheckIfOtherAudioIsPlaying ()
void CreateAppCacheDirIfNeeded ()
void NotifyOSOfOrientationPreference (eOrientationMode orientation)
bool HasVibration ()
Variables
string g_string
Function Documentation
void AppendStringToFile (string filename, string text)
Definition at line 337 of file ResourceUtils.cpp.
References GetPlatformID(), and PLATFORM_ID_LINUX.
Referenced by LogMsg().
bool CheckIfOtherAudioIsPlaying ()
Definition at line 471 of file LinuxUtils.cpp.
void CreateAppCacheDirIfNeeded ()
Definition at line 476 of file LinuxUtils.cpp.
void CreateDirectoryRecursively (string basePath, string path)
Definition at line 317 of file LinuxUtils.cpp.
References RTCreateDirectory(), StringReplace(), and StringTokenize().
string GetAppCachePath ()
Definition at line 75 of file LinuxUtils.cpp.
References GetAndroidMainClassName(), GetBundleName(), GetBundlePrefix(), GetJavaEnv(), GetSavePathBasic(), and LogMsg().
string GetBaseAppPath ()
Definition at line 57 of file LinuxUtils.cpp.
string GetClipboardText ()
Definition at line 90 of file LinuxUtils.cpp.
References GetAndroidMainClassName(), and GetJavaEnv().
void GetDateAndTime (int * monthOut, int * dayOut, int * yearOut, int * hourOut, int * minOut, int * secOut)
Definition at line 209 of file LinuxUtils.cpp.
string GetDateAndTimeAsString ()
Definition at line 196 of file LinuxUtils.cpp.
Referenced by LogMsg().
int GetDaysSinceDate (int month, int day, int year)
Definition at line 294 of file LinuxUtils.cpp.
eDeviceMemoryClass GetDeviceMemoryClass ()
Definition at line 151 of file LinuxUtils.cpp.
References C_DEVICE_MEMORY_CLASS_1, and C_DEVICE_MEMORY_CLASS_2.
float GetDeviceOSVersion ()
Definition at line 95 of file LinuxUtils.cpp.
vector<string> GetDirectoriesAtPath (string path)
Definition at line 339 of file LinuxUtils.cpp.
References LogError().
vector<string> GetFilesAtPath (string path)
Definition at line 376 of file LinuxUtils.cpp.
References LogError().
unsigned int GetFreeMemory ()
Definition at line 229 of file LinuxUtils.cpp.
std::string GetLastStringInput ()
Definition at line 241 of file LinuxUtils.cpp.
References g_string.
string GetMacAddress ()
Definition at line 101 of file LinuxUtils.cpp.
ePlatformID GetPlatformID ()
Gets the platform id of the real running environment.
The emulated platform can be different from this one.
Definition at line 126 of file LinuxUtils.cpp.
References PLATFORM_ID_ANDROID, and PLATFORM_ID_LINUX.
string GetRegionString ()
Definition at line 288 of file LinuxUtils.cpp.
References GetAndroidMainClassName(), and GetJavaEnv().
string GetSavePath ()
Definition at line 66 of file LinuxUtils.cpp.
References g_preferSDCardForUserStorage, GetAppCachePath(), GetSavePathBasic(), and LogMsg().
int GetSystemData ()
Definition at line 251 of file LinuxUtils.cpp.
double GetSystemTimeAccurate ()
Definition at line 223 of file LinuxUtils.cpp.
References GetSystemTimeTick().
unsigned int GetSystemTimeTick ()
Definition at line 161 of file LinuxUtils.cpp.
uint64 GetSystemTimeTickLong ()
Definition at line 186 of file LinuxUtils.cpp.
int GetYOffset ()
Definition at line 156 of file LinuxUtils.cpp.
bool HasVibration ()
Definition at line 485 of file LinuxUtils.cpp.
bool IsDesktop ()
Checks if the currently emulated platform is a desktop platform.
Definition at line 112 of file LinuxUtils.cpp.
References GetEmulatedPlatformID(), PLATFORM_ID_ANDROID, PLATFORM_ID_LINUX, PLATFORM_ID_OSX, and PLATFORM_ID_WINDOWS.
bool IsIPAD ()
Definition at line 146 of file LinuxUtils.cpp.
bool IsIphone ()
Definition at line 136 of file LinuxUtils.cpp.
bool IsIPhone3GS ()
Definition at line 107 of file LinuxUtils.cpp.
bool IsIphone4 ()
Definition at line 141 of file LinuxUtils.cpp.
bool IsIphoneOriPad ()
Definition at line 131 of file LinuxUtils.cpp.
eNetworkType IsNetReachable (string url)
Definition at line 246 of file LinuxUtils.cpp.
References C_NETWORK_WIFI.
void LaunchEmail (string subject, string content)
Definition at line 81 of file LinuxUtils.cpp.
void LaunchURL (string url)
Definition at line 85 of file LinuxUtils.cpp.
References LogMsg().
void LogMsg (const char * traceStr, ...)
Definition at line 30 of file LinuxUtils.cpp.
References Console::AddLine(), AppendStringToFile(), GetAppName(), GetBaseApp(), GetBaseAppPath(), BaseApp::GetConsole(), GetDateAndTimeAsString(), and IsBaseAppInitted().
void NotifyOSOfOrientationPreference (eOrientationMode orientation)
Definition at line 481 of file LinuxUtils.cpp.
bool RemoveDirectoryRecursively (string path)
Definition at line 411 of file LinuxUtils.cpp.
References LogError(), and RemoveDirectoryRecursively().
void RemoveFile (string fileName, bool bAddSavePath)
Definition at line 256 of file LinuxUtils.cpp.
References GetSavePath(), LogError(), and LogMsg().
bool RTCreateDirectory (const std::string & dir_name)
Definition at line 301 of file LinuxUtils.cpp.
References LogMsg().
void SetLastStringInput (string s)
Definition at line 236 of file LinuxUtils.cpp.
References g_string.
void StringReplace (const std::string & what, const std::string & with, std::string & in)
Definition at line 426 of file ResourceUtils.cpp.
vector<string> StringTokenize (const string & theString, const string & theDelimiter)
Definition at line 337 of file MiscUtils.cpp.
Variable Documentation
string g_string
Definition at line 234 of file LinuxUtils.cpp.