Proton: LinuxMain.cpp File Reference
LinuxMain.cpp File Reference
Functions
int GetPrimaryGLX ()
int GetPrimaryGLY ()
int initSDL_GLES ()
bool InitSDL ()
void ChangeEmulationOrientationIfPossible (int desiredX, int desiredY, eOrientationMode desiredOrienation)
int ConvertSDLKeycodeToProtonVirtualKey (SDLKey sdlkey)
void SDLEventLoop ()
int main (int argc, char *argv[])
Variables
bool g_bAppFinished = false
SDL_Surface * g_screen = NULL
SDL_Joystick * g_pSDLJoystick = NULL
CL_Vec3f g_accelHold = CL_Vec3f(0,0,0)
bool g_isInForeground = true
int g_winVideoScreenX = 0
int g_winVideoScreenY = 0
PointerEventHandler * gPointerEventHandler = NULL
Function Documentation
void ChangeEmulationOrientationIfPossible (int desiredX, int desiredY, eOrientationMode desiredOrienation)
Definition at line 93 of file LinuxMain.cpp.
References GetForcedOrientation(), LogMsg(), ORIENTATION_DONT_CARE, and SetupScreenInfo().
Referenced by SDLEventLoop().
int ConvertSDLKeycodeToProtonVirtualKey (SDLKey sdlkey)
Definition at line 102 of file LinuxMain.cpp.
References VIRTUAL_KEY_BACK, VIRTUAL_KEY_CONTROL, VIRTUAL_KEY_DIR_DOWN, VIRTUAL_KEY_DIR_LEFT, VIRTUAL_KEY_DIR_RIGHT, VIRTUAL_KEY_DIR_UP, VIRTUAL_KEY_F1, and VIRTUAL_KEY_SHIFT.
Referenced by SDLEventLoop().
int GetPrimaryGLX ()
Definition at line 23 of file LinuxMain.cpp.
References g_winVideoScreenX.
int GetPrimaryGLY ()
Definition at line 28 of file LinuxMain.cpp.
References g_winVideoScreenY.
bool InitSDL ()
Definition at line 76 of file LinuxMain.cpp.
References glClear(), glClearColor(), glColorMask(), initSDL_GLES(), and LogMsg().
Referenced by main().
int initSDL_GLES ()
Definition at line 33 of file LinuxMain.cpp.
References g_screen, GetAppName(), GetPrimaryGLX(), GetPrimaryGLY(), glGetString(), and LogMsg().
Referenced by InitSDL().
int main (int argc, char * argv[])
Definition at line 274 of file LinuxMain.cpp.
References BaseApp::Draw(), g_bAppFinished, g_isInForeground, g_pSDLJoystick, g_winVideoScreenX, g_winVideoScreenY, GetBaseApp(), GetMessageManager(), VideoModeSelector::getNamedMode(), VideoMode::getOrientationMode(), BaseApp::GetOSMessages(), VideoMode::getPlatformID(), GetPrimaryGLX(), GetPrimaryGLY(), VideoMode::getX(), VideoMode::getY(), glFinish(), glFlush(), gPointerEventHandler, InitSDL(), IsDesktop(), BaseApp::Kill(), LogError(), LogMsg(), OSMessage::m_type, OSMessage::m_x, OSMessage::MESSAGE_CHECK_CONNECTION, OSMessage::MESSAGE_CLOSE_TEXT_BOX, OSMessage::MESSAGE_OPEN_TEXT_BOX, OSMessage::MESSAGE_SET_ACCELEROMETER_UPDATE_HZ, OSMessage::MESSAGE_SET_FPS_LIMIT, MESSAGE_TYPE_OS_CONNECTION_CHECKED, VideoModeSelector::modesAsString(), BaseApp::OnPreInitVideo(), BaseApp::OnScreenSizeChange(), ORIENTATION_DONT_CARE, ORIENTATION_PORTRAIT, PLATFORM_ID_LINUX, RemoveFile(), RT_kCFStreamEventOpenCompleted, SDLEventLoop(), MessageManager::SendGUI(), SetEmulatedPlatformID(), SetForcedOrientation(), SetupScreenInfo(), and BaseApp::Update().
void SDLEventLoop ()
Definition at line 130 of file LinuxMain.cpp.
References ChangeEmulationOrientationIfPossible(), ConvertCoordinatesIfRequired(), ConvertSDLKeycodeToProtonVirtualKey(), g_accelHold, g_bAppFinished, g_isInForeground, GetBaseApp(), GetMessageManager(), GetPrimaryGLX(), GetPrimaryGLY(), gPointerEventHandler, PointerEventHandler::handlePointerDownEvent(), PointerEventHandler::handlePointerMoveEvent(), PointerEventHandler::handlePointerUpEvent(), LogMsg(), MESSAGE_TYPE_GUI_ACCELEROMETER, MESSAGE_TYPE_GUI_CHAR, MESSAGE_TYPE_GUI_CHAR_RAW, BaseApp::OnEnterBackground(), BaseApp::OnEnterForeground(), ORIENTATION_LANDSCAPE_LEFT, ORIENTATION_LANDSCAPE_RIGHT, ORIENTATION_PORTRAIT, ORIENTATION_PORTRAIT_UPSIDE_DOWN, MessageManager::SendGUI(), VIRTUAL_KEY_PRESS, and VIRTUAL_KEY_RELEASE.
Referenced by main().
Variable Documentation
CL_Vec3f g_accelHold = CL_Vec3f(0,0,0)
Definition at line 14 of file LinuxMain.cpp.
Referenced by SDLEventLoop().
bool g_bAppFinished = false
Definition at line 10 of file LinuxMain.cpp.
Referenced by main(), and SDLEventLoop().
bool g_isInForeground = true
Definition at line 16 of file LinuxMain.cpp.
Referenced by main(), and SDLEventLoop().
SDL_Joystick* g_pSDLJoystick = NULL
Definition at line 13 of file LinuxMain.cpp.
Referenced by main().
SDL_Surface* g_screen = NULL
Definition at line 12 of file LinuxMain.cpp.
Referenced by initSDL_GLES().
int g_winVideoScreenX = 0
Definition at line 18 of file LinuxMain.cpp.
int g_winVideoScreenY = 0
Definition at line 19 of file LinuxMain.cpp.
PointerEventHandler* gPointerEventHandler = NULL
Definition at line 21 of file LinuxMain.cpp.
Referenced by main(), and SDLEventLoop().