Proton: LogDisplayComponent.cpp File Reference
LogDisplayComponent.cpp File Reference
Functions
void SetConsole (bool bOn, bool bEnableScrollbars)
void ToggleConsole ()
Entity * CreateLogDisplayEntity (Entity *pParent, string entName, CL_Vec2f vPos, CL_Vec2f vTextAreaSize, string msg, float scale)
Function Documentation
Entity* CreateLogDisplayEntity (Entity * pParent, string entName, CL_Vec2f vPos, CL_Vec2f vTextAreaSize, string msg, float scale)
Definition at line 371 of file LogDisplayComponent.cpp.
References Entity::AddComponent(), Entity::AddEntity(), FONT_SMALL, EntityComponent::GetVar(), Entity::GetVar(), Variant::Set(), and SetupTextEntity().
void SetConsole (bool bOn, bool bEnableScrollbars)
Definition at line 329 of file LogDisplayComponent.cpp.
References Entity::AddComponent(), Entity::AddEntity(), AddFocusIfNeeded(), Entity::GetEntityByName(), GetEntityRoot(), GetScreenSizeXf(), GetScreenSizeYf(), EntityComponent::GetVar(), Entity::GetVar(), KillEntity(), and Variant::Set().
Referenced by ToggleConsole().
void ToggleConsole ()
Definition at line 357 of file LogDisplayComponent.cpp.
References Entity::GetEntityByName(), GetEntityRoot(), and SetConsole().