Proton: main.cpp File Reference
main.cpp File Reference
Functions
App * GetApp ()
bool IsLargeScreen ()
bool IsTabletSize ()
int GetPrimaryGLX ()
int GetPrimaryGLY ()
void Native_Render ()
void Native_OnGotFocus ()
void Native_OnLostFocus ()
void Native_SendGUIEx ()
void Native_Update ()
int main (int argc, char **argv)
Variables
uint32_t g_nativeScreenWidth = 0
uint32_t g_nativeScreenHeight = 0
App g_App
Function Documentation
App* GetApp ()
Definition at line 32 of file main.cpp.
References g_App.
Referenced by main(), Native_Render(), and Native_Update().
int GetPrimaryGLX ()
Definition at line 46 of file main.cpp.
References g_nativeScreenWidth.
int GetPrimaryGLY ()
Definition at line 47 of file main.cpp.
References g_nativeScreenHeight.
bool IsLargeScreen ()
Definition at line 34 of file main.cpp.
Referenced by AddIPADToFileName(), CreateSlider(), iPhoneMap2X(), iPhoneMapX2X(), iPhoneMapY2X(), ReplaceWithLargeInFileName(), and ReplaceWithLargeInFileNameAndOSSpecific().
bool IsTabletSize ()
Definition at line 39 of file main.cpp.
Referenced by ReplaceWithDeviceNameInFileName().
int main (int argc, char ** argv)
Definition at line 164 of file main.cpp.
References g_nativeScreenHeight, g_nativeScreenWidth, GetApp(), GetBaseApp(), GetFakePrimaryScreenSizeX(), GetPrimaryGLX(), GetPrimaryGLY(), GLFlashAdaptor_Initialize(), LogError(), LogMsg(), ORIENTATION_PORTRAIT, and SetupScreenInfo().
void Native_OnGotFocus ()
Definition at line 56 of file main.cpp.
References GetBaseApp(), and BaseApp::OnEnterForeground().
void Native_OnLostFocus ()
Definition at line 63 of file main.cpp.
References GetBaseApp(), and BaseApp::OnEnterBackground().
void Native_Render ()
Definition at line 49 of file main.cpp.
References GetApp().
void Native_SendGUIEx ()
Definition at line 70 of file main.cpp.
References GetMessageManager(), MESSAGE_TYPE_GUI_CHAR_RAW, MessageManager::SendGUIEx(), VIRTUAL_KEY_BACK, VIRTUAL_KEY_CONTROL, VIRTUAL_KEY_DIR_DOWN, VIRTUAL_KEY_DIR_LEFT, VIRTUAL_KEY_DIR_RIGHT, VIRTUAL_KEY_DIR_UP, VIRTUAL_KEY_F1, VIRTUAL_KEY_F10, VIRTUAL_KEY_F2, VIRTUAL_KEY_F3, VIRTUAL_KEY_F4, VIRTUAL_KEY_F5, VIRTUAL_KEY_F6, VIRTUAL_KEY_F7, VIRTUAL_KEY_F8, VIRTUAL_KEY_F9, and VIRTUAL_KEY_SHIFT.
void Native_Update ()
Definition at line 123 of file main.cpp.
References GetApp(), GetBaseApp(), GetMessageManager(), BaseApp::GetOSMessages(), LogMsg(), OSMessage::m_string, OSMessage::m_type, OSMessage::MESSAGE_CHECK_CONNECTION, OSMessage::MESSAGE_CLOSE_TEXT_BOX, OSMessage::MESSAGE_OPEN_TEXT_BOX, OSMessage::MESSAGE_SET_ACCELEROMETER_UPDATE_HZ, OSMessage::MESSAGE_SET_FPS_LIMIT, MESSAGE_TYPE_OS_CONNECTION_CHECKED, RT_kCFStreamEventOpenCompleted, MessageManager::SendGUI(), and SetIsUsingNativeUI().
Variable Documentation
App g_App
Definition at line 31 of file main.cpp.
Referenced by GetApp().
uint32_t g_nativeScreenHeight = 0
Definition at line 24 of file main.cpp.
Referenced by GetPrimaryGLY(), and main().
uint32_t g_nativeScreenWidth = 0
Definition at line 23 of file main.cpp.
Referenced by GetPrimaryGLX(), and main().