Proton: MathUtils.cpp File Reference
MathUtils.cpp File Reference
Functions
void ApplyOffset (CL_Rectf *pR, const CL_Vec2f &vOffset)
void ApplyPadding (CL_Rectf *pR, const CL_Vec2f &vPadding)
void ApplyPadding (CL_Rectf *pR, const CL_Rectf &vPadding)
CL_Rectf ScaleRect (const CL_Rectf &r, float scale)
CL_Rectf ScaleRect2D (const CL_Rectf &r, CL_Vec2f vScale)
string PrintVector2 (CL_Vec2f v)
string PrintVector3 (CL_Vec3f v)
string PrintMatrix (CL_Mat4f v)
string PrintRect (CL_Rectf v)
string PrintRect (rtRectf v)
string PrintColor (uint32 color)
CL_Vec2f GetAlignmentOffset (const CL_Vec2f &vSize, eAlignment alignment)
unsigned int DecryptPiece (byte *data, unsigned int size, int key)
unsigned int EncryptPiece (byte *data, unsigned int size, int key)
bool IntersectRaySphere (CL_Vec2f p, CL_Vec2f d, rtCircle s, float &t, CL_Vec2f &q)
bool CircleSegmentIntersect (CL_Vec2f C, float r, CL_Vec2f A, CL_Vec2f B, CL_Vec2f &P)
double sethround (double val)
float ModNearestInt (float a, float b)
float GetAngleBetweenTwoAnglesRadians (float a, float b)
void TurnAngleToward_Degrees (float *angle, float target, float amount)
CL_Rectf RotateGUIRect (CL_Rectf vRect, CL_Rectf inputRect, float angle, CL_Vec2f destRectSize)
CL_Vec3f LerpVector (const CL_Vec3f &vOriginal, const CL_Vec3f &vTarget, float f_percent)
CL_Vec2f RotateGUIPoint (CL_Vec2f vPos, CL_Rectf r, float angle, CL_Vec2f destRectSize)
float AngleBetweenPointsInDegrees (CL_Vec2f target, CL_Vec2f me)
float AngleBetweenPoints (CL_Vec2f target, CL_Vec2f me)
Function Documentation
float AngleBetweenPoints (CL_Vec2f target, CL_Vec2f me)
Definition at line 417 of file MathUtils.cpp.
Referenced by AngleBetweenPointsInDegrees().
float AngleBetweenPointsInDegrees (CL_Vec2f target, CL_Vec2f me)
Definition at line 412 of file MathUtils.cpp.
References AngleBetweenPoints().
void ApplyOffset (CL_Rectf * pR, const CL_Vec2f & vOffset)
Definition at line 5 of file MathUtils.cpp.
void ApplyPadding (CL_Rectf * pR, const CL_Vec2f & vPadding)
Definition at line 14 of file MathUtils.cpp.
Referenced by TouchDragComponent::OnInput().
void ApplyPadding (CL_Rectf * pR, const CL_Rectf & vPadding)
Definition at line 23 of file MathUtils.cpp.
bool CircleSegmentIntersect (CL_Vec2f C, float r, CL_Vec2f A, CL_Vec2f B, CL_Vec2f & P)
Definition at line 221 of file MathUtils.cpp.
unsigned int DecryptPiece (byte * data, unsigned int size, int key)
Definition at line 128 of file MathUtils.cpp.
Referenced by EncryptPiece().
unsigned int EncryptPiece (byte * data, unsigned int size, int key)
Definition at line 146 of file MathUtils.cpp.
References DecryptPiece().
CL_Vec2f GetAlignmentOffset (const CL_Vec2f & vSize, eAlignment alignment)
Definition at line 92 of file MathUtils.cpp.
References ALIGNMENT_CENTER, ALIGNMENT_DOWN_CENTER, ALIGNMENT_DOWN_LEFT, ALIGNMENT_DOWN_RIGHT, ALIGNMENT_LEFT_CENTER, ALIGNMENT_UPPER_CENTER, ALIGNMENT_UPPER_LEFT, and ALIGNMENT_UPPER_RIGHT.
Referenced by SurfaceAnim::BlitScaledAnim(), Surface::BlitScaledWithRotatePoint(), Entity::CallFunctionRecursivelyWithUpdatedVar(), ConvertEntityClickToScreenCoords(), RTFont::DrawAligned(), RTFont::DrawAlignedSolidColor(), FilterInputComponent::FilterOnInput(), ManuallySetAlignmentEntity(), and MeasureEntityAndChildren().
float GetAngleBetweenTwoAnglesRadians (float a, float b)
Definition at line 281 of file MathUtils.cpp.
References ModNearestInt().
bool IntersectRaySphere (CL_Vec2f p, CL_Vec2f d, rtCircle s, float & t, CL_Vec2f & q)
Definition at line 195 of file MathUtils.cpp.
CL_Vec3f LerpVector (const CL_Vec3f & vOriginal, const CL_Vec3f & vTarget, float f_percent)
Definition at line 341 of file MathUtils.cpp.
float ModNearestInt (float a, float b)
Definition at line 254 of file MathUtils.cpp.
References sethround().
Referenced by GetAngleBetweenTwoAnglesRadians().
string PrintColor (uint32 color)
Definition at line 84 of file MathUtils.cpp.
string PrintMatrix (CL_Mat4f v)
Definition at line 59 of file MathUtils.cpp.
string PrintRect (CL_Rectf v)
Definition at line 71 of file MathUtils.cpp.
Referenced by glDrawArraysEx(), and Variant::Print().
string PrintRect (rtRectf v)
Definition at line 78 of file MathUtils.cpp.
References rtRectf::bottom, rtRectf::left, rtRectf::right, and rtRectf::top.
string PrintVector2 (CL_Vec2f v)
Definition at line 45 of file MathUtils.cpp.
Referenced by Variant::Print().
string PrintVector3 (CL_Vec3f v)
Definition at line 52 of file MathUtils.cpp.
CL_Vec2f RotateGUIPoint (CL_Vec2f vPos, CL_Rectf r, float angle, CL_Vec2f destRectSize)
Definition at line 346 of file MathUtils.cpp.
References GetScreenSize(), and GetScreenSizeXf().
Referenced by AdjustGUIElementForWindowView(), and RotateGUIRect().
CL_Rectf RotateGUIRect (CL_Rectf vRect, CL_Rectf inputRect, float angle, CL_Vec2f destRectSize)
Definition at line 325 of file MathUtils.cpp.
References RotateGUIPoint().
CL_Rectf ScaleRect (const CL_Rectf & r, float scale)
Definition at line 34 of file MathUtils.cpp.
CL_Rectf ScaleRect2D (const CL_Rectf & r, CL_Vec2f vScale)
Definition at line 39 of file MathUtils.cpp.
double sethround (double val) [inline]
Definition at line 248 of file MathUtils.cpp.
Referenced by ModNearestInt().
void TurnAngleToward_Degrees (float * angle, float target, float amount)
Definition at line 286 of file MathUtils.cpp.