Proton: MiscUtils.h File Reference
MiscUtils.h File Reference
Functions
uint32 HashString (const char *str, int32 len=0)
unsigned int GetHashOfFile (std::string fName, bool bAddBasePath)
bool IsEven (int number)
void ToLowerCase (char *pCharArray)
void ToUpperCase (char *pCharArray)
std::string ToLowerCaseString (const std::string &s)
std::string ToUpperCaseString (const std::string &s)
bool CaseInsensitiveCompare (const char *a, const char *b)
void SetIntWithTarget (int32 *p_out_dest, int r_target, int r_amount)
int mod (int a, int b)
int Random (int range)
Returns a random number limited by range.
int RandomRange (int rangeMin, int rangeMax)
Returns a random number between rangeMin and rangeMax.
float RandomRangeFloat (float rangeMin, float rangeMax)
Returns a random floating point number between rangeMin and rangeMax.
float LerpFloat (float f_origin, float f_target, float f_percent)
std::string RemoveLastPartOfDir (std::string path)
std::string BoolToEnabled (bool bEnabled)
char * float_to_money (double num, char *buf, int dec)
std::string FloatToMoney (float f, int decimalsOfCents=0)
std::string IntToTime (uint32 ms, bool bTextFormat=false)
std::string IntToTimeSeconds (uint32 seconds, bool bTextFormat=false)
std::vector< std::string > StringTokenize (const std::string &str, const std::string &delimiter)
Splits str into multiple parts delimited by delimiter.
std::string PopFirstParmString (std::string *lineInOut, const std::string delimiter="|")
std::string PeekFirstParmString (std::string *lineInOut, const std::string delimiter="|")
void ForceRange (float &a, const float min, const float max)
template<class C >
std::string toString (C value)
int StringToInt (const std::string &s)
std::string PrefixLeading (const std::string input, unsigned int leadingCount, std::string leadingChar, std::string insertAfterPrefix="")
std::string PostfixLeading (const std::string input, unsigned int leadingCount, std::string leadingChar, std::string insertAfterPrefix="")
bool force_range (int *i_original, int i_min, int i_max)
std::string GetCountryCode ()
std::string StripWhiteSpace (const std::string &s)
std::string TrimLeft (const std::string &s, const std::string &t=RT_UTIL_SPACES)
std::string TrimRight (const std::string &s, const std::string &t=RT_UTIL_SPACES)
std::string GetFileNameFromString (const std::string &path)
std::string GetPathFromString (const std::string &path)
std::string RemoveTrailingBackslash (std::string st)
std::string GetFileExtension (std::string fileName)
std::string ModifyFileExtension (std::string fileName, std::string extension)
void TruncateString (std::string &input, size_t len)
bool IsInString (const std::string &s, const char *search)
void RotationToXYMod (float rotation, float *pXMod, float *pYMod)
void SetFloatWithTarget (float *p_out_dest, float r_target, float r_amount)
std::string FilterToValidAscii (const std::string &input, bool bStrict)
bool isOrdinaryChar (char c, bool bStrict)
int GiveOrTake (int baseNum, int modAmount)
Function Documentation
std::string BoolToEnabled (bool bEnabled)
Definition at line 59 of file MiscUtils.cpp.
bool CaseInsensitiveCompare (const char * a, const char * b)
Definition at line 564 of file MiscUtils.cpp.
std::string FilterToValidAscii (const std::string & input, bool bStrict)
char* float_to_money (double num, char * buf, int dec)
Definition at line 229 of file MiscUtils.cpp.
References StringReverse().
Referenced by FloatToMoney().
std::string FloatToMoney (float f, int decimalsOfCents = 0)
Definition at line 275 of file MiscUtils.cpp.
References float_to_money().
bool force_range (int * i_original, int i_min, int i_max)
Definition at line 370 of file MiscUtils.cpp.
References in_range().
void ForceRange (float & a, const float min, const float max)
Definition at line 378 of file MiscUtils.cpp.
std::string GetCountryCode ()
Definition at line 393 of file MiscUtils.cpp.
References GetRegionString(), and ToLowerCaseString().
std::string GetFileExtension (std::string fileName)
std::string GetFileNameFromString (const std::string & path)
unsigned int GetHashOfFile (std::string fName, bool bAddBasePath)
std::string GetPathFromString (const std::string & path)
int GiveOrTake (int baseNum, int modAmount)
Definition at line 188 of file MiscUtils.cpp.
References Random().
uint32 HashString (const char * str, int32 len = 0)
Definition at line 11 of file MiscUtils.cpp.
Referenced by GetHashOfFile().
std::string IntToTime (uint32 ms, bool bTextFormat = false)
Definition at line 667 of file MiscUtils.cpp.
References IntToTimeSeconds().
std::string IntToTimeSeconds (uint32 seconds, bool bTextFormat = false)
Definition at line 578 of file MiscUtils.cpp.
References toString().
Referenced by IntToTime().
bool IsEven (int number)
Definition at line 53 of file MiscUtils.cpp.
bool IsInString (const std::string & s, const char * search)
bool isOrdinaryChar (char c, bool bStrict)
Definition at line 528 of file MiscUtils.cpp.
Referenced by FilterToValidAscii().
float LerpFloat (float f_origin, float f_target, float f_percent)
Definition at line 193 of file MiscUtils.cpp.
int mod (int a, int b)
Definition at line 158 of file MiscUtils.cpp.
Referenced by AdManager::ModifyTapPoints(), BaseApp::ModMemUsed(), BaseApp::ModTexUsed(), and Gamepad::Update().
std::string ModifyFileExtension (std::string fileName, std::string extension)
std::string PeekFirstParmString (std::string * lineInOut, const std::string delimiter = "|")
std::string PopFirstParmString (std::string * lineInOut, const std::string delimiter = "|")
std::string PostfixLeading (const std::string input, unsigned int leadingCount, std::string leadingChar, std::string insertAfterPrefix = "")
std::string PrefixLeading (const std::string input, unsigned int leadingCount, std::string leadingChar, std::string insertAfterPrefix = "")
int Random (int range)
Returns a random number limited by range.
If range is positive the returned value is on the interval [0, range[.
If range is negative the returned value is on the interval [0, -range[.
Definition at line 168 of file MiscUtils.cpp.
Referenced by GetBrightColor(), and GiveOrTake().
int RandomRange (int rangeMin, int rangeMax)
Returns a random number between rangeMin and rangeMax.
The range includes rangeMin but not rangeMax, in other words the returned value is on the interval [rangeMin, rangeMax[.
This function is meant to be used so that rangeMin < rangeMax. However the behaviour is well defined for other combinations as well.
If rangeMin equals rangeMax then rangeMin is returned.
If rangeMin != rangeMax the returned value is on the interval [rangeMin, rangeMin+abs(rangeMax-rangeMin)[.
Definition at line 173 of file MiscUtils.cpp.
float RandomRangeFloat (float rangeMin, float rangeMax)
Returns a random floating point number between rangeMin and rangeMax.
The behaviour of this function is similar to RandomRange(). The notes on that function apply to this function too.
See also:
RandomRange()
Definition at line 179 of file MiscUtils.cpp.
std::string RemoveLastPartOfDir (std::string path)
std::string RemoveTrailingBackslash (std::string st)
void RotationToXYMod (float rotation, float * pXMod, float * pYMod)
Definition at line 493 of file MiscUtils.cpp.
Referenced by ManuallySetAlignmentEntity().
void SetFloatWithTarget (float * p_out_dest, float r_target, float r_amount)
Definition at line 141 of file MiscUtils.cpp.
void SetIntWithTarget (int32 * p_out_dest, int r_target, int r_amount)
Definition at line 123 of file MiscUtils.cpp.
int StringToInt (const std::string & s)
std::vector<std::string> StringTokenize (const std::string & str, const std::string & delimiter)
Splits str into multiple parts delimited by delimiter.
Examples:
 string str("foo_bar_baz");
 StringTokenize(str, "_"); // Returned parts are "foo", "bar" and "baz"
 string str("foo***bar****baz");
 StringTokenize(str, "**"); // Returned parts are "foo", "*bar", "" (an empty string) and "baz"
std::string StripWhiteSpace (const std::string & s)
void ToLowerCase (char * pCharArray)
Definition at line 87 of file MiscUtils.cpp.
std::string ToLowerCaseString (const std::string & s)
template<class C > std::string toString (C value)
Definition at line 82 of file MiscUtils.h.
Referenced by VariantList::GetContentsAsDebugString(), AdManager::GetPointsString(), TestResults::GetResultString(), IntToTimeSeconds(), VideoModeSelector::modesAsString(), Variant::Print(), ProtonVirtualKeyToString(), SetupLightBarSelect(), and ProtonTester::showResultOnScreen().
void ToUpperCase (char * pCharArray)
Definition at line 95 of file MiscUtils.cpp.
std::string ToUpperCaseString (const std::string & s)
std::string TrimLeft (const std::string & s, const std::string & t = RT_UTIL_SPACES)
std::string TrimRight (const std::string & s, const std::string & t = RT_UTIL_SPACES)
void TruncateString (std::string & input, size_t len)