Proton: MiscUtils.cpp File Reference
MiscUtils.cpp File Reference
Functions
uint32 HashString (const char *str, int32 len)
unsigned int GetHashOfFile (string fName, bool bAddBasePath)
bool IsEven (int number)
string BoolToEnabled (bool bEnabled)
string RemoveLastPartOfDir (string path)
void ToLowerCase (char *pCharArray)
void ToUpperCase (char *pCharArray)
string ToLowerCaseString (const string &s)
string ToUpperCaseString (const string &s)
void SetIntWithTarget (int32 *p_out_dest, int r_target, int r_amount)
void SetFloatWithTarget (float *p_out_dest, float r_target, float r_amount)
int mod (int a, int b)
int Random (int range)
Returns a random number limited by range.
int RandomRange (int rangeMin, int rangeMax)
Returns a random number between rangeMin and rangeMax.
float RandomRangeFloat (float rangeMin, float rangeMax)
Returns a random floating point number between rangeMin and rangeMax.
int GiveOrTake (int baseNum, int modAmount)
float LerpFloat (float f_origin, float f_target, float f_percent)
char * StringReverse (char *str)
string RemoveTrailingBackslash (string st)
char * float_to_money (double num, char *buf, int dec)
string FloatToMoney (float f, int decimalsOfCents)
string PrefixLeading (const string input, unsigned int leadingCount, string leadingChar, string insertAfterPrefix)
string PostfixLeading (const string input, unsigned int leadingCount, string leadingChar, string insertAfterPrefix)
string PopFirstParmString (string *lineInOut, const string delimiter)
string PeekFirstParmString (string *lineInOut, const string delimiter)
vector< string > StringTokenize (const string &theString, const string &theDelimiter)
bool in_range (int i_num, int i_low, int i_high)
bool force_range (int *i_original, int i_min, int i_max)
void ForceRange (float &a, const float min, const float max)
string GetCountryCode ()
string TrimRight (const string &s, const string &t)
string TrimLeft (const string &s, const string &t)
string StripWhiteSpace (const string &s)
string GetFileNameFromString (const string &path)
string GetPathFromString (const string &path)
string ModifyFileExtension (string fileName, string extension)
string GetFileExtension (string fileName)
void TruncateString (string &input, size_t len)
bool IsInString (const string &s, const char *search)
void RotationToXYMod (float rotation, float *pXMod, float *pYMod)
bool isOrdinaryChar (char c, bool bStrict)
string FilterToValidAscii (const string &input, bool bStrict)
bool CaseInsensitiveCompare (const char *a, const char *b)
string IntToTimeSeconds (uint32 seconds, bool bTextFormat)
string IntToTime (uint32 ms, bool bTextFormat)
int StringToInt (const string &s)
Function Documentation
string BoolToEnabled (bool bEnabled)
Definition at line 59 of file MiscUtils.cpp.
bool CaseInsensitiveCompare (const char * a, const char * b)
Definition at line 564 of file MiscUtils.cpp.
string FilterToValidAscii (const string & input, bool bStrict)
Definition at line 548 of file MiscUtils.cpp.
References isOrdinaryChar().
char* float_to_money (double num, char * buf, int dec)
Definition at line 229 of file MiscUtils.cpp.
References StringReverse().
Referenced by FloatToMoney().
string FloatToMoney (float f, int decimalsOfCents)
Definition at line 275 of file MiscUtils.cpp.
References float_to_money().
bool force_range (int * i_original, int i_min, int i_max)
Definition at line 370 of file MiscUtils.cpp.
References in_range().
void ForceRange (float & a, const float min, const float max)
Definition at line 378 of file MiscUtils.cpp.
string GetCountryCode ()
Definition at line 393 of file MiscUtils.cpp.
References GetRegionString(), and ToLowerCaseString().
string GetFileExtension (string fileName)
Definition at line 467 of file MiscUtils.cpp.
Referenced by CompressFile(), AudioManagerAndroid::Play(), AudioManagerSDL::Preload(), AudioManagerFMOD::Preload(), and AudioManagerAndroid::Preload().
string GetFileNameFromString (const string & path)
Definition at line 427 of file MiscUtils.cpp.
unsigned int GetHashOfFile (string fName, bool bAddBasePath)
Definition at line 32 of file MiscUtils.cpp.
References FileManager::Get(), GetFileManager(), HashString(), and LoadFileIntoMemoryBasic().
string GetPathFromString (const string & path)
Definition at line 440 of file MiscUtils.cpp.
int GiveOrTake (int baseNum, int modAmount)
Definition at line 188 of file MiscUtils.cpp.
References Random().
uint32 HashString (const char * str, int32 len)
Definition at line 11 of file MiscUtils.cpp.
Referenced by GetHashOfFile().
bool in_range (int i_num, int i_low, int i_high)
Definition at line 363 of file MiscUtils.cpp.
Referenced by force_range().
string IntToTime (uint32 ms, bool bTextFormat)
Definition at line 667 of file MiscUtils.cpp.
References IntToTimeSeconds().
string IntToTimeSeconds (uint32 seconds, bool bTextFormat)
Definition at line 578 of file MiscUtils.cpp.
References toString().
Referenced by IntToTime().
bool IsEven (int number)
Definition at line 53 of file MiscUtils.cpp.
bool IsInString (const string & s, const char * search)
Definition at line 486 of file MiscUtils.cpp.
bool isOrdinaryChar (char c, bool bStrict)
Definition at line 528 of file MiscUtils.cpp.
Referenced by FilterToValidAscii().
float LerpFloat (float f_origin, float f_target, float f_percent)
Definition at line 193 of file MiscUtils.cpp.
int mod (int a, int b)
Definition at line 158 of file MiscUtils.cpp.
Referenced by AdManager::ModifyTapPoints(), BaseApp::ModMemUsed(), BaseApp::ModTexUsed(), and Gamepad::Update().
string ModifyFileExtension (string fileName, string extension)
Definition at line 455 of file MiscUtils.cpp.
Referenced by CompressFile(), AudioManagerAndroid::Play(), and AudioManagerAndroid::Preload().
string PeekFirstParmString (string * lineInOut, const string delimiter)
Definition at line 327 of file MiscUtils.cpp.
References StringTokenize().
string PopFirstParmString (string * lineInOut, const string delimiter)
Definition at line 305 of file MiscUtils.cpp.
References StringTokenize().
string PostfixLeading (const string input, unsigned int leadingCount, string leadingChar, string insertAfterPrefix)
Definition at line 296 of file MiscUtils.cpp.
string PrefixLeading (const string input, unsigned int leadingCount, string leadingChar, string insertAfterPrefix)
Definition at line 283 of file MiscUtils.cpp.
int Random (int range)
Returns a random number limited by range.
If range is positive the returned value is on the interval [0, range[.
If range is negative the returned value is on the interval [0, -range[.
Definition at line 168 of file MiscUtils.cpp.
Referenced by GetBrightColor(), and GiveOrTake().
int RandomRange (int rangeMin, int rangeMax)
Returns a random number between rangeMin and rangeMax.
The range includes rangeMin but not rangeMax, in other words the returned value is on the interval [rangeMin, rangeMax[.
This function is meant to be used so that rangeMin < rangeMax. However the behaviour is well defined for other combinations as well.
If rangeMin equals rangeMax then rangeMin is returned.
If rangeMin != rangeMax the returned value is on the interval [rangeMin, rangeMin+abs(rangeMax-rangeMin)[.
Definition at line 173 of file MiscUtils.cpp.
float RandomRangeFloat (float rangeMin, float rangeMax)
Returns a random floating point number between rangeMin and rangeMax.
The behaviour of this function is similar to RandomRange(). The notes on that function apply to this function too.
See also:
RandomRange()
Definition at line 179 of file MiscUtils.cpp.
string RemoveLastPartOfDir (string path)
Definition at line 71 of file MiscUtils.cpp.
string RemoveTrailingBackslash (string st)
Definition at line 217 of file MiscUtils.cpp.
void RotationToXYMod (float rotation, float * pXMod, float * pYMod)
Definition at line 493 of file MiscUtils.cpp.
Referenced by ManuallySetAlignmentEntity().
void SetFloatWithTarget (float * p_out_dest, float r_target, float r_amount)
Definition at line 141 of file MiscUtils.cpp.
void SetIntWithTarget (int32 * p_out_dest, int r_target, int r_amount)
Definition at line 123 of file MiscUtils.cpp.
char* StringReverse (char * str)
Definition at line 198 of file MiscUtils.cpp.
Referenced by float_to_money().
int StringToInt (const string & s)
Definition at line 672 of file MiscUtils.cpp.
vector<string> StringTokenize (const string & theString, const string & theDelimiter)
Definition at line 337 of file MiscUtils.cpp.
Referenced by CreateDirectoryRecursively(), TextScanner::GetMultipleLineStrings(), TextScanner::GetParmString(), PeekFirstParmString(), PopFirstParmString(), TextScanner::SetupFromMemoryAddress(), and TextScanner::TokenizeLine().
string StripWhiteSpace (const string & s)
Definition at line 421 of file MiscUtils.cpp.
References TrimLeft(), and TrimRight().
Referenced by TextScanner::GetAll(), and TextScanner::StripLeadingSpaces().
void ToLowerCase (char * pCharArray)
Definition at line 87 of file MiscUtils.cpp.
string ToLowerCaseString (const string & s)
Definition at line 103 of file MiscUtils.cpp.
Referenced by GetCountryCode(), and AudioManagerFMOD::Preload().
void ToUpperCase (char * pCharArray)
Definition at line 95 of file MiscUtils.cpp.
string ToUpperCaseString (const string & s)
Definition at line 113 of file MiscUtils.cpp.
string TrimLeft (const string & s, const string & t)
Definition at line 415 of file MiscUtils.cpp.
Referenced by StripWhiteSpace().
string TrimRight (const string & s, const string & t) [inline]
Definition at line 405 of file MiscUtils.cpp.
Referenced by StripWhiteSpace().
void TruncateString (string & input, size_t len)
Definition at line 478 of file MiscUtils.cpp.