Proton: ProtonTester Namespace Reference
ProtonTester Namespace Reference
Functions
void RegisterInitFunction (Function *func)
void RegisterCleanFunction (Function *func)
void runAllTests ()
std::string GetCurrentlyRunningTestName ()
unsigned int GetTotalRun ()
unsigned int GetNumPassed ()
unsigned int GetNumFailed ()
void showResultOnScreen (Entity *parent)
Function Documentation
std::string ProtonTester::GetCurrentlyRunningTestName ()
Definition at line 216 of file ProtonTester.cpp.
unsigned int ProtonTester::GetNumFailed ()
Definition at line 231 of file ProtonTester.cpp.
References TestResults::GetNumFailed().
Referenced by showResultOnScreen().
unsigned int ProtonTester::GetNumPassed ()
Definition at line 226 of file ProtonTester.cpp.
References TestResults::GetNumPassed().
Referenced by showResultOnScreen().
unsigned int ProtonTester::GetTotalRun ()
Definition at line 221 of file ProtonTester.cpp.
References TestResults::GetTotalRun().
Referenced by showResultOnScreen().
void ProtonTester::RegisterCleanFunction (Function * func)
Definition at line 205 of file ProtonTester.cpp.
void ProtonTester::RegisterInitFunction (Function * func)
Definition at line 200 of file ProtonTester.cpp.
void ProtonTester::runAllTests ()
Definition at line 210 of file ProtonTester.cpp.
References TestResults::GetResultString(), and LogMsg().
void ProtonTester::showResultOnScreen (Entity * parent)
Definition at line 10 of file ProtonTesterGUI.cpp.
References CreateTextLabelEntity(), GetNumFailed(), GetNumPassed(), GetTotalRun(), Entity::GetVar(), Variant::Set(), and toString().