Proton: NetUtils.cpp File Reference
NetUtils.cpp File Reference
Functions
char * Base64Encode (const char *data, size_t input_length, size_t *output_length)
void DecToHexString (uint32 value, byte *pOut, int16 charArrayMaxSize)
web.h 1.Declares a class to encode strings converting a String into a MIME format called "x-www-form-urlencoded" format.
string GetDomainFromURL (string url)
void BreakDownURLIntoPieces (string url, string &domainOut, string &requestOut, int &port)
Variables
static char encoding_table []
static int mod_table [] = {0, 2, 1}
Function Documentation
char* Base64Encode (const char * data, size_t input_length, size_t * output_length)
Definition at line 22 of file NetUtils.cpp.
References encoding_table, and mod_table.
void BreakDownURLIntoPieces (string url, string & domainOut, string & requestOut, int & port)
Definition at line 240 of file NetUtils.cpp.
References GetDomainFromURL(), and StringReplace().
void DecToHexString (uint32 value, byte * pOut, int16 charArrayMaxSize)
web.h 1.Declares a class to encode strings converting a String into a MIME format called "x-www-form-urlencoded" format.
To convert a String, each character is examined in turn: 1) The ASCII characters 'a' through 'z', 'A' through 'Z', and '0' through '9' remain the same. 2) The space character ' ' is converted into a plus sign '+'. 3) All other characters are converted into the 3-character string "%xy", where xy is the two-digit hexadecimal representation of the lower 8-bits of the character. 2.Declares a class to decode such strings 3. Declares the WebForm class to wrap win32 HTTP calls Author: Vijay Mathew Pandyalakal Date: 18/10/03
Stolen from CodeProject
Definition at line 67 of file NetUtils.cpp.
Referenced by URLEncoder::encodeData().
string GetDomainFromURL (string url)
Definition at line 226 of file NetUtils.cpp.
Referenced by BreakDownURLIntoPieces().
Variable Documentation
char encoding_table[] [static]
Initial value:
 {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X',
'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f',
'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
'w', 'x', 'y', 'z', '0', '1', '2', '3',
'4', '5', '6', '7', '8', '9', '+', '/'}
Definition at line 10 of file NetUtils.cpp.
Referenced by Base64Encode().
int mod_table[] = {0, 2, 1} [static]
Definition at line 19 of file NetUtils.cpp.
Referenced by Base64Encode().