Proton: NetUtils.h File Reference
NetUtils.h File Reference
Classes
class URLEncoder
class URLDecoder
Functions
void BreakDownURLIntoPieces (string url, string &domainOut, string &requestOut, int &port)
string GetDomainFromURL (string url)
char * Base64Encode (const char *data, size_t input_length, size_t *output_length)
Function Documentation
char* Base64Encode (const char * data, size_t input_length, size_t * output_length)
Definition at line 22 of file NetUtils.cpp.
References encoding_table, and mod_table.
void BreakDownURLIntoPieces (string url, string & domainOut, string & requestOut, int & port)
Definition at line 240 of file NetUtils.cpp.
References GetDomainFromURL(), and StringReplace().
string GetDomainFromURL (string url)
Definition at line 226 of file NetUtils.cpp.
Referenced by BreakDownURLIntoPieces().