Proton: P3DPlot.cpp File Reference
P3DPlot.cpp File Reference
Functions
void MakeExamplePlot1 (P3DPlot &ioPPlot)
void MakeExamplePlot2 (P3DPlot &ioPPlot)
Function Documentation
void MakeExamplePlot1 (P3DPlot & ioPPlot)
Definition at line 136 of file P3DPlot.cpp.
References P3DPlot::SetData().
Referenced by MakeExamplePlot().
void MakeExamplePlot2 (P3DPlot & ioPPlot)
Definition at line 151 of file P3DPlot.cpp.
References P3DPlot::SetData().
Referenced by MakeExamplePlot().