Proton: PlatformSetup.h File Reference
PlatformSetup.h File Reference
Functions
void LogMsg (const char *traceStr,...)
void LogError (const char *traceStr,...)
void SetEmulatedPlatformID (ePlatformID platformID)
std::string AddPlatformNameURL ()
std::string GetPlatformName ()
void SetMarketID (eMarketID marketID)
eMarketID GetMarketID ()
bool GetForceAspectRatioWhenResizing ()
int GetScreenSizeY ()
int GetScreenSizeX ()
float GetScreenSizeYf ()
float GetScreenSizeXf ()
bool IsLargeScreen ()
std::string PlatformIDAsString (ePlatformID platformID)
Returns a string representation of a platform identifier.
std::string PlatformIDAsStringDisplay (ePlatformID platformID)
Returns a string representation of a platform identifier for display purposes.
ePlatformID PlatformStringAsID (std::string platform)
std::string OrientationAsStringDisplay (eOrientationMode orientation)
Returns a string representation of an orientation mode for display purposes.
Variables
const uint16 C_JPG_HEADER_MARKER = 55551
const uint32 PURE_WHITE = MAKE_RGBA(255, 255, 255, 255)
Function Documentation
std::string AddPlatformNameURL ()
Definition at line 24 of file PlatformSetup.cpp.
References GetEmulatedPlatformID(), GetPlatformName(), and PLATFORM_ID_WINDOWS.
bool GetForceAspectRatioWhenResizing ()
Definition at line 5 of file PlatformSetup.cpp.
References g_forceAspectRatioWhenChangingWindowSize.
eMarketID GetMarketID ()
Definition at line 114 of file PlatformSetup.cpp.
References g_marketID.
std::string GetPlatformName ()
Definition at line 103 of file PlatformSetup.cpp.
References GetEmulatedPlatformID(), and PlatformIDAsString().
Referenced by AddPlatformNameURL().
int GetScreenSizeX ()
Definition at line 127 of file PlatformSetup.cpp.
float GetScreenSizeXf ()
Definition at line 125 of file PlatformSetup.cpp.
int GetScreenSizeY ()
Definition at line 128 of file PlatformSetup.cpp.
float GetScreenSizeYf ()
Definition at line 126 of file PlatformSetup.cpp.
bool IsLargeScreen ()
Definition at line 34 of file main.cpp.
void LogError (const char * traceStr, ...)
Definition at line 460 of file BaseApp.cpp.
References GetBaseApp(), LogMsg(), and BaseApp::SetConsoleVisible().
Referenced by AdManager::AddProvider(), GamepadManager::AddProvider(), MySQLManager::AddSelectResults(), Entity::CallFunctionRecursivelyWithUpdatedVar(), StreamingInstanceZip::Close(), FileManager::Copy(), CreateCheckbox(), CreateOverlayEntity(), MySQLManager::DoesTableExist(), MySQLManager::DoResultsExist(), FilterInputComponent::FilterOnInput(), FileSystemZip::Get(), FileManager::Get(), RTFont::GetColorFromString(), FileSystemZip::GetContents(), GetDirectoriesAtPath(), GetFilesAtPath(), FileSystemZip::GetFileSize(), GetJavaEnv(), TextScanner::GetParmString(), MySQLManager::GetTableRecordCount(), glDrawArraysEx(), glMatrixMode(), glTexImage2D(), glVertexPointerEx(), GamepadDirectX::Init(), FileSystemZip::Init(), IrrlichtManager::Init(), GamepadProviderDirectX::Init(), FileCopier::Init(), NetSocket::InitHost(), Variant::Interpolate(), RTFont::Load(), SpriteAnimationSet::LoadFile(), SoftSurface::LoadFileFromMemory(), Surface::LoadFileFromMemory(), main(), RTFont::MeasureTextAndAddByLinesIntoDeque(), Entity::MoveComponentToBottomByAddress(), Entity::MoveComponentToTopByAddress(), Entity::MoveEntityToBottomByAddress(), Entity::MoveEntityToTopByAddress(), AdProviderFlurry::OnAddToManager(), AdProviderChartBoost::OnAddToManager(), InterpolateComponent::OnDurationChanged(), InterpolateComponent::OnUpdate(), InterpolateComponent::OnVarNameChanged(), JPGSurfaceLoader::output_message(), AudioManagerSDL::Play(), AudioManagerFlash::Play(), AudioManagerFMOD::Play(), AudioManagerAndroid::Play(), AudioManagerBBX::Play(), AudioManagerAudiere::Play(), MySQLManager::Query(), StreamingInstanceZip::Read(), RemoveDirectoryRecursively(), RemoveFile(), RenderClipComponent::RenderClipComponent(), ResizeScrollBounds(), VariantDB::Save(), TextScanner::SaveFile(), rtRectf::Scale(), SpriteAnimationUtils::SetAnimationName(), MySQLManager::ShowError(), SpriteAnimationUtils::StartAnimationEntity(), UpdateBlendModes(), SoftSurface::WriteBMPOut(), and SoftSurface::WriteRawDataOut().
void LogMsg (const char * traceStr, ...)
Definition at line 93 of file AndroidUtils.cpp.
References Console::AddLine(), AppendStringToFile(), GetAppName(), GetBaseApp(), GetBaseAppPath(), BaseApp::GetConsole(), GetDateAndTimeAsString(), and IsBaseAppInitted().
Referenced by L_ParticleEffect::add(), GamepadManager::AddGamepad(), AdManager::AddProvider(), GamepadManager::AddProvider(), MySQLManager::AddSelectResults(), AppDone(), AppInit(), AppOnJoypad(), AppOnKey(), AppOnTouch(), AppPause(), AppResize(), AppResume(), AppUpdate(), IAPManager::BuyItem(), AdProvider::CacheShowInterstitial(), AdProviderChartBoost::CacheShowInterstitial(), AdProvider::CacheShowMoreApps(), ChangeEmulationOrientationIfPossible(), CheckDay(), CompressFile(), Gamepad::ConnectToArcadeComponent(), FileManager::Copy(), RTFont::CountCharsThatFitX(), L_ParticleEffect::create_particle(), DestroyUnusedTextures(), MessageManager::DumpMessages(), TextScanner::DumpToLog(), FireAchievement(), RenderBatcher::Flush(), FMOD_ERROR_CHECK(), GenerateSmartBuffer(), GetAPKFile(), GetAppCachePath(), GetDaysSinceDate(), GetDirectoriesAtPath(), GetFileSize(), GetFilterSetting(), AudioManagerAndroid::GetPos(), GetSavePath(), ResourceManager::GetSpriteAnimationSet(), FileSystemZip::GetStreaming(), ResourceManager::GetSurfaceResource(), AdManager::GetTapPointsFromServer(), glActiveTexture(), glClientActiveTexture(), glClipPlanef(), glColorMask(), glCopyTexSubImage2D(), glDeleteTextures(), glDrawArraysEx(), glEnableClientStateEx(), glEnableEx(), GLFlashAdaptor_Initialize(), GLFlashAdaptor_Kill(), glGetBooleanv(), glGetFloatv(), glGetIntegerv(), glLightf(), glLightfv(), glLightModelf(), glLightModelfv(), glPopMatrix(), glReadPixels(), glTexEnvi(), glTexImage2D(), glTexParameteri(), glTexSubImage2D(), IAPManager::HandleIAPBuyResult(), IAPManager::HandleItemUpdateState(), IAPManager::HandlePurchaseListReply(), MySQLManager::Init(), GamepadProvideriCade::Init(), AudioManagerSDL::Init(), GamepadProviderMoga::Init(), FileSystemZip::Init(), IrrlichtManager::Init(), AudioManagerFlash::Init(), GamepadProviderDirectX::Init(), AdManager::Init(), AudioManagerBBX::Init(), FileCopier::Init(), BaseApp::Init(), FileCopier::InitAndCopy(), Surface::InitBlankSurface(), RTGLESExt::InitExtensions(), Surface::InitFromSoftSurface(), NetSocket::InitHost(), InitSDL(), initSDL_GLES(), AdManager::InitTapjoy(), IsDirectoryDateNewerThan(), JNI_OnLoad(), AudioManagerAndroid::Kill(), AudioManagerSDL::KillCachedSounds(), AudioManagerFlash::KillCachedSounds(), AudioManagerFMOD::KillCachedSounds(), AudioManagerAndroid::KillCachedSounds(), AudioManagerAudiere::KillCachedSounds(), AudioManagerBBX::KillCachedSounds(), LaterThanNow(), LaunchURL(), RTFont::Load(), VariantDB::Load(), Surface::LoadFile(), Surface::LoadFileFromMemory(), LogError(), main(), RTFont::MeasureText(), Native_Update(), DPadComponent::OnAdd(), AdProviderFlurry::OnAddToManager(), AdProviderChartBoost::OnAddToManager(), Gamepad::OnButton(), BaseApp::OnEnterBackground(), BaseApp::OnEnterForeground(), Gamepad::OnHat(), GamepadMoga::OnJoypadEvent(), IrrlichtManager::OnLoadSurfaces(), Surface::OnLoadSurfaces(), GamepadProvideriCade::OnLostiCadeConnection(), BaseApp::OnMemoryWarning(), AdManager::OnMessage(), IrrlichtManager::OnUnloadSurfaces(), Surface::OnUnloadSurfaces(), TyperComponent::OnUpdate(), StreamingInstanceFile::Open(), AdManager::OpenTapjoyOfferWall(), AudioManagerSDL::Play(), AudioManagerFlash::Play(), AudioManagerFMOD::Play(), AudioManagerBBX::Play(), AudioManagerSDL::Preload(), AudioManagerFlash::Preload(), AudioManagerFMOD::Preload(), AudioManagerAndroid::Preload(), AudioManagerAudiere::Preload(), AudioManagerBBX::Preload(), VariantDB::Print(), BaseApp::PrintGLString(), Entity::PrintTreeAsText(), StreamingInstanceFile::Read(), StreamingInstance::ReadLineOfText(), RemoveFile(), GamepadManager::RemoveProviderByName(), BaseApp::ResetTouches(), RTCreateDirectory(), ProtonTester::runAllTests(), Variant::Save(), SDLEventLoop(), Gamepad::SendArcadeDirectionByDegrees(), Gamepad::SendArcadeDirectionByKey(), IAPManager::SendUnexpectedPurchaseSignal(), SeparateStringSTL(), VariantList::SerializeFromMem(), Gamepad::SetAxis(), SetFilterSetting(), BaseApp::SetManualRotationMode(), AudioManagerFlash::SetMusicVol(), AudioManagerBBX::SetMusicVol(), AudioManagerAndroid::SetPos(), AdManager::SetTapjoyFeatureAppVisible(), SetupScreenInfo(), AdProvider::ShowInterstitial(), AdProviderChartBoost::ShowInterstitial(), AdProvider::ShowMoreApps(), AudioManagerBBX::StopMusic(), IAPManager::SyncPurchases(), AudioManagerFlash::Testy(), IAPManager::Update(), NetSocket::UpdateRead(), AudioManager::Vibrate(), Gamepad::~Gamepad(), and InputTextRenderComponent::~InputTextRenderComponent().
std::string OrientationAsStringDisplay (eOrientationMode orientation)
Returns a string representation of an orientation mode for display purposes.
This string can be used to display a textual representation of an orientation mode for the user or put it to a log for example. The strings returned by this method may change from Proton version to another.
Definition at line 90 of file PlatformSetup.cpp.
References ORIENTATION_DONT_CARE, ORIENTATION_LANDSCAPE_LEFT, ORIENTATION_LANDSCAPE_RIGHT, ORIENTATION_PORTRAIT, and ORIENTATION_PORTRAIT_UPSIDE_DOWN.
Referenced by VideoModeSelector::modesAsString().
std::string PlatformIDAsString (ePlatformID platformID)
Returns a string representation of a platform identifier.
This string is not meant for display purposes. The strings returned by this method are guaranteed to remain unchanged between different versions of Proton (expect new string may be added for new platforms).
See also:
PlatformIDAsStringDisplay()
Definition at line 34 of file PlatformSetup.cpp.
References PLATFORM_ID_ANDROID, PLATFORM_ID_BBX, PLATFORM_ID_IOS, PLATFORM_ID_LINUX, PLATFORM_ID_OSX, PLATFORM_ID_UNKNOWN, PLATFORM_ID_WEBOS, PLATFORM_ID_WINDOWS, and PLATFORM_ID_WINDOWS_MOBILE.
Referenced by GetPlatformName().
std::string PlatformIDAsStringDisplay (ePlatformID platformID)
Returns a string representation of a platform identifier for display purposes.
This string can be used to display a textual representation of a platform for the user or put it to a log for example. The strings returned by this method may change from Proton version to another.
See also:
PlatformIDAsString()
Definition at line 71 of file PlatformSetup.cpp.
References PLATFORM_ID_ANDROID, PLATFORM_ID_BBX, PLATFORM_ID_IOS, PLATFORM_ID_LINUX, PLATFORM_ID_OSX, PLATFORM_ID_UNKNOWN, PLATFORM_ID_WEBOS, PLATFORM_ID_WINDOWS, and PLATFORM_ID_WINDOWS_MOBILE.
Referenced by VideoModeSelector::modesAsString().
ePlatformID PlatformStringAsID (std::string platform)
void SetEmulatedPlatformID (ePlatformID platformID)
Definition at line 119 of file PlatformSetup.cpp.
References g_emulatedPlatformID.
Referenced by main().
void SetMarketID (eMarketID marketID)
Definition at line 109 of file PlatformSetup.cpp.
References g_marketID.
Variable Documentation
const uint16 C_JPG_HEADER_MARKER = 55551
Definition at line 65 of file PlatformSetup.h.
Referenced by SoftSurface::LoadFileFromMemory(), and Surface::LoadFileFromMemory().
const uint32 PURE_WHITE = MAKE_RGBA(255, 255, 255, 255)
Definition at line 83 of file PlatformSetup.h.
Referenced by Surface::ApplyBlendingMode(), SpriteAnimationRenderComponent::OnAdd(), and Surface::RemoveBlendingMode().