Proton: PlatformEnums.h File Reference
PlatformEnums.h File Reference
Enumerations
enum eNetworkType { C_NETWORK_NONE, C_NETWORK_CELL, C_NETWORK_WIFI }
enum eDeviceMemoryClass { C_DEVICE_MEMORY_CLASS_1, C_DEVICE_MEMORY_CLASS_2, C_DEVICE_MEMORY_CLASS_3, C_DEVICE_MEMORY_CLASS_4 }
enum ePlatformID {
PLATFORM_ID_UNKNOWN = -1, PLATFORM_ID_WINDOWS, PLATFORM_ID_IOS, PLATFORM_ID_OSX,
PLATFORM_ID_LINUX, PLATFORM_ID_ANDROID, PLATFORM_ID_WINDOWS_MOBILE, PLATFORM_ID_WEBOS,
PLATFORM_ID_BBX, PLATFORM_ID_FLASH, PLATFORM_ID_COUNT
}
enum eMarketID { MARKET_ID_UNSPECIFIED, MARKET_ID_ANDROID_MARKET, MARKET_ID_APPLE_APPSTORE, MARKET_ID_AMAZON_MARKET }
enum eOrientationMode {
ORIENTATION_DONT_CARE, ORIENTATION_PORTRAIT = 1, ORIENTATION_PORTRAIT_UPSIDE_DOWN, ORIENTATION_LANDSCAPE_LEFT,
ORIENTATION_LANDSCAPE_RIGHT
}
Functions
ePlatformID GetPlatformID ()
Gets the platform id of the real running environment.
ePlatformID GetEmulatedPlatformID ()
Gets the emulated platform id.
void NotifyOSOfOrientationPreference (eOrientationMode orientation)
std::string GetBaseAppPath ()
std::string GetSavePath ()
std::string GetAppCachePath ()
void SetAppCachePath (std::string path)
void CreateAppCacheDirIfNeeded ()
bool LaterThanNow (const int year, const int month, const int day)
bool CheckDay (const int year, const int month, const int day)
unsigned int GetSystemTimeTick ()
double GetSystemTimeAccurate ()
unsigned int GetFreeMemory ()
unsigned int GetNativeMemoryUsed ()
void LaunchURL (std::string url)
void FireAchievement (std::string achievement)
void LogMsg (const char *lpFormat,...)
void LogError (const char *traceStr,...)
void SetLastStringInput (std::string s)
std::string GetLastStringInput ()
void RemoveFile (std::string fileName, bool bAddSavePath=true)
void CreateDirectoryRecursively (std::string basePath, std::string path)
bool RemoveDirectoryRecursively (std::string path)
std::vector< std::string > GetDirectoriesAtPath (std::string path)
std::vector< std::string > GetFilesAtPath (std::string path)
std::string GetRegionString ()
bool IsAppInstalled (std::string packageName)
bool IsIphone ()
bool IsIPAD ()
bool IsIphoneOriPad ()
bool IsIPhone3GS ()
bool IsIphone4 ()
int GetPrimaryGLX ()
int GetPrimaryGLY ()
int GetSystemData ()
eNetworkType IsNetReachable (std::string url)
void InitDeviceScreenInfo ()
eDeviceMemoryClass GetDeviceMemoryClass ()
bool IsIPodTouchThirdGen ()
std::string GetClipboardText ()
void SetClipboardText (std::string)
float GetDeviceOSVersion ()
std::string GetMacAddress ()
bool IsDesktop ()
Checks if the currently emulated platform is a desktop platform.
bool HasVibration ()
std::string GetDeviceID ()
void ForceVideoUpdate ()
std::string GetDateAndTimeAsString ()
void GetDateAndTime (int *monthOut, int *dayOut, int *yearOut, int *hourOut, int *minOut, int *secOut)
Enumeration Type Documentation
enum eDeviceMemoryClass
Enumerator:
C_DEVICE_MEMORY_CLASS_1
C_DEVICE_MEMORY_CLASS_2
C_DEVICE_MEMORY_CLASS_3
C_DEVICE_MEMORY_CLASS_4
Definition at line 38 of file PlatformEnums.h.
enum eMarketID
Enumerator:
MARKET_ID_UNSPECIFIED
MARKET_ID_ANDROID_MARKET
MARKET_ID_APPLE_APPSTORE
MARKET_ID_AMAZON_MARKET
Definition at line 63 of file PlatformEnums.h.
enum eNetworkType
Enumerator:
C_NETWORK_NONE
C_NETWORK_CELL
C_NETWORK_WIFI
Definition at line 31 of file PlatformEnums.h.
enum eOrientationMode
Enumerator:
ORIENTATION_DONT_CARE
ORIENTATION_PORTRAIT
ORIENTATION_PORTRAIT_UPSIDE_DOWN
ORIENTATION_LANDSCAPE_LEFT
ORIENTATION_LANDSCAPE_RIGHT
Definition at line 71 of file PlatformEnums.h.
enum ePlatformID
Enumerator:
PLATFORM_ID_UNKNOWN
PLATFORM_ID_WINDOWS
PLATFORM_ID_IOS
PLATFORM_ID_OSX
PLATFORM_ID_LINUX
PLATFORM_ID_ANDROID
PLATFORM_ID_WINDOWS_MOBILE
PLATFORM_ID_WEBOS
PLATFORM_ID_BBX
PLATFORM_ID_FLASH
PLATFORM_ID_COUNT
Definition at line 46 of file PlatformEnums.h.
Function Documentation
bool CheckDay (const int year, const int month, const int day)
Definition at line 381 of file AndroidUtils.cpp.
References LogMsg().
void CreateAppCacheDirIfNeeded ()
Definition at line 729 of file AndroidUtils.cpp.
void CreateDirectoryRecursively (std::string basePath, std::string path)
void FireAchievement (std::string achievement)
void ForceVideoUpdate ()
Definition at line 1225 of file AndroidUtils.cpp.
References RenderBatcher::Flush(), and g_globalBatcher.
std::string GetAppCachePath ()
Definition at line 221 of file AndroidUtils.cpp.
References g_appCachePath, GetAndroidMainClassName(), GetBundleName(), GetBundlePrefix(), GetJavaEnv(), GetSavePathBasic(), and LogMsg().
Referenced by AppResize(), and GetSavePath().
std::string GetBaseAppPath ()
Definition at line 114 of file AndroidUtils.cpp.
Referenced by TextScanner::AppendToFile(), FileManager::Copy(), FileManager::FileExists(), FileManager::Get(), FileManager::GetFileSize(), FileManager::GetStreaming(), IrrlichtManager::GetTexture(), LoadFileIntoMemoryBasic(), LogMsg(), AudioManagerSDL::Play(), AudioManagerAndroid::Play(), AudioManagerBBX::Play(), AudioManagerSDL::Preload(), AudioManagerFlash::Preload(), AudioManagerFMOD::Preload(), AudioManagerAndroid::Preload(), AudioManagerAudiere::Preload(), and AudioManagerBBX::Preload().
std::string GetClipboardText ()
Definition at line 294 of file AndroidUtils.cpp.
References GetAndroidMainClassName(), and GetJavaEnv().
void GetDateAndTime (int * monthOut, int * dayOut, int * yearOut, int * hourOut, int * minOut, int * secOut)
Definition at line 209 of file LinuxUtils.cpp.
std::string GetDateAndTimeAsString ()
Definition at line 196 of file LinuxUtils.cpp.
Referenced by LogMsg().
std::string GetDeviceID ()
Definition at line 342 of file AndroidUtils.cpp.
References GetAndroidMainClassName(), and GetJavaEnv().
eDeviceMemoryClass GetDeviceMemoryClass ()
Definition at line 376 of file AndroidUtils.cpp.
References C_DEVICE_MEMORY_CLASS_1, C_DEVICE_MEMORY_CLASS_2, and C_DEVICE_MEMORY_CLASS_3.
float GetDeviceOSVersion ()
Definition at line 370 of file AndroidUtils.cpp.
std::vector<std::string> GetDirectoriesAtPath (std::string path)
ePlatformID GetEmulatedPlatformID ()
Gets the emulated platform id.
Can be different from the real platform id. Can be set with SetEmulatedPlatformID(). By default this is the same as the real platform id.
Definition at line 13 of file PlatformSetup.cpp.
References g_emulatedPlatformID, GetPlatformID(), and PLATFORM_ID_UNKNOWN.
Referenced by AddPlatformNameURL(), IAPManager::BuyItem(), GetPlatformName(), IsDesktop(), BaseApp::OnEnterBackground(), BaseApp::OnEnterForeground(), PreloadKeyboard(), RenderClipComponent::RenderClipComponent(), ReplaceMP3(), ReplaceWithLargeInFileNameAndOSSpecific(), and LoopingSound::Update().
std::vector<std::string> GetFilesAtPath (std::string path)
unsigned int GetFreeMemory ()
Definition at line 477 of file AndroidUtils.cpp.
Referenced by BaseApp::Draw().
std::string GetLastStringInput ()
Definition at line 489 of file AndroidUtils.cpp.
References g_string.
std::string GetMacAddress ()
Definition at line 359 of file AndroidUtils.cpp.
unsigned int GetNativeMemoryUsed ()
Definition at line 182 of file FlashUtils.cpp.
Referenced by BaseApp::Draw().
ePlatformID GetPlatformID ()
Gets the platform id of the real running environment.
The emulated platform can be different from this one.
Definition at line 322 of file AndroidUtils.cpp.
References PLATFORM_ID_ANDROID, PLATFORM_ID_FLASH, and PLATFORM_ID_LINUX.
Referenced by AppendStringToFile(), TextScanner::AppendToFile(), GetEmulatedPlatformID(), and BaseApp::OnEnterBackground().
int GetPrimaryGLX ()
Definition at line 83 of file AndroidUtils.cpp.
References g_nativeScreenWidth, and g_winVideoScreenX.
Referenced by AppRender(), AppResize(), ConvertFakeScreenRectToReal(), Surface::CopyFromScreen(), RenderScissorComponent::FilterOnRender(), GetOGLPos(), IrrlichtManager::Init(), InitBaseScreenSizeFromPrimary(), initSDL_GLES(), main(), NeedToUseFakeScreenSize(), BaseApp::OnFullscreenToggleRequest(), SDLEventLoop(), SetLockedLandscape(), and SetupScreenInfo().
int GetPrimaryGLY ()
Definition at line 88 of file AndroidUtils.cpp.
References g_nativeScreenHeight, and g_winVideoScreenY.
Referenced by AppRender(), AppResize(), ConvertFakeScreenRectToReal(), Surface::CopyFromScreen(), RenderScissorComponent::FilterOnRender(), GetOGLPos(), IrrlichtManager::Init(), InitBaseScreenSizeFromPrimary(), initSDL_GLES(), main(), NeedToUseFakeScreenSize(), BaseApp::OnFullscreenToggleRequest(), SDLEventLoop(), SetLockedLandscape(), and SetupScreenInfo().
std::string GetRegionString ()
Definition at line 536 of file AndroidUtils.cpp.
References GetAndroidMainClassName(), and GetJavaEnv().
Referenced by GetCountryCode().
std::string GetSavePath ()
Definition at line 175 of file AndroidUtils.cpp.
References g_preferSDCardForUserStorage, GetAppCachePath(), GetSavePathBasic(), and LogMsg().
Referenced by VariantDB::Load(), LoadFileIntoMemoryBasic(), RemoveFile(), VariantDB::Save(), and TextScanner::SaveFile().
int GetSystemData ()
Definition at line 499 of file AndroidUtils.cpp.
double GetSystemTimeAccurate ()
Definition at line 472 of file AndroidUtils.cpp.
References GetSystemTimeTick().
Referenced by GameTimer::Reset(), and GameTimer::Update().
unsigned int GetSystemTimeTick ()
Definition at line 442 of file AndroidUtils.cpp.
Referenced by AppResume(), AppUpdate(), NetSocket::GetIdleTimeMS(), GetSystemTimeAccurate(), NetSocket::Init(), profile_begin(), profile_end(), profile_init(), profile_tally(), CRandom::Randomize(), NetSocket::SetSocket(), NetSocket::UpdateRead(), and NetSocket::UpdateWrite().
bool HasVibration ()
Definition at line 738 of file AndroidUtils.cpp.
void InitDeviceScreenInfo ()
bool IsAppInstalled (std::string packageName)
bool IsDesktop ()
Checks if the currently emulated platform is a desktop platform.
Definition at line 316 of file AndroidUtils.cpp.
References GetEmulatedPlatformID(), PLATFORM_ID_ANDROID, PLATFORM_ID_LINUX, PLATFORM_ID_OSX, and PLATFORM_ID_WINDOWS.
Referenced by main().
bool IsIPAD ()
Definition at line 365 of file AndroidUtils.cpp.
Referenced by SetProtonPixelScaleFactor().
bool IsIphone ()
Definition at line 332 of file AndroidUtils.cpp.
bool IsIPhone3GS ()
Definition at line 311 of file AndroidUtils.cpp.
bool IsIphone4 ()
Definition at line 337 of file AndroidUtils.cpp.
bool IsIphoneOriPad ()
Definition at line 327 of file AndroidUtils.cpp.
bool IsIPodTouchThirdGen ()
eNetworkType IsNetReachable (std::string url)
bool LaterThanNow (const int year, const int month, const int day)
Definition at line 400 of file AndroidUtils.cpp.
References LogMsg().
void LaunchURL (std::string url)
void LogError (const char * traceStr, ...)
Definition at line 460 of file BaseApp.cpp.
void LogMsg (const char * lpFormat, ...)
Definition at line 93 of file AndroidUtils.cpp.
void NotifyOSOfOrientationPreference (eOrientationMode orientation)
Definition at line 734 of file AndroidUtils.cpp.
Referenced by SetupScreenInfo().
bool RemoveDirectoryRecursively (std::string path)
void RemoveFile (std::string fileName, bool bAddSavePath = true)
void SetAppCachePath (std::string path)
Definition at line 100 of file FlashUtils.cpp.
References g_appCachePath.
void SetClipboardText (std::string)
void SetLastStringInput (std::string s)