Proton: PlatformSetup.cpp File Reference
PlatformSetup.cpp File Reference
Functions
bool GetForceAspectRatioWhenResizing ()
ePlatformID GetEmulatedPlatformID ()
Gets the emulated platform id.
string AddPlatformNameURL ()
string PlatformIDAsString (ePlatformID platformID)
Returns a string representation of a platform identifier.
ePlatformID PlatformStringAsID (string platform)
string PlatformIDAsStringDisplay (ePlatformID platformID)
Returns a string representation of a platform identifier for display purposes.
string OrientationAsStringDisplay (eOrientationMode orientation)
Returns a string representation of an orientation mode for display purposes.
string GetPlatformName ()
void SetMarketID (eMarketID marketID)
eMarketID GetMarketID ()
void SetEmulatedPlatformID (ePlatformID platformID)
float GetScreenSizeXf ()
Returns the same as GetScreenSizeX() but as a float.
float GetScreenSizeYf ()
Returns the same as GetScreenSizeY() but as a float.
int GetScreenSizeX ()
Returns the current width of the scene viewport.
int GetScreenSizeY ()
Returns the current height of the scene viewport.
Variables
bool g_forceAspectRatioWhenChangingWindowSize = true
ePlatformID g_emulatedPlatformID = PLATFORM_ID_UNKNOWN
eMarketID g_marketID = MARKET_ID_UNSPECIFIED
Function Documentation
string AddPlatformNameURL ()
Definition at line 24 of file PlatformSetup.cpp.
References GetEmulatedPlatformID(), GetPlatformName(), and PLATFORM_ID_WINDOWS.
ePlatformID GetEmulatedPlatformID ()
Gets the emulated platform id.
Can be different from the real platform id. Can be set with SetEmulatedPlatformID(). By default this is the same as the real platform id.
Definition at line 13 of file PlatformSetup.cpp.
References g_emulatedPlatformID, GetPlatformID(), and PLATFORM_ID_UNKNOWN.
Referenced by AddPlatformNameURL(), IAPManager::BuyItem(), GetPlatformName(), IsDesktop(), BaseApp::OnEnterBackground(), BaseApp::OnEnterForeground(), PreloadKeyboard(), RenderClipComponent::RenderClipComponent(), ReplaceMP3(), ReplaceWithLargeInFileNameAndOSSpecific(), and LoopingSound::Update().
bool GetForceAspectRatioWhenResizing ()
Definition at line 5 of file PlatformSetup.cpp.
References g_forceAspectRatioWhenChangingWindowSize.
eMarketID GetMarketID ()
Definition at line 114 of file PlatformSetup.cpp.
References g_marketID.
string GetPlatformName ()
Definition at line 103 of file PlatformSetup.cpp.
References GetEmulatedPlatformID(), and PlatformIDAsString().
Referenced by AddPlatformNameURL().
int GetScreenSizeX ()
Returns the current width of the scene viewport.
Usually this is the same as the width of the application window. But it can be also different if the fake screen size mode is used.
Definition at line 127 of file PlatformSetup.cpp.
Referenced by GetOGLPos(), glDrawArraysEx(), glGetIntegerv(), AdManager::OnRender(), SetupFakePrimaryScreenSize(), and SlideScreen().
float GetScreenSizeXf ()
Returns the same as GetScreenSizeX() but as a float.
Definition at line 125 of file PlatformSetup.cpp.
Referenced by ConvertCoordinatesIfRequired(), EntityRetinaRemapIfNeeded(), EntityScaleiPad(), FadeScreen(), FadeScreenUp(), GetOGLPos(), GLFlashAdaptor_Initialize(), iPadMap(), iPadMapX(), iPhoneMap(), iPhoneMapX(), AdManager::OnRender(), BaseApp::OnScreenSizeChange(), OnShowTextMessage(), RemoveOrthoRenderSize(), RotateGUIPoint(), ScreenToWorld(), SetConsole(), SetupOrtho(), and SlideScreen().
int GetScreenSizeY ()
Returns the current height of the scene viewport.
Usually this is the same as the height of the application window. But it can be also different if the fake screen size mode is used.
Definition at line 128 of file PlatformSetup.cpp.
Referenced by GetOGLPos(), glDrawArraysEx(), glGetIntegerv(), glScissor(), AdManager::OnRender(), and SetupFakePrimaryScreenSize().
float GetScreenSizeYf ()
Returns the same as GetScreenSizeY() but as a float.
Definition at line 126 of file PlatformSetup.cpp.
Referenced by ConvertCoordinatesIfRequired(), EnforceMinimumFontLineToScreenRatio(), EntityRetinaRemapIfNeeded(), EntityScaleiPad(), FadeScreen(), FadeScreenUp(), GetFontAndScaleToFitThisLinesPerScreenY(), GetOGLPos(), GLFlashAdaptor_Initialize(), iPadMap(), iPadMapY(), iPhoneMap(), iPhoneMapY(), AdManager::OnRender(), BaseApp::OnScreenSizeChange(), OnShowTextMessage(), RemoveOrthoRenderSize(), ScreenToWorld(), SetConsole(), SetupOrtho(), and SlideScreenVertical().
string OrientationAsStringDisplay (eOrientationMode orientation)
Returns a string representation of an orientation mode for display purposes.
This string can be used to display a textual representation of an orientation mode for the user or put it to a log for example. The strings returned by this method may change from Proton version to another.
Definition at line 90 of file PlatformSetup.cpp.
References ORIENTATION_DONT_CARE, ORIENTATION_LANDSCAPE_LEFT, ORIENTATION_LANDSCAPE_RIGHT, ORIENTATION_PORTRAIT, and ORIENTATION_PORTRAIT_UPSIDE_DOWN.
Referenced by VideoModeSelector::modesAsString().
string PlatformIDAsString (ePlatformID platformID)
Returns a string representation of a platform identifier.
This string is not meant for display purposes. The strings returned by this method are guaranteed to remain unchanged between different versions of Proton (expect new string may be added for new platforms).
See also:
PlatformIDAsStringDisplay()
Definition at line 34 of file PlatformSetup.cpp.
References PLATFORM_ID_ANDROID, PLATFORM_ID_BBX, PLATFORM_ID_IOS, PLATFORM_ID_LINUX, PLATFORM_ID_OSX, PLATFORM_ID_UNKNOWN, PLATFORM_ID_WEBOS, PLATFORM_ID_WINDOWS, and PLATFORM_ID_WINDOWS_MOBILE.
Referenced by GetPlatformName().
string PlatformIDAsStringDisplay (ePlatformID platformID)
Returns a string representation of a platform identifier for display purposes.
This string can be used to display a textual representation of a platform for the user or put it to a log for example. The strings returned by this method may change from Proton version to another.
See also:
PlatformIDAsString()
Definition at line 71 of file PlatformSetup.cpp.
References PLATFORM_ID_ANDROID, PLATFORM_ID_BBX, PLATFORM_ID_IOS, PLATFORM_ID_LINUX, PLATFORM_ID_OSX, PLATFORM_ID_UNKNOWN, PLATFORM_ID_WEBOS, PLATFORM_ID_WINDOWS, and PLATFORM_ID_WINDOWS_MOBILE.
Referenced by VideoModeSelector::modesAsString().
ePlatformID PlatformStringAsID (string platform)
Definition at line 56 of file PlatformSetup.cpp.
References PLATFORM_ID_ANDROID, PLATFORM_ID_BBX, PLATFORM_ID_IOS, PLATFORM_ID_LINUX, PLATFORM_ID_OSX, PLATFORM_ID_UNKNOWN, PLATFORM_ID_WEBOS, PLATFORM_ID_WINDOWS, and PLATFORM_ID_WINDOWS_MOBILE.
void SetEmulatedPlatformID (ePlatformID platformID)
Definition at line 119 of file PlatformSetup.cpp.
References g_emulatedPlatformID.
Referenced by main().
void SetMarketID (eMarketID marketID)
Definition at line 109 of file PlatformSetup.cpp.
References g_marketID.
Variable Documentation
ePlatformID g_emulatedPlatformID = PLATFORM_ID_UNKNOWN
Definition at line 9 of file PlatformSetup.cpp.
Referenced by GetEmulatedPlatformID(), and SetEmulatedPlatformID().
bool g_forceAspectRatioWhenChangingWindowSize = true
Definition at line 3 of file PlatformSetup.cpp.
Referenced by GetForceAspectRatioWhenResizing().
eMarketID g_marketID = MARKET_ID_UNSPECIFIED
Definition at line 10 of file PlatformSetup.cpp.
Referenced by GetMarketID(), and SetMarketID().