Proton: PPlot.cpp File Reference
PPlot.cpp File Reference
Functions
template<class T >
const T & PMin (const T &a, const T &b)
template<class T >
const T & PMax (const T &a, const T &b)
float SafeLog (float inFloat, float inBase, float inFac)
float SafeExp (float inFloat, float inBase, float inFac)
float GetMaxFromRange (const PlotDataBase &inData, long inStartIndex, long inEndIndex)
void FindRange (const PlotDataBase &inData, float inMin, float inMax, long &outStartIndex, long &outEndIndex)
bool MakeExamplePlot (int inExample, PPlot &ioPPlot)
void MakeExamplePlot1 (PPlot &ioPPlot)
void MakeExamplePlot2 (PPlot &ioPPlot)
void MakeExamplePlot3 (PPlot &ioPPlot)
void MakeExamplePlot4 (PPlot &ioPPlot)
void MakeExamplePlot5 (PPlot &ioPPlot)
void MakeExamplePlot6 (PPlot &ioPPlot)
void MakeExamplePlot7 (PPlot &ioPPlot)
void MakeExamplePlot8 (PPlot &ioPPlot)
void MakePainterTester (PPlot &ioPPlot)
void SetCurrentPPlot (PPlot *inPPlot)
PPlot & GetCurrentPPlot ()
void MakeCopy (const PPlot &inPPlot, PPlot &outPPlot)
Variables
static PPlot * sCurrentPPlot = 0
const float kFloatSmall = 1e-20f
const float kLogMin = 1e-10f
const float kExpMax = 1e10f
const float kLogMinClipValue = 1e-10f
const float kEps = 1e-4f
const float kRelMajorTickSize = 0.02f
const float kRelMinorTickSize = 0.01f
const int kMinMinorTickScreenSize = 1
const float kMaxMajorTickSizeInFontHeight = 0.5f
const float kLittleIncrease = 1.0001f
const float kLittleDecrease = 0.9999f
const float kTickValueVeryBig = 1.0e4
const float kTickValueVerySmall = (float)1.0e-3
const float kMajorTickXInitialFac = 2.0f
const float kMajorTickYInitialFac = 3.0f
const PMargins kDefaultMargins = PMargins (40,20,5,42)
Function Documentation
void FindRange (const PlotDataBase & inData, float inMin, float inMax, long & outStartIndex, long & outEndIndex)
Definition at line 1403 of file PPlot.cpp.
References PlotDataBase::GetSize(), and PlotDataBase::GetValue().
Referenced by LineDataDrawer::DrawData().
PPlot& GetCurrentPPlot ()
Definition at line 2136 of file PPlot.cpp.
References sCurrentPPlot.
float GetMaxFromRange (const PlotDataBase & inData, long inStartIndex, long inEndIndex)
Definition at line 1383 of file PPlot.cpp.
References PlotDataBase::GetValue().
Referenced by LineDataDrawer::DrawData().
void MakeCopy (const PPlot & inPPlot, PPlot & outPPlot)
Definition at line 2149 of file PPlot.cpp.
References PlotDataContainer::AddXYPlot(), DataDrawerBase::Clone(), PlotDataContainer::GetConstDataDrawer(), PlotDataContainer::GetConstLegendData(), PlotDataContainer::GetConstXData(), PlotDataContainer::GetConstYData(), PlotDataContainer::GetPlotCount(), PPlot::mGridInfo, PPlot::mMargins, PPlot::mPlotBackground, PPlot::mPlotDataContainer, PPlot::mXAxisSetup, and PPlot::mYAxisSetup.
bool MakeExamplePlot (int inExample, PPlot & ioPPlot)
Definition at line 1865 of file PPlot.cpp.
References MakeExamplePlot1(), MakeExamplePlot2(), MakeExamplePlot3(), MakeExamplePlot4(), MakeExamplePlot5(), MakeExamplePlot6(), MakeExamplePlot7(), and MakeExamplePlot8().
void MakeExamplePlot1 (PPlot & ioPPlot)
Definition at line 1903 of file PPlot.cpp.
References PlotDataContainer::AddXYPlot(), PlotDataContainer::GetLegendData(), PStyle::mFontSize, AxisSetup::mLabel, PPlot::mMargins, PStyle::mPenWidth, PPlot::mPlotBackground, PPlot::mPlotDataContainer, LegendData::mStyle, LineDataDrawer::mStyle, TickInfo::mStyle, AxisSetup::mStyle, PlotBackground::mStyle, AxisSetup::mTickInfo, PlotBackground::mTitle, PMargins::mTop, PPlot::mXAxisSetup, and PPlot::mYAxisSetup.
void MakeExamplePlot2 (PPlot & ioPPlot)
Definition at line 1947 of file PPlot.cpp.
References PlotDataContainer::AddXYPlot(), AxisSetup::mAscending, AxisSetup::mCrossOrigin, PStyle::mFontSize, AxisSetup::mLabel, PPlot::mMargins, AxisSetup::mMax, AxisSetup::mMin, PPlot::mPlotBackground, PPlot::mPlotDataContainer, PlotBackground::mPlotRegionBackColor, PMargins::mRight, PlotBackground::mStyle, PlotBackground::mTitle, PMargins::mTop, PlotBackground::mTransparent, PPlot::mXAxisSetup, PPlot::mYAxisSetup, and AxisSetup::SetAutoScale().
void MakeExamplePlot3 (PPlot & ioPPlot)
Definition at line 1988 of file PPlot.cpp.
References PlotDataContainer::AddXYPlot(), PMargins::mBottom, PMargins::mLeft, PPlot::mMargins, PPlot::mPlotBackground, PPlot::mPlotDataContainer, PlotBackground::mPlotRegionBackColor, PMargins::mRight, PlotBackground::mTitle, PMargins::mTop, and PlotBackground::mTransparent.
Referenced by MakeExamplePlot().
void MakeExamplePlot4 (PPlot & ioPPlot)
Definition at line 2009 of file PPlot.cpp.
References PlotDataContainer::AddXYPlot(), LegendData::mColor, PPlot::mGridInfo, PMargins::mLeft, AxisSetup::mLogBase, AxisSetup::mLogScale, PPlot::mMargins, LegendData::mName, PPlot::mPlotDataContainer, PMargins::mTop, PPlot::mXAxisSetup, GridInfo::mXGridOn, PPlot::mYAxisSetup, and GridInfo::mYGridOn.
Referenced by MakeExamplePlot().
void MakeExamplePlot5 (PPlot & ioPPlot)
Definition at line 2032 of file PPlot.cpp.
References StringData::AddItem(), PlotDataContainer::AddXYPlot(), LegendData::mColor, PMargins::mLeft, PPlot::mMargins, LegendData::mName, PPlot::mPlotDataContainer, and PMargins::mTop.
Referenced by MakeExamplePlot().
void MakeExamplePlot6 (PPlot & ioPPlot)
Definition at line 2052 of file PPlot.cpp.
References PlotDataContainer::AddXYPlot(), LineDataDrawer::mDrawLine, LineDataDrawer::mDrawPoint, PMargins::mLeft, PPlot::mMargins, PStyle::mPenWidth, PPlot::mPlotBackground, PPlot::mPlotDataContainer, LineDataDrawer::mStyle, PlotBackground::mTitle, and PMargins::mTop.
Referenced by MakeExamplePlot().
void MakeExamplePlot7 (PPlot & ioPPlot)
Definition at line 2085 of file PPlot.cpp.
References PlotDataContainer::AddXYPlot(), LegendData::mColor, PPlot::mGridInfo, PMargins::mLeft, AxisSetup::mLogFactor, AxisSetup::mLogScale, PPlot::mMargins, LegendData::mName, PPlot::mPlotDataContainer, PMargins::mTop, GridInfo::mXGridOn, PPlot::mYAxisSetup, and GridInfo::mYGridOn.
Referenced by MakeExamplePlot().
void MakeExamplePlot8 (PPlot & ioPPlot)
Definition at line 2107 of file PPlot.cpp.
References PlotDataContainer::AddXYPlot(), LegendData::mColor, PMargins::mLeft, PPlot::mMargins, LegendData::mName, PPlot::mPlotBackground, PPlot::mPlotDataContainer, PlotBackground::mTitle, and PMargins::mTop.
Referenced by MakeExamplePlot().
void MakePainterTester (PPlot & ioPPlot)
Definition at line 2128 of file PPlot.cpp.
References PPlot::SetPPlotDrawer().
template<class T > const T& PMax (const T & a, const T & b)
Definition at line 43 of file PPlot.cpp.
Referenced by LinTickIterator::InitFromRanges(), and LogTickIterator::InitFromRanges().
template<class T > const T& PMin (const T & a, const T & b)
Definition at line 40 of file PPlot.cpp.
float SafeExp (float inFloat, float inBase, float inFac)
Definition at line 54 of file PPlot.cpp.
References kExpMax.
Referenced by LogTickIterator::AdjustRange(), LogTickIterator::GetNextTick(), LogTickIterator::Init(), and LogTrafo::TransformBack().
float SafeLog (float inFloat, float inBase, float inFac)
Definition at line 47 of file PPlot.cpp.
References kLogMin.
Referenced by PPlot::CalculateLogTransformation(), LogTickIterator::GetNextTick(), LogTickIterator::Init(), LogTickIterator::RoundDown(), LogTickIterator::RoundUp(), and LogTrafo::Transform().
void SetCurrentPPlot (PPlot * inPPlot)
Definition at line 2132 of file PPlot.cpp.
References sCurrentPPlot.
Variable Documentation
const PMargins kDefaultMargins = PMargins (40,20,5,42)
Definition at line 36 of file PPlot.cpp.
Referenced by PPlot::PPlot().
const float kEps = 1e-4f
Definition at line 25 of file PPlot.cpp.
Referenced by LogTickIterator::GetNextTick().
const float kExpMax = 1e10f
Definition at line 23 of file PPlot.cpp.
Referenced by SafeExp().
const float kFloatSmall = 1e-20f
Definition at line 21 of file PPlot.cpp.
Referenced by PPlot::CalculateLinTransformation(), PPlot::CalculateLogTransformation(), LinTickIterator::InitFromRanges(), and LogTickIterator::InitFromRanges().
const float kLittleDecrease = 0.9999f
Definition at line 31 of file PPlot.cpp.
Referenced by LogTickIterator::AdjustRange(), and LogTickIterator::Init().
const float kLittleIncrease = 1.0001f
Definition at line 30 of file PPlot.cpp.
Referenced by LogTickIterator::AdjustRange(), LinTickIterator::GetNextTick(), and LogTickIterator::GetNextTick().
const float kLogMin = 1e-10f
Definition at line 22 of file PPlot.cpp.
Referenced by SafeLog().
const float kLogMinClipValue = 1e-10f
Definition at line 24 of file PPlot.cpp.
Referenced by LogTickIterator::AdjustRange(), PPlot::CalculateAxisRanges(), PPlot::CheckRange(), and LogTrafo::Transform().
const float kMajorTickXInitialFac = 2.0f
Definition at line 34 of file PPlot.cpp.
Referenced by PPlot::CalculateTickInfo().
const float kMajorTickYInitialFac = 3.0f
Definition at line 35 of file PPlot.cpp.
Referenced by PPlot::CalculateTickInfo().
const float kMaxMajorTickSizeInFontHeight = 0.5f
Definition at line 29 of file PPlot.cpp.
Referenced by PPlot::SetTickSizes().
const int kMinMinorTickScreenSize = 1
Definition at line 28 of file PPlot.cpp.
Referenced by LinTickIterator::InitFromRanges(), and LogTickIterator::InitFromRanges().
const float kRelMajorTickSize = 0.02f
Definition at line 26 of file PPlot.cpp.
Referenced by LinTickIterator::InitFromRanges(), LogTickIterator::InitFromRanges(), and PPlot::SetTickSizes().
const float kRelMinorTickSize = 0.01f
Definition at line 27 of file PPlot.cpp.
Referenced by LinTickIterator::InitFromRanges(), LogTickIterator::InitFromRanges(), and PPlot::SetTickSizes().
const float kTickValueVeryBig = 1.0e4
Definition at line 32 of file PPlot.cpp.
Referenced by TickInfo::MakeFormatString().
const float kTickValueVerySmall = (float)1.0e-3
Definition at line 33 of file PPlot.cpp.
Referenced by TickInfo::MakeFormatString().
PPlot* sCurrentPPlot = 0 [static]
Definition at line 19 of file PPlot.cpp.
Referenced by GetCurrentPPlot(), and SetCurrentPPlot().