Proton: pplot.h File Reference
pplot.h File Reference
Classes
class PStyle
class CalculatedDataBase
class PlotDataBase
class PlotDataPointer
class PlotData
class CalculatedData
class CalculatedPlotData
class DummyData
class StringData
class PRect
class PMargins
class PColor
class LegendData
class PlotDataSelection
class Painter
class DummyPainter
class DataDrawerBase
class LineDataDrawer
class DotDataDrawer
class BarDataDrawer
class PlotDataContainer
class GridInfo
class TickInfo
class AxisSetup
class Trafo
class LinTrafo
class LogTrafo
class TickIterator
class LinTickIterator
class LogTickIterator
class NamedTickIterator
class PlotBackground
class PDrawer
class PCalculator
class PainterTester
class PPlot
Typedefs
typedef vector< float > RealPlotData
typedef vector< PlotDataBase * > PlotDataList
typedef vector< LegendData * > LegendDataList
typedef vector
< PlotDataSelection * > PlotDataSelectionList
typedef vector< DataDrawerBase * > DataDrawerList
Functions
float SafeLog (float inFloat, float inBase, float inFac=1)
float SafeExp (float inFloat, float inBase, float inFac=1)
bool MakeExamplePlot (int inExample, PPlot &ioPPlot)
void MakeExamplePlot1 (PPlot &ioPPlot)
void MakeExamplePlot2 (PPlot &ioPPlot)
void MakeExamplePlot3 (PPlot &ioPPlot)
void MakeExamplePlot4 (PPlot &ioPPlot)
void MakeExamplePlot5 (PPlot &ioPPlot)
void MakeExamplePlot6 (PPlot &ioPPlot)
void MakeExamplePlot7 (PPlot &ioPPlot)
void MakeExamplePlot8 (PPlot &ioPPlot)
void MakePainterTester (PPlot &ioPPlot)
void MakeCopy (const PPlot &inPPlot, PPlot &outPPlot)
void SetCurrentPPlot (PPlot *inPPlot)
PPlot & GetCurrentPPlot ()
Typedef Documentation
typedef vector<DataDrawerBase *> DataDrawerList
Definition at line 230 of file pplot.h.
typedef vector<LegendData *> LegendDataList
Definition at line 159 of file pplot.h.
typedef vector<PlotDataBase *> PlotDataList
Definition at line 51 of file pplot.h.
typedef vector<PlotDataSelection *> PlotDataSelectionList
Definition at line 169 of file pplot.h.
typedef vector<float> RealPlotData
Definition at line 22 of file pplot.h.
Function Documentation
PPlot& GetCurrentPPlot ()
Definition at line 2136 of file PPlot.cpp.
References sCurrentPPlot.
void MakeCopy (const PPlot & inPPlot, PPlot & outPPlot)
Definition at line 2149 of file PPlot.cpp.
References PlotDataContainer::AddXYPlot(), DataDrawerBase::Clone(), PlotDataContainer::GetConstDataDrawer(), PlotDataContainer::GetConstLegendData(), PlotDataContainer::GetConstXData(), PlotDataContainer::GetConstYData(), PlotDataContainer::GetPlotCount(), PPlot::mGridInfo, PPlot::mMargins, PPlot::mPlotBackground, PPlot::mPlotDataContainer, PPlot::mXAxisSetup, and PPlot::mYAxisSetup.
bool MakeExamplePlot (int inExample, PPlot & ioPPlot)
Definition at line 1865 of file PPlot.cpp.
References MakeExamplePlot1(), MakeExamplePlot2(), MakeExamplePlot3(), MakeExamplePlot4(), MakeExamplePlot5(), MakeExamplePlot6(), MakeExamplePlot7(), and MakeExamplePlot8().
void MakeExamplePlot1 (PPlot & ioPPlot)
Definition at line 1903 of file PPlot.cpp.
References PlotDataContainer::AddXYPlot(), PlotDataContainer::GetLegendData(), PStyle::mFontSize, AxisSetup::mLabel, PPlot::mMargins, PStyle::mPenWidth, PPlot::mPlotBackground, PPlot::mPlotDataContainer, LegendData::mStyle, LineDataDrawer::mStyle, TickInfo::mStyle, AxisSetup::mStyle, PlotBackground::mStyle, AxisSetup::mTickInfo, PlotBackground::mTitle, PMargins::mTop, PPlot::mXAxisSetup, and PPlot::mYAxisSetup.
void MakeExamplePlot2 (PPlot & ioPPlot)
Definition at line 1947 of file PPlot.cpp.
References PlotDataContainer::AddXYPlot(), AxisSetup::mAscending, AxisSetup::mCrossOrigin, PStyle::mFontSize, AxisSetup::mLabel, PPlot::mMargins, AxisSetup::mMax, AxisSetup::mMin, PPlot::mPlotBackground, PPlot::mPlotDataContainer, PlotBackground::mPlotRegionBackColor, PMargins::mRight, PlotBackground::mStyle, PlotBackground::mTitle, PMargins::mTop, PlotBackground::mTransparent, PPlot::mXAxisSetup, PPlot::mYAxisSetup, and AxisSetup::SetAutoScale().
void MakeExamplePlot3 (PPlot & ioPPlot)
Definition at line 1988 of file PPlot.cpp.
References PlotDataContainer::AddXYPlot(), PMargins::mBottom, PMargins::mLeft, PPlot::mMargins, PPlot::mPlotBackground, PPlot::mPlotDataContainer, PlotBackground::mPlotRegionBackColor, PMargins::mRight, PlotBackground::mTitle, PMargins::mTop, and PlotBackground::mTransparent.
Referenced by MakeExamplePlot().
void MakeExamplePlot4 (PPlot & ioPPlot)
Definition at line 2009 of file PPlot.cpp.
References PlotDataContainer::AddXYPlot(), LegendData::mColor, PPlot::mGridInfo, PMargins::mLeft, AxisSetup::mLogBase, AxisSetup::mLogScale, PPlot::mMargins, LegendData::mName, PPlot::mPlotDataContainer, PMargins::mTop, PPlot::mXAxisSetup, GridInfo::mXGridOn, PPlot::mYAxisSetup, and GridInfo::mYGridOn.
Referenced by MakeExamplePlot().
void MakeExamplePlot5 (PPlot & ioPPlot)
Definition at line 2032 of file PPlot.cpp.
References StringData::AddItem(), PlotDataContainer::AddXYPlot(), LegendData::mColor, PMargins::mLeft, PPlot::mMargins, LegendData::mName, PPlot::mPlotDataContainer, and PMargins::mTop.
Referenced by MakeExamplePlot().
void MakeExamplePlot6 (PPlot & ioPPlot)
Definition at line 2052 of file PPlot.cpp.
References PlotDataContainer::AddXYPlot(), LineDataDrawer::mDrawLine, LineDataDrawer::mDrawPoint, PMargins::mLeft, PPlot::mMargins, PStyle::mPenWidth, PPlot::mPlotBackground, PPlot::mPlotDataContainer, LineDataDrawer::mStyle, PlotBackground::mTitle, and PMargins::mTop.
Referenced by MakeExamplePlot().
void MakeExamplePlot7 (PPlot & ioPPlot)
Definition at line 2085 of file PPlot.cpp.
References PlotDataContainer::AddXYPlot(), LegendData::mColor, PPlot::mGridInfo, PMargins::mLeft, AxisSetup::mLogFactor, AxisSetup::mLogScale, PPlot::mMargins, LegendData::mName, PPlot::mPlotDataContainer, PMargins::mTop, GridInfo::mXGridOn, PPlot::mYAxisSetup, and GridInfo::mYGridOn.
Referenced by MakeExamplePlot().
void MakeExamplePlot8 (PPlot & ioPPlot)
Definition at line 2107 of file PPlot.cpp.
References PlotDataContainer::AddXYPlot(), LegendData::mColor, PMargins::mLeft, PPlot::mMargins, LegendData::mName, PPlot::mPlotBackground, PPlot::mPlotDataContainer, PlotBackground::mTitle, and PMargins::mTop.
Referenced by MakeExamplePlot().
void MakePainterTester (PPlot & ioPPlot)
Definition at line 2128 of file PPlot.cpp.
References PPlot::SetPPlotDrawer().
float SafeExp (float inFloat, float inBase, float inFac = 1)
Definition at line 54 of file PPlot.cpp.
References kExpMax.
Referenced by LogTickIterator::AdjustRange(), LogTickIterator::GetNextTick(), LogTickIterator::Init(), and LogTrafo::TransformBack().
float SafeLog (float inFloat, float inBase, float inFac = 1)
Definition at line 47 of file PPlot.cpp.
References kLogMin.
Referenced by PPlot::CalculateLogTransformation(), LogTickIterator::GetNextTick(), LogTickIterator::Init(), LogTickIterator::RoundDown(), LogTickIterator::RoundUp(), and LogTrafo::Transform().
void SetCurrentPPlot (PPlot * inPPlot)
Definition at line 2132 of file PPlot.cpp.
References sCurrentPPlot.