Proton: PPlotInteraction.cpp File Reference
PPlotInteraction.cpp File Reference
Functions
float pmax (float inX1, float inX2)
float pmin (float inX1, float inX2)
template<class T >
bool Erase (const vector< int > &inEraseList, vector< T > &ioVec)
Variables
const float kHitDistance = (float)10.0
Function Documentation
template<class T > bool Erase (const vector< int > & inEraseList, vector< T > & ioVec)
Definition at line 595 of file PPlotInteraction.cpp.
Referenced by PDeleteInteraction::HandleDeleteKey().
float pmax (float inX1, float inX2)
Definition at line 19 of file PPlotInteraction.cpp.
Referenced by PZoomInteraction::DoZoomIn(), and PZoomInteraction::DoZoomOut().
float pmin (float inX1, float inX2)
Definition at line 25 of file PPlotInteraction.cpp.
Referenced by PZoomInteraction::DoZoomIn(), PZoomInteraction::DoZoomOut(), and PZoomInteraction::Draw().
Variable Documentation
const float kHitDistance = (float)10.0
Definition at line 17 of file PPlotInteraction.cpp.
Referenced by PSelectionInteraction::Calculate().