Proton: Profile.cpp File Reference
Profile.cpp File Reference
Functions
static void store_profile_in_history (char *name, float percent)
static void get_profile_from_history (char *name, float *ave, float *min, float *max)
void profile_init (void)
void profile_begin (char *name)
void profile_end (char *name)
void profile_tally (void)
void profile_set_paused (bool bPause)
bool profile_get_paused ()
Variables
bool g_profile_pause = false
static sample_point_t samples [MAX_SAMPLE_POINTS]
static sample_history_t history [MAX_SAMPLE_POINTS]
static long startTime
static long endTime
Function Documentation
void get_profile_from_history (char * name, float * ave, float * min, float * max) [static]
Definition at line 341 of file Profile.cpp.
References history.
Referenced by profile_tally().
void profile_begin (char * name)
Definition at line 88 of file Profile.cpp.
References g_profile_pause, and GetSystemTimeTick().
void profile_end (char * name)
Definition at line 134 of file Profile.cpp.
References endTime, g_profile_pause, GetSystemTimeTick(), and startTime.
bool profile_get_paused ()
Definition at line 367 of file Profile.cpp.
References g_profile_pause.
void profile_init (void)
Definition at line 70 of file Profile.cpp.
References endTime, GetSystemTimeTick(), history, and startTime.
void profile_set_paused (bool bPause)
Definition at line 362 of file Profile.cpp.
References g_profile_pause.
void profile_tally (void)
Definition at line 201 of file Profile.cpp.
References endTime, g_profile_pause, get_profile_from_history(), GetSystemTimeTick(), profile_clear_buffer(), profile_write_buffer(), startTime, and store_profile_in_history().
void store_profile_in_history (char * name, float percent) [static]
Definition at line 277 of file Profile.cpp.
References history.
Referenced by profile_tally().
Variable Documentation
long endTime [static]
Definition at line 57 of file Profile.cpp.
Referenced by profile_end(), profile_init(), and profile_tally().
bool g_profile_pause = false
Definition at line 18 of file Profile.cpp.
Referenced by profile_begin(), profile_end(), profile_get_paused(), profile_set_paused(), and profile_tally().
sample_history_t history[MAX_SAMPLE_POINTS] [static]
Definition at line 53 of file Profile.cpp.
Referenced by get_profile_from_history(), profile_init(), and store_profile_in_history().
sample_point_t samples[MAX_SAMPLE_POINTS] [static]
Definition at line 52 of file Profile.cpp.
long startTime [static]
Definition at line 56 of file Profile.cpp.
Referenced by profile_end(), profile_init(), and profile_tally().