Proton: Profile.h File Reference
Profile.h File Reference
Functions
void profile_init (void)
void profile_begin (char *name)
void profile_end (char *name)
void profile_tally (void)
void profile_set_paused (bool bPause)
bool profile_get_paused ()
void profile_clear_buffer (void)
void profile_write_buffer (const char *text)
Variables
bool g_profile_pause
Function Documentation
void profile_begin (char * name)
Definition at line 88 of file Profile.cpp.
References g_profile_pause, and GetSystemTimeTick().
void profile_clear_buffer (void)
Referenced by profile_tally().
void profile_end (char * name)
Definition at line 134 of file Profile.cpp.
References endTime, g_profile_pause, GetSystemTimeTick(), and startTime.
bool profile_get_paused ()
Definition at line 367 of file Profile.cpp.
References g_profile_pause.
void profile_init (void)
Definition at line 70 of file Profile.cpp.
References endTime, GetSystemTimeTick(), history, and startTime.
void profile_set_paused (bool bPause)
Definition at line 362 of file Profile.cpp.
References g_profile_pause.
void profile_tally (void)
Definition at line 201 of file Profile.cpp.
References endTime, g_profile_pause, get_profile_from_history(), GetSystemTimeTick(), profile_clear_buffer(), profile_write_buffer(), startTime, and store_profile_in_history().
void profile_write_buffer (const char * text)
Referenced by profile_tally().
Variable Documentation
bool g_profile_pause
Definition at line 18 of file Profile.cpp.
Referenced by profile_begin(), profile_end(), profile_get_paused(), profile_set_paused(), and profile_tally().