Proton: RenderUtils.cpp File Reference
RenderUtils.cpp File Reference
Functions
eOrientationMode GetForcedOrientation ()
void SetForcedOrientation (eOrientationMode orientation)
void SetProtonPixelScaleFactor (float scale)
float GetProtonPixelScaleFactor ()
void InitBaseScreenSizeFromPrimary ()
float GetDeviceSizeDiagonalInInches ()
void SetDeviceSizeDiagonalInInches (float sizeInInches)
int GetDevicePixelsPerInchDiagonal ()
void RenderGLTriangle ()
void RenderSpinningTriangle ()
void RenderTexturedGLTriangle ()
void RenderTexturedGLTriangleWithDrawElements ()
void RenderTexturedRectangle (float RectSize)
void SetupFakePrimaryScreenSize (int x, int y)
void SetupOriginalScreenSize (int x, int y)
int GetOriginalScreenSizeX ()
int GetOriginalScreenSizeY ()
int GetFakePrimaryScreenSizeX ()
int GetFakePrimaryScreenSizeY ()
bool NeedToUseFakeScreenSize ()
void UndoFakeScreenSize ()
void RedoFakeScreenSize ()
int GetScreenSizeY ()
Returns the current height of the scene viewport.
int GetScreenSizeX ()
Returns the current width of the scene viewport.
float GetScreenSizeYf ()
Returns the same as GetScreenSizeY() but as a float.
float GetScreenSizeXf ()
Returns the same as GetScreenSizeX() but as a float.
CL_Vec2f GetScreenSize ()
Constructs a vector from the values returned by GetScreenSizeXf() and GetScreenSizeYf().
CL_Rectf GetScreenRect ()
bool IsLargeScreen ()
bool IsTabletSize ()
int GetOrientation ()
bool GetLockedLandscape ()
void SetLockedLandscape (bool bNew)
Entity * GetEntityWithNativeUIFocus ()
void SetEntityWithNativeUIFocus (Entity *pEnt, bool bSendLosingFocusMessage)
bool GetIsUsingNativeUI ()
void SetIsUsingNativeUI (bool bNew)
bool CanRotateTo (int orientation)
bool SetupScreenInfoIPhone (int interfaceOrientation)
void SetupScreenInfo (int x, int y, int orientation)
void ConvertCoordinatesIfRequired (int &xPos, int &yPos)
void ConvertCoordinatesIfRequired (float &xPos, float &yPos)
bool NeedsOrthoSet ()
void ResetOrthoFlag ()
void SetOrthoModeFlag ()
bool InLandscapeGUIMode ()
float SinPulseByMS (int ms)
float SinPulseByCustomTimerMS (int ms, unsigned int timerMS)
float SinGamePulseByMS (int ms)
float SinToZeroToOneRange (float sinIn)
uint32 GetBrightColor ()
uint32 ColorCombineMix (uint32 c1, uint32 c2, float progress)
uint32 ColorCombine (uint32 c1, uint32 c2, float alphaMod)
Performs a "linear burn" operation for the colors c1 and c2.
void ScreenToWorld (CL_Vec2f pt, CL_Vec3f *pReturnA, float dist)
CL_Vec3f GetOGLPos (int x, int y, float z, CL_Vec3f *pNormalOut, CL_Mat4f *pModelMatrix, CL_Mat4f *pModelProjectionMatrix)
float iPhoneMapY (float y)
float iPhoneMapX (float x)
CL_Vec2f iPhoneMap (CL_Vec2f vPos)
CL_Vec2f iPhoneMap (float x, float y)
float iPadMapY (float y)
float iPadMapX (float x)
CL_Vec2f iPadMap (CL_Vec2f vPos)
CL_Vec2f iPadMap (float x, float y)
float iPhoneMapX2X (float x)
float iPhoneMapY2X (float y)
CL_Vec2f iPhoneMap2X (CL_Vec2f vPos)
CL_Vec2f iPhoneMap2X (float x, float y)
rtRectf ConvertFakeScreenRectToReal (rtRectf r)
float GetFadeAlphaFromTime (int curTimeMS, int totalTimeMS, int fadeInMS, int fadeOutMS)
Variables
int g_screenSizeY = GetPrimaryGLY()
int g_screenSizeX = GetPrimaryGLX()
int g_fakePrimaryScreenSizeX = 0
int g_fakePrimaryScreenSizeY = 0
int g_originalScreenSizeX = 0
int g_originalScreenSizeY = 0
float g_deviceDiagonalSizeInInches = 0
float g_protonPixelScaleFactor = 1.0f
eOrientationMode g_forcedOrientation = ORIENTATION_DONT_CARE
int g_orientation = ORIENTATION_PORTRAIT
bool g_lockedLandscape = false
int g_undoFakeScreenSizeX = 0
int g_undoFakeScreenSizeY = 0
bool g_usingNativeUI = false
Entity * g_pGUIWithGUIFocus = NULL
bool g_needsOrthoModeSet = true
Function Documentation
bool CanRotateTo (int orientation)
Definition at line 548 of file RenderUtils.cpp.
References GetLockedLandscape().
Referenced by SetupScreenInfoIPhone().
uint32 ColorCombine (uint32 c1, uint32 c2, float alphaMod = 1.0f)
Performs a "linear burn" operation for the colors c1 and c2.
This is achieved by summing the color component values together and subtracting 255 from the result. The result of this is then clamped to the accepted range of [0, 255]. Note that this operation is also performed for the alpha channel.
Finally the alpha value is multiplied with alphaMod.
http://en.wikipedia.org/wiki/Blend_modes#Dodge_and_burn
Returns:
The final resulting color of the operation.
Definition at line 762 of file RenderUtils.cpp.
uint32 ColorCombineMix (uint32 c1, uint32 c2, float progress)
Definition at line 746 of file RenderUtils.cpp.
Referenced by Variant::Interpolate().
void ConvertCoordinatesIfRequired (int & xPos, int & yPos)
Definition at line 611 of file RenderUtils.cpp.
References ConvertCoordinatesIfRequired().
Referenced by AppOSMessageGet(), ConvertCoordinatesIfRequired(), and SDLEventLoop().
void ConvertCoordinatesIfRequired (float & xPos, float & yPos)
Definition at line 620 of file RenderUtils.cpp.
References GetBaseApp(), GetFakePrimaryScreenSizeX(), BaseApp::GetManualRotationMode(), GetOrientation(), GetOriginalScreenSizeX(), GetOriginalScreenSizeY(), GetProtonPixelScaleFactor(), GetScreenSizeXf(), GetScreenSizeYf(), InLandscapeGUIMode(), ORIENTATION_LANDSCAPE_LEFT, ORIENTATION_LANDSCAPE_RIGHT, ORIENTATION_PORTRAIT, and ORIENTATION_PORTRAIT_UPSIDE_DOWN.
rtRectf ConvertFakeScreenRectToReal (rtRectf r)
Definition at line 1014 of file RenderUtils.cpp.
References rtRectf::bottom, GetBaseApp(), GetFakePrimaryScreenSizeX(), GetFakePrimaryScreenSizeY(), rtRectf::GetHeight(), BaseApp::GetManualRotationMode(), GetPrimaryGLX(), GetPrimaryGLY(), rtRectf::GetWidth(), InLandscapeGUIMode(), rtRectf::left, rtRectf::right, and rtRectf::top.
Referenced by RenderScissorComponent::FilterOnRender().
uint32 GetBrightColor ()
Definition at line 725 of file RenderUtils.cpp.
References Random().
int GetDevicePixelsPerInchDiagonal ()
Definition at line 67 of file RenderUtils.cpp.
References g_deviceDiagonalSizeInInches, and GetScreenSize().
Referenced by EntityAdjustScaleSoPhysicalSizeMatches(), and IsTabletSize().
float GetDeviceSizeDiagonalInInches ()
Definition at line 57 of file RenderUtils.cpp.
References g_deviceDiagonalSizeInInches.
Entity* GetEntityWithNativeUIFocus ()
Definition at line 514 of file RenderUtils.cpp.
References g_pGUIWithGUIFocus.
Referenced by InputTextRenderComponent::~InputTextRenderComponent().
float GetFadeAlphaFromTime (int curTimeMS, int totalTimeMS, int fadeInMS, int fadeOutMS)
Definition at line 1046 of file RenderUtils.cpp.
int GetFakePrimaryScreenSizeX ()
Definition at line 362 of file RenderUtils.cpp.
References g_fakePrimaryScreenSizeX.
Referenced by ConvertCoordinatesIfRequired(), ConvertFakeScreenRectToReal(), GetOGLPos(), main(), AdManager::OnRender(), SetupScreenInfo(), and UndoFakeScreenSize().
int GetFakePrimaryScreenSizeY ()
Definition at line 367 of file RenderUtils.cpp.
References g_fakePrimaryScreenSizeY.
Referenced by ConvertFakeScreenRectToReal(), and SetupScreenInfo().
eOrientationMode GetForcedOrientation ()
Definition at line 30 of file RenderUtils.cpp.
References g_forcedOrientation.
Referenced by ChangeEmulationOrientationIfPossible(), SetLockedLandscape(), SetupScreenInfo(), and SetupScreenInfoIPhone().
bool GetIsUsingNativeUI ()
Definition at line 535 of file RenderUtils.cpp.
References g_usingNativeUI.
Referenced by AppOnKey(), and InputTextRenderComponent::~InputTextRenderComponent().
bool GetLockedLandscape ()
Definition at line 473 of file RenderUtils.cpp.
References g_lockedLandscape.
Referenced by CanRotateTo().
CL_Vec3f GetOGLPos (int x, int y, float z, CL_Vec3f * pNormalOut, CL_Mat4f * pModelMatrix, CL_Mat4f * pModelProjectionMatrix)
Definition at line 818 of file RenderUtils.cpp.
References GetBaseApp(), GetFakePrimaryScreenSizeX(), BaseApp::GetManualRotationMode(), GetOrientation(), GetOriginalScreenSizeX(), GetOriginalScreenSizeY(), GetPrimaryGLX(), GetPrimaryGLY(), BaseApp::GetProjectionMatrix(), GetScreenSizeX(), GetScreenSizeXf(), GetScreenSizeY(), GetScreenSizeYf(), gluUnProject(), ORIENTATION_LANDSCAPE_LEFT, ORIENTATION_LANDSCAPE_RIGHT, ORIENTATION_PORTRAIT, and ORIENTATION_PORTRAIT_UPSIDE_DOWN.
int GetOrientation ()
Definition at line 471 of file RenderUtils.cpp.
References g_orientation.
Referenced by ConvertCoordinatesIfRequired(), RenderScissorComponent::FilterOnRender(), GetOGLPos(), InLandscapeGUIMode(), OrientationToDegrees(), RedoFakeScreenSize(), RotateGLIfNeeded(), SetLockedLandscape(), SetupFakePrimaryScreenSize(), and UndoFakeScreenSize().
int GetOriginalScreenSizeX ()
Definition at line 352 of file RenderUtils.cpp.
References g_originalScreenSizeX.
Referenced by ConvertCoordinatesIfRequired(), GetOGLPos(), AdManager::OnRender(), RedoFakeScreenSize(), SetupScreenInfo(), and UndoFakeScreenSize().
int GetOriginalScreenSizeY ()
Definition at line 357 of file RenderUtils.cpp.
References g_originalScreenSizeY.
Referenced by ConvertCoordinatesIfRequired(), GetOGLPos(), AdManager::OnRender(), RedoFakeScreenSize(), SetupScreenInfo(), and UndoFakeScreenSize().
float GetProtonPixelScaleFactor ()
Definition at line 45 of file RenderUtils.cpp.
References g_protonPixelScaleFactor.
Referenced by ConvertCoordinatesIfRequired().
CL_Rectf GetScreenRect ()
Definition at line 444 of file RenderUtils.cpp.
References g_screenSizeX, and g_screenSizeY.
Referenced by EntityIsOnScreen().
CL_Vec2f GetScreenSize ()
Constructs a vector from the values returned by GetScreenSizeXf() and GetScreenSizeYf().
Definition at line 439 of file RenderUtils.cpp.
References g_screenSizeX, and g_screenSizeY.
Referenced by GetDevicePixelsPerInchDiagonal(), OnShowTextMessage(), and RotateGUIPoint().
int GetScreenSizeX ()
Returns the current width of the scene viewport.
Usually this is the same as the width of the application window. But it can be also different if the fake screen size mode is used.
Definition at line 424 of file RenderUtils.cpp.
References g_screenSizeX.
float GetScreenSizeXf ()
Returns the same as GetScreenSizeX() but as a float.
Definition at line 434 of file RenderUtils.cpp.
References g_screenSizeX.
int GetScreenSizeY ()
Returns the current height of the scene viewport.
Usually this is the same as the height of the application window. But it can be also different if the fake screen size mode is used.
Definition at line 419 of file RenderUtils.cpp.
References g_screenSizeY.
float GetScreenSizeYf ()
Returns the same as GetScreenSizeY() but as a float.
Definition at line 429 of file RenderUtils.cpp.
References g_screenSizeY.
void InitBaseScreenSizeFromPrimary ()
Definition at line 50 of file RenderUtils.cpp.
References g_screenSizeX, g_screenSizeY, GetPrimaryGLX(), and GetPrimaryGLY().
bool InLandscapeGUIMode ()
Definition at line 694 of file RenderUtils.cpp.
References GetOrientation().
Referenced by SoftSurface::BlitFromScreen(), ConvertCoordinatesIfRequired(), ConvertFakeScreenRectToReal(), and RenderScissorComponent::FilterOnRender().
CL_Vec2f iPadMap (CL_Vec2f vPos)
Definition at line 952 of file RenderUtils.cpp.
References GetScreenSizeXf(), and GetScreenSizeYf().
CL_Vec2f iPadMap (float x, float y)
Definition at line 957 of file RenderUtils.cpp.
References GetScreenSizeXf(), and GetScreenSizeYf().
float iPadMapX (float x)
Definition at line 947 of file RenderUtils.cpp.
References GetScreenSizeXf().
float iPadMapY (float y)
Definition at line 942 of file RenderUtils.cpp.
References GetScreenSizeYf().
CL_Vec2f iPhoneMap (CL_Vec2f vPos)
Definition at line 931 of file RenderUtils.cpp.
References GetScreenSizeXf(), and GetScreenSizeYf().
Referenced by CreateScrollingTextBoxEntity(), and EntityRetinaRemapIfNeeded().
CL_Vec2f iPhoneMap (float x, float y)
Definition at line 937 of file RenderUtils.cpp.
References GetScreenSizeXf(), and GetScreenSizeYf().
CL_Vec2f iPhoneMap2X (CL_Vec2f vPos)
Definition at line 976 of file RenderUtils.cpp.
References IsLargeScreen().
CL_Vec2f iPhoneMap2X (float x, float y)
Definition at line 983 of file RenderUtils.cpp.
References IsLargeScreen().
float iPhoneMapX (float x)
Definition at line 926 of file RenderUtils.cpp.
References GetScreenSizeXf().
Referenced by CreateCheckbox().
float iPhoneMapX2X (float x)
Definition at line 963 of file RenderUtils.cpp.
References IsLargeScreen().
float iPhoneMapY (float y)
Definition at line 921 of file RenderUtils.cpp.
References GetScreenSizeYf().
Referenced by CreateCheckbox().
float iPhoneMapY2X (float y)
Definition at line 970 of file RenderUtils.cpp.
References IsLargeScreen().
Referenced by CreateSlider().
bool IsLargeScreen ()
Definition at line 450 of file RenderUtils.cpp.
References g_screenSizeX, and g_screenSizeY.
bool IsTabletSize ()
Definition at line 455 of file RenderUtils.cpp.
References g_screenSizeX, g_screenSizeY, and GetDevicePixelsPerInchDiagonal().
bool NeedsOrthoSet ()
Definition at line 678 of file RenderUtils.cpp.
References g_needsOrthoModeSet.
Referenced by PrepareForGL(), RemoveOrthoRenderSize(), and SetupOrtho().
bool NeedToUseFakeScreenSize ()
Definition at line 375 of file RenderUtils.cpp.
References g_fakePrimaryScreenSizeX, g_fakePrimaryScreenSizeY, GetPrimaryGLX(), and GetPrimaryGLY().
void RedoFakeScreenSize ()
Definition at line 402 of file RenderUtils.cpp.
References g_undoFakeScreenSizeX, g_undoFakeScreenSizeY, GetOrientation(), GetOriginalScreenSizeX(), GetOriginalScreenSizeY(), PrepareForGL(), SetupFakePrimaryScreenSize(), and SetupScreenInfo().
void RenderGLTriangle ()
Definition at line 104 of file RenderUtils.cpp.
References glColor4x(), glDisable(), glDisableClientState(), glDrawArrays(), glEnable(), glEnableClientState(), and glVertexPointer().
Referenced by RenderSpinningTriangle().
void RenderSpinningTriangle ()
Definition at line 142 of file RenderUtils.cpp.
References GetBaseApp(), glDisable(), glEnable(), glLoadIdentity(), glPopMatrix(), glPushMatrix(), glRotatef(), glTranslatef(), and RenderGLTriangle().
void RenderTexturedGLTriangle ()
Definition at line 157 of file RenderUtils.cpp.
References GetBaseApp(), glDisable(), glDrawArrays(), glEnable(), glEnableClientState(), glPopMatrix(), glPushMatrix(), glRotatef(), glTexCoordPointer(), and glVertexPointer().
void RenderTexturedGLTriangleWithDrawElements ()
Definition at line 216 of file RenderUtils.cpp.
References GetBaseApp(), glDisable(), glDrawElements(), glEnable(), glEnableClientState(), glLoadIdentity(), glPopMatrix(), glPushMatrix(), glRotatef(), glTexCoordPointer(), glTranslatef(), and glVertexPointer().
void RenderTexturedRectangle (float RectSize)
Definition at line 294 of file RenderUtils.cpp.
References glDisable(), glDrawArrays(), glEnable(), glEnableClientState(), glTexCoordPointer(), and glVertexPointer().
void ResetOrthoFlag ()
Definition at line 683 of file RenderUtils.cpp.
References g_needsOrthoModeSet.
Referenced by PrepareForGL().
void ScreenToWorld (CL_Vec2f pt, CL_Vec3f * pReturnA, float dist)
Definition at line 790 of file RenderUtils.cpp.
References GetScreenSizeXf(), GetScreenSizeYf(), and glGetFloatv().
void SetDeviceSizeDiagonalInInches (float sizeInInches)
Definition at line 62 of file RenderUtils.cpp.
References g_deviceDiagonalSizeInInches.
void SetEntityWithNativeUIFocus (Entity * pEnt, bool bSendLosingFocusMessage)
Definition at line 519 of file RenderUtils.cpp.
References VariantDB::CallFunctionIfExists(), and Entity::GetShared().
void SetForcedOrientation (eOrientationMode orientation)
Definition at line 31 of file RenderUtils.cpp.
References g_forcedOrientation.
Referenced by main().
void SetIsUsingNativeUI (bool bNew)
Definition at line 537 of file RenderUtils.cpp.
References g_usingNativeUI, GetBaseApp(), and BaseApp::m_sig_native_input_state_changed.
Referenced by AppOnKey(), and Native_Update().
void SetLockedLandscape (bool bNew)
Definition at line 475 of file RenderUtils.cpp.
References g_lockedLandscape, GetBaseApp(), GetForcedOrientation(), GetOrientation(), GetPrimaryGLX(), GetPrimaryGLY(), ORIENTATION_DONT_CARE, ORIENTATION_LANDSCAPE_LEFT, ORIENTATION_PORTRAIT, ORIENTATION_PORTRAIT_UPSIDE_DOWN, and SetupScreenInfo().
void SetOrthoModeFlag ()
Definition at line 689 of file RenderUtils.cpp.
References g_needsOrthoModeSet.
Referenced by SetupOrtho().
void SetProtonPixelScaleFactor (float scale)
Definition at line 33 of file RenderUtils.cpp.
References g_protonPixelScaleFactor, and IsIPAD().
void SetupFakePrimaryScreenSize (int x, int y)
Definition at line 335 of file RenderUtils.cpp.
References g_fakePrimaryScreenSizeX, g_fakePrimaryScreenSizeY, GetOrientation(), GetScreenSizeX(), GetScreenSizeY(), and SetupScreenInfo().
Referenced by RedoFakeScreenSize().
void SetupOriginalScreenSize (int x, int y)
Definition at line 345 of file RenderUtils.cpp.
References g_originalScreenSizeX, and g_originalScreenSizeY.
Referenced by SetupScreenInfo(), and UndoFakeScreenSize().
void SetupScreenInfo (int x, int y, int orientation)
Definition at line 576 of file RenderUtils.cpp.
References g_orientation, g_screenSizeX, g_screenSizeY, GetBaseApp(), GetFakePrimaryScreenSizeX(), GetFakePrimaryScreenSizeY(), GetForcedOrientation(), GetOriginalScreenSizeX(), GetOriginalScreenSizeY(), GetPrimaryGLX(), GetPrimaryGLY(), IsBaseAppInitted(), LogMsg(), NotifyOSOfOrientationPreference(), BaseApp::OnScreenSizeChange(), ORIENTATION_DONT_CARE, and SetupOriginalScreenSize().
Referenced by AppResize(), ChangeEmulationOrientationIfPossible(), main(), RedoFakeScreenSize(), SetLockedLandscape(), SetupFakePrimaryScreenSize(), SetupScreenInfoIPhone(), and UndoFakeScreenSize().
bool SetupScreenInfoIPhone (int interfaceOrientation)
Definition at line 559 of file RenderUtils.cpp.
References CanRotateTo(), g_screenSizeX, g_screenSizeY, GetForcedOrientation(), ORIENTATION_DONT_CARE, and SetupScreenInfo().
float SinGamePulseByMS (int ms)
Definition at line 712 of file RenderUtils.cpp.
References GetBaseApp(), and BaseApp::GetGameTick().
float SinPulseByCustomTimerMS (int ms, unsigned int timerMS)
Definition at line 706 of file RenderUtils.cpp.
float SinPulseByMS (int ms)
Definition at line 700 of file RenderUtils.cpp.
References GetBaseApp(), and BaseApp::GetTick().
float SinToZeroToOneRange (float sinIn)
Definition at line 719 of file RenderUtils.cpp.
void UndoFakeScreenSize ()
Definition at line 382 of file RenderUtils.cpp.
References g_fakePrimaryScreenSizeX, g_fakePrimaryScreenSizeY, g_screenSizeX, g_screenSizeY, g_undoFakeScreenSizeX, g_undoFakeScreenSizeY, GetFakePrimaryScreenSizeX(), GetOrientation(), GetOriginalScreenSizeX(), GetOriginalScreenSizeY(), PrepareForGL(), SetupOriginalScreenSize(), and SetupScreenInfo().
Variable Documentation
float g_deviceDiagonalSizeInInches = 0
Definition at line 21 of file RenderUtils.cpp.
Referenced by GetDevicePixelsPerInchDiagonal(), GetDeviceSizeDiagonalInInches(), and SetDeviceSizeDiagonalInInches().
int g_fakePrimaryScreenSizeX = 0
Definition at line 17 of file RenderUtils.cpp.
Referenced by GetFakePrimaryScreenSizeX(), NeedToUseFakeScreenSize(), SetupFakePrimaryScreenSize(), and UndoFakeScreenSize().
int g_fakePrimaryScreenSizeY = 0
Definition at line 18 of file RenderUtils.cpp.
Referenced by GetFakePrimaryScreenSizeY(), NeedToUseFakeScreenSize(), SetupFakePrimaryScreenSize(), and UndoFakeScreenSize().
eOrientationMode g_forcedOrientation = ORIENTATION_DONT_CARE
Definition at line 26 of file RenderUtils.cpp.
Referenced by GetForcedOrientation(), and SetForcedOrientation().
bool g_lockedLandscape = false
Definition at line 28 of file RenderUtils.cpp.
Referenced by GetLockedLandscape(), and SetLockedLandscape().
bool g_needsOrthoModeSet = true
Definition at line 676 of file RenderUtils.cpp.
Referenced by NeedsOrthoSet(), ResetOrthoFlag(), and SetOrthoModeFlag().
int g_orientation = ORIENTATION_PORTRAIT
Definition at line 27 of file RenderUtils.cpp.
Referenced by GetOrientation(), and SetupScreenInfo().
int g_originalScreenSizeX = 0
Definition at line 19 of file RenderUtils.cpp.
Referenced by GetOriginalScreenSizeX(), and SetupOriginalScreenSize().
int g_originalScreenSizeY = 0
Definition at line 20 of file RenderUtils.cpp.
Referenced by GetOriginalScreenSizeY(), and SetupOriginalScreenSize().
Entity* g_pGUIWithGUIFocus = NULL
Definition at line 512 of file RenderUtils.cpp.
Referenced by GetEntityWithNativeUIFocus().
float g_protonPixelScaleFactor = 1.0f
Definition at line 24 of file RenderUtils.cpp.
Referenced by GetProtonPixelScaleFactor(), and SetProtonPixelScaleFactor().
int g_screenSizeX = GetPrimaryGLX()
Definition at line 16 of file RenderUtils.cpp.
Referenced by GetScreenRect(), GetScreenSize(), GetScreenSizeX(), GetScreenSizeXf(), InitBaseScreenSizeFromPrimary(), IsLargeScreen(), IsTabletSize(), SetupScreenInfo(), SetupScreenInfoIPhone(), and UndoFakeScreenSize().
int g_screenSizeY = GetPrimaryGLY()
Definition at line 15 of file RenderUtils.cpp.
Referenced by GetScreenRect(), GetScreenSize(), GetScreenSizeY(), GetScreenSizeYf(), InitBaseScreenSizeFromPrimary(), IsLargeScreen(), IsTabletSize(), SetupScreenInfo(), SetupScreenInfoIPhone(), and UndoFakeScreenSize().
int g_undoFakeScreenSizeX = 0
Definition at line 372 of file RenderUtils.cpp.
Referenced by RedoFakeScreenSize(), and UndoFakeScreenSize().
int g_undoFakeScreenSizeY = 0
Definition at line 373 of file RenderUtils.cpp.
Referenced by RedoFakeScreenSize(), and UndoFakeScreenSize().
bool g_usingNativeUI = false
Definition at line 511 of file RenderUtils.cpp.
Referenced by GetIsUsingNativeUI(), and SetIsUsingNativeUI().