Proton: ResourceUtils.cpp File Reference
ResourceUtils.cpp File Reference
Functions
bool IsPowerOf2 (int n)
bool SaveToFile (const string &str, FILE *fp)
bool LoadFromFile (string &str, FILE *fp)
bool SaveToFile (int num, FILE *fp)
bool SaveToFile (uint32 num, FILE *fp)
bool SaveToFile (float num, FILE *fp)
bool LoadFromFile (int32 &num, FILE *fp)
bool LoadFromFile (float &num, FILE *fp)
bool LoadFromFile (bool &num, FILE *fp)
bool LoadFromFile (uint32 &num, FILE *fp)
bool LoadFromFile (CL_Vec2f &num, FILE *fp)
bool LoadFromFile (CL_Vec3f &num, FILE *fp)
bool LoadFromFile (CL_Rectf &num, FILE *fp)
bool FileExists (const string &fName)
byte * DecompressRTPackToMemory (byte *pMem, unsigned int *pDecompressedSize)
byte * LoadFileIntoMemoryBasic (string fileName, unsigned int *length, bool bUseSavePath, bool bAddBasePath)
bool IsAPackedFile (byte *pFile)
bool IsARTFile (byte *pFile)
bool CompressFile (string fName)
rtpack_header BuildRTPackHeader (int size, int compressedSize)
byte * zlibDeflateToMemory (byte *pInput, int sizeBytes, int *pSizeCompressedOut)
byte * zLibInflateToMemory (byte *pInput, unsigned int compressedSize, unsigned int decompressedSize)
void AppendStringToFile (const string filename, const string text)
byte * LoadFileIntoMemory (string fileName, unsigned int *p_ui_size, bool bUseSavePath)
string SeparateStringSTL (string input, int index, char delimiter)
bool SeparateString (const char str[], int num, char delimiter, char *return1)
void StringReplace (const std::string &what, const std::string &with, std::string &in)
int GetFileSize (const string &fName)
string AddIPADToFileName (string file)
string ReplaceWithDeviceNameInFileName (const string &fName)
string ReplaceWithLargeInFileName (const string &fName)
string ReplaceWithLargeInFileNameAndOSSpecific (const string &fName)
string ReplaceMP3 (const string &fName)
std::string StripColorCodes (const std::string text)
bool StringFromStartMatches (const std::string &line, const std::string textToMatch)
bool StringFromEndMatches (const std::string &line, const std::string textToMatch)
void MemorySerialize (std::string &num, uint8 *pMem, int &offsetInOut, bool bWriteToMem)
void MemorySerializeRaw (uint8 *pVar, uint8 *pMem, int sizeBytes, int &offsetInOut, bool bWriteToMem)
Function Documentation
string AddIPADToFileName (string file)
Definition at line 465 of file ResourceUtils.cpp.
References IsLargeScreen().
void AppendStringToFile (const string filename, const string text)
Definition at line 337 of file ResourceUtils.cpp.
References GetPlatformID(), and PLATFORM_ID_LINUX.
Referenced by LogMsg().
rtpack_header BuildRTPackHeader (int size, int compressedSize)
Definition at line 247 of file ResourceUtils.cpp.
References C_COMPRESSION_ZLIB, rtpack_header::compressedSize, rtpack_header::compressionType, rtpack_header::decompressedSize, RTFileHeader::fileTypeID, rtpack_header::rtFileHeader, and RTFileHeader::version.
Referenced by CompressFile().
bool CompressFile (string fName)
Definition at line 202 of file ResourceUtils.cpp.
References BuildRTPackHeader(), GetFileExtension(), IsAPackedFile(), LoadFileIntoMemoryBasic(), LogMsg(), ModifyFileExtension(), and zlibDeflateToMemory().
byte* DecompressRTPackToMemory (byte * pMem, unsigned int * pDecompressedSize)
Definition at line 127 of file ResourceUtils.cpp.
References rtpack_header::compressedSize, rtpack_header::decompressedSize, IsAPackedFile(), and zLibInflateToMemory().
Referenced by FileManager::Get().
bool FileExists (const string & fName)
Definition at line 102 of file ResourceUtils.cpp.
References FileManager::FileExists(), and GetFileManager().
Referenced by DPadComponent::OnAdd(), AudioManagerAndroid::Play(), and AudioManagerAndroid::Preload().
int GetFileSize (const string & fName)
Definition at line 438 of file ResourceUtils.cpp.
References LogMsg().
bool IsAPackedFile (byte * pFile)
Definition at line 191 of file ResourceUtils.cpp.
Referenced by CompressFile(), DecompressRTPackToMemory(), and FileManager::Get().
bool IsARTFile (byte * pFile)
Definition at line 196 of file ResourceUtils.cpp.
bool IsPowerOf2 (int n)
Definition at line 9 of file ResourceUtils.cpp.
Referenced by JPGSurfaceLoader::LoadFromMem().
byte* LoadFileIntoMemory (string fileName, unsigned int * p_ui_size, bool bUseSavePath)
Definition at line 368 of file ResourceUtils.cpp.
References LoadFileIntoMemoryBasic().
byte* LoadFileIntoMemoryBasic (string fileName, unsigned int * length, bool bUseSavePath, bool bAddBasePath)
Definition at line 148 of file ResourceUtils.cpp.
References GetBaseAppPath(), and GetSavePath().
Referenced by CompressFile(), GetHashOfFile(), and LoadFileIntoMemory().
bool LoadFromFile (string & str, FILE * fp)
Definition at line 23 of file ResourceUtils.cpp.
Referenced by VariantDB::Load().
bool LoadFromFile (int32 & num, FILE * fp)
Definition at line 59 of file ResourceUtils.cpp.
bool LoadFromFile (float & num, FILE * fp)
Definition at line 64 of file ResourceUtils.cpp.
bool LoadFromFile (bool & num, FILE * fp)
Definition at line 70 of file ResourceUtils.cpp.
bool LoadFromFile (uint32 & num, FILE * fp)
Definition at line 75 of file ResourceUtils.cpp.
bool LoadFromFile (CL_Vec2f & num, FILE * fp)
Definition at line 82 of file ResourceUtils.cpp.
bool LoadFromFile (CL_Vec3f & num, FILE * fp)
Definition at line 88 of file ResourceUtils.cpp.
bool LoadFromFile (CL_Rectf & num, FILE * fp)
Definition at line 94 of file ResourceUtils.cpp.
void MemorySerialize (std::string & num, uint8 * pMem, int & offsetInOut, bool bWriteToMem)
Definition at line 589 of file ResourceUtils.cpp.
void MemorySerializeRaw (uint8 * pVar, uint8 * pMem, int sizeBytes, int & offsetInOut, bool bWriteToMem)
Definition at line 620 of file ResourceUtils.cpp.
string ReplaceMP3 (const string & fName)
Definition at line 534 of file ResourceUtils.cpp.
References GetEmulatedPlatformID(), PLATFORM_ID_ANDROID, and StringReplace().
Referenced by BaseApp::OnMessage().
string ReplaceWithDeviceNameInFileName (const string & fName)
Definition at line 480 of file ResourceUtils.cpp.
References IsTabletSize(), and StringReplace().
string ReplaceWithLargeInFileName (const string & fName)
Definition at line 500 of file ResourceUtils.cpp.
References IsLargeScreen(), and StringReplace().
string ReplaceWithLargeInFileNameAndOSSpecific (const string & fName)
Definition at line 512 of file ResourceUtils.cpp.
References GetEmulatedPlatformID(), IsLargeScreen(), PLATFORM_ID_OSX, PLATFORM_ID_WINDOWS, and StringReplace().
bool SaveToFile (const string & str, FILE * fp)
Definition at line 11 of file ResourceUtils.cpp.
Referenced by Variant::Save().
bool SaveToFile (int num, FILE * fp)
Definition at line 41 of file ResourceUtils.cpp.
bool SaveToFile (uint32 num, FILE * fp)
Definition at line 47 of file ResourceUtils.cpp.
bool SaveToFile (float num, FILE * fp)
Definition at line 53 of file ResourceUtils.cpp.
bool SeparateString (const char str[], int num, char delimiter, char * return1)
Definition at line 398 of file ResourceUtils.cpp.
Referenced by SeparateStringSTL().
string SeparateStringSTL (string input, int index, char delimiter)
Definition at line 382 of file ResourceUtils.cpp.
References LogMsg(), and SeparateString().
Referenced by TextScanner::GetParmFloatFromLine(), TextScanner::GetParmIntFromLine(), and TextScanner::GetParmStringFromLine().
bool StringFromEndMatches (const std::string & line, const std::string textToMatch)
Definition at line 579 of file ResourceUtils.cpp.
bool StringFromStartMatches (const std::string & line, const std::string textToMatch)
Definition at line 569 of file ResourceUtils.cpp.
Referenced by VariantDB::AddVarPointersToVector(), and Entity::RemoveEntitiesByNameThatStartWith().
void StringReplace (const std::string & what, const std::string & with, std::string & in)
Definition at line 426 of file ResourceUtils.cpp.
Referenced by BreakDownURLIntoPieces(), CreateDirectoryRecursively(), TextScanner::DumpToLog(), GetAndroidMainClassName(), AudioManagerFlash::Play(), AudioManagerAndroid::Play(), AudioManagerFlash::Preload(), AudioManagerAndroid::Preload(), TextScanner::Replace(), ReplaceMP3(), ReplaceWithDeviceNameInFileName(), ReplaceWithLargeInFileName(), ReplaceWithLargeInFileNameAndOSSpecific(), and TextScanner::SetupFromMemoryAddress().
std::string StripColorCodes (const std::string text)
Definition at line 548 of file ResourceUtils.cpp.
byte* zlibDeflateToMemory (byte * pInput, int sizeBytes, int * pSizeCompressedOut)
Definition at line 264 of file ResourceUtils.cpp.
Referenced by CompressFile().
byte* zLibInflateToMemory (byte * pInput, unsigned int compressedSize, unsigned int decompressedSize)
Definition at line 299 of file ResourceUtils.cpp.
References void().
Referenced by DecompressRTPackToMemory().