Proton: ResourceUtils.h File Reference
ResourceUtils.h File Reference
Functions
bool LoadFromFile (CL_Vec2f &num, FILE *fp)
bool LoadFromFile (CL_Vec3f &num, FILE *fp)
bool LoadFromFile (CL_Rectf &num, FILE *fp)
byte * LoadFileIntoMemory (std::string fileName, unsigned int *p_ui_size, bool bUseSavePath=false)
byte * LoadFileIntoMemoryBasic (std::string fileName, unsigned int *length, bool bUseSavePath=false, bool bAddBasePath=true)
bool FileExists (const std::string &fName)
std::string SeparateStringSTL (std::string input, int index, char delimiter)
bool SeparateString (const char str[], int num, char delimiter, char *return1)
void StringReplace (const std::string &what, const std::string &with, std::string &in)
bool CompressFile (std::string fName)
bool IsAPackedFile (byte *pFile)
bool IsARTFile (byte *pFile)
rtpack_header BuildRTPackHeader (int size, int compressedSize)
byte * zlibDeflateToMemory (byte *pInput, int sizeBytes, int *pSizeCompressedOut)
byte * zLibInflateToMemory (byte *pInput, unsigned int compressedSize, unsigned int decompressedSize)
bool LoadFromFile (std::string &str, FILE *fp)
bool LoadFromFile (float &num, FILE *fp)
bool LoadFromFile (int32 &num, FILE *fp)
bool LoadFromFile (uint32 &num, FILE *fp)
bool LoadFromFile (bool &num, FILE *fp)
bool SaveToFile (float num, FILE *fp)
bool SaveToFile (int num, FILE *fp)
bool SaveToFile (uint32 num, FILE *fp)
bool SaveToFile (const std::string &str, FILE *fp)
bool IsPowerOf2 (int n)
byte * DecompressRTPackToMemory (byte *pMem, unsigned int *pDecompressedSize=NULL)
int GetFileSize (const std::string &fName)
std::string AddIPADToFileName (std::string file)
std::string ReplaceWithDeviceNameInFileName (const std::string &fName)
std::string ReplaceWithLargeInFileName (const std::string &fName)
std::string ReplaceWithLargeInFileNameAndOSSpecific (const std::string &fName)
std::string ReplaceMP3 (const std::string &fName)
void AppendStringToFile (const std::string filename, const std::string text)
std::string StripColorCodes (const std::string text)
bool StringFromStartMatches (const std::string &line, const std::string textToMatch)
bool StringFromEndMatches (const std::string &line, const std::string textToMatch)
template<class myType >
void MemorySerialize (myType &num, uint8 *pMem, int &offsetInOut, bool bWriteToMem)
void MemorySerialize (std::string &num, uint8 *pMem, int &offsetInOut, bool bWriteToMem)
void MemorySerializeRaw (uint8 *pVar, uint8 *pMem, int sizeBytes, int &offsetInOut, bool bWriteToMem)
Function Documentation
std::string AddIPADToFileName (std::string file)
void AppendStringToFile (const std::string filename, const std::string text)
rtpack_header BuildRTPackHeader (int size, int compressedSize)
Definition at line 247 of file ResourceUtils.cpp.
References C_COMPRESSION_ZLIB, rtpack_header::compressedSize, rtpack_header::compressionType, rtpack_header::decompressedSize, RTFileHeader::fileTypeID, rtpack_header::rtFileHeader, and RTFileHeader::version.
Referenced by CompressFile().
bool CompressFile (std::string fName)
byte* DecompressRTPackToMemory (byte * pMem, unsigned int * pDecompressedSize = NULL)
Definition at line 127 of file ResourceUtils.cpp.
References rtpack_header::compressedSize, rtpack_header::decompressedSize, IsAPackedFile(), and zLibInflateToMemory().
Referenced by FileManager::Get().
bool FileExists (const std::string & fName)
int GetFileSize (const std::string & fName)
bool IsAPackedFile (byte * pFile)
Definition at line 191 of file ResourceUtils.cpp.
Referenced by CompressFile(), DecompressRTPackToMemory(), and FileManager::Get().
bool IsARTFile (byte * pFile)
Definition at line 196 of file ResourceUtils.cpp.
bool IsPowerOf2 (int n)
Definition at line 9 of file ResourceUtils.cpp.
Referenced by JPGSurfaceLoader::LoadFromMem().
byte* LoadFileIntoMemory (std::string fileName, unsigned int * p_ui_size, bool bUseSavePath = false)
byte* LoadFileIntoMemoryBasic (std::string fileName, unsigned int * length, bool bUseSavePath = false, bool bAddBasePath = true)
bool LoadFromFile (CL_Vec2f & num, FILE * fp)
Definition at line 82 of file ResourceUtils.cpp.
bool LoadFromFile (CL_Vec3f & num, FILE * fp)
Definition at line 88 of file ResourceUtils.cpp.
bool LoadFromFile (CL_Rectf & num, FILE * fp)
Definition at line 94 of file ResourceUtils.cpp.
bool LoadFromFile (std::string & str, FILE * fp)
bool LoadFromFile (float & num, FILE * fp)
Definition at line 64 of file ResourceUtils.cpp.
bool LoadFromFile (int32 & num, FILE * fp)
Definition at line 59 of file ResourceUtils.cpp.
bool LoadFromFile (uint32 & num, FILE * fp)
Definition at line 75 of file ResourceUtils.cpp.
bool LoadFromFile (bool & num, FILE * fp)
Definition at line 70 of file ResourceUtils.cpp.
template<class myType > void MemorySerialize (myType & num, uint8 * pMem, int & offsetInOut, bool bWriteToMem)
Definition at line 58 of file ResourceUtils.h.
void MemorySerialize (std::string & num, uint8 * pMem, int & offsetInOut, bool bWriteToMem)
Definition at line 589 of file ResourceUtils.cpp.
void MemorySerializeRaw (uint8 * pVar, uint8 * pMem, int sizeBytes, int & offsetInOut, bool bWriteToMem)
Definition at line 620 of file ResourceUtils.cpp.
std::string ReplaceMP3 (const std::string & fName)
std::string ReplaceWithDeviceNameInFileName (const std::string & fName)
std::string ReplaceWithLargeInFileName (const std::string & fName)
std::string ReplaceWithLargeInFileNameAndOSSpecific (const std::string & fName)
bool SaveToFile (float num, FILE * fp)
Definition at line 53 of file ResourceUtils.cpp.
bool SaveToFile (int num, FILE * fp)
Definition at line 41 of file ResourceUtils.cpp.
bool SaveToFile (uint32 num, FILE * fp)
Definition at line 47 of file ResourceUtils.cpp.
bool SaveToFile (const std::string & str, FILE * fp)
bool SeparateString (const char str[], int num, char delimiter, char * return1)
Definition at line 398 of file ResourceUtils.cpp.
Referenced by SeparateStringSTL().
std::string SeparateStringSTL (std::string input, int index, char delimiter)
bool StringFromEndMatches (const std::string & line, const std::string textToMatch)
Definition at line 579 of file ResourceUtils.cpp.
bool StringFromStartMatches (const std::string & line, const std::string textToMatch)
Definition at line 569 of file ResourceUtils.cpp.
Referenced by VariantDB::AddVarPointersToVector(), and Entity::RemoveEntitiesByNameThatStartWith().
void StringReplace (const std::string & what, const std::string & with, std::string & in)
Definition at line 426 of file ResourceUtils.cpp.
std::string StripColorCodes (const std::string text)
Definition at line 548 of file ResourceUtils.cpp.
byte* zlibDeflateToMemory (byte * pInput, int sizeBytes, int * pSizeCompressedOut)
Definition at line 264 of file ResourceUtils.cpp.
Referenced by CompressFile().
byte* zLibInflateToMemory (byte * pInput, unsigned int compressedSize, unsigned int decompressedSize)
Definition at line 299 of file ResourceUtils.cpp.
References void().
Referenced by DecompressRTPackToMemory().