Proton: rtRect Struct Reference
rtRect Struct Reference
#include <rtRect.h>
Public Member Functions
rtRect ()
rtRect (int l, int t, int r, int b)
void Clear ()
int GetHeight () const
int GetWidth () const
void ScaleCentered (float f)
void AdjustPosition (int x, int y)
void Inflate (int x, int y)
Public Attributes
int left
int top
int right
int bottom
Detailed Description
Definition at line 28 of file rtRect.h.
Constructor & Destructor Documentation
rtRect::rtRect ()
Definition at line 18 of file rtRect.cpp.
rtRect::rtRect (int l, int t, int r, int b) [inline]
Definition at line 31 of file rtRect.h.
Member Function Documentation
void rtRect::AdjustPosition (int x, int y)
Definition at line 23 of file rtRect.cpp.
Referenced by AdManager::OnRender().
void rtRect::Clear () [inline]
Definition at line 33 of file rtRect.h.
int rtRect::GetHeight () const [inline]
Definition at line 34 of file rtRect.h.
References top.
Referenced by DrawFilledRect(), DrawRect(), RTFont::DrawWrapped(), AdManager::OnRender(), ScaleCentered(), and Surface::UpdateSurfaceRect().
int rtRect::GetWidth () const [inline]
Definition at line 35 of file rtRect.h.
References left.
Referenced by DrawFilledRect(), DrawRect(), RTFont::DrawWrapped(), AdManager::OnRender(), ScaleCentered(), and Surface::UpdateSurfaceRect().
void rtRect::Inflate (int x, int y)
Definition at line 31 of file rtRect.cpp.
void rtRect::ScaleCentered (float f)
Definition at line 5 of file rtRect.cpp.
References GetHeight(), and GetWidth().
Member Data Documentation
int rtRect::bottom
Definition at line 31 of file rtRect.h.
Referenced by DrawFilledBitmapRect(), and rtRectf::rtRectf().
int rtRect::left
Definition at line 31 of file rtRect.h.
Referenced by DrawFilledBitmapRect(), DrawFilledRect(), DrawRect(), RTFont::DrawWrapped(), GetWidth(), rtRectf::rtRectf(), and Surface::UpdateSurfaceRect().
int rtRect::right
Definition at line 31 of file rtRect.h.
Referenced by DrawFilledBitmapRect(), and rtRectf::rtRectf().
int rtRect::top
Definition at line 31 of file rtRect.h.
Referenced by DrawFilledBitmapRect(), DrawFilledRect(), DrawRect(), RTFont::DrawWrapped(), GetHeight(), rtRectf::rtRectf(), and Surface::UpdateSurfaceRect().
The documentation for this struct was generated from the following files:
rtRect.h
rtRect.cpp