Proton: Surface.cpp File Reference
Surface.cpp File Reference
Enumerations
enum eBlitMode { BLIT_MODE_NORMAL, BLIT_MODE_ROTATE_LEFT }
Functions
int GetIntFromMemImplementation (byte *pMem)
template<typename T >
T nextPowerOfTwo (T n)
void BlitBmp (int posX, int posY, byte *pDest, int dstX, int dstY, int dstPixelType, byte *pSrc, int srcX, int srcY, int srcPixelType, eBlitMode mode)
string PrintGLColor (glColorBytes color)
Variables
const float C_TEXEL_HACK_AMOUNT = (0)
GLuint g_lastBound = 0
Enumeration Type Documentation
enum eBlitMode
Enumerator:
BLIT_MODE_NORMAL
BLIT_MODE_ROTATE_LEFT
Definition at line 856 of file Surface.cpp.
Function Documentation
void BlitBmp (int posX, int posY, byte * pDest, int dstX, int dstY, int dstPixelType, byte * pSrc, int srcX, int srcY, int srcPixelType, eBlitMode mode)
Definition at line 862 of file Surface.cpp.
int GetIntFromMemImplementation (byte * pMem)
Definition at line 181 of file Surface.cpp.
template<typename T > T nextPowerOfTwo (T n)
Definition at line 825 of file Surface.cpp.
Referenced by Surface::InitBlankSurface(), and Surface::InitFromSoftSurface().
string PrintGLColor (glColorBytes color)
Definition at line 1243 of file Surface.cpp.
References glColorBytes::a, glColorBytes::b, glColorBytes::g, and glColorBytes::r.
Referenced by glDrawArraysEx().
Variable Documentation
const float C_TEXEL_HACK_AMOUNT = (0)
Definition at line 11 of file Surface.cpp.
Referenced by Surface::BlitEx().
GLuint g_lastBound = 0
Definition at line 13 of file Surface.cpp.
Referenced by Surface::Bind(), and IrrlichtManager::EndScene().